insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Medio Ambiente','Środowisko naturalne','el medio ambiente','środowisko naturalne'),
('Medio Ambiente','Środowisko naturalne','la naturaleza','natura'),
('Medio Ambiente','Środowisko naturalne','la ecología','ekologia'),
('Medio Ambiente','Środowisko naturalne','el ecosistema','ekosystem'),
('Medio Ambiente','Środowisko naturalne','la biodiversidad','bioróżnorodność'),
('Medio Ambiente','Środowisko naturalne','la fauna','fauna'),
('Medio Ambiente','Środowisko naturalne','la flora','flora'),
('Medio Ambiente','Środowisko naturalne','el hábitat','siedlisko'),
('Medio Ambiente','Środowisko naturalne','la conservación','ochrona / konserwacja'),
('Medio Ambiente','Środowisko naturalne','proteger','chronić'),
('Medio Ambiente','Środowisko naturalne','la contaminación','zanieczyszczenie'),
('Medio Ambiente','Środowisko naturalne','contaminar','zanieczyszczać'),
('Medio Ambiente','Środowisko naturalne','la polución','smog / zanieczyszczenie (powietrza)'),
('Medio Ambiente','Środowisko naturalne','el calentamiento global','globalne ocieplenie'),
('Medio Ambiente','Środowisko naturalne','el cambio climático','zmiana klimatu'),
('Medio Ambiente','Środowisko naturalne','el efecto invernadero','efekt cieplarniany'),
('Medio Ambiente','Środowisko naturalne','la emisión de gases','emisja gazów'),
('Medio Ambiente','Środowisko naturalne','el dióxido de carbono','dwutlenek węgla'),
('Medio Ambiente','Środowisko naturalne','la huella de carbono','ślad węglowy'),
('Medio Ambiente','Środowisko naturalne','la capa de ozono','warstwa ozonowa'),
('Medio Ambiente','Środowisko naturalne','la deforestación','wylesianie'),
('Medio Ambiente','Środowisko naturalne','la tala de árboles','wycinka drzew'),
('Medio Ambiente','Środowisko naturalne','los recursos naturales','zasoby naturalne'),
('Medio Ambiente','Środowisko naturalne','la energía renovable','energia odnawialna'),
('Medio Ambiente','Środowisko naturalne','la energía solar','energia słoneczna'),
('Medio Ambiente','Środowisko naturalne','la energía eólica','energia wiatrowa'),
('Medio Ambiente','Środowisko naturalne','la energía nuclear','energia jądrowa'),
('Medio Ambiente','Środowisko naturalne','sostenible','zrównoważony'),
('Medio Ambiente','Środowisko naturalne','la sostenibilidad','zrównoważony rozwój'),
('Medio Ambiente','Środowisko naturalne','el ecologista','ekolog'),
('Medio Ambiente','Środowisko naturalne','verde','zielony / ekologiczny'),
('Medio Ambiente','Środowisko naturalne','la basura','śmieci'),
('Medio Ambiente','Środowisko naturalne','el residuo / el desecho','odpad / resztka'),
('Medio Ambiente','Środowisko naturalne','el vertedero','wysypisko śmieci'),
('Medio Ambiente','Środowisko naturalne','tóxico','toksyczny'),
('Medio Ambiente','Środowisko naturalne','el pesticida','pestycyd'),
('Medio Ambiente','Środowisko naturalne','en peligro de extinción','zagrożony wyginięciem'),
('Medio Ambiente','Środowisko naturalne','la extinción','wyginięcie'),
('Medio Ambiente','Środowisko naturalne','la sobreexplotación','nadmierna eksploatacja'),
('Medio Ambiente','Środowisko naturalne','el agua potable','woda pitna'),
('Medio Ambiente','Środowisko naturalne','purificar','oczyszczać'),
('Medio Ambiente','Środowisko naturalne','el aire puro','czyste powietrze'),
('Medio Ambiente','Środowisko naturalne','la reserva natural','rezerwat przyrody'),
('Medio Ambiente','Środowisko naturalne','el parque nacional','park narodowy'),
('Medio Ambiente','Środowisko naturalne','la biosfera','biosfera'),
('Medio Ambiente','Środowisko naturalne','la degradación','degradacja'),
('Medio Ambiente','Środowisko naturalne','el impacto ambiental','wpływ na środowisko'),
('Medio Ambiente','Środowisko naturalne','la concienciación','budowanie świadomości'),
('Medio Ambiente','Środowisko naturalne','concienciar','uświadamiać'),
('Medio Ambiente','Środowisko naturalne','preservar','zachowywać / chronić'),
('Reciclaje','Recykling','el reciclaje','recykling'),
('Reciclaje','Recykling','reciclar','przetwarzać / poddawać recyklingowi'),
('Reciclaje','Recykling','reutilizar','używać ponownie'),
('Reciclaje','Recykling','reducir','redukować / zmniejszać'),
('Reciclaje','Recykling','el contenedor','kontener / pojemnik'),
('Reciclaje','Recykling','la basura','śmieci'),
('Reciclaje','Recykling','la papelera','kosz na śmieci'),
('Reciclaje','Recykling','el cubo de basura','wiaderko na śmieci'),
('Reciclaje','Recykling','la separación de residuos','segregacja odpadów'),
('Reciclaje','Recykling','separar','segregować / oddzielać'),
('Reciclaje','Recykling','clasificar','klasyfikować / sortować'),
('Reciclaje','Recykling','el residuo','odpad'),
('Reciclaje','Recykling','el desecho','odpadek'),
('Reciclaje','Recykling','orgánico','organiczny'),
('Reciclaje','Recykling','inorgánico','nieorganiczny'),
('Reciclaje','Recykling','el plástico','plastik'),
('Reciclaje','Recykling','el vidrio','szkło (np. butelki)'),
('Reciclaje','Recykling','el cartón','karton'),
('Reciclaje','Recykling','el papel','papier'),
('Reciclaje','Recykling','el envase','opakowanie / pojemnik'),
('Reciclaje','Recykling','el envoltorio','opakowanie / papierek'),
('Reciclaje','Recykling','la lata','puszka'),
('Reciclaje','Recykling','la botella','butelka'),
('Reciclaje','Recykling','el metal','metal'),
('Reciclaje','Recykling','el aluminio','aluminium'),
('Reciclaje','Recykling','la pila','bateria (np. paluszek)'),
('Reciclaje','Recykling','la batería','bateria / akumulator'),
('Reciclaje','Recykling','la chatarra','złom'),
('Reciclaje','Recykling','el escombro','gruz / śmieci budowlane'),
('Reciclaje','Recykling','el punto limpio / el ecopunto','punkt zbiórki odpadów (PSZOK)'),
('Reciclaje','Recykling','la planta de reciclaje','zakład recyklingu'),
('Reciclaje','Recykling','la bolsa de plástico','torba foliowa / reklamówka'),
('Reciclaje','Recykling','la bolsa de tela','torba materiałowa'),
('Reciclaje','Recykling','biodegradable','biodegradowalny'),
('Reciclaje','Recykling','el compost','kompost'),
('Reciclaje','Recykling','el abono','nawóz'),
('Reciclaje','Recykling','ecológico','ekologiczny'),
('Reciclaje','Recykling','el desperdicio','marnotrawstwo / odpad'),
('Reciclaje','Recykling','desperdiciar','marnować'),
('Reciclaje','Recykling','tirar (a la basura)','wyrzucać (do śmieci)'),
('Reciclaje','Recykling','recoger','zbierać'),
('Reciclaje','Recykling','el material reciclado','materiał z recyklingu'),
('Reciclaje','Recykling','el embalaje','opakowanie (transportowe)'),
('Reciclaje','Recykling','contaminante','zanieczyszczający (substancja)'),
('Reciclaje','Recykling','verter','wylewać / wyrzucać na wysypisko'),
('Reciclaje','Recykling','el vertedero','wysypisko śmieci'),
('Reciclaje','Recykling','el residuo tóxico','odpad toksyczny'),
('Reciclaje','Recykling','la economía circular','gospodarka obiegu zamkniętego'),
('Reciclaje','Recykling','cero residuos (zero waste)','zero odpadów'),
('Reciclaje','Recykling','recuperar','odzyskiwać'),
('El Universo','Wszechświat','el universo','wszechświat'),
('El Universo','Wszechświat','el cosmos','kosmos'),
('El Universo','Wszechświat','el espacio exterior','przestrzeń kosmiczna'),
('El Universo','Wszechświat','la galaxia','galaktyka'),
('El Universo','Wszechświat','la Vía Láctea','Droga Mleczna'),
('El Universo','Wszechświat','el sistema solar','układ słoneczny'),
('El Universo','Wszechświat','la estrella','gwiazda'),
('El Universo','Wszechświat','el planeta','planeta'),
('El Universo','Wszechświat','la órbita','orbita'),
('El Universo','Wszechświat','orbitar','krążyć po orbicie'),
('El Universo','Wszechświat','la luna','księżyc'),
('El Universo','Wszechświat','el satélite natural','naturalny satelita'),
('El Universo','Wszechświat','el sol','słońce'),
('El Universo','Wszechświat','el asteroide','asteroida'),
('El Universo','Wszechświat','el cometa','kometa'),
('El Universo','Wszechświat','el meteorito','meteoryt'),
('El Universo','Wszechświat','el meteoro / la estrella fugaz','meteor / spadająca gwiazda'),
('El Universo','Wszechświat','la gravedad','grawitacja'),
('El Universo','Wszechświat','el agujero negro','czarna dziura'),
('El Universo','Wszechświat','la nebulosa','mgławica'),
('El Universo','Wszechświat','la constelación','konstelacja'),
('El Universo','Wszechświat','el año luz','rok świetlny'),
('El Universo','Wszechświat','la velocidad de la luz','prędkość światła'),
('El Universo','Wszechświat','el telescopio','teleskop'),
('El Universo','Wszechświat','el observatorio','obserwatorium'),
('El Universo','Wszechświat','la nave espacial','statek kosmiczny'),
('El Universo','Wszechświat','el cohete','rakieta'),
('El Universo','Wszechświat','el transbordador espacial','prom kosmiczny'),
('El Universo','Wszechświat','la estación espacial','stacja kosmiczna'),
('El Universo','Wszechświat','la sonda','sonda (kosmiczna)'),
('El Universo','Wszechświat','el astronauta','astronauta'),
('El Universo','Wszechświat','el cosmonauta','kosmonauta'),
('El Universo','Wszechświat','el traje espacial','skafander kosmiczny'),
('El Universo','Wszechświat','la gravedad cero','stan nieważkości'),
('El Universo','Wszechświat','la exploración espacial','eksploracja kosmosu'),
('El Universo','Wszechświat','el lanzamiento','start (rakiety)'),
('El Universo','Wszechświat','aterrizar','lądować'),
('El Universo','Wszechświat','alunizar','lądować na księżycu'),
('El Universo','Wszechświat','la órbita terrestre','orbita okołoziemska'),
('El Universo','Wszechświat','el extraterrestre','kosmita'),
('El Universo','Wszechświat','el ovni','UFO'),
('El Universo','Wszechświat','el alienígena','obcy / kosmita'),
('El Universo','Wszechświat','el cielo','niebo'),
('El Universo','Wszechświat','el vacío','próżnia'),
('El Universo','Wszechświat','el Big Bang','Wielki Wybuch'),
('El Universo','Wszechświat','la materia oscura','ciemna materia'),
('El Universo','Wszechświat','la supernova','supernowa'),
('El Universo','Wszechświat','el eclipse solar','zaćmienie słońca'),
('El Universo','Wszechświat','el eclipse lunar','zaćmienie księżyca'),
('El Universo','Wszechświat','el polvo cósmico','pył kosmiczny'),
('Planetas','Planety','el planeta','planeta'),
('Planetas','Planety','Mercurio','Merkury'),
('Planetas','Planety','Venus','Wenus'),
('Planetas','Planety','la Tierra','Ziemia'),
('Planetas','Planety','Marte','Mars'),
('Planetas','Planety','Júpiter','Jowisz'),
('Planetas','Planety','Saturno','Saturn'),
('Planetas','Planety','Urano','Uran'),
('Planetas','Planety','Neptuno','Neptun'),
('Planetas','Planety','Plutón','Pluton'),
('Planetas','Planety','el planeta enano','planeta karłowata'),
('Planetas','Planety','el exoplaneta','egzoplaneta'),
('Planetas','Planety','la órbita','orbita'),
('Planetas','Planety','el satélite natural','naturalny satelita'),
('Planetas','Planety','la luna','księżyc'),
('Planetas','Planety','el sistema solar','układ słoneczny'),
('Planetas','Planety','el sol','słońce'),
('Planetas','Planety','la estrella','gwiazda'),
('Planetas','Planety','el anillo','pierścień (np. Saturna)'),
('Planetas','Planety','el gas','gaz'),
('Planetas','Planety','la roca','skała'),
('Planetas','Planety','el cráter','krater'),
('Planetas','Planety','la superficie','powierzchnia'),
('Planetas','Planety','la atmósfera','atmosfera'),
('Planetas','Planety','la gravedad','grawitacja'),
('Planetas','Planety','la rotación','rotacja / obrót'),
('Planetas','Planety','la traslación','ruch obiegowy'),
('Planetas','Planety','el ecuador','równik'),
('Planetas','Planety','el hemisferio','półkula'),
('Planetas','Planety','el polo','biegun'),
('Planetas','Planety','el telescopio','teleskop'),
('Planetas','Planety','la sonda espacial','sonda kosmiczna'),
('Planetas','Planety','el rover','łazik'),
('Planetas','Planety','el satélite','satelita'),
('Planetas','Planety','la exploración','eksploracja'),
('Planetas','Planety','descubrir','odkrywać'),
('Planetas','Planety','rocoso','skalisty'),
('Planetas','Planety','gaseoso','gazowy'),
('Planetas','Planety','el gigante gaseoso','gazowy olbrzym'),
('Planetas','Planety','el núcleo','jądro'),
('Planetas','Planety','la corteza','skorupa'),
('Planetas','Planety','el manto','płaszcz'),
('Planetas','Planety','el campo magnético','pole magnetyczne'),
('Planetas','Planety','el día solar','dzień słoneczny'),
('Planetas','Planety','el año luz','rok świetlny'),
('Planetas','Planety','la temperatura','temperatura'),
('Planetas','Planety','el hielo','lód'),
('Planetas','Planety','la vida extraterrestre','życie pozaziemskie'),
('Planetas','Planety','el espacio','kosmos / przestrzeń'),
('Planetas','Planety','el vacío','próżnia'),
('Vehículos','Pojazdy','el vehículo','pojazd'),
('Vehículos','Pojazdy','el coche','samochód'),
('Vehículos','Pojazdy','el automóvil','samochód (formalnie)'),
('Vehículos','Pojazdy','el autobús','autobus'),
('Vehículos','Pojazdy','el autocar','autokar'),
('Vehículos','Pojazdy','el camión','ciężarówka'),
('Vehículos','Pojazdy','la furgoneta','furgonetka / van'),
('Vehículos','Pojazdy','la camioneta','pick-up'),
('Vehículos','Pojazdy','el tren','pociąg'),
('Vehículos','Pojazdy','el tranvía','tramwaj'),
('Vehículos','Pojazdy','el metro','metro'),
('Vehículos','Pojazdy','el avión','samolot'),
('Vehículos','Pojazdy','el helicóptero','helikopter'),
('Vehículos','Pojazdy','el barco','statek'),
('Vehículos','Pojazdy','el buque','okręt / duży statek'),
('Vehículos','Pojazdy','el ferry','prom'),
('Vehículos','Pojazdy','la lancha','motorówka'),
('Vehículos','Pojazdy','el yate','jacht'),
('Vehículos','Pojazdy','el submarino','łódź podwodna'),
('Vehículos','Pojazdy','la bicicleta','rower'),
('Vehículos','Pojazdy','la motocicleta / la moto','motocykl'),
('Vehículos','Pojazdy','el ciclomotor','motorower'),
('Vehículos','Pojazdy','el patinete','hulajnoga'),
('Vehículos','Pojazdy','el patinete eléctrico','hulajnoga elektryczna'),
('Vehículos','Pojazdy','el monopatín','deskorolka'),
('Vehículos','Pojazdy','el tractor','traktor'),
('Vehículos','Pojazdy','la excavadora','koparka'),
('Vehículos','Pojazdy','la ambulancia','ambulans / karetka'),
('Vehículos','Pojazdy','el coche de policía','radiowóz'),
('Vehículos','Pojazdy','el camión de bomberos','wóz strażacki'),
('Vehículos','Pojazdy','el taxi','taksówka'),
('Vehículos','Pojazdy','el carro','wóz / bryczka'),
('Vehículos','Pojazdy','el trineo','sanie / sanki'),
('Vehículos','Pojazdy','el globo aerostático','balon na ogrzane powietrze'),
('Vehículos','Pojazdy','el teleférico','kolejka linowa'),
('Vehículos','Pojazdy','el funicular','kolejka linowo-terenowa'),
('Vehículos','Pojazdy','el cohete','rakieta'),
('Vehículos','Pojazdy','la nave espacial','statek kosmiczny'),
('Vehículos','Pojazdy','el triciclo','rower trójkołowy'),
('Vehículos','Pojazdy','el remolque','przyczepa'),
('Vehículos','Pojazdy','la caravana','przyczepa kempingowa'),
('Vehículos','Pojazdy','la autocaravana','kamper'),
('Vehículos','Pojazdy','el vehículo todoterreno','samochód terenowy (4x4)'),
('Vehículos','Pojazdy','el quad','quad'),
('Vehículos','Pojazdy','el transporte público','transport publiczny'),
('Vehículos','Pojazdy','el transporte privado','transport prywatny'),
('Vehículos','Pojazdy','el velero','żaglówka'),
('Vehículos','Pojazdy','el bote','łódka'),
('Vehículos','Pojazdy','el coche deportivo','samochód sportowy'),
('Vehículos','Pojazdy','el crucero','statek wycieczkowy'),
('Partes de un Coche','Części samochodu','el motor','silnik'),
('Partes de un Coche','Części samochodu','el volante','kierownica'),
('Partes de un Coche','Części samochodu','la rueda','koło'),
('Partes de un Coche','Części samochodu','el neumático','opona'),
('Partes de un Coche','Części samochodu','el freno','hamulec'),
('Partes de un Coche','Części samochodu','el acelerador','pedał gazu'),
('Partes de un Coche','Części samochodu','el embrague','sprzęgło'),
('Partes de un Coche','Części samochodu','la marcha','bieg'),
('Partes de un Coche','Części samochodu','la caja de cambios','skrzynia biegów'),
('Partes de un Coche','Części samochodu','el parachoques','zderzak'),
('Partes de un Coche','Części samochodu','el capó','maska'),
('Partes de un Coche','Części samochodu','el maletero','bagażnik'),
('Partes de un Coche','Części samochodu','el parabrisas','szyba przednia'),
('Partes de un Coche','Części samochodu','el limpiaparabrisas','wycieraczka'),
('Partes de un Coche','Części samochodu','la ventanilla','szyba (w oknie)'),
('Partes de un Coche','Części samochodu','el espejo retrovisor','lusterko wsteczne'),
('Partes de un Coche','Części samochodu','el espejo lateral','lusterko boczne'),
('Partes de un Coche','Części samochodu','el faro','reflektor'),
('Partes de un Coche','Części samochodu','la luz intermitente','kierunkowskaz'),
('Partes de un Coche','Części samochodu','la matrícula','tablica rejestracyjna'),
('Partes de un Coche','Części samochodu','el tubo de escape','rura wydechowa'),
('Partes de un Coche','Części samochodu','la bocina / el claxon','klakson'),
('Partes de un Coche','Części samochodu','el asiento','siedzenie'),
('Partes de un Coche','Części samochodu','el cinturón de seguridad','pas bezpieczeństwa'),
('Partes de un Coche','Części samochodu','el airbag','poduszka powietrzna'),
('Partes de un Coche','Części samochodu','el salpicadero','deska rozdzielcza'),
('Partes de un Coche','Części samochodu','el velocímetro','prędkościomierz'),
('Partes de un Coche','Części samochodu','el depósito de gasolina','bak paliwa'),
('Partes de un Coche','Części samochodu','la batería','akumulator'),
('Partes de un Coche','Części samochodu','la bujía','świeca zapłonowa'),
('Partes de un Coche','Części samochodu','el radiador','chłodnica'),
('Partes de un Coche','Części samochodu','la suspensión','zawieszenie'),
('Partes de un Coche','Części samochodu','el amortiguador','amortyzator'),
('Partes de un Coche','Części samochodu','el eje','oś'),
('Partes de un Coche','Części samochodu','la puerta','drzwi'),
('Partes de un Coche','Części samochodu','la manilla','klamka'),
('Partes de un Coche','Części samochodu','la cerradura','zamek (w drzwiach)'),
('Partes de un Coche','Części samochodu','la llave','kluczyk'),
('Partes de un Coche','Części samochodu','el pedal','pedał'),
('Partes de un Coche','Części samochodu','la palanca de cambios','dźwignia zmiany biegów'),
('Partes de un Coche','Części samochodu','el freno de mano','hamulec ręczny'),
('Partes de un Coche','Części samochodu','el asiento trasero','tylne siedzenie'),
('Partes de un Coche','Części samochodu','el techo','dach'),
('Partes de un Coche','Części samochodu','la antena','antena'),
('Partes de un Coche','Części samochodu','el tapacubos','kołpak'),
('Partes de un Coche','Części samochodu','el chasis','podwozie / rama'),
('Partes de un Coche','Części samochodu','la guantera','schowek (przed pasażerem)'),
('Partes de un Coche','Części samochodu','el reposacabezas','zagłówek'),
('Partes de un Coche','Części samochodu','el cuentakilómetros','licznik przebiegu'),
('Partes de un Coche','Części samochodu','el maletero de techo','bagażnik dachowy'),
('Tráfico','Ruch drogowy','el tráfico','ruch drogowy'),
('Tráfico','Ruch drogowy','la circulación','ruch / obieg'),
('Tráfico','Ruch drogowy','el atasco','korek drogowy'),
('Tráfico','Ruch drogowy','la calle','ulica'),
('Tráfico','Ruch drogowy','la carretera','droga / szosa'),
('Tráfico','Ruch drogowy','la autopista','autostrada'),
('Tráfico','Ruch drogowy','la autovía','droga ekspresowa'),
('Tráfico','Ruch drogowy','el carril','pas ruchu'),
('Tráfico','Ruch drogowy','el carril bici','ścieżka rowerowa'),
('Tráfico','Ruch drogowy','la acera','chodnik'),
('Tráfico','Ruch drogowy','el cruce','skrzyżowanie'),
('Tráfico','Ruch drogowy','la rotonda','rondo'),
('Tráfico','Ruch drogowy','el semáforo','sygnalizacja świetlna'),
('Tráfico','Ruch drogowy','el paso de cebra','przejście dla pieszych'),
('Tráfico','Ruch drogowy','la señal de tráfico','znak drogowy'),
('Tráfico','Ruch drogowy','el límite de velocidad','ograniczenie prędkości'),
('Tráfico','Ruch drogowy','la velocidad','prędkość'),
('Tráfico','Ruch drogowy','el peatón','pieszy'),
('Tráfico','Ruch drogowy','el conductor','kierowca'),
('Tráfico','Ruch drogowy','el ciclista','rowerzysta'),
('Tráfico','Ruch drogowy','el pasajero','pasażer'),
('Tráfico','Ruch drogowy','el accidente','wypadek'),
('Tráfico','Ruch drogowy','el choque','zderzenie'),
('Tráfico','Ruch drogowy','atropellar','potrącić'),
('Tráfico','Ruch drogowy','la multa','mandat'),
('Tráfico','Ruch drogowy','el peaje','myto / bramki na autostradzie'),
('Tráfico','Ruch drogowy','el aparcamiento','parking'),
('Tráfico','Ruch drogowy','aparcar','parkować'),
('Tráfico','Ruch drogowy','la grúa','laweta'),
('Tráfico','Ruch drogowy','el policía de tráfico','policjant drogówki'),
('Tráfico','Ruch drogowy','la infracción','wykroczenie'),
('Tráfico','Ruch drogowy','el carnet de conducir','prawo jazdy'),
('Tráfico','Ruch drogowy','el sentido','kierunek ruchu'),
('Tráfico','Ruch drogowy','la dirección','kierunek / adres'),
('Tráfico','Ruch drogowy','la ruta','trasa'),
('Tráfico','Ruch drogowy','el desvío','objazd'),
('Tráfico','Ruch drogowy','la curva','zakręt'),
('Tráfico','Ruch drogowy','adelantar','wyprzedzać'),
('Tráfico','Ruch drogowy','frenar','hamować'),
('Tráfico','Ruch drogowy','acelerar','przyspieszać'),
('Tráfico','Ruch drogowy','ceder el paso','ustąpić pierwszeństwa'),
('Tráfico','Ruch drogowy','la prioridad','pierwszeństwo'),
('Tráfico','Ruch drogowy','la señal de stop','znak stop'),
('Tráfico','Ruch drogowy','el peligro','niebezpieczeństwo'),
('Tráfico','Ruch drogowy','el badén','próg zwalniający'),
('Tráfico','Ruch drogowy','la zona peatonal','strefa dla pieszych'),
('Tráfico','Ruch drogowy','el puente','most'),
('Tráfico','Ruch drogowy','el túnel','tunel'),
('Tráfico','Ruch drogowy','el viandante','przechodzień'),
('Tráfico','Ruch drogowy','la calzada','jezdnia'),
('En el Tren','W pociągu','el tren','pociąg'),
('En el Tren','W pociągu','la estación de tren','stacja kolejowa'),
('En el Tren','W pociągu','el andén','peron'),
('En el Tren','W pociągu','la vía','tor'),
('En el Tren','W pociągu','el billete','bilet'),
('En el Tren','W pociągu','el billete de ida','bilet w jedną stronę'),
('En el Tren','W pociągu','el billete de ida y vuelta','bilet w obie strony'),
('En el Tren','W pociągu','la taquilla','kasa biletowa'),
('En el Tren','W pociągu','la máquina expendedora','automat biletowy'),
('En el Tren','W pociągu','el horario','rozkład jazdy'),
('En el Tren','W pociągu','la pantalla','tablica odjazdów / ekran'),
('En el Tren','W pociągu','el destino','miejsce docelowe'),
('En el Tren','W pociągu','la salida','odjazd'),
('En el Tren','W pociągu','la llegada','przyjazd'),
('En el Tren','W pociągu','el retraso','opóźnienie'),
('En el Tren','W pociągu','el pasajero','pasażer'),
('En el Tren','W pociągu','el revisor','konduktor / rewizor'),
('En el Tren','W pociągu','el maquinista','maszynista'),
('En el Tren','W pociągu','el vagón','wagon'),
('En el Tren','W pociągu','el coche cama','wagon sypialny'),
('En el Tren','W pociągu','el coche comedor','wagon restauracyjny'),
('En el Tren','W pociągu','el asiento','siedzenie'),
('En el Tren','W pociągu','la ventanilla','okno (w pociągu)'),
('En el Tren','W pociągu','el pasillo','korytarz'),
('En el Tren','W pociągu','el portaequipajes','półka na bagaż'),
('En el Tren','W pociągu','la maleta','walizka'),
('En el Tren','W pociągu','el transbordo','przesiadka'),
('En el Tren','W pociągu','hacer transbordo','przesiadać się'),
('En el Tren','W pociągu','directo','bezpośredni (pociąg)'),
('En el Tren','W pociągu','el tren de alta velocidad','pociąg dużych prędkości'),
('En el Tren','W pociągu','el tren de cercanías','pociąg podmiejski'),
('En el Tren','W pociągu','el metro','metro'),
('En el Tren','W pociągu','el tranvía','tramwaj'),
('En el Tren','W pociągu','el silbato','gwizdek'),
('En el Tren','W pociągu','subir','wsiadać'),
('En el Tren','W pociągu','bajar','wysiadać'),
('En el Tren','W pociągu','reservar','rezerwować'),
('En el Tren','W pociągu','la reserva','rezerwacja'),
('En el Tren','W pociągu','el número de asiento','numer siedzenia'),
('En el Tren','W pociągu','el coche de pasajeros','wagon pasażerski'),
('En el Tren','W pociągu','la primera clase','pierwsza klasa'),
('En el Tren','W pociągu','la segunda clase','druga klasa'),
('En el Tren','W pociągu','el descuento','zniżka'),
('En el Tren','W pociągu','validar','kasować / zatwierdzać (bilet)'),
('En el Tren','W pociągu','la consigna','przechowalnia bagażu'),
('En el Tren','W pociągu','viajar','podróżować'),
('En el Tren','W pociągu','el viaje','podróż'),
('En el Tren','W pociągu','puntual','punktualny'),
('En el Tren','W pociągu','el equipaje','bagaż'),
('En el Tren','W pociągu','la estación de término','stacja końcowa'),
('En el Barco','Na statku','el barco','statek'),
('En el Barco','Na statku','el bote','łódź'),
('En el Barco','Na statku','el velero','żaglówka'),
('En el Barco','Na statku','el crucero','statek wycieczkowy'),
('En el Barco','Na statku','el yate','jacht'),
('En el Barco','Na statku','el ferry','prom'),
('En el Barco','Na statku','la lancha','motorówka'),
('En el Barco','Na statku','la cubierta','pokład'),
('En el Barco','Na statku','el camarote','kajuta / kabina'),
('En el Barco','Na statku','el capitán','kapitan'),
('En el Barco','Na statku','el marinero','marynarz'),
('En el Barco','Na statku','la tripulación','załoga'),
('En el Barco','Na statku','el ancla','kotwica'),
('En el Barco','Na statku','el puerto','port'),
('En el Barco','Na statku','el muelle','molo / pirs'),
('En el Barco','Na statku','zarpar','wypływać (z portu)'),
('En el Barco','Na statku','atracar','cumować'),
('En el Barco','Na statku','navegar','żeglować / pływać'),
('En el Barco','Na statku','naufragar','zatonąć / rozbić się'),
('En el Barco','Na statku','el naufragio','katastrofa morska'),
('En el Barco','Na statku','el chaleco salvavidas','kamizelka ratunkowa'),
('En el Barco','Na statku','el bote salvavidas','szalupa ratunkowa'),
('En el Barco','Na statku','la proa','dziób statku'),
('En el Barco','Na statku','la popa','rufa'),
('En el Barco','Na statku','babor','bakburta (lewa)'),
('En el Barco','Na statku','estribor','sterburta (prawa)'),
('En el Barco','Na statku','el mástil','maszt'),
('En el Barco','Na statku','la vela','żagiel'),
('En el Barco','Na statku','el timón','ster'),
('En el Barco','Na statku','el faro','latarnia morska'),
('En el Barco','Na statku','la ola','fala'),
('En el Barco','Na statku','el mar','morze'),
('En el Barco','Na statku','el océano','ocean'),
('En el Barco','Na statku','marearse','mieć chorobę morską'),
('En el Barco','Na statku','el mareo','choroba morska'),
('En el Barco','Na statku','el pasaje','bilet (na rejs)'),
('En el Barco','Na statku','el pasajero','pasażer'),
('En el Barco','Na statku','el salvavidas','koło ratunkowe / ratownik'),
('En el Barco','Na statku','la brújula','kompas'),
('En el Barco','Na statku','el radar','radar'),
('En el Barco','Na statku','la escotilla','właz'),
('En el Barco','Na statku','la bodega','ładownia'),
('En el Barco','Na statku','hundirse','tonąć'),
('En el Barco','Na statku','flotar','unosić się na wodzie'),
('En el Barco','Na statku','el nudo','węzeł'),
('En el Barco','Na statku','el pirata','pirat'),
('En el Barco','Na statku','el remo','wiosło'),
('En el Barco','Na statku','remar','wiosłować'),
('En el Barco','Na statku','la cuerda','lina'),
('En el Barco','Na statku','la marea','pływ (przypływ/odpływ)'),
('Transporte Público','Transport publiczny','el transporte público','transport publiczny'),
('Transporte Público','Transport publiczny','el autobús','autobus'),
('Transporte Público','Transport publiczny','el autocar','autokar'),
('Transporte Público','Transport publiczny','el tranvía','tramwaj'),
('Transporte Público','Transport publiczny','el metro','metro'),
('Transporte Público','Transport publiczny','el tren','pociąg'),
('Transporte Público','Transport publiczny','el taxi','taksówka'),
('Transporte Público','Transport publiczny','la parada','przystanek'),
('Transporte Público','Transport publiczny','la estación','stacja'),
('Transporte Público','Transport publiczny','la terminal','terminal'),
('Transporte Público','Transport publiczny','el billete / el boleto','bilet'),
('Transporte Público','Transport publiczny','el bono de transporte','bilet okresowy'),
('Transporte Público','Transport publiczny','la tarjeta de transporte','karta miejska'),
('Transporte Público','Transport publiczny','validar','kasować (bilet)'),
('Transporte Público','Transport publiczny','la máquina expendedora','automat biletowy'),
('Transporte Público','Transport publiczny','el revisor','kontroler biletów / rewizor'),
('Transporte Público','Transport publiczny','el conductor','kierowca'),
('Transporte Público','Transport publiczny','el pasajero','pasażer'),
('Transporte Público','Transport publiczny','subir','wsiadać'),
('Transporte Público','Transport publiczny','bajar','wysiadać'),
('Transporte Público','Transport publiczny','hacer transbordo','przesiadać się'),
('Transporte Público','Transport publiczny','la línea','linia'),
('Transporte Público','Transport publiczny','la ruta','trasa'),
('Transporte Público','Transport publiczny','el horario','rozkład jazdy'),
('Transporte Público','Transport publiczny','el retraso','opóźnienie'),
('Transporte Público','Transport publiczny','puntual','punktualny'),
('Transporte Público','Transport publiczny','la marquesina','wiata przystankowa'),
('Transporte Público','Transport publiczny','el asiento','siedzenie'),
('Transporte Público','Transport publiczny','ceder el asiento','ustąpić miejsca'),
('Transporte Público','Transport publiczny','de pie','na stojąco'),
('Transporte Público','Transport publiczny','el timbre','dzwonek'),
('Transporte Público','Transport publiczny','solicitar parada','żądać zatrzymania (przystanek na żądanie)'),
('Transporte Público','Transport publiczny','la hora punta','godzina szczytu'),
('Transporte Público','Transport publiczny','lleno','pełny'),
('Transporte Público','Transport publiczny','vacío','pusty'),
('Transporte Público','Transport publiczny','la tarifa','taryfa / opłata'),
('Transporte Público','Transport publiczny','el descuento','zniżka'),
('Transporte Público','Transport publiczny','la multa','mandat'),
('Transporte Público','Transport publiczny','el andén','peron'),
('Transporte Público','Transport publiczny','la vía','tor'),
('Transporte Público','Transport publiczny','la dirección','kierunek'),
('Transporte Público','Transport publiczny','próximo','następny'),
('Transporte Público','Transport publiczny','la parada de taxis','postój taksówek'),
('Transporte Público','Transport publiczny','el taxímetro','taksometr'),
('Transporte Público','Transport publiczny','la parada a petición','przystanek na żądanie'),
('Transporte Público','Transport publiczny','moverse','poruszać się'),
('Transporte Público','Transport publiczny','viajar','podróżować'),
('Transporte Público','Transport publiczny','el abono mensual','bilet miesięczny'),
('Transporte Público','Transport publiczny','la conexión','połączenie'),
('Transporte Público','Transport publiczny','el trayecto','przejazd / odcinek trasy'),
('Medicina','Medycyna','la medicina','medycyna / lek'),
('Medicina','Medycyna','el médico / la médica','lekarz'),
('Medicina','Medycyna','el doctor / la doctora','doktor'),
('Medicina','Medycyna','el enfermero / la enfermera','pielęgniarz/pielęgniarka'),
('Medicina','Medycyna','el paciente','pacjent'),
('Medicina','Medycyna','la salud','zdrowie'),
('Medicina','Medycyna','la enfermedad','choroba'),
('Medicina','Medycyna','el diagnóstico','diagnoza'),
('Medicina','Medycyna','diagnosticar','diagnozować'),
('Medicina','Medycyna','el tratamiento','leczenie / kuracja'),
('Medicina','Medycyna','tratar','leczyć'),
('Medicina','Medycyna','curar','uzdrawiać / wyleczyć'),
('Medicina','Medycyna','la cura','lekarstwo / wyleczenie'),
('Medicina','Medycyna','prevenir','zapobiegać'),
('Medicina','Medycyna','la prevención','profilaktyka'),
('Medicina','Medycyna','el síntoma','objaw'),
('Medicina','Medycyna','la consulta','wizyta lekarska'),
('Medicina','Medycyna','el consultorio','przychodnia / gabinet'),
('Medicina','Medycyna','examinar','badać'),
('Medicina','Medycyna','el examen médico','badanie lekarskie'),
('Medicina','Medycyna','la presión arterial','ciśnienie krwi'),
('Medicina','Medycyna','el pulso','puls'),
('Medicina','Medycyna','tomar el pulso','mierzyć puls'),
('Medicina','Medycyna','el termómetro','termometr'),
('Medicina','Medycyna','la temperatura','temperatura'),
('Medicina','Medycyna','la fiebre','gorączka'),
('Medicina','Medycyna','la inyección','zastrzyk'),
('Medicina','Medycyna','la vacuna','szczepionka'),
('Medicina','Medycyna','vacunar','szczepić'),
('Medicina','Medycyna','la operación','operacja'),
('Medicina','Medycyna','operar','operować'),
('Medicina','Medycyna','el cirujano','chirurg'),
('Medicina','Medycyna','la receta','recepta'),
('Medicina','Medycyna','recetar','przepisywać lek'),
('Medicina','Medycyna','la pastilla','tabletka'),
('Medicina','Medycyna','el jarabe','syrop'),
('Medicina','Medycyna','la sangre','krew'),
('Medicina','Medycyna','el análisis de sangre','badanie krwi'),
('Medicina','Medycyna','la radiografía','rentgen (zdjęcie)'),
('Medicina','Medycyna','el dolor','ból'),
('Medicina','Medycyna','doler','boleć'),
('Medicina','Medycyna','el especialista','specjalista'),
('Medicina','Medycyna','el pediatra','pediatra'),
('Medicina','Medycyna','el cardiólogo','kardiolog'),
('Medicina','Medycyna','el dentista','dentysta'),
('Medicina','Medycyna','el psicólogo','psycholog'),
('Medicina','Medycyna','el psiquiatra','psychiatra'),
('Medicina','Medycyna','la terapia','terapia'),
('Medicina','Medycyna','recuperarse','wracać do zdrowia'),
('Medicina','Medycyna','la recuperación','rekonwalescencja'),
('En la Farmacia','W aptece','la farmacia','apteka'),
('En la Farmacia','W aptece','el farmacéutico','farmaceuta'),
('En la Farmacia','W aptece','el medicamento','lekarstwo'),
('En la Farmacia','W aptece','la medicina','lek'),
('En la Farmacia','W aptece','la pastilla / la píldora','tabletka / pigułka'),
('En la Farmacia','W aptece','la cápsula','kapsułka'),
('En la Farmacia','W aptece','el jarabe','syrop'),
('En la Farmacia','W aptece','la pomada / la crema','maść / krem'),
('En la Farmacia','W aptece','el gel','żel'),
('En la Farmacia','W aptece','las gotas','krople'),
('En la Farmacia','W aptece','el supositorio','czopek'),
('En la Farmacia','W aptece','el antibiótico','antybiotyk'),
('En la Farmacia','W aptece','el analgésico','środek przeciwbólowy'),
('En la Farmacia','W aptece','el antiinflamatorio','lek przeciwzapalny'),
('En la Farmacia','W aptece','la aspirina','aspiryna'),
('En la Farmacia','W aptece','el paracetamol','paracetamol'),
('En la Farmacia','W aptece','el ibuprofeno','ibuprofen'),
('En la Farmacia','W aptece','el jarabe para la tos','syrop na kaszel'),
('En la Farmacia','W aptece','las vitaminas','witaminy'),
('En la Farmacia','W aptece','la receta médica','recepta lekarska'),
('En la Farmacia','W aptece','el prospecto','ulotka (dołączona do leku)'),
('En la Farmacia','W aptece','la dosis','dawka'),
('En la Farmacia','W aptece','los efectos secundarios','skutki uboczne'),
('En la Farmacia','W aptece','la fecha de caducidad','data ważności'),
('En la Farmacia','W aptece','caducado','przeterminowany'),
('En la Farmacia','W aptece','la tirita / la curita','plaster'),
('En la Farmacia','W aptece','el vendaje / la venda','bandaż'),
('En la Farmacia','W aptece','el algodón','wata'),
('En la Farmacia','W aptece','el alcohol','spirytus salicylowy'),
('En la Farmacia','W aptece','el agua oxigenada','woda utleniona'),
('En la Farmacia','W aptece','el desinfectante','środek dezynfekujący'),
('En la Farmacia','W aptece','la jeringa','strzykawka'),
('En la Farmacia','W aptece','la aguja','igła'),
('En la Farmacia','W aptece','el termómetro','termometr'),
('En la Farmacia','W aptece','el preservativo','prezerwatywa'),
('En la Farmacia','W aptece','la prueba de embarazo','test ciążowy'),
('En la Farmacia','W aptece','el colirio','krople do oczu'),
('En la Farmacia','W aptece','el botiquín','apteczka'),
('En la Farmacia','W aptece','aliviar','przynosić ulgę / łagodzić'),
('En la Farmacia','W aptece','chupar','ssać (np. tabletkę)'),
('En la Farmacia','W aptece','tragar','połykać'),
('En la Farmacia','W aptece','aplicar','nakładać / aplikować'),
('En la Farmacia','W aptece','la alergia','alergia'),
('En la Farmacia','W aptece','el antihistamínico','lek przeciwhistaminowy'),
('En la Farmacia','W aptece','el somnífero','lek nasenny'),
('En la Farmacia','W aptece','la receta electrónica','e-recepta'),
('En la Farmacia','W aptece','de venta libre','bez recepty'),
('En la Farmacia','W aptece','la gasa','gaza'),
('En la Farmacia','W aptece','el esparadrapo','przylepiec / taśma medyczna'),
('En la Farmacia','W aptece','el ungüento','maść (tłusta)'),
('En el Hospital','W szpitalu','el hospital','szpital'),
('En el Hospital','W szpitalu','la clínica','klinika'),
('En el Hospital','W szpitalu','el ambulatorio','przychodnia'),
('En el Hospital','W szpitalu','urgencias','ostry dyżur / SOR'),
('En el Hospital','W szpitalu','la emergencia','nagły wypadek'),
('En el Hospital','W szpitalu','la ambulancia','karetka'),
('En el Hospital','W szpitalu','el paramédico','ratownik medyczny'),
('En el Hospital','W szpitalu','la camilla','nosze'),
('En el Hospital','W szpitalu','la silla de ruedas','wózek inwalidzki'),
('En el Hospital','W szpitalu','la muleta','kula ortopedyczna'),
('En el Hospital','W szpitalu','el bastón','laska'),
('En el Hospital','W szpitalu','la sala de espera','poczekalnia'),
('En el Hospital','W szpitalu','la habitación','sala chorych'),
('En el Hospital','W szpitalu','la cama de hospital','łóżko szpitalne'),
('En el Hospital','W szpitalu','el quirófano','sala operacyjna'),
('En el Hospital','W szpitalu','la operación','operacja'),
('En el Hospital','W szpitalu','la cirugía','chirurgia'),
('En el Hospital','W szpitalu','el cirujano','chirurg'),
('En el Hospital','W szpitalu','el anestesista','anestezjolog'),
('En el Hospital','W szpitalu','la anestesia','znieczulenie / narkoza'),
('En el Hospital','W szpitalu','el oxígeno','tlen'),
('En el Hospital','W szpitalu','la mascarilla','maska tlenowa / maseczka'),
('En el Hospital','W szpitalu','el suero','kroplówka / surowica'),
('En el Hospital','W szpitalu','la vía','wkłucie / wenflon'),
('En el Hospital','W szpitalu','la donación de sangre','oddawanie krwi'),
('En el Hospital','W szpitalu','el donante','dawca'),
('En el Hospital','W szpitalu','la transfusión','transfuzja'),
('En el Hospital','W szpitalu','el escáner','skaner / tomograf'),
('En el Hospital','W szpitalu','la ecografía','USG'),
('En el Hospital','W szpitalu','la resonancia magnética','rezonans magnetyczny'),
('En el Hospital','W szpitalu','el parto','poród'),
('En el Hospital','W szpitalu','dar a luz','rodzić'),
('En el Hospital','W szpitalu','la planta','oddział szpitalny'),
('En el Hospital','W szpitalu','la UCI','OIOM (Oddział Intensywnej Terapii)'),
('En el Hospital','W szpitalu','el alta','wypis (ze szpitala)'),
('En el Hospital','W szpitalu','dar el alta','wypisać ze szpitala'),
('En el Hospital','W szpitalu','ingresar','przyjąć do szpitala'),
('En el Hospital','W szpitalu','el ingreso','przyjęcie do szpitala'),
('En el Hospital','W szpitalu','visitar','odwiedzać'),
('En el Hospital','W szpitalu','el horario de visitas','godziny odwiedzin'),
('En el Hospital','W szpitalu','grave','ciężki (stan)'),
('En el Hospital','W szpitalu','estable','stabilny (stan)'),
('En el Hospital','W szpitalu','crítico','krytyczny (stan)'),
('En el Hospital','W szpitalu','el yeso / la escayola','gips'),
('En el Hospital','W szpitalu','la herida','rana'),
('En el Hospital','W szpitalu','la cicatriz','blizna'),
('En el Hospital','W szpitalu','los puntos','szwy'),
('En el Hospital','W szpitalu','desmayarse','zemdleć'),
('En el Hospital','W szpitalu','sangrar','krwawić'),
('En el Hospital','W szpitalu','el coma','śpiączka'),
('Síntomas','Symptomy','el síntoma','objaw / symptom'),
('Síntomas','Symptomy','el dolor','ból'),
('Síntomas','Symptomy','la fiebre','gorączka'),
('Síntomas','Symptomy','la tos','kaszel'),
('Síntomas','Symptomy','el resfriado','katar / przeziębienie'),
('Síntomas','Symptomy','el estornudo','kichnięcie'),
('Síntomas','Symptomy','la fatiga / el cansancio','zmęczenie'),
('Síntomas','Symptomy','la debilidad','osłabienie'),
('Síntomas','Symptomy','el mareo','zawroty głowy / nudności'),
('Síntomas','Symptomy','la náusea','mdłości'),
('Síntomas','Symptomy','el vómito','wymioty'),
('Síntomas','Symptomy','la diarrea','biegunka'),
('Síntomas','Symptomy','el estreñimiento','zaparcie'),
('Síntomas','Symptomy','la erupción / el sarpullido','wysypka'),
('Síntomas','Symptomy','el picor / la comezón','swędzenie'),
('Síntomas','Symptomy','la hinchazón','obrzęk / opuchlizna'),
('Síntomas','Symptomy','los escalofríos','dreszcze'),
('Síntomas','Symptomy','el sudor','pot / pocenie się'),
('Síntomas','Symptomy','la falta de aire','duszność'),
('Síntomas','Symptomy','la dificultad para respirar','trudności w oddychaniu'),
('Síntomas','Symptomy','la hemorragia / el sangrado','krwawienie'),
('Síntomas','Symptomy','el moretón / el hematoma','siniak / krwiak'),
('Síntomas','Symptomy','el calambre','skurcz'),
('Síntomas','Symptomy','el entumecimiento','drętwienie'),
('Síntomas','Symptomy','el hormigueo','mrowienie'),
('Síntomas','Symptomy','el insomnio','bezsenność'),
('Síntomas','Symptomy','la pérdida de apetito','utrata apetytu'),
('Síntomas','Symptomy','la pérdida de peso','utrata wagi'),
('Síntomas','Symptomy','el aumento de peso','przyrost wagi'),
('Síntomas','Symptomy','la palidez','bladość'),
('Síntomas','Symptomy','el enrojecimiento','zaczerwienienie'),
('Síntomas','Symptomy','el dolor de cabeza','ból głowy'),
('Síntomas','Symptomy','el dolor de estómago','ból brzucha'),
('Síntomas','Symptomy','el dolor de garganta','ból gardła'),
('Síntomas','Symptomy','la acidez','zgaga'),
('Síntomas','Symptomy','la indigestión','niestrawność'),
('Síntomas','Symptomy','las flatulencias / los gases','wzdęcia / gazy'),
('Síntomas','Symptomy','el pinchazo','kłucie'),
('Síntomas','Symptomy','el ardor','pieczenie'),
('Síntomas','Symptomy','el lagrimeo','łzawienie'),
('Síntomas','Symptomy','la rinitis alérgica','katar sienny'),
('Síntomas','Symptomy','la ronquera','chrypka'),
('Síntomas','Symptomy','la pérdida de olfato','utrata węchu'),
('Síntomas','Symptomy','la pérdida de gusto','utrata smaku'),
('Síntomas','Symptomy','el desmayo','omdlenie'),
('Síntomas','Symptomy','las palpitaciones','palpitacje'),
('Síntomas','Symptomy','la asfixia','duszność / duszenie się'),
('Síntomas','Symptomy','la debilidad muscular','osłabienie mięśni'),
('Síntomas','Symptomy','la rigidez','sztywność'),
('Síntomas','Symptomy','el temblor','drżenie'),
('Tratamientos Médicos','Leczenie','el tratamiento','leczenie / kuracja'),
('Tratamientos Médicos','Leczenie','el medicamento / la medicina','lekarstwo'),
('Tratamientos Médicos','Leczenie','la pastilla','tabletka / pigułka'),
('Tratamientos Médicos','Leczenie','el jarabe','syrop'),
('Tratamientos Médicos','Leczenie','la pomada / la crema','maść / krem'),
('Tratamientos Médicos','Leczenie','la inyección','zastrzyk'),
('Tratamientos Médicos','Leczenie','el suero','kroplówka'),
('Tratamientos Médicos','Leczenie','la vacuna','szczepionka'),
('Tratamientos Médicos','Leczenie','el antibiótico','antybiotyk'),
('Tratamientos Médicos','Leczenie','el analgésico','środek przeciwbólowy'),
('Tratamientos Médicos','Leczenie','la operación','operacja'),
('Tratamientos Médicos','Leczenie','la cirugía','chirurgia'),
('Tratamientos Médicos','Leczenie','la rehabilitación','rehabilitacja'),
('Tratamientos Médicos','Leczenie','la fisioterapia','fizjoterapia'),
('Tratamientos Médicos','Leczenie','el masaje','masaż'),
('Tratamientos Médicos','Leczenie','la terapia','terapia'),
('Tratamientos Médicos','Leczenie','la quimioterapia','chemioterapia'),
('Tratamientos Médicos','Leczenie','la radioterapia','radioterapia'),
('Tratamientos Médicos','Leczenie','el trasplante','przeszczep'),
('Tratamientos Médicos','Leczenie','la diálisis','dializa'),
('Tratamientos Médicos','Leczenie','la inhalación','inhalacja'),
('Tratamientos Médicos','Leczenie','el vendaje','opatrunek / bandażowanie'),
('Tratamientos Médicos','Leczenie','la venda','bandaż'),
('Tratamientos Médicos','Leczenie','el yeso / la escayola','gips'),
('Tratamientos Médicos','Leczenie','las muletas','kule ortopedyczne'),
('Tratamientos Médicos','Leczenie','la silla de ruedas','wózek inwalidzki'),
('Tratamientos Médicos','Leczenie','los puntos de sutura','szwy'),
('Tratamientos Médicos','Leczenie','los primeros auxilios','pierwsza pomoc'),
('Tratamientos Médicos','Leczenie','la reanimación / la RCP','resuscytacja'),
('Tratamientos Médicos','Leczenie','la respiración artificial','sztuczne oddychanie'),
('Tratamientos Médicos','Leczenie','el análisis de sangre','badanie krwi'),
('Tratamientos Médicos','Leczenie','la radiografía','rentgen'),
('Tratamientos Médicos','Leczenie','la resonancia magnética','rezonans magnetyczny'),
('Tratamientos Médicos','Leczenie','la ecografía','USG'),
('Tratamientos Médicos','Leczenie','la receta','recepta'),
('Tratamientos Médicos','Leczenie','la dosis','dawka'),
('Tratamientos Médicos','Leczenie','el reposo en cama','leżenie w łóżku (odpoczynek)'),
('Tratamientos Médicos','Leczenie','la dieta','dieta'),
('Tratamientos Médicos','Leczenie','las vitaminas','witaminy'),
('Tratamientos Médicos','Leczenie','el suplemento','suplement'),
('Tratamientos Médicos','Leczenie','la acupuntura','akupunktura'),
('Tratamientos Médicos','Leczenie','la homeopatía','homeopatia'),
('Tratamientos Médicos','Leczenie','la anestesia','znieczulenie'),
('Tratamientos Médicos','Leczenie','el desfibrilador','defibrylator'),
('Tratamientos Médicos','Leczenie','el respirador','respirator'),
('Tratamientos Médicos','Leczenie','la cuarentena','kwarantanna'),
('Tratamientos Médicos','Leczenie','el aislamiento','izolacja'),
('Tratamientos Médicos','Leczenie','la desintoxicación','detoks'),
('Tratamientos Médicos','Leczenie','el trasplante de médula','przeszczep szpiku'),
('Tratamientos Médicos','Leczenie','la terapia láser','laseroterapia'),
('Deportes de Equipo','Sporty zespołowe','el deporte de equipo','sport zespołowy'),
('Deportes de Equipo','Sporty zespołowe','el equipo','drużyna'),
('Deportes de Equipo','Sporty zespołowe','el jugador / la jugadora','zawodnik / gracz'),
('Deportes de Equipo','Sporty zespołowe','el entrenador','trener'),
('Deportes de Equipo','Sporty zespołowe','el capitán','kapitan'),
('Deportes de Equipo','Sporty zespołowe','el árbitro','sędzia'),
('Deportes de Equipo','Sporty zespołowe','el fútbol','piłka nożna'),
('Deportes de Equipo','Sporty zespołowe','el baloncesto','koszykówka'),
('Deportes de Equipo','Sporty zespołowe','el voleibol','siatkówka'),
('Deportes de Equipo','Sporty zespołowe','el balonmano','piłka ręczna'),
('Deportes de Equipo','Sporty zespołowe','el rugby','rugby'),
('Deportes de Equipo','Sporty zespołowe','el fútbol americano','futbol amerykański'),
('Deportes de Equipo','Sporty zespołowe','el béisbol','baseball'),
('Deportes de Equipo','Sporty zespołowe','el hockey sobre hielo','hokej na lodzie'),
('Deportes de Equipo','Sporty zespołowe','el hockey sobre hierba','hokej na trawie'),
('Deportes de Equipo','Sporty zespołowe','el waterpolo','piłka wodna'),
('Deportes de Equipo','Sporty zespołowe','el críquet','krykiet'),
('Deportes de Equipo','Sporty zespołowe','el lacrosse','lacrosse'),
('Deportes de Equipo','Sporty zespołowe','el polo','polo'),
('Deportes de Equipo','Sporty zespołowe','el curling','curling'),
('Deportes de Equipo','Sporty zespołowe','el partido','mecz'),
('Deportes de Equipo','Sporty zespołowe','el torneo','turniej'),
('Deportes de Equipo','Sporty zespołowe','el campeonato','mistrzostwa'),
('Deportes de Equipo','Sporty zespołowe','la liga','liga'),
('Deportes de Equipo','Sporty zespołowe','la copa','puchar'),
('Deportes de Equipo','Sporty zespołowe','el estadio','stadion'),
('Deportes de Equipo','Sporty zespołowe','el campo / la cancha','boisko'),
('Deportes de Equipo','Sporty zespołowe','la portería','bramka'),
('Deportes de Equipo','Sporty zespołowe','la canasta','kosz'),
('Deportes de Equipo','Sporty zespołowe','la red','siatka'),
('Deportes de Equipo','Sporty zespołowe','el balón / la pelota','piłka'),
('Deportes de Equipo','Sporty zespołowe','el disco','krążek (hokejowy)'),
('Deportes de Equipo','Sporty zespołowe','el casco','kask'),
('Deportes de Equipo','Sporty zespołowe','las protecciones','ochraniacze'),
('Deportes de Equipo','Sporty zespołowe','marcar un gol','strzelić gola'),
('Deportes de Equipo','Sporty zespołowe','anotar un punto','zdobyć punkt'),
('Deportes de Equipo','Sporty zespołowe','lanzar','rzucać'),
('Deportes de Equipo','Sporty zespołowe','atrapar / coger','łapać'),
('Deportes de Equipo','Sporty zespołowe','pasar','podawać'),
('Deportes de Equipo','Sporty zespołowe','la falta','faul'),
('Deportes de Equipo','Sporty zespołowe','el penalti','rzut karny'),
('Deportes de Equipo','Sporty zespołowe','el fuera de juego','spalony'),
('Deportes de Equipo','Sporty zespołowe','el empate','remis'),
('Deportes de Equipo','Sporty zespołowe','la prórroga','dogrywka'),
('Deportes de Equipo','Sporty zespołowe','ganar','wygrać'),
('Deportes de Equipo','Sporty zespołowe','perder','przegrać'),
('Deportes de Equipo','Sporty zespołowe','el aficionado / el hincha','kibic'),
('Deportes de Equipo','Sporty zespołowe','la táctica','taktyka'),
('Deportes de Equipo','Sporty zespołowe','la defensa','obrona'),
('Deportes de Equipo','Sporty zespołowe','el ataque','atak');
