insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Deportes Individuales','Sporty indywidualne','el deporte individual','sport indywidualny'),
('Deportes Individuales','Sporty indywidualne','el atletismo','lekkoatletyka'),
('Deportes Individuales','Sporty indywidualne','la carrera / el running','bieganie'),
('Deportes Individuales','Sporty indywidualne','el esprint','sprint'),
('Deportes Individuales','Sporty indywidualne','el maratón','maraton'),
('Deportes Individuales','Sporty indywidualne','el salto de longitud','skok w dal'),
('Deportes Individuales','Sporty indywidualne','el salto de altura','skok wzwyż'),
('Deportes Individuales','Sporty indywidualne','el salto con pértiga','skok o tyczce'),
('Deportes Individuales','Sporty indywidualne','el lanzamiento de jabalina','rzut oszczepem'),
('Deportes Individuales','Sporty indywidualne','la natación','pływanie'),
('Deportes Individuales','Sporty indywidualne','el ciclismo','kolarstwo'),
('Deportes Individuales','Sporty indywidualne','el tenis','tenis'),
('Deportes Individuales','Sporty indywidualne','el tenis de mesa / el ping-pong','tenis stołowy'),
('Deportes Individuales','Sporty indywidualne','el bádminton','badminton'),
('Deportes Individuales','Sporty indywidualne','el squash','squash'),
('Deportes Individuales','Sporty indywidualne','el golf','golf'),
('Deportes Individuales','Sporty indywidualne','el boxeo','boks'),
('Deportes Individuales','Sporty indywidualne','la lucha libre','zapasy'),
('Deportes Individuales','Sporty indywidualne','el judo','judo'),
('Deportes Individuales','Sporty indywidualne','el karate','karate'),
('Deportes Individuales','Sporty indywidualne','el taekwondo','taekwondo'),
('Deportes Individuales','Sporty indywidualne','la esgrima','szermierka'),
('Deportes Individuales','Sporty indywidualne','la gimnasia','gimnastyka'),
('Deportes Individuales','Sporty indywidualne','el patinaje artístico','łyżwiarstwo figurowe'),
('Deportes Individuales','Sporty indywidualne','el esquí','narciarstwo'),
('Deportes Individuales','Sporty indywidualne','el snowboard','snowboard'),
('Deportes Individuales','Sporty indywidualne','la halterofilia','podnoszenie ciężarów'),
('Deportes Individuales','Sporty indywidualne','el tiro','strzelectwo'),
('Deportes Individuales','Sporty indywidualne','el tiro con arco','łucznictwo'),
('Deportes Individuales','Sporty indywidualne','la equitación / la hípica','jeździectwo'),
('Deportes Individuales','Sporty indywidualne','el triatlón','triathlon'),
('Deportes Individuales','Sporty indywidualne','el pentatlón','pięciobój'),
('Deportes Individuales','Sporty indywidualne','la escalada','wspinaczka'),
('Deportes Individuales','Sporty indywidualne','el billar','billiard'),
('Deportes Individuales','Sporty indywidualne','los dardos','rzutki (darts)'),
('Deportes Individuales','Sporty indywidualne','el ajedrez','szachy'),
('Deportes Individuales','Sporty indywidualne','la carrera','wyścig'),
('Deportes Individuales','Sporty indywidualne','el récord','rekord'),
('Deportes Individuales','Sporty indywidualne','la medalla','medal'),
('Deportes Individuales','Sporty indywidualne','el oro','złoto'),
('Deportes Individuales','Sporty indywidualne','la plata','srebro'),
('Deportes Individuales','Sporty indywidualne','el bronce','brąz'),
('Deportes Individuales','Sporty indywidualne','el campeón','mistrz'),
('Deportes Individuales','Sporty indywidualne','el podio','podium'),
('Deportes Individuales','Sporty indywidualne','el oponente / el contrincante','przeciwnik'),
('Deportes Individuales','Sporty indywidualne','el rival','rywal'),
('Deportes Individuales','Sporty indywidualne','el entrenamiento','trening'),
('Deportes Individuales','Sporty indywidualne','la condición física','kondycja'),
('Deportes Individuales','Sporty indywidualne','la técnica','technika'),
('Deportes Individuales','Sporty indywidualne','el equipamiento','sprzęt (sportowy)'),
('Deportes Acuáticos','Sporty wodne','el deporte acuático','sport wodny'),
('Deportes Acuáticos','Sporty wodne','la natación','pływanie'),
('Deportes Acuáticos','Sporty wodne','los saltos (de trampolín)','skoki do wody'),
('Deportes Acuáticos','Sporty wodne','el waterpolo','piłka wodna'),
('Deportes Acuáticos','Sporty wodne','la natación sincronizada','pływanie synchroniczne'),
('Deportes Acuáticos','Sporty wodne','el remo','wioślarstwo'),
('Deportes Acuáticos','Sporty wodne','el piragüismo / el kayak','kajakarstwo'),
('Deportes Acuáticos','Sporty wodne','la vela','żeglarstwo'),
('Deportes Acuáticos','Sporty wodne','el windsurf','windsurfing'),
('Deportes Acuáticos','Sporty wodne','el kitesurf','kitesurfing'),
('Deportes Acuáticos','Sporty wodne','el surf','surfing'),
('Deportes Acuáticos','Sporty wodne','el buceo / el submarinismo','nurkowanie'),
('Deportes Acuáticos','Sporty wodne','la apnea','freediving (na wstrzymanym oddechu)'),
('Deportes Acuáticos','Sporty wodne','el esnórquel','snorkeling (z rurką)'),
('Deportes Acuáticos','Sporty wodne','el esquí acuático','narty wodne'),
('Deportes Acuáticos','Sporty wodne','el wakeboard','wakeboard'),
('Deportes Acuáticos','Sporty wodne','el rafting','rafting'),
('Deportes Acuáticos','Sporty wodne','la piscina','basen'),
('Deportes Acuáticos','Sporty wodne','el mar','morze'),
('Deportes Acuáticos','Sporty wodne','el lago','jezioro'),
('Deportes Acuáticos','Sporty wodne','el agua','woda'),
('Deportes Acuáticos','Sporty wodne','la tabla de surf','deska surfingowa'),
('Deportes Acuáticos','Sporty wodne','la vela (objeto)','żagiel'),
('Deportes Acuáticos','Sporty wodne','el remo (objeto)','wiosło'),
('Deportes Acuáticos','Sporty wodne','la canoa / el kayak','kajak / kanoe'),
('Deportes Acuáticos','Sporty wodne','la barca','łódź'),
('Deportes Acuáticos','Sporty wodne','el bañador','strój kąpielowy'),
('Deportes Acuáticos','Sporty wodne','el traje de neopreno','pianka (do pływania)'),
('Deportes Acuáticos','Sporty wodne','las gafas de natación','okulary pływackie'),
('Deportes Acuáticos','Sporty wodne','el gorro de baño','czepek'),
('Deportes Acuáticos','Sporty wodne','las aletas','płetwy'),
('Deportes Acuáticos','Sporty wodne','el tubo de buceo','rurka do nurkowania'),
('Deportes Acuáticos','Sporty wodne','el chaleco salvavidas','kamizelka ratunkowa'),
('Deportes Acuáticos','Sporty wodne','el socorrista','ratownik wodny'),
('Deportes Acuáticos','Sporty wodne','la ola','fala'),
('Deportes Acuáticos','Sporty wodne','el viento','wiatr'),
('Deportes Acuáticos','Sporty wodne','la corriente','prąd (wodny)'),
('Deportes Acuáticos','Sporty wodne','la profundidad','głębokość'),
('Deportes Acuáticos','Sporty wodne','el estilo libre / el crol','kraul / styl dowolny'),
('Deportes Acuáticos','Sporty wodne','la braza','styl klasyczny (żabka)'),
('Deportes Acuáticos','Sporty wodne','el estilo espalda','styl grzbietowy'),
('Deportes Acuáticos','Sporty wodne','el estilo mariposa','styl motylkowy (delfin)'),
('Deportes Acuáticos','Sporty wodne','el trampolín','trampolina'),
('Deportes Acuáticos','Sporty wodne','la inmersión','zanurzenie'),
('Deportes Acuáticos','Sporty wodne','la regata','regaty / wyścig'),
('Deportes Acuáticos','Sporty wodne','el puerto deportivo','marina / przystań'),
('Deportes Acuáticos','Sporty wodne','el amarre','miejsce cumowania'),
('Deportes Acuáticos','Sporty wodne','la balsa','tratwa'),
('Deportes Acuáticos','Sporty wodne','la moto de agua','skuter wodny'),
('Deportes Acuáticos','Sporty wodne','bucear','nurkować'),
('Deportes de Invierno','Sporty zimowe','el deporte de invierno','sport zimowy'),
('Deportes de Invierno','Sporty zimowe','el esquí','narciarstwo / narta'),
('Deportes de Invierno','Sporty zimowe','el snowboard','snowboard'),
('Deportes de Invierno','Sporty zimowe','el patinaje sobre hielo','łyżwiarstwo figurowe / na lodzie'),
('Deportes de Invierno','Sporty zimowe','el hockey sobre hielo','hokej na lodzie'),
('Deportes de Invierno','Sporty zimowe','el patinaje de velocidad','łyżwiarstwo szybkie'),
('Deportes de Invierno','Sporty zimowe','el salto de esquí','skoki narciarskie'),
('Deportes de Invierno','Sporty zimowe','el biatlón','biathlon'),
('Deportes de Invierno','Sporty zimowe','el bobsleigh','bobsleje'),
('Deportes de Invierno','Sporty zimowe','el trineo','sanki / saneczkarstwo'),
('Deportes de Invierno','Sporty zimowe','el curling','curling'),
('Deportes de Invierno','Sporty zimowe','el alpinismo','alpinizm'),
('Deportes de Invierno','Sporty zimowe','la nieve','śnieg'),
('Deportes de Invierno','Sporty zimowe','el hielo','lód'),
('Deportes de Invierno','Sporty zimowe','la montaña','góra'),
('Deportes de Invierno','Sporty zimowe','la pista de esquí','stok narciarski'),
('Deportes de Invierno','Sporty zimowe','el telesilla / el remonte','wyciąg krzesełkowy / orczyk'),
('Deportes de Invierno','Sporty zimowe','el teleférico','kolejka linowa'),
('Deportes de Invierno','Sporty zimowe','la avalancha / el alud','lawina'),
('Deportes de Invierno','Sporty zimowe','el copo de nieve','płatek śniegu'),
('Deportes de Invierno','Sporty zimowe','el invierno','zima'),
('Deportes de Invierno','Sporty zimowe','el frío','zimno'),
('Deportes de Invierno','Sporty zimowe','bajo cero','poniżej zera'),
('Deportes de Invierno','Sporty zimowe','congelado','zamarznięty'),
('Deportes de Invierno','Sporty zimowe','resbaladizo','śliski'),
('Deportes de Invierno','Sporty zimowe','patinar','jeździć na łyżwach'),
('Deportes de Invierno','Sporty zimowe','esquiar','jeździć na nartach'),
('Deportes de Invierno','Sporty zimowe','deslizarse','ślizgać się / zjeżdżać'),
('Deportes de Invierno','Sporty zimowe','frenar','hamować'),
('Deportes de Invierno','Sporty zimowe','caerse','przewrócić się'),
('Deportes de Invierno','Sporty zimowe','los esquís','narty'),
('Deportes de Invierno','Sporty zimowe','los bastones (de esquí)','kije narciarskie'),
('Deportes de Invierno','Sporty zimowe','las fijaciones','wiązania'),
('Deportes de Invierno','Sporty zimowe','las botas de esquí','buty narciarskie'),
('Deportes de Invierno','Sporty zimowe','la tabla de snowboard','deska snowboardowa'),
('Deportes de Invierno','Sporty zimowe','los patines','łyżwy'),
('Deportes de Invierno','Sporty zimowe','el disco (de hockey)','krążek hokejowy'),
('Deportes de Invierno','Sporty zimowe','el casco','kask'),
('Deportes de Invierno','Sporty zimowe','las gafas de ventisca','gogle narciarskie'),
('Deportes de Invierno','Sporty zimowe','los guantes','rękawice'),
('Deportes de Invierno','Sporty zimowe','el abrigo','płaszcz / kurtka'),
('Deportes de Invierno','Sporty zimowe','el gorro','czapka'),
('Deportes de Invierno','Sporty zimowe','la bufanda','szalik'),
('Deportes de Invierno','Sporty zimowe','el forfait','karnet narciarski'),
('Deportes de Invierno','Sporty zimowe','el instructor','instruktor'),
('Deportes de Invierno','Sporty zimowe','la clase de esquí','lekcja narciarstwa'),
('Deportes de Invierno','Sporty zimowe','el campeonato','mistrzostwa'),
('Deportes de Invierno','Sporty zimowe','el fuera de pista','jazda poza trasą (freeride)'),
('Deportes de Invierno','Sporty zimowe','la estación de esquí','ośrodek narciarski'),
('Deportes de Invierno','Sporty zimowe','el trineo de perros','psi zaprzęg'),
('Equipamiento Deportivo','Sprzęt sportowy','el equipamiento deportivo','sprzęt sportowy'),
('Equipamiento Deportivo','Sprzęt sportowy','la pelota','piłka (zwykle mała)'),
('Equipamiento Deportivo','Sprzęt sportowy','el balón','piłka (duża)'),
('Equipamiento Deportivo','Sprzęt sportowy','la raqueta','rakieta (np. tenisowa)'),
('Equipamiento Deportivo','Sprzęt sportowy','el bate','kij baseballowy'),
('Equipamiento Deportivo','Sprzęt sportowy','el palo','kij (golfowy, hokejowy)'),
('Equipamiento Deportivo','Sprzęt sportowy','la red','siatka'),
('Equipamiento Deportivo','Sprzęt sportowy','la portería','bramka'),
('Equipamiento Deportivo','Sprzęt sportowy','la canasta','kosz'),
('Equipamiento Deportivo','Sprzęt sportowy','los guantes','rękawice'),
('Equipamiento Deportivo','Sprzęt sportowy','el casco','kask'),
('Equipamiento Deportivo','Sprzęt sportowy','las rodilleras','nakolanniki'),
('Equipamiento Deportivo','Sprzęt sportowy','las coderas','nałokietniki'),
('Equipamiento Deportivo','Sprzęt sportowy','las espinilleras','ochraniacze na piszczele'),
('Equipamiento Deportivo','Sprzęt sportowy','las gafas de natación','okulary pływackie'),
('Equipamiento Deportivo','Sprzęt sportowy','el gorro de baño','czepek pływacki'),
('Equipamiento Deportivo','Sprzęt sportowy','el bañador','strój kąpielowy'),
('Equipamiento Deportivo','Sprzęt sportowy','el chándal','dres'),
('Equipamiento Deportivo','Sprzęt sportowy','las zapatillas de deporte','buty sportowe'),
('Equipamiento Deportivo','Sprzęt sportowy','los tacos','korki (buty)'),
('Equipamiento Deportivo','Sprzęt sportowy','los patines','łyżwy / rolki'),
('Equipamiento Deportivo','Sprzęt sportowy','la bicicleta','rower'),
('Equipamiento Deportivo','Sprzęt sportowy','el sillín','siodełko'),
('Equipamiento Deportivo','Sprzęt sportowy','el pedal','pedał'),
('Equipamiento Deportivo','Sprzęt sportowy','el manillar','kierownica (rowerowa)'),
('Equipamiento Deportivo','Sprzęt sportowy','la tabla','deska'),
('Equipamiento Deportivo','Sprzęt sportowy','los esquís','narty'),
('Equipamiento Deportivo','Sprzęt sportowy','el silbato','gwizdek'),
('Equipamiento Deportivo','Sprzęt sportowy','el cronómetro','stoper'),
('Equipamiento Deportivo','Sprzęt sportowy','la cinta de correr','bieżnia (urządzenie)'),
('Equipamiento Deportivo','Sprzęt sportowy','la pesa','ciężarek'),
('Equipamiento Deportivo','Sprzęt sportowy','la mancuerna','hantel'),
('Equipamiento Deportivo','Sprzęt sportowy','la barra','sztanga / drążek'),
('Equipamiento Deportivo','Sprzęt sportowy','el disco (de pesas)','talerz (obciążenie)'),
('Equipamiento Deportivo','Sprzęt sportowy','la esterilla / la colchoneta','mata (np. do jogi) / materac'),
('Equipamiento Deportivo','Sprzęt sportowy','el saco de boxeo','worek treningowy'),
('Equipamiento Deportivo','Sprzęt sportowy','el kimono','kimono'),
('Equipamiento Deportivo','Sprzęt sportowy','el cinturón','pas (np. w sztukach walki)'),
('Equipamiento Deportivo','Sprzęt sportowy','los dardos','rzutki (lotki)'),
('Equipamiento Deportivo','Sprzęt sportowy','la diana','tarcza (do rzutek)'),
('Equipamiento Deportivo','Sprzęt sportowy','el tablero','plansza (np. do szachów)'),
('Equipamiento Deportivo','Sprzęt sportowy','las piezas','pionki / bierki'),
('Equipamiento Deportivo','Sprzęt sportowy','el aro','obręcz (np. hula hop)'),
('Equipamiento Deportivo','Sprzęt sportowy','la comba','skakanka'),
('Equipamiento Deportivo','Sprzęt sportowy','el trampolín','trampolina'),
('Equipamiento Deportivo','Sprzęt sportowy','la jabalina','oszczep'),
('Equipamiento Deportivo','Sprzęt sportowy','el disco (atletismo)','dysk (do rzutu)'),
('Equipamiento Deportivo','Sprzęt sportowy','el trofeo','trofeum / puchar'),
('Equipamiento Deportivo','Sprzęt sportowy','la medalla','medal'),
('Equipamiento Deportivo','Sprzęt sportowy','el uniforme','stój sportowy (uniform)'),
('En el Gimnasio','Na siłowni','el gimnasio','siłownia'),
('En el Gimnasio','Na siłowni','el entrenamiento','trening'),
('En el Gimnasio','Na siłowni','entrenar','trenować'),
('En el Gimnasio','Na siłowni','hacer ejercicio','ćwiczyć'),
('En el Gimnasio','Na siłowni','estar en forma','być w formie'),
('En el Gimnasio','Na siłowni','la salud','zdrowie'),
('En el Gimnasio','Na siłowni','la condición física','kondycja fizyczna'),
('En el Gimnasio','Na siłowni','el entrenador personal','trener personalny'),
('En el Gimnasio','Na siłowni','el instructor','instruktor'),
('En el Gimnasio','Na siłowni','el músculo','mięsień'),
('En el Gimnasio','Na siłowni','la fuerza','siła'),
('En el Gimnasio','Na siłowni','la resistencia','wytrzymałość'),
('En el Gimnasio','Na siłowni','el calentamiento','rozgrzewka'),
('En el Gimnasio','Na siłowni','calentar','rozgrzewać się'),
('En el Gimnasio','Na siłowni','el estiramiento','rozciągananie'),
('En el Gimnasio','Na siłowni','estirar','rozciągać się'),
('En el Gimnasio','Na siłowni','la máquina','maszyna / sprzęt (do ćwiczeń)'),
('En el Gimnasio','Na siłowni','la cinta de correr','bieżnia'),
('En el Gimnasio','Na siłowni','la bicicleta estática','rowerek stacjonarny'),
('En el Gimnasio','Na siłowni','la elíptica','orbitrek / maszyna eliptyczna'),
('En el Gimnasio','Na siłowni','las pesas','ciężary'),
('En el Gimnasio','Na siłowni','levantar pesas','podnosić ciężary'),
('En el Gimnasio','Na siłowni','la mancuerna','hantel'),
('En el Gimnasio','Na siłowni','la pesa rusa / la kettlebell','odważnik kulowy (kettlebell)'),
('En el Gimnasio','Na siłowni','la barra','sztanga'),
('En el Gimnasio','Na siłowni','la repetición','powtórzenie'),
('En el Gimnasio','Na siłowni','la serie','seria'),
('En el Gimnasio','Na siłowni','el descanso','odpoczynek'),
('En el Gimnasio','Na siłowni','sudar','pocić się'),
('En el Gimnasio','Na siłowni','el sudor','pot'),
('En el Gimnasio','Na siłowni','la toalla','ręcznik'),
('En el Gimnasio','Na siłowni','la botella de agua','butelka wody'),
('En el Gimnasio','Na siłowni','el vestuario','szatnia'),
('En el Gimnasio','Na siłowni','la taquilla','szafka (w szatni)'),
('En el Gimnasio','Na siłowni','la ducha','prysznic'),
('En el Gimnasio','Na siłowni','la clase dirigida','zajęcia grupowe'),
('En el Gimnasio','Na siłowni','el yoga','joga'),
('En el Gimnasio','Na siłowni','el pilates','pilates'),
('En el Gimnasio','Na siłowni','el aeróbic','aerobik'),
('En el Gimnasio','Na siłowni','el zumba','zumba'),
('En el Gimnasio','Na siłowni','el spinning','spinning'),
('En el Gimnasio','Na siłowni','la esterilla','mata do ćwiczeń'),
('En el Gimnasio','Na siłowni','los abdominales','brzuszki (ćwiczenie) / mięśnie brzucha'),
('En el Gimnasio','Na siłowni','las flexiones','pompki (ćwiczenie)'),
('En el Gimnasio','Na siłowni','las sentadillas','przysiady'),
('En el Gimnasio','Na siłowni','perder peso','schudnąć / tracić na wadze'),
('En el Gimnasio','Na siłowni','ganar masa muscular','budować masę mięśniową'),
('En el Gimnasio','Na siłowni','la dieta','dieta'),
('En el Gimnasio','Na siłowni','la proteína','białko'),
('En el Gimnasio','Na siłowni','la motivación','motywacja'),
('Artes Marciales','Sztuki walki','las artes marciales','sztuki walki'),
('Artes Marciales','Sztuki walki','el kárate','karate'),
('Artes Marciales','Sztuki walki','el judo','judo'),
('Artes Marciales','Sztuki walki','el taekwondo','taekwondo'),
('Artes Marciales','Sztuki walki','el boxeo','boks'),
('Artes Marciales','Sztuki walki','el kickboxing','kick-boxing'),
('Artes Marciales','Sztuki walki','el muay thai','muay thai (boks tajski)'),
('Artes Marciales','Sztuki walki','el jiu-jitsu','jiu-jitsu'),
('Artes Marciales','Sztuki walki','el kung fu','kung fu'),
('Artes Marciales','Sztuki walki','la esgrima','szermierka'),
('Artes Marciales','Sztuki walki','la lucha libre','zapasy'),
('Artes Marciales','Sztuki walki','el combate','walka / starcie'),
('Artes Marciales','Sztuki walki','el asalto / el round','runda'),
('Artes Marciales','Sztuki walki','el cuadrilátero / el ring','ring'),
('Artes Marciales','Sztuki walki','el tatami','mata (tatami)'),
('Artes Marciales','Sztuki walki','el luchador','wojownik / zapaśnik'),
('Artes Marciales','Sztuki walki','el boxeador','bokser'),
('Artes Marciales','Sztuki walki','el maestro / el sensei','mistrz / nauczyciel'),
('Artes Marciales','Sztuki walki','el oponente / el rival','przeciwnik / rywal'),
('Artes Marciales','Sztuki walki','el árbitro','sędzia'),
('Artes Marciales','Sztuki walki','atacar','atakować'),
('Artes Marciales','Sztuki walki','el ataque','atak'),
('Artes Marciales','Sztuki walki','defender','bronić'),
('Artes Marciales','Sztuki walki','la defensa','obrona'),
('Artes Marciales','Sztuki walki','bloquear','blokować'),
('Artes Marciales','Sztuki walki','el bloqueo','blok (ciosu)'),
('Artes Marciales','Sztuki walki','golpear','uderzać'),
('Artes Marciales','Sztuki walki','el golpe','cios / uderzenie'),
('Artes Marciales','Sztuki walki','el puñetazo','uderzenie pięścią'),
('Artes Marciales','Sztuki walki','la patada','kopnięcie'),
('Artes Marciales','Sztuki walki','el gancho','sierpowy / hak (cios)'),
('Artes Marciales','Sztuki walki','esquivar','unikać (ciosu)'),
('Artes Marciales','Sztuki walki','derribar','powalić / obalić'),
('Artes Marciales','Sztuki walki','el agarre','chwyt'),
('Artes Marciales','Sztuki walki','la llave','dźwignia'),
('Artes Marciales','Sztuki walki','la sumisión','poddanie'),
('Artes Marciales','Sztuki walki','rendirse','poddać się'),
('Artes Marciales','Sztuki walki','ganar','wygrać'),
('Artes Marciales','Sztuki walki','perder','przegrać'),
('Artes Marciales','Sztuki walki','el nocaut (KO)','nokaut (KO)'),
('Artes Marciales','Sztuki walki','la disciplina','dyscyplina'),
('Artes Marciales','Sztuki walki','el respeto','szacunek'),
('Artes Marciales','Sztuki walki','la concentración','koncentracja'),
('Artes Marciales','Sztuki walki','el kimono / el dobok','kimono'),
('Artes Marciales','Sztuki walki','el cinturón','pas'),
('Artes Marciales','Sztuki walki','el cinturón negro','czarny pas'),
('Artes Marciales','Sztuki walki','el guante de boxeo','rękawica bokserska'),
('Artes Marciales','Sztuki walki','el saco de boxeo','worek treningowy'),
('Artes Marciales','Sztuki walki','la técnica','technika'),
('Artes Marciales','Sztuki walki','el torneo','turniej'),
('Música Clásica','Muzyka klasyczna','la música clásica','muzyka klasyczna'),
('Música Clásica','Muzyka klasyczna','la música','muzyka'),
('Música Clásica','Muzyka klasyczna','el músico','muzyk'),
('Música Clásica','Muzyka klasyczna','el compositor','kompozytor'),
('Música Clásica','Muzyka klasyczna','componer','komponować'),
('Música Clásica','Muzyka klasyczna','la obra','dzieło'),
('Música Clásica','Muzyka klasyczna','la pieza musical','utwór muzyczny'),
('Música Clásica','Muzyka klasyczna','la sinfonía','symfonia'),
('Música Clásica','Muzyka klasyczna','el concierto','koncert'),
('Música Clásica','Muzyka klasyczna','la sonata','sonata'),
('Música Clásica','Muzyka klasyczna','la ópera','opera'),
('Música Clásica','Muzyka klasyczna','el ballet','balet'),
('Música Clásica','Muzyka klasyczna','la orquesta','orkiestra'),
('Música Clásica','Muzyka klasyczna','la orquesta sinfónica','orkiestra symfoniczna'),
('Música Clásica','Muzyka klasyczna','el director de orquesta','dyrygent'),
('Música Clásica','Muzyka klasyczna','la batuta','batuta'),
('Música Clásica','Muzyka klasyczna','el ensayo','próba'),
('Música Clásica','Muzyka klasyczna','ensayar','robić próbę / ćwiczyć'),
('Música Clásica','Muzyka klasyczna','el escenario','scena'),
('Música Clásica','Muzyka klasyczna','el público','publiczność'),
('Música Clásica','Muzyka klasyczna','aplaudir','klaskać'),
('Música Clásica','Muzyka klasyczna','el aplauso','oklaski / brawa'),
('Música Clásica','Muzyka klasyczna','el teatro','teatr'),
('Música Clásica','Muzyka klasyczna','el auditorio','audytorium / sala koncertowa'),
('Música Clásica','Muzyka klasyczna','el instrumento','instrument'),
('Música Clásica','Muzyka klasyczna','el violín','skrzypce'),
('Música Clásica','Muzyka klasyczna','la viola','altówka'),
('Música Clásica','Muzyka klasyczna','el violonchelo','wiolonczela'),
('Música Clásica','Muzyka klasyczna','el contrabajo','kontrabas'),
('Música Clásica','Muzyka klasyczna','el piano','pianino / fortepian'),
('Música Clásica','Muzyka klasyczna','la flauta','flet'),
('Música Clásica','Muzyka klasyczna','el clarinete','klarnet'),
('Música Clásica','Muzyka klasyczna','el oboe','obój'),
('Música Clásica','Muzyka klasyczna','la trompeta','trąbka'),
('Música Clásica','Muzyka klasyczna','el trombón','puzon'),
('Música Clásica','Muzyka klasyczna','la trompa','waltornia'),
('Música Clásica','Muzyka klasyczna','los timbales','kotły (instrument)'),
('Música Clásica','Muzyka klasyczna','el arpa','harfa'),
('Música Clásica','Muzyka klasyczna','afinar','stroić'),
('Música Clásica','Muzyka klasyczna','tocar','grać (na instrumencie)'),
('Música Clásica','Muzyka klasyczna','la melodía','melodia'),
('Música Clásica','Muzyka klasyczna','la armonía','harmonia'),
('Música Clásica','Muzyka klasyczna','el ritmo','rytm'),
('Música Clásica','Muzyka klasyczna','la partitura','partytura / zapis nutowy'),
('Música Clásica','Muzyka klasyczna','la nota','nuta'),
('Música Clásica','Muzyka klasyczna','el atril','pulpit (na nuty)'),
('Música Clásica','Muzyka klasyczna','el coro','chór'),
('Música Clásica','Muzyka klasyczna','cantar','śpiewać'),
('Música Clásica','Muzyka klasyczna','el soprano','sopran'),
('Música Clásica','Muzyka klasyczna','el tenor','tenor'),
('Géneros Musicales','Gatunki muzyczne','el género musical','gatunek muzyczny'),
('Géneros Musicales','Gatunki muzyczne','el pop','pop'),
('Géneros Musicales','Gatunki muzyczne','el rock','rock'),
('Géneros Musicales','Gatunki muzyczne','el jazz','jazz'),
('Géneros Musicales','Gatunki muzyczne','el blues','blues'),
('Géneros Musicales','Gatunki muzyczne','la música clásica','muzyka klasyczna'),
('Géneros Musicales','Gatunki muzyczne','el hip hop','hip hop'),
('Géneros Musicales','Gatunki muzyczne','el rap','rap'),
('Géneros Musicales','Gatunki muzyczne','el reguetón','reggaeton'),
('Géneros Musicales','Gatunki muzyczne','la salsa','salsa'),
('Géneros Musicales','Gatunki muzyczne','la bachata','bachata'),
('Géneros Musicales','Gatunki muzyczne','el merengue','merengue'),
('Géneros Musicales','Gatunki muzyczne','la cumbia','cumbia'),
('Géneros Musicales','Gatunki muzyczne','el flamenco','flamenco'),
('Géneros Musicales','Gatunki muzyczne','el tango','tango'),
('Géneros Musicales','Gatunki muzyczne','el country','country'),
('Géneros Musicales','Gatunki muzyczne','el heavy metal','heavy metal'),
('Géneros Musicales','Gatunki muzyczne','el punk','punk'),
('Géneros Musicales','Gatunki muzyczne','la música electrónica','muzyka elektroniczna'),
('Géneros Musicales','Gatunki muzyczne','el tecno','techno'),
('Géneros Musicales','Gatunki muzyczne','el house','house'),
('Géneros Musicales','Gatunki muzyczne','la música disco','muzyka disco'),
('Géneros Musicales','Gatunki muzyczne','el reggae','reggae'),
('Géneros Musicales','Gatunki muzyczne','el soul','soul'),
('Géneros Musicales','Gatunki muzyczne','el R&B','R&B'),
('Géneros Musicales','Gatunki muzyczne','la música indie','muzyka indie'),
('Géneros Musicales','Gatunki muzyczne','el folk / la música folclórica','muzyka folkowa / ludowa'),
('Géneros Musicales','Gatunki muzyczne','la ópera','opera'),
('Géneros Musicales','Gatunki muzyczne','la zarzuela','zarzuela (hiszpańska operetka)'),
('Géneros Musicales','Gatunki muzyczne','el gospel','gospel'),
('Géneros Musicales','Gatunki muzyczne','el funk','funk'),
('Géneros Musicales','Gatunki muzyczne','el ska','ska'),
('Géneros Musicales','Gatunki muzyczne','la música ambiental','muzyka ambient / tła'),
('Géneros Musicales','Gatunki muzyczne','el villancico','kolęda'),
('Géneros Musicales','Gatunki muzyczne','el himno','hymn'),
('Géneros Musicales','Gatunki muzyczne','la balada','balada'),
('Géneros Musicales','Gatunki muzyczne','el bolero','bolero'),
('Géneros Musicales','Gatunki muzyczne','la ranchera','ranchera'),
('Géneros Musicales','Gatunki muzyczne','el mariachi','muzyka mariachi'),
('Géneros Musicales','Gatunki muzyczne','la música de cámara','muzyka kameralna'),
('Géneros Musicales','Gatunki muzyczne','la sinfonía','symfonia'),
('Géneros Musicales','Gatunki muzyczne','la música instrumental','muzyka instrumentalna'),
('Géneros Musicales','Gatunki muzyczne','la música vocal','muzyka wokalna'),
('Géneros Musicales','Gatunki muzyczne','el ritmo','rytm'),
('Géneros Musicales','Gatunki muzyczne','el compás','takt / metrum'),
('Géneros Musicales','Gatunki muzyczne','el acorde','akord'),
('Géneros Musicales','Gatunki muzyczne','la melodía','melodia'),
('Géneros Musicales','Gatunki muzyczne','el estribillo','refren'),
('Géneros Musicales','Gatunki muzyczne','la estrofa','zwrotka'),
('Géneros Musicales','Gatunki muzyczne','el estilo','styl (muzyczny)'),
('Pintura y Escultura','Malarstwo i rzeźba','la pintura','malarstwo / farba'),
('Pintura y Escultura','Malarstwo i rzeźba','el cuadro','obraz'),
('Pintura y Escultura','Malarstwo i rzeźba','el pintor','malarz'),
('Pintura y Escultura','Malarstwo i rzeźba','la pintora','malarka'),
('Pintura y Escultura','Malarstwo i rzeźba','el pincel','pędzel'),
('Pintura y Escultura','Malarstwo i rzeźba','la paleta','paleta'),
('Pintura y Escultura','Malarstwo i rzeźba','el lienzo','płótno'),
('Pintura y Escultura','Malarstwo i rzeźba','el caballete','sztaluga'),
('Pintura y Escultura','Malarstwo i rzeźba','la acuarela','akwarela'),
('Pintura y Escultura','Malarstwo i rzeźba','el óleo','farba olejna / obraz olejny'),
('Pintura y Escultura','Malarstwo i rzeźba','el acrílico','akryl'),
('Pintura y Escultura','Malarstwo i rzeźba','el pastel','pastel'),
('Pintura y Escultura','Malarstwo i rzeźba','el carboncillo','węgiel (do rysowania)'),
('Pintura y Escultura','Malarstwo i rzeźba','el boceto','szkic / zarys'),
('Pintura y Escultura','Malarstwo i rzeźba','el esbozo','szkic'),
('Pintura y Escultura','Malarstwo i rzeźba','el dibujo','rysunek'),
('Pintura y Escultura','Malarstwo i rzeźba','el retrato','portret'),
('Pintura y Escultura','Malarstwo i rzeźba','el autorretrato','autoportret'),
('Pintura y Escultura','Malarstwo i rzeźba','el paisaje','pejzaż / krajobraz'),
('Pintura y Escultura','Malarstwo i rzeźba','el bodegón','martwa natura'),
('Pintura y Escultura','Malarstwo i rzeźba','la perspectiva','perspektywa'),
('Pintura y Escultura','Malarstwo i rzeźba','la textura','tekstura'),
('Pintura y Escultura','Malarstwo i rzeźba','la obra de arte','dzieło sztuki'),
('Pintura y Escultura','Malarstwo i rzeźba','la exposición','wystawa'),
('Pintura y Escultura','Malarstwo i rzeźba','la galería','galeria (sztuki)'),
('Pintura y Escultura','Malarstwo i rzeźba','el museo','muzeum'),
('Pintura y Escultura','Malarstwo i rzeźba','el marco','rama'),
('Pintura y Escultura','Malarstwo i rzeźba','la escultura','rzeźba'),
('Pintura y Escultura','Malarstwo i rzeźba','el escultor','rzeźbiarz'),
('Pintura y Escultura','Malarstwo i rzeźba','esculpir','rzeźbić'),
('Pintura y Escultura','Malarstwo i rzeźba','tallar','rzeźbić / ciosać (w drewnie/kamieniu)'),
('Pintura y Escultura','Malarstwo i rzeźba','el mármol','marmur'),
('Pintura y Escultura','Malarstwo i rzeźba','el bronce','brąz'),
('Pintura y Escultura','Malarstwo i rzeźba','la arcilla','glina'),
('Pintura y Escultura','Malarstwo i rzeźba','el yeso','gips'),
('Pintura y Escultura','Malarstwo i rzeźba','la piedra','kamień'),
('Pintura y Escultura','Malarstwo i rzeźba','el cincel','dłuto'),
('Pintura y Escultura','Malarstwo i rzeźba','el martillo','młotek'),
('Pintura y Escultura','Malarstwo i rzeźba','el relieve','płaskorzeźba'),
('Pintura y Escultura','Malarstwo i rzeźba','el busto','popiersie'),
('Pintura y Escultura','Malarstwo i rzeźba','la estatua','statua / posąg'),
('Pintura y Escultura','Malarstwo i rzeźba','el monumento','pomnik'),
('Pintura y Escultura','Malarstwo i rzeźba','la obra maestra','arcydzieło'),
('Pintura y Escultura','Malarstwo i rzeźba','la creatividad','kreatywność'),
('Pintura y Escultura','Malarstwo i rzeźba','abstracto','abstrakcyjny'),
('Pintura y Escultura','Malarstwo i rzeźba','figurativo','figuratywny'),
('Pintura y Escultura','Malarstwo i rzeźba','realista','realistyczny'),
('Pintura y Escultura','Malarstwo i rzeźba','surrealista','surrealistyczny'),
('Pintura y Escultura','Malarstwo i rzeźba','la pincelada','pociągnięcie pędzlem'),
('Pintura y Escultura','Malarstwo i rzeźba','las bellas artes','sztuki piękne'),
('Arquitectura','Architektura','la arquitectura','architektura'),
('Arquitectura','Architektura','el arquitecto','architekt'),
('Arquitectura','Architektura','el edificio','budynek'),
('Arquitectura','Architektura','la construcción','budowa / konstrukcja'),
('Arquitectura','Architektura','construir','budować'),
('Arquitectura','Architektura','el plano','plan / projekt'),
('Arquitectura','Architektura','el diseño','projekt / design'),
('Arquitectura','Architektura','el proyecto','projekt'),
('Arquitectura','Architektura','los cimientos','fundamenty'),
('Arquitectura','Architektura','la fachada','fasada / elewacja'),
('Arquitectura','Architektura','el muro','mur'),
('Arquitectura','Architektura','la pared','ściana'),
('Arquitectura','Architektura','el techo','sufit / dach'),
('Arquitectura','Architektura','el tejado','dach'),
('Arquitectura','Architektura','la columna','kolumna'),
('Arquitectura','Architektura','el pilar','filar'),
('Arquitectura','Architektura','el arco','łuk (architektoniczny)'),
('Arquitectura','Architektura','la bóveda','sklepienie'),
('Arquitectura','Architektura','la cúpula','kopuła'),
('Arquitectura','Architektura','la escalera','schody'),
('Arquitectura','Architektura','el balcón','balkon'),
('Arquitectura','Architektura','la terraza','taras'),
('Arquitectura','Architektura','la ventana','okno'),
('Arquitectura','Architektura','la puerta','drzwi'),
('Arquitectura','Architektura','el rascacielos','drapacz chmur'),
('Arquitectura','Architektura','la torre','wieża'),
('Arquitectura','Architektura','el castillo','zamek'),
('Arquitectura','Architektura','el palacio','pałac'),
('Arquitectura','Architektura','la iglesia','kościół'),
('Arquitectura','Architektura','la catedral','katedra'),
('Arquitectura','Architektura','el templo','świątynia'),
('Arquitectura','Architektura','la mezquita','meczet'),
('Arquitectura','Architektura','el puente','most'),
('Arquitectura','Architektura','el monumento','zabytek / pomnik'),
('Arquitectura','Architektura','el ladrillo','cegła'),
('Arquitectura','Architektura','el cemento','cement'),
('Arquitectura','Architektura','el hormigón','beton'),
('Arquitectura','Architektura','el acero','stal'),
('Arquitectura','Architektura','el vidrio','szkło'),
('Arquitectura','Architektura','la madera','drewno'),
('Arquitectura','Architektura','el estilo gótico','styl gotycki'),
('Arquitectura','Architektura','el estilo románico','styl romański'),
('Arquitectura','Architektura','el estilo barroco','styl barokowy'),
('Arquitectura','Architektura','el estilo renacentista','styl renesansowy'),
('Arquitectura','Architektura','el estilo modernista','styl modernistyczny'),
('Arquitectura','Architektura','el espacio','przestrzeń'),
('Arquitectura','Architektura','la luz','światło'),
('Arquitectura','Architektura','el urbanismo','urbanistyka'),
('Arquitectura','Architektura','el plano de planta','rzut poziomy'),
('Arquitectura','Architektura','la estructura','struktura / szkielet'),
('Fotografía','Fotografia','la fotografía','fotografia'),
('Fotografía','Fotografia','la foto','zdjęcie'),
('Fotografía','Fotografia','el fotógrafo','fotograf'),
('Fotografía','Fotografia','la cámara (fotográfica)','aparat (fotograficzny)'),
('Fotografía','Fotografia','el objetivo / la lente','obiektyw / soczewka'),
('Fotografía','Fotografia','el flash','flesz / lampa błyskowa'),
('Fotografía','Fotografia','el trípode','statyw'),
('Fotografía','Fotografia','el enfoque','ostrość / punkt ostrości'),
('Fotografía','Fotografia','enfocar','ustawiać ostrość'),
('Fotografía','Fotografia','el encuadre','kadr'),
('Fotografía','Fotografia','la luz','światło'),
('Fotografía','Fotografia','la iluminación','oświetlenie'),
('Fotografía','Fotografia','el contraste','kontrast'),
('Fotografía','Fotografia','la exposición','ekspozycja'),
('Fotografía','Fotografia','el diafragma','przesłona'),
('Fotografía','Fotografia','la velocidad de obturación','czas naświetlania'),
('Fotografía','Fotografia','el sensor','matryca (w aparacie)'),
('Fotografía','Fotografia','el carrete','klisza / film'),
('Fotografía','Fotografia','revelar','wywoływać (zdjęcia)'),
('Fotografía','Fotografia','el cuarto oscuro','ciemnia'),
('Fotografía','Fotografia','el álbum','album'),
('Fotografía','Fotografia','el retrato','portret'),
('Fotografía','Fotografia','el paisaje','pejzaż'),
('Fotografía','Fotografia','la fotografía en blanco y negro','fotografia czarno-biała'),
('Fotografía','Fotografia','la fotografía en color','fotografia kolorowa'),
('Fotografía','Fotografia','el primer plano','pierwszy plan / zbliżenie'),
('Fotografía','Fotografia','el fondo','tło'),
('Fotografía','Fotografia','el píxel','piksel'),
('Fotografía','Fotografia','la resolución','rozdzielczość'),
('Fotografía','Fotografia','el archivo','plik (np. ze zdjęciem)'),
('Fotografía','Fotografia','editar','edytować'),
('Fotografía','Fotografia','retocar','retuszować'),
('Fotografía','Fotografia','el filtro','filtr'),
('Fotografía','Fotografia','el modelo / la modelo','model / modelka'),
('Fotografía','Fotografia','posar','pozować'),
('Fotografía','Fotografia','el estudio fotográfico','studio fotograficzne'),
('Fotografía','Fotografia','la instantánea','zdjęcie natychmiastowe / polaroid'),
('Fotografía','Fotografia','el fotoperiodismo','fotoreportaż'),
('Fotografía','Fotografia','hacer una foto / sacar una foto','robić zdjęcie'),
('Fotografía','Fotografia','borrar','kasować'),
('Fotografía','Fotografia','guardar','zapisywać'),
('Fotografía','Fotografia','capturar','uchwycić'),
('Fotografía','Fotografia','la nitidez','ostrość (zdjęcia)'),
('Fotografía','Fotografia','desenfocado','rozmazany / nieostry'),
('Fotografía','Fotografia','nítido','ostry / wyraźny'),
('Fotografía','Fotografia','el gran angular','obiektyw szerokokątny'),
('Fotografía','Fotografia','el teleobjetivo','teleobiektyw'),
('Fotografía','Fotografia','la tarjeta de memoria','karta pamięci'),
('Fotografía','Fotografia','el autorretrato / el selfi','autoportret / selfie'),
('Fotografía','Fotografia','el visor','wizjer'),
('Géneros Literarios','Gatunki literackie','la literatura','literatura'),
('Géneros Literarios','Gatunki literackie','el género literario','gatunek literacki'),
('Géneros Literarios','Gatunki literackie','la novela','powieść'),
('Géneros Literarios','Gatunki literackie','la novela histórica','powieść historyczna'),
('Géneros Literarios','Gatunki literackie','la novela policíaca','powieść kryminalna'),
('Géneros Literarios','Gatunki literackie','la novela romántica','romans'),
('Géneros Literarios','Gatunki literackie','la ciencia ficción','science fiction'),
('Géneros Literarios','Gatunki literackie','la fantasía','fantasy'),
('Géneros Literarios','Gatunki literackie','el cuento','opowiadanie / bajka'),
('Géneros Literarios','Gatunki literackie','el relato','opowiadanie / relacja'),
('Géneros Literarios','Gatunki literackie','la leyenda','legenda'),
('Géneros Literarios','Gatunki literackie','el mito','mit'),
('Géneros Literarios','Gatunki literackie','la fábula','bajka (ze zwierzętami i morałem)'),
('Géneros Literarios','Gatunki literackie','el poema','wiersz'),
('Géneros Literarios','Gatunki literackie','la poesía','poezja'),
('Géneros Literarios','Gatunki literackie','el poeta','poeta'),
('Géneros Literarios','Gatunki literackie','el drama','dramat'),
('Géneros Literarios','Gatunki literackie','la comedia','komedia'),
('Géneros Literarios','Gatunki literackie','la tragedia','tragedia'),
('Géneros Literarios','Gatunki literackie','el ensayo','esej'),
('Géneros Literarios','Gatunki literackie','la biografía','biografia'),
('Géneros Literarios','Gatunki literackie','la autobiografía','autobiografia'),
('Géneros Literarios','Gatunki literackie','el diario','dziennik / pamiętnik'),
('Géneros Literarios','Gatunki literackie','las memorias','wspomnienia'),
('Géneros Literarios','Gatunki literackie','la crónica','kronika'),
('Géneros Literarios','Gatunki literackie','el artículo','artykuł'),
('Géneros Literarios','Gatunki literackie','la prosa','proza'),
('Géneros Literarios','Gatunki literackie','el verso','wers / wiersz'),
('Géneros Literarios','Gatunki literackie','la estrofa','zwrotka'),
('Géneros Literarios','Gatunki literackie','la rima','rym'),
('Géneros Literarios','Gatunki literackie','la métrica','metryka / rytm'),
('Géneros Literarios','Gatunki literackie','el narrador','narrator'),
('Géneros Literarios','Gatunki literackie','el protagonista','główny bohater'),
('Géneros Literarios','Gatunki literackie','el antagonista','antagonista / wróg'),
('Géneros Literarios','Gatunki literackie','el personaje','postać'),
('Géneros Literarios','Gatunki literackie','la trama','fabuła / intryga'),
('Géneros Literarios','Gatunki literackie','el argumento','streszczenie / treść'),
('Géneros Literarios','Gatunki literackie','el clímax','punkt kulminacyjny'),
('Géneros Literarios','Gatunki literackie','el desenlace','zakończenie / rozwiązanie'),
('Géneros Literarios','Gatunki literackie','el diálogo','dialog'),
('Géneros Literarios','Gatunki literackie','el monólogo','monolog'),
('Géneros Literarios','Gatunki literackie','la metáfora','metafora'),
('Géneros Literarios','Gatunki literackie','la obra literaria','dzieło literackie'),
('Géneros Literarios','Gatunki literackie','el autor','autor'),
('Géneros Literarios','Gatunki literackie','el escritor','pisarz'),
('Géneros Literarios','Gatunki literackie','la editorial','wydawnictwo'),
('Géneros Literarios','Gatunki literackie','publicar','publikować'),
('Géneros Literarios','Gatunki literackie','el best seller','bestseller'),
('Géneros Literarios','Gatunki literackie','el capítulo','rozdział'),
('Géneros Literarios','Gatunki literackie','el índice','spis treści'),
('El Periódico','Gazeta','el periódico','gazeta'),
('El Periódico','Gazeta','la revista','magazyn / czasopismo'),
('El Periódico','Gazeta','la prensa','prasa'),
('El Periódico','Gazeta','la noticia','wiadomość'),
('El Periódico','Gazeta','el periodista','dziennikarz'),
('El Periódico','Gazeta','la periodista','dziennikarka'),
('El Periódico','Gazeta','el artículo','artykuł'),
('El Periódico','Gazeta','el titular','nagłówek'),
('El Periódico','Gazeta','la portada','okładka / pierwsza strona'),
('El Periódico','Gazeta','la columna','kolumna'),
('El Periódico','Gazeta','el editorial','artykuł wstępny (edytorial)'),
('El Periódico','Gazeta','la entrevista','wywiad'),
('El Periódico','Gazeta','el reportaje','reportaż'),
('El Periódico','Gazeta','el reportero','reporter'),
('El Periódico','Gazeta','la sección','sekcja / dział'),
('El Periódico','Gazeta','las noticias locales','wiadomości lokalne'),
('El Periódico','Gazeta','las noticias internacionales','wiadomości międzynarodowe'),
('El Periódico','Gazeta','la sección de deportes','dział sportowy'),
('El Periódico','Gazeta','la sección de economía','dział gospodarczy'),
('El Periódico','Gazeta','la cultura','kultura'),
('El Periódico','Gazeta','el anuncio','ogłoszenie / reklama'),
('El Periódico','Gazeta','los clasificados','ogłoszenia drobne'),
('El Periódico','Gazeta','la tira cómica','komiks / pasek komiksowy'),
('El Periódico','Gazeta','el crucigrama','krzyżówka'),
('El Periódico','Gazeta','el horóscopo','horoskop'),
('El Periódico','Gazeta','el quiosco','kiosk'),
('El Periódico','Gazeta','el suscriptor','prenumerator'),
('El Periódico','Gazeta','la suscripción','prenumerata / subskrypcja'),
('El Periódico','Gazeta','publicar','publikować'),
('El Periódico','Gazeta','editar','edytować / wydawać'),
('El Periódico','Gazeta','el editor','redaktor / wydawca'),
('El Periódico','Gazeta','el redactor','redaktor (piszący)'),
('El Periódico','Gazeta','la redacción','redakcja'),
('El Periódico','Gazeta','la fuente','źródło (informacji)'),
('El Periódico','Gazeta','la objetividad','obiektywizm'),
('El Periódico','Gazeta','la censura','cenzura'),
('El Periódico','Gazeta','el tabloide','tabloid'),
('El Periódico','Gazeta','la tirada','nakład'),
('El Periódico','Gazeta','imprimir','drukować'),
('El Periódico','Gazeta','la imprenta','drukarnia'),
('El Periódico','Gazeta','el suplemento','dodatek (do gazety)'),
('El Periódico','Gazeta','la crítica','recenzja / krytyka'),
('El Periódico','Gazeta','la exclusiva','materiał na wyłączność (exclusive)'),
('El Periódico','Gazeta','el chisme / el cotilleo','plotka'),
('El Periódico','Gazeta','la prensa amarilla','prasa brukowa'),
('El Periódico','Gazeta','el corresponsal','korespondent'),
('El Periódico','Gazeta','el fotógrafo','fotograf'),
('El Periódico','Gazeta','leer','czytać'),
('El Periódico','Gazeta','hojear','kartkować'),
('El Periódico','Gazeta','enterarse','dowiadywać się'),
('Televisión y Radio','Telewizja i Radio','la televisión / la tele','telewizja'),
('Televisión y Radio','Telewizja i Radio','el televisor','telewizor'),
('Televisión y Radio','Telewizja i Radio','la radio','radio'),
('Televisión y Radio','Telewizja i Radio','el programa','program'),
('Televisión y Radio','Telewizja i Radio','el canal','kanał'),
('Televisión y Radio','Telewizja i Radio','la emisora','stacja (radiowa)'),
('Televisión y Radio','Telewizja i Radio','la cadena','sieć (telewizyjna/radiowa)'),
('Televisión y Radio','Telewizja i Radio','el mando a distancia','pilot (do telewizora)'),
('Televisión y Radio','Telewizja i Radio','la pantalla','ekran'),
('Televisión y Radio','Telewizja i Radio','el volumen','głośność'),
('Televisión y Radio','Telewizja i Radio','encender','włączać'),
('Televisión y Radio','Telewizja i Radio','apagar','wyłączać'),
('Televisión y Radio','Telewizja i Radio','cambiar de canal','zmieniać kanał'),
('Televisión y Radio','Telewizja i Radio','el telediario / las noticias','dziennik / wiadomości'),
('Televisión y Radio','Telewizja i Radio','la serie','serial'),
('Televisión y Radio','Telewizja i Radio','la telenovela','telenowela'),
('Televisión y Radio','Telewizja i Radio','el documental','film dokumentalny'),
('Televisión y Radio','Telewizja i Radio','el concurso','teleturniej'),
('Televisión y Radio','Telewizja i Radio','el programa de entrevistas','talk-show'),
('Televisión y Radio','Telewizja i Radio','los dibujos animados','kreskówki'),
('Televisión y Radio','Telewizja i Radio','la película','film'),
('Televisión y Radio','Telewizja i Radio','el anuncio','reklama'),
('Televisión y Radio','Telewizja i Radio','la pausa publicitaria','przerwa na reklamę'),
('Televisión y Radio','Telewizja i Radio','el presentador','prezenter'),
('Televisión y Radio','Telewizja i Radio','el locutor','spiker / prezenter radiowy'),
('Televisión y Radio','Telewizja i Radio','la audiencia','widownia / słuchacze'),
('Televisión y Radio','Telewizja i Radio','el espectador','widz'),
('Televisión y Radio','Telewizja i Radio','el oyente','słuchacz'),
('Televisión y Radio','Telewizja i Radio','el micrófono','mikrofon'),
('Televisión y Radio','Telewizja i Radio','la antena','antena'),
('Televisión y Radio','Telewizja i Radio','transmitir / emitir','nadawać / emitować'),
('Televisión y Radio','Telewizja i Radio','la transmisión / la emisión','emisja / transmisja'),
('Televisión y Radio','Telewizja i Radio','en directo / en vivo','na żywo'),
('Televisión y Radio','Telewizja i Radio','grabado','nagrany'),
('Televisión y Radio','Telewizja i Radio','el episodio','odcinek'),
('Televisión y Radio','Telewizja i Radio','la temporada','sezon (serialu)'),
('Televisión y Radio','Telewizja i Radio','sintonizar','dostroić / włączyć stację'),
('Televisión y Radio','Telewizja i Radio','el dial','tarcza (w radiu) / częstotliwość'),
('Televisión y Radio','Telewizja i Radio','el podcast','podcast'),
('Televisión y Radio','Telewizja i Radio','el volumen alto','wysoka głośność'),
('Televisión y Radio','Telewizja i Radio','el volumen bajo','niska głośność'),
('Televisión y Radio','Telewizja i Radio','subir el volumen','zgłośnić'),
('Televisión y Radio','Telewizja i Radio','bajar el volumen','ściszyć'),
('Televisión y Radio','Telewizja i Radio','el satélite','satelita'),
('Televisión y Radio','Telewizja i Radio','la televisión por cable','telewizja kablowa'),
('Televisión y Radio','Telewizja i Radio','la programación','ramówka / program'),
('Televisión y Radio','Telewizja i Radio','el guion','scenariusz'),
('Televisión y Radio','Telewizja i Radio','el plató','studio telewizyjne'),
('Televisión y Radio','Telewizja i Radio','los subtítulos','napisy'),
('Televisión y Radio','Telewizja i Radio','el doblaje','dubbing'),
('Cine y Teatro','Kino i Teatr','el cine','kino'),
('Cine y Teatro','Kino i Teatr','el teatro','teatr'),
('Cine y Teatro','Kino i Teatr','la película','film'),
('Cine y Teatro','Kino i Teatr','la obra de teatro','sztuka teatralna'),
('Cine y Teatro','Kino i Teatr','el actor','aktor'),
('Cine y Teatro','Kino i Teatr','la actriz','aktorka'),
('Cine y Teatro','Kino i Teatr','el director','reżyser'),
('Cine y Teatro','Kino i Teatr','dirigir','reżyserować'),
('Cine y Teatro','Kino i Teatr','el guion','scenariusz'),
('Cine y Teatro','Kino i Teatr','el guionista','scenarzysta'),
('Cine y Teatro','Kino i Teatr','el escenario','scena'),
('Cine y Teatro','Kino i Teatr','el telón','kurtyna'),
('Cine y Teatro','Kino i Teatr','la pantalla','ekran'),
('Cine y Teatro','Kino i Teatr','la butaca','fotel (w kinie/teatrze)'),
('Cine y Teatro','Kino i Teatr','la fila','rząd'),
('Cine y Teatro','Kino i Teatr','el pasillo','korytarz / przejście'),
('Cine y Teatro','Kino i Teatr','la entrada','bilet'),
('Cine y Teatro','Kino i Teatr','la taquilla','kasa biletowa'),
('Cine y Teatro','Kino i Teatr','el acomodador','bileter'),
('Cine y Teatro','Kino i Teatr','el estreno','premiera'),
('Cine y Teatro','Kino i Teatr','la cartelera','repertuar'),
('Cine y Teatro','Kino i Teatr','el espectador','widz'),
('Cine y Teatro','Kino i Teatr','el público','publiczność'),
('Cine y Teatro','Kino i Teatr','aplaudir','klaskać'),
('Cine y Teatro','Kino i Teatr','el aplauso','oklaski'),
('Cine y Teatro','Kino i Teatr','actuar','grać (rolę)'),
('Cine y Teatro','Kino i Teatr','la actuación','występ / gra aktorska'),
('Cine y Teatro','Kino i Teatr','el personaje','postać'),
('Cine y Teatro','Kino i Teatr','el protagonista','główny bohater'),
('Cine y Teatro','Kino i Teatr','el papel','rola'),
('Cine y Teatro','Kino i Teatr','el ensayo','próba'),
('Cine y Teatro','Kino i Teatr','ensayar','odbywać próbę'),
('Cine y Teatro','Kino i Teatr','el camerino','garderoba'),
('Cine y Teatro','Kino i Teatr','el maquillaje','makijaż / charakteryzacja'),
('Cine y Teatro','Kino i Teatr','el vestuario','kostiumy'),
('Cine y Teatro','Kino i Teatr','el decorado','dekoracja / scenografia'),
('Cine y Teatro','Kino i Teatr','la iluminación','oświetlenie'),
('Cine y Teatro','Kino i Teatr','los efectos especiales','efekty specjalne'),
('Cine y Teatro','Kino i Teatr','la banda sonora','ścieżka dźwiękowa'),
('Cine y Teatro','Kino i Teatr','el tráiler','zwiastun'),
('Cine y Teatro','Kino i Teatr','el cortometraje','film krótkometrażowy'),
('Cine y Teatro','Kino i Teatr','el largometraje','film pełnometrażowy'),
('Cine y Teatro','Kino i Teatr','la comedia','komedia'),
('Cine y Teatro','Kino i Teatr','el drama','dramat'),
('Cine y Teatro','Kino i Teatr','el musical','musical'),
('Cine y Teatro','Kino i Teatr','el intermedio','przerwa / antrakt'),
('Cine y Teatro','Kino i Teatr','las palomitas','popcorn'),
('Cine y Teatro','Kino i Teatr','el premio','nagroda'),
('Cine y Teatro','Kino i Teatr','nominar','nominować'),
('Cine y Teatro','Kino i Teatr','rodar','kręcić (film)'),
('Profesiones Médicas','Zawody medyczne','el médico / la médica','lekarz / lekarka'),
('Profesiones Médicas','Zawody medyczne','el enfermero / la enfermera','pielęgniarz / pielęgniarka'),
('Profesiones Médicas','Zawody medyczne','el cirujano','chirurg'),
('Profesiones Médicas','Zawody medyczne','el anestesista','anestezjolog'),
('Profesiones Médicas','Zawody medyczne','el pediatra','pediatra'),
('Profesiones Médicas','Zawody medyczne','el cardiólogo','kardiolog'),
('Profesiones Médicas','Zawody medyczne','el dermatólogo','dermatolog'),
('Profesiones Médicas','Zawody medyczne','el ginecólogo','ginekolog'),
('Profesiones Médicas','Zawody medyczne','el obstetra','położnik'),
('Profesiones Médicas','Zawody medyczne','la matrona','położna'),
('Profesiones Médicas','Zawody medyczne','el neurólogo','neurolog'),
('Profesiones Médicas','Zawody medyczne','el psiquiatra','psychiatra'),
('Profesiones Médicas','Zawody medyczne','el psicólogo','psycholog'),
('Profesiones Médicas','Zawody medyczne','el oftalmólogo','okulista'),
('Profesiones Médicas','Zawody medyczne','el dentista / el odontólogo','dentysta / stomatolog'),
('Profesiones Médicas','Zawody medyczne','el ortodoncista','ortodonta'),
('Profesiones Médicas','Zawody medyczne','el traumatólogo','traumatolog / ortopeda'),
('Profesiones Médicas','Zawody medyczne','el fisioterapeuta','fizjoterapeuta'),
('Profesiones Médicas','Zawody medyczne','el farmacéutico','farmaceuta'),
('Profesiones Médicas','Zawody medyczne','el veterinario','weterynarz'),
('Profesiones Médicas','Zawody medyczne','el oncólogo','onkolog'),
('Profesiones Médicas','Zawody medyczne','el urólogo','urolog'),
('Profesiones Médicas','Zawody medyczne','el endocrino','endokrynolog'),
('Profesiones Médicas','Zawody medyczne','el alergólogo','alergolog'),
('Profesiones Médicas','Zawody medyczne','el neumólogo','pulmonolog'),
('Profesiones Médicas','Zawody medyczne','el gastroenterólogo','gastrolog'),
('Profesiones Médicas','Zawody medyczne','el radiólogo','radiolog'),
('Profesiones Médicas','Zawody medyczne','el patólogo','patolog'),
('Profesiones Médicas','Zawody medyczne','el paramédico','ratownik medyczny'),
('Profesiones Médicas','Zawody medyczne','el asistente médico','asystent medyczny'),
('Profesiones Médicas','Zawody medyczne','el celador','sanitariusz (w szpitalu)'),
('Profesiones Médicas','Zawody medyczne','el nutricionista','dietetyk'),
('Profesiones Médicas','Zawody medyczne','el terapeuta ocupacional','terapeuta zajęciowy'),
('Profesiones Médicas','Zawody medyczne','el logopeda','logopeda'),
('Profesiones Médicas','Zawody medyczne','el podólogo','podolog'),
('Profesiones Médicas','Zawody medyczne','el quiropráctico','kręgarz / chiropraktyk'),
('Profesiones Médicas','Zawody medyczne','el cirujano plástico','chirurg plastyczny'),
('Profesiones Médicas','Zawody medyczne','el médico de cabecera','lekarz rodzinny'),
('Profesiones Médicas','Zawody medyczne','el médico de urgencias','lekarz pogotowia / ratunkowy'),
('Profesiones Médicas','Zawody medyczne','el hematólogo','hematolog'),
('Profesiones Médicas','Zawody medyczne','el reumatólogo','reumatolog'),
('Profesiones Médicas','Zawody medyczne','el nefrólogo','nefrolog'),
('Profesiones Médicas','Zawody medyczne','el otorrinolaringólogo','laryngolog'),
('Profesiones Médicas','Zawody medyczne','el epidemiólogo','epidemiolog'),
('Profesiones Médicas','Zawody medyczne','el inmunólogo','immunolog'),
('Profesiones Médicas','Zawody medyczne','el forense','lekarz medycyny sądowej'),
('Profesiones Médicas','Zawody medyczne','el técnico de laboratorio','technik laboratoryjny'),
('Profesiones Médicas','Zawody medyczne','el óptico','optyk'),
('Profesiones Médicas','Zawody medyczne','el osteópata','osteopata'),
('Profesiones Médicas','Zawody medyczne','el especialista','specjalista');
