insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Religiones del Mundo','Religie świata','la religión','religión'),
('Religiones del Mundo','Religie świata','la religión','religia'),
('Religiones del Mundo','Religie świata','la fe','wiara'),
('Religiones del Mundo','Religie świata','la creencia','przekonanie / wierzenie'),
('Religiones del Mundo','Religie świata','el dios','bóg'),
('Religiones del Mundo','Religie świata','la diosa','bogini'),
('Religiones del Mundo','Religie świata','lo divino','boskość'),
('Religiones del Mundo','Religie świata','el culto','kult'),
('Religiones del Mundo','Religie świata','el rito','rytuał'),
('Religiones del Mundo','Religie świata','la ceremonia','ceremonia'),
('Religiones del Mundo','Religie świata','la oración','modlitwa'),
('Religiones del Mundo','Religie świata','orar','modlić się'),
('Religiones del Mundo','Religie świata','el templo','świątynia'),
('Religiones del Mundo','Religie świata','la iglesia','kościół'),
('Religiones del Mundo','Religie świata','la mezquita','meczet'),
('Religiones del Mundo','Religie świata','la sinagoga','synagoga'),
('Religiones del Mundo','Religie świata','el templo budista','świątynia buddyjska'),
('Religiones del Mundo','Religie świata','el sacerdote','kapłan'),
('Religiones del Mundo','Religie świata','el pastor','pastor'),
('Religiones del Mundo','Religie świata','el imán','imam'),
('Religiones del Mundo','Religie świata','el rabino','rabin'),
('Religiones del Mundo','Religie świata','el monje','mnich'),
('Religiones del Mundo','Religie świata','la monja','mianich'),
('Religiones del Mundo','Religie świata','el papa','papież'),
('Religiones del Mundo','Religie świata','el obispo','biskup'),
('Religiones del Mundo','Religie świata','el cristiano','chrześcijanin'),
('Religiones del Mundo','Religie świata','el católico','katolik'),
('Religiones del Mundo','Religie świata','el protestante','protestant'),
('Religiones del Mundo','Religie świata','el musulmán','muzułmanin'),
('Religiones del Mundo','Religie świata','el judío','żyd'),
('Religiones del Mundo','Religie świata','el budista','buddysta'),
('Religiones del Mundo','Religie świata','el hinduista','hinduista'),
('Religiones del Mundo','Religie świata','la Biblia','Biblia'),
('Religiones del Mundo','Religie świata','el Corán','Koran'),
('Religiones del Mundo','Religie świata','la Torá','Tora'),
('Religiones del Mundo','Religie świata','el dogma','dogmat'),
('Religiones del Mundo','Religie świata','la salvación','zbawienie'),
('Religiones del Mundo','Religie świata','el pecado','grzech'),
('Religiones del Mundo','Religie świata','pecar','grzeszyć'),
('Religiones del Mundo','Religie świata','el perdón','przebaczenie'),
('Religiones del Mundo','Religie świata','el cielo','niebo'),
('Religiones del Mundo','Religie świata','el infierno','piekło'),
('Religiones del Mundo','Religie świata','el alma','dusza'),
('Religiones del Mundo','Religie świata','la reencarnación','reinkarnacja'),
('Religiones del Mundo','Religie świata','el milagro','cud'),
('Religiones del Mundo','Religie świata','la profecía','proroctwo'),
('Religiones del Mundo','Religie świata','el profeta','prorok'),
('Religiones del Mundo','Religie świata','la espiritualidad','duchowość'),
('Religiones del Mundo','Religie świata','el ateo','ateista'),
('Religiones del Mundo','Religie świata','el agnóstico','agnostyk'),
('Mitología','Mitologia','la mitología','mitologia'),
('Mitología','Mitologia','el mito','mit'),
('Mitología','Mitologia','la leyenda','legenda'),
('Mitología','Mitologia','el dios','bóg'),
('Mitología','Mitologia','la diosa','bogini'),
('Mitología','Mitologia','el semidiós','półbóg'),
('Mitología','Mitologia','el Héroe','bohater'),
('Mitología','Mitologia','el monstruo','potwór'),
('Mitología','Mitologia','el titán','tytan'),
('Mitología','Mitologia','la ninfa','nimfa'),
('Mitología','Mitologia','el dragón','smok'),
('Mitología','Mitologia','el Olimpo','Olimp'),
('Mitología','Mitologia','el inframundo','zaświaty / podziemia'),
('Mitología','Mitologia','el destino','przeznaczenie'),
('Mitología','Mitologia','la profecía','proroctwo'),
('Mitología','Mitologia','el hechizo','klątwa / czar'),
('Mitología','Mitologia','la magia','magia'),
('Mitología','Mitologia','la inmortalidad','nieśmiertelność'),
('Mitología','Mitologia','inmortal','nieśmiertelny'),
('Mitología','Mitologia','el Olimpo griego','grecki Olimp'),
('Mitología','Mitologia','Zeus','Zeus'),
('Mitología','Mitologia','Hera','Hera'),
('Mitología','Mitologia','Poseidón','Posejdon'),
('Mitología','Mitologia','Hades','Hades'),
('Mitología','Mitologia','Atenea','Ateny / Atena'),
('Mitología','Mitologia','Apolo','Apolo'),
('Mitología','Mitologia','Afrodita','Afrodyta'),
('Mitología','Mitologia','Ares','Ares'),
('Mitología','Mitologia','Hermes','Hermes'),
('Mitología','Mitologia','Dionisio','Dionizjusz / Dionizos'),
('Mitología','Mitologia','Hércules','Herkules'),
('Mitología','Mitologia','Aquiles','Achilles'),
('Mitología','Mitologia','Ulises / Odiseo','Odyseusz'),
('Mitología','Mitologia','Prometeo','Prometeusz'),
('Mitología','Mitologia','Medusa','Muza / Meduza'),
('Mitología','Mitologia','el Minotauro','Minotaur'),
('Mitología','Mitologia','el Pegaso','Pegaz'),
('Mitología','Mitologia','la Hidra','Hydra'),
('Mitología','Mitologia','la Quimera','Chimera'),
('Mitología','Mitologia','el laberinto','labirynt'),
('Mitología','Mitologia','el tridente','trójząb'),
('Mitología','Mitologia','el rayo','piorun (boga)'),
('Mitología','Mitologia','la ambrosía','ambrozja'),
('Mitología','Mitologia','el néctar','nektar (bogów)'),
('Mitología','Mitologia','la metamorfosis','metamorfoza'),
('Mitología','Mitologia','el panteón','panteon'),
('Mitología','Mitologia','la ofrenda','ofiara'),
('Mitología','Mitologia','el sacrificio','składanie ofiary'),
('Mitología','Mitologia','la epopeya','epopeja'),
('Mitología','Mitologia','el relato épico','opowieść epicka'),
('Filosofía','Filozofia','la filosofía','filozofia'),
('Filosofía','Filozofia','el filósofo','filozof'),
('Filosofía','Filozofia','pensar','myśleć'),
('Filosofía','Filozofia','el pensamiento','myśl'),
('Filosofía','Filozofia','la lógica','logika'),
('Filosofía','Filozofia','la ética','etyka'),
('Filosofía','Filozofia','la moral','moralność'),
('Filosofía','Filozofia','la metafísica','metafizyka'),
('Filosofía','Filozofia','la epistemología','epistemologia'),
('Filosofía','Filozofia','la ontología','ontologia'),
('Filosofía','Filozofia','la estética','estetyka'),
('Filosofía','Filozofia','la verdad','prawda'),
('Filosofía','Filozofia','la mentira','kłamstwo'),
('Filosofía','Filozofia','la realidad','rzeczywistość'),
('Filosofía','Filozofia','la existencia','egzystencja / istnienie'),
('Filosofía','Filozofia','el ser','byt / istota'),
('Filosofía','Filozofia','la conciencia','świadomość'),
('Filosofía','Filozofia','el conocimiento','wiedza'),
('Filosofía','Filozofia','la razón','rozum'),
('Filosofía','Filozofia','la sabiduría','mądrość'),
('Filosofía','Filozofia','el alma','dusza'),
('Filosofía','Filozofia','el espíritu','duch'),
('Filosofía','Filozofia','el libre albedrío','wolna wola'),
('Filosofía','Filozofia','el determinismo','determinizm'),
('Filosofía','Filozofia','el escepticismo','sceptycyzm'),
('Filosofía','Filozofia','el empirismo','empiryzm'),
('Filosofía','Filozofia','el racionalismo','racjonalizm'),
('Filosofía','Filozofia','el existencialismo','egzystencjalizm'),
('Filosofía','Filozofia','el estoicismo','stoicyzm'),
('Filosofía','Filozofia','el hedonismo','hedonizm'),
('Filosofía','Filozofia','el nihilismo','nihilizm'),
('Filosofía','Filozofia','el idealismo','idealizm'),
('Filosofía','Filozofia','el materialismo','materializm'),
('Filosofía','Filozofia','la dialéctica','dialektyka'),
('Filosofía','Filozofia','el argumento','argument'),
('Filosofía','Filozofia','la premisa','przesłanka'),
('Filosofía','Filozofia','la conclusión','wniosek'),
('Filosofía','Filozofia','la paradoja','paradoks'),
('Filosofía','Filozofia','el dilema','dylemat'),
('Filosofía','Filozofia','la hipótesis','hipoteza'),
('Filosofía','Filozofia','el sentido','sens'),
('Filosofía','Filozofia','el absurdo','absurd'),
('Filosofía','Filozofia','la libertad','wolność'),
('Filosofía','Filozofia','la justicia','sprawiedliwość'),
('Filosofía','Filozofia','la virtud','cnota'),
('Filosofía','Filozofia','el vicio','wada / grzech'),
('Filosofía','Filozofia','la felicidad','szczęście'),
('Filosofía','Filozofia','el bien','dobro'),
('Filosofía','Filozofia','el mal','zło'),
('Filosofía','Filozofia','la duda','wątpliwość'),
('Psicología','Psychologia','la psicología','psychologia'),
('Psicología','Psychologia','el psicólogo','psycholog'),
('Psicología','Psychologia','el psiquiatra','psychiatra'),
('Psicología','Psychologia','el psicoanálisis','psychoanaliza'),
('Psicología','Psychologia','la mente','umysł'),
('Psicología','Psychologia','el cerebro','mózg'),
('Psicología','Psychologia','la conducta','zachowanie'),
('Psicología','Psychologia','el comportamiento','postawa / zachowanie'),
('Psicología','Psychologia','la emoción','emocja'),
('Psicología','Psychologia','el sentimiento','uczucie'),
('Psicología','Psychologia','la personalidad','osobowość'),
('Psicología','Psychologia','el carácter','charakter'),
('Psicología','Psychologia','el temperamento','temperament'),
('Psicología','Psychologia','el subconsciente','podświadomość'),
('Psicología','Psychologia','el inconsciente','nieświadomość'),
('Psicología','Psychologia','el trauma','trauma'),
('Psicología','Psychologia','la ansiedad','lęk / stan lękowy'),
('Psicología','Psychologia','la depresión','depresja'),
('Psicología','Psychologia','el estrés','stres'),
('Psicología','Psychologia','la terapia','terapia'),
('Psicología','Psychologia','el terapeuta','terapeuta'),
('Psicología','Psychologia','la psicoterapia','psychoterapia'),
('Psicología','Psychologia','el trastorno','zaburzenie'),
('Psicología','Psychologia','la fobia','fobia'),
('Psicología','Psychologia','la obsesión','obsesja'),
('Psicología','Psychologia','la compulsión','kompulsja'),
('Psicología','Psychologia','la autoestima','poczucie własnej wartości'),
('Psicología','Psychologia','el ego','ego'),
('Psicología','Psychologia','la empatía','empatia'),
('Psicología','Psychologia','la motivación','motywacja'),
('Psicología','Psychologia','el estímulo','bodziec'),
('Psicología','Psychologia','la respuesta','reakcja'),
('Psicología','Psychologia','el aprendizaje','nauka / uczenie się'),
('Psicología','Psychologia','la memoria','pamięć'),
('Psicología','Psychologia','el olvido','zapominanie'),
('Psicología','Psychologia','la percepción','percepcja'),
('Psicología','Psychologia','la cognición','poznanie / kognicja'),
('Psicología','Psychologia','el desarrollo','rozwój'),
('Psicología','Psychologia','la inteligencia','inteligencja'),
('Psicología','Psychologia','la creatividad','kreatywność'),
('Psicología','Psychologia','el complejo','kompleks'),
('Psicología','Psychologia','la introversión','introwersja'),
('Psicología','Psychologia','la extroversión','ekstrawersja'),
('Psicología','Psychologia','la frustracion','frustracja'),
('Psicología','Psychologia','el conflicto','konflikt'),
('Psicología','Psychologia','la defensa','obrona (psychologiczna)'),
('Psicología','Psychologia','la resiliencia','odporność psychiczna / rezyliencja'),
('Psicología','Psychologia','la psicosis','psychoza'),
('Psicología','Psychologia','la neurosis','neuroza'),
('Psicología','Psychologia','el bienestar','dobrostan'),
('Sociología','Socjologia','la sociología','socjologia'),
('Sociología','Socjologia','la sociedad','społeczeństwo'),
('Sociología','Socjologia','el grupo social','grupa społeczna'),
('Sociología','Socjologia','la comunidad','społeczność / wspólnota'),
('Sociología','Socjologia','la cultura','kultura'),
('Sociología','Socjologia','la norma','norma społeczna'),
('Sociología','Socjologia','el valor','wartość'),
('Sociología','Socjologia','la costumbre','obyczaj / zwyczaj'),
('Sociología','Socjologia','la tradición','tradycja'),
('Sociología','Socjologia','la clase social','klasa społeczna'),
('Sociología','Socjologia','la clase alta','klasa wyższa'),
('Sociología','Socjologia','la clase media','klasa średnia'),
('Sociología','Socjologia','la clase baja','klasa niższa'),
('Sociología','Socjologia','la estratificación','warstwowanie społeczne'),
('Sociología','Socjologia','la desigualdad','nierówność społeczna'),
('Sociología','Socjologia','la movilidad social','mobilność społeczna'),
('Sociología','Socjologia','la pobreza','ubóstwo'),
('Sociología','Socjologia','la riqueza','bogactwo'),
('Sociología','Socjologia','la marginación','marginalizacja'),
('Sociología','Socjologia','la exclusión social','wykluczenie społeczne'),
('Sociología','Socjologia','la integración','integracja'),
('Sociología','Socjologia','la asimilación','asymilacja'),
('Sociología','Socjologia','la inmigración','imigracja'),
('Sociología','Socjologia','la emigración','emigracja'),
('Sociología','Socjologia','el demografía','demografia'),
('Sociología','Socjologia','la población','populacja / ludność'),
('Sociología','Socjologia','el censo','spis powszechny'),
('Sociología','Socjologia','la natalidad','urodzenia / wskaźnik urodzeń'),
('Sociología','Socjologia','la mortalidad','śmiertelność'),
('Sociología','Socjologia','la urbanización','urbanizacja'),
('Sociología','Socjologia','el cambio social','zmiana społeczna'),
('Sociología','Socjologia','el conflicto social','konflikt społeczny'),
('Sociología','Socjologia','la interacción','interakcja'),
('Sociología','Socjologia','la socialización','socjalizacja'),
('Sociología','Socjologia','el rol social','rola społeczna'),
('Sociología','Socjologia','el estatus','status społeczny'),
('Sociología','Socjologia','la opinión pública','opinia publiczna'),
('Sociología','Socjologia','los medios de comunicación','media masowe'),
('Sociología','Socjologia','la globalización','globalizacja'),
('Sociología','Socjologia','la multiculturalidad','multikulturowość'),
('Sociología','Socjologia','el género','płeć społeczno-kulturowa (gender)'),
('Sociología','Socjologia','el feminismo','feminizm'),
('Sociología','Socjologia','el patriarcado','patriarchat'),
('Sociología','Socjologia','la familia','rodzina'),
('Sociología','Socjologia','el matrimonio','małżeństwo'),
('Sociología','Socjologia','el individuo','jednostka'),
('Sociología','Socjologia','la colectividad','zbiorowość'),
('Sociología','Socjologia','la red social','sieć społeczna'),
('Sociología','Socjologia','la burocracia','biurokracja'),
('Sociología','Socjologia','la institución','instytucja'),
('Geografía Política','Geografia polityczna','la geografía política','geografia polityczna'),
('Geografía Política','Geografia polityczna','el estado','państwo'),
('Geografía Política','Geografia polityczna','la nación','naród'),
('Geografía Política','Geografia polityczna','la frontera','granica'),
('Geografía Política','Geografia polityczna','el territorio','terytorium'),
('Geografía Política','Geografia polityczna','la soberanía','suwerenność'),
('Geografía Política','Geografia polityczna','el gobierno','rząd'),
('Geografía Política','Geografia polityczna','la capital','stolica'),
('Geografía Política','Geografia polityczna','la provincia','prowincja'),
('Geografía Política','Geografia polityczna','la región','region'),
('Geografía Política','Geografia polityczna','el municipio','gmina / miasto'),
('Geografía Política','Geografia polityczna','la autonomía','autonomia'),
('Geografía Política','Geografia polityczna','la federación','federacja'),
('Geografía Política','Geografia polityczna','el estado federal','państwo federacyjne'),
('Geografía Política','Geografia polityczna','la república','republika'),
('Geografía Política','Geografia polityczna','la monarquía','monarchia'),
('Geografía Política','Geografia polityczna','el imperio','imperium'),
('Geografía Política','Geografia polityczna','la colonia','kolonia'),
('Geografía Política','Geografia polityczna','el protectorado','protektorat'),
('Geografía Política','Geografia polityczna','el enclave','enklawa'),
('Geografía Política','Geografia polityczna','el exclave','eksklawa'),
('Geografía Política','Geografia polityczna','el conflicto fronterizo','konflikt graniczny'),
('Geografía Política','Geografia polityczna','la disputa territorial','spór terytorialny'),
('Geografía Política','Geografia polityczna','la geopolítica','geopolitika'),
('Geografía Política','Geografia polityczna','la influencia','wpływ / strefa wpływów'),
('Geografía Política','Geografia polityczna','la alianza','sojusz'),
('Geografía Política','Geografia polityczna','el tratado','traktat międzynarodowy'),
('Geografía Política','Geografia polityczna','la organización internacional','organizacja międzynarodowa'),
('Geografía Política','Geografia polityczna','la diplomacia','dyplomacja'),
('Geografía Política','Geografia polityczna','la embajada','ambasada'),
('Geografía Política','Geografia polityczna','el consulado','konsulat'),
('Geografía Política','Geografia polityczna','el embajador','ambasador'),
('Geografía Política','Geografia polityczna','el pasaporte','paszport'),
('Geografía Política','Geografia polityczna','el visado','wiza'),
('Geografía Política','Geografia polityczna','el control fronterizio','kontrola graniczna'),
('Geografía Política','Geografia polityczna','la independencia','niepodległość'),
('Geografía Política','Geografia polityczna','la secesja','secesja'),
('Geografía Política','Geografia polityczna','el referéndum','referendum'),
('Geografía Política','Geografia polityczna','el mapa político','mapa polityczna'),
('Geografía Política','Geografia polityczna','el hemisferio','półkula'),
('Geografía Política','Geografia polityczna','el bloque','blok (polityczny)'),
('Geografía Política','Geografia polityczna','la superpotencia','supermocarstwo'),
('Geografía Política','Geografia polityczna','el país en desarrollo','kraj rozwijający się'),
('Geografía Política','Geografia polityczna','el país desarrollado','kraj rozwinięty'),
('Geografía Política','Geografia polityczna','la descolonización','dekolonizacja'),
('Geografía Política','Geografia polityczna','la unificación','zjednoczenie'),
('Geografía Política','Geografia polityczna','la particja','podział / rozbiór'),
('Geografía Política','Geografia polityczna','la expansión','ekspansja'),
('Geografía Política','Geografia polityczna','la hegemonía','hegemonia'),
('Geografía Política','Geografia polityczna','la globalización','globalizacja'),
('Países y Nacionalidades','Kraje i narodowości','el país','kraj'),
('Países y Nacionalidades','Kraje i narodowości','la nacionalidad','narodowość'),
('Países y Nacionalidades','Kraje i narodowości','el extranjero','zagranica / obcokrajowiec'),
('Países y Nacionalidades','Kraje i narodowości','España','Hiszpania'),
('Países y Nacionalidades','Kraje i narodowości','español / española','hiszpański / hiszpanka'),
('Países y Nacionalidades','Kraje i narodowości','Polonia','Polska'),
('Países y Nacionalidades','Kraje i narodowości','polaco / polaca','polski / polka'),
('Países y Nacionalidades','Kraje i narodowości','México','Meksyk'),
('Países y Nacionalidades','Kraje i narodowości','mexicano / mexicana','meksykański / meksykanka'),
('Países y Nacionalidades','Kraje i narodowości','Argentina','Argentyna'),
('Países y Nacionalidades','Kraje i narodowości','argentino / argentina','argentyński / argentyntka'),
('Países y Nacionalidades','Kraje i narodowości','Colombia','Kolumbia'),
('Países y Nacionalidades','Kraje i narodowości','colombiano / colombiana','kolumbijski / kolumbijka'),
('Países y Nacionalidades','Kraje i narodowości','Estados Unidos','Stany Zjednoczone'),
('Países y Nacionalidades','Kraje i narodowości','estadounidense','amerykański / amerykańska'),
('Países y Nacionalidades','Kraje i narodowości','Francia','Francja'),
('Países y Nacionalidades','Kraje i narodowości','francés / francesa','francuski / francuzka'),
('Países y Nacionalidades','Kraje i narodowości','Alemania','Niemcy'),
('Países y Nacionalidades','Kraje i narodowości','alemán / alemana','niemiecki / niemka'),
('Países y Nacionalidades','Kraje i narodowości','Italia','Włochy'),
('Países y Nacionalidades','Kraje i narodowości','italiano / italiana','włoski / włoszka'),
('Países y Nacionalidades','Kraje i narodowości','Reino Unido','Wielka Brytania'),
('Países y Nacionalidades','Kraje i narodowości','británico / británica','brytyjski / brytyjka'),
('Países y Nacionalidades','Kraje i narodowości','China','Chiny'),
('Países y Nacionalidades','Kraje i narodowości','chino / china','chiński / Chinka'),
('Países y Nacionalidades','Kraje i narodowości','Japón','Japonia'),
('Países y Nacionalidades','Kraje i narodowości','japonés / japonesa','japoński / japonka'),
('Países y Nacionalidades','Kraje i narodowości','Brasil','Brazylia'),
('Países y Nacionalidades','Kraje i narodowości','brasileño / brasileña','brazylijski / brazylijka'),
('Países y Nacionalidades','Kraje i narodowości','Rusia','Rosja'),
('Países y Nacionalidades','Kraje i narodowości','ruso / rusa','rosyjski / rosjanka'),
('Países y Nacionalidades','Kraje i narodowości','Canadá','Kanada'),
('Países y Nacionalidades','Kraje i narodowości','canadiense','kanadyjski / kanadyjka'),
('Países y Nacionalidades','Kraje i narodowości','Australia','Australia'),
('Países y Nacionalidades','Kraje i narodowości','australiano / australiana','australijski / australijka'),
('Países y Nacionalidades','Kraje i narodowości','Egipto','Egipt'),
('Países y Nacionalidades','Kraje i narodowości','egipcio / egipcia','egipski / egipcjanka'),
('Países y Nacionalidades','Kraje i narodowości','India','Indie'),
('Países y Nacionalidades','Kraje i narodowości','indio / india','indyjski / indyjka'),
('Países y Nacionalidades','Kraje i narodowości','Grecia','Grecja'),
('Países y Nacionalidades','Kraje i narodowości','griego / griega','grecki / greczynka'),
('Países y Nacionalidades','Kraje i narodowości','Turquía','Turcja'),
('Países y Nacionalidades','Kraje i narodowości','turco / turca','turecki / turczynka'),
('Países y Nacionalidades','Kraje i narodowości','Portugal','Portugalia'),
('Países y Nacionalidades','Kraje i narodowości','portugués / portuguesa','portugalski / portugalka'),
('Países y Nacionalidades','Kraje i narodowości','Suecia','Szwecja'),
('Países y Nacionalidades','Kraje i narodowości','sueco / sueca','szwedzki / szwedka'),
('Países y Nacionalidades','Kraje i narodowości','Suiza','Szwajcaria'),
('Países y Nacionalidades','Kraje i narodowości','suizo / suiza','szwajcarski / szwajcarka'),
('Idiomas','Języki','el idioma','język'),
('Idiomas','Języki','la lengua','język (mowa)'),
('Idiomas','Języki','el español / el castellano','język hiszpanśki'),
('Idiomas','Języki','el polaco','język polski'),
('Idiomas','Języki','el inglés','język angielski'),
('Idiomas','Języki','el francés','język francuski'),
('Idiomas','Języki','el alemán','język niemiecki'),
('Idiomas','Języki','el italiano','język włoski'),
('Idiomas','Języki','el portugués','język portugalski'),
('Idiomas','Języki','el ruso','język rosyjski'),
('Idiomas','Języki','el chino','język chiński'),
('Idiomas','Języki','el japonés','język japoński'),
('Idiomas','Języki','el árabe','język arabski'),
('Idiomas','Języki','el hindi','język hindi'),
('Idiomas','Języki','el latín','łacina'),
('Idiomas','Języki','el griego','grecki'),
('Idiomas','Języki','la lengua materna','język ojczysty'),
('Idiomas','Języki','el idioma extranjero','język obcy'),
('Idiomas','Języki','bilingüe','dwujęzyczny'),
('Idiomas','Języki','multilingüe','wielojęzyczny'),
('Idiomas','Języki','la gramática','gramatyka'),
('Idiomas','Języki','el vocabulario','słownictwo'),
('Idiomas','Języki','la pronunciación','wymowa'),
('Idiomas','Języki','la ortografía','ortografia'),
('Idiomas','Języki','el acento','akcent'),
('Idiomas','Języki','el dialecto','dialekt'),
('Idiomas','Języki','la jerga','żargon / slang'),
('Idiomas','Języki','la traducción','tłumaczenie'),
('Idiomas','Języki','traducir','tłumaczyć'),
('Idiomas','Języki','el traductor','tłumacz'),
('Idiomas','Języki','el intérprete','tłumacz ustny'),
('Idiomas','Języki','aprender','uczyć się'),
('Idiomas','Języki','enseñar','uczyć / uczyć innych'),
('Idiomas','Języki','hablar','mówić'),
('Idiomas','Języki','entender','rozumieć'),
('Idiomas','Języki','escribir','pisać'),
('Idiomas','Języki','leer','czytać'),
('Idiomas','Języki','escuchar','słuchać'),
('Idiomas','Języki','la fluidez','płynność'),
('Idiomas','Języki','fluido','płynny'),
('Idiomas','Języki','el nivel','poziom'),
('Idiomas','Języki','el curso','kurs'),
('Idiomas','Języki','la academia','akademia / szkoła językowa'),
('Idiomas','Języki','el intercambio','wymiana (językowa)'),
('Idiomas','Języki','la competencia','kompetencja'),
('Idiomas','Języki','la comunicación','komunikacja'),
('Idiomas','Języki','expresarse','wyrażać się'),
('Idiomas','Języki','la palabra','słowo'),
('Idiomas','Języki','la frase','zdanie'),
('Idiomas','Języki','el significado','znaczenie'),
('Continentes y Océanos','Kontynenty i oceany','el continente','kontynent'),
('Continentes y Océanos','Kontynenty i oceany','el océano','ocean'),
('Continentes y Océanos','Kontynenty i oceany','Europa','Europa'),
('Continentes y Océanos','Kontynenty i oceany','Asia','Azja'),
('Continentes y Océanos','Kontynenty i oceany','África','Afryka'),
('Continentes y Océanos','Kontynenty i oceany','América del Norte','Ameryka Północna'),
('Continentes y Océanos','Kontynenty i oceany','América del Sur','Ameryka Południowa'),
('Continentes y Océanos','Kontynenty i oceany','Oceanía','Oceania'),
('Continentes y Océanos','Kontynenty i oceany','la Antártida','Antarktyda'),
('Continentes y Océanos','Kontynenty i oceany','el Océano Pacífico','Ocean Spokojny / Pacyfik'),
('Continentes y Océanos','Kontynenty i oceany','el Océano Atlántico','Ocean Atlantycki'),
('Continentes y Océanos','Kontynenty i oceany','el Océano Índico','Ocean Indyjski'),
('Continentes y Océanos','Kontynenty i oceany','el Océano Ártico','Ocean Arktyczny'),
('Continentes y Océanos','Kontynenty i oceany','el Océano Antártico','Ocean Południowy'),
('Continentes y Océanos','Kontynenty i oceany','el mar','morze'),
('Continentes y Océanos','Kontynenty i oceany','la tierra','ziemia / ląd'),
('Continentes y Océanos','Kontynenty i oceany','la isla','wyspa'),
('Continentes y Océanos','Kontynenty i oceany','el archipiélago','archipelag'),
('Continentes y Océanos','Kontynenty i oceany','la península','półwysep'),
('Continentes y Océanos','Kontynenty i oceany','el istmo','przesmyk'),
('Continentes y Océanos','Kontynenty i oceany','el cabo','przylądek'),
('Continentes y Océanos','Kontynenty i oceany','el golfo','zatoka'),
('Continentes y Océanos','Kontynenty i oceany','la bahía','zatoka (mała)'),
('Continentes y Océanos','Kontynenty i oceany','el estrecho','cieśnina'),
('Continentes y Océanos','Kontynenty i oceany','el ecuador','równik'),
('Continentes y Océanos','Kontynenty i oceany','el meridiano','południk'),
('Continentes y Océanos','Kontynenty i oceany','los trópicos','zwrotniki'),
('Continentes y Océanos','Kontynenty i oceany','el polo norte','biegun północny'),
('Continentes y Océanos','Kontynenty i oceany','el polo sur','biegun południowy'),
('Continentes y Océanos','Kontynenty i oceany','la latitud','szerokość geograficzna'),
('Continentes y Océanos','Kontynenty i oceany','la longitud','długość geograficzna'),
('Continentes y Océanos','Kontynenty i oceany','el hemisferio norte','półkula północna'),
('Continentes y Océanos','Kontynenty i oceany','el hemisferio sur','półkula południowa'),
('Continentes y Océanos','Kontynenty i oceany','el mapa','mapa'),
('Continentes y Océanos','Kontynenty i oceany','el globo terráqueo','globus'),
('Continentes y Océanos','Kontynenty i oceany','la cartografía','kartografia'),
('Continentes y Océanos','Kontynenty i oceany','el atlas','atlas'),
('Continentes y Océanos','Kontynenty i oceany','la brújula','kompas'),
('Continentes y Océanos','Kontynenty i oceany','el relieve','rzeźba terenu'),
('Continentes y Océanos','Kontynenty i oceany','la llanura','równina'),
('Continentes y Océanos','Kontynenty i oceany','la meseta','płaskowyż'),
('Continentes y Océanos','Kontynenty i oceany','la cordillera','łańcuch górski'),
('Continentes y Océanos','Kontynenty i oceany','el valle','dolina'),
('Continentes y Océanos','Kontynenty i oceany','el desierto','pustynia'),
('Continentes y Océanos','Kontynenty i oceany','la selva','dżungla'),
('Continentes y Océanos','Kontynenty i oceany','el bosque','las'),
('Continentes y Océanos','Kontynenty i oceany','la tundra','tundra'),
('Continentes y Océanos','Kontynenty i oceany','la taiga','tajga'),
('Continentes y Océanos','Kontynenty i oceany','la sabana','sawanna'),
('Continentes y Océanos','Kontynenty i oceany','la costa','wybrzeże'),
('Demografía','Demografia','la demografía','demografia'),
('Demografía','Demografia','la población','populacja'),
('Demografía','Demografia','el censo','spis powszechny'),
('Demografía','Demografia','el habitante','mieszkaniec'),
('Demografía','Demografia','el crecimiento demográfico','wzrost demograficzny'),
('Demografía','Demografia','la tasa de natalidad','wskaźnik urodzeń'),
('Demografía','Demografia','la tasa de mortalidad','wskaźnik śmiertelności'),
('Demografía','Demografia','la tasa de fertilidad','wskaźnik dzietności'),
('Demografía','Demografia','la esperanza de vida','średnia długość życia'),
('Demografía','Demografia','la densidad de población','gęstość zaludnienia'),
('Demografía','Demografia','el envejecimiento','starzenie się'),
('Demografía','Demografia','la población activa','ludność aktywna zawodowo'),
('Demografía','Demografia','la población inactiva','ludność nieaktywna zawodowo'),
('Demografía','Demografia','el éxodo rural','migracja ze wsi do miast'),
('Demografía','Demografia','la urbanización','urbanizacja'),
('Demografía','Demografia','la metrópoli','metropolia'),
('Demografía','Demografia','la ciudad','miasto'),
('Demografía','Demografia','el pueblo','wieś / miasteczko'),
('Demografía','Demografia','el suburbio','przedmieście'),
('Demografía','Demografia','la tasa de crecimiento','stopa wzrostu'),
('Demografía','Demografia','la pirámide de población','piramida wieku'),
('Demografía','Demografia','la cohorte','kohorta'),
('Demografía','Demografia','el baby boom','wyż demograficzny'),
('Demografía','Demografia','la tasa de nupcialidad','wskaźnik małżeństw'),
('Demografía','Demografia','la tasa de divorcio','wskaźnik rozwodów'),
('Demografía','Demografia','el hogar','gospodarstwo domowe'),
('Demografía','Demografia','la familia','rodzina'),
('Demografía','Demografia','el soltero','kawaler / singiel'),
('Demografía','Demografia','el casado','żonaty / zamężna'),
('Demografía','Demografia','el divorciado','rozwiedziony'),
('Demografía','Demografia','el viudo','wdowiec'),
('Demografía','Demografia','la tasa de dependencia','wskaźnik obciążenia demograficznego'),
('Demografía','Demografia','la superpoblación','przeludnienie'),
('Demografía','Demografia','el control de la natalidad','kontrola urodzeń'),
('Demografía','Demografia','la planificación familiar','planowanie rodziny'),
('Demografía','Demografia','la migración','migracja'),
('Demografía','Demografia','la inmigración','imigracja'),
('Demografía','Demografia','la emigración','emigracja'),
('Demografía','Demografia','el saldo migratorio','saldo migracji'),
('Demografía','Demografia','el éxodo','eksodus / wędrówka ludów'),
('Demografía','Demografia','el asentamiento','osadnictwo'),
('Demografía','Demografia','la comunidad','wspólnota / społeczność'),
('Demografía','Demografia','la minoría','mniejszość'),
('Demografía','Demografia','la mayoría','większość'),
('Demografía','Demografia','la tasa de mortalidad infantil','śmiertelność niemowląt'),
('Demografía','Demografia','la esperanza de vida al nacer','oczekiwana długość życia przy urodzeniu'),
('Demografía','Demografia','el demógrafo','demograf'),
('Demografía','Demografia','la estadística','statystyka'),
('Demografía','Demografia','el indicador','wskaźnik'),
('Demografía','Demografia','la población total','ludność całkowita'),
('Problemas Sociales','Problemy społeczne','el problema social','problem społeczny'),
('Problemas Sociales','Problemy społeczne','la pobreza','ubóstwo'),
('Problemas Sociales','Problemy społeczne','la desigualdad','nierówność'),
('Problemas Sociales','Problemy społeczne','la discriminación','dyskryminacja'),
('Problemas Sociales','Problemy społeczne','el desempleo','bezrobocie'),
('Problemas Sociales','Problemy społeczne','la delincuencia','przestępczość'),
('Problemas Sociales','Problemy społeczne','la violencia','przemoc'),
('Problemas Sociales','Problemy społeczne','la violencia de género','przemoc ze względu na płeć'),
('Problemas Sociales','Problemy społeczne','el racismo','rasizm'),
('Problemas Sociales','Problemy społeczne','la xenofobia','ksenofobia'),
('Problemas Sociales','Problemy społeczne','la homofobia','homofobia'),
('Problemas Sociales','Problemy społeczne','la marginación','marginalizacja'),
('Problemas Sociales','Problemy społeczne','la exclusión social','wykluczenie społeczne'),
('Problemas Sociales','Problemy społeczne','la adicción','uzależnienie'),
('Problemas Sociales','Problemy społeczne','el alcoholismo','alkoholizm'),
('Problemas Sociales','Problemy społeczne','la drogadicción','narkomania'),
('Problemas Sociales','Problemy społeczne','la ludopatía','uzależnienie od hazardu'),
('Problemas Sociales','Problemy społeczne','la indigencia','bezdomność'),
('Problemas Sociales','Problemy społeczne','el sintecho','bezdomny'),
('Problemas Sociales','Problemy społeczne','la corrupción','korupcja'),
('Problemas Sociales','Problemy społeczne','la delincuencia juvenil','przestępczość nieletnich'),
('Problemas Sociales','Problemy społeczne','el acoso','nękanie'),
('Problemas Sociales','Problemy społeczne','el acoso escolar','przemoc szkolna'),
('Problemas Sociales','Problemy społeczne','el mobbing','mobbing / nękanie w pracy'),
('Problemas Sociales','Problemy społeczne','la explotación infantil','wyzysk dzieci'),
('Problemas Sociales','Problemy społeczne','el trabajo esclavo','praca niewolnicza'),
('Problemas Sociales','Problemy społeczne','la trata de personas','handel ludźmi'),
('Problemas Sociales','Problemy społeczne','la contaminación','zanieczyszczenie'),
('Problemas Sociales','Problemy społeczne','el cambio climático','zmiana klimatu'),
('Problemas Sociales','Problemy społeczne','la crisis económica','kryzys gospodarczy'),
('Problemas Sociales','Problemy społeczne','la inflación','inflacja'),
('Problemas Sociales','Problemy społeczne','la precariedad laboral','niestabilność zatrudnienia'),
('Problemas Sociales','Problemy społeczne','la falta de vivienda','brak mieszkań'),
('Problemas Sociales','Problemy społeczne','el analfabetismo','analfabetyzm'),
('Problemas Sociales','Problemy społeczne','la desnutrición','niedożywienie'),
('Problemas Sociales','Problemy społeczne','la hambruna','głód'),
('Problemas Sociales','Problemy społeczne','el conflicto','konflikt'),
('Problemas Sociales','Problemy społeczne','la guerra','wojna'),
('Problemas Sociales','Problemy społeczne','la delincuencia organizada','zorganizowana przestępczość'),
('Problemas Sociales','Problemy społeczne','la violencia doméstica','przemoc domowa'),
('Problemas Sociales','Problemy społeczne','la discriminación laboral','dyskryminacja w pracy'),
('Problemas Sociales','Problemy społeczne','la brecha salarial','różnica w płacach'),
('Problemas Sociales','Problemy społeczne','la injusticia','niesprawiedliwość'),
('Problemas Sociales','Problemy społeczne','la protesta','protest'),
('Problemas Sociales','Problemy społeczne','la huelga','strajk'),
('Problemas Sociales','Problemy społeczne','la manifestación','manifestacja'),
('Problemas Sociales','Problemy społeczne','la solución','rozwiązanie'),
('Problemas Sociales','Problemy społeczne','la prevención','profilaktyka'),
('Problemas Sociales','Problemy społeczne','el apoyo','wsparcie'),
('Problemas Sociales','Problemy społeczne','la solidaridad','solidarność'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la pobreza','ubóstwo'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la riqueza','bogactwo'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el pobre','biedny'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el rico','bogaty'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la indigencia','skrajna bieda'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la miseria','nędza'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el lujo','luksus'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la opulencia','przepych'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la abundancia','obfitość'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la escasez','niedostatek'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la desigualdad','nierówność'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la brecha social','przepaść społeczna'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el umbral de pobreza','próg ubóstwa'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la pobreza extrema','skrajne ubóstwo'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el hambre','głód'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la desnutrición','niedożywienie'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el sintecho','bezdomny'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la asistencia social','opieka społeczna'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la beneficencia','dobroczynność'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la caridad','miłosierdzie'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la ayuda humanitaria','pomoc humanitarna'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la subvención','dotacja / zapomoga'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el subsidio','zasiłek'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el subsidio de desempleo','zasiłek dla bezrobotnych'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el magnate','magnat'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el millonario','milioner'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el multimillonario','multimilioner'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la fortuna','majątek'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el patrimonio','aktywa / majątek'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la herencia','spadek'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la inversión','inwestycja'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el capital','kapitał'),
('Pobreza y Riqueza','Bóstwo i bogactwo','los ingresos','dochody'),
('Pobreza y Riqueza','Bóstwo i bogactwo','los gastos','wydatki'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la ganancia','zysk'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la pérdida','strata'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la quiebra','bankructwo'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la bancarrota','bancructwo / niewypłacalność'),
('Pobreza y Riqueza','Bóstwo i bogactwo','mendigar','żebrać'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el mendigo','żebrak'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la limosna','jałmużna'),
('Pobreza y Riqueza','Bóstwo i bogactwo','derrochar','roztrwaniać'),
('Pobreza y Riqueza','Bóstwo i bogactwo','malbaratar','marnotrawić'),
('Pobreza y Riqueza','Bóstwo i bogactwo','ahorrar','oszczędzać'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la austeridad','austeryczność'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la generosidad','hojność'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la avaricia','chciwość'),
('Pobreza y Riqueza','Bóstwo i bogactwo','avaro','chciwy'),
('Pobreza y Riqueza','Bóstwo i bogactwo','próspero','pomyślny'),
('Pobreza y Riqueza','Bóstwo i bogactwo','acomodado','zamożny'),
('Migración','Migracja','la migración','migracja'),
('Migración','Migracja','el migrante','migrant'),
('Migración','Migracja','el inmigrante','imigrant'),
('Migración','Migracja','el emigrante','emigrant'),
('Migración','Migracja','emigrar','emigrować'),
('Migración','Migracja','inmigrar','imigrować'),
('Migración','Migracja','el refugiado','uchodźca'),
('Migración','Migracja','el asilado','azylant'),
('Migración','Migracja','el solicitante de asilo','osoba ubiegająca się o azyl'),
('Migración','Migracja','el exiliado','wygnaniec'),
('Migración','Migracja','el exilio','wygnanie / emigracja polityczna'),
('Migración','Migracja','la diáspora','diaspora'),
('Migración','Migracja','la frontera','granica'),
('Migración','Migracja','el control fronterizo','kontrola graniczna'),
('Migración','Migracja','el visado','wiza'),
('Migración','Migracja','el pasaporte','paszport'),
('Migración','Migracja','el permiso de residencia','zezwolenie na pobyt'),
('Migración','Migracja','el permiso de trabajo','zezwolenie na pracę'),
('Migración','Migracja','la residencia','pobyt / rezydentura'),
('Migración','Migracja','la deportación','deportacja'),
('Migración','Migracja','deportar','deportować'),
('Migración','Migracja','la expulsión','wydalenie'),
('Migración','Migracja','expulsar','wydalać'),
('Migración','Migracja','la integración','integracja'),
('Migración','Migracja','integrar','integrować'),
('Migración','Migracja','la asimilación','asymilacja'),
('Migración','Migracja','la asimilación cultural','asymilacja kulturowa'),
('Migración','Migracja','la multiculturalidad','multikulturalizm'),
('Migración','Migracja','la xenofobia','ksenofobia'),
('Migración','Migracja','el racismo','rasizm'),
('Migración','Migracja','la discriminación','dyskryminacja'),
('Migración','Migracja','el traficante de personas','przemytnik ludzi'),
('Migración','Migracja','la patera','łódź pontonowa (imigrantów)'),
('Migración','Migracja','el cayuco','łódź rybacka (migrancka)'),
('Migración','Migracja','el naufragio','katastrofa morska'),
('Migración','Migracja','la ruta migratoria','szlak migracyjny'),
('Migración','Migracja','la acogida','przyjęcie / gościnność'),
('Migración','Migracja','acoger','przyjmować'),
('Migración','Migracja','el centro de acogida','ośrodek dla uchodźców'),
('Migración','Migracja','la repatriación','repatriacja'),
('Migración','Migracja','repatriar','repatriować'),
('Migración','Migracja','la crisis migratoria','kryzys migracyjny'),
('Migración','Migracja','la llegada','przybycie'),
('Migración','Migracja','la salida','wyjazd'),
('Migración','Migracja','el flujo migratorio','przepływ migracyjny'),
('Migración','Migracja','la remesa','przekaz pieniężny'),
('Migración','Migracja','la mano de obra','siła robocza'),
('Migración','Migracja','la clandestinidad','nielegalność'),
('Migración','Migracja','clandestino','nielegalny'),
('Migración','Migracja','la barrera','bariera'),
('Educación Infantil','Edukacja wczesnoszkolna','la educación infantil','edukacja przedszkolna'),
('Educación Infantil','Edukacja wczesnoszkolna','la guardería','żłobek'),
('Educación Infantil','Edukacja wczesnoszkolna','el jardín de infancia','przedszkole'),
('Educación Infantil','Edukacja wczesnoszkolna','la escuela infantil','szkoła przedszkolna'),
('Educación Infantil','Edukacja wczesnoszkolna','el parvulario','oddział przedszkolny'),
('Educación Infantil','Edukacja wczesnoszkolna','el niño','dziecko'),
('Educación Infantil','Edukacja wczesnoszkolna','la niña','dziewczynka'),
('Educación Infantil','Edukacja wczesnoszkolna','el infante','niemowlę / małe dziecko'),
('Educación Infantil','Edukacja wczesnoszkolna','el párvulo','przedszkolak'),
('Educación Infantil','Edukacja wczesnoszkolna','el educador','wychowawca'),
('Educación Infantil','Edukacja wczesnoszkolna','la educadora','wychowawczyni'),
('Educación Infantil','Edukacja wczesnoszkolna','el maestro de infantil','nauczyciel przedszkola'),
('Educación Infantil','Edukacja wczesnoszkolna','la maestra','nauczycielka'),
('Educación Infantil','Edukacja wczesnoszkolna','la ludoteca','świetlica / sala zabaw'),
('Educación Infantil','Edukacja wczesnoszkolna','el juego','zabawa'),
('Educación Infantil','Edukacja wczesnoszkolna','jugar','bawić się'),
('Educación Infantil','Edukacja wczesnoszkolna','el juguete','zabawka'),
('Educación Infantil','Edukacja wczesnoszkolna','el dibujo','rysunek'),
('Educación Infantil','Edukacja wczesnoszkolna','pintar','rysować / malować'),
('Educación Infantil','Edukacja wczesnoszkolna','colorear','kolorować'),
('Educación Infantil','Edukacja wczesnoszkolna','la plastelina','plastelina'),
('Educación Infantil','Edukacja wczesnoszkolna','el cuento','bajka'),
('Educación Infantil','Edukacja wczesnoszkolna','contantar un cuento','opowiadać bajkę'),
('Educación Infantil','Edukacja wczesnoszkolna','la canción','piosenka'),
('Educación Infantil','Edukacja wczesnoszkolna','cantar','śpiewać'),
('Educación Infantil','Edukacja wczesnoszkolna','bailar','tańczyć'),
('Educación Infantil','Edukacja wczesnoszkolna','el aprendizaje','nauka'),
('Educación Infantil','Edukacja wczesnoszkolna','aprender','uczyć się'),
('Educación Infantil','Edukacja wczesnoszkolna','la socialización','socjalizacja'),
('Educación Infantil','Edukacja wczesnoszkolna','compartir','dzielić się'),
('Educación Infantil','Edukacja wczesnoszkolna','el compañerismo','koleżeństwo'),
('Educación Infantil','Edukacja wczesnoszkolna','el patio','plac zabaw'),
('Educación Infantil','Edukacja wczesnoszkolna','el tobogán','zjeżdżalnia'),
('Educación Infantil','Edukacja wczesnoszkolna','el columpio','huśtawka'),
('Educación Infantil','Edukacja wczesnoszkolna','el arenero','piaskownica'),
('Educación Infantil','Edukacja wczesnoszkolna','la siesta','drzemka'),
('Educación Infantil','Edukacja wczesnoszkolna','dormir','spać'),
('Educación Infantil','Edukacja wczesnoszkolna','comer','jeść'),
('Educación Infantil','Edukacja wczesnoszkolna','el almuerzo','drugie śniadanie'),
('Educación Infantil','Edukacja wczesnoszkolna','la merienda','podwieczorek'),
('Educación Infantil','Edukacja wczesnoszkolna','el pañal','pielucha'),
('Educación Infantil','Edukacja wczesnoszkolna','el orinal','nocnik'),
('Educación Infantil','Edukacja wczesnoszkolna','el biberón','butelka dla dziecka'),
('Educación Infantil','Edukacja wczesnoszkolna','el desarrollo','rozwój'),
('Educación Infantil','Edukacja wczesnoszkolna','la motricidad','motoryka'),
('Educación Infantil','Edukacja wczesnoszkolna','la creatividad','kreatywność'),
('Educación Infantil','Edukacja wczesnoszkolna','la imaginación','wyobraźnia'),
('Educación Infantil','Edukacja wczesnoszkolna','el abecedario','alfabet'),
('Educación Infantil','Edukacja wczesnoszkolna','los números','liczby'),
('Educación Infantil','Edukacja wczesnoszkolna','los colores','kolory'),
('Educación Secundaria','Edukacja średnia','la educación secundaria','edukacja średnia / gimnazjum i liceum'),
('Educación Secundaria','Edukacja średnia','el instituto','liceum / szkoła średnia'),
('Educación Secundaria','Edukacja średnia','el colegio','szkoła'),
('Educación Secundaria','Edukacja średnia','el alumno / la alumna','uczeń / uczennica'),
('Educación Secundaria','Edukacja średnia','el estudiante','student / uczeń'),
('Educación Secundaria','Edukacja średnia','el profesor / la profesora','nauczyciel / profesor'),
('Educación Secundaria','Edukacja średnia','el docente','nauczyciel / wykładowca'),
('Educación Secundaria','Edukacja średnia','el director','dyrektor szkoły'),
('Educación Secundaria','Edukacja średnia','el tutor','wychowawca / mentor'),
('Educación Secundaria','Edukacja średnia','la clase','klasa / lekcja'),
('Educación Secundaria','Edukacja średnia','el aula','sala lekcyjna'),
('Educación Secundaria','Edukacja średnia','el horario','plan lekcji'),
('Educación Secundaria','Edukacja średnia','la asignatura','przedmiot szkolny'),
('Educación Secundaria','Edukacja średnia','la materia','przedmiot / materia'),
('Educación Secundaria','Edukacja średnia','el examen','egzamin'),
('Educación Secundaria','Edukacja średnia','la prueba','sprawdzian / test'),
('Educación Secundaria','Edukacja średnia','la nota','ocena'),
('Educación Secundaria','Edukacja średnia','la calificación','ocena / kwalifikacja'),
('Educación Secundaria','Edukacja średnia','aprobar','zdać'),
('Educación Secundaria','Edukacja średnia','suspender','zjeść pałę / nie zdać'),
('Educación Secundaria','Edukacja średnia','el boletín de notas','świadectwo / karta ocen'),
('Educación Secundaria','Edukacja średnia','el trimestre','trymestr'),
('Educación Secundaria','Edukacja średnia','el curso escolar','rok szkolny'),
('Educación Secundaria','Edukacja średnia','el recreo','przerwa (międzylekcyjna)'),
('Educación Secundaria','Edukacja średnia','la tarea','zadanie domowe'),
('Educación Secundaria','Edukacja średnia','los deberes','praca domowa'),
('Educación Secundaria','Edukacja średnia','el cuaderno','zeszyt'),
('Educación Secundaria','Edukacja średnia','el libro de texto','podręcznik'),
('Educación Secundaria','Edukacja średnia','el bolígrafo','długopis'),
('Educación Secundaria','Edukacja średnia','el lápiz','ołówek'),
('Educación Secundaria','Edukacja średnia','la goma','gumka do ścierania'),
('Educación Secundaria','Edukacja średnia','la regla','linijka'),
('Educación Secundaria','Edukacja średnia','la mochila','plecak'),
('Educación Secundaria','Edukacja średnia','el estuche','piórnik'),
('Educación Secundaria','Edukacja średnia','la pizarra','tablica'),
('Educación Secundaria','Edukacja średnia','la tiza','kreda'),
('Educación Secundaria','Edukacja średnia','el marcador','marker'),
('Educación Secundaria','Edukacja średnia','el borrador','gąbka do tablicy'),
('Educación Secundaria','Edukacja średnia','el instituto de educación secundaria (IES)','liceum ogólnokształcące'),
('Educación Secundaria','Edukacja średnia','la selectividad / la EBAU','matura (egzamin wstępny na studia)'),
('Educación Secundaria','Edukacja średnia','el bachillerato','liceum (ostatnie lata) / matura'),
('Educación Secundaria','Edukacja średnia','la formación profesional (FP)','szkolenie zawodowe'),
('Educación Secundaria','Edukacja średnia','el título','dyplom / tytuł'),
('Educación Secundaria','Edukacja średnia','el graduado','absolwent'),
('Educación Secundaria','Edukacja średnia','la graduación','ukończenie szkoły / ceremonia absolwencka'),
('Educación Secundaria','Edukacja średnia','el acoso escolar','nękanie / przemoc szkolna'),
('Educación Secundaria','Edukacja średnia','el compañero de clase','kolega z klasy'),
('Educación Secundaria','Edukacja średnia','el delegado de clase','gospodarz klasy'),
('Educación Secundaria','Edukacja średnia','la excursión','wycieczka szkolna'),
('Educación Secundaria','Edukacja średnia','la biblioteca','biblioteka szkolna'),
('Universidad','Uniwersytet','la universidad','uniwersytet'),
('Universidad','Uniwersytet','el campus','kampus uniwersytecki'),
('Universidad','Uniwersytet','el rector','rektor'),
('Universidad','Uniwersytet','el decano','dziekan'),
('Universidad','Uniwersytet','el profesor / la profesora','profesor / wykładowca'),
('Universidad','Uniwersytet','el catedrático','profesor zwyczajny / kierownik katedry'),
('Universidad','Uniwersytet','el investigador','badacza / naukowiec'),
('Universidad','Uniwersytet','el estudiante / el universitario','student'),
('Universidad','Uniwersytet','el alumno','student / uczeń'),
('Universidad','Uniwersytet','la carrera','kierunek studiów'),
('Universidad','Uniwersytet','la licenciatura','licencjat'),
('Universidad','Uniwersytet','el grado','studia licencjackie / stopień'),
('Universidad','Uniwersytet','el máster','studia magisterskie / magister'),
('Universidad','Uniwersytet','el doctorado','doktorat'),
('Universidad','Uniwersytet','el doctor','doktor'),
('Universidad','Uniwersytet','la tesis','praca dyplomowa / rozprawa'),
('Universidad','Uniwersytet','la tesis doctoral','rozprawa doktorska'),
('Universidad','Uniwersytet','la facultad','wydział'),
('Universidad','Uniwersytet','el departamento','katedra / wydział'),
('Universidad','Uniwersytet','el seminarium','seminarium'),
('Universidad','Uniwersytet','la clase magistral','wykład'),
('Universidad','Uniwersytet','el auditorio','aula wykładowa'),
('Universidad','Uniwersytet','el crédito','punkt ECTS / kredyt'),
('Universidad','Uniwersytet','la matrícula','wpis na studia / czesne'),
('Universidad','Uniwersytet','matricularse','zapisać się na studia'),
('Universidad','Uniwersytet','la beca','stypendium'),
('Universidad','Uniwersytet','el becario','stypendysta / stażysta'),
('Universidad','Uniwersytet','la residencia de estudiantes','akademik / dom studencki'),
('Universidad','Uniwersytet','el rectorado','rektorat'),
('Universidad','Uniwersytet','el decanato','dziekanat'),
('Universidad','Uniwersytet','la secretaría','sekretariat uczelni'),
('Universidad','Uniwersytet','el expediente académico','indeks / przebieg studiów'),
('Universidad','Uniwersytet','el examen final','egzamin końcowy'),
('Universidad','Uniwersytet','la convocatoria','termin egzaminu'),
('Universidad','Uniwersytet','suspender','oblać egzamin'),
('Universidad','Uniwersytet','aprobar','zdać'),
('Universidad','Uniwersytet','el título universitario','dyplom uniwersytecki'),
('Universidad','Uniwersytet','el graduado','absolwent'),
('Universidad','Uniwersytet','la ceremonia de graduación','ceremonia rozdania dyplomów'),
('Universidad','Uniwersytet','el intercambio','wymiana studencka (np. Erasmus)'),
('Universidad','Uniwersytet','la investigación','badania naukowe'),
('Universidad','Uniwersytet','publicar','publikować'),
('Universidad','Uniwersytet','el artículo científico','artykuł naukowy'),
('Universidad','Uniwersytet','la conferencia','konferencja'),
('Universidad','Uniwersytet','el laboratorio','laboratorium'),
('Universidad','Uniwersytet','la biblioteca universitaria','biblioteka uniwersytecka'),
('Universidad','Uniwersytet','el rector','rektor'),
('Universidad','Uniwersytet','el campus virtual','wirtualny kampus'),
('Universidad','Uniwersytet','la asignatura optativa','przedmiot do wyboru'),
('Universidad','Uniwersytet','la asignatura obligatoria','przedmiot obowiązkowy'),
('Asignaturas Escolares','Przedmioty szkolne','la asignatura','przedmiot szkolny');
