insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Telefonía Móvil','Telefonia komórkowa','el teléfono móvil / el celular','telefon komórkowy / smartfon'),
('Telefonía Móvil','Telefonia komórkowa','la llamada','połączenie telefoniczne'),
('Telefonía Móvil','Telefonia komórkowa','llamar','dzwonić'),
('Telefonía Móvil','Telefonia komórkowa','contestar','odbierać (telefon)'),
('Telefonía Móvil','Telefonia komórkowa','colgar','rozłączać się'),
('Telefonía Móvil','Telefonia komórkowa','el tono de llamada','dźwięk dzwonka'),
('Telefonía Móvil','Telefonia komórkowa','el buzón de voz','poczta głosowa'),
('Telefonía Móvil','Telefonia komórkowa','el mensaje de texto / el SMS','wiadomość tekstowa / SMS'),
('Telefonía Móvil','Telefonia komórkowa','el mensaje de voz','wiadomość głosowa'),
('Telefonía Móvil','Telefonia komórkowa','la pantalla táctil','ekran dotykowy'),
('Telefonía Móvil','Telefonia komórkowa','la batería','bateria'),
('Telefonía Móvil','Telefonia komórkowa','el cargador','ładowarka'),
('Telefonía Móvil','Telefonia komórkowa','cargar el móvil','ładować telefon'),
('Telefonía Móvil','Telefonia komórkowa','la tarjeta SIM','karta SIM'),
('Telefonía Móvil','Telefonia komórkowa','la cobertura','zasięg'),
('Telefonía Móvil','Telefonia komórkowa','sin cobertura','brak zasięgu'),
('Telefonía Móvil','Telefonia komórkowa','la red móvil','sieć komórkowa'),
('Telefonía Móvil','Telefonia komórkowa','los datos móviles','dane komórkowe'),
('Telefonía Móvil','Telefonia komórkowa','el roaming','roaming'),
('Telefonía Móvil','Telefonia komórkowa','la aplicación / la app','aplikacja'),
('Telefonía Móvil','Telefonia komórkowa','descargar una aplicación','pobrać aplikację'),
('Telefonía Móvil','Telefonia komórkowa','la cámara','aparat (w telefonie)'),
('Telefonía Móvil','Telefonia komórkowa','la cámara frontal','przedni aparat / kamera do selfie'),
('Telefonía Móvil','Telefonia komórkowa','el flash','flesz'),
('Telefonía Móvil','Telefonia komórkowa','la agenda','książka adresowa / kontakty'),
('Telefonía Móvil','Telefonia komórkowa','la videollamada','rozmowa wideo'),
('Telefonía Móvil','Telefonia komórkowa','el chat','czat'),
('Telefonía Móvil','Telefonia komórkowa','la notificación','powiadomienie'),
('Telefonía Móvil','Telefonia komórkowa','el ajuste','ustawienia'),
('Telefonía Móvil','Telefonia komórkowa','el modo avión','tryb samolotowy'),
('Telefonía Móvil','Telefonia komórkowa','el tono de aviso','dźwięk powiadomienia'),
('Telefonía Móvil','Telefonia komórkowa','la funda','etui / pokrowczyk'),
('Telefonía Móvil','Telefonia komórkowa','el protector de pantalla','szkło / folia ochronna na ekran'),
('Telefonía Móvil','Telefonia komórkowa','el manos libres','zestaw głośnomówiący'),
('Telefonía Móvil','Telefonia komórkowa','el auricular','słuchawka'),
('Telefonía Móvil','Telefonia komórkowa','el bluetooth','Bluetooth'),
('Telefonía Móvil','Telefonia komórkowa','el GPS','GPS / nawigacja'),
('Telefonía Móvil','Telefonia komórkowa','la huella dactilar','czytnik linii papilarnych'),
('Telefonía Móvil','Telefonia komórkowa','el reconocimiento facial','rozpoznawanie twarzy'),
('Telefonía Móvil','Telefonia komórkowa','reiniciar','uruchomić ponownie'),
('Telefonía Móvil','Telefonia komórkowa','apagar','wyłączyć'),
('Telefonía Móvil','Telefonia komórkowa','encender','włączyć'),
('Telefonía Móvil','Telefonia komórkowa','bloquear','zablokować'),
('Telefonía Móvil','Telefonia komórkowa','desbloquear','odblokować'),
('Telefonía Móvil','Telefonia komórkowa','la factura de teléfono','rachunek za telefon'),
('Telefonía Móvil','Telefonia komórkowa','la recarga','doładowanie (konta)'),
('Telefonía Móvil','Telefonia komórkowa','el operador de telefonía','operator telefoniczny'),
('Telefonía Móvil','Telefonia komórkowa','la tarifa plana','stawka ryczałtowa / bez limitu'),
('Telefonía Móvil','Telefonia komórkowa','el smartphone','smartfon'),
('Telefonía Móvil','Telefonia komórkowa','la memoria interna','pamięć wewnętrzna'),
('Videojuegos','Gry wideo','el videojuego','gra wideo'),
('Videojuegos','Gry wideo','la consola','konsola do gier'),
('Videojuegos','Gry wideo','el jugador','gracz'),
('Videojuegos','Gry wideo','el mando / el controlador','pad / kontroler'),
('Videojuegos','Gry wideo','la partida','rozgrywka / partida'),
('Videojuegos','Gry wideo','la pantalla','ekran'),
('Videojuegos','Gry wideo','el nivel','poziom'),
('Videojuegos','Gry wideo','la fase','fase / etap'),
('Videojuegos','Gry wideo','el jefe','boss (szef w grze)'),
('Videojuegos','Gry wideo','la puntuación','wynik / punktacja'),
('Videojuegos','Gry wideo','la vida','życie (w grze)'),
('Videojuegos','Gry wideo','el punto de control','punkt kontrolny (checkpoint)'),
('Videojuegos','Gry wideo','el inventario','ekwipunek / inwentarz'),
('Videojuegos','Gry wideo','la misión','misja / zadanie'),
('Videojuegos','Gry wideo','la aventura','przygoda'),
('Videojuegos','Gry wideo','el juego de rol (RPG)','gra RPG'),
('Videojuegos','Gry wideo','el simulador','symulator'),
('Videojuegos','Gry wideo','la estrategia','strategia'),
('Videojuegos','Gry wideo','el modo multijugador','tryb wieloosobowy (multiplayer)'),
('Videojuegos','Gry wideo','el modo individual','tryb dla jednego gracza (singleplayer)'),
('Videojuegos','Gry wideo','la realidad virtual','rzeczywistość wirtualna (VR)'),
('Videojuegos','Gry wideo','el gráfico','grafika'),
('Videojuegos','Gry wideo','la animación','animacja'),
('Videojuegos','Gry wideo','la jugabilidad','rozgrywka (gameplay)'),
('Videojuegos','Gry wideo','jugar','grać'),
('Videojuegos','Gry wideo','ganar','wygrać'),
('Videojuegos','Gry wideo','perder','przegrać'),
('Videojuegos','Gry wideo','morir','zginąć (w grze)'),
('Videojuegos','Gry wideo','revivir','ożywić / odrodzić się'),
('Videojuegos','Gry wideo','la plataforma','platforma do gier'),
('Videojuegos','Gry wideo','el juego en línea','gra online'),
('Videojuegos','Gry wideo','el servidor','serwer'),
('Videojuegos','Gry wideo','el retraso (lag)','opóźnienie (lag)'),
('Videojuegos','Gry wideo','el truco','kod / sztuczka (cheat)'),
('Videojuegos','Gry wideo','la beta','wersja beta'),
('Videojuegos','Gry wideo','el parche','łatka / aktualizacja (patch)'),
('Videojuegos','Gry wideo','la expansión','dodatek do gry (expansion)'),
('Videojuegos','Gry wideo','el estudio de desarrollo','studio deweloperskie'),
('Videojuegos','Gry wideo','el desarrollador','programista / deweloper'),
('Videojuegos','Gry wideo','el lanzamiento','premiera'),
('Videojuegos','Gry wideo','la banda sonora','ścieżka dźwiękowa'),
('Videojuegos','Gry wideo','la historia','fabuła / historia'),
('Videojuegos','Gry wideo','el personaje','postać'),
('Videojuegos','Gry wideo','el avatar','awatar'),
('Videojuegos','Gry wideo','el streaming','streaming'),
('Videojuegos','Gry wideo','el streamer','streamer'),
('Videojuegos','Gry wideo','la transmisión','transmisja'),
('Videojuegos','Gry wideo','la comunidad','społeczność'),
('Videojuegos','Gry wideo','la tabla de clasificación','tabela wyników (leaderboard)'),
('Videojuegos','Gry wideo','la edición coleccionista','edycja kolekcjonerska'),
('Física','Fizyka','la física','fizyka'),
('Física','Fizyka','la materia','materia'),
('Física','Fizyka','la energía','energia'),
('Física','Fizyka','la fuerza','siła'),
('Física','Fizyka','la masa','masa'),
('Física','Fizyka','el peso','ciężar'),
('Física','Fizyka','la velocidad','prędkość'),
('Física','Fizyka','la aceleración','przyspieszenie'),
('Física','Fizyka','la gravedad','grawitacja'),
('Física','Fizyka','el movimiento','ruch'),
('Física','Fizyka','el reposo','spoczynek'),
('Física','Fizyka','la inercia','bezwładność'),
('Física','Fizyka','la ley','prawo (fizyczne)'),
('Física','Fizyka','la teoría','teoria'),
('Física','Fizyka','el átomo','atom'),
('Física','Fizyka','la molécula','cząsteczka'),
('Física','Fizyka','el electrón','elektron'),
('Física','Fizyka','el protón','proton'),
('Física','Fizyka','el neutrón','neutron'),
('Física','Fizyka','la carga eléctrica','ładunek elektryczny'),
('Física','Fizyka','la electricidad','elektryczność'),
('Física','Fizyka','el magnetismo','magnetyzm'),
('Física','Fizyka','la onda','fala'),
('Física','Fizyka','la frecuencia','częstotliwość'),
('Física','Fizyka','la longitud de onda','długość fali'),
('Física','Fizyka','la luz','światło'),
('Física','Fizyka','el sonido','dźwięk'),
('Física','Fizyka','el calor','ciepło / temperatura'),
('Física','Fizyka','la termodinámica','termodynamika'),
('Física','Fizyka','la presión','ciśnienie'),
('Física','Fizyka','el volumen','objętość'),
('Física','Fizyka','la densidad','gęstość'),
('Física','Fizyka','el trabajo','praca (fizyczna)'),
('Física','Fizyka','la potencia','moc'),
('Física','Fizyka','la óptica','optyka'),
('Física','Fizyka','la mecánica','mechanika'),
('Física','Fizyka','la cuántica','fizyka kwantowa'),
('Física','Fizyka','la relatividad','względność'),
('Física','Fizyka','el espacio','przestrzeń'),
('Física','Fizyka','el tiempo','czas'),
('Física','Fizyka','el vacío','próżnia'),
('Física','Fizyka','el experimento','eksperyment'),
('Física','Fizyka','la hipótesis','hipoteza'),
('Física','Fizyka','medir','mierzyć'),
('Física','Fizyka','la unidad','jednostka'),
('Física','Fizyka','el metro','metr'),
('Física','Fizyka','el kilogramo','kilogram'),
('Física','Fizyka','el segundo','sekunda'),
('Física','Fizyka','el newton','niuton'),
('Física','Fizyka','el julio','dżul'),
('Química','Chemia','la química','chemia'),
('Química','Chemia','la sustancia','substancja'),
('Química','Chemia','el elemento','pierwiastek'),
('Química','Chemia','el compuesto','związek chemiczny'),
('Química','Chemia','la tabla periódica','układ okresowy pierwiastków'),
('Química','Chemia','el átomo','atom'),
('Química','Chemia','la molécula','cząsteczka'),
('Química','Chemia','el electrón','elektron'),
('Química','Chemia','el núcleo','jądro atomowe'),
('Química','Chemia','la reacción química','reakcja chemiczna'),
('Química','Chemia','la fórmula','wzór chemiczny'),
('Química','Chemia','el enlace','wiązanie chemiczne'),
('Química','Chemia','el ácido','kwas'),
('Química','Chemia','la base','zasada'),
('Química','Chemia','el pH','pH'),
('Química','Chemia','la solución / la disolución','roztwór'),
('Química','Chemia','el disolvente','rozpuszczalnik'),
('Química','Chemia','el soluto','substancja rozpuszczona'),
('Química','Chemia','la concentración','stężenie'),
('Química','Chemia','el estado de la materia','stan skupienia'),
('Química','Chemia','el estado sólido','stan stały'),
('Química','Chemia','el estado líquido','stan ciekły'),
('Química','Chemia','el estado gaseoso','stan gazowy'),
('Química','Chemia','el gas','gaz'),
('Química','Chemia','el líquido','ciecz'),
('Química','Chemia','el sólido','ciało stałe'),
('Química','Chemia','fundir','topić / stapiać'),
('Química','Chemia','congelar','zamrażać'),
('Química','Chemia','evaporar','odparowywać'),
('Química','Chemia','condensar','skraplać'),
('Química','Chemia','sublimar','sublimować'),
('Química','Chemia','la combustión','spalanie'),
('Química','Chemia','la oxidación','utlenianie'),
('Química','Chemia','la reducción','redukcja'),
('Química','Chemia','el laboratorio','laboratorium'),
('Química','Chemia','el tubo de ensayo','probówka'),
('Química','Chemia','el matraz','kolba laboratoryjna'),
('Química','Chemia','el vaso de precipitados','zlewek laboratoryjny'),
('Química','Chemia','la pipeta','pipeta'),
('Química','Chemia','la balanza','waga laboratoryjna'),
('Química','Chemia','el mechero Bunsen','palnik Bunsen'),
('Química','Chemia','tóxico','toksyczny'),
('Química','Chemia','inflamable','łatwopalny'),
('Química','Chemia','corrosivo','żrący'),
('Química','Chemia','el peligro','niebezpieczeństwo'),
('Química','Chemia','la seguridad','bezpieczeństwo'),
('Química','Chemia','el catalizador','katalizator'),
('Química','Chemia','la orgánica','chemia organiczna'),
('Química','Chemia','la inorgánica','chemia nieorganiczna'),
('Química','Chemia','la bioquímica','biochemia'),
('Biología','Biologia','la biología','biologia'),
('Biología','Biologia','la vida','życie'),
('Biología','Biologia','el organismo','organizm'),
('Biología','Biologia','la célula','komórka'),
('Biología','Biologia','el ADN','DNA'),
('Biología','Biologia','el ARN','RNA'),
('Biología','Biologia','el gen','gen'),
('Biología','Biologia','la genética','genetyka'),
('Biología','Biologia','la evolución','ewolucja'),
('Biología','Biologia','la especie','gatunek'),
('Biología','Biologia','el ecosistema','ekosystem'),
('Biología','Biologia','la biodiversidad','bioróżnorodność'),
('Biología','Biologia','el hábitat','siedlisko'),
('Biología','Biologia','la adaptación','adaptacja / przystosowanie'),
('Biología','Biologia','la selección natural','dobór naturalny'),
('Biología','Biologia','la anatomía','anatomia'),
('Biología','Biologia','la fisiología','fizjologia'),
('Biología','Biologia','el tejido','tkanka'),
('Biología','Biologia','el órgano','narząd / organ'),
('Biología','Biologia','el sistema','układ (np. krążenia, nerwowy)'),
('Biología','Biologia','la reproducción','rozmnażanie'),
('Biología','Biologia','el crecimiento','wzrost'),
('Biología','Biologia','la nutrición','odżywianie'),
('Biología','Biologia','el metabolismo','metabolizm'),
('Biología','Biologia','la fotosíntesis','fotosynteza'),
('Biología','Biologia','la bacteria','bakteria'),
('Biología','Biologia','el virus','wirus'),
('Biología','Biologia','el hongo','grzyb'),
('Biología','Biologia','la planta','roślina'),
('Biología','Biologia','el animal','zwierzę'),
('Biología','Biologia','la botánica','botanika'),
('Biología','Biologia','la zoología','zoologia'),
('Biología','Biologia','la microbiología','mikrobiologia'),
('Biología','Biologia','la ecología','ekologia'),
('Biología','Biologia','la zoología','zoologia'),
('Biología','Biologia','el fósil','skamieniałość'),
('Biología','Biologia','la extinción','wyginięcie'),
('Biología','Biologia','la clonación','klonowanie'),
('Biología','Biologia','la mutación','mutacja'),
('Biología','Biologia','el microscopio','mikroskop'),
('Biología','Biologia','la muestra','próbka'),
('Biología','Biologia','el espécimen','okaz'),
('Biología','Biologia','la membrana','błona komórkowa'),
('Biología','Biologia','el núcleo','jądro komórkowe'),
('Biología','Biologia','el citoplasma','cytoplazma'),
('Biología','Biologia','la enzima','enzym'),
('Biología','Biologia','la proteína','białko'),
('Biología','Biologia','el aminoácido','aminokwas'),
('Biología','Biologia','la simbiosis','symbioza'),
('Biología','Biologia','el parásito','pasożyt'),
('Matemáticas','Matematyka','las matemáticas','matematyka'),
('Matemáticas','Matematyka','el número','liczba / numer'),
('Matemáticas','Matematyka','la cifra','cyfra'),
('Matemáticas','Matematyka','la suma','suma / dodawanie'),
('Matemáticas','Matematyka','la resta','odejmowanie'),
('Matemáticas','Matematyka','la multiplicación','mnożenie'),
('Matemáticas','Matematyka','la división','dzielenie'),
('Matemáticas','Matematyka','sumar','dodawać'),
('Matemáticas','Matematyka','restar','odejmować'),
('Matemáticas','Matematyka','multiplicar','mnożyć'),
('Matemáticas','Matematyka','dividir','dzielić'),
('Matemáticas','Matematyka','el resultado','wynik'),
('Matemáticas','Matematyka','el total','całkowity / suma'),
('Matemáticas','Matematyka','la fracción','ułamek'),
('Matemáticas','Matematyka','el decimal','liczba dziesiętna'),
('Matemáticas','Matematyka','el porcentaje','procent'),
('Matemáticas','Matematyka','la ecuación','równanie'),
('Matemáticas','Matematyka','la fórmula','wzór'),
('Matemáticas','Matematyka','la variable','zmienna'),
('Matemáticas','Matematyka','la constante','stała'),
('Matemáticas','Matematyka','la geometría','geometria'),
('Matemáticas','Matematyka','el álgebra','algebra'),
('Matemáticas','Matematyka','el cálculo','rachunek / obliczenie'),
('Matemáticas','Matematyka','la trigonometria','trygonometria'),
('Matemáticas','Matematyka','la estadística','statystyka'),
('Matemáticas','Matematyka','la probabilidad','prawdopodobieństwo'),
('Matemáticas','Matematyka','el ángulo','kąt'),
('Matemáticas','Matematyka','el triángulo','trójkąt'),
('Matemáticas','Matematyka','el cuadrado','kwadrat'),
('Matemáticas','Matematyka','el círculo','koło'),
('Matemáticas','Matematyka','el rectángulo','prostokąt'),
('Matemáticas','Matematyka','el radio','promień'),
('Matemáticas','Matematyka','el diámetro','średnica'),
('Matemáticas','Matematyka','el perímetro','obwód'),
('Matemáticas','Matematyka','el área','pole powierzchni'),
('Matemáticas','Matematyka','el volumen','objętość'),
('Matemáticas','Matematyka','la raíz cuadrada','pierwiastek kwadratowy'),
('Matemáticas','Matematyka','la potencia','potęga'),
('Matemáticas','Matematyka','el exponente','wykładnik potęgi'),
('Matemáticas','Matematyka','la matriz','macierz'),
('Matemáticas','Matematyka','el vector','wektor'),
('Matemáticas','Matematyka','la función','funkcja'),
('Matemáticas','Matematyka','la derivada','pochodna'),
('Matemáticas','Matematyka','la integral','całka'),
('Matemáticas','Matematyka','el teorema','twierdzenie'),
('Matemáticas','Matematyka','la demostración','dowód'),
('Matemáticas','Matematyka','el infinito','nieskończoność'),
('Matemáticas','Matematyka','la lógica','logika'),
('Matemáticas','Matematyka','el gráfico','wykres'),
('Matemáticas','Matematyka','la tabla','tabela'),
('Historia Antigua','Historia starożytna','la historia antigua','historia starożytna'),
('Historia Antigua','Historia starożytna','la prehistoria','prehistoria'),
('Historia Antigua','Historia starożytna','la antigüedad','starożytność'),
('Historia Antigua','Historia starożytna','la civilización','cywilizacja'),
('Historia Antigua','Historia starożytna','el imperio','imperium'),
('Historia Antigua','Historia starożytna','el reino','królestwo'),
('Historia Antigua','Historia starożytna','la dinastía','dynastia'),
('Historia Antigua','Historia starożytna','el faraón','faraon'),
('Historia Antigua','Historia starożytna','el emperador','cesarz'),
('Historia Antigua','Historia starożytna','el rey','król'),
('Historia Antigua','Historia starożytna','la reina','królowa'),
('Historia Antigua','Historia starożytna','el esclavo','niewolnik'),
('Historia Antigua','Historia starożytna','la esclavitud','niewolnictwo'),
('Historia Antigua','Historia starożytna','el gladiador','gladiator'),
('Historia Antigua','Historia starożytna','el templo','świątynia'),
('Historia Antigua','Historia starożytna','la pirámide','piramida'),
('Historia Antigua','Historia starożytna','el monumento','pomnik / zabytek'),
('Historia Antigua','Historia starożytna','las ruinas','ruiny'),
('Historia Antigua','Historia starożytna','la mitología','mitologia'),
('Historia Antigua','Historia starożytna','el dios','bóg'),
('Historia Antigua','Historia starożytna','la diosa','bogini'),
('Historia Antigua','Historia starożytna','el mito','mit'),
('Historia Antigua','Historia starożytna','la leyenda','legenda'),
('Historia Antigua','Historia starożytna','la escritura','pismo'),
('Historia Antigua','Historia starożytna','el jeroglífico','hieroglif'),
('Historia Antigua','Historia starożytna','el papiro','papirus'),
('Historia Antigua','Historia starożytna','el pergamino','pergamin'),
('Historia Antigua','Historia starożytna','la arqueología','archeologia'),
('Historia Antigua','Historia starożytna','el arqueólogo','archeolog'),
('Historia Antigua','Historia starożytna','el fósil','skamieniałość'),
('Historia Antigua','Historia starożytna','la excavación','wykopaliska'),
('Historia Antigua','Historia starożytna','el tesoro','skarb'),
('Historia Antigua','Historia starożytna','la conquista','podbój'),
('Historia Antigua','Historia starożytna','conquistar','podbijać'),
('Historia Antigua','Historia starożytna','la batalla','bitwa'),
('Historia Antigua','Historia starożytna','la guerra','wojna'),
('Historia Antigua','Historia starożytna','el ejército','armia'),
('Historia Antigua','Historia starożytna','el soldado','żołnierza'),
('Historia Antigua','Historia starożytna','la espada','miecz'),
('Historia Antigua','Historia starożytna','el escudo','tarcza'),
('Historia Antigua','Historia starożytna','Grecia','Grecja'),
('Historia Antigua','Historia starożytna','Roma','Rzym'),
('Historia Antigua','Historia starożytna','Egipto','Egipt'),
('Historia Antigua','Historia starożytna','Mesopotamia','Mezopotamizacja / Mezopotamia'),
('Historia Antigua','Historia starożytna','Persia','Persja'),
('Historia Antigua','Historia starożytna','Esparta','Sparta'),
('Historia Antigua','Historia starożytna','Atenas','Ateny'),
('Historia Antigua','Historia starożytna','el coliseo','koloseum'),
('Historia Antigua','Historia starożytna','el senat','senat'),
('Historia Antigua','Historia starożytna','la república','republika'),
('Historia Moderna','Historia nowożytna','la historia moderna','historia nowożytna'),
('Historia Moderna','Historia nowożytna','la Edad Moderna','epoka nowożytna'),
('Historia Moderna','Historia nowożytna','el Renacimiento','renesans'),
('Historia Moderna','Historia nowożytna','el Humanismo','humanizm'),
('Historia Moderna','Historia nowożytna','el descubrimiento','odkrycie'),
('Historia Moderna','Historia nowożytna','el explorador','odkrywca / badacz'),
('Historia Moderna','Historia nowożytna','la colonización','kolonizacja'),
('Historia Moderna','Historia nowożytna','la colonia','kolonia'),
('Historia Moderna','Historia nowożytna','la conquista','podbój'),
('Historia Moderna','Historia nowożytna','el continente','kontynent'),
('Historia Moderna','Historia nowożytna','el Nuevo Mundo','Nowy Świat'),
('Historia Moderna','Historia nowożytna','la Reforma','reforma (religiosa)'),
('Historia Moderna','Historia nowożytna','el protestantismo','protestantyzm'),
('Historia Moderna','Historia nowożytna','la Contrarreforma','kontrreformacja'),
('Historia Moderna','Historia nowożytna','la monarquía absoluta','monarchia absolutna'),
('Historia Moderna','Historia nowożytna','el absolutismo','absolutyzm'),
('Historia Moderna','Historia nowożytna','la Revolución','rewolucja'),
('Historia Moderna','Historia nowożytna','la Revolución Industrial','rewolucja przemysłowa'),
('Historia Moderna','Historia nowożytna','la burguesía','burżuazja'),
('Historia Moderna','Historia nowożytna','el proletariado','proletariat'),
('Historia Moderna','Historia nowożytna','el capitalismo','kapitalizm'),
('Historia Moderna','Historia nowożytna','el mercantilismo','merkantylizm'),
('Historia Moderna','Historia nowożytna','la máquina de vapor','maszyna parowa'),
('Historia Moderna','Historia nowożytna','la imprenta','drukarnia'),
('Historia Moderna','Historia nowożytna','el telescopio','teleskop'),
('Historia Moderna','Historia nowożytna','la ilustración','oświecenie'),
('Historia Moderna','Historia nowożytna','la enciclopedia','encyklopedia'),
('Historia Moderna','Historia nowożytna','la independencia','niepodległość'),
('Historia Moderna','Historia nowożytna','la república','republika'),
('Historia Moderna','Historia nowożytna','la democracia','demokracja'),
('Historia Moderna','Historia nowożytna','el ciudadano','obywatel'),
('Historia Moderna','Historia nowożytna','los derechos humanos','prawa człowieka'),
('Historia Moderna','Historia nowożytna','la guillotina','gilotyna'),
('Historia Moderna','Historia nowożytna','el rey','król'),
('Historia Moderna','Historia nowożytna','la reina','królowa'),
('Historia Moderna','Historia nowożytna','la corte','dwór królewski'),
('Historia Moderna','Historia nowożytna','el palacio','pałac'),
('Historia Moderna','Historia nowożytna','la armada','flota wojenna'),
('Historia Moderna','Historia nowożytna','el tratado','traktat / umowa'),
('Historia Moderna','Historia nowożytna','la paz','pokój'),
('Historia Moderna','Historia nowożytna','la crisis','kryzys'),
('Historia Moderna','Historia nowożytna','la hambruna','głód'),
('Historia Moderna','Historia nowożytna','la peste','dżuma / zaraza'),
('Historia Moderna','Historia nowożytna','el siglo','wiek / stulecie'),
('Historia Moderna','Historia nowożytna','la época','epoka'),
('Historia Moderna','Historia nowożytna','el evento','wydarzenie'),
('Historia Moderna','Historia nowożytna','el cambio','zmiana'),
('Historia Moderna','Historia nowożytna','el progreso','postęp'),
('Historia Moderna','Historia nowożytna','la sociedad','społeczeństwo'),
('Historia Moderna','Historia nowożytna','la cultura','kultura'),
('Guerra y Paz','Wojna i pokój','la guerra','wojna'),
('Guerra y Paz','Wojna i pokój','la paz','pokój'),
('Guerra y Paz','Wojna i pokój','el conflicto','konflikt'),
('Guerra y Paz','Wojna i pokój','la batalla','bitwa'),
('Guerra y Paz','Wojna i pokój','el combate','walka / starcie'),
('Guerra y Paz','Wojna i pokój','el ejército','armia / wojsko'),
('Guerra y Paz','Wojna i pokój','el soldado','żołnierza'),
('Guerra y Paz','Wojna i pokój','el oficial','oficer'),
('Guerra y Paz','Wojna i pokój','el general','generał'),
('Guerra y Paz','Wojna i pokój','el comandante','dowódca / komendant'),
('Guerra y Paz','Wojna i pokój','el enemigo','wróg'),
('Guerra y Paz','Wojna i pokój','el aliado','sojusznik'),
('Guerra y Paz','Wojna i pokój','la alianza','sojusz'),
('Guerra y Paz','Wojna i pokój','la tregua','zawieszenie broni / rozejm'),
('Guerra y Paz','Wojna i pokój','el tratado de paz','traktat pokojowy'),
('Guerra y Paz','Wojna i pokój','la rendición','kapitulacja'),
('Guerra y Paz','Wojna i pokój','rendirse','poddać się'),
('Guerra y Paz','Wojna i pokój','la victoria','zwycięstwo'),
('Guerra y Paz','Wojna i pokój','la derrota','porażka'),
('Guerra y Paz','Wojna i pokój','el arma','broń'),
('Guerra y Paz','Wojna i pokój','el arma de fuego','broń palna'),
('Guerra y Paz','Wojna i pokój','el rifle','karabin'),
('Guerra y Paz','Wojna i pokój','la pistola','pistolet'),
('Guerra y Paz','Wojna i pokój','la espada','miecz'),
('Guerra y Paz','Wojna i pokój','la bomba','bomba'),
('Guerra y Paz','Wojna i pokój','el misil','pocisk rakietowy'),
('Guerra y Paz','Wojna i pokój','el tanque','czołg'),
('Guerra y Paz','Wojna i pokój','el avión de combate','samolot myśliwski / myśliwiec'),
('Guerra y Paz','Wojna i pokój','el buque de guerra','okręt wojenny'),
('Guerra y Paz','Wojna i pokój','la base militar','baza wojskowa'),
('Guerra y Paz','Wojna i pokój','la trinchera','okop'),
('Guerra y Paz','Wojna i pokój','el frente','front'),
('Guerra y Paz','Wojna i pokój','la estrategia','strategia'),
('Guerra y Paz','Wojna i pokój','la táctica','taktyka'),
('Guerra y Paz','Wojna i pokój','el espía','szpieg'),
('Guerra y Paz','Wojna i pokój','el espionaje','szpiegostwo'),
('Guerra y Paz','Wojna i pokój','la inteligencia','wywiad (służba)'),
('Guerra y Paz','Wojna i pokój','el prisionero de guerra','jeeniec wojenny'),
('Guerra y Paz','Wojna i pokój','el refugiado','uchodźca'),
('Guerra y Paz','Wojna i pokój','la víctima','ofiara'),
('Guerra y Paz','Wojna i pokój','el herido','ranny'),
('Guerra y Paz','Wojna i pokój','el hospital de campaña','szpital polowy'),
('Guerra y Paz','Wojna i pokój','la destrucción','zniszczenie'),
('Guerra y Paz','Wojna i pokój','los escombros','gruzy'),
('Guerra y Paz','Wojna i pokój','la amenaza','zagrożenie'),
('Guerra y Paz','Wojna i pokój','la tensión','napięcie'),
('Guerra y Paz','Wojna i pokój','la diplomacia','dyplomacja'),
('Guerra y Paz','Wojna i pokój','el desarme','rozbrojenie'),
('Guerra y Paz','Wojna i pokój','la seguridad','bezpieczeństwo'),
('Guerra y Paz','Wojna i pokój','el monumento a los caídos','pomnik poległych'),
('Sistema Político','System polityczny','el sistema político','system polityczny'),
('Sistema Político','System polityczny','la política','polityka'),
('Sistema Político','System polityczny','el gobierno','rząd'),
('Sistema Político','System polityczny','el Estado','państwo'),
('Sistema Político','System polityczny','la democracia','demokracja'),
('Sistema Político','System polityczny','la dictadura','dyktatura'),
('Sistema Político','System polityczny','la monarquía','monarchia'),
('Sistema Político','System polityczny','la república','republika'),
('Sistema Político','System polityczny','la constitución','konstytucja'),
('Sistema Político','System polityczny','las leyes','prawa / ustawy'),
('Sistema Político','System polityczny','el poder','władza'),
('Sistema Político','System polityczny','la división de poderes','trójpodział władzy'),
('Sistema Político','System polityczny','el poder ejecutivo','władza wykonawcza'),
('Sistema Político','System polityczny','el poder legislativo','władza ustawodawcza'),
('Sistema Político','System polityczny','el poder judicial','władza sądownicza'),
('Sistema Político','System polityczny','el parlamento','parlament'),
('Sistema Político','System polityczny','el congreso','kongres'),
('Sistema Político','System polityczny','el senado','senat'),
('Sistema Político','System polityczny','el diputado','poseł'),
('Sistema Político','System polityczny','el senador','senator'),
('Sistema Político','System polityczny','el presidente','prezident'),
('Sistema Político','System polityczny','el primer ministro','premier'),
('Sistema Político','System polityczny','el ministro','minister'),
('Sistema Político','System polityczny','el ministerio','ministerstwo'),
('Sistema Político','System polityczny','el partido político','partia polityczna'),
('Sistema Político','System polityczny','las elecciones','wybory'),
('Sistema Político','System polityczny','votar','głosować'),
('Sistema Político','System polityczny','el voto','głos'),
('Sistema Político','System polityczny','el electorado','elektorat / wyborcy'),
('Sistema Político','System polityczny','la campaña electoral','kampania wyborcza'),
('Sistema Político','System polityczny','el candidato','kandydat'),
('Sistema Político','System polityczny','la oposición','opozycja'),
('Sistema Político','System polityczny','la mayoría','większość'),
('Sistema Político','System polityczny','la minoría','mniejszość'),
('Sistema Político','System polityczny','la coalición','koalicja'),
('Sistema Político','System polityczny','el ayuntamiento','urząd miasta / ratusz'),
('Sistema Político','System polityczny','el alcalde','burmistrz / prezydent miasta'),
('Sistema Político','System polityczny','la diplomacia','dyplomacja'),
('Sistema Político','System polityczny','el embajador','ambasador'),
('Sistema Político','System polityczny','la embajada','ambasada'),
('Sistema Político','System polityczny','el derecho','prawo'),
('Sistema Político','System polityczny','la libertad','wolność'),
('Sistema Político','System polityczny','la igualdad','równość'),
('Sistema Político','System polityczny','la justicia','sprawiedliwość'),
('Sistema Político','System polityczny','la corrupción','korupcja'),
('Sistema Político','System polityczny','el ciudadano','obywatel'),
('Sistema Político','System polityczny','la ciudadanía','obywatelstwo'),
('Sistema Político','System polityczny','la reforma','reforma'),
('Sistema Político','System polityczny','la crisis política','kryzys polityczny'),
('Sistema Político','System polityczny','la soberanía','suwerenność'),
('Elecciones','Wybory','las elecciones','wybory'),
('Elecciones','Wybory','el voto','głos'),
('Elecciones','Wybory','votar','głosować'),
('Elecciones','Wybory','el votante','wyborca'),
('Elecciones','Wybory','el electorado','elektorat'),
('Elecciones','Wybory','el colegio electoral','lokal wyborczy'),
('Elecciones','Wybory','la urna','urna wyborcza'),
('Elecciones','Wybory','la papeleta','karta do głosowania'),
('Elecciones','Wybory','el candidato','kandydat'),
('Elecciones','Wybory','el partido político','partia polityczna'),
('Elecciones','Wybory','la campaña electoral','kampania wyborcza'),
('Elecciones','Wybory','el mitin','wiec wyborczy'),
('Elecciones','Wybory','el debate','debata'),
('Elecciones','Wybory','el programa electoral','program wyborczy'),
('Elecciones','Wybory','la encuesta','sondaż / ankieta'),
('Elecciones','Wybory','el sondeo de opinión','sondaż opinii publicznej'),
('Elecciones','Wybory','la mayoría','większość'),
('Elecciones','Wybory','la minoría','mniejszość'),
('Elecciones','Wybory','la coalición','koalicja'),
('Elecciones','Wybory','el escaño','mandat / miejsce w parlamencie'),
('Elecciones','Wybory','el parlamento','parlament'),
('Elecciones','Wybory','el congreso','kongres'),
('Elecciones','Wybory','el senado','senat'),
('Elecciones','Wybory','el diputado','poseł'),
('Elecciones','Wybory','el senador','senator'),
('Elecciones','Wybory','el alcalde','burmistrz / prezydent miasta'),
('Elecciones','Wybory','el presidente','prezydent'),
('Elecciones','Wybory','el primer ministro','premier'),
('Elecciones','Wybory','el gobierno','rząd'),
('Elecciones','Wybory','la oposición','opozycja'),
('Elecciones','Wybory','ganar','wygrać'),
('Elecciones','Wybory','perder','przegrać'),
('Elecciones','Wybory','el resultado','wynik'),
('Elecciones','Wybory','la victoria','zwycięstwo'),
('Elecciones','Wybory','la derrota','porażka'),
('Elecciones','Wybory','el recuento','przeliczanie głosów'),
('Elecciones','Wybory','la abstención','abstencja'),
('Elecciones','Wybory','el censo electoral','spis wyborców'),
('Elecciones','Wybory','el sufragio','prawo głosu'),
('Elecciones','Wybory','el sufragio universal','wybory powszechne'),
('Elecciones','Wybory','la circunscripción','okręg wyborczy'),
('Elecciones','Wybory','la jornada electoral','dzień wyborów'),
('Elecciones','Wybory','el escrutinio','skrutynium / podsumowanie głosów'),
('Elecciones','Wybory','proclamar','ogłosić / proklamować'),
('Elecciones','Wybory','jurar','składać przysięgę'),
('Elecciones','Wybory','la investidura','zaprzysiężenie'),
('Elecciones','Wybory','el mandato','kadencja / mandat'),
('Elecciones','Wybory','la reelección','reelekcja / ponowny wybór'),
('Elecciones','Wybory','fraudulento','sfałszowany / oszukańczy'),
('Elecciones','Wybory','democrático','demokratyczny'),
('Derechos Humanos','Prawa człowieka','los derechos humanos','prawa człowieka'),
('Derechos Humanos','Prawa człowieka','el derecho','prawo'),
('Derechos Humanos','Prawa człowieka','la libertad','wolność'),
('Derechos Humanos','Prawa człowieka','la igualdad','równość'),
('Derechos Humanos','Prawa człowieka','la dignidad','godność'),
('Derechos Humanos','Prawa człowieka','la justicia','sprawiedliwość'),
('Derechos Humanos','Prawa człowieka','la discriminación','dyskryminacja'),
('Derechos Humanos','Prawa człowieka','discriminar','dyskryminować'),
('Derechos Humanos','Prawa człowieka','el racismo','rasizm'),
('Derechos Humanos','Prawa człowieka','racista','rasistowski'),
('Derechos Humanos','Prawa człowieka','la xenofobia','ksenofobia'),
('Derechos Humanos','Prawa człowieka','el sexismo','seksizm'),
('Derechos Humanos','Prawa człowieka','la igualdad de género','równość płci'),
('Derechos Humanos','Prawa człowieka','la tolerancia','tolerancja'),
('Derechos Humanos','Prawa człowieka','tolerar','tolerować'),
('Derechos Humanos','Prawa człowieka','la opresión','ucisk / uciemiężenie'),
('Derechos Humanos','Prawa człowieka','oprimir','uciskać'),
('Derechos Humanos','Prawa człowieka','la persecución','prześladowanie'),
('Derechos Humanos','Prawa człowieka','perseguir','prześladować'),
('Derechos Humanos','Prawa człowieka','la libertad de expresión','wolność słowa'),
('Derechos Humanos','Prawa człowieka','la libertad de prensa','wolność prasy'),
('Derechos Humanos','Prawa człowieka','la libertad religiosa','wolność religijna'),
('Derechos Humanos','Prawa człowieka','la libertad de reunión','wolność zgromadzeń'),
('Derechos Humanos','Prawa człowieka','el asilo','azyl'),
('Derechos Humanos','Prawa człowieka','el refugiado','uchodźca'),
('Derechos Humanos','Prawa człowieka','el asilado','azylant'),
('Derechos Humanos','Prawa człowieka','la tortura','tortura'),
('Derechos Humanos','Prawa człowieka','torturar','torturować'),
('Derechos Humanos','Prawa człowieka','la esclavitud','niewolnictwo'),
('Derechos Humanos','Prawa człowieka','el esclavo','niewolnik'),
('Derechos Humanos','Prawa człowieka','la Declaración Universal','Powszechna Deklaracja'),
('Derechos Humanos','Prawa człowieka','Amnistía Internacional','Amnesty International'),
('Derechos Humanos','Prawa człowieka','el activista','aktywista'),
('Derechos Humanos','Prawa człowieka','la manifestación','manifestacja'),
('Derechos Humanos','Prawa człowieka','manifestarse','manifestować'),
('Derechos Humanos','Prawa człowieka','la protesta','protest'),
('Derechos Humanos','Prawa człowieka','protestar','protestować'),
('Derechos Humanos','Prawa człowieka','la huelga','strajk'),
('Derechos Humanos','Prawa człowieka','la censura','cenzura'),
('Derechos Humanos','Prawa człowieka','censurar','cenzurować'),
('Derechos Humanos','Prawa człowieka','la igualdad de oportunidades','równość szans'),
('Derechos Humanos','Prawa człowieka','el derecho al voto','prawo do głosowania'),
('Derechos Humanos','Prawa człowieka','la dignidad humana','godność ludzka'),
('Derechos Humanos','Prawa człowieka','el respeto','szacunek'),
('Derechos Humanos','Prawa człowieka','respetar','szanować'),
('Derechos Humanos','Prawa człowieka','la vulnerabilidad','wrażliwość / podatność'),
('Derechos Humanos','Prawa człowieka','vulnerable','wrażliwy / podatny'),
('Derechos Humanos','Prawa człowieka','la injusticia','niesprawiedliwość'),
('Derechos Humanos','Prawa człowieka','la impunidad','bezkarność'),
('Derechos Humanos','Prawa człowieka','la paz','pokój'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la delincuencia','przestępczość'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el delincuente','przestępca'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el crimen','przestępstwo / zbrodnia'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el delito','przestępstwo'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la falta','wykroczenie'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el robo','kradzież'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','robar','kraść'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el ladrón','złodziej'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el asalto','napad'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','asaltar','napadać'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el hurto','kradzież bez przemocy'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el asesinato','zabójstwo / morderstwo'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','asesinar','zamordować'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el asesino','morderca'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el secuestro','porwanie'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','secuestrar','porwać'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la extorsión','wymuszenie / szantaż'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el soborno','łapówka'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el fraude','oszustwo'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la estafa','wyłudzenie'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el estafador','oszust'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el narcotráfico','handel narkotykami'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el narcotraficante','handlarz narkotykami'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la corrupción','korupcja'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el vandalismo','wandalizm'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la violencia','przemoc'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la agresión','agresja / napaść'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','agredir','zaatakować'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la víctima','ofiara'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el testigo','świadek'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el sospechoso','podejrzany'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la prueba','dowód'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la investigación','śledztwo'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','investigcar','prowadzić śledztwo'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el juez','sędzia'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el tribunal','sąd'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la sentencia','wyrok'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','condenar','skazać'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la condena','skazanie / wyrok'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la cárcel','więzienie'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el preso','więzień'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la prisión','areszt / więzienie'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la multa','grzywna'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la libertad condicional','warunkowe zwolnienie'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el abogado','prawnik / adwokat'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el fiscal','prokurator'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la fiscalía','prokuratura'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la ley','prawo'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el código penal','kodeks karny'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la justicia','sprawiedliwość'),
('Policía','Policja','la policía','policja'),
('Policía','Policja','el policía','policjant'),
('Policía','Policja','el agente','funkcjonariusz'),
('Policía','Policja','la comisaría','komisariat policji'),
('Policía','Policja','el coche de patrulla','radiowóz'),
('Policía','Policja','la sirena','syrena'),
('Policía','Policja','la patrulla','patrol'),
('Policía','Policja','patrullar','patrolować'),
('Policía','Policja','el uniforme','mundur'),
('Policía','Policja','la placa','odznaka'),
('Policía','Policja','las esposas','kajdanki'),
('Policía','Policja','esposar','zakładać kajdanki'),
('Policía','Policja','el arresto','aresztowanie'),
('Policía','Policja','detener','zatrzymać / aresztować'),
('Policía','Policja','la detención','zatrzymanie'),
('Policía','Policja','el control de carretera','kontrola drogowa'),
('Policía','Policja','el radar','radar'),
('Policía','Policja','la multa','mandat'),
('Policía','Policja','poner una multa','wystawić mandat'),
('Policía','Policja','el alcoholímetro','alkomat'),
('Policía','Policja','la prueba de alcoholemia','badanie alkomatem'),
('Policía','Policja','el tráfico','ruch drogowy'),
('Policía','Policja','el orden público','porządek publiczny'),
('Policía','Policja','la seguridad ciudadana','bezpieczeństwo publiczne'),
('Policía','Policja','la investigación','dochodzenie'),
('Policía','Policja','interrogar','przesłuchiwać'),
('Policía','Policja','el interrogatorio','przesłuchanie'),
('Policía','Policja','la pista','trop / ślad'),
('Policía','Policja','el sospechoso','podejrzany'),
('Policía','Policja','la huella dactilar','odcisk palca'),
('Policía','Policja','la escena del crimen','miejsce zbrodni'),
('Policía','Policja','la persecución','pościg'),
('Policía','Policja','perseguir','ścigać'),
('Policía','Policja','disparar','strzelać'),
('Policía','Policja','el disparo','strzał'),
('Policía','Policja','el arma de fuego','broń palna'),
('Policía','Policja','el chaleco antibalas','kamizelka kuloodporna'),
('Policía','Policja','la comisaría central','komisariat centralny'),
('Policía','Policja','el turno','zmiana'),
('Policía','Policja','el rescate','ratunek'),
('Policía','Policja','la llamada de emergencia','zgłoszenie alarmowe'),
('Policía','Policja','el número de emergencia','numer alarmowy'),
('Policía','Policja','el antidisturbios','oddział prewencji'),
('Policía','Policja','la manifestación','zgromadzenie'),
('Policía','Policja','disolver','rozpędzić tłum'),
('Policía','Policja','la seguridad','bezpieczeństwo'),
('Policía','Policja','proteger','chronić'),
('Policía','Policja','auxiliar','udzielać pomocy'),
('Policía','Policja','el parte policial','raport policyjny'),
('Policía','Policja','la autoridad','władza / organ ścigania'),
('En el Tribunal','W sądzie','el tribunal','sąd'),
('En el Tribunal','W sądzie','el juzgado','urząd sądowy'),
('En el Tribunal','W sądzie','la sala de audiencias','sala rozpraw'),
('En el Tribunal','W sądzie','el juez','sędzia'),
('En el Tribunal','W sądzie','el magistrado','sędzia trybunału'),
('En el Tribunal','W sądzie','el fiscal','prokurator'),
('En el Tribunal','W sądzie','el abogado','adwokat'),
('En el Tribunal','W sądzie','el abogado defensor','obrońca'),
('En el Tribunal','W sądzie','el acusado','oskarżony'),
('En el Tribunal','W sądzie','el demandante','powód'),
('En el Tribunal','W sądzie','el demandado','pozwany'),
('En el Tribunal','W sądzie','la demanda','pozew'),
('En el Tribunal','W sądzie','la acusación','oskarżenie'),
('En el Tribunal','W sądzie','el testigo','świadek'),
('En el Tribunal','W sądzie','el perito','biegły sądowy'),
('En el Tribunal','W sądzie','el jurado','ław przysięgłych'),
('En el Tribunal','W sądzie','el miembro del jurado','przysięgły'),
('En el Tribunal','W sądzie','la prueba','dowód'),
('En el Tribunal','W sądzie','la evidencia','dowód rzeczowy'),
('En el Tribunal','W sądzie','el testimonio','zeznanie'),
('En el Tribunal','W sądzie','declarar','składać zeznania'),
('En el Tribunal','W sądzie','el interrogatorio','przesłuchanie'),
('En el Tribunal','W sądzie','interrogar','przesłuchiwać'),
('En el Tribunal','W sądzie','la objeción','sprzeciw'),
('En el Tribunal','W sądzie','objetar','zgłaszać sprzeciw'),
('En el Tribunal','W sądzie','el veredicto','werdykt'),
('En el Tribunal','W sądzie','la sentencia','wyrok'),
('En el Tribunal','W sądzie','condenar','skazać'),
('En el Tribunal','W sądzie','absolver','uniewinnić'),
('En el Tribunal','W sądzie','la absolución','uniewinnienie'),
('En el Tribunal','W sądzie','la condena','wyrok skazujący'),
('En el Tribunal','W sądzie','la apelación','apelacja'),
('En el Tribunal','W sądzie','apelar','składać apelację'),
('En el Tribunal','W sądzie','el recurso','środek odwoławczy'),
('En el Tribunal','W sądzie','el caso','sprawa'),
('En el Tribunal','W sądzie','la vista','rozprawa'),
('En el Tribunal','W sądzie','el juicio','proces sądowy'),
('En el Tribunal','W sądzie','la coartada','alibi'),
('En el Tribunal','W sądzie','el secreto de sumario','tajemnica śledztwa'),
('En el Tribunal','W sądzie','firmar','podpisać'),
('En el Tribunal','W sądzie','dictar sentencia','wydać wyrok'),
('En el Tribunal','W sądzie','el magistrado presidente','przewodniczący składu'),
('En el Tribunal','W sądzie','la indemnización','odszkodowanie'),
('En el Tribunal','W sądzie','los daños y perjuicios','odszkodowanie za straty'),
('En el Tribunal','W sądzie','culpable','winny'),
('En el Tribunal','W sądzie','inocente','niewinny'),
('En el Tribunal','W sądzie','la culpabilidad','wina'),
('En el Tribunal','W sądzie','la inocencia','niewinność'),
('En el Tribunal','W sądzie','el acta','protokół'),
('En el Tribunal','W sądzie','el secretario judicial','sekretarz sądowy'),
('Prisión','Więzienie','la prisión','więzienie'),
('Prisión','Więzienie','la cárcel','więzienie / areszt'),
('Prisión','Więzienie','la penitenciaría','zakład karny'),
('Prisión','Więzienie','el calabozo','karcer / loch / celi policyjna'),
('Prisión','Więzienie','la celda','cela'),
('Prisión','Więzienie','el recluso / el preso','więziec / osadzony'),
('Prisión','Więzienie','el criminal','przestępca'),
('Prisión','Więzienie','el delincuente','skazany'),
('Prisión','Więzienie','el alcaide','naczelnik więzienia'),
('Prisión','Więzienie','el guardia','strażnik więzienny'),
('Prisión','Więzienie','el carcelero','dozorca więzienny'),
('Prisión','Więzienie','la condena','wyrok skazujący'),
('Prisión','Więzienie','cumplic condena','odsiadwać wyrok'),
('Prisión','Więzienie','la cadena perpetua','dożywocie'),
('Prisión','Więzienie','la celda de aislamiento','cela izolacyjna'),
('Prisión','Więzienie','el patio','dziedziniec więzienny'),
('Prisión','Więzienie','el 3er grado','przepustka / wolność kontrolowada'),
('Prisión','Więzienie','la libertad condicional','warunkowe przedterminowe zwolnienie'),
('Prisión','Więzienie','la fuga','ucieczka'),
('Prisión','Więzienie','fugarse','uciec z więzienia'),
('Prisión','Więzienie','el preso fugado','zbieg'),
('Prisión','Więzienie','la visita','widzenie (w więzieniu)'),
('Prisión','Więzienie','el vis a vis','widzenie intymne / bez nadzoru'),
('Prisión','Więzienie','la huelga de hambre','strajk głodowy'),
('Prisión','Więzienie','la revuelta','bunt (więzienny)'),
('Prisión','Więzienie','el motín','zamieszki / bunt'),
('Prisión','Więzienie','la rehabilitación','resocjalizacja'),
('Prisión','Więzienie','rehabitarse','resocjalizować się'),
('Prisión','Więzienie','el régimen penitenciario','system penitencjarny'),
('Prisión','Więzienie','la condena condicional','wyrok w zawieszeniu'),
('Prisión','Więzienie','el brazalete electrónico','obrączka elektroniczna'),
('Prisión','Więzienie','la condena de trabajos','prace społeczne'),
('Prisión','Więzienie','el indulto','ułaskawienie'),
('Prisión','Więzienie','indultar','ułaskawić'),
('Prisión','Więzienie','la amnistía','amnestia'),
('Prisión','Więzienie','el expediente','akta / kartoteka'),
('Prisión','Więzienie','el ingreso en prisión','osadzenie w zakładzie karnym'),
('Prisión','Więzienie','la libertad','wolność'),
('Prisión','Więzienie','salir en libertad','wyjść na wolność'),
('Prisión','Więzienie','el reincidente','recydywista'),
('Prisión','Więzienie','la reincidencia','recydywa'),
('Prisión','Więzienie','el delito menor','wykroczenie / drobny przestępca'),
('Prisión','Więzienie','la seguridad','bezpieczeństwo'),
('Prisión','Więzienie','el control','kontrola'),
('Prisión','Więzienie','el cacheo','rewizja osobistia'),
('Prisión','Więzienie','la requisa','przeszukanie celi'),
('Prisión','Więzienie','el contrabando','kontrabanda'),
('Prisión','Więzienie','el aislamiento','izolacja'),
('Prisión','Więzienie','el grillete','kajdanki na nogi'),
('Prisión','Więzienie','la llave','klucz');
