insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('En el Aeropuerto','Na lotnisku','el aeropuerto','lotnisko'),
('En el Aeropuerto','Na lotnisku','el avión','samolot'),
('En el Aeropuerto','Na lotnisku','el vuelo','lot'),
('En el Aeropuerto','Na lotnisku','la terminal','terminal'),
('En el Aeropuerto','Na lotnisku','la puerta de embarque','bramka (gate)'),
('En el Aeropuerto','Na lotnisku','el mostrador','stanowisko odprawy'),
('En el Aeropuerto','Na lotnisku','la facturación','odprawa biletowa'),
('En el Aeropuerto','Na lotnisku','el billete','bilet'),
('En el Aeropuerto','Na lotnisku','la tarjeta de embarque','karta pokładowa'),
('En el Aeropuerto','Na lotnisku','el pasaporte','paszport'),
('En el Aeropuerto','Na lotnisku','el carné de identidad','dowód osobisty'),
('En el Aeropuerto','Na lotnisku','el visado','wiza'),
('En el Aeropuerto','Na lotnisku','el equipaje','bagaż'),
('En el Aeropuerto','Na lotnisku','la maleta','walizka'),
('En el Aeropuerto','Na lotnisku','el equipaje de mano','bagaż podręczny'),
('En el Aeropuerto','Na lotnisku','la cinta','taśma bagażowa'),
('En el Aeropuerto','Na lotnisku','la aduana','urząd celny / cło'),
('En el Aeropuerto','Na lotnisku','el control de seguridad','kontrola bezpieczeństwa'),
('En el Aeropuerto','Na lotnisku','el pasajero','pasażer'),
('En el Aeropuerto','Na lotnisku','el piloto','pilot'),
('En el Aeropuerto','Na lotnisku','la azafata','stewardesa'),
('En el Aeropuerto','Na lotnisku','el asiento','siedzenie / miejsce'),
('En el Aeropuerto','Na lotnisku','el cinturón de seguridad','pas bezpieczeństwa'),
('En el Aeropuerto','Na lotnisku','despegar','startować'),
('En el Aeropuerto','Na lotnisku','el despegue','start (samolotu)'),
('En el Aeropuerto','Na lotnisku','aterrizar','lądować'),
('En el Aeropuerto','Na lotnisku','el aterrizaje','lądowanie'),
('En el Aeropuerto','Na lotnisku','el retraso','opóźnienie'),
('En el Aeropuerto','Na lotnisku','retrasado','opóźniony'),
('En el Aeropuerto','Na lotnisku','cancelado','odwołany'),
('En el Aeropuerto','Na lotnisku','a tiempo','na czas'),
('En el Aeropuerto','Na lotnisku','la llegada','przylot'),
('En el Aeropuerto','Na lotnisku','la salida','odlot'),
('En el Aeropuerto','Na lotnisku','la escala','międzylądowanie / przesiadka'),
('En el Aeropuerto','Na lotnisku','la compañía aérea','linia lotnicza'),
('En el Aeropuerto','Na lotnisku','el exceso de equipaje','nadbagaż'),
('En el Aeropuerto','Na lotnisku','declarar','clić / deklarować'),
('En el Aeropuerto','Na lotnisku','la pantalla','ekran / tablica odlotów'),
('En el Aeropuerto','Na lotnisku','el vuelo nacional','lot krajowy'),
('En el Aeropuerto','Na lotnisku','el vuelo internacional','lot międzynarodowy'),
('En el Aeropuerto','Na lotnisku','la sala de espera','poczekalnia'),
('En el Aeropuerto','Na lotnisku','el carrito','wózek na bagaż'),
('En el Aeropuerto','Na lotnisku','el asiento de pasillo','miejsce przy korytarzu'),
('En el Aeropuerto','Na lotnisku','el asiento de ventanilla','miejsce przy oknie'),
('En el Aeropuerto','Na lotnisku','la emergencia','awaria / nagły wypadek'),
('En el Aeropuerto','Na lotnisku','el chaleco salvavidas','kamizelka ratunkowa'),
('En el Aeropuerto','Na lotnisku','la máscara de oxígeno','maska tlenowa'),
('En el Aeropuerto','Na lotnisku','volar','latać'),
('En el Aeropuerto','Na lotnisku','el destino','cel podróży'),
('En el Aeropuerto','Na lotnisku','el viaje','podróż'),
('Las Direcciones','Kierunki','la dirección','kierunek / adres'),
('Las Direcciones','Kierunki','la calle','ulica'),
('Las Direcciones','Kierunki','la avenida','aleja'),
('Las Direcciones','Kierunki','la plaza','plac'),
('Las Direcciones','Kierunki','el cruce','skrzyżowanie'),
('Las Direcciones','Kierunki','la esquina','róg'),
('Las Direcciones','Kierunki','el semáforo','sygnalizacja świetlna'),
('Las Direcciones','Kierunki','el paso de cebra','przejście dla pieszych'),
('Las Direcciones','Kierunki','la acera','chodnik'),
('Las Direcciones','Kierunki','el puente','most'),
('Las Direcciones','Kierunki','el túnel','tunel'),
('Las Direcciones','Kierunki','el edificio','budynek'),
('Las Direcciones','Kierunki','el barrio','dzielnica'),
('Las Direcciones','Kierunki','el mapa','mapa'),
('Las Direcciones','Kierunki','el plano','plan (miasta)'),
('Las Direcciones','Kierunki','el GPS','GPS'),
('Las Direcciones','Kierunki','la ruta','trasa'),
('Las Direcciones','Kierunki','el norte','północ'),
('Las Direcciones','Kierunki','el sur','południe'),
('Las Direcciones','Kierunki','el este','wschód'),
('Las Direcciones','Kierunki','el oeste','zachód'),
('Las Direcciones','Kierunki','la derecha','prawa strona'),
('Las Direcciones','Kierunki','la izquierda','lewa strona'),
('Las Direcciones','Kierunki','recto','prosto'),
('Las Direcciones','Kierunki','hacia adelante','naprzód'),
('Las Direcciones','Kierunki','hacia atrás','w tył'),
('Las Direcciones','Kierunki','arriba','w górę / na górze'),
('Las Direcciones','Kierunki','abajo','w dół / na dole'),
('Las Direcciones','Kierunki','cerca','blisko'),
('Las Direcciones','Kierunki','lejos','daleko'),
('Las Direcciones','Kierunki','aquí','tutaj'),
('Las Direcciones','Kierunki','allí / allá','tam'),
('Las Direcciones','Kierunki','enfrente de','naprzeciwko'),
('Las Direcciones','Kierunki','detrás de','za'),
('Las Direcciones','Kierunki','al lado de','obok'),
('Las Direcciones','Kierunki','entre','pomiędzy'),
('Las Direcciones','Kierunki','cruzar','przechodzić / przekraczać'),
('Las Direcciones','Kierunki','girar / torcer','skręcać'),
('Las Direcciones','Kierunki','seguir / continuar','kontynuować / iść dalej'),
('Las Direcciones','Kierunki','parar','zatrzymywać się'),
('Las Direcciones','Kierunki','buscar','szukać'),
('Las Direcciones','Kierunki','encontrar','znaleźć'),
('Las Direcciones','Kierunki','perderse','zgubić się'),
('Las Direcciones','Kierunki','estar perdido','być zagubionym'),
('Las Direcciones','Kierunki','preguntar','pytać'),
('Las Direcciones','Kierunki','la distancia','odległość'),
('Las Direcciones','Kierunki','el kilómetro','kilometr'),
('Las Direcciones','Kierunki','el metro','metr'),
('Las Direcciones','Kierunki','ir','iść / jechać'),
('Las Direcciones','Kierunki','llegar','przybywać / docierać'),
('El Dinero','Pieniądze','el dinero','pieniądze'),
('El Dinero','Pieniądze','el efectivo','gotówka'),
('El Dinero','Pieniądze','la moneda','moneta / waluta'),
('El Dinero','Pieniądze','el billete','banknot'),
('El Dinero','Pieniądze','el sueldo','pensja'),
('El Dinero','Pieniądze','el salario','wynagrodzenie'),
('El Dinero','Pieniądze','la cartera','portfel'),
('El Dinero','Pieniądze','el monedero','portmonetka'),
('El Dinero','Pieniądze','el banco','bank'),
('El Dinero','Pieniądze','la cuenta bancaria','konto bankowe'),
('El Dinero','Pieniądze','la tarjeta de crédito','karta kredytowa'),
('El Dinero','Pieniądze','la tarjeta de débito','karta debetowa'),
('El Dinero','Pieniądze','el cajero automático','bankomat'),
('El Dinero','Pieniądze','el PIN','kod PIN'),
('El Dinero','Pieniądze','el cambio','reszta (z zakupów)'),
('El Dinero','Pieniądze','la divisa','waluta obca'),
('El Dinero','Pieniądze','el euro','euro'),
('El Dinero','Pieniądze','el dólar','dolar'),
('El Dinero','Pieniądze','el zloty','złoty'),
('El Dinero','Pieniądze','el precio','cena'),
('El Dinero','Pieniądze','caro','drogi'),
('El Dinero','Pieniądze','barato','tani'),
('El Dinero','Pieniądze','gratis','za darmo'),
('El Dinero','Pieniądze','costar','kosztować'),
('El Dinero','Pieniądze','pagar','płacić'),
('El Dinero','Pieniądze','cobrar','pobierać opłatę / zarabiać'),
('El Dinero','Pieniądze','comprar','kupować'),
('El Dinero','Pieniądze','vender','sprzedawać'),
('El Dinero','Pieniądze','gastar','wydawać'),
('El Dinero','Pieniądze','ahorrar','oszczędzać'),
('El Dinero','Pieniądze','prestar','pożyczać (komuś)'),
('El Dinero','Pieniądze','pedir prestado','pożyczać (od kogoś)'),
('El Dinero','Pieniądze','deber','być winnym'),
('El Dinero','Pieniądze','la deuda','dług'),
('El Dinero','Pieniądze','la factura','faktura'),
('El Dinero','Pieniądze','el recibo','paragon'),
('El Dinero','Pieniądze','la caja','kasa (w sklepie)'),
('El Dinero','Pieniądze','el descuento','zniżka'),
('El Dinero','Pieniądze','la oferta','oferta / promocja'),
('El Dinero','Pieniądze','la rebaja','wyprzedaż / obniżka'),
('El Dinero','Pieniądze','el porcentaje','procent'),
('El Dinero','Pieniądze','la comisión','prowizja'),
('El Dinero','Pieniądze','el impuesto','podatek'),
('El Dinero','Pieniądze','el interés','odsetki'),
('El Dinero','Pieniądze','rico','bogaty'),
('El Dinero','Pieniądze','pobre','biedny'),
('El Dinero','Pieniądze','la riqueza','bogactwo'),
('El Dinero','Pieniądze','la pobreza','bieda'),
('El Dinero','Pieniądze','la propina','napiwek'),
('El Dinero','Pieniądze','la alcancía / la hucha','skarbonka'),
('De Compras','Na zakupach','ir de compras','iść na zakupy'),
('De Compras','Na zakupach','la tienda','sklep'),
('De Compras','Na zakupach','el centro comercial','centrum handlowe'),
('De Compras','Na zakupach','el mercado','rynek / targ'),
('De Compras','Na zakupach','el supermercado','supermarket'),
('De Compras','Na zakupach','el dependiente / la dependienta','ekspedient / ekspedientka'),
('De Compras','Na zakupach','el cliente / la clienta','klient / klientka'),
('De Compras','Na zakupach','el escaparate','witryna sklepowa'),
('De Compras','Na zakupach','el probador','przymierzalnia'),
('De Compras','Na zakupach','probarse','przymierzać (ubranie)'),
('De Compras','Na zakupach','la talla','rozmiar (ubrania)'),
('De Compras','Na zakupach','el número','rozmiar (buta)'),
('De Compras','Na zakupach','quedar bien','pasować / dobrze leżeć'),
('De Compras','Na zakupach','quedar mal','nie pasować / źle leżeć'),
('De Compras','Na zakupach','el carrito','wózek na zakupy'),
('De Compras','Na zakupach','la cesta','koszyk (na zakupy)'),
('De Compras','Na zakupach','la bolsa','torba / siatka'),
('De Compras','Na zakupach','la caja','kasa'),
('De Compras','Na zakupach','el cajero / la cajera','kasjer / kasjerka'),
('De Compras','Na zakupach','la cola / la fila','kolejka'),
('De Compras','Na zakupach','hacer cola','stać w kolejce'),
('De Compras','Na zakupach','el precio','cena'),
('De Compras','Na zakupach','la etiqueta','etykieta / metka'),
('De Compras','Na zakupach','el descuento','zniżka'),
('De Compras','Na zakupach','la oferta','oferta / promocja'),
('De Compras','Na zakupach','las rebajas','wyprzedaże'),
('De Compras','Na zakupach','barato','tani'),
('De Compras','Na zakupach','caro','drogi'),
('De Compras','Na zakupach','gratis','za darmo'),
('De Compras','Na zakupach','pagar','płacić'),
('De Compras','Na zakupach','en efectivo','gotówką'),
('De Compras','Na zakupach','con tarjeta','kartą'),
('De Compras','Na zakupach','el cambio','reszta (pieniądze)'),
('De Compras','Na zakupach','el recibo / el ticket','paragon'),
('De Compras','Na zakupach','la factura','faktura'),
('De Compras','Na zakupach','la garantía','gwarancja'),
('De Compras','Na zakupach','devolver','zwracać'),
('De Compras','Na zakupach','el reembolso','zwrot pieniędzy'),
('De Compras','Na zakupach','comprar','kupować'),
('De Compras','Na zakupach','vender','sprzedawać'),
('De Compras','Na zakupach','gastar','wydawać (pieniądze)'),
('De Compras','Na zakupach','abierto','otwarty'),
('De Compras','Na zakupach','cerrado','zamknięty'),
('De Compras','Na zakupach','el horario','godziny otwarcia'),
('De Compras','Na zakupach','la marca','marka'),
('De Compras','Na zakupach','de segunda mano','z drugiej ręki / używany'),
('De Compras','Na zakupach','el producto','produkt'),
('De Compras','Na zakupach','la calidad','jakość'),
('De Compras','Na zakupach','envolver','pakować (np. na prezent)'),
('De Compras','Na zakupach','el turno','kolej (w kolejce)'),
('Los Muebles','Meble','el mueble','mebel'),
('Los Muebles','Meble','amueblar','umeblować'),
('Los Muebles','Meble','la silla','krzesło'),
('Los Muebles','Meble','la mesa','stół'),
('Los Muebles','Meble','el sofá','kanapa'),
('Los Muebles','Meble','el sillón','fotel'),
('Los Muebles','Meble','la cama','łóżko'),
('Los Muebles','Meble','el armario','szafa'),
('Los Muebles','Meble','la estantería','regał'),
('Los Muebles','Meble','el estante','półka'),
('Los Muebles','Meble','la cómoda','komoda'),
('Los Muebles','Meble','el cajón','szuflada'),
('Los Muebles','Meble','la mesita de noche','stolik nocny'),
('Los Muebles','Meble','el escritorio','biurko'),
('Los Muebles','Meble','el taburete','stołek / taboret'),
('Los Muebles','Meble','la butaca','fotel / miejsce na widowni'),
('Los Muebles','Meble','el perchero','wieszak (stojący)'),
('Los Muebles','Meble','la percha','wieszak (do szafy)'),
('Los Muebles','Meble','el zapatero','szafka na buty'),
('Los Muebles','Meble','el aparador','kredens'),
('Los Muebles','Meble','la vitrina','witryna (mebel)'),
('Los Muebles','Meble','el tocador','toaletka'),
('Los Muebles','Meble','el espejo','lustro'),
('Los Muebles','Meble','la lámpara','lampa'),
('Los Muebles','Meble','la cuna','łóżeczko dziecięce'),
('Los Muebles','Meble','la litera','łóżko piętrowe'),
('Los Muebles','Meble','el colchón','materac'),
('Los Muebles','Meble','el cojín','poduszka (dekoracyjna)'),
('Los Muebles','Meble','la alfombra','dywan'),
('Los Muebles','Meble','la cortina','zasłona'),
('Los Muebles','Meble','el cuadro','obraz'),
('Los Muebles','Meble','el póster','plakat'),
('Los Muebles','Meble','la mecedora','fotel bujany'),
('Los Muebles','Meble','la hamaca','hamak'),
('Los Muebles','Meble','el cabecero','wezgłowie'),
('Los Muebles','Meble','el banco','ławka'),
('Los Muebles','Meble','la tapicería','tapicerka'),
('Los Muebles','Meble','de madera','z drewna'),
('Los Muebles','Meble','de plástico','z plastiku'),
('Los Muebles','Meble','de metal','z metalu'),
('Los Muebles','Meble','de cristal','ze szkła'),
('Los Muebles','Meble','antiguo','zabytkowy / stary'),
('Los Muebles','Meble','moderno','nowoczesny'),
('Los Muebles','Meble','montar','składać (meble)'),
('Los Muebles','Meble','desmontar','rozkładać (meble)'),
('Los Muebles','Meble','el diseño','design'),
('Los Muebles','Meble','espacioso','przestronny'),
('Los Muebles','Meble','cómodo','wygodny'),
('Los Muebles','Meble','incómodo','niewygodny'),
('Los Muebles','Meble','la decoración','dekoracja'),
('Los Electrodomésticos','Sprzęt AGD','el electrodoméstico','sprzęt AGD'),
('Los Electrodomésticos','Sprzęt AGD','la nevera / el frigorífico','lodówka'),
('Los Electrodomésticos','Sprzęt AGD','el congelador','zamrażarka'),
('Los Electrodomésticos','Sprzęt AGD','el horno','piekarnik'),
('Los Electrodomésticos','Sprzęt AGD','el microondas','mikrofalówka'),
('Los Electrodomésticos','Sprzęt AGD','la cocina (eléctrica/de gas)','kuchenka (elektryczna/gazowa)'),
('Los Electrodomésticos','Sprzęt AGD','la campana extractora','okap kuchenny'),
('Los Electrodomésticos','Sprzęt AGD','el lavavajillas / el lavaplatos','zmywarka'),
('Los Electrodomésticos','Sprzęt AGD','la lavadora','pralka'),
('Los Electrodomésticos','Sprzęt AGD','la secadora','suszarka do ubrań'),
('Los Electrodomésticos','Sprzęt AGD','la plancha','żelazko'),
('Los Electrodomésticos','Sprzęt AGD','la aspiradora','odkurzacz'),
('Los Electrodomésticos','Sprzęt AGD','el televisor / la tele','telewizor'),
('Los Electrodomésticos','Sprzęt AGD','la radio','radio'),
('Los Electrodomésticos','Sprzęt AGD','el ventilador','wentylator'),
('Los Electrodomésticos','Sprzęt AGD','el aire acondicionado','klimatyzacja'),
('Los Electrodomésticos','Sprzęt AGD','la estufa / el calentador','piecyk / grzejnik'),
('Los Electrodomésticos','Sprzęt AGD','el radiador','kaloryfer'),
('Los Electrodomésticos','Sprzęt AGD','el secador de pelo','suszarka do włosów'),
('Los Electrodomésticos','Sprzęt AGD','la tostadora','toster'),
('Los Electrodomésticos','Sprzęt AGD','la batidora','mikser / blender'),
('Los Electrodomésticos','Sprzęt AGD','la cafetera','ekspres do kawy'),
('Los Electrodomésticos','Sprzęt AGD','el hervidor (de agua)','czajnik (elektryczny)'),
('Los Electrodomésticos','Sprzęt AGD','el exprimidor','wyciskarka'),
('Los Electrodomésticos','Sprzęt AGD','la licuadora','sokowirówka'),
('Los Electrodomésticos','Sprzęt AGD','la freidora','frytkownica'),
('Los Electrodomésticos','Sprzęt AGD','la báscula / el peso','waga'),
('Los Electrodomésticos','Sprzęt AGD','la maquinilla de afeitar','maszynka do golenia (elektryczna)'),
('Los Electrodomésticos','Sprzęt AGD','la máquina de coser','maszyna do szycia'),
('Los Electrodomésticos','Sprzęt AGD','el robot de cocina','robot kuchenny'),
('Los Electrodomésticos','Sprzęt AGD','el enchufe','wtyczka / gniazdko'),
('Los Electrodomésticos','Sprzęt AGD','el cable','kabel'),
('Los Electrodomésticos','Sprzęt AGD','el botón','przycisk'),
('Los Electrodomésticos','Sprzęt AGD','el interruptor','włącznik'),
('Los Electrodomésticos','Sprzęt AGD','la pantalla','ekran'),
('Los Electrodomésticos','Sprzęt AGD','el mando a distancia','pilot (np. do TV)'),
('Los Electrodomésticos','Sprzęt AGD','la batería','bateria'),
('Los Electrodomésticos','Sprzęt AGD','enchufar','podłączać do prądu'),
('Los Electrodomésticos','Sprzęt AGD','desenchufar','odłączać od prądu'),
('Los Electrodomésticos','Sprzęt AGD','encender','włączać'),
('Los Electrodomésticos','Sprzęt AGD','apagar','wyłączać'),
('Los Electrodomésticos','Sprzęt AGD','funcionar','działać'),
('Los Electrodomésticos','Sprzęt AGD','estar estropeado','być zepsutym'),
('Los Electrodomésticos','Sprzęt AGD','estar roto','być rozbitym / zepsutym'),
('Los Electrodomésticos','Sprzęt AGD','reparar / arreglar','naprawiać'),
('Los Electrodomésticos','Sprzęt AGD','el técnico','technik / fachowiec'),
('Los Electrodomésticos','Sprzęt AGD','el repuesto','część zamienna'),
('Los Electrodomésticos','Sprzęt AGD','consumir','zużywać (energię)'),
('Los Electrodomésticos','Sprzęt AGD','el consumo','zużycie'),
('Los Electrodomésticos','Sprzęt AGD','inteligente','inteligentny (smart)'),
('Herramientas','Narzędzia','la herramienta','narzędzie'),
('Herramientas','Narzędzia','la caja de herramientas','skrzynka z narzędziami'),
('Herramientas','Narzędzia','el martillo','młotek'),
('Herramientas','Narzędzia','el clavo','gwóźdź'),
('Herramientas','Narzędzia','el tornillo','śruba / wkręt'),
('Herramientas','Narzędzia','el destornillador','śrubokręt'),
('Herramientas','Narzędzia','la tuerca','nakrętka'),
('Herramientas','Narzędzia','la llave inglesa','klucz francuski / nastawny'),
('Herramientas','Narzędzia','la llave Allen','klucz imbusowy'),
('Herramientas','Narzędzia','los alicates / el alicate','kombinerki / obcęgi'),
('Herramientas','Narzędzia','la sierra','piła (narzędzie)'),
('Herramientas','Narzędzia','el serrucho','piła ręczna'),
('Herramientas','Narzędzia','el taladro','wiertarka'),
('Herramientas','Narzędzia','la broca','wiertło'),
('Herramientas','Narzędzia','la cinta métrica','miara zwijana'),
('Herramientas','Narzędzia','la regla','linijka'),
('Herramientas','Narzędzia','el nivel','poziomica'),
('Herramientas','Narzędzia','el cúter','nóż do tapet / introligatorski'),
('Herramientas','Narzędzia','las tijeras','nożyczki'),
('Herramientas','Narzędzia','el pegamento','klej'),
('Herramientas','Narzędzia','la cinta adhesiva','taśma klejąca'),
('Herramientas','Narzędzia','la cinta aislante','taśma izolacyjna'),
('Herramientas','Narzędzia','la cuerda','lina / sznurek'),
('Herramientas','Narzędzia','el alambre','drut'),
('Herramientas','Narzędzia','la pala','łopata / szufla'),
('Herramientas','Narzędzia','el pico','kilof'),
('Herramientas','Narzędzia','el hacha','siekiera'),
('Herramientas','Narzędzia','la azada','motyka'),
('Herramientas','Narzędzia','el rastrillo','grabie'),
('Herramientas','Narzędzia','la carretilla','taczka'),
('Herramientas','Narzędzia','el pincel','pędzel'),
('Herramientas','Narzędzia','la brocha','pędzel malarski (szeroki)'),
('Herramientas','Narzędzia','el rodillo','wałek malarski'),
('Herramientas','Narzędzia','la pintura','farba'),
('Herramientas','Narzędzia','el papel de lija','papier ścierny'),
('Herramientas','Narzędzia','la espátula','szpachelka'),
('Herramientas','Narzędzia','la linterna','latarka'),
('Herramientas','Narzędzia','la lima','pilnik'),
('Herramientas','Narzędzia','el cincel','dłuto'),
('Herramientas','Narzędzia','el soldador','lutownica / spawarka'),
('Herramientas','Narzędzia','el casco','kask'),
('Herramientas','Narzędzia','los guantes de trabajo','rękawice robocze'),
('Herramientas','Narzędzia','clavar','wbijać (gwoździe)'),
('Herramientas','Narzędzia','atornillar','wkręcać (śrubę)'),
('Herramientas','Narzędzia','cortar','ciąć'),
('Herramientas','Narzędzia','pegar','kleić'),
('Herramientas','Narzędzia','medir','mierzyć'),
('Herramientas','Narzędzia','pintar','malować'),
('Herramientas','Narzędzia','lijar','szlifować'),
('Herramientas','Narzędzia','construir','budować'),
('El Coche','Samochód','el coche / el auto','samochód'),
('El Coche','Samochód','el volante','kierownica'),
('El Coche','Samochód','el motor','silnik'),
('El Coche','Samochód','la rueda','koło'),
('El Coche','Samochód','el neumático / la llanta','opona'),
('El Coche','Samochód','el freno','hamulec'),
('El Coche','Samochód','el acelerador','pedał gazu'),
('El Coche','Samochód','el embrague','sprzęgło'),
('El Coche','Samochód','la marcha','bieg (w samochodzie)'),
('El Coche','Samochód','el cinturón de seguridad','pas bezpieczeństwa'),
('El Coche','Samochód','el asiento','siedzenie / fotel'),
('El Coche','Samochód','el maletero','bagażnik'),
('El Coche','Samochód','el capó','maska samochodu'),
('El Coche','Samochód','el parabrisas','szyba przednia'),
('El Coche','Samochód','el limpiaparabrisas','wycieraczka (samochodowa)'),
('El Coche','Samochód','el espejo retrovisor','lusterko wsteczne'),
('El Coche','Samochód','el faro','reflektor'),
('El Coche','Samochód','la luz intermitente','kierunkowskaz'),
('El Coche','Samochód','la matrícula / la placa','tablica rejestracyjna'),
('El Coche','Samochód','la puerta','drzwi'),
('El Coche','Samochód','la ventanilla','szyba (w drzwiach)'),
('El Coche','Samochód','el claxon / la bocina','klakson'),
('El Coche','Samochód','el tubo de escape','rura wydechowa'),
('El Coche','Samochód','el depósito','bak'),
('El Coche','Samochód','la gasolina','benzyna'),
('El Coche','Samochód','el diésel / el gasoil','olej napędowy / diesel'),
('El Coche','Samochód','eléctrico','elektryczny (samochód)'),
('El Coche','Samochód','la gasolinera','stacja benzynowa'),
('El Coche','Samochód','el mecánico','mechanik'),
('El Coche','Samochód','el taller','warsztat'),
('El Coche','Samochód','la avería','awaria'),
('El Coche','Samochód','el accidente','wypadek'),
('El Coche','Samochód','conducir / manejar','prowadzić (samochód)'),
('El Coche','Samochód','frenar','hamować'),
('El Coche','Samochód','acelerar','przyspieszać'),
('El Coche','Samochód','aparcar / estacionar','parkować'),
('El Coche','Samochód','arrancar','odpalać / ruszać'),
('El Coche','Samochód','la velocidad','prędkość'),
('El Coche','Samochód','el límite de velocidad','ograniczenie prędkości'),
('El Coche','Samochód','la carretera','szosa / droga'),
('El Coche','Samochód','la autopista','autostrada'),
('El Coche','Samochód','el peaje','bramka autostradowa / myto'),
('El Coche','Samochód','el conductor','kierowca'),
('El Coche','Samochód','el pasajero','pasażer'),
('El Coche','Samochód','el carnet de conducir','prawo jazdy'),
('El Coche','Samochód','el seguro','ubezpieczenie'),
('El Coche','Samochód','la multa','mandat'),
('El Coche','Samochód','el tráfico','ruch drogowy'),
('El Coche','Samochód','el atasco / el embotellamiento','korek drogowy'),
('El Coche','Samochód','adelantar','wyprzedzać'),
('La Informática','Informatyka','la informática','informatyka'),
('La Informática','Informatyka','el ordenador','komputer'),
('La Informática','Informatyka','el portátil','laptop'),
('La Informática','Informatyka','el ratón','myszka'),
('La Informática','Informatyka','el teclado','klawiatura'),
('La Informática','Informatyka','la pantalla','ekran'),
('La Informática','Informatyka','el monitor','monitor'),
('La Informática','Informatyka','el hardware','sprzęt komputerowy'),
('La Informática','Informatyka','el software','oprogramowanie'),
('La Informática','Informatyka','el sistema operativo','system operacyjny'),
('La Informática','Informatyka','el archivo','plik'),
('La Informática','Informatyka','la carpeta','folder'),
('La Informática','Informatyka','el documento','dokument'),
('La Informática','Informatyka','el servidor','serwer'),
('La Informática','Informatyka','la nube','chmura (internetowa)'),
('La Informática','Informatyka','el disco duro','dysk twardy'),
('La Informática','Informatyka','la memoria USB / el pendrive','pendrive'),
('La Informática','Informatyka','el procesador','procesor'),
('La Informática','Informatyka','la placa base','płyta główna'),
('La Informática','Informatyka','el virus','wirus'),
('La Informática','Informatyka','el antivirus','antywirus'),
('La Informática','Informatyka','el código','kod'),
('La Informática','Informatyka','el programador','programista'),
('La Informática','Informatyka','programar','programować'),
('La Informática','Informatyka','la base de datos','baza danych'),
('La Informática','Informatyka','la red','sieć'),
('La Informática','Informatyka','el wifi','wi-fi'),
('La Informática','Informatyka','la conexión','połączenie'),
('La Informática','Informatyka','guardar','zapisywać'),
('La Informática','Informatyka','borrar','usuwać'),
('La Informática','Informatyka','copiar','kopiować'),
('La Informática','Informatyka','pegar','wklejać'),
('La Informática','Informatyka','cortar','wycinać'),
('La Informática','Informatyka','imprimir','drukować'),
('La Informática','Informatyka','hacer clic','klikać'),
('La Informática','Informatyka','arrastrar','przeciągać'),
('La Informática','Informatyka','reiniciar','restartować'),
('La Informática','Informatyka','encender','włączać'),
('La Informática','Informatyka','apagar','wyłączać'),
('La Informática','Informatyka','actualizar','aktualizować'),
('La Informática','Informatyka','la actualización','aktualizacja'),
('La Informática','Informatyka','el enlace / el link','link / odnośnik'),
('La Informática','Informatyka','el navegador','przeglądarka internetowa'),
('La Informática','Informatyka','el buscador','wyszukiwarka'),
('La Informática','Informatyka','el correo electrónico','e-mail'),
('La Informática','Informatyka','la arroba','małpa (@)'),
('La Informática','Informatyka','el punto','kropka (w adresie web)'),
('La Informática','Informatyka','descargar','pobierać'),
('La Informática','Informatyka','subir','wysyłać / wgrywać'),
('La Informática','Informatyka','la contraseña','hasło'),
('Redes Sociales','Media społecznościowe','la red social','sieć społecznościowa'),
('Redes Sociales','Media społecznościowe','el perfil','profil'),
('Redes Sociales','Media społecznościowe','la cuenta','konto'),
('Redes Sociales','Media społecznościowe','el usuario','użytkownik'),
('Redes Sociales','Media społecznościowe','la contraseña','hasło'),
('Redes Sociales','Media społecznościowe','iniciar sesión','zalogować się'),
('Redes Sociales','Media społecznościowe','cerrar sesión','wylogować się'),
('Redes Sociales','Media społecznościowe','la publicación','post / publikacja'),
('Redes Sociales','Media społecznościowe','publicar','publikować'),
('Redes Sociales','Media społecznościowe','el seguidor','obserwujący (follower)'),
('Redes Sociales','Media społecznościowe','seguir','obserwować (kogoś)'),
('Redes Sociales','Media społecznościowe','el me gusta','lajk / lubię to'),
('Redes Sociales','Media społecznościowe','dar me gusta','dać lajka'),
('Redes Sociales','Media społecznościowe','el comentario','komentarz'),
('Redes Sociales','Media społecznościowe','comentar','komentować'),
('Redes Sociales','Media społecznościowe','compartir','udostępniać'),
('Redes Sociales','Media społecznościowe','el mensaje','wiadomość'),
('Redes Sociales','Media społecznościowe','enviar','wysyłać'),
('Redes Sociales','Media społecznościowe','recibir','otrzymywać'),
('Redes Sociales','Media społecznościowe','el chat','czat'),
('Redes Sociales','Media społecznościowe','chatear','czatować'),
('Redes Sociales','Media społecznościowe','la notificación','powiadomienie'),
('Redes Sociales','Media społecznościowe','la foto','zdjęcie'),
('Redes Sociales','Media społecznościowe','el vídeo','wideo'),
('Redes Sociales','Media społecznościowe','el estado','status'),
('Redes Sociales','Media społecznościowe','la historia','story / relacja'),
('Redes Sociales','Media społecznościowe','la etiqueta','tag / znacznik'),
('Redes Sociales','Media społecznościowe','etiquetar','oznaczać (kogoś)'),
('Redes Sociales','Media społecznościowe','el hashtag','hasztag'),
('Redes Sociales','Media społecznościowe','el enlace','link'),
('Redes Sociales','Media społecznościowe','en línea','online / dostępny'),
('Redes Sociales','Media społecznościowe','desconectado','offline / niedostępny'),
('Redes Sociales','Media społecznościowe','bloquear','blokować'),
('Redes Sociales','Media społecznościowe','desbloquear','odblokować'),
('Redes Sociales','Media społecznościowe','el grupo','grupa'),
('Redes Sociales','Media społecznościowe','la página','strona'),
('Redes Sociales','Media społecznościowe','el muro','tablica (na profilu)'),
('Redes Sociales','Media społecznościowe','el influencer','influencer'),
('Redes Sociales','Media społecznościowe','viral','wirusowy / viralowy'),
('Redes Sociales','Media społecznościowe','hacerse viral','stać się viralem'),
('Redes Sociales','Media społecznościowe','el algoritmo','algorytm'),
('Redes Sociales','Media społecznościowe','la privacidad','prywatność'),
('Redes Sociales','Media społecznościowe','público','publiczny'),
('Redes Sociales','Media społecznościowe','privado','prywatny'),
('Redes Sociales','Media społecznościowe','el avatar','awatar / zdjęcie profilowe'),
('Redes Sociales','Media społecznościowe','el filtro','filtr (do zdjęć)'),
('Redes Sociales','Media społecznościowe','la solicitud de amistad','zaproszenie do znajomych'),
('Redes Sociales','Media społecznościowe','agregar','dodawać (znajomego)'),
('Redes Sociales','Media społecznościowe','eliminar','usuwać'),
('Redes Sociales','Media społecznościowe','silenciar','wyciszać'),
('La Religión','Religia','la religión','religia'),
('La Religión','Religia','Dios','Bóg'),
('La Religión','Religia','Jesús','Jezus'),
('La Religión','Religia','la cruz','krzyż'),
('La Religión','Religia','la iglesia','kościół'),
('La Religión','Religia','el templo','świątynia'),
('La Religión','Religia','la catedral','katedra'),
('La Religión','Religia','la mezquita','meczet'),
('La Religión','Religia','la sinagoga','synagoga'),
('La Religión','Religia','el sacerdote / el cura','ksiądz'),
('La Religión','Religia','el obispo','biskup'),
('La Religión','Religia','el papa','papież'),
('La Religión','Religia','el monje','mnich'),
('La Religión','Religia','la monja','zakonnica'),
('La Religión','Religia','el fiel','wierny'),
('La Religión','Religia','la fe','wiara'),
('La Religión','Religia','creer','wierzyć'),
('La Religión','Religia','la oración','modlitwa'),
('La Religión','Religia','rezar','modlić się'),
('La Religión','Religia','el pecado','grzech'),
('La Religión','Religia','pecar','grzeszyć'),
('La Religión','Religia','el perdón','przebaczenie'),
('La Religión','Religia','perdonar','przebaczać'),
('La Religión','Religia','el cielo','niebo (raj)'),
('La Religión','Religia','el infierno','piekło'),
('La Religión','Religia','el diablo / el demonio','diabeł / demon'),
('La Religión','Religia','el ángel','anioł'),
('La Religión','Religia','el alma','dusza'),
('La Religión','Religia','el espíritu','duch'),
('La Religión','Religia','el Espíritu Santo','Duch Święty'),
('La Religión','Religia','sagrado','święty (rzecz)'),
('La Religión','Religia','el santo','święty (osoba)'),
('La Religión','Religia','la Biblia','Biblia'),
('La Religión','Religia','el Corán','Koran'),
('La Religión','Religia','la misa','msza'),
('La Religión','Religia','el bautismo','chrzest'),
('La Religión','Religia','bautizar','chrzcić'),
('La Religión','Religia','la comunión','komunia'),
('La Religión','Religia','el matrimonio','małżeństwo / ślub kościelny'),
('La Religión','Religia','el funeral','pogrzeb'),
('La Religión','Religia','el cementerio','cmentarz'),
('La Religión','Religia','el milagro','cud'),
('La Religión','Religia','la peregrinación','pielgrzymka'),
('La Religión','Religia','el peregrino','pielgrzym'),
('La Religión','Religia','la procesión','procesja'),
('La Religión','Religia','el altar','ołtarz'),
('La Religión','Religia','el incienso','kadzidło'),
('La Religión','Religia','el creador','stwórca'),
('La Religión','Religia','ateo','ateista'),
('La Religión','Religia','creyente','wierzący'),
('La Ciencia','Nauka','la ciencia','nauka (dziedzina)'),
('La Ciencia','Nauka','el científico / la científica','naukowiec'),
('La Ciencia','Nauka','el investigador','badacz'),
('La Ciencia','Nauka','la investigación','badanie / śledztwo'),
('La Ciencia','Nauka','el experimento','eksperyment'),
('La Ciencia','Nauka','experimentar','eksperymentować'),
('La Ciencia','Nauka','el laboratorio','laboratorium'),
('La Ciencia','Nauka','el descubrimiento','odkrycie'),
('La Ciencia','Nauka','descubrir','odkrywać'),
('La Ciencia','Nauka','la teoría','teoria'),
('La Ciencia','Nauka','la hipótesis','hipoteza'),
('La Ciencia','Nauka','el análisis','analiza'),
('La Ciencia','Nauka','analizar','analizować'),
('La Ciencia','Nauka','el resultado','wynik'),
('La Ciencia','Nauka','la prueba','dowód / test'),
('La Ciencia','Nauka','el método','metoda'),
('La Ciencia','Nauka','observar','obserwować'),
('La Ciencia','Nauka','medir','mierzyć'),
('La Ciencia','Nauka','la fórmula','wzór / formuła'),
('La Ciencia','Nauka','el microscopio','mikroskop'),
('La Ciencia','Nauka','el tubo de ensayo','probówka'),
('La Ciencia','Nauka','la química','chemia'),
('La Ciencia','Nauka','la física','fizyka'),
('La Ciencia','Nauka','la biología','biologia'),
('La Ciencia','Nauka','la astronomía','astronomia'),
('La Ciencia','Nauka','las matemáticas','matematyka'),
('La Ciencia','Nauka','el átomo','atom'),
('La Ciencia','Nauka','la molécula','cząsteczka'),
('La Ciencia','Nauka','la célula','komórka'),
('La Ciencia','Nauka','el ADN','DNA'),
('La Ciencia','Nauka','la genética','genetyka'),
('La Ciencia','Nauka','el gen','gen'),
('La Ciencia','Nauka','el elemento','pierwiastek'),
('La Ciencia','Nauka','la gravedad','grawitacja'),
('La Ciencia','Nauka','la energía','energia'),
('La Ciencia','Nauka','la masa','masa'),
('La Ciencia','Nauka','la materia','materia'),
('La Ciencia','Nauka','el invento','wynalazek'),
('La Ciencia','Nauka','inventar','wynaleźć'),
('La Ciencia','Nauka','el inventor','wynalazca'),
('La Ciencia','Nauka','la patente','patent'),
('La Ciencia','Nauka','el congreso','kongres / konferencja'),
('La Ciencia','Nauka','la publicación','publikacja'),
('La Ciencia','Nauka','el premio Nobel','nagroda Nobla'),
('La Ciencia','Nauka','demostrar','udowadniać'),
('La Ciencia','Nauka','el fenómeno','zjawisko'),
('La Ciencia','Nauka','exacto','dokładny'),
('La Ciencia','Nauka','empírico','empiryczny'),
('La Ciencia','Nauka','la evolución','ewolucja'),
('La Ciencia','Nauka','el estudio','badanie / studium'),
('El Espacio','Kosmos','el espacio','kosmos / przestrzeń'),
('El Espacio','Kosmos','el universo','wszechświat'),
('El Espacio','Kosmos','la galaxia','galaktyka'),
('El Espacio','Kosmos','el sistema solar','układ słoneczny'),
('El Espacio','Kosmos','el planeta','planeta'),
('El Espacio','Kosmos','la estrella','gwiazda'),
('El Espacio','Kosmos','el sol','słońce'),
('El Espacio','Kosmos','la luna','księżyc'),
('El Espacio','Kosmos','la tierra','ziemia'),
('El Espacio','Kosmos','el asteroide','asteroida'),
('El Espacio','Kosmos','el cometa','kometa'),
('El Espacio','Kosmos','el meteorito','meteoryt'),
('El Espacio','Kosmos','la órbita','orbita'),
('El Espacio','Kosmos','orbitar','krążyć (po orbicie)'),
('El Espacio','Kosmos','la gravedad','grawitacja'),
('El Espacio','Kosmos','el agujero negro','czarna dziura'),
('El Espacio','Kosmos','el eclipse','zaćmienie'),
('El Espacio','Kosmos','el telescopio','teleskop'),
('El Espacio','Kosmos','el observatorio','obserwatorium'),
('El Espacio','Kosmos','el astronauta','astronauta'),
('El Espacio','Kosmos','el cohete','rakieta'),
('El Espacio','Kosmos','la nave espacial','statek kosmiczny'),
('El Espacio','Kosmos','el transbordador','wahadłowiec'),
('El Espacio','Kosmos','el satélite','satelita'),
('El Espacio','Kosmos','la estación espacial','stacja kosmiczna'),
('El Espacio','Kosmos','el lanzamiento','start / wystrzelenie'),
('El Espacio','Kosmos','lanzar','wystrzeliwać (rakietę)'),
('El Espacio','Kosmos','aterrizar','lądować (na ziemi/planecie)'),
('El Espacio','Kosmos','alunizar','lądować na księżycu'),
('El Espacio','Kosmos','la misión','misja'),
('El Espacio','Kosmos','explorar','odkrywać / badać'),
('El Espacio','Kosmos','la exploración','eksploracja'),
('El Espacio','Kosmos','extraterrestre (adj.)','pozaziemski'),
('El Espacio','Kosmos','el extraterrestre','kosmita'),
('El Espacio','Kosmos','el alienígena','obcy'),
('El Espacio','Kosmos','el ovni','UFO'),
('El Espacio','Kosmos','la Vía Láctea','Droga Mleczna'),
('El Espacio','Kosmos','el rayo','promień'),
('El Espacio','Kosmos','luminoso','świetlny'),
('El Espacio','Kosmos','el año luz','rok świetlny'),
('El Espacio','Kosmos','el cielo','niebo'),
('El Espacio','Kosmos','la constelación','konstelacja'),
('El Espacio','Kosmos','el cosmos','kosmos'),
('El Espacio','Kosmos','cósmico','kosmiczny'),
('El Espacio','Kosmos','el vacío','próżnia'),
('El Espacio','Kosmos','flotar','unosić się / pływać'),
('El Espacio','Kosmos','la velocidad de la luz','prędkość światła'),
('El Espacio','Kosmos','el cráter','krater'),
('El Espacio','Kosmos','la superficie','powierzchnia'),
('El Espacio','Kosmos','descubrir','odkryć (planetę)'),
('Materiales','Materiały','el material','materiał'),
('Materiales','Materiały','la madera','drewno'),
('Materiales','Materiały','el plástico','plastik'),
('Materiales','Materiały','el metal','metal'),
('Materiales','Materiały','el cristal / el vidrio','szkło'),
('Materiales','Materiały','el acero','stal'),
('Materiales','Materiały','el hierro','żelazo'),
('Materiales','Materiały','el aluminio','aluminium'),
('Materiales','Materiały','el cobre','miedź'),
('Materiales','Materiały','el oro','złoto'),
('Materiales','Materiały','la plata','srebro'),
('Materiales','Materiały','el bronce','brąz'),
('Materiales','Materiały','la piedra','kamień'),
('Materiales','Materiały','el mármol','marmur'),
('Materiales','Materiały','el granito','granit'),
('Materiales','Materiały','el ladrillo','cegła'),
('Materiales','Materiały','el cemento','cement'),
('Materiales','Materiały','el hormigón','beton'),
('Materiales','Materiały','la arcilla','glina'),
('Materiales','Materiały','la arena','piasek'),
('Materiales','Materiały','el papel','papier'),
('Materiales','Materiały','el cartón','karton'),
('Materiales','Materiały','la tela','tkanina / materiał'),
('Materiales','Materiały','el algodón','bawełna'),
('Materiales','Materiały','la lana','wełna'),
('Materiales','Materiały','la seda','jedwab'),
('Materiales','Materiały','el lino','lniany materiał / len'),
('Materiales','Materiały','el poliéster','poliester'),
('Materiales','Materiały','el nailon','nylon'),
('Materiales','Materiały','el cuero / la piel','skóra (materiał)'),
('Materiales','Materiały','el ante','zamsz'),
('Materiales','Materiały','la goma','guma'),
('Materiales','Materiały','el caucho','kauczuk'),
('Materiales','Materiały','el corcho','korek'),
('Materiales','Materiały','la cerámica','ceramika'),
('Materiales','Materiały','la porcelana','porcelana'),
('Materiales','Materiały','el diamante','diament'),
('Materiales','Materiały','el carbón','węgiel'),
('Materiales','Materiały','el petróleo','ropa naftowa'),
('Materiales','Materiały','el gas','gaz'),
('Materiales','Materiały','sólido','stały (stan skupienia)'),
('Materiales','Materiały','líquido','ciekły'),
('Materiales','Materiały','gaseoso','gazowy'),
('Materiales','Materiały','blando','miękki'),
('Materiales','Materiały','duro','twardy'),
('Materiales','Materiały','resistente','wytrzymały'),
('Materiales','Materiały','frágil','kruchy / delikatny'),
('Materiales','Materiały','pesado','ciężki'),
('Materiales','Materiały','ligero','lekki'),
('Materiales','Materiały','elástico','elastyczny'),
('Formas Geométricas','Kształty geometryczne','la forma','kształt'),
('Formas Geométricas','Kształty geometryczne','el círculo','koło'),
('Formas Geométricas','Kształty geometryczne','el cuadrado','kwadrat'),
('Formas Geométricas','Kształty geometryczne','el triángulo','trójkąt'),
('Formas Geométricas','Kształty geometryczne','el rectángulo','prostokąt'),
('Formas Geométricas','Kształty geometryczne','el óvalo','owal'),
('Formas Geométricas','Kształty geometryczne','el rombo','romb'),
('Formas Geométricas','Kształty geometryczne','el pentágono','pięciokąt'),
('Formas Geométricas','Kształty geometryczne','el hexágono','sześciokąt'),
('Formas Geométricas','Kształty geometryczne','el octógono','ośmiokąt'),
('Formas Geométricas','Kształty geometryczne','la estrella','gwiazda (kształt)'),
('Formas Geométricas','Kształty geometryczne','la cruz','krzyż (kształt)'),
('Formas Geométricas','Kształty geometryczne','la esfera','kula'),
('Formas Geométricas','Kształty geometryczne','el cubo','sześcian'),
('Formas Geométricas','Kształty geometryczne','el cilindro','cylinder / walec'),
('Formas Geométricas','Kształty geometryczne','el cono','stożek'),
('Formas Geométricas','Kształty geometryczne','la pirámide','piramida'),
('Formas Geométricas','Kształty geometryczne','el prisma','graniastosłup'),
('Formas Geométricas','Kształty geometryczne','la línea','linia'),
('Formas Geométricas','Kształty geometryczne','recto','prosty (o linii)'),
('Formas Geométricas','Kształty geometryczne','curvo','krzywy'),
('Formas Geométricas','Kształty geometryczne','el punto','punkt'),
('Formas Geométricas','Kształty geometryczne','el ángulo','kąt'),
('Formas Geométricas','Kształty geometryczne','redondo','okrągły'),
('Formas Geométricas','Kształty geometryczne','cuadrado (adj.)','kwadratowy'),
('Formas Geométricas','Kształty geometryczne','triangular','trójkątny'),
('Formas Geométricas','Kształty geometryczne','rectangular','prostokątny'),
('Formas Geométricas','Kształty geometryczne','ovalado','owalny'),
('Formas Geométricas','Kształty geometryczne','plano','płaski'),
('Formas Geométricas','Kształty geometryczne','tridimensional','trójwymiarowy'),
('Formas Geométricas','Kształty geometryczne','la dimensión','wymiar'),
('Formas Geométricas','Kształty geometryczne','el centro','środek'),
('Formas Geométricas','Kształty geometryczne','el lado','bok'),
('Formas Geométricas','Kształty geometryczne','el borde','krawędź / brzeg'),
('Formas Geométricas','Kształty geometryczne','la superficie','powierzchnia'),
('Formas Geométricas','Kształty geometryczne','el volumen','objętość'),
('Formas Geométricas','Kształty geometryczne','la anchura','szerokość'),
('Formas Geométricas','Kształty geometryczne','ancho','szeroki'),
('Formas Geométricas','Kształty geometryczne','la longitud','długość'),
('Formas Geométricas','Kształty geometryczne','largo','długi'),
('Formas Geométricas','Kształty geometryczne','la altura','wysokość'),
('Formas Geométricas','Kształty geometryczne','alto','wysoki'),
('Formas Geométricas','Kształty geometryczne','profundo','głęboki'),
('Formas Geométricas','Kształty geometryczne','la profundidad','głębokość'),
('Formas Geométricas','Kształty geometryczne','simétrico','symetryczny'),
('Formas Geométricas','Kształty geometryczne','asimétrico','asymetryczny'),
('Formas Geométricas','Kształty geometryczne','paralelo','równoległy'),
('Formas Geométricas','Kształty geometryczne','perpendicular','prostopadły'),
('Formas Geométricas','Kształty geometryczne','el diámetro','średnica'),
('Formas Geométricas','Kształty geometryczne','el radio','promień'),
('El Ocio','Czas wolny','el ocio','czas wolny'),
('El Ocio','Czas wolny','el tiempo libre','czas wolny'),
('El Ocio','Czas wolny','el hobby / la afición','hobby / pasja'),
('El Ocio','Czas wolny','descansar','odpoczywać'),
('El Ocio','Czas wolny','el descanso','odpoczynek'),
('El Ocio','Czas wolny','relajarse','relaksować się'),
('El Ocio','Czas wolny','divertirse','bawić się / spędzać dobrze tiempo'),
('El Ocio','Czas wolny','el entretenimiento','rozrywka'),
('El Ocio','Czas wolny','el paseo','spacer'),
('El Ocio','Czas wolny','pasear','spacerować'),
('El Ocio','Czas wolny','el parque','park'),
('El Ocio','Czas wolny','el cine','kino'),
('El Ocio','Czas wolny','el teatro','teatr'),
('El Ocio','Czas wolny','el museo','muzeum'),
('El Ocio','Czas wolny','el concierto','koncert'),
('El Ocio','Czas wolny','la exposición','wystawa'),
('El Ocio','Czas wolny','el festival','festiwal'),
('El Ocio','Czas wolny','la discoteca','dyskoteka'),
('El Ocio','Czas wolny','bailar','tańczyć'),
('El Ocio','Czas wolny','el baile','taniec'),
('El Ocio','Czas wolny','cantar','śpiewać'),
('El Ocio','Czas wolny','el karaoke','karaoke'),
('El Ocio','Czas wolny','escuchar música','słuchać muzyki'),
('El Ocio','Czas wolny','leer','czytać'),
('El Ocio','Czas wolny','la lectura','czytanie / lektura'),
('El Ocio','Czas wolny','ver la televisión','oglądać telewizję'),
('El Ocio','Czas wolny','ver una película','oglądać film'),
('El Ocio','Czas wolny','ver una serie','oglądać serial'),
('El Ocio','Czas wolny','jugar','grać / bawić się'),
('El Ocio','Czas wolny','el juego','gra'),
('El Ocio','Czas wolny','navegar por internet','surfować po internecie'),
('El Ocio','Czas wolny','chatear','czatować'),
('El Ocio','Czas wolny','ir de compras','iść na zakupy'),
('El Ocio','Czas wolny','el deporte','sport'),
('El Ocio','Czas wolny','hacer deporte','uprawiać sport'),
('El Ocio','Czas wolny','ir al gimnasio','iść na siłownię'),
('El Ocio','Czas wolny','nadar','pływać'),
('El Ocio','Czas wolny','montar en bicicleta','jeździć na rowerze'),
('El Ocio','Czas wolny','el viaje','podróż'),
('El Ocio','Czas wolny','viajar','podróżować'),
('El Ocio','Czas wolny','las vacaciones','wakacje'),
('El Ocio','Czas wolny','la fotografía','fotografia (hobby)'),
('El Ocio','Czas wolny','sacar fotos','robić zdjęcia'),
('El Ocio','Czas wolny','pintar','malować'),
('El Ocio','Czas wolny','cocinar','gotować (dla przyjemności)'),
('El Ocio','Czas wolny','la jardinería','ogrodnictwo'),
('El Ocio','Czas wolny','el club','klub'),
('El Ocio','Czas wolny','la fiesta','impreza / przyjęcie'),
('El Ocio','Czas wolny','salir','wychodzić (na miasto)'),
('El Ocio','Czas wolny','quedar con amigos','spotykać się z przyjaciółmi');
