insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('La Familia','Rodzina','la madre','matka'),
('La Familia','Rodzina','el padre','ojciec'),
('La Familia','Rodzina','el hijo','syn'),
('La Familia','Rodzina','la hija','córka'),
('La Familia','Rodzina','el hermano','brat'),
('La Familia','Rodzina','la hermana','siostra'),
('La Familia','Rodzina','el abuelo','dziadek'),
('La Familia','Rodzina','la abuela','babcia'),
('La Familia','Rodzina','el nieto','wnuk'),
('La Familia','Rodzina','la nieta','wnuczka'),
('La Familia','Rodzina','el tío','wujek'),
('La Familia','Rodzina','la tía','ciocia'),
('La Familia','Rodzina','el primo','kuzyn'),
('La Familia','Rodzina','la prima','kuzynka'),
('La Familia','Rodzina','el sobrino','siostrzeniec/bratanek'),
('La Familia','Rodzina','la sobrina','siostrzenica/bratanica'),
('La Familia','Rodzina','el esposo','mąż'),
('La Familia','Rodzina','la esposa','żona'),
('La Familia','Rodzina','el marido','mąż'),
('La Familia','Rodzina','la mujer','kobieta/żona'),
('La Familia','Rodzina','el suegro','teść'),
('La Familia','Rodzina','la suegra','teściowa'),
('La Familia','Rodzina','el yerno','zięć'),
('La Familia','Rodzina','la nuera','synowa'),
('La Familia','Rodzina','el cuñado','szwagier'),
('La Familia','Rodzina','la cuñada','szwagierka'),
('La Familia','Rodzina','el padrastro','ojczym'),
('La Familia','Rodzina','la madrastra','macocha'),
('La Familia','Rodzina','el hijastro','pasierb'),
('La Familia','Rodzina','la hijastra','pasierbica'),
('La Familia','Rodzina','el hermanastro','przyrodni brat'),
('La Familia','Rodzina','la hermanastra','przyrodnia siostra'),
('La Familia','Rodzina','el padrino','ojciec chrzestny'),
('La Familia','Rodzina','la madrina','matka chrzestna'),
('La Familia','Rodzina','el ahijado','chrześniak'),
('La Familia','Rodzina','la ahijada','chrześniaczka'),
('La Familia','Rodzina','los padres','rodzice'),
('La Familia','Rodzina','los hijos','dzieci'),
('La Familia','Rodzina','los abuelos','dziadkowie'),
('La Familia','Rodzina','los suegros','teściowie'),
('La Familia','Rodzina','el pariente','krewny'),
('La Familia','Rodzina','la parienta','krewna'),
('La Familia','Rodzina','el huérfano','sierota (chłopiec)'),
('La Familia','Rodzina','la huérfana','sierota (dziewczynka)'),
('La Familia','Rodzina','los gemelos','bliźniacy'),
('La Familia','Rodzina','las gemelas','bliźniaczki'),
('La Familia','Rodzina','el primogénito','pierworodny'),
('La Familia','Rodzina','la familia política','rodzina ze strony męża/żony'),
('La Familia','Rodzina','el antepasado','przodek'),
('La Familia','Rodzina','la descendencia','potomstwo'),
('El Cuerpo Humano','Ciało ludzkie','la cabeza','głowa'),
('El Cuerpo Humano','Ciało ludzkie','el pelo','włosy'),
('El Cuerpo Humano','Ciało ludzkie','la cara','twarz'),
('El Cuerpo Humano','Ciało ludzkie','la frente','czoło'),
('El Cuerpo Humano','Ciało ludzkie','el ojo','oko'),
('El Cuerpo Humano','Ciało ludzkie','la ceja','brew'),
('El Cuerpo Humano','Ciało ludzkie','la pestaña','rzęsa'),
('El Cuerpo Humano','Ciało ludzkie','la nariz','nos'),
('El Cuerpo Humano','Ciało ludzkie','la boca','usta'),
('El Cuerpo Humano','Ciało ludzkie','el labio','warga'),
('El Cuerpo Humano','Ciało ludzkie','el diente','ząb'),
('El Cuerpo Humano','Ciało ludzkie','la lengua','język'),
('El Cuerpo Humano','Ciało ludzkie','la oreja','ucho (zewnętrzne)'),
('El Cuerpo Humano','Ciało ludzkie','el oído','ucho (wewnętrzne)'),
('El Cuerpo Humano','Ciało ludzkie','la mejilla','policzek'),
('El Cuerpo Humano','Ciało ludzkie','la barbilla','broda (część twarzy)'),
('El Cuerpo Humano','Ciało ludzkie','el cuello','szyja'),
('El Cuerpo Humano','Ciało ludzkie','la garganta','gardło'),
('El Cuerpo Humano','Ciało ludzkie','el hombro','ramię (staw)'),
('El Cuerpo Humano','Ciało ludzkie','el brazo','ręka (od ramienia do dłoni)'),
('El Cuerpo Humano','Ciało ludzkie','el codo','łokieć'),
('El Cuerpo Humano','Ciało ludzkie','la muñeca','nadgarstek'),
('El Cuerpo Humano','Ciało ludzkie','la mano','dłoń'),
('El Cuerpo Humano','Ciało ludzkie','el dedo','palec (u ręki)'),
('El Cuerpo Humano','Ciało ludzkie','la uña','paznokieć'),
('El Cuerpo Humano','Ciało ludzkie','el pecho','klatka piersiowa'),
('El Cuerpo Humano','Ciało ludzkie','el corazón','serce'),
('El Cuerpo Humano','Ciało ludzkie','el estómago','żołądek'),
('El Cuerpo Humano','Ciało ludzkie','la barriga','brzuch'),
('El Cuerpo Humano','Ciało ludzkie','el ombligo','pępek'),
('El Cuerpo Humano','Ciało ludzkie','la espalda','plecy'),
('El Cuerpo Humano','Ciało ludzkie','la columna vertebral','kręgosłup'),
('El Cuerpo Humano','Ciało ludzkie','la cintura','talia'),
('El Cuerpo Humano','Ciało ludzkie','la cadera','biodro'),
('El Cuerpo Humano','Ciało ludzkie','el trasero','pośladki'),
('El Cuerpo Humano','Ciało ludzkie','la pierna','noga'),
('El Cuerpo Humano','Ciało ludzkie','el muslo','udo'),
('El Cuerpo Humano','Ciało ludzkie','la rodilla','kolano'),
('El Cuerpo Humano','Ciało ludzkie','el tobillo','kostka'),
('El Cuerpo Humano','Ciało ludzkie','el pie','stopa'),
('El Cuerpo Humano','Ciało ludzkie','el dedo del pie','palec u nogi'),
('El Cuerpo Humano','Ciało ludzkie','el talón','pięta'),
('El Cuerpo Humano','Ciało ludzkie','la piel','skóra'),
('El Cuerpo Humano','Ciało ludzkie','el hueso','kość'),
('El Cuerpo Humano','Ciało ludzkie','el músculo','mięsień'),
('El Cuerpo Humano','Ciało ludzkie','la sangre','krew'),
('El Cuerpo Humano','Ciało ludzkie','la vena','żyła'),
('El Cuerpo Humano','Ciało ludzkie','el pulmón','płuco'),
('El Cuerpo Humano','Ciało ludzkie','el cerebro','mózg'),
('El Cuerpo Humano','Ciało ludzkie','el hígado','wątroba'),
('La Ciudad','Miasto','la ciudad','miasto'),
('La Ciudad','Miasto','el pueblo','wioska/miasteczko'),
('La Ciudad','Miasto','el centro','centrum'),
('La Ciudad','Miasto','el barrio','dzielnica'),
('La Ciudad','Miasto','las afueras','przedmieścia'),
('La Ciudad','Miasto','la calle','ulica'),
('La Ciudad','Miasto','la avenida','aleja'),
('La Ciudad','Miasto','la plaza','plac'),
('La Ciudad','Miasto','el parque','park'),
('La Ciudad','Miasto','el jardín','ogród'),
('La Ciudad','Miasto','el edificio','budynek'),
('La Ciudad','Miasto','el rascacielos','drapacz chmur'),
('La Ciudad','Miasto','la casa','dom'),
('La Ciudad','Miasto','el apartamento','apartament/mieszkanie'),
('La Ciudad','Miasto','la tienda','sklep'),
('La Ciudad','Miasto','el centro comercial','centrum handlowe'),
('La Ciudad','Miasto','el supermercado','supermarket'),
('La Ciudad','Miasto','el mercado','rynek/targ'),
('La Ciudad','Miasto','la panadería','piekarnia'),
('La Ciudad','Miasto','la carnicería','rzeźnik'),
('La Ciudad','Miasto','la farmacia','apteka'),
('La Ciudad','Miasto','el hospital','szpital'),
('La Ciudad','Miasto','la clínica','klinika'),
('La Ciudad','Miasto','la escuela','szkoła'),
('La Ciudad','Miasto','el colegio','szkoła podstawowa/średnia'),
('La Ciudad','Miasto','la universidad','uniwersytet'),
('La Ciudad','Miasto','la biblioteca','biblioteka'),
('La Ciudad','Miasto','el museo','muzeum'),
('La Ciudad','Miasto','el teatro','teatr'),
('La Ciudad','Miasto','el cine','kino'),
('La Ciudad','Miasto','el restaurante','restauracja'),
('La Ciudad','Miasto','el café','kawiarnia'),
('La Ciudad','Miasto','el bar','bar'),
('La Ciudad','Miasto','el banco','bank'),
('La Ciudad','Miasto','el cajero automático','bankomat'),
('La Ciudad','Miasto','la oficina de correos','poczta'),
('La Ciudad','Miasto','la comisaría','posterunek policji'),
('La Ciudad','Miasto','la estación de bomberos','remiza strażacka'),
('La Ciudad','Miasto','el ayuntamiento','ratusz'),
('La Ciudad','Miasto','la iglesia','kościół'),
('La Ciudad','Miasto','la catedral','katedra'),
('La Ciudad','Miasto','la estación de tren','stacja kolejowa'),
('La Ciudad','Miasto','la estación de autobuses','dworzec autobusowy'),
('La Ciudad','Miasto','el aeropuerto','lotnisko'),
('La Ciudad','Miasto','el puente','most'),
('La Ciudad','Miasto','el monumento','pomnik'),
('La Ciudad','Miasto','la fuente','fontanna'),
('La Ciudad','Miasto','el semáforo','sygnalizacja świetlna'),
('La Ciudad','Miasto','la acera','chodnik'),
('La Ciudad','Miasto','el paso de cebra','przejście dla pieszych'),
('La Casa','Dom','la casa','dom'),
('La Casa','Dom','el piso','mieszkanie/piętro'),
('La Casa','Dom','el edificio','budynek'),
('La Casa','Dom','el tejado','dach'),
('La Casa','Dom','la chimenea','komin'),
('La Casa','Dom','la pared','ściana'),
('La Casa','Dom','el suelo','podłoga'),
('La Casa','Dom','el techo','sufit'),
('La Casa','Dom','la ventana','okno'),
('La Casa','Dom','la puerta','drzwi'),
('La Casa','Dom','el balcón','balkon'),
('La Casa','Dom','la terraza','taras'),
('La Casa','Dom','el jardín','ogród'),
('La Casa','Dom','el garaje','garaż'),
('La Casa','Dom','el sótano','piwnica'),
('La Casa','Dom','el ático','strych'),
('La Casa','Dom','la escalera','schody'),
('La Casa','Dom','el ascensor','winda'),
('La Casa','Dom','el pasillo','korytarz'),
('La Casa','Dom','el recibidor','przedpokój'),
('La Casa','Dom','el salón','salon'),
('La Casa','Dom','el comedor','jadalnia'),
('La Casa','Dom','la cocina','kuchnia'),
('La Casa','Dom','el dormitorio','sypialnia'),
('La Casa','Dom','el cuarto de baño','łazienka'),
('La Casa','Dom','el aseo','toaleta'),
('La Casa','Dom','el estudio','gabinet'),
('La Casa','Dom','el cuarto de invitados','pokój gościnny'),
('La Casa','Dom','el mueble','mebel'),
('La Casa','Dom','la silla','krzesło'),
('La Casa','Dom','la mesa','stół'),
('La Casa','Dom','el sofá','kanapa'),
('La Casa','Dom','el sillón','fotel'),
('La Casa','Dom','la estantería','regał'),
('La Casa','Dom','el armario','szafa'),
('La Casa','Dom','la cama','łóżko'),
('La Casa','Dom','la mesita de noche','stolik nocny'),
('La Casa','Dom','el escritorio','biurko'),
('La Casa','Dom','la lámpara','lampa'),
('La Casa','Dom','la alfombra','dywan'),
('La Casa','Dom','el espejo','lustro'),
('La Casa','Dom','el cuadro','obraz'),
('La Casa','Dom','la cortina','zasłona'),
('La Casa','Dom','la persiana','roleta'),
('La Casa','Dom','el cojín','poduszka (dekoracyjna)'),
('La Casa','Dom','la almohada','poduszka (do spania)'),
('La Casa','Dom','la manta','koc'),
('La Casa','Dom','la sábana','prześcieradło'),
('La Casa','Dom','la calefacción','ogrzewanie'),
('La Casa','Dom','el aire acondicionado','klimatyzacja'),
('La Comida','Jedzenie','el desayuno','śniadanie'),
('La Comida','Jedzenie','el almuerzo','drugie śniadanie/lunch'),
('La Comida','Jedzenie','la comida','obiad/jedzenie'),
('La Comida','Jedzenie','la cena','kolacja'),
('La Comida','Jedzenie','el plato','danie/talerz'),
('La Comida','Jedzenie','el primer plato','pierwsze danie'),
('La Comida','Jedzenie','el segundo plato','drugie danie'),
('La Comida','Jedzenie','el postre','deser'),
('La Comida','Jedzenie','el pan','chleb'),
('La Comida','Jedzenie','el panecillo','bułka'),
('La Comida','Jedzenie','la mantequilla','masło'),
('La Comida','Jedzenie','el queso','ser'),
('La Comida','Jedzenie','el huevo','jajko'),
('La Comida','Jedzenie','la carne','mięso'),
('La Comida','Jedzenie','el pollo','kurczak'),
('La Comida','Jedzenie','el cerdo','wieprzowina'),
('La Comida','Jedzenie','la ternera','cielęcina'),
('La Comida','Jedzenie','el pescado','ryba'),
('La Comida','Jedzenie','el marisco','owoce morza'),
('La Comida','Jedzenie','la sopa','zupa'),
('La Comida','Jedzenie','la ensalada','sałatka'),
('La Comida','Jedzenie','la pasta','makaron'),
('La Comida','Jedzenie','el arroz','ryż'),
('La Comida','Jedzenie','la patata','ziemniak'),
('La Comida','Jedzenie','la verdura','warzywo'),
('La Comida','Jedzenie','el tomate','pomidor'),
('La Comida','Jedzenie','la cebolla','cebula'),
('La Comida','Jedzenie','el ajo','czosnek'),
('La Comida','Jedzenie','la fruta','owoc'),
('La Comida','Jedzenie','la manzana','jabłko'),
('La Comida','Jedzenie','el plátano','banan'),
('La Comida','Jedzenie','la naranja','pomarańcza'),
('La Comida','Jedzenie','el limón','cytryna'),
('La Comida','Jedzenie','la fresa','truskawka'),
('La Comida','Jedzenie','la uva','winogrono'),
('La Comida','Jedzenie','el azúcar','cukier'),
('La Comida','Jedzenie','la sal','sól'),
('La Comida','Jedzenie','la pimienta','pieprz'),
('La Comida','Jedzenie','el aceite','olej/oliwa'),
('La Comida','Jedzenie','el vinagre','ocet'),
('La Comida','Jedzenie','la salsa','sos'),
('La Comida','Jedzenie','el chocolate','czekolada'),
('La Comida','Jedzenie','el caramelo','cukierek'),
('La Comida','Jedzenie','el helado','lody'),
('La Comida','Jedzenie','el pastel','ciasto'),
('La Comida','Jedzenie','la galleta','ciastko'),
('La Comida','Jedzenie','el bocadillo','kanapka (z bagietki)'),
('La Comida','Jedzenie','el sándwich','kanapka (z chleba tostowego)'),
('La Comida','Jedzenie','la hamburguesa','hamburger'),
('La Comida','Jedzenie','la pizza','pizza'),
('Las Bebidas','Napoje','el agua','woda'),
('Las Bebidas','Napoje','el agua mineral','woda mineralna'),
('Las Bebidas','Napoje','el agua con gas','woda gazowana'),
('Las Bebidas','Napoje','el agua sin gas','woda niegazowana'),
('Las Bebidas','Napoje','el té','herbata'),
('Las Bebidas','Napoje','el té negro','czarna herbata'),
('Las Bebidas','Napoje','el té verde','zielona herbata'),
('Las Bebidas','Napoje','el café','kawa'),
('Las Bebidas','Napoje','el café solo','czarna kawa'),
('Las Bebidas','Napoje','el café con leche','kawa z mlekiem'),
('Las Bebidas','Napoje','el cortado','kawa z odrobiną mleka'),
('Las Bebidas','Napoje','el capuchino','cappuccino'),
('Las Bebidas','Napoje','el zumo / el jugo','sok'),
('Las Bebidas','Napoje','el zumo de naranja','sok pomarańczowy'),
('Las Bebidas','Napoje','el zumo de manzana','sok jabłkowy'),
('Las Bebidas','Napoje','el zumo de piña','sok ananasowy'),
('Las Bebidas','Napoje','la leche','mleko'),
('Las Bebidas','Napoje','el batido','koktajl mleczny / szejk'),
('Las Bebidas','Napoje','el refresco','napój gazowany'),
('Las Bebidas','Napoje','la cola','cola'),
('Las Bebidas','Napoje','la limonada','lemoniada'),
('Las Bebidas','Napoje','la naranjada','oranżada'),
('Las Bebidas','Napoje','el jarabe','syrop'),
('Las Bebidas','Napoje','la cerveza','piwo'),
('Las Bebidas','Napoje','la cerveza rubia','jasne piwo'),
('Las Bebidas','Napoje','la cerveza negra','ciemne piwo'),
('Las Bebidas','Napoje','el vino','wino'),
('Las Bebidas','Napoje','el vino tinto','czerwone wino'),
('Las Bebidas','Napoje','el vino blanco','białe wino'),
('Las Bebidas','Napoje','el vino rosado','różowe wino'),
('Las Bebidas','Napoje','el champán','szampan'),
('Las Bebidas','Napoje','el cava','wino musujące'),
('Las Bebidas','Napoje','el licor','likier'),
('Las Bebidas','Napoje','el ron','rum'),
('Las Bebidas','Napoje','el vodka','wódka'),
('Las Bebidas','Napoje','el whisky','whisky'),
('Las Bebidas','Napoje','la ginebra','dżin'),
('Las Bebidas','Napoje','el cóctel','koktajl (alkoholowy)'),
('Las Bebidas','Napoje','el aguardiente','wódka / bimber'),
('Las Bebidas','Napoje','el vermú','wermut'),
('Las Bebidas','Napoje','la sangría','sangria'),
('Las Bebidas','Napoje','el chocolate caliente','gorąca czekolada'),
('Las Bebidas','Napoje','el hielo','lód'),
('Las Bebidas','Napoje','la bebida isotónica','napój izotoniczny'),
('Las Bebidas','Napoje','la infusión','napar'),
('Las Bebidas','Napoje','el vaso','szklanka'),
('Las Bebidas','Napoje','la taza','filiżanka'),
('Las Bebidas','Napoje','la botella','butelka'),
('Las Bebidas','Napoje','la jarra','dzbanek'),
('Las Bebidas','Napoje','la lata','puszka'),
('La Ropa','Ubrania','la camisa','koszula'),
('La Ropa','Ubrania','la camiseta','koszulka / t-shirt'),
('La Ropa','Ubrania','el pantalón','spodnie'),
('La Ropa','Ubrania','los vaqueros','dżinsy'),
('La Ropa','Ubrania','la falda','spódnica'),
('La Ropa','Ubrania','el vestido','sukienka'),
('La Ropa','Ubrania','el traje','garnitur'),
('La Ropa','Ubrania','la chaqueta','kurtka / marynarka'),
('La Ropa','Ubrania','el abrigo','płaszcz'),
('La Ropa','Ubrania','el jersey / el suéter','sweter'),
('La Ropa','Ubrania','la sudadera','bluza'),
('La Ropa','Ubrania','el chaleco','kamizelka'),
('La Ropa','Ubrania','los pantalones cortos','krótkie spodenki'),
('La Ropa','Ubrania','la ropa interior','bielizna'),
('La Ropa','Ubrania','las bragas','majtki (damskie)'),
('La Ropa','Ubrania','los calzoncillos','majtki (męskie)'),
('La Ropa','Ubrania','el sujetador','biustonosz'),
('La Ropa','Ubrania','los calcetines','skarpetki'),
('La Ropa','Ubrania','las medias','rajstopy / pończochy'),
('La Ropa','Ubrania','el pijama','piżama'),
('La Ropa','Ubrania','el camisón','koszula nocna'),
('La Ropa','Ubrania','el albornoz','szlafrok'),
('La Ropa','Ubrania','el bañador','strój kąpielowy'),
('La Ropa','Ubrania','el bikini','bikini'),
('La Ropa','Ubrania','los zapatos','buty'),
('La Ropa','Ubrania','las zapatillas de deporte','buty sportowe'),
('La Ropa','Ubrania','las botas','kozaki / buty za kostkę'),
('La Ropa','Ubrania','las sandalias','sandały'),
('La Ropa','Ubrania','los tacones','buty na obcasie'),
('La Ropa','Ubrania','las zapatillas de casa','kapcie'),
('La Ropa','Ubrania','el gorro','czapka'),
('La Ropa','Ubrania','el sombrero','kapelusz'),
('La Ropa','Ubrania','la bufanda','szalik'),
('La Ropa','Ubrania','los guantes','rękawiczki'),
('La Ropa','Ubrania','el cinturón','pasek'),
('La Ropa','Ubrania','la corbata','krawat'),
('La Ropa','Ubrania','la pajarita','mucha (do garnituru)'),
('La Ropa','Ubrania','el pañuelo','chustka'),
('La Ropa','Ubrania','el bolso','torebka'),
('La Ropa','Ubrania','la cartera','portfel'),
('La Ropa','Ubrania','la mochila','plecak'),
('La Ropa','Ubrania','el paraguas','parasol'),
('La Ropa','Ubrania','las gafas de sol','okulary przeciwsłoneczne'),
('La Ropa','Ubrania','el botón','guzik'),
('La Ropa','Ubrania','la cremallera','zamek błyskawiczny'),
('La Ropa','Ubrania','el bolsillo','kieszeń'),
('La Ropa','Ubrania','la manga','rękaw'),
('La Ropa','Ubrania','el cuello','kołnierzyk'),
('La Ropa','Ubrania','el algodón','bawełna'),
('La Ropa','Ubrania','la lana','wełna'),
('Los Colores','Kolory','el color','kolor'),
('Los Colores','Kolory','rojo','czerwony'),
('Los Colores','Kolory','azul','niebieski'),
('Los Colores','Kolory','amarillo','żółty'),
('Los Colores','Kolory','verde','zielony'),
('Los Colores','Kolory','negro','czarny'),
('Los Colores','Kolory','blanco','biały'),
('Los Colores','Kolory','gris','szary'),
('Los Colores','Kolory','marrón / café','brązowy'),
('Los Colores','Kolory','naranja','pomarańczowy'),
('Los Colores','Kolory','rosa','różowy'),
('Los Colores','Kolory','morado / púrpura','fioletowy'),
('Los Colores','Kolory','violeta','fiołkowy'),
('Los Colores','Kolory','celeste','błękitny'),
('Los Colores','Kolory','azul marino','granatowy'),
('Los Colores','Kolory','verde oliva','oliwkowy'),
('Los Colores','Kolory','verde esmeralda','szmaragdowy'),
('Los Colores','Kolory','beige','beżowy'),
('Los Colores','Kolory','granate / burdeos','bordowy'),
('Los Colores','Kolory','fucsia','fuksja'),
('Los Colores','Kolory','turquesa','turkusowy'),
('Los Colores','Kolory','coral','koralowy'),
('Los Colores','Kolory','magenta','magenta'),
('Los Colores','Kolory','lila','liliowy'),
('Los Colores','Kolory','dorado','złoty'),
('Los Colores','Kolory','plateado','srebrny'),
('Los Colores','Kolory','bronce','brązowy (odlew) / spiżowy'),
('Los Colores','Kolory','cobre','miedziany'),
('Los Colores','Kolory','claro','jasny'),
('Los Colores','Kolory','oscuro','ciemny'),
('Los Colores','Kolory','brillante','błyszczący'),
('Los Colores','Kolory','mate','matowy'),
('Los Colores','Kolory','pálido','blady'),
('Los Colores','Kolory','vivo','żywy / jaskrawy'),
('Los Colores','Kolory','intenso','intensywny'),
('Los Colores','Kolory','pastel','pastelowy'),
('Los Colores','Kolory','multicolor','wielokolorowy'),
('Los Colores','Kolory','a rayas','w paski'),
('Los Colores','Kolory','a cuadros','w kratkę'),
('Los Colores','Kolory','a lunares','w grochy'),
('Los Colores','Kolory','liso','gładki / jednolity'),
('Los Colores','Kolory','teñir','farbować'),
('Los Colores','Kolory','pintar','malować'),
('Los Colores','Kolory','el tono','odcień'),
('Los Colores','Kolory','el matiz','tonacja / niuans'),
('Los Colores','Kolory','el arcoíris','tęcza'),
('Los Colores','Kolory','transparente','przezroczysty'),
('Los Colores','Kolory','opaco','nieprzezroczysty'),
('Los Colores','Kolory','translúcido','półprzezroczysty'),
('Los Colores','Kolory','fosforescente','fosforyzujący'),
('Los Números','Liczby','cero','zero'),
('Los Números','Liczby','uno','jeden'),
('Los Números','Liczby','dos','dwa'),
('Los Números','Liczby','tres','trzy'),
('Los Números','Liczby','cuatro','cztery'),
('Los Números','Liczby','cinco','pięć'),
('Los Números','Liczby','seis','sześć'),
('Los Números','Liczby','siete','siedem'),
('Los Números','Liczby','ocho','osiem'),
('Los Números','Liczby','nueve','dziewięć'),
('Los Números','Liczby','diez','dziesięć'),
('Los Números','Liczby','once','jedenaście'),
('Los Números','Liczby','doce','dwanaście'),
('Los Números','Liczby','trece','trzynaście'),
('Los Números','Liczby','catorce','czternaście'),
('Los Números','Liczby','quince','piętnaście'),
('Los Números','Liczby','dieciséis','szesnaście'),
('Los Números','Liczby','diecisiete','siedemnaście'),
('Los Números','Liczby','dieciocho','osiemnaście'),
('Los Números','Liczby','diecinueve','dziewiętnaście'),
('Los Números','Liczby','veinte','dwadzieścia'),
('Los Números','Liczby','veintiuno','dwadzieścia jeden'),
('Los Números','Liczby','treinta','trzydzieści'),
('Los Números','Liczby','cuarenta','czterdzieści'),
('Los Números','Liczby','cincuenta','pięćdziesiąt'),
('Los Números','Liczby','sesenta','sześćdziesiąt'),
('Los Números','Liczby','setenta','siedemdziesiąt'),
('Los Números','Liczby','ochenta','osiemdziesiąt'),
('Los Números','Liczby','noventa','dziewięćdziesiąt'),
('Los Números','Liczby','cien','sto'),
('Los Números','Liczby','ciento uno','sto jeden'),
('Los Números','Liczby','doscientos','dwieście'),
('Los Números','Liczby','trescientos','trzysta'),
('Los Números','Liczby','quinientos','pięćset'),
('Los Números','Liczby','mil','tysiąc'),
('Los Números','Liczby','un millón','milion'),
('Los Números','Liczby','un billón','bilion'),
('Los Números','Liczby','la mitad','połowa'),
('Los Números','Liczby','un tercio','jedna trzecia'),
('Los Números','Liczby','un cuarto','jedna czwarta'),
('Los Números','Liczby','primero','pierwszy'),
('Los Números','Liczby','segundo','drugi'),
('Los Números','Liczby','tercero','trzeci'),
('Los Números','Liczby','cuarto','czwarty'),
('Los Números','Liczby','quinto','piąty'),
('Los Números','Liczby','sexto','szósty'),
('Los Números','Liczby','séptimo','siódmy'),
('Los Números','Liczby','octavo','ósmy'),
('Los Números','Liczby','noveno','dziewiąty'),
('Los Números','Liczby','décimo','dziesiąty'),
('El Tiempo','Czas','el tiempo','czas / pogoda'),
('El Tiempo','Czas','la hora','godzina'),
('El Tiempo','Czas','el minuto','minuta'),
('El Tiempo','Czas','el segundo','sekunda'),
('El Tiempo','Czas','el día','dzień'),
('El Tiempo','Czas','la semana','tydzień'),
('El Tiempo','Czas','el fin de semana','weekend'),
('El Tiempo','Czas','el mes','miesiąc'),
('El Tiempo','Czas','el año','rok'),
('El Tiempo','Czas','la década','dekada'),
('El Tiempo','Czas','el siglo','wiek / stulecie'),
('El Tiempo','Czas','el milenio','tysiąclecie'),
('El Tiempo','Czas','hoy','dzisiaj'),
('El Tiempo','Czas','mañana','jutro / rano'),
('El Tiempo','Czas','ayer','wczoraj'),
('El Tiempo','Czas','anteayer','przedwczoraj'),
('El Tiempo','Czas','pasado mañana','pojutrze'),
('El Tiempo','Czas','la madrugada','świt / wczesny ranek'),
('El Tiempo','Czas','la mañana','poranek'),
('El Tiempo','Czas','el mediodía','południe'),
('El Tiempo','Czas','la tarde','popołudnie'),
('El Tiempo','Czas','la noche','noc'),
('El Tiempo','Czas','la medianoche','północ'),
('El Tiempo','Czas','el amanecer','wschód słońca'),
('El Tiempo','Czas','el atardecer','zachód słońca'),
('El Tiempo','Czas','la fecha','data'),
('El Tiempo','Czas','el calendario','kalendarz'),
('El Tiempo','Czas','el reloj','zegar / zegarek'),
('El Tiempo','Czas','el reloj de pulsera','zegarek na rękę'),
('El Tiempo','Czas','el reloj de pared','zegar ścienny'),
('El Tiempo','Czas','el despertador','budzik'),
('El Tiempo','Czas','pronto','wkrótce / wcześnie'),
('El Tiempo','Czas','tarde','późno'),
('El Tiempo','Czas','temprano','wcześnie'),
('El Tiempo','Czas','ahora','teraz'),
('El Tiempo','Czas','luego','później'),
('El Tiempo','Czas','antes','wcześniej / przedtem'),
('El Tiempo','Czas','después','potem'),
('El Tiempo','Czas','siempre','zawsze'),
('El Tiempo','Czas','nunca','nigdy'),
('El Tiempo','Czas','a veces','czasami'),
('El Tiempo','Czas','a menudo','często'),
('El Tiempo','Czas','de vez en cuando','od czasu do czasu'),
('El Tiempo','Czas','diariamente','codziennie'),
('El Tiempo','Czas','semanalmente','cotygodniowo'),
('El Tiempo','Czas','mensualmente','miesięcznie'),
('El Tiempo','Czas','anualmente','rocznie'),
('El Tiempo','Czas','puntual','punktualny'),
('El Tiempo','Czas','retrasado','opóźniony'),
('El Tiempo','Czas','la duración','czas trwania'),
('El Clima','Pogoda','el sol','słońce'),
('El Clima','Pogoda','la lluvia','deszcz'),
('El Clima','Pogoda','la nieve','śnieg'),
('El Clima','Pogoda','el viento','wiatr'),
('El Clima','Pogoda','la nube','chmura'),
('El Clima','Pogoda','la tormenta','burza'),
('El Clima','Pogoda','el relámpago','błyskawica'),
('El Clima','Pogoda','el trueno','grzmot'),
('El Clima','Pogoda','el granizo','grad'),
('El Clima','Pogoda','la niebla','mgła'),
('El Clima','Pogoda','el hielo','lód'),
('El Clima','Pogoda','el calor','upał'),
('El Clima','Pogoda','el frío','zimno / chłód'),
('El Clima','Pogoda','la temperatura','temperatura'),
('El Clima','Pogoda','el grado','stopień'),
('El Clima','Pogoda','el pronóstico','prognoza pogody'),
('El Clima','Pogoda','el huracán','huragan'),
('El Clima','Pogoda','el tornado','tornado'),
('El Clima','Pogoda','el arcoíris','tęcza'),
('El Clima','Pogoda','el clima','klimat'),
('El Clima','Pogoda','soleado','słoneczny'),
('El Clima','Pogoda','nublado','pochmurny'),
('El Clima','Pogoda','lluvioso','deszczowy'),
('El Clima','Pogoda','ventoso','wietrzny'),
('El Clima','Pogoda','despejado','bezchmurny'),
('El Clima','Pogoda','húmedo','wilgotny'),
('El Clima','Pogoda','seco','suchy'),
('El Clima','Pogoda','la humedad','wilgotność'),
('El Clima','Pogoda','la sequía','susza'),
('El Clima','Pogoda','la inundación','powódź'),
('El Clima','Pogoda','llover','padać (o deszczu)'),
('El Clima','Pogoda','nevar','padać (o śniegu)'),
('El Clima','Pogoda','helar','zamarzać'),
('El Clima','Pogoda','derretir','topnieć'),
('El Clima','Pogoda','la brisa','bryza'),
('El Clima','Pogoda','el chaparrón','ulewa / kapuśniaczek'),
('El Clima','Pogoda','el charco','kałuża'),
('El Clima','Pogoda','el termómetro','termometr'),
('El Clima','Pogoda','el invierno','zima'),
('El Clima','Pogoda','la primavera','wiosna'),
('El Clima','Pogoda','el verano','lato'),
('El Clima','Pogoda','el otoño','jesień'),
('El Clima','Pogoda','el chubasco','przlotny deszcz'),
('El Clima','Pogoda','la ráfaga','poryw wiatru'),
('El Clima','Pogoda','la escarcha','szron'),
('El Clima','Pogoda','el bochorno','parno / duchota'),
('El Clima','Pogoda','templado','umiarkowany / łagodny'),
('El Clima','Pogoda','el monzón','monsun'),
('El Clima','Pogoda','la gota','kropla'),
('El Clima','Pogoda','el paraguas','parasol'),
('La Naturaleza','Natura','la naturaleza','natura / przyroda'),
('La Naturaleza','Natura','el árbol','drzewo'),
('La Naturaleza','Natura','el bosque','las'),
('La Naturaleza','Natura','la selva','dżungla / puszcza'),
('La Naturaleza','Natura','la montaña','góra'),
('La Naturaleza','Natura','la colina','wzgórze'),
('La Naturaleza','Natura','el valle','dolina'),
('La Naturaleza','Natura','el río','rzeka'),
('La Naturaleza','Natura','el lago','jezioro'),
('La Naturaleza','Natura','el mar','morze'),
('La Naturaleza','Natura','el océano','ocean'),
('La Naturaleza','Natura','la playa','plaża'),
('La Naturaleza','Natura','la arena','piasek'),
('La Naturaleza','Natura','la isla','wyspa'),
('La Naturaleza','Natura','la costa','wybrzeże'),
('La Naturaleza','Natura','el desierto','pustynia'),
('La Naturaleza','Natura','la tierra','ziemia'),
('La Naturaleza','Natura','el suelo','gleba / grunt'),
('La Naturaleza','Natura','la piedra','kamień'),
('La Naturaleza','Natura','la roca','skała'),
('La Naturaleza','Natura','el mineral','minerał'),
('La Naturaleza','Natura','la hierba','trawa'),
('La Naturaleza','Natura','el césped','trawnik'),
('La Naturaleza','Natura','la planta','roślina'),
('La Naturaleza','Natura','la flor','kwiat'),
('La Naturaleza','Natura','la hoja','liść'),
('La Naturaleza','Natura','la rama','gałąź'),
('La Naturaleza','Natura','la raíz','korzeń'),
('La Naturaleza','Natura','el tronco','pień'),
('La Naturaleza','Natura','el arbusto','krzew'),
('La Naturaleza','Natura','la semilla','nasiono'),
('La Naturaleza','Natura','el fuego','ogień'),
('La Naturaleza','Natura','el aire','powietrze'),
('La Naturaleza','Natura','el agua','woda'),
('La Naturaleza','Natura','el paisaje','krajobraz'),
('La Naturaleza','Natura','el volcán','wulkan'),
('La Naturaleza','Natura','la cueva','jaskinia'),
('La Naturaleza','Natura','la cascada','wodospad'),
('La Naturaleza','Natura','el campo','pole / wieś'),
('La Naturaleza','Natura','el prado','łąka'),
('La Naturaleza','Natura','la fauna','fauna'),
('La Naturaleza','Natura','la flora','flora'),
('La Naturaleza','Natura','la ecología','ekologia'),
('La Naturaleza','Natura','el medio ambiente','środowisko naturalne'),
('La Naturaleza','Natura','la contaminación','zanieczyszczenie'),
('La Naturaleza','Natura','proteger','chronić'),
('La Naturaleza','Natura','el parque nacional','park narodowy'),
('La Naturaleza','Natura','la reserva','rezerwat'),
('La Naturaleza','Natura','el camino','ścieżka / droga'),
('La Naturaleza','Natura','el cielo','niebo'),
('Los Animales','Zwierzęta','el animal','zwierzę'),
('Los Animales','Zwierzęta','el perro','pies'),
('Los Animales','Zwierzęta','el gato','kot'),
('Los Animales','Zwierzęta','el ratón','mysz'),
('Los Animales','Zwierzęta','el caballo','koń'),
('Los Animales','Zwierzęta','la vaca','krowa'),
('Los Animales','Zwierzęta','el cerdo','świnia'),
('Los Animales','Zwierzęta','la oveja','owca'),
('Los Animales','Zwierzęta','la cabra','koza'),
('Los Animales','Zwierzęta','el burro','osioł'),
('Los Animales','Zwierzęta','la gallina','kura'),
('Los Animales','Zwierzęta','el gallo','kogut'),
('Los Animales','Zwierzęta','el pato','kaczka'),
('Los Animales','Zwierzęta','el pájaro','ptak'),
('Los Animales','Zwierzęta','el pez','ryba'),
('Los Animales','Zwierzęta','la rana','żaba'),
('Los Animales','Zwierzęta','la serpiente','wąż'),
('Los Animales','Zwierzęta','el cocodrilo','krokodyl'),
('Los Animales','Zwierzęta','la tortuga','żółw'),
('Los Animales','Zwierzęta','el león','lew'),
('Los Animales','Zwierzęta','el tigre','tygrys'),
('Los Animales','Zwierzęta','el elefante','słoń'),
('Los Animales','Zwierzęta','la jirafa','żyrafa'),
('Los Animales','Zwierzęta','el mono','małpa'),
('Los Animales','Zwierzęta','el oso','niedźwiedź'),
('Los Animales','Zwierzęta','el lobo','wilk'),
('Los Animales','Zwierzęta','el zorro','lis'),
('Los Animales','Zwierzęta','el ciervo','jeleń'),
('Los Animales','Zwierzęta','el conejo','królik'),
('Los Animales','Zwierzęta','la liebre','zając'),
('Los Animales','Zwierzęta','el murciélago','nietoperz'),
('Los Animales','Zwierzęta','la mariposa','motyl'),
('Los Animales','Zwierzęta','la mosca','mucha'),
('Los Animales','Zwierzęta','el mosquito','komar'),
('Los Animales','Zwierzęta','la abeja','pszczoła'),
('Los Animales','Zwierzęta','la araña','pająk'),
('Los Animales','Zwierzęta','la hormiga','mrówka'),
('Los Animales','Zwierzęta','el gusano','robak / dżdżownica'),
('Los Animales','Zwierzęta','el caracol','ślimak'),
('Los Animales','Zwierzęta','el cangrejo','krab'),
('Los Animales','Zwierzęta','la ballena','wieloryb'),
('Los Animales','Zwierzęta','el delfín','delfin'),
('Los Animales','Zwierzęta','el tiburón','rekin'),
('Los Animales','Zwierzęta','el pulpo','ośmiornica'),
('Los Animales','Zwierzęta','la foca','foka'),
('Los Animales','Zwierzęta','el pingüino','pingwin'),
('Los Animales','Zwierzęta','el búho','sowa'),
('Los Animales','Zwierzęta','el águila','orzeł'),
('Los Animales','Zwierzęta','el loro','papuga'),
('Los Animales','Zwierzęta','la mascota','zwierzę domowe'),
('Las Profesiones','Zawody','la profesión','zawód'),
('Las Profesiones','Zawody','el trabajo','praca'),
('Las Profesiones','Zawody','el médico / la médica','lekarz / lekarka'),
('Las Profesiones','Zawody','el enfermero / la enfermera','pielęgniarz / pielęgniarka'),
('Las Profesiones','Zawody','el dentista','dentysta'),
('Las Profesiones','Zawody','el veterinario','weterynarz'),
('Las Profesiones','Zawody','el profesor / la profesora','nauczyciel / nauczycielka'),
('Las Profesiones','Zawody','el estudiante','student / uczeń'),
('Las Profesiones','Zawody','el abogado / la abogada','prawnik / prawniczka'),
('Las Profesiones','Zawody','el juez / la jueza','sędzia'),
('Las Profesiones','Zawody','el policía','policjant'),
('Las Profesiones','Zawody','el bombero','strażak'),
('Las Profesiones','Zawody','el soldado','żołnierz'),
('Las Profesiones','Zawody','el ingeniero / la ingeniera','inżynier'),
('Las Profesiones','Zawody','el arquitecto','architekt'),
('Las Profesiones','Zawody','el informático','informatyk'),
('Las Profesiones','Zawody','el científico','naukowiec'),
('Las Profesiones','Zawody','el periodista','dziennikarz'),
('Las Profesiones','Zawody','el escritor / la escritora','pisarz / pisarka'),
('Las Profesiones','Zawody','el actor / la actriz','aktor / aktorka'),
('Las Profesiones','Zawody','el cantante','piosenkarz'),
('Las Profesiones','Zawody','el músico','muzyk'),
('Las Profesiones','Zawody','el artista','artysta'),
('Las Profesiones','Zawody','el pintor / la pintora','malarz / malarka'),
('Las Profesiones','Zawody','el fotógrafo','fotograf'),
('Las Profesiones','Zawody','el cocinero / la cocinera','kucharz / kucharka'),
('Las Profesiones','Zawody','el camarero / la camarera','kelner / kelnerka'),
('Las Profesiones','Zawody','el panadero','piekarz'),
('Las Profesiones','Zawody','el carnicero','rzeźnik'),
('Las Profesiones','Zawody','el peluquero / la peluquera','fryzjer / fryzjerka'),
('Las Profesiones','Zawody','el mecánico','mechanik'),
('Las Profesiones','Zawody','el conductor','kierowca'),
('Las Profesiones','Zawody','el piloto','pilot'),
('Las Profesiones','Zawody','el albañil','murarz'),
('Las Profesiones','Zawody','el electricista','elektryk'),
('Las Profesiones','Zawody','el fontanero','hydraulik'),
('Las Profesiones','Zawody','el carpintero','stolarz'),
('Las Profesiones','Zawody','el agricultor','rolnik'),
('Las Profesiones','Zawody','el jardinero','ogrodnik'),
('Las Profesiones','Zawody','el cartero','listonosz'),
('Las Profesiones','Zawody','el vendedor / la vendedora','sprzedawca / sprzedawczyni'),
('Las Profesiones','Zawody','el dependiente','ekspedient'),
('Las Profesiones','Zawody','el cajero / la cajera','kasjer / kasjerka'),
('Las Profesiones','Zawody','el contable','księgowy'),
('Las Profesiones','Zawody','el secretario / la secretaria','sekretarz / sekretarka'),
('Las Profesiones','Zawody','el jefe / la jefa','szef / szefowa'),
('Las Profesiones','Zawody','el empleado / la empleada','pracownik / pracownica'),
('Las Profesiones','Zawody','el empresario','przedsiębiorca'),
('Las Profesiones','Zawody','el político','polityk'),
('Las Profesiones','Zawody','el gerente','menedżer / kierownik'),
('La Educación','Edukacja','la educación','edukacja'),
('La Educación','Edukacja','la escuela','szkoła'),
('La Educación','Edukacja','el colegio','szkoła (podstawowa)'),
('La Educación','Edukacja','el instituto','liceum / szkoła średnia'),
('La Educación','Edukacja','la universidad','uniwersytet'),
('La Educación','Edukacja','la clase','klasa / lekcja'),
('La Educación','Edukacja','el aula','sala lekcyjna'),
('La Educación','Edukacja','el curso','kurs / rok szkolny'),
('La Educación','Edukacja','la asignatura','przedmiot szkolny'),
('La Educación','Edukacja','el recreo','przerwa'),
('La Educación','Edukacja','el maestro / la maestra','nauczyciel / nauczycielka (klas młodszych)'),
('La Educación','Edukacja','el alumno / la alumna','uczeń / uczennica'),
('La Educación','Edukacja','el compañero de clase','kolega z klasy'),
('La Educación','Edukacja','el director','dyrektor'),
('La Educación','Edukacja','el libro','książka'),
('La Educación','Edukacja','el cuaderno','zeszyt'),
('La Educación','Edukacja','el estuche','piórnik'),
('La Educación','Edukacja','el bolígrafo / el boli','długopis'),
('La Educación','Edukacja','el lápiz','ołówek'),
('La Educación','Edukacja','la goma de borrar','gumka do ścierania'),
('La Educación','Edukacja','el rotulador','flamaster / mazak'),
('La Educación','Edukacja','la regla','linijka'),
('La Educación','Edukacja','la mochila','plecak'),
('La Educación','Edukacja','la pizarra','tablica'),
('La Educación','Edukacja','la tiza','kreda'),
('La Educación','Edukacja','el borrador','gąbka do tablicy'),
('La Educación','Edukacja','el pupitre','ławka szkolna'),
('La Educación','Edukacja','el escritorio','biurko'),
('La Educación','Edukacja','la biblioteca','biblioteka'),
('La Educación','Edukacja','el gimnasio','sala gimnastyczna'),
('La Educación','Edukacja','el comedor','stołówka'),
('La Educación','Edukacja','el examen','egzamin'),
('La Educación','Edukacja','la prueba','sprawdzian'),
('La Educación','Edukacja','el test','test'),
('La Educación','Edukacja','la nota','ocena'),
('La Educación','Edukacja','el sobresaliente','ocena bardzo dobra / celująca'),
('La Educación','Edukacja','el aprobado','ocena dostateczna / zdany'),
('La Educación','Edukacja','el suspenso','ocena niedostateczna / oblany'),
('La Educación','Edukacja','los deberes','praca domowa'),
('La Educación','Edukacja','la tarea','zadanie (domowe)'),
('La Educación','Edukacja','estudiar','uczyć się (nauka)'),
('La Educación','Edukacja','aprender','uczyć się (przyswajać wiedzę)'),
('La Educación','Edukacja','enseñar','nauczać'),
('La Educación','Edukacja','leer','czytać'),
('La Educación','Edukacja','escribir','pisać'),
('La Educación','Edukacja','preguntar','pytać'),
('La Educación','Edukacja','responder','odpowiadać'),
('La Educación','Edukacja','el conocimiento','wiedza'),
('La Educación','Edukacja','el título','tytuł / dyplom'),
('La Educación','Edukacja','la beca','stypendium'),
('La Salud','Zdrowie','la salud','zdrowie'),
('La Salud','Zdrowie','la enfermedad','choroba'),
('La Salud','Zdrowie','el dolor','ból'),
('La Salud','Zdrowie','el paciente','pacjent'),
('La Salud','Zdrowie','la pastilla / la píldora','tabletka / pigułka'),
('La Salud','Zdrowie','el jarabe','syrop'),
('La Salud','Zdrowie','la inyección','zastrzyk'),
('La Salud','Zdrowie','la receta','recepta'),
('La Salud','Zdrowie','el termómetro','termometr'),
('La Salud','Zdrowie','la fiebre','gorączka'),
('La Salud','Zdrowie','la tos','kaszel'),
('La Salud','Zdrowie','el resfriado','przeziębienie'),
('La Salud','Zdrowie','la gripe','grypa'),
('La Salud','Zdrowie','el síntoma','objaw / symptom'),
('La Salud','Zdrowie','la tirita / la curita','plaster'),
('La Salud','Zdrowie','el vendaje','bandaż / opatrunek'),
('La Salud','Zdrowie','la sangre','krew'),
('La Salud','Zdrowie','sangrar','krwawić'),
('La Salud','Zdrowie','respirar','oddychać'),
('La Salud','Zdrowie','desmayarse','zemdleć'),
('La Salud','Zdrowie','vomitar','wymiotować'),
('La Salud','Zdrowie','mareado','mający mdłości / zawroty głowy'),
('La Salud','Zdrowie','la alergia','alergia'),
('La Salud','Zdrowie','la vacuna','szczepionka'),
('La Salud','Zdrowie','el virus','wirus'),
('La Salud','Zdrowie','la bacteria','bakteria'),
('La Salud','Zdrowie','la infección','infekcja'),
('La Salud','Zdrowie','la cicatriz','blizna'),
('La Salud','Zdrowie','la herida','rana'),
('La Salud','Zdrowie','el pulso','tętno / puls'),
('La Salud','Zdrowie','la presión arterial','ciśnienie krwi'),
('La Salud','Zdrowie','el infarto','zawał'),
('La Salud','Zdrowie','el asma','astma'),
('La Salud','Zdrowie','el cáncer','rak (choroba)'),
('La Salud','Zdrowie','la operación','operacja'),
('La Salud','Zdrowie','el cirujano','chirurg'),
('La Salud','Zdrowie','la sala de emergencias','ostry dyżur / SOR'),
('La Salud','Zdrowie','la camilla','nosze'),
('La Salud','Zdrowie','la silla de ruedas','wózek inwalidzki'),
('La Salud','Zdrowie','la muleta','kula (ortopedyczna)'),
('La Salud','Zdrowie','el yeso / la escayola','gips'),
('La Salud','Zdrowie','romperse','złamać sobie (coś)'),
('La Salud','Zdrowie','curar','leczyć / uzdrawiać'),
('La Salud','Zdrowie','el botiquín','apteczka'),
('La Salud','Zdrowie','la clínica','klinika'),
('La Salud','Zdrowie','sano','zdrowy'),
('La Salud','Zdrowie','enfermo','chory'),
('La Salud','Zdrowie','recuperarse','wracać do zdrowia'),
('La Salud','Zdrowie','el tratamiento','leczenie'),
('La Salud','Zdrowie','el diagnóstico','diagnoza');
