insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Enfermedades','Choroby','la enfermedad','choroba'),
('Enfermedades','Choroby','el resfriado','przeziębienie'),
('Enfermedades','Choroby','la gripe','grypa'),
('Enfermedades','Choroby','la fiebre','gorączka'),
('Enfermedades','Choroby','la tos','kaszel'),
('Enfermedades','Choroby','el dolor de cabeza','ból głowy'),
('Enfermedades','Choroby','el dolor de garganta','ból gardła'),
('Enfermedades','Choroby','el dolor de estómago','ból brzucha'),
('Enfermedades','Choroby','la infección','infekcja'),
('Enfermedades','Choroby','la inflamación','stan zapalny'),
('Enfermedades','Choroby','el virus','wirus'),
('Enfermedades','Choroby','la bacteria','bakteria'),
('Enfermedades','Choroby','el asma','astma'),
('Enfermedades','Choroby','la alergia','alergia'),
('Enfermedades','Choroby','la diabetes','cukrzyca'),
('Enfermedades','Choroby','el cáncer','rak (choroba)'),
('Enfermedades','Choroby','el infarto','zawał'),
('Enfermedades','Choroby','el derrame cerebral','udar mózgu'),
('Enfermedades','Choroby','la neumonía','zapalenie płuc'),
('Enfermedades','Choroby','la bronquitis','zapalenie oskrzeli'),
('Enfermedades','Choroby','la artritis','artretyzm'),
('Enfermedades','Choroby','el reumatismo','reumatyzm'),
('Enfermedades','Choroby','la hipertensión','nadciśnienie'),
('Enfermedades','Choroby','el colesterol','cholesterol'),
('Enfermedades','Choroby','la obesidad','otyłość'),
('Enfermedades','Choroby','el trastorno','zaburzenie'),
('Enfermedades','Choroby','la depresión','depresja'),
('Enfermedades','Choroby','la ansiedad','niepokój / stany lękowe'),
('Enfermedades','Choroby','el estrés','stres'),
('Enfermedades','Choroby','el insomnio','bezsenność'),
('Enfermedades','Choroby','la migraña','migrena'),
('Enfermedades','Choroby','la diarrea','biegunka'),
('Enfermedades','Choroby','el vómito','wymioty'),
('Enfermedades','Choroby','el mareo','zawroty głowy / choroba lokomocyjna'),
('Enfermedades','Choroby','la náusea','mdłości'),
('Enfermedades','Choroby','la fractura','złamanie'),
('Enfermedades','Choroby','el esguince','skręcenie'),
('Enfermedades','Choroby','la cicatriz','blizna'),
('Enfermedades','Choroby','la herida','rana'),
('Enfermedades','Choroby','el síntoma','objaw'),
('Enfermedades','Choroby','el diagnóstico','diagnoza'),
('Enfermedades','Choroby','contagiarse','zarazić się'),
('Enfermedades','Choroby','el contagio','zarażenie'),
('Enfermedades','Choroby','la epidemia','epidemia'),
('Enfermedades','Choroby','la pandemia','pandemia'),
('Enfermedades','Choroby','crónico','przewlekły'),
('Enfermedades','Choroby','agudo','ostry (np. ból)'),
('Enfermedades','Choroby','leve','lekki (np. przebieg)'),
('Enfermedades','Choroby','grave','ciężki / poważny'),
('Enfermedades','Choroby','incurable','nieuleczalny'),
('Partes del Día','Pory dnia','el amanecer','świt'),
('Partes del Día','Pory dnia','la madrugada','wczesny ranek'),
('Partes del Día','Pory dnia','la mañana','poranek'),
('Partes del Día','Pory dnia','el mediodía','południe'),
('Partes del Día','Pory dnia','la tarde','popołudnie'),
('Partes del Día','Pory dnia','el atardecer','późne popołudnie / zachód słońca'),
('Partes del Día','Pory dnia','el anochecer','zmierzch'),
('Partes del Día','Pory dnia','la noche','noc'),
('Partes del Día','Pory dnia','la medianoche','północ'),
('Partes del Día','Pory dnia','de madrugada','nad ranem'),
('Partes del Día','Pory dnia','por la mañana','rano'),
('Partes del Día','Pory dnia','al mediodía','w południe'),
('Partes del Día','Pory dnia','por la tarde','po południu'),
('Partes del Día','Pory dnia','por la noche','w nocy'),
('Partes del Día','Pory dnia','el alba','brzask'),
('Partes del Día','Pory dnia','la puesta de sol','zachód słońca'),
('Partes del Día','Pory dnia','la salida del sol','wschód słońca'),
('Partes del Día','Pory dnia','el crepúsculo','zmrok'),
('Partes del Día','Pory dnia','la oscuridad','ciemność'),
('Partes del Día','Pory dnia','la luz','światło'),
('Partes del Día','Pory dnia','el día','dzień'),
('Partes del Día','Pory dnia','la jornada','dzień pracy'),
('Partes del Día','Pory dnia','el reloj','zegar'),
('Partes del Día','Pory dnia','la hora','godzina'),
('Partes del Día','Pory dnia','el minuto','minuta'),
('Partes del Día','Pory dnia','el segundo','sekunda'),
('Partes del Día','Pory dnia','el instante','chwila / moment'),
('Partes del Día','Pory dnia','el rato','chwila (krótki czas)'),
('Partes del Día','Pory dnia','temprano','wcześnie'),
('Partes del Día','Pory dnia','tarde','późno'),
('Partes del Día','Pory dnia','puntual','punktualny'),
('Partes del Día','Pory dnia','el retraso','opóźnienie'),
('Partes del Día','Pory dnia','a tiempo','na czas'),
('Partes del Día','Pory dnia','la siesta','drzemka poobiednia'),
('Partes del Día','Pory dnia','el desayuno','śniadanie (pora)'),
('Partes del Día','Pory dnia','la comida','obiad (pora)'),
('Partes del Día','Pory dnia','la cena','kolacja (pora)'),
('Partes del Día','Pory dnia','despertarse','budzić się'),
('Partes del Día','Pory dnia','levantarse','wstawać'),
('Partes del Día','Pory dnia','acostarse','kłaść się spać'),
('Partes del Día','Pory dnia','trasnochar','zarywać noc'),
('Partes del Día','Pory dnia','madrugar','wstawać wcześnie rano'),
('Partes del Día','Pory dnia','el turno de mañana','poranna zmiana'),
('Partes del Día','Pory dnia','el turno de tarde','popołudniowa zmiana'),
('Partes del Día','Pory dnia','el turno de noche','nocna zmiana'),
('Partes del Día','Pory dnia','diario','codzienny'),
('Partes del Día','Pory dnia','nocturno','nocny'),
('Partes del Día','Pory dnia','matutino','poranny'),
('Partes del Día','Pory dnia','vespertino','popołudniowy / wieczorny'),
('Partes del Día','Pory dnia','24 horas / todo el día','całą dobę / cały dzień'),
('Días de la Semana','Dni tygodnia','el día de la semana','dzień tygodnia'),
('Días de la Semana','Dni tygodnia','el lunes','poniedziałek'),
('Días de la Semana','Dni tygodnia','el martes','wtorek'),
('Días de la Semana','Dni tygodnia','el miércoles','środa'),
('Días de la Semana','Dni tygodnia','el jueves','czwartek'),
('Días de la Semana','Dni tygodnia','el viernes','piątek'),
('Días de la Semana','Dni tygodnia','el sábado','sobota'),
('Días de la Semana','Dni tygodnia','el domingo','niedziela'),
('Días de la Semana','Dni tygodnia','el fin de semana','weekend'),
('Días de la Semana','Dni tygodnia','el día laborable / el día hábil','dzień roboczy'),
('Días de la Semana','Dni tygodnia','el día festivo','dzień świąteczny'),
('Días de la Semana','Dni tygodnia','el puente','długi weekend'),
('Días de la Semana','Dni tygodnia','ayer','wczoraj'),
('Días de la Semana','Dni tygodnia','hoy','dzisiaj'),
('Días de la Semana','Dni tygodnia','mañana','jutro'),
('Días de la Semana','Dni tygodnia','anteayer / antes de ayer','przedwczoraj'),
('Días de la Semana','Dni tygodnia','pasado mañana','pojutrze'),
('Días de la Semana','Dni tygodnia','el día anterior','poprzedni dzień'),
('Días de la Semana','Dni tygodnia','el día siguiente','następny dzień'),
('Días de la Semana','Dni tygodnia','todos los días','codziennie'),
('Días de la Semana','Dni tygodnia','cada lunes','w każdy poniedziałek'),
('Días de la Semana','Dni tygodnia','el próximo lunes','w przyszły poniedziałek'),
('Días de la Semana','Dni tygodnia','el lunes pasado','w zeszły poniedziałek'),
('Días de la Semana','Dni tygodnia','a mediados de semana','w środku tygodnia'),
('Días de la Semana','Dni tygodnia','el calendario','kalendarz'),
('Días de la Semana','Dni tygodnia','la semana','tydzień'),
('Días de la Semana','Dni tygodnia','la semana que viene','przyszły tydzień'),
('Días de la Semana','Dni tygodnia','la semana pasada','zeszły tydzień'),
('Días de la Semana','Dni tygodnia','una quincena','dwa tygodnie'),
('Días de la Semana','Dni tygodnia','semanal','tygodniowy'),
('Días de la Semana','Dni tygodnia','el horario','harmonogram / plan lekcji'),
('Días de la Semana','Dni tygodnia','la agenda','terminarz / kalendarz'),
('Días de la Semana','Dni tygodnia','la fecha','data'),
('Días de la Semana','Dni tygodnia','¿Qué día es hoy?','Jaki dziś dzień?'),
('Días de la Semana','Dni tygodnia','trabajar','pracować'),
('Días de la Semana','Dni tygodnia','descansar','odpoczywać'),
('Días de la Semana','Dni tygodnia','la rutina','rutyna'),
('Días de la Semana','Dni tygodnia','el festivo','święto'),
('Días de la Semana','Dni tygodnia','de lunes a viernes','od poniedziałku do piątku'),
('Días de la Semana','Dni tygodnia','entre semana','w dni robocze / w tygodniu'),
('Días de la Semana','Dni tygodnia','el puente festivo','długi weekend świąteczny'),
('Días de la Semana','Dni tygodnia','librar','mieć dzień wolny'),
('Días de la Semana','Dni tygodnia','el día libre','dzień wolny'),
('Días de la Semana','Dni tygodnia','semanalmente','co tydzień'),
('Días de la Semana','Dni tygodnia','el inicio de semana','początek tygodnia'),
('Días de la Semana','Dni tygodnia','el fin de mes','koniec miesiąca'),
('Días de la Semana','Dni tygodnia','la jornada laboral','dzień pracy'),
('Días de la Semana','Dni tygodnia','bisemanal','dwutygodniowy'),
('Días de la Semana','Dni tygodnia','cada semana','każdego tygodnia'),
('Días de la Semana','Dni tygodnia','diariamente','codziennie'),
('Meses del Año','Miesiące','el mes','miesiąc'),
('Meses del Año','Miesiące','enero','styczeń'),
('Meses del Año','Miesiące','febrero','luty'),
('Meses del Año','Miesiące','marzo','marzec'),
('Meses del Año','Miesiące','abril','kwiecień'),
('Meses del Año','Miesiące','mayo','maj'),
('Meses del Año','Miesiące','junio','czerwiec'),
('Meses del Año','Miesiące','julio','lipiec'),
('Meses del Año','Miesiące','agosto','sierpień'),
('Meses del Año','Miesiące','septiembre','wrzesień'),
('Meses del Año','Miesiące','octubre','październik'),
('Meses del Año','Miesiące','noviembre','listopad'),
('Meses del Año','Miesiące','diciembre','grudzień'),
('Meses del Año','Miesiące','el año','rok'),
('Meses del Año','Miesiące','el año bisiesto','rok przestępny'),
('Meses del Año','Miesiące','a principios de','na początku'),
('Meses del Año','Miesiące','a mediados de','w połowie'),
('Meses del Año','Miesiące','a finales de','pod koniec'),
('Meses del Año','Miesiące','el próximo mes','w przyszłym miesiącu'),
('Meses del Año','Miesiące','el mes pasado','w zeszłym miesiącu'),
('Meses del Año','Miesiące','mensual','miesięczny'),
('Meses del Año','Miesiące','mensualmente','co miesiąc'),
('Meses del Año','Miesiące','el trimestre','kwartał'),
('Meses del Año','Miesiące','el semestre','półrocze'),
('Meses del Año','Miesiące','la temporada','sezon'),
('Meses del Año','Miesiące','el aniversario','rocznica'),
('Meses del Año','Miesiące','anual','roczny'),
('Meses del Año','Miesiące','anualmente','corocznie'),
('Meses del Año','Miesiące','el año que viene','w przyszłym roku'),
('Meses del Año','Miesiące','el año pasado','w zeszłym roku'),
('Meses del Año','Miesiące','la década','dekada'),
('Meses del Año','Miesiące','el siglo','wiek / stulecie'),
('Meses del Año','Miesiące','el milenio','tysiąclecie'),
('Meses del Año','Miesiące','el calendario','kalendarz'),
('Meses del Año','Miesiące','bimensual','dwumiesięczny'),
('Meses del Año','Miesiące','trimestral','kwartalny'),
('Meses del Año','Miesiące','semestral','półroczny'),
('Meses del Año','Miesiące','el fin de año','koniec roku / sylwester'),
('Meses del Año','Miesiące','el comienzo de año','początek roku'),
('Meses del Año','Miesiące','la fecha de nacimiento','data urodzenia'),
('Meses del Año','Miesiące','caducar','wygasać / tracić ważność'),
('Meses del Año','Miesiące','la fecha de caducidad','data ważności'),
('Meses del Año','Miesiące','enero cuesta arriba','styczniowa bieda / ciężki styczeń'),
('Meses del Año','Miesiące','en enero','w styczniu'),
('Meses del Año','Miesiące','desde febrero','od lutego'),
('Meses del Año','Miesiące','hasta marzo','do marca'),
('Meses del Año','Miesiące','cada mes','każdego miesiąca'),
('Meses del Año','Miesiące','un par de meses','kilka miesięcy'),
('Meses del Año','Miesiące','hace un mes','miesiąc temu'),
('Meses del Año','Miesiące','dentro de un mes','za miesiąc'),
('Las Estaciones','Pory roku','la estación','pora roku'),
('Las Estaciones','Pory roku','la primavera','wiosna'),
('Las Estaciones','Pory roku','el verano','lato'),
('Las Estaciones','Pory roku','el otoño','jesień'),
('Las Estaciones','Pory roku','el invierno','zima'),
('Las Estaciones','Pory roku','primaveral','wiosenny'),
('Las Estaciones','Pory roku','veraniego','letni'),
('Las Estaciones','Pory roku','otoñal','jesienny'),
('Las Estaciones','Pory roku','invernal','zimowy'),
('Las Estaciones','Pory roku','la temporada alta','wysoki sezon'),
('Las Estaciones','Pory roku','la temporada baja','niski sezon'),
('Las Estaciones','Pory roku','el clima','klimat'),
('Las Estaciones','Pory roku','el tiempo','pogoda / czas'),
('Las Estaciones','Pory roku','el cambio de estación','zmiana pory roku'),
('Las Estaciones','Pory roku','las vacaciones de verano','wakacje letnie'),
('Las Estaciones','Pory roku','las vacaciones de invierno','ferie zimowe'),
('Las Estaciones','Pory roku','la temperatura','temperatura'),
('Las Estaciones','Pory roku','el calor','upał'),
('Las Estaciones','Pory roku','el frío','zimno'),
('Las Estaciones','Pory roku','la nieve','śnieg'),
('Las Estaciones','Pory roku','la lluvia','deszcz'),
('Las Estaciones','Pory roku','el viento','wiatr'),
('Las Estaciones','Pory roku','el sol','słońce'),
('Las Estaciones','Pory roku','florecer','kwitnąć'),
('Las Estaciones','Pory roku','la flor','kwiat'),
('Las Estaciones','Pory roku','la hoja','liść'),
('Las Estaciones','Pory roku','caer las hojas','opadać (o liściach)'),
('Las Estaciones','Pory roku','nevar','padać śnieg'),
('Las Estaciones','Pory roku','llover','padać deszcz'),
('Las Estaciones','Pory roku','helar','zamarzać / mrozić'),
('Las Estaciones','Pory roku','el deshielo','odwilż'),
('Las Estaciones','Pory roku','la ola de calor','fala upałów'),
('Las Estaciones','Pory roku','la ola de frío','fala mrozów'),
('Las Estaciones','Pory roku','el solsticio','przesilenie'),
('Las Estaciones','Pory roku','el equinoccio','równonoc'),
('Las Estaciones','Pory roku','al aire libre','na świeżym powietrzu'),
('Las Estaciones','Pory roku','tomar el sol','opalać się'),
('Las Estaciones','Pory roku','esquiar','jeździć na nartach'),
('Las Estaciones','Pory roku','la cosecha','żniwa / zbiory'),
('Las Estaciones','Pory roku','la vendimia','winobranie'),
('Las Estaciones','Pory roku','el abrigo','płaszcz'),
('Las Estaciones','Pory roku','el traje de baño','strój kąpielowy'),
('Las Estaciones','Pory roku','las gafas de sol','okulary przeciwsłoneczne'),
('Las Estaciones','Pory roku','la bufanda','szalik'),
('Las Estaciones','Pory roku','el paraguas','parasol'),
('Las Estaciones','Pory roku','broncearse','opalać się (pokryć brązem)'),
('Las Estaciones','Pory roku','tiritar','trząść się z zimna'),
('Las Estaciones','Pory roku','sudar','pocić się'),
('Las Estaciones','Pory roku','refrescar','ochładzać się / odświeżać'),
('Las Estaciones','Pory roku','el clima tropical','klimat tropikalny'),
('Adverbios de Tiempo','Przysłówki czasu','ahora','teraz'),
('Adverbios de Tiempo','Przysłówki czasu','antes','wcześniej / przedtem'),
('Adverbios de Tiempo','Przysłówki czasu','después','potem / później'),
('Adverbios de Tiempo','Przysłówki czasu','luego','następnie / później'),
('Adverbios de Tiempo','Przysłówki czasu','hoy','dzisiaj'),
('Adverbios de Tiempo','Przysłówki czasu','mañana','jutro'),
('Adverbios de Tiempo','Przysłówki czasu','ayer','wczoraj'),
('Adverbios de Tiempo','Przysłówki czasu','pronto','wkrótce / niedługo'),
('Adverbios de Tiempo','Przysłówki czasu','tarde','późno'),
('Adverbios de Tiempo','Przysłówki czasu','temprano','wcześnie'),
('Adverbios de Tiempo','Przysłówki czasu','siempre','zawsze'),
('Adverbios de Tiempo','Przysłówki czasu','nunca','nigdy'),
('Adverbios de Tiempo','Przysłówki czasu','jamás','nigdy w życiu'),
('Adverbios de Tiempo','Przysłówki czasu','a veces','czasami'),
('Adverbios de Tiempo','Przysłówki czasu','ya','już'),
('Adverbios de Tiempo','Przysłówki czasu','todavía','jeszcze (ciągle)'),
('Adverbios de Tiempo','Przysłówki czasu','aún','jeszcze / mimo to'),
('Adverbios de Tiempo','Przysłówki czasu','enseguida','natychmiast / zaraz'),
('Adverbios de Tiempo','Przysłówki czasu','inmediatamente','natychmiast'),
('Adverbios de Tiempo','Przysłówki czasu','mientras','podczas gdy / dopóki'),
('Adverbios de Tiempo','Przysłówki czasu','mientras tanto','w międzyczasie'),
('Adverbios de Tiempo','Przysłówki czasu','de repente','nagle'),
('Adverbios de Tiempo','Przysłówki czasu','de pronto','nagle (nieoczekiwanie)'),
('Adverbios de Tiempo','Przysłówki czasu','frecuentemente','często'),
('Adverbios de Tiempo','Przysłówki czasu','a menudo','często (gęsto)'),
('Adverbios de Tiempo','Przysłówki czasu','raramente','rzadko'),
('Adverbios de Tiempo','Przysłówki czasu','rara vez','rzadka (bardzo rzadko)'),
('Adverbios de Tiempo','Przysłówki czasu','de vez en cuando','od czasu do czasu'),
('Adverbios de Tiempo','Przysłówki czasu','recientemente','ostatnio (niedawno)'),
('Adverbios de Tiempo','Przysłówki czasu','últimamente','ostatnio (w ostatnim czasie)'),
('Adverbios de Tiempo','Przysłówki czasu','actualmente','obecnie'),
('Adverbios de Tiempo','Przysłówki czasu','constantemente','stale / ciągle'),
('Adverbios de Tiempo','Przysłówki czasu','en este momento','w tym momencie'),
('Adverbios de Tiempo','Przysłówki czasu','al instante','w tej chwili'),
('Adverbios de Tiempo','Przysłówki czasu','a tiempo','na czas'),
('Adverbios de Tiempo','Przysłówki czasu','con tiempo','z wyprzedzeniem'),
('Adverbios de Tiempo','Przysłówki czasu','tarde o temprano','prędzej czy później'),
('Adverbios de Tiempo','Przysłówki czasu','antes de ayer','przedwczoraj'),
('Adverbios de Tiempo','Przysłówki czasu','de día','w dzień'),
('Adverbios de Tiempo','Przysłówki czasu','de noche','w nocy'),
('Adverbios de Tiempo','Przysłówki czasu','al principio','na początku'),
('Adverbios de Tiempo','Przysłówki czasu','al final','na końcu'),
('Adverbios de Tiempo','Przysłówki czasu','finalmente','w końcu / ostatecznie'),
('Adverbios de Tiempo','Przysłówki czasu','previamente','poprzednio / wcześniej'),
('Adverbios de Tiempo','Przysłówki czasu','cotidianamente','codziennie'),
('Adverbios de Tiempo','Przysłówki czasu','apenas','ledwie / dopiero co'),
('Adverbios de Tiempo','Przysłówki czasu','recién','dopiero co (Ameryka Łac.)'),
('Adverbios de Tiempo','Przysłówki czasu','jamás de los jamases','nigdy przenigdy'),
('Adverbios de Tiempo','Przysłówki czasu','en un rato','za chwilę'),
('Adverbios de Tiempo','Przysłówki czasu','hace poco','niedawno'),
('Adverbios de Lugar','Przysłówki miejsca','aquí','tutaj'),
('Adverbios de Lugar','Przysłówki miejsca','ahí','tam (blisko)'),
('Adverbios de Lugar','Przysłówki miejsca','allí','tam (daleko)'),
('Adverbios de Lugar','Przysłówki miejsca','allá','tam (bardzo daleko/ogólnie)'),
('Adverbios de Lugar','Przysłówki miejsca','acá','tutaj (Ameryka Łac. / w tym kierunku)'),
('Adverbios de Lugar','Przysłówki miejsca','cerca','blisko'),
('Adverbios de Lugar','Przysłówki miejsca','lejos','daleko'),
('Adverbios de Lugar','Przysłówki miejsca','arriba','w górze / na górze'),
('Adverbios de Lugar','Przysłówki miejsca','abajo','w dole / na dole'),
('Adverbios de Lugar','Przysłówki miejsca','delante','z przodu / przed'),
('Adverbios de Lugar','Przysłówki miejsca','detrás','z tyłu / za'),
('Adverbios de Lugar','Przysłówki miejsca','encima','na (powierzchni) / nad'),
('Adverbios de Lugar','Przysłówki miejsca','debajo','pod / pod spodem'),
('Adverbios de Lugar','Przysłówki miejsca','dentro','w środku / wewnątrz'),
('Adverbios de Lugar','Przysłówki miejsca','fuera','na zewnątrz'),
('Adverbios de Lugar','Przysłówki miejsca','adentro','do środka / wewnątrz'),
('Adverbios de Lugar','Przysłówki miejsca','afuera','na zewnątrz / dwór'),
('Adverbios de Lugar','Przysłówki miejsca','alrededor','dookoła / wokół'),
('Adverbios de Lugar','Przysłówki miejsca','junto','razem / obok'),
('Adverbios de Lugar','Przysłówki miejsca','al lado','obok'),
('Adverbios de Lugar','Przysłówki miejsca','enfrente','naprzeciwko'),
('Adverbios de Lugar','Przysłówki miejsca','atrás','w tył / z tyłu'),
('Adverbios de Lugar','Przysłówki miejsca','adelante','naprzód / z przodu'),
('Adverbios de Lugar','Przysłówki miejsca','donde','gdzie'),
('Adverbios de Lugar','Przysłówki miejsca','adonde','dokąd'),
('Adverbios de Lugar','Przysłówki miejsca','por donde','tędy / którędy'),
('Adverbios de Lugar','Przysłówki miejsca','hacia acá','w tę stronę'),
('Adverbios de Lugar','Przysłówki miejsca','hacia allá','w tamtą stronę'),
('Adverbios de Lugar','Przysłówki miejsca','en cualquier lugar / en cualquier sitio','gdziekolwiek'),
('Adverbios de Lugar','Przysłówki miejsca','en ningún lugar / en ningún sitio','nigdzie'),
('Adverbios de Lugar','Przysłówki miejsca','en todas partes','wszędzie'),
('Adverbios de Lugar','Przysłówki miejsca','en otra parte','gdzie indziej'),
('Adverbios de Lugar','Przysłówki miejsca','en alguna parte','gdzieś'),
('Adverbios de Lugar','Przysłówki miejsca','más allá','dalej / poza'),
('Adverbios de Lugar','Przysłówki miejsca','a la derecha','na prawo / po prawej'),
('Adverbios de Lugar','Przysłówki miejsca','a la izquierda','na lewo / po lewej'),
('Adverbios de Lugar','Przysłówki miejsca','recto / derecho','prosto'),
('Adverbios de Lugar','Przysłówki miejsca','en medio','pośrodku'),
('Adverbios de Lugar','Przysłówki miejsca','por aquí','tędy (blisko)'),
('Adverbios de Lugar','Przysłówki miejsca','por allí','tamtędy (daleko)'),
('Adverbios de Lugar','Przysłówki miejsca','en el fondo','w głębi / na dnie'),
('Adverbios de Lugar','Przysłówki miejsca','a lo lejos','w dali'),
('Adverbios de Lugar','Przysłówki miejsca','en lo alto','na wysokości / na szczycie'),
('Adverbios de Lugar','Przysłówki miejsca','boca arriba','na plecach (twarzą do góry)'),
('Adverbios de Lugar','Przysłówki miejsca','boca abajo','na brzuchu (twarzą w dół)'),
('Adverbios de Lugar','Przysłówki miejsca','por doquier','wszędzie (lit.)'),
('Adverbios de Lugar','Przysłówki miejsca','intramuros','w obrębie murów'),
('Adverbios de Lugar','Przysłówki miejsca','extramuros','poza murami'),
('Adverbios de Lugar','Przysłówki miejsca','en casa','w domu'),
('Adverbios de Lugar','Przysłówki miejsca','fuera de casa','poza domem'),
('Adverbios de Modo','Przysłówki sposobu','así','tak / w ten sposób'),
('Adverbios de Modo','Przysłówki sposobu','bien','dobrze'),
('Adverbios de Modo','Przysłówki sposobu','mal','źle'),
('Adverbios de Modo','Przysłówki sposobu','mejor','lepiej'),
('Adverbios de Modo','Przysłówki sposobu','peor','gorzej'),
('Adverbios de Modo','Przysłówki sposobu','despacio','wolno / powoli'),
('Adverbios de Modo','Przysłówki sposobu','rápido','szybko'),
('Adverbios de Modo','Przysłówki sposobu','lentamente','powoli'),
('Adverbios de Modo','Przysłówki sposobu','rápidamente','szybko'),
('Adverbios de Modo','Przysłówki sposobu','fácilmente','łatwo'),
('Adverbios de Modo','Przysłówki sposobu','difícilmente','z trudem / trudno'),
('Adverbios de Modo','Przysłówki sposobu','felizmente','szczęśliwie'),
('Adverbios de Modo','Przysłówki sposobu','tristemente','smutnie'),
('Adverbios de Modo','Przysłówki sposobu','claramente','jasno / wyraźnie'),
('Adverbios de Modo','Przysłówki sposobu','oscuro','ciemno'),
('Adverbios de Modo','Przysłówki sposobu','suavemente','delikatnie / miękko'),
('Adverbios de Modo','Przysłówki sposobu','fuertemente','mocno'),
('Adverbios de Modo','Przysłówki sposobu','duro','ciężko / twardo'),
('Adverbios de Modo','Przysłówki sposobu','aprisa','śpiesznie / prędko'),
('Adverbios de Modo','Przysłówki sposobu','aposta / adrede','celowo / specjalnie'),
('Adverbios de Modo','Przysłówki sposobu','sin querer','niechcący'),
('Adverbios de Modo','Przysłówki sposobu','a propósito','celowo / przy okazji'),
('Adverbios de Modo','Przysłówki sposobu','en voz alta','na głos'),
('Adverbios de Modo','Przysłówki sposobu','en voz baja','szeptem / po cichu'),
('Adverbios de Modo','Przysłówki sposobu','de memoria','na pamięć'),
('Adverbios de Modo','Przysłówki sposobu','a ciegas','na oślep'),
('Adverbios de Modo','Przysłówki sposobu','a escondidas','w ukryciu / potajemnie'),
('Adverbios de Modo','Przysłówki sposobu','de repente / de golpe','nagle / jednym ruchem'),
('Adverbios de Modo','Przysłówki sposobu','casi','prawie'),
('Adverbios de Modo','Przysłówki sposobu','apenas','ledwie'),
('Adverbios de Modo','Przysłówki sposobu','completamente','całkowicie'),
('Adverbios de Modo','Przysłówki sposobu','parcialmente','częściowo'),
('Adverbios de Modo','Przysłówki sposobu','totalmente','zupełnie / totalnie'),
('Adverbios de Modo','Przysłówki sposobu','absolutamente','absolutnie'),
('Adverbios de Modo','Przysłówki sposobu','exactamente','dokładnie'),
('Adverbios de Modo','Przysłówki sposobu','justamente','właśnie / dokładnie'),
('Adverbios de Modo','Przysłówki sposobu','estupendamente','wspaniale'),
('Adverbios de Modo','Przysłówki sposobu','terriblemente','okropnie'),
('Adverbios de Modo','Przysłówki sposobu','naturalmente','naturalnie'),
('Adverbios de Modo','Przysłówki sposobu','seguramente','pewnie / na pewno'),
('Adverbios de Modo','Przysłówki sposobu','probablemente','prawdopodobnie'),
('Adverbios de Modo','Przysłówki sposobu','posiblemente','możliwe'),
('Adverbios de Modo','Przysłówki sposobu','igual','tak samo / równo'),
('Adverbios de Modo','Przysłówki sposobu','diferente / distinto','inaczej'),
('Adverbios de Modo','Przysłówki sposobu','gratis','za darmo'),
('Adverbios de Modo','Przysłówki sposobu','solo / solamente','tylko'),
('Adverbios de Modo','Przysłówki sposobu','únicamente','wyłącznie'),
('Adverbios de Modo','Przysłówki sposobu','exclusivamente','wyłącznie'),
('Adverbios de Modo','Przysłówki sposobu','a medias','w połowie / niedokładnie'),
('Adverbios de Modo','Przysłówki sposobu','de maravilla','cudownie / świetnie'),
('Preposiciones','Przyimki','a','do / na / w (kierunek, czas)'),
('Preposiciones','Przyimki','ante','wobec / przed (np. sądem)'),
('Preposiciones','Przyimki','bajo','pod'),
('Preposiciones','Przyimki','cabe','obok (archaiczne)'),
('Preposiciones','Przyimki','con','z'),
('Preposiciones','Przyimki','contra','przeciw / przeciwko'),
('Preposiciones','Przyimki','de','z / od / o (kogoś/czegoś)'),
('Preposiciones','Przyimki','desde','od (czas/miejsce)'),
('Preposiciones','Przyimki','durante','podczas'),
('Preposiciones','Przyimki','en','w / na'),
('Preposiciones','Przyimki','entre','między / pomiędzy'),
('Preposiciones','Przyimki','hacia','w kierunku / ku'),
('Preposiciones','Przyimki','hasta','do / aż do'),
('Preposiciones','Przyimki','mediante','za pomocą / poprzez'),
('Preposiciones','Przyimki','para','dla / żeby'),
('Preposiciones','Przyimki','por','przez / za / dla'),
('Preposiciones','Przyimki','según','według / zgodnie z'),
('Preposiciones','Przyimki','sin','bez'),
('Preposiciones','Przyimki','so','pod (archaiczne)'),
('Preposiciones','Przyimki','sobre','na / o (temat)'),
('Preposiciones','Przyimki','tras','za / po'),
('Preposiciones','Przyimki','versus','kontra / przeciwko'),
('Preposiciones','Przyimki','vía','przez (trasę)'),
('Preposiciones','Przyimki','acerca de','na temat / o'),
('Preposiciones','Przyimki','además de','oprócz'),
('Preposiciones','Przyimki','alrededor de','wokół'),
('Preposiciones','Przyimki','antes de','przed (czas)'),
('Preposiciones','Przyimki','a pesar de','pomimo'),
('Preposiciones','Przyimki','cerca de','blisko'),
('Preposiciones','Przyimki','con respecto a','w odniesieniu do'),
('Preposiciones','Przyimki','debajo de','pod (pod spodem)'),
('Preposiciones','Przyimki','delante de','przed (miejsce)'),
('Preposiciones','Przyimki','dentro de','wewnątrz / w (czas)'),
('Preposiciones','Przyimki','después de','po (czas)'),
('Preposiciones','Przyimki','detrás de','za (miejsce)'),
('Preposiciones','Przyimki','en contra de','przeciwko'),
('Preposiciones','Przyimki','en medio de','w środku / pomiędzy'),
('Preposiciones','Przyimki','en lugar de','zamiast'),
('Preposiciones','Przyimki','en vez de','zamiast'),
('Preposiciones','Przyimki','encima de','nad / na'),
('Preposiciones','Przyimki','frente a','naprzeciwko / wobec'),
('Preposiciones','Przyimki','fuera de','poza'),
('Preposiciones','Przyimki','gracias a','dzięki'),
('Preposiciones','Przyimki','junto a','obok'),
('Preposiciones','Przyimki','lejos de','daleko od'),
('Preposiciones','Przyimki','por causa de','z powodu'),
('Preposiciones','Przyimki','por culpa de','przez (z winy)'),
('Preposiciones','Przyimki','a través de','poprzez'),
('Preposiciones','Przyimki','con el fin de','w celu'),
('Preposiciones','Przyimki','a favor de','na rzecz / za'),
('Conjunciones','Spójniki','y','i / oraz'),
('Conjunciones','Spójniki','e','i / oraz (przed wyrazem na i/hi)'),
('Conjunciones','Spójniki','ni','ani'),
('Conjunciones','Spójniki','que','że / który'),
('Conjunciones','Spójniki','o','albo / lub'),
('Conjunciones','Spójniki','u','albo / lub (przed wyrazem na o/ho)'),
('Conjunciones','Spójniki','pero','ale'),
('Conjunciones','Spójniki','mas','lecz / ale (literackie)'),
('Conjunciones','Spójniki','sino','lecz (po przeczeniu)'),
('Conjunciones','Spójniki','porque','ponieważ / bo'),
('Conjunciones','Spójniki','pues','zatem / bo'),
('Conjunciones','Spójniki','ya que','skoro / jako że'),
('Conjunciones','Spójniki','puesto que','ponieważ / skoro'),
('Conjunciones','Spójniki','dado que','zważywszy że'),
('Conjunciones','Spójniki','como','jako / ponieważ / jak'),
('Conjunciones','Spójniki','si','jeśli / czy'),
('Conjunciones','Spójniki','siempre que','zawsze gdy / pod warunkiem że'),
('Conjunciones','Spójniki','con tal (de) que','pod warunkiem że'),
('Conjunciones','Spójniki','a condición de que','pod warunkiem że'),
('Conjunciones','Spójniki','aunque','chociaż / mimo że'),
('Conjunciones','Spójniki','a pesar de que','pomimo że'),
('Conjunciones','Spójniki','aun cuando','nawet jeśli'),
('Conjunciones','Spójniki','por más que','nie ważne jak / chociaż'),
('Conjunciones','Spójniki','para que','aby / żeby'),
('Conjunciones','Spójniki','a fin de que','w tym celu żeby'),
('Conjunciones','Spójniki','luego','więc / toteż'),
('Conjunciones','Spójniki','conque','a więc / wobec tego'),
('Conjunciones','Spójniki','así que','więc / tak więc'),
('Conjunciones','Spójniki','por lo tanto','dlatego też'),
('Conjunciones','Spójniki','por consiguiente','w konsekwencji'),
('Conjunciones','Spójniki','sea... sea','czy to... czy to'),
('Conjunciones','Spójniki','ya... ya','raz... raz'),
('Conjunciones','Spójniki','bien... bien','albo... albo'),
('Conjunciones','Spójniki','mientras','podczas gdy'),
('Conjunciones','Spójniki','cuando','kiedy / gdy'),
('Conjunciones','Spójniki','antes de que','zanim'),
('Conjunciones','Spójniki','después de que','po tym jak'),
('Conjunciones','Spójniki','hasta que','aż / dopóki no'),
('Conjunciones','Spójniki','desde que','odkąd'),
('Conjunciones','Spójniki','luego que','skoro tylko'),
('Conjunciones','Spójniki','tan pronto como','jak tylko'),
('Conjunciones','Spójniki','apenas','zaledwie'),
('Conjunciones','Spójniki','es decir','to znaczy'),
('Conjunciones','Spójniki','o sea','czyli / to znaczy'),
('Conjunciones','Spójniki','esto es','to jest'),
('Conjunciones','Spójniki','sin embargo','jednakże / mimo to'),
('Conjunciones','Spójniki','no obstante','niemniej jednak'),
('Conjunciones','Spójniki','salvo','z wyjątkiem'),
('Conjunciones','Spójniki','excepto','oprócz / wyjąwszy'),
('Conjunciones','Spójniki','además','ponadto'),
('Pronombres','Zaimki','yo','ja'),
('Pronombres','Zaimki','tú','ty'),
('Pronombres','Zaimki','él','on'),
('Pronombres','Zaimki','ella','ona'),
('Pronombres','Zaimki','usted','pan / pani'),
('Pronombres','Zaimki','nosotros','my (mężczyźni/mieszane)'),
('Pronombres','Zaimki','nosotras','my (kobiety)'),
('Pronombres','Zaimki','vosotros','wy (mężczyźni/mieszane - Hiszpania)'),
('Pronombres','Zaimki','vosotras','wy (kobiety - Hiszpania)'),
('Pronombres','Zaimki','ellos','oni'),
('Pronombres','Zaimki','ellas','one'),
('Pronombres','Zaimki','ustedes','państwo (wy)'),
('Pronombres','Zaimki','me','mi / mnie'),
('Pronombres','Zaimki','te','ci / ciebie'),
('Pronombres','Zaimki','le','jemu / jej / panu (celownik)'),
('Pronombres','Zaimki','lo','go / jego / to (biernik)'),
('Pronombres','Zaimki','la','ją (biernik)'),
('Pronombres','Zaimki','nos','nam / nas'),
('Pronombres','Zaimki','os','wam / was'),
('Pronombres','Zaimki','les','im / państwu (celownik)'),
('Pronombres','Zaimki','los','ich (biernik r.m.)'),
('Pronombres','Zaimki','las','je (biernik r.ż.)'),
('Pronombres','Zaimki','se','się / sobie'),
('Pronombres','Zaimki','mí','mnie (po przyimku)'),
('Pronombres','Zaimki','ti','tobie (po przyimku)'),
('Pronombres','Zaimki','sí','sobie / nim (po przyimku)'),
('Pronombres','Zaimki','conmigo','ze mną'),
('Pronombres','Zaimki','contigo','z tobą'),
('Pronombres','Zaimki','consigo','z nim / ze sobą'),
('Pronombres','Zaimki','mío / mía','mój / moja'),
('Pronombres','Zaimki','tuyo / tuya','twój / twoja'),
('Pronombres','Zaimki','suyo / suya','jego / jej / ich'),
('Pronombres','Zaimki','nuestro / nuestra','nasz / nasza'),
('Pronombres','Zaimki','vuestro / vuestra','wasz / wasza'),
('Pronombres','Zaimki','este','ten'),
('Pronombres','Zaimki','esta','ta'),
('Pronombres','Zaimki','esto','to'),
('Pronombres','Zaimki','ese','tamten'),
('Pronombres','Zaimki','esa','tamta'),
('Pronombres','Zaimki','eso','tamto'),
('Pronombres','Zaimki','aquel','ów (daleki)'),
('Pronombres','Zaimki','aquella','owa (daleka)'),
('Pronombres','Zaimki','aquello','owo (dalekie)'),
('Pronombres','Zaimki','quien','kto / ten, kto'),
('Pronombres','Zaimki','quienes','którzy / ci, którzy'),
('Pronombres','Zaimki','que','który / co'),
('Pronombres','Zaimki','cual','który / jaki'),
('Pronombres','Zaimki','cuales','które / jacy'),
('Pronombres','Zaimki','alguien','ktoś'),
('Pronombres','Zaimki','nadie','nikt'),
('Verbos Regulares AR','Czasowniki regularne AR','hablar','mówić / rozmawiać'),
('Verbos Regulares AR','Czasowniki regularne AR','trabajar','pracować'),
('Verbos Regulares AR','Czasowniki regularne AR','estudiar','uczyć się / studiować'),
('Verbos Regulares AR','Czasowniki regularne AR','amar','kochać'),
('Verbos Regulares AR','Czasowniki regularne AR','viajar','podróżować'),
('Verbos Regulares AR','Czasowniki regularne AR','cantar','śpiewać'),
('Verbos Regulares AR','Czasowniki regularne AR','bailar','tańczyć'),
('Verbos Regulares AR','Czasowniki regularne AR','escuchar','słuchać'),
('Verbos Regulares AR','Czasowniki regularne AR','mirar','patrzeć'),
('Verbos Regulares AR','Czasowniki regularne AR','comprar','kupować'),
('Verbos Regulares AR','Czasowniki regularne AR','pagar','płacić'),
('Verbos Regulares AR','Czasowniki regularne AR','tomar','brać / pić'),
('Verbos Regulares AR','Czasowniki regularne AR','llevar','nieść / nosić'),
('Verbos Regulares AR','Czasowniki regularne AR','dejar','zostawiać / pozwalać'),
('Verbos Regulares AR','Czasowniki regularne AR','ayudar','pomagać'),
('Verbos Regulares AR','Czasowniki regularne AR','preparar','przygotowywać'),
('Verbos Regulares AR','Czasowniki regularne AR','cocinar','gotować'),
('Verbos Regulares AR','Czasowniki regularne AR','entrar','wchodzić'),
('Verbos Regulares AR','Czasowniki regularne AR','llegar','przybierać / docierać'),
('Verbos Regulares AR','Czasowniki regularne AR','pasar','spędzać / mijać'),
('Verbos Regulares AR','Czasowniki regularne AR','mandar','wysyłać / rozkazywać'),
('Verbos Regulares AR','Czasowniki regularne AR','preguntar','pytać'),
('Verbos Regulares AR','Czasowniki regularne AR','contestar','odpowiadać'),
('Verbos Regulares AR','Czasowniki regularne AR','necesitar','potrzebować'),
('Verbos Regulares AR','Czasowniki regularne AR','usar','używać'),
('Verbos Regulares AR','Czasowniki regularne AR','explicar','wyjaśniać'),
('Verbos Regulares AR','Czasowniki regularne AR','ganar','wygrywać / zarabiać'),
('Verbos Regulares AR','Czasowniki regularne AR','llorar','płakać'),
('Verbos Regulares AR','Czasowniki regularne AR','nadar','pływać'),
('Verbos Regulares AR','Czasowniki regularne AR','caminar','spacerować / chodzić'),
('Verbos Regulares AR','Czasowniki regularne AR','descansar','odpoczywać'),
('Verbos Regulares AR','Czasowniki regularne AR','terminar','kończyć'),
('Verbos Regulares AR','Czasowniki regularne AR','olvidar','zapominać'),
('Verbos Regulares AR','Czasowniki regularne AR','pintar','malować'),
('Verbos Regulares AR','Czasowniki regularne AR','limpiar','sprzątać / czyścić'),
('Verbos Regulares AR','Czasowniki regularne AR','lavar','myć / prać'),
('Verbos Regulares AR','Czasowniki regularne AR','desayunar','jeść śniadanie'),
('Verbos Regulares AR','Czasowniki regularne AR','cenar','jeść kolację'),
('Verbos Regulares AR','Czasowniki regularne AR','saludar','pozdrawiać / witać'),
('Verbos Regulares AR','Czasowniki regularne AR','invitar','zapraszać'),
('Verbos Regulares AR','Czasowniki regularne AR','arreglar','naprawiać / porządkować'),
('Verbos Regulares AR','Czasowniki regularne AR','buscar','szukać'),
('Verbos Regulares AR','Czasowniki regularne AR','aceptar','akceptować / przyjmować'),
('Verbos Regulares AR','Czasowniki regularne AR','acompañar','towarzyszyć'),
('Verbos Regulares AR','Czasowniki regularne AR','esperar','czekać / mieć nadzieję'),
('Verbos Regulares AR','Czasowniki regularne AR','llamar','dzwonić / wołać'),
('Verbos Regulares AR','Czasowniki regularne AR','cuidar','opiekować się / dbać'),
('Verbos Regulares AR','Czasowniki regularne AR','pasear','spacerować'),
('Verbos Regulares AR','Czasowniki regularne AR','tocar','dotykać / grać (na instrumencie)'),
('Verbos Regulares AR','Czasowniki regularne AR','bajar','schodzić / obniżać'),
('Verbos Regulares ER','Czasowniki regularne ER','comer','jeść'),
('Verbos Regulares ER','Czasowniki regularne ER','beber','pić'),
('Verbos Regulares ER','Czasowniki regularne ER','comprender','rozumieć (głęboko)'),
('Verbos Regulares ER','Czasowniki regularne ER','aprender','uczyć się (przyswajać)'),
('Verbos Regulares ER','Czasowniki regularne ER','leer','czytać'),
('Verbos Regulares ER','Czasowniki regularne ER','vender','sprzedawać'),
('Verbos Regulares ER','Czasowniki regularne ER','responder','odpowiadać'),
('Verbos Regulares ER','Czasowniki regularne ER','correr','biec / biegać'),
('Verbos Regulares ER','Czasowniki regularne ER','deber','musieć / mieć powinność'),
('Verbos Regulares ER','Czasowniki regularne ER','esconder','chować / ukrywać'),
('Verbos Regulares ER','Czasowniki regularne ER','prometer','obiecywać'),
('Verbos Regulares ER','Czasowniki regularne ER','creer','wierzyć / sądzić'),
('Verbos Regulares ER','Czasowniki regularne ER','romper','psuć / łamać / rwać'),
('Verbos Regulares ER','Czasowniki regularne ER','meter','wkładać'),
('Verbos Regulares ER','Czasowniki regularne ER','cometer','popełniać (np. błąd)'),
('Verbos Regulares ER','Czasowniki regularne ER','depender','zależeć'),
('Verbos Regulares ER','Czasowniki regularne ER','ofender','obrażać'),
('Verbos Regulares ER','Czasowniki regularne ER','proceder','postępować / pochodzić'),
('Verbos Regulares ER','Czasowniki regularne ER','suceder','dziać się / następować'),
('Verbos Regulares ER','Czasowniki regularne ER','toser','kasłać'),
('Verbos Regulares ER','Czasowniki regularne ER','tejer','tkać / robić na drutach'),
('Verbos Regulares ER','Czasowniki regularne ER','sorprender','zaskakiwać'),
('Verbos Regulares ER','Czasowniki regularne ER','emprender','podejmować (działanie)'),
('Verbos Regulares ER','Czasowniki regularne ER','barrer','zamiatać'),
('Verbos Regulares ER','Czasowniki regularne ER','pretender','zamierzać / pretendować'),
('Verbos Regulares ER','Czasowniki regularne ER','ceder','ustępować'),
('Verbos Regulares ER','Czasowniki regularne ER','conceder','przyznawać / udzielać'),
('Verbos Regulares ER','Czasowniki regularne ER','someter','poddawać (kogoś czemuś)'),
('Verbos Regulares ER','Czasowniki regularne ER','temer','bać się'),
('Verbos Regulares ER','Czasowniki regularne ER','poseer','posiadać'),
('Verbos Regulares ER','Czasowniki regularne ER','lamer','lizać'),
('Verbos Regulares ER','Czasowniki regularne ER','absorber','absorbować / wchłaniać'),
('Verbos Regulares ER','Czasowniki regularne ER','acceder','uzyskiwać dostęp / zgadzać się'),
('Verbos Regulares ER','Czasowniki regularne ER','anteceder','poprzedzać'),
('Verbos Regulares ER','Czasowniki regularne ER','expeler','wydalać / wyrzucać'),
('Verbos Regulares ER','Czasowniki regularne ER','repeler','odstręczać / odpychać'),
('Verbos Regulares ER','Czasowniki regularne ER','proveer','zaopatrywać'),
('Verbos Regulares ER','Czasowniki regularne ER','suspender','oblewać (egzamin) / zawieszać'),
('Verbos Regulares ER','Czasowniki regularne ER','coser','szyć'),
('Verbos Regulares ER','Czasowniki regularne ER','prender','zapalać (np. światło) / łapać'),
('Verbos Regulares ER','Czasowniki regularne ER','defender','bronić (zmienna samogłoska w niektórych czasach, ale reg. ER w strukturze)'),
('Verbos Regulares ER','Czasowniki regularne ER','encender','włączać / zapalać'),
('Verbos Regulares ER','Czasowniki regularne ER','entender','rozumieć'),
('Verbos Regulares ER','Czasowniki regularne ER','perder','gubić / tracić'),
('Verbos Regulares ER','Czasowniki regularne ER','atender','obsługiwać / uważać'),
('Verbos Regulares ER','Czasowniki regularne ER','extender','rozciągać / poszerzać'),
('Verbos Regulares ER','Czasowniki regularne ER','resolver','rozwiązywać'),
('Verbos Regulares ER','Czasowniki regularne ER','volver','wracać'),
('Verbos Regulares ER','Czasowniki regularne ER','devolver','zwracać (coś)'),
('Verbos Regulares ER','Czasowniki regularne ER','envolver','owijać / pakować'),
('Verbos Regulares IR','Czasowniki regularne IR','vivir','żyć / mieszkać'),
('Verbos Regulares IR','Czasowniki regularne IR','escribir','pisać'),
('Verbos Regulares IR','Czasowniki regularne IR','abrir','otwierać'),
('Verbos Regulares IR','Czasowniki regularne IR','recibir','otrzymywać'),
('Verbos Regulares IR','Czasowniki regularne IR','permitir','pozwalać'),
('Verbos Regulares IR','Czasowniki regularne IR','subir','wchodzić (do góry) / wsiadać'),
('Verbos Regulares IR','Czasowniki regularne IR','dividir','dzielić'),
('Verbos Regulares IR','Czasowniki regularne IR','decidir','decydować'),
('Verbos Regulares IR','Czasowniki regularne IR','descubrir','odkrywać'),
('Verbos Regulares IR','Czasowniki regularne IR','sufrir','cierpieć'),
('Verbos Regulares IR','Czasowniki regularne IR','existir','istnieć'),
('Verbos Regulares IR','Czasowniki regularne IR','añadir','dodawać'),
('Verbos Regulares IR','Czasowniki regularne IR','admitir','przyznawać / wpuszczać'),
('Verbos Regulares IR','Czasowniki regularne IR','describir','opisywać'),
('Verbos Regulares IR','Czasowniki regularne IR','ocurrir','wydarzyć się / dziać się'),
('Verbos Regulares IR','Czasowniki regularne IR','asistir','uczestniczyć / brać udział'),
('Verbos Regulares IR','Czasowniki regularne IR','definir','definiować'),
('Verbos Regulares IR','Czasowniki regularne IR','discutir','kłócić się / dyskutować'),
('Verbos Regulares IR','Czasowniki regularne IR','insistir','nalegać'),
('Verbos Regulares IR','Czasowniki regularne IR','partir','kroić / wyruszać'),
('Verbos Regulares IR','Czasowniki regularne IR','imprimir','drukować'),
('Verbos Regulares IR','Czasowniki regularne IR','prohibir','zabraniać'),
('Verbos Regulares IR','Czasowniki regularne IR','resumir','podsumowywać'),
('Verbos Regulares IR','Czasowniki regularne IR','unir','łączyć'),
('Verbos Regulares IR','Czasowniki regularne IR','asumir','zakładać / przejmować'),
('Verbos Regulares IR','Czasowniki regularne IR','compartir','dzielić się (czymś)'),
('Verbos Regulares IR','Czasowniki regularne IR','cumplir','spełniać / kończyć (lata)'),
('Verbos Regulares IR','Czasowniki regularne IR','batir','ubijać / bić (rekord)'),
('Verbos Regulares IR','Czasowniki regularne IR','exprimir','wyciskać'),
('Verbos Regulares IR','Czasowniki regularne IR','hundir','topić / zatapiać'),
('Verbos Regulares IR','Czasowniki regularne IR','crujir','chrupać / skrzypieć'),
('Verbos Regulares IR','Czasowniki regularne IR','nutrir','odżywiać'),
('Verbos Regulares IR','Czasowniki regularne IR','omitir','pomijać'),
('Verbos Regulares IR','Czasowniki regularne IR','percibir','postrzegać'),
('Verbos Regulares IR','Czasowniki regularne IR','persistir','wytrwać / utrzymywać się'),
('Verbos Regulares IR','Czasowniki regularne IR','persuadir','przekonywać'),
('Verbos Regulares IR','Czasowniki regularne IR','presumir','chwalić się / zakładać'),
('Verbos Regulares IR','Czasowniki regularne IR','coincidir','zbiegać się / zgadzać się'),
('Verbos Regulares IR','Czasowniki regularne IR','confundir','mylić'),
('Verbos Regulares IR','Czasowniki regularne IR','deprimir','dołować / deprimować'),
('Verbos Regulares IR','Czasowniki regularne IR','evadir','unikać'),
('Verbos Regulares IR','Czasowniki regularne IR','fundir','topić (metal/ser)'),
('Verbos Regulares IR','Czasowniki regularne IR','presidir','przewodniczyć'),
('Verbos Regulares IR','Czasowniki regularne IR','rebatir','zbijać (argument)'),
('Verbos Regulares IR','Czasowniki regularne IR','recurrir','uciekać się do / odwoływać się'),
('Verbos Regulares IR','Czasowniki regularne IR','resistir','stawiać opór / wytrzymywać'),
('Verbos Regulares IR','Czasowniki regularne IR','sacudir','potrząsać'),
('Verbos Regulares IR','Czasowniki regularne IR','sobrevivir','przeżyć / przetrwać'),
('Verbos Regulares IR','Czasowniki regularne IR','suplir','zastępować / uzupełniać'),
('Verbos Regulares IR','Czasowniki regularne IR','latir','bić (o sercu)'),
('Verbos Irregulares','Czasowniki nieregularne','ser','być (cechy stałe)'),
('Verbos Irregulares','Czasowniki nieregularne','estar','być (stany, lokalizacja)'),
('Verbos Irregulares','Czasowniki nieregularne','ir','iść / jechać'),
('Verbos Irregulares','Czasowniki nieregularne','tener','mieć'),
('Verbos Irregulares','Czasowniki nieregularne','hacer','robić'),
('Verbos Irregulares','Czasowniki nieregularne','decir','mówić / powiedzieć'),
('Verbos Irregulares','Czasowniki nieregularne','poder','móc'),
('Verbos Irregulares','Czasowniki nieregularne','querer','chcieć / kochać'),
('Verbos Irregulares','Czasowniki nieregularne','saber','wiedzieć / umieć'),
('Verbos Irregulares','Czasowniki nieregularne','venir','przychodzić / przyjeżdżać'),
('Verbos Irregulares','Czasowniki nieregularne','ver','widzieć'),
('Verbos Irregulares','Czasowniki nieregularne','dar','dawać'),
('Verbos Irregulares','Czasowniki nieregularne','poner','kłaść / umieszczać'),
('Verbos Irregulares','Czasowniki nieregularne','salir','wychodzić / wyjeżdżać'),
('Verbos Irregulares','Czasowniki nieregularne','traer','przynosić'),
('Verbos Irregulares','Czasowniki nieregularne','oír','słyszeć'),
('Verbos Irregulares','Czasowniki nieregularne','jugar','grać / bawić się'),
('Verbos Irregulares','Czasowniki nieregularne','pensar','myśleć'),
('Verbos Irregulares','Czasowniki nieregularne','volver','wracać'),
('Verbos Irregulares','Czasowniki nieregularne','dormir','spać'),
('Verbos Irregulares','Czasowniki nieregularne','pedir','prosić / zamawiać'),
('Verbos Irregulares','Czasowniki nieregularne','sentir','czuć / żałować'),
('Verbos Irregulares','Czasowniki nieregularne','caer','spadać / upadać'),
('Verbos Irregulares','Czasowniki nieregularne','conocer','znać / poznawać'),
('Verbos Irregulares','Czasowniki nieregularne','conducir','prowadzić (pojazd)'),
('Verbos Irregulares','Czasowniki nieregularne','seguir','śledzić / kontynuować / podążać'),
('Verbos Irregulares','Czasowniki nieregularne','cerrar','zamykać'),
('Verbos Irregulares','Czasowniki nieregularne','empezar','zaczynać'),
('Verbos Irregulares','Czasowniki nieregularne','encontrar','znajdować'),
('Verbos Irregulares','Czasowniki nieregularne','recordar','pamiętać / przypominać'),
('Verbos Irregulares','Czasowniki nieregularne','perder','tracić / gubić'),
('Verbos Irregulares','Czasowniki nieregularne','contar','liczyć / opowiadać'),
('Verbos Irregulares','Czasowniki nieregularne','entender','rozumieć'),
('Verbos Irregulares','Czasowniki nieregularne','servir','służyć / serwować'),
('Verbos Irregulares','Czasowniki nieregularne','reír','śmiać się'),
('Verbos Irregulares','Czasowniki nieregularne','volar','latać'),
('Verbos Irregulares','Czasowniki nieregularne','mover','ruszać / poruszać'),
('Verbos Irregulares','Czasowniki nieregularne','elegir','wybierać'),
('Verbos Irregulares','Czasowniki nieregularne','nacer','rodzić się'),
('Verbos Irregulares','Czasowniki nieregularne','morir','umierać'),
('Verbos Irregulares','Czasowniki nieregularne','traducir','tłumaczyć (język)'),
('Verbos Irregulares','Czasowniki nieregularne','producir','produkować'),
('Verbos Irregulares','Czasowniki nieregularne','caber','mieścić się'),
('Verbos Irregulares','Czasowniki nieregularne','valer','kosztować / być wartym'),
('Verbos Irregulares','Czasowniki nieregularne','andar','chodzić / spacerować'),
('Verbos Irregulares','Czasowniki nieregularne','construir','budować'),
('Verbos Irregulares','Czasowniki nieregularne','huir','uciekać'),
('Verbos Irregulares','Czasowniki nieregularne','influir','wpływać (na coś)'),
('Verbos Irregulares','Czasowniki nieregularne','destruir','niszczyć'),
('Verbos Irregulares','Czasowniki nieregularne','oler','pachnieć / wąchać'),
('Verbos Reflexivos','Czasowniki zwrotne','lavarse','myć się'),
('Verbos Reflexivos','Czasowniki zwrotne','ducharse','brać prysznic'),
('Verbos Reflexivos','Czasowniki zwrotne','bañarse','kąpać się'),
('Verbos Reflexivos','Czasowniki zwrotne','peinarse','czesać się'),
('Verbos Reflexivos','Czasowniki zwrotne','afeitarse','golić się'),
('Verbos Reflexivos','Czasowniki zwrotne','despertarse','budzić się'),
('Verbos Reflexivos','Czasowniki zwrotne','levantarse','wstawać'),
('Verbos Reflexivos','Czasowniki zwrotne','acostarse','kłaść się (spać)'),
('Verbos Reflexivos','Czasowniki zwrotne','dormirse','zasypiać'),
('Verbos Reflexivos','Czasowniki zwrotne','vestirse','ubierać się'),
('Verbos Reflexivos','Czasowniki zwrotne','desvestirse','rozbierać się'),
('Verbos Reflexivos','Czasowniki zwrotne','quitarse','zdejmować (z siebie)'),
('Verbos Reflexivos','Czasowniki zwrotne','ponerse','zakładać (na siebie) / stawać się'),
('Verbos Reflexivos','Czasowniki zwrotne','maquillarse','malować się'),
('Verbos Reflexivos','Czasowniki zwrotne','cepillarse','szczotkować (np. zęby)'),
('Verbos Reflexivos','Czasowniki zwrotne','sentarse','siadać'),
('Verbos Reflexivos','Czasowniki zwrotne','llamarse','nazywać się'),
('Verbos Reflexivos','Czasowniki zwrotne','casarse','brać ślub / hajtasz się'),
('Verbos Reflexivos','Czasowniki zwrotne','divorciarse','rozwodzić się'),
('Verbos Reflexivos','Czasowniki zwrotne','enamorarse','zakochać się'),
('Verbos Reflexivos','Czasowniki zwrotne','enfadarse','złościć się / obrażać się'),
('Verbos Reflexivos','Czasowniki zwrotne','alegrarse','cieszyć się'),
('Verbos Reflexivos','Czasowniki zwrotne','aburrirse','nudzić się'),
('Verbos Reflexivos','Czasowniki zwrotne','preocuparse','martwić się'),
('Verbos Reflexivos','Czasowniki zwrotne','quejarse','narzekać / skarżyć się'),
('Verbos Reflexivos','Czasowniki zwrotne','relajarse','relaksować się'),
('Verbos Reflexivos','Czasowniki zwrotne','quedarse','zostawać'),
('Verbos Reflexivos','Czasowniki zwrotne','irse','iść sobie / odchodzić'),
('Verbos Reflexivos','Czasowniki zwrotne','acercarse','zbliżać się'),
('Verbos Reflexivos','Czasowniki zwrotne','alejarse','oddalać się'),
('Verbos Reflexivos','Czasowniki zwrotne','acordarse','pamiętać / przypominać sobie'),
('Verbos Reflexivos','Czasowniki zwrotne','olvidarse','zapominać'),
('Verbos Reflexivos','Czasowniki zwrotne','despedirse','żegnać się'),
('Verbos Reflexivos','Czasowniki zwrotne','reunirse','spotykać się / gromadzić się'),
('Verbos Reflexivos','Czasowniki zwrotne','darse','zdarzać się / poddawać się'),
('Verbos Reflexivos','Czasowniki zwrotne','atreverse','odważać się'),
('Verbos Reflexivos','Czasowniki zwrotne','equivocarse','mielić się / popełniać błąd'),
('Verbos Reflexivos','Czasowniki zwrotne','arrepentirse','żałować (za grzechy / błędy)'),
('Verbos Reflexivos','Czasowniki zwrotne','enterarse','dowiadywać się'),
('Verbos Reflexivos','Czasowniki zwrotne','fijarse','zwracać uwagę / przyglądać się'),
('Verbos Reflexivos','Czasowniki zwrotne','burlarse','naigrawać się / drwić'),
('Verbos Reflexivos','Czasowniki zwrotne','reírse','śmiać się (z czegoś)'),
('Verbos Reflexivos','Czasowniki zwrotne','darse cuenta','zdawać sobie sprawę'),
('Verbos Reflexivos','Czasowniki zwrotne','mudarse','przeprowadzać się'),
('Verbos Reflexivos','Czasowniki zwrotne','prepararse','przygotowywać się'),
('Verbos Reflexivos','Czasowniki zwrotne','secarse','wycierać się / suszyć się'),
('Verbos Reflexivos','Czasowniki zwrotne','cortarse','zaciąć się (np. przy goleniu)'),
('Verbos Reflexivos','Czasowniki zwrotne','quemarse','oparzyć się / spalić się'),
('Verbos Reflexivos','Czasowniki zwrotne','caerse','przewrócić się / upaść'),
('Verbos Reflexivos','Czasowniki zwrotne','esconderse','chować się');
