insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Los Transportes','Transport','el transporte','transport'),
('Los Transportes','Transport','el vehículo','pojazd'),
('Los Transportes','Transport','el coche / el carro','samochód'),
('Los Transportes','Transport','el autobús','autobus'),
('Los Transportes','Transport','el tren','pociąg'),
('Los Transportes','Transport','el tranvía','tramwaj'),
('Los Transportes','Transport','el metro','metro'),
('Los Transportes','Transport','el avión','samolot'),
('Los Transportes','Transport','el helicóptero','helikopter'),
('Los Transportes','Transport','el barco','statek'),
('Los Transportes','Transport','el ferry','prom'),
('Los Transportes','Transport','la bicicleta','rower'),
('Los Transportes','Transport','la moto / la motocicleta','motocykl'),
('Los Transportes','Transport','el camión','ciężarówka'),
('Los Transportes','Transport','la furgoneta','furgonetka / van'),
('Los Transportes','Transport','el taxi','taksówka'),
('Los Transportes','Transport','el billete / el boleto','bilet'),
('Los Transportes','Transport','el pasaje','przejazd / bilet lotniczy'),
('Los Transportes','Transport','la estación','stacja / dworzec'),
('Los Transportes','Transport','la parada','przystanek'),
('Los Transportes','Transport','el aeropuerto','lotnisko'),
('Los Transportes','Transport','el puerto','port'),
('Los Transportes','Transport','el andén','peron'),
('Los Transportes','Transport','la vía','tor'),
('Los Transportes','Transport','volar','latać'),
('Los Transportes','Transport','conducir / manejar','prowadzić (pojazd)'),
('Los Transportes','Transport','montar','jeździć (np. na rowerze, konno)'),
('Los Transportes','Transport','navegar','żeglować / pływać'),
('Los Transportes','Transport','viajar','podróżować'),
('Los Transportes','Transport','el pasajero','pasażer'),
('Los Transportes','Transport','el conductor','kierowca'),
('Los Transportes','Transport','el piloto','pilot'),
('Los Transportes','Transport','el billete de ida','bilet w jedną stronę'),
('Los Transportes','Transport','el billete de ida y vuelta','bilet w obie strony'),
('Los Transportes','Transport','la taquilla','kasa biletowa'),
('Los Transportes','Transport','el equipaje','bagaż'),
('Los Transportes','Transport','la maleta','walizka'),
('Los Transportes','Transport','el tráfico','ruch drogowy'),
('Los Transportes','Transport','el atasco','korek drogowy'),
('Los Transportes','Transport','el semáforo','sygnalizacja świetlna'),
('Los Transportes','Transport','la autopista','autostrada'),
('Los Transportes','Transport','la carretera','szosa / droga'),
('Los Transportes','Transport','la calle','ulica'),
('Los Transportes','Transport','la velocidad','prędkość'),
('Los Transportes','Transport','frenar','hamować'),
('Los Transportes','Transport','acelerar','przyspieszać'),
('Los Transportes','Transport','aparcar','parkować'),
('Los Transportes','Transport','el garaje','garaż'),
('Los Transportes','Transport','la gasolina','benzyna'),
('Los Transportes','Transport','la multa','mandat'),
('La Tecnología','Technologia','la tecnología','technologia'),
('La Tecnología','Technologia','el ordenador / la computadora','komputer'),
('La Tecnología','Technologia','el portátil','laptop'),
('La Tecnología','Technologia','el teléfono móvil / el celular','telefon komórkowy'),
('La Tecnología','Technologia','la tableta','tablet'),
('La Tecnología','Technologia','la pantalla','ekran'),
('La Tecnología','Technologia','el teclado','klawiatura'),
('La Tecnología','Technologia','el ratón','myszka (komputerowa)'),
('La Tecnología','Technologia','el cable','kabel'),
('La Tecnología','Technologia','el cargador','ładowarka'),
('La Tecnología','Technologia','la batería','bateria'),
('La Tecnología','Technologia','el enchufe','wtyczka / gniazdko'),
('La Tecnología','Technologia','la red','sieć'),
('La Tecnología','Technologia','el wifi','wi-fi'),
('La Tecnología','Technologia','el internet','internet'),
('La Tecnología','Technologia','la página web','strona internetowa'),
('La Tecnología','Technologia','el correo electrónico','poczta elektroniczna (e-mail)'),
('La Tecnología','Technologia','la contraseña','hasło'),
('La Tecnología','Technologia','el usuario','użytkownik'),
('La Tecnología','Technologia','la aplicación / la app','aplikacja'),
('La Tecnología','Technologia','el software','oprogramowanie'),
('La Tecnología','Technologia','el hardware','sprzęt komputerowy'),
('La Tecnología','Technologia','el archivo','plik'),
('La Tecnología','Technologia','la carpeta','folder / teczka'),
('La Tecnología','Technologia','el enlace / el link','link / odnośnik'),
('La Tecnología','Technologia','el virus (informático)','wirus (komputerowy)'),
('La Tecnología','Technologia','el antivirus','antywirus'),
('La Tecnología','Technologia','descargar','pobierać (plik)'),
('La Tecnología','Technologia','subir','przesyłać / wgrywać'),
('La Tecnología','Technologia','guardar','zapisywać (plik)'),
('La Tecnología','Technologia','borrar','usuwać / kasować'),
('La Tecnología','Technologia','imprimir','drukować'),
('La Tecnología','Technologia','la impresora','drukarka'),
('La Tecnología','Technologia','el escáner','skaner'),
('La Tecnología','Technologia','los auriculares','słuchawki'),
('La Tecnología','Technologia','el altavoz','głośnik'),
('La Tecnología','Technologia','el micrófono','mikrofon'),
('La Tecnología','Technologia','la cámara','kamera / aparat'),
('La Tecnología','Technologia','el botón','przycisk'),
('La Tecnología','Technologia','encender','włączać'),
('La Tecnología','Technologia','apagar','wyłączać'),
('La Tecnología','Technologia','reiniciar','uruchamiać ponownie'),
('La Tecnología','Technologia','hacer clic','klikać'),
('La Tecnología','Technologia','navegar (por internet)','surfować (w internecie)'),
('La Tecnología','Technologia','el servidor','serwer'),
('La Tecnología','Technologia','el mensaje de texto','wiadomość tekstowa (SMS)'),
('La Tecnología','Technologia','el chat','czat'),
('La Tecnología','Technologia','la base de datos','baza danych'),
('La Tecnología','Technologia','programar','programować'),
('La Tecnología','Technologia','el código','kod'),
('Los Deportes','Sport','el deporte','sport'),
('Los Deportes','Sport','el equipo','drużyna'),
('Los Deportes','Sport','el jugador / la jugadora','gracz / zawodnik'),
('Los Deportes','Sport','el entrenador','trener'),
('Los Deportes','Sport','el árbitro','sędzia (sportowy)'),
('Los Deportes','Sport','el partido','mecz'),
('Los Deportes','Sport','el estadio','stadion'),
('Los Deportes','Sport','la cancha','boisko / kort'),
('Los Deportes','Sport','la pista','bieżnia / tor'),
('Los Deportes','Sport','el balón / la pelota','piłka'),
('Los Deportes','Sport','el fútbol','piłka nożna'),
('Los Deportes','Sport','el baloncesto','koszykówka'),
('Los Deportes','Sport','el voleibol','siatkówka'),
('Los Deportes','Sport','el tenis','tenis'),
('Los Deportes','Sport','el béisbol','baseball'),
('Los Deportes','Sport','el golf','golf'),
('Los Deportes','Sport','el rugby','rugby'),
('Los Deportes','Sport','el atletismo','lekkoatletyka'),
('Los Deportes','Sport','la natación','pływanie'),
('Los Deportes','Sport','el ciclismo','kolarstwo'),
('Los Deportes','Sport','el boxeo','boks'),
('Los Deportes','Sport','las artes marciales','sztuki walki'),
('Los Deportes','Sport','el esquí','narciarstwo'),
('Los Deportes','Sport','el patinaje','łyżwiarstwo / jazda na rolkach'),
('Los Deportes','Sport','la gimnasia','gimnastyka'),
('Los Deportes','Sport','el campeonato','mistrzostwa'),
('Los Deportes','Sport','la medalla','medal'),
('Los Deportes','Sport','el trofeo','trofeum'),
('Los Deportes','Sport','la copa','puchar'),
('Los Deportes','Sport','ganar','wygrywać'),
('Los Deportes','Sport','perder','przegrywać'),
('Los Deportes','Sport','empatar','remisować'),
('Los Deportes','Sport','el empate','remis'),
('Los Deportes','Sport','marcar (un gol)','strzelić (gola)'),
('Los Deportes','Sport','el gol','gol'),
('Los Deportes','Sport','el punto','punkt'),
('Los Deportes','Sport','la carrera','wyścig'),
('Los Deportes','Sport','correr','biegać'),
('Los Deportes','Sport','saltar','skakać'),
('Los Deportes','Sport','lanzar','rzucać'),
('Los Deportes','Sport','atrapar','łapać'),
('Los Deportes','Sport','entrenar','trenować'),
('Los Deportes','Sport','el entrenamiento','trening'),
('Los Deportes','Sport','el aficionado / el hincha','kibic'),
('Los Deportes','Sport','el uniforme','mundur / strój sportowy'),
('Los Deportes','Sport','la raqueta','rakieta (np. tenisowa)'),
('Los Deportes','Sport','el bate','kij (np. baseballowy)'),
('Los Deportes','Sport','la red','siatka (sportowa)'),
('Los Deportes','Sport','el casco','kask'),
('Los Deportes','Sport','la regla','zasada / reguła'),
('El Arte','Sztuka','el arte','sztuka'),
('El Arte','Sztuka','el artista','artysta'),
('El Arte','Sztuka','la obra de arte','dzieło sztuki'),
('El Arte','Sztuka','la pintura','malarstwo / obraz'),
('El Arte','Sztuka','el cuadro','obraz'),
('El Arte','Sztuka','el pintor / la pintora','malarz / malarka'),
('El Arte','Sztuka','el pincel','pędzel'),
('El Arte','Sztuka','la paleta','paleta'),
('El Arte','Sztuka','el lienzo','płótno'),
('El Arte','Sztuka','la escultura','rzeźba (dziedzina lub obiekt)'),
('El Arte','Sztuka','el escultor','rzeźbiarz'),
('El Arte','Sztuka','el mármol','marmur'),
('El Arte','Sztuka','la arcilla','glina'),
('El Arte','Sztuka','el dibujo','rysunek'),
('El Arte','Sztuka','el dibujante','rysownik'),
('El Arte','Sztuka','el lápiz','ołówek'),
('El Arte','Sztuka','el retrato','portret'),
('El Arte','Sztuka','el paisaje','pejzaż'),
('El Arte','Sztuka','el bodegón','martwa natura'),
('El Arte','Sztuka','la exposición','wystawa'),
('El Arte','Sztuka','la galería','galeria'),
('El Arte','Sztuka','el museo','muzeum'),
('El Arte','Sztuka','el marco','rama'),
('El Arte','Sztuka','la creatividad','kreatywność'),
('El Arte','Sztuka','la inspiración','inspiracja'),
('El Arte','Sztuka','el estilo','styl'),
('El Arte','Sztuka','clásico','klasyczny'),
('El Arte','Sztuka','moderno','nowoczesny'),
('El Arte','Sztuka','abstracto','abstrakcyjny'),
('El Arte','Sztuka','realista','realistyczny'),
('El Arte','Sztuka','el surrealismo','surrealizm'),
('El Arte','Sztuka','la acuarela','akwarela'),
('El Arte','Sztuka','el óleo','farba olejna'),
('El Arte','Sztuka','el boceto','szkic'),
('El Arte','Sztuka','diseñar','projektować'),
('El Arte','Sztuka','el diseño','projekt / design'),
('El Arte','Sztuka','el arquitecto','architekt'),
('El Arte','Sztuka','la arquitectura','architektura'),
('El Arte','Sztuka','el edificio','budynek'),
('El Arte','Sztuka','el monumento','zabytek / pomnik'),
('El Arte','Sztuka','la fotografía','fotografia'),
('El Arte','Sztuka','el fotógrafo','fotograf'),
('El Arte','Sztuka','la cámara fotográfica','aparat fotograficzny'),
('El Arte','Sztuka','capturar','uchwycić / sfotografować'),
('El Arte','Sztuka','el grabado','grawer / rycina'),
('El Arte','Sztuka','la cerámica','ceramika'),
('El Arte','Sztuka','el mosaico','mozaika'),
('El Arte','Sztuka','la simetría','symetria'),
('El Arte','Sztuka','la perspectiva','perspektywa'),
('El Arte','Sztuka','admirar','podziwiać'),
('La Música','Muzyka','la música','muzyka'),
('La Música','Muzyka','la canción','piosenka'),
('La Música','Muzyka','el cantante / la cantante','piosenkarz / piosenkarka'),
('La Música','Muzyka','el instrumento','instrument'),
('La Música','Muzyka','la guitarra','gitara'),
('La Música','Muzyka','el piano','pianino'),
('La Música','Muzyka','el violín','skrzypce'),
('La Música','Muzyka','la batería','perkusja'),
('La Música','Muzyka','el bajo','gitara basowa'),
('La Música','Muzyka','la banda / el grupo','zespół (muzyczny)'),
('La Música','Muzyka','el concierto','koncert'),
('La Música','Muzyka','el escenario','scena'),
('La Música','Muzyka','el micrófono','mikrofon'),
('La Música','Muzyka','el ritmo','rytm'),
('La Música','Muzyka','la melodía','melodia'),
('La Música','Muzyka','la letra','tekst (piosenki)'),
('La Música','Muzyka','el disco','płyta'),
('La Música','Muzyka','el álbum','album'),
('La Música','Muzyka','los auriculares','słuchawki'),
('La Música','Muzyka','el altavoz','głośnik'),
('La Música','Muzyka','la nota','nuta'),
('La Música','Muzyka','el acorde','akord'),
('La Música','Muzyka','el compositor','kompozytor'),
('La Música','Muzyka','tocar (un instrumento)','grać (na instrumencie)'),
('La Música','Muzyka','cantar','śpiewać'),
('La Música','Muzyka','escuchar','słuchać'),
('La Música','Muzyka','el ensayo','próba'),
('La Música','Muzyka','la orquesta','orkiestra'),
('La Música','Muzyka','el coro','chór'),
('La Música','Muzyka','la música clásica','muzyka klasyczna'),
('La Música','Muzyka','el rock','rock'),
('La Música','Muzyka','el pop','pop'),
('La Música','Muzyka','el jazz','jazz'),
('La Música','Muzyka','el flamenco','flamenco'),
('La Música','Muzyka','el reguetón','reggaeton'),
('La Música','Muzyka','la salsa','salsa (taniec/muzyka)'),
('La Música','Muzyka','la partitura','partytura / zapis nutowy'),
('La Música','Muzyka','el afinador','stroik / tuner'),
('La Música','Muzyka','el amplificador','wzmacniacz'),
('La Música','Muzyka','la cuerda','struna'),
('La Música','Muzyka','el teclado','keyboard / instrument klawiszowy'),
('La Música','Muzyka','la trompeta','trąbka'),
('La Música','Muzyka','la flauta','flet'),
('La Música','Muzyka','el saxofón','saksofon'),
('La Música','Muzyka','el DJ','DJ'),
('La Música','Muzyka','el festival','festiwal'),
('La Música','Muzyka','la entrada','bilet wstępu'),
('La Música','Muzyka','el público','publiczność'),
('La Música','Muzyka','grabar','nagrywać'),
('La Música','Muzyka','el sonido','dźwięk'),
('El Cine','Kino','el cine','kino (budynek i sztuka)'),
('El Cine','Kino','la película','film'),
('El Cine','Kino','el actor','aktor'),
('El Cine','Kino','la actriz','aktorka'),
('El Cine','Kino','el director','reżyser'),
('El Cine','Kino','el guion','scenariusz'),
('El Cine','Kino','el guionista','scenarzysta'),
('El Cine','Kino','la pantalla','ekran'),
('El Cine','Kino','la entrada','bilet'),
('El Cine','Kino','la taquilla','kasa biletowa'),
('El Cine','Kino','las palomitas','popcorn'),
('El Cine','Kino','el asiento / la butaca','miejsce / fotel'),
('El Cine','Kino','la fila','rząd'),
('El Cine','Kino','la cartelera','repertuar kinowy'),
('El Cine','Kino','el estreno','premiera'),
('El Cine','Kino','el tráiler','zwiastun'),
('El Cine','Kino','el género','gatunek'),
('El Cine','Kino','la comedia','komedia'),
('El Cine','Kino','el drama','dramat'),
('El Cine','Kino','la película de terror','horror'),
('El Cine','Kino','la película de acción','film akcji'),
('El Cine','Kino','la ciencia ficción','science fiction'),
('El Cine','Kino','el documental','film dokumentalny'),
('El Cine','Kino','la animación','animacja'),
('El Cine','Kino','el personaje','postać'),
('El Cine','Kino','el protagonista','główny bohater'),
('El Cine','Kino','el antagonista','antagonista / czarny charakter'),
('El Cine','Kino','la escena','scena (w filmie)'),
('El Cine','Kino','el rodaje','kręcenie filmu / zdjęcia'),
('El Cine','Kino','la cámara','kamera'),
('El Cine','Kino','la claqueta','klaps'),
('El Cine','Kino','el premio','nagroda'),
('El Cine','Kino','el festival de cine','festiwal filmowy'),
('El Cine','Kino','el Óscar','Oscar (nagroda)'),
('El Cine','Kino','la banda sonora','ścieżka dźwiękowa'),
('El Cine','Kino','el doblaje','dubbing'),
('El Cine','Kino','los subtítulos','napisy'),
('El Cine','Kino','el espectador','widz'),
('El Cine','Kino','el crítico de cine','krytyk filmowy'),
('El Cine','Kino','la reseña','recenzja'),
('El Cine','Kino','los efectos especiales','efekty specjalne'),
('El Cine','Kino','el maquillaje','charakteryzacja / makijaż'),
('El Cine','Kino','el vestuario','kostiumy'),
('El Cine','Kino','la pantalla grande','wielki ekran'),
('El Cine','Kino','un éxito de taquilla','hit kinowy'),
('El Cine','Kino','dirigir','reżyserować'),
('El Cine','Kino','actuar','grać (rolę)'),
('El Cine','Kino','proyectar','wyświetlać'),
('El Cine','Kino','el plano','ujęcie'),
('El Cine','Kino','el cortometraje','film krótkometrażowy'),
('La Literatura','Literatura','la literatura','literatura'),
('La Literatura','Literatura','el libro','książka'),
('La Literatura','Literatura','el autor / la autora','autor / autorka'),
('La Literatura','Literatura','el escritor / la escritora','pisarz / pisarka'),
('La Literatura','Literatura','el poeta / la poetisa','poeta / poetka'),
('La Literatura','Literatura','el poema','wiersz'),
('La Literatura','Literatura','la poesía','poezja'),
('La Literatura','Literatura','la novela','powieść'),
('La Literatura','Literatura','el cuento','opowiadanie / bajka'),
('La Literatura','Literatura','el ensayo','esej'),
('La Literatura','Literatura','la página','strona'),
('La Literatura','Literatura','el capítulo','rozdział'),
('La Literatura','Literatura','la portada','okładka (przednia)'),
('La Literatura','Literatura','la contraportada','tylna okładka'),
('La Literatura','Literatura','el índice','spis treści'),
('La Literatura','Literatura','el título','tytuł'),
('La Literatura','Literatura','la editorial','wydawnictwo'),
('La Literatura','Literatura','la librería','księgarnia'),
('La Literatura','Literatura','la biblioteca','biblioteka'),
('La Literatura','Literatura','leer','czytać'),
('La Literatura','Literatura','escribir','pisać'),
('La Literatura','Literatura','publicar','publikować / wydawać'),
('La Literatura','Literatura','imprimir','drukować'),
('La Literatura','Literatura','el lector / la lectora','czytelnik / czytelniczka'),
('La Literatura','Literatura','el personaje','postać'),
('La Literatura','Literatura','el protagonista','bohater główny'),
('La Literatura','Literatura','el narrador','narrator'),
('La Literatura','Literatura','la trama','fabuła'),
('La Literatura','Literatura','el argumento','streszczenie fabuły'),
('La Literatura','Literatura','el clímax','punkt kulminacyjny'),
('La Literatura','Literatura','el desenlace','zakończenie / rozwiązanie akcji'),
('La Literatura','Literatura','el género','gatunek literacki'),
('La Literatura','Literatura','la ficción','fikcja literacka'),
('La Literatura','Literatura','la biografía','biografia'),
('La Literatura','Literatura','la autobiografía','autobiografia'),
('La Literatura','Literatura','la fantasía','fantasy'),
('La Literatura','Literatura','el misterio','kryminał / tajemnica'),
('La Literatura','Literatura','el romance','romans'),
('La Literatura','Literatura','el cómic','komiks'),
('La Literatura','Literatura','la revista','czasopismo / magazyn'),
('La Literatura','Literatura','el periódico','gazeta'),
('La Literatura','Literatura','el artículo','artykuł'),
('La Literatura','Literatura','la estantería','regał na książki'),
('La Literatura','Literatura','el marcapáginas','zakładka do książki'),
('La Literatura','Literatura','la encuadernación','oprawa'),
('La Literatura','Literatura','el prólogo','prolog / wstęp'),
('La Literatura','Literatura','el epílogo','epilog'),
('La Literatura','Literatura','la traducción','tłumaczenie / przekład'),
('La Literatura','Literatura','el traductor / la traductora','tłumacz / tłumaczka'),
('La Literatura','Literatura','el manuscrito','manuskrypt / rękopis'),
('La Política','Polityka','la política','polityka'),
('La Política','Polityka','el político / la política','polityk'),
('La Política','Polityka','el gobierno','rząd'),
('La Política','Polityka','el presidente / la presidenta','prezydent'),
('La Política','Polityka','el ministro / la ministra','minister'),
('La Política','Polityka','el alcalde / la alcaldesa','burmistrz / prezydent miasta'),
('La Política','Polityka','el parlamento','parlament'),
('La Política','Polityka','el congreso','kongres'),
('La Política','Polityka','el senado','senat'),
('La Política','Polityka','el partido político','partia polityczna'),
('La Política','Polityka','la elección','wybory'),
('La Política','Polityka','el voto','głos (wyborczy)'),
('La Política','Polityka','votar','głosować'),
('La Política','Polityka','la urna','urna wyborcza'),
('La Política','Polityka','la campaña','kampania'),
('La Política','Polityka','el candidato','kandydat'),
('La Política','Polityka','la democracia','demokracja'),
('La Política','Polityka','la dictadura','dyktatura'),
('La Política','Polityka','la república','republika'),
('La Política','Polityka','la monarquía','monarchia'),
('La Política','Polityka','el rey','król'),
('La Política','Polityka','la reina','królowa'),
('La Política','Polityka','la ley','ustawa / prawo'),
('La Política','Polityka','la constitución','konstytucja'),
('La Política','Polityka','el derecho','prawo (ogół norm)'),
('La Política','Polityka','el ciudadano','obywatel'),
('La Política','Polityka','el debate','debata'),
('La Política','Polityka','el discurso','przemówienie'),
('La Política','Polityka','la manifestación','manifestacja / demonstracja'),
('La Política','Polityka','la huelga','strajk'),
('La Política','Polityka','la protesta','protest'),
('La Política','Polityka','la oposición','opozycja'),
('La Política','Polityka','la mayoría','większość'),
('La Política','Polityka','la minoría','mniejszość'),
('La Política','Polityka','la corrupción','korupcja'),
('La Política','Polityka','la crisis','kryzys'),
('La Política','Polityka','la reforma','reforma'),
('La Política','Polityka','el impuesto','podatek'),
('La Política','Polityka','el presupuesto','budżet'),
('La Política','Polityka','el estado','państwo'),
('La Política','Polityka','la nación','naród'),
('La Política','Polityka','la frontera','granica'),
('La Política','Polityka','la embajada','ambasada'),
('La Política','Polityka','el embajador','ambasador'),
('La Política','Polityka','el tratado','traktat / układ'),
('La Política','Polityka','la paz','pokój (stan bez wojny)'),
('La Política','Polityka','la guerra','wojna'),
('La Política','Polityka','la independencia','niepodległość'),
('La Política','Polityka','el poder','władza'),
('La Política','Polityka','el ministerio','ministerstwo'),
('La Economía','Gospodarka','la economía','gospodarka / ekonomia'),
('La Economía','Gospodarka','el dinero','pieniądze'),
('La Economía','Gospodarka','el banco','bank'),
('La Economía','Gospodarka','la cuenta bancaria','konto bankowe'),
('La Economía','Gospodarka','la tarjeta de crédito','karta kredytowa'),
('La Economía','Gospodarka','el efectivo / el metálico','gotówka'),
('La Economía','Gospodarka','la moneda','moneta / waluta'),
('La Economía','Gospodarka','el billete','banknot'),
('La Economía','Gospodarka','el cajero automático','bankomat'),
('La Economía','Gospodarka','el ingreso','przychód / dochód'),
('La Economía','Gospodarka','el gasto','wydatek'),
('La Economía','Gospodarka','el presupuesto','budżet'),
('La Economía','Gospodarka','el sueldo','pensja'),
('La Economía','Gospodarka','el salario','wynagrodzenie'),
('La Economía','Gospodarka','el precio','cena'),
('La Economía','Gospodarka','el coste / el costo','koszt'),
('La Economía','Gospodarka','barato','tani'),
('La Economía','Gospodarka','caro','drogi'),
('La Economía','Gospodarka','la inflación','inflacja'),
('La Economía','Gospodarka','la crisis económica','kryzys gospodarczy'),
('La Economía','Gospodarka','el crecimiento','wzrost'),
('La Economía','Gospodarka','el mercado','rynek'),
('La Economía','Gospodarka','la empresa','firma / przedsiębiorstwo'),
('La Economía','Gospodarka','el negocio','biznes / interes'),
('La Economía','Gospodarka','el empresario','przedsiębiorca'),
('La Economía','Gospodarka','el trabajador','pracownik'),
('La Economía','Gospodarka','el empleo','zatrudnienie'),
('La Economía','Gospodarka','el desempleo / el paro','bezrobocie'),
('La Economía','Gospodarka','la tasa de paro','stopa bezrobocia'),
('La Economía','Gospodarka','el contrato','kontrakt / umowa'),
('La Economía','Gospodarka','la inversión','inwestycja'),
('La Economía','Gospodarka','invertir','inwestować'),
('La Economía','Gospodarka','la bolsa (de valores)','giełda (papierów wartościowych)'),
('La Economía','Gospodarka','la acción','akcja (giełdowa)'),
('La Economía','Gospodarka','el dividendo','dywidenda'),
('La Economía','Gospodarka','el impuesto','podatek'),
('La Economía','Gospodarka','el IVA','podatek VAT'),
('La Economía','Gospodarka','la factura','faktura'),
('La Economía','Gospodarka','el recibo','paragon / pokwitowanie'),
('La Economía','Gospodarka','el cheque','czek'),
('La Economía','Gospodarka','el préstamo','pożyczka'),
('La Economía','Gospodarka','la deuda','dług'),
('La Economía','Gospodarka','el interés','odsetki / oprocentowanie'),
('La Economía','Gospodarka','la hipoteca','kredyt hipoteczny'),
('La Economía','Gospodarka','el ahorro','oszczędności'),
('La Economía','Gospodarka','ahorrar','oszczędzać'),
('La Economía','Gospodarka','comprar','kupować'),
('La Economía','Gospodarka','vender','sprzedawać'),
('La Economía','Gospodarka','el comercio','handel'),
('La Economía','Gospodarka','la exportación','eksport'),
('La Geografía','Geografia','la geografía','geografia'),
('La Geografía','Geografia','el mapa','mapa'),
('La Geografía','Geografia','el globo terráqueo','globus'),
('La Geografía','Geografia','el continente','kontynent'),
('La Geografía','Geografia','el país','kraj / państwo'),
('La Geografía','Geografia','la frontera','granica'),
('La Geografía','Geografia','el océano','ocean'),
('La Geografía','Geografia','el mar','morze'),
('La Geografía','Geografia','el golfo','zatoka (duża)'),
('La Geografía','Geografia','la bahía','zatoka (mniejsza)'),
('La Geografía','Geografia','el lago','jezioro'),
('La Geografía','Geografia','el río','rzeka'),
('La Geografía','Geografia','el arroyo','strumień'),
('La Geografía','Geografia','la montaña','góra'),
('La Geografía','Geografia','la cordillera','łańcuch górski'),
('La Geografía','Geografia','el volcán','wulkan'),
('La Geografía','Geografia','el valle','dolina'),
('La Geografía','Geografia','la llanura','równina'),
('La Geografía','Geografia','el desierto','pustynia'),
('La Geografía','Geografia','la selva','dżungla'),
('La Geografía','Geografia','el bosque','las'),
('La Geografía','Geografia','el ecuador','równik'),
('La Geografía','Geografia','el polo norte','biegun północny'),
('La Geografía','Geografia','el polo sur','biegun południowy'),
('La Geografía','Geografia','la latitud','szerokość geograficzna'),
('La Geografía','Geografia','la longitud','długość geograficzna'),
('La Geografía','Geografia','el clima','klimat'),
('La Geografía','Geografia','la península','półwysep'),
('La Geografía','Geografia','la isla','wyspa'),
('La Geografía','Geografia','el archipiélago','archipelag'),
('La Geografía','Geografia','el cabo','przylądek'),
('La Geografía','Geografia','el estrecho','cieśnina'),
('La Geografía','Geografia','la costa','wybrzeże'),
('La Geografía','Geografia','la playa','plaża'),
('La Geografía','Geografia','el acantilado','klif'),
('La Geografía','Geografia','la cueva','jaskinia'),
('La Geografía','Geografia','el hemisferio','półkula'),
('La Geografía','Geografia','la altitud','wysokość (n.p.m.)'),
('La Geografía','Geografia','el relieve','ukształtowanie powierzchni'),
('La Geografía','Geografia','el paisaje','krajobraz'),
('La Geografía','Geografia','el territorio','terytorium'),
('La Geografía','Geografia','la capital','stolica'),
('La Geografía','Geografia','la provincia','prowincja'),
('La Geografía','Geografia','el municipio','gmina / miasto'),
('La Geografía','Geografia','la región','region'),
('La Geografía','Geografia','el habitante','mieszkaniec'),
('La Geografía','Geografia','la población','populacja / ludność'),
('La Geografía','Geografia','el glaciar','lodowiec'),
('La Geografía','Geografia','el pantano','bagno'),
('La Geografía','Geografia','la duna','wydma'),
('La Historia','Historia','la historia','historia'),
('La Historia','Historia','el pasado','przeszłość'),
('La Historia','Historia','el presente','teraźniejszość'),
('La Historia','Historia','el futuro','przyszłość'),
('La Historia','Historia','el siglo','wiek / stulecie'),
('La Historia','Historia','la década','dekada'),
('La Historia','Historia','la época','epoka'),
('La Historia','Historia','la era','era'),
('La Historia','Historia','la prehistoria','prehistoria'),
('La Historia','Historia','la antigüedad','starożytność'),
('La Historia','Historia','la Edad Media','średniowiecze'),
('La Historia','Historia','el Renacimiento','renesans'),
('La Historia','Historia','el imperio','imperium'),
('La Historia','Historia','el rey','król'),
('La Historia','Historia','la reina','królowa'),
('La Historia','Historia','el emperador','cesarz'),
('La Historia','Historia','el faraón','faraon'),
('La Historia','Historia','el caballero','rycerz'),
('La Historia','Historia','el castillo','zamek'),
('La Historia','Historia','la corona','korona'),
('La Historia','Historia','la guerra','wojna'),
('La Historia','Historia','la paz','pokój (stan bez wojny)'),
('La Historia','Historia','la batalla','bitwa'),
('La Historia','Historia','el ejército','wojsko / armia'),
('La Historia','Historia','la revolución','rewolucja'),
('La Historia','Historia','la independencia','niepodległość'),
('La Historia','Historia','el descubrimiento','odkrycie'),
('La Historia','Historia','el explorador','odkrywca'),
('La Historia','Historia','la colonia','kolonia'),
('La Historia','Historia','el tratado','traktat'),
('La Historia','Historia','la alianza','sojusz'),
('La Historia','Historia','la victoria','zwycięstwo'),
('La Historia','Historia','la derrota','porażka'),
('La Historia','Historia','el héroe','bohater'),
('La Historia','Historia','el líder','przywódca'),
('La Historia','Historia','la civilización','cywilizacja'),
('La Historia','Historia','el monumento','pomnik / zabytek'),
('La Historia','Historia','la ruina','ruina'),
('La Historia','Historia','el museo','muzeum'),
('La Historia','Historia','el arqueólogo','archeolog'),
('La Historia','Historia','la excavación','wykopalisko'),
('La Historia','Historia','el artefacto','artefakt'),
('La Historia','Historia','el documento','dokument'),
('La Historia','Historia','el archivo','archiwum'),
('La Historia','Historia','el mito','mit'),
('La Historia','Historia','la leyenda','legenda'),
('La Historia','Historia','la tradición','tradycja'),
('La Historia','Historia','el antepasado','przodek'),
('La Historia','Historia','el progreso','postęp'),
('La Historia','Historia','la cronología','chronologia'),
('Las Emociones','Emocje','la emoción','emocja'),
('Las Emociones','Emocje','el sentimiento','uczucie'),
('Las Emociones','Emocje','la alegría','radość'),
('Las Emociones','Emocje','la tristeza','smutek'),
('Las Emociones','Emocje','el enfado / la ira','złość / gniew'),
('Las Emociones','Emocje','el miedo','strach'),
('Las Emociones','Emocje','la sorpresa','niespodzianka / zdziwienie'),
('Las Emociones','Emocje','el asco','wstręt'),
('Las Emociones','Emocje','el amor','miłość'),
('Las Emociones','Emocje','el odio','nienawiść'),
('Las Emociones','Emocje','la felicidad','szczęście'),
('Las Emociones','Emocje','la depresión','depresja'),
('Las Emociones','Emocje','la ansiedad','niepokój / lęk'),
('Las Emociones','Emocje','el estrés','stres'),
('Las Emociones','Emocje','la tranquilidad','spokój'),
('Las Emociones','Emocje','la esperanza','nadzieja'),
('Las Emociones','Emocje','la desesperación','rozpacz'),
('Las Emociones','Emocje','la culpa','wina'),
('Las Emociones','Emocje','la vergüenza','wstyd'),
('Las Emociones','Emocje','el orgullo','duma'),
('Las Emociones','Emocje','la envidia','zazdrość (o to, co ma ktoś)'),
('Las Emociones','Emocje','los celos','zazdrość (w miłości)'),
('Las Emociones','Emocje','la compasión','współczucie'),
('Las Emociones','Emocje','la empatía','empatia'),
('Las Emociones','Emocje','la simpatía','sympatia'),
('Las Emociones','Emocje','el aburrimiento','nuda'),
('Las Emociones','Emocje','la diversión','zabawa'),
('Las Emociones','Emocje','el entusiasmo','entuzjazm'),
('Las Emociones','Emocje','la frustración','frustracja'),
('Las Emociones','Emocje','la confusión','dezorientacja'),
('Las Emociones','Emocje','la decepción','rozczarowanie'),
('Las Emociones','Emocje','el alivio','ulga'),
('Las Emociones','Emocje','la gratitud','wdzięczność'),
('Las Emociones','Emocje','la nostalgia','nostalgia / tęsknota'),
('Las Emociones','Emocje','la soledad','samotność'),
('Las Emociones','Emocje','el cariño','czułość'),
('Las Emociones','Emocje','la pasión','pasja / namiętność'),
('Las Emociones','Emocje','la ternura','tkliwość'),
('Las Emociones','Emocje','la admiración','podziw'),
('Las Emociones','Emocje','el pánico','panika'),
('Las Emociones','Emocje','el terror','przerażenie'),
('Las Emociones','Emocje','la euforia','euforia'),
('Las Emociones','Emocje','el nerviosismo','nerwowość'),
('Las Emociones','Emocje','la confianza','zaufanie / pewność siebie'),
('Las Emociones','Emocje','la duda','wątpliwość'),
('Las Emociones','Emocje','el optimismo','optymizm'),
('Las Emociones','Emocje','el pesimismo','pesymizm'),
('Las Emociones','Emocje','llorar','płakać'),
('Las Emociones','Emocje','reír','śmiać się'),
('Las Emociones','Emocje','sonreír','uśmiechać się'),
('Los Verbos de Acción','Czasowniki akcji','hacer','robić'),
('Los Verbos de Acción','Czasowniki akcji','ir','iść / jechać'),
('Los Verbos de Acción','Czasowniki akcji','venir','przychodzić / przyjeżdżać'),
('Los Verbos de Acción','Czasowniki akcji','correr','biegać'),
('Los Verbos de Acción','Czasowniki akcji','caminar / andar','chodzić / spacerować'),
('Los Verbos de Acción','Czasowniki akcji','saltar','skakać'),
('Los Verbos de Acción','Czasowniki akcji','nadar','pływać'),
('Los Verbos de Acción','Czasowniki akcji','volar','latać'),
('Los Verbos de Acción','Czasowniki akcji','caer','spadać / upadać'),
('Los Verbos de Acción','Czasowniki akcji','lanzar','rzucać'),
('Los Verbos de Acción','Czasowniki akcji','atrapar','łapać'),
('Los Verbos de Acción','Czasowniki akcji','golpear','uderzać'),
('Los Verbos de Acción','Czasowniki akcji','empujar','pchać'),
('Los Verbos de Acción','Czasowniki akcji','tirar','ciągnąć / rzucać'),
('Los Verbos de Acción','Czasowniki akcji','levantar','podnosić'),
('Los Verbos de Acción','Czasowniki akcji','llevar','nieść / nosić / zabierać'),
('Los Verbos de Acción','Czasowniki akcji','traer','przynosić'),
('Los Verbos de Acción','Czasowniki akcji','abrir','otwierać'),
('Los Verbos de Acción','Czasowniki akcji','cerrar','zamykać'),
('Los Verbos de Acción','Czasowniki akcji','romper','psuć / łamać'),
('Los Verbos de Acción','Czasowniki akcji','arreglar','naprawiać'),
('Los Verbos de Acción','Czasowniki akcji','cortar','ciąć / kroić'),
('Los Verbos de Acción','Czasowniki akcji','pegar','przyklejać / uderzać'),
('Los Verbos de Acción','Czasowniki akcji','buscar','szukać'),
('Los Verbos de Acción','Czasowniki akcji','encontrar','znajdować'),
('Los Verbos de Acción','Czasowniki akcji','esconder','chować / ukrywać'),
('Los Verbos de Acción','Czasowniki akcji','dar','dawać'),
('Los Verbos de Acción','Czasowniki akcji','recibir','otrzymywać'),
('Los Verbos de Acción','Czasowniki akcji','coger / tomar','brać / chwytać'),
('Los Verbos de Acción','Czasowniki akcji','poner','kłaść / umieszczać'),
('Los Verbos de Acción','Czasowniki akcji','quitar','zdejmować / zabierać'),
('Los Verbos de Acción','Czasowniki akcji','subir','wchodzić (pod górę) / wsiadać'),
('Los Verbos de Acción','Czasowniki akcji','bajar','schodzić (w dół) / wysiadać'),
('Los Verbos de Acción','Czasowniki akcji','entrar','wchodzić'),
('Los Verbos de Acción','Czasowniki akcji','salir','wychodzić'),
('Los Verbos de Acción','Czasowniki akcji','escapar','uciekać'),
('Los Verbos de Acción','Czasowniki akcji','perseguir','gonić / ścigać'),
('Los Verbos de Acción','Czasowniki akcji','luchar','walczyć'),
('Los Verbos de Acción','Czasowniki akcji','ganar','wygrywać'),
('Los Verbos de Acción','Czasowniki akcji','perder','przegrywać / gubić'),
('Los Verbos de Acción','Czasowniki akcji','construir','budować'),
('Los Verbos de Acción','Czasowniki akcji','destruir','niszczyć'),
('Los Verbos de Acción','Czasowniki akcji','limpiar','czyścić / sprzątać'),
('Los Verbos de Acción','Czasowniki akcji','ensuciar','brudzić'),
('Los Verbos de Acción','Czasowniki akcji','lavar','myć / prać'),
('Los Verbos de Acción','Czasowniki akcji','secar','suszyć / wycierać'),
('Los Verbos de Acción','Czasowniki akcji','cocinar','gotować'),
('Los Verbos de Acción','Czasowniki akcji','comer','jeść'),
('Los Verbos de Acción','Czasowniki akcji','beber','pić'),
('Los Verbos de Acción','Czasowniki akcji','dormir','spać'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','simpático','sympatyczny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','antipático','niesympatyczny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','amable','uprzejmy / miły'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','grosero','niegrzeczny / grubiański'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','educado','wychowany'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','maleducado','niewychowany'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','inteligente','inteligentny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','tonto','głupi'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','listo','bystry / gotowy'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','trabajador','pracowity'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','perezoso / vago','leniwy'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','valiente','odważny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','cobarde','tchórzliwy'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','tímido','nieśmiały'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','extrovertido','ekstrawertyczny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','introvertido','introwertyczny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','generoso','hojny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','egoísta','egoistyczny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','honesto','uczciwy'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','mentiroso','kłamliwy / kłamca'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','sincero','szczery'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','hipócrita','hipokryta'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','alegre','radosny / wesoły'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','triste','smutny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','divertido','zabawny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','aburrido','nudny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','paciente','cierpliwy'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','impaciente','niecierpliwy'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','tranquilo','spokojny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','nervioso','nerwowy'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','optimista','optymistyczny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','pesimista','pesymistyczny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','orgulloso','dumny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','humilde','pokorny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','ambicioso','ambitny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','modesto','skromny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','creativo','kreatywny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','curioso','ciekawy (świata)'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','responsable','odpowiedzialny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','irresponsable','nieodpowiedzialny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','puntual','punktualny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','impuntual','niepunktualny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','tolerante','tolerancyjny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','intolerante','nietolerancyjny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','leal','lojalny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','desleal','nielojalny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','fiel','wierny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','infiel','niewierny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','cariñoso','czuły'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','frío','chłodny (w obyciu)'),
('En el Restaurante','W restauracji','el restaurante','restauracja'),
('En el Restaurante','W restauracji','el menú','menu'),
('En el Restaurante','W restauracji','la carta','karta dań'),
('En el Restaurante','W restauracji','el camarero','kelner'),
('En el Restaurante','W restauracji','la camarera','kelnerka'),
('En el Restaurante','W restauracji','el cliente','klient'),
('En el Restaurante','W restauracji','la mesa','stół'),
('En el Restaurante','W restauracji','la silla','krzesło'),
('En el Restaurante','W restauracji','la reserva','rezerwacja'),
('En el Restaurante','W restauracji','reservar','rezerwować'),
('En el Restaurante','W restauracji','pedir','zamawiać / prosić'),
('En el Restaurante','W restauracji','la cuenta','rachunek'),
('En el Restaurante','W restauracji','la propina','napiwek'),
('En el Restaurante','W restauracji','el plato','talerz / danie'),
('En el Restaurante','W restauracji','el vaso','szklanka'),
('En el Restaurante','W restauracji','la copa','kieliszek'),
('En el Restaurante','W restauracji','la taza','filiżanka'),
('En el Restaurante','W restauracji','los cubiertos','sztućce'),
('En el Restaurante','W restauracji','el tenedor','widelec'),
('En el Restaurante','W restauracji','el cuchillo','nóż'),
('En el Restaurante','W restauracji','la cuchara','łyżka'),
('En el Restaurante','W restauracji','la cucharilla','łyżeczka'),
('En el Restaurante','W restauracji','la servilleta','serwetka'),
('En el Restaurante','W restauracji','el mantel','obrus'),
('En el Restaurante','W restauracji','la sal','sól'),
('En el Restaurante','W restauracji','la pimienta','pieprz'),
('En el Restaurante','W restauracji','el aceite','oliwa / olej'),
('En el Restaurante','W restauracji','el vinagre','ocet'),
('En el Restaurante','W restauracji','el pan','chleb'),
('En el Restaurante','W restauracji','el agua','woda'),
('En el Restaurante','W restauracji','la bebida','napój'),
('En el Restaurante','W restauracji','el entrante','przystawka'),
('En el Restaurante','W restauracji','el primer plato','pierwsze danie'),
('En el Restaurante','W restauracji','el plato principal','danie główne'),
('En el Restaurante','W restauracji','el postre','deser'),
('En el Restaurante','W restauracji','la especialidad de la casa','specjalność zakładu'),
('En el Restaurante','W restauracji','la recomendación','rekomendacja'),
('En el Restaurante','W restauracji','el chef','szef kuchni'),
('En el Restaurante','W restauracji','cocinar','gotować'),
('En el Restaurante','W restauracji','sabroso','smaczny'),
('En el Restaurante','W restauracji','picante','pikantny'),
('En el Restaurante','W restauracji','salado','słony'),
('En el Restaurante','W restauracji','dulce','słodki'),
('En el Restaurante','W restauracji','amargo','gorzki'),
('En el Restaurante','W restauracji','ácido','kwaśny'),
('En el Restaurante','W restauracji','la botella','butelka'),
('En el Restaurante','W restauracji','pagar','płacić'),
('En el Restaurante','W restauracji','en efectivo','gotówką'),
('En el Restaurante','W restauracji','con tarjeta','kartą'),
('En el Restaurante','W restauracji','el servicio','obsługa'),
('En el Hotel','W hotelu','el hotel','hotel'),
('En el Hotel','W hotelu','la recepción','recepcja'),
('En el Hotel','W hotelu','el recepcionista','recepcjonista'),
('En el Hotel','W hotelu','el huésped','gość (hotelowy)'),
('En el Hotel','W hotelu','la llave','klucz'),
('En el Hotel','W hotelu','la tarjeta','karta (do pokoju)'),
('En el Hotel','W hotelu','la habitación','pokój'),
('En el Hotel','W hotelu','la habitación individual','pokój jednoosobowy'),
('En el Hotel','W hotelu','la habitación doble','pokój dwuosobowy'),
('En el Hotel','W hotelu','la cama','łóżko'),
('En el Hotel','W hotelu','la almohada','poduszka'),
('En el Hotel','W hotelu','la manta','koc'),
('En el Hotel','W hotelu','el baño','łazienka'),
('En el Hotel','W hotelu','la ducha','prysznic'),
('En el Hotel','W hotelu','la bañera','wanna'),
('En el Hotel','W hotelu','el jabón','mydło'),
('En el Hotel','W hotelu','el champú','szampon'),
('En el Hotel','W hotelu','la toalla','ręcznik'),
('En el Hotel','W hotelu','el papel higiénico','papier toaletowy'),
('En el Hotel','W hotelu','el aire acondicionado','klimatyzacja'),
('En el Hotel','W hotelu','la calefacción','ogrzewanie'),
('En el Hotel','W hotelu','el balcón','balkon'),
('En el Hotel','W hotelu','las vistas','widok'),
('En el Hotel','W hotelu','el ascensor','winda'),
('En el Hotel','W hotelu','las escaleras','schody'),
('En el Hotel','W hotelu','el equipaje','bagaż'),
('En el Hotel','W hotelu','la maleta','walizka'),
('En el Hotel','W hotelu','el pasillo','korytarz'),
('En el Hotel','W hotelu','el desayuno','śniadanie'),
('En el Hotel','W hotelu','la pensión completa','pełne wyżywienie'),
('En el Hotel','W hotelu','la media pensión','niepełne wyżywienie'),
('En el Hotel','W hotelu','el servicio de habitaciones','obsługa pokoju'),
('En el Hotel','W hotelu','la limpieza','sprzątanie'),
('En el Hotel','W hotelu','cancelar','anulować'),
('En el Hotel','W hotelu','registrarse','zameldować się'),
('En el Hotel','W hotelu','la salida','wymeldowanie / wyjazd'),
('En el Hotel','W hotelu','la estancia','pobyt'),
('En el Hotel','W hotelu','la factura','faktura / rachunek'),
('En el Hotel','W hotelu','el gerente','kierownik'),
('En el Hotel','W hotelu','el botones','boy hotelowy'),
('En el Hotel','W hotelu','el vestíbulo','lobby / hol'),
('En el Hotel','W hotelu','la piscina','basen'),
('En el Hotel','W hotelu','el gimnasio','siłownia'),
('En el Hotel','W hotelu','el wifi','wi-fi'),
('En el Hotel','W hotelu','la contraseña','hasło'),
('En el Hotel','W hotelu','despertar','budzić'),
('En el Hotel','W hotelu','quejarse','skarżyć się'),
('En el Hotel','W hotelu','libre','wolny'),
('En el Hotel','W hotelu','ocupado','zajęty'),
('En el Hotel','W hotelu','la percha','wieszak');
