insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Asignaturas Escolares','Przedmioty szkolne','las matemáticas','matematyka'),
('Asignaturas Escolares','Przedmioty szkolne','la lengua española','język hiszpański'),
('Asignaturas Escolares','Przedmioty szkolne','la literatura','literatura'),
('Asignaturas Escolares','Przedmioty szkolne','la historia','historia'),
('Asignaturas Escolares','Przedmioty szkolne','la geografía','geografia'),
('Asignaturas Escolares','Przedmioty szkolne','la física','fizyka'),
('Asignaturas Escolares','Przedmioty szkolne','la química','chemia'),
('Asignaturas Escolares','Przedmioty szkolne','la biología','biologia'),
('Asignaturas Escolares','Przedmioty szkolne','la geología','geologia'),
('Asignaturas Escolares','Przedmioty szkolne','el idioma extranjero','język obcy'),
('Asignaturas Escolares','Przedmioty szkolne','el inglés','język angielski'),
('Asignaturas Escolares','Przedmioty szkolne','el francés','język francuski'),
('Asignaturas Escolares','Przedmioty szkolne','el alemán','język niemiecki'),
('Asignaturas Escolares','Przedmioty szkolne','el latín','łacina'),
('Asignaturas Escolares','Przedmioty szkolne','el griego antiguo','greka klasyczna'),
('Asignaturas Escolares','Przedmioty szkolne','la informática','informatyka'),
('Asignaturas Escolares','Przedmioty szkolne','la tecnología','technologia / technika'),
('Asignaturas Escolares','Przedmioty szkolne','la educación física','wychowanie fizyczne (WF)'),
('Asignaturas Escolares','Przedmioty szkolne','la música','muzyka'),
('Asignaturas Escolares','Przedmioty szkolne','el arte','sztuka'),
('Asignaturas Escolares','Przedmioty szkolne','la educación plástica y visual','plastyka'),
('Asignaturas Escolares','Przedmioty szkolne','la filosofía','filozofia'),
('Asignaturas Escolares','Przedmioty szkolne','la economía','ekonomia'),
('Asignaturas Escolares','Przedmioty szkolne','el dibujo técnico','rysunek techniczny'),
('Asignaturas Escolares','Przedmioty szkolne','la religión','religios'),
('Asignaturas Escolares','Przedmioty szkolne','la ética','etyka'),
('Asignaturas Escolares','Przedmioty szkolne','la educación cívica','wos / wiedza o społeczeństwie'),
('Asignaturas Escolares','Przedmioty szkolne','las ciencias sociales','nauki społeczne'),
('Asignaturas Escolares','Przedmioty szkolne','las ciencias naturales','przyroda / nauki przyrodnicze'),
('Asignaturas Escolares','Przedmioty szkolne','el taller','warsztat'),
('Asignaturas Escolares','Przedmioty szkolne','el laboratorio','laboratorium'),
('Asignaturas Escolares','Przedmioty szkolne','el deporte','sport'),
('Asignaturas Escolares','Przedmioty szkolne','el teatro','teatr'),
('Asignaturas Escolares','Przedmioty szkolne','el coro','chór'),
('Asignaturas Escolares','Przedmioty szkolne','la oratoria','retoryka'),
('Asignaturas Escolares','Przedmioty szkolne','la programación','programowanie'),
('Asignaturas Escolares','Przedmioty szkolne','la robótica','robotyka'),
('Asignaturas Escolares','Przedmioty szkolne','la contabilidad','rachunkowość'),
('Asignaturas Escolares','Przedmioty szkolne','la sociología','socjologia'),
('Asignaturas Escolares','Przedmioty szkolne','la psicología','psychologia'),
('Asignaturas Escolares','Przedmioty szkolne','la ecología','ekologia'),
('Asignaturas Escolares','Przedmioty szkolne','la astronomía','astronomia'),
('Asignaturas Escolares','Przedmioty szkolne','la estadística','statystyka'),
('Asignaturas Escolares','Przedmioty szkolne','la asignatura obligatoria','przedmiot obowiązkowy'),
('Asignaturas Escolares','Przedmioty szkolne','la asignatura optativa','przedmiot do wyboru'),
('Asignaturas Escolares','Przedmioty szkolne','el currículo','program nauczania'),
('Asignaturas Escolares','Przedmioty szkolne','el temario','zakres materiału'),
('Asignaturas Escolares','Przedmioty szkolne','la optativa','przedmiot fakultatywny'),
('Asignaturas Escolares','Przedmioty szkolne','la troncal','przedmiot główny / kluczowy'),
('Material Escolar','Przybory szkolne','el material escolar','przybory szkolne'),
('Material Escolar','Przybory szkolne','el bolígrafo','długopis'),
('Material Escolar','Przybory szkolne','el lápiz','ołówek'),
('Material Escolar','Przybory szkolne','el portaminas','ołówek automatyczny'),
('Material Escolar','Przybory szkolne','la goma de borrar','gumka do ścierania'),
('Material Escolar','Przybory szkolne','el sacapuntas','tempérka / temperówka'),
('Material Escolar','Przybory szkolne','la regla','linijka'),
('Material Escolar','Przybory szkolne','la escuadra','ekierka'),
('Material Escolar','Przybory szkolne','el cartabón','ekierka (trójkątna)'),
('Material Escolar','Przybory szkolne','el transportador de ángulos','kątomierz'),
('Material Escolar','Przybory szkolne','el compás','cyrkiel'),
('Material Escolar','Przybory szkolne','el cuaderno','zeszyt'),
('Material Escolar','Przybory szkolne','la libreta','notatnik / zeszyt'),
('Material Escolar','Przybory szkolne','el bloc de notas','blok rysunkowy / notatnik'),
('Material Escolar','Przybory szkolne','el papel','papier'),
('Material Escolar','Przybory szkolne','la carpeta','teczka'),
('Material Escolar','Przybory szkolne','el archivador','segregator'),
('Material Escolar','Przybory szkolne','los folios','kartki papieru (A4)'),
('Material Escolar','Przybory szkolne','el libro de texto','podręcznik'),
('Material Escolar','Przybory szkolne','el diccionario','słownik'),
('Material Escolar','Przybory szkolne','la mochila','plecak'),
('Material Escolar','Przybory szkolne','el estuche','piórnik'),
('Material Escolar','Przybory szkolne','las tijeras','nożyczki'),
('Material Escolar','Przybory szkolne','el pegamento','klej'),
('Material Escolar','Przybory szkolne','la barra de glue','klej w sztyfcie'),
('Material Escolar','Przybory szkolne','la cinta adhesiva','taśma klejąca'),
('Material Escolar','Przybory szkolne','las ceras','kredki świecowe'),
('Material Escolar','Przybory szkolne','los lápices de colores','kredki ołówkowe'),
('Material Escolar','Przybory szkolne','los rotuladores','mazaki / pisaki'),
('Material Escolar','Przybory szkolne','las acuarelas','farby akwarelowe'),
('Material Escolar','Przybory szkolne','la témpera','farby plakatowe / tempery'),
('Material Escolar','Przybory szkolne','el pincel','pędzel'),
('Material Escolar','Przybory szkolne','la paleta','paleta do farb'),
('Material Escolar','Przybory szkolne','el lienzo','płótno'),
('Material Escolar','Przybory szkolne','la plastelina','plastelina'),
('Material Escolar','Przybory szkolne','el corrector líquido','korektor w płynie'),
('Material Escolar','Przybory szkolne','la grapadora','zszywacze'),
('Material Escolar','Przybory szkolne','las grapas','zszywki'),
('Material Escolar','Przybory szkolne','el clip','spinacz biurowy'),
('Material Escolar','Przybory szkolne','la perforadora','dziurkacz'),
('Material Escolar','Przybory szkolne','la calculadora','kalkulator'),
('Material Escolar','Przybory szkolne','el ordenador portátil','laptop szkolny'),
('Material Escolar','Przybory szkolne','la tableta','tablet'),
('Material Escolar','Przybory szkolne','los auriculares','słuchawki'),
('Material Escolar','Przybory szkolne','la pizarra blanca','mała tablica suchościeralna'),
('Material Escolar','Przybory szkolne','el rotulador de pizarra','marker do tablic'),
('Material Escolar','Przybory szkolne','la agenda escolar','dzienniczek / planner szkolny'),
('Material Escolar','Przybory szkolne','el marcapáginas','zakładka do książki'),
('Material Escolar','Przybory szkolne','la cinta correctora','korektor w taśmie'),
('Material Escolar','Przybory szkolne','el portafolios','teczka na dokumenty'),
('Exámenes y Notas','Egzaminy i oceny','el examen','egzamin'),
('Exámenes y Notas','Egzaminy i oceny','la prueba','test / sprawdzian'),
('Exámenes y Notas','Egzaminy i oceny','el control','kartkówka / test kontrolny'),
('Exámenes y Notas','Egzaminy i oceny','el examen parcial','kolokwium / egzamin cząstkowy'),
('Exámenes y Notas','Egzaminy i oceny','el examen final','egzamin końcowy'),
('Exámenes y Notas','Egzaminy i oceny','la nota','ocena'),
('Exámenes y Notas','Egzaminy i oceny','la calificación','ocena / stopień'),
('Exámenes y Notas','Egzaminy i oceny','el sobresaliente','celujący (szóstka)'),
('Exámenes y Notas','Egzaminy i oceny','el notable','bardzo dobry / dobry (czwórka/piątka)'),
('Exámenes y Notas','Egzaminy i oceny','el bien','dostateczny (trójka)'),
('Exámenes y Notas','Egzaminy i oceny','el aprobado','dostateczny / zdany (trójka)'),
('Exámenes y Notas','Egzaminy i oceny','el suspenso','niedostateczny / oblany (jedynka/dwójka)'),
('Exámenes y Notas','Egzaminy i oceny','aprobar','zdać (egzamin)'),
('Exámenes y Notas','Egzaminy i oceny','suspender','oblać / nie zdać'),
('Exámenes y Notas','Egzaminy i oceny','sacar buena nota','dostać dobrą ocenę'),
('Exámenes y Notas','Egzaminy i oceny','sacar mala nota','dostać złą ocenę'),
('Exámenes y Notas','Egzaminy i oceny','el boletín de notas','świadectwo / karta ocen'),
('Exámenes y Notas','Egzaminy i oceny','el suspensso','niedostateczny'),
('Exámenes y Notas','Egzaminy i oceny','copiar','ściągać (na egzaminie)'),
('Exámenes y Notas','Egzaminy i oceny','la chuleta','ściągawka'),
('Exámenes y Notas','Egzaminy i oceny','suspender por copia','zostać przyłapanym na ściąganiu'),
('Exámenes y Notas','Egzaminy i oceny','el profesor','egzaminator / nauczyciel'),
('Exámenes y Notas','Egzaminy i oceny','el tribunal','komisja egzaminacyjna'),
('Exámenes y Notas','Egzaminy i oceny','la convocatoria','termin egzaminu'),
('Exámenes y Notas','Egzaminy i oceny','la nota media','średnia ocen'),
('Exámenes y Notas','Egzaminy i oceny','el suspenso','poprawka (warunek)'),
('Exámenes y Notas','Egzaminy i oceny','el examen de recuperación','egzamin poprawkowy'),
('Exámenes y Notas','Egzaminy i oceny','recuperar','poprawić ocenę'),
('Exámenes y Notas','Egzaminy i oceny','estudiar','uczyć się'),
('Exámenes y Notas','Egzaminy i oceny','repasar','powtarzać materiał'),
('Exámenes y Notas','Egzaminy i oceny','el repaso','powtórka'),
('Exámenes y Notas','Egzaminy i oceny','el temario','zakres materiału'),
('Exámenes y Notas','Egzaminy i oceny','memorizar','zapamiętywać / uczyć się na pamięć'),
('Exámenes y Notas','Egzaminy i oceny','entregar el examen','oddać egzamin'),
('Exámenes y Notas','Egzaminy i oceny','terminar el examen','skończyć egzamin'),
('Exámenes y Notas','Egzaminy i oceny','el tiempo','czas (na egzaminie)'),
('Exámenes y Notas','Egzaminy i oceny','la pregunta','pytanie'),
('Exámenes y Notas','Egzaminy i oceny','la respuesta','odpowiedź'),
('Exámenes y Notas','Egzaminy i oceny','responder','odpowiadać'),
('Exámenes y Notas','Egzaminy i oceny','acertar','trafić / odpowiedzieć poprawnie'),
('Exámenes y Notas','Egzaminy i oceny','fallar','pomylić się / popełnić błąd'),
('Exámenes y Notas','Egzaminy i oceny','el error','błąd'),
('Exámenes y Notas','Egzaminy i oceny','la corrección','poprawianie / korekta'),
('Exámenes y Notas','Egzaminy i oceny','la nota numérica','ocena cyfrowa'),
('Exámenes y Notas','Egzaminy i oceny','la evaluación','ocena / ewaluación'),
('Exámenes y Notas','Egzaminy i oceny','el test psicotécnico','test psychotechniczny'),
('Exámenes y Notas','Egzaminy i oceny','la prueba de acceso','egzamin wstępny'),
('Exámenes y Notas','Egzaminy i oceny','el resultado','wynik'),
('Exámenes y Notas','Egzaminy i oceny','el certificado','certyfikat / zaświadczenie'),
('Exámenes y Notas','Egzaminy i oceny','el éxito','sukces'),
('Aficiones','Zainteresowania','la afición','zainteresowanie / hobby'),
('Aficiones','Zainteresowania','el pasatiempo','hobby / czas wolny'),
('Aficiones','Zainteresowania','el hobby','hobby'),
('Aficiones','Zainteresowania','disfrutar','cieszyć się'),
('Aficiones','Zainteresowania','entretenerse','zabawiać się / spędzać czas'),
('Aficiones','Zainteresowania','el oceno','czas wolny'),
('Aficiones','Zainteresowania','leer','czytać'),
('Aficiones','Zainteresowania','escribir','pisać'),
('Aficiones','Zainteresowania','fotografiar','fotografować'),
('Aficiones','Zainteresowania','pintar','malować'),
('Aficiones','Zainteresowania','dibujar','rysować'),
('Aficiones','Zainteresowania','tocar un instrumento','grać na instrumencie'),
('Aficiones','Zainteresowania','cantar','śpiewać'),
('Aficiones','Zainteresowania','bailar','tańczyć'),
('Aficiones','Zainteresowania','cocinar','gotować'),
('Aficiones','Zainteresowania','hornear','piec (np. ciasta)'),
('Aficiones','Zainteresowania','viajar','podróżować'),
('Aficiones','Zainteresowania','acampar','kempingować'),
('Aficiones','Zainteresowania','senderismo','turystyka piesza / trekking'),
('Aficiones','Zainteresowania','la jardinería','ogrodnictwo'),
('Aficiones','Zainteresowania','el bricolaje','majsterkowanie'),
('Aficiones','Zainteresowania','la costura','szycie'),
('Aficiones','Zainteresowania','tejer','robić na drutach'),
('Aficiones','Zainteresowania','coleccionar','kolekcjonować'),
('Aficiones','Zainteresowania','los videojuegos','gry wideo'),
('Aficiones','Zainteresowania','el ajedrez','szachy'),
('Aficiones','Zainteresowania','los rompecabezas','puzzle / łamigłówki'),
('Aficiones','Zainteresowania','las manualidades','prace ręczne / handmade'),
('Aficiones','Zainteresowania','pescar','łowić ryby'),
('Aficiones','Zainteresowania','cazar','polować'),
('Aficiones','Zainteresowania','patinar','jeździć na łyżwach / rolkach'),
('Aficiones','Zainteresowania','montar en bicicleta','jeździć na rowerze'),
('Aficiones','Zainteresowania','nadar','pływać'),
('Aficiones','Zainteresowania','correr','biegać'),
('Aficiones','Zainteresowania','hacer yoga','uprawiać jogę'),
('Aficiones','Zainteresowania','meditar','medytować'),
('Aficiones','Zainteresowania','el cine','kino (oglądanie filmów)'),
('Aficiones','Zainteresowania','el teatro','teatr'),
('Aficiones','Zainteresowania','los conciertos','koncerty'),
('Aficiones','Zainteresowania','los museos','muzea'),
('Aficiones','Zainteresowania','el voluntariado','wolontariat'),
('Aficiones','Zainteresowania','aprender idiomas','uczyć się języków'),
('Aficiones','Zainteresowania','la astronomia','astronomia (jako hobby)'),
('Aficiones','Zainteresowania','observar aves','obserwowanie ptaków'),
('Aficiones','Zainteresowania','la cerámica','ceramika'),
('Aficiones','Zainteresowania','la carpintería','stolarstwo'),
('Aficiones','Zainteresowania','el diseño','projektowanie'),
('Aficiones','Zainteresowania','la cata de vinos','degustacja wina'),
('Aficiones','Zainteresowania','apasionante','pasjonujący'),
('Aficiones','Zainteresowania','divertido','zabawny / przyjemny'),
('Manualidades','Rękodzieło','las manualidades','rękodzieło / prace ręczne'),
('Manualidades','Rękodzieło','el arte','sztuka'),
('Manualidades','Rękodzieło','la artesanía','rzemiosło'),
('Manualidades','Rękodzieło','crear','tworzyć'),
('Manualidades','Rękodzieło','hacer a mano','robić ręcznie'),
('Manualidades','Rękodzieło','el DIY (hazlo tú mismo)','zrób to sam (DIY)'),
('Manualidades','Rękodzieło','el papel','papier'),
('Manualidades','Rękodzieło','la cartulina','karton / brystol'),
('Manualidades','Rękodzieło','las tijeras','nożyczki'),
('Manualidades','Rękodzieło','el pegamento','klej'),
('Manualidades','Rękodzieło','la pistola de pegamento caliente','pistolet do kleju na gorąco'),
('Manualidades','Rękodzieło','la cinta adhesiva','taśma klejąca'),
('Manualidades','Rękodzieło','el hilo','nić'),
('Manualidades','Rękodzieło','la aguja','igła'),
('Manualidades','Rękodzieło','coser','szyć'),
('Manualidades','Rękodzieło','tejer','robić na drutach / szydełkować'),
('Manualidades','Rękodzieło','el ganchillo','szydełkowanie'),
('Manualidades','Rękodzieło','la lana','włóczka / wełna'),
('Manualidades','Rękodzieło','la tela','tkanina / materiał'),
('Manualidades','Rękodzieło','el fieltro','filc'),
('Manualidades','Rękodzieło','la arcilla','glina'),
('Manualidades','Rękodzieło','la porcelana fría','porcelana plastyczna / zimna'),
('Manualidades','Rękodzieło','la plastelina','plastelina'),
('Manualidades','Rękodzieło','pintar','malować'),
('Manualidades','Rękodzieło','el pincel','pędzel'),
('Manualidades','Rękodzieło','las pinturas','farby'),
('Manualidades','Rękodzieło','el abalorio','koralik'),
('Manualidades','Rękodzieło','la bisutería','biżuteria artystyczna'),
('Manualidades','Rękodzieło','el collar','naszyjnik'),
('Manualidades','Rękodzieło','la pulsera','bransoletka'),
('Manualidades','Rękodzieło','el papel de regalo','papier do pakowania prezentów'),
('Manualidades','Rękodzieło','la caja','pudełko'),
('Manualidades','Rękodzieło','decorar','dekorować'),
('Manualidades','Rękodzieło','la decoración','dekoracja'),
('Manualidades','Rękodzieło','reciclar','recyklingować (materiały do prac)'),
('Manualidades','Rękodzieło','el cartón','tektura'),
('Manualidades','Rękodzieło','la madera','drewno'),
('Manualidades','Rękodzieło','tallar','rzeźbić'),
('Manualidades','Rękodzieło','el pegamento de contacto','klej montażowy'),
('Manualidades','Rękodzieło','el patrón','wzór / szablon'),
('Manualidades','Rękodzieło','la aguja de coser','igła do szycia'),
('Manualidades','Rękodzieło','el dedal','naparstek'),
('Manualidades','Rękodzieło','el botón','guzik'),
('Manualidades','Rękodzieło','la cremallera','zamek błyskawiczny'),
('Manualidades','Rękodzieło','la lana de vidrio','wata szklana'),
('Manualidades','Rękodzieło','barnizar','lakierować'),
('Manualidades','Rękodzieło','lijar','szlifować'),
('Manualidades','Rękodzieło','el molde','forma / odlew'),
('Manualidades','Rękodzieło','original','oryginalny'),
('Manualidades','Rękodzieło','creativo','kreatywny'),
('Coleccionismo','Kolekcjonerstwo','el coleccionismo','kolekcjonerstwo'),
('Coleccionismo','Kolekcjonerstwo','el coleccionista','kolekcjoner'),
('Coleccionismo','Kolekcjonerstwo','la colección','kolekcja'),
('Coleccionismo','Kolekcjonerstwo','coleccionar','kolekcjonować'),
('Coleccionismo','Kolekcjonerstwo','el sello','znaczek pocztorski'),
('Coleccionismo','Kolekcjonerstwo','la filatelia','filatelistika'),
('Coleccionismo','Kolekcjonerstwo','la moneda','moneta'),
('Coleccionismo','Kolekcjonerstwo','la numismática','numizmatyka'),
('Coleccionismo','Kolekcjonerstwo','el billete','banknot'),
('Coleccionismo','Kolekcjonerstwo','la tarjeta postal','pocztówka'),
('Coleccionismo','Kolekcjonerstwo','el cromo','kolekcjonerska karta / naklejka'),
('Coleccionismo','Kolekcjonerstwo','el tebeo / el cómic','komiks'),
('Coleccionismo','Kolekcjonerstwo','el libro antiguo','stara książka / biały kruk'),
('Coleccionismo','Kolekcjonerstwo','el vinylo','płyta winylowa'),
('Coleccionismo','Kolekcjonerstwo','el CD','płyta CD'),
('Coleccionismo','Kolekcjonerstwo','el casete','kaseta magnetofonowa'),
('Coleccionismo','Kolekcjonerstwo','el juguete antiguo','stara zabawka'),
('Coleccionismo','Kolekcjonerstwo','la miniatura','miniatura'),
('Coleccionismo','Kolekcjonerstwo','el modelo a escala','model w skali'),
('Coleccionismo','Kolekcjonerstwo','la maqueta','makieta'),
('Coleccionismo','Kolekcjonerstwo','el coche de juguete','samochodzik'),
('Coleccionismo','Kolekcjonerstwo','el tren eléctrico','kolejka elektryczna'),
('Coleccionismo','Kolekcjonerstwo','la figura de acción','figurka akcji'),
('Coleccionismo','Kolekcjonerstwo','la piedra preciosa','kamień szlachetny'),
('Coleccionismo','Kolekcjonerstwo','el mineral','minerał'),
('Coleccionismo','Kolekcjonerstwo','el fósil','skamieniałość'),
('Coleccionismo','Kolekcjonerstwo','la concha','muszla'),
('Coleccionismo','Kolekcjonerstwo','la antigüedades','antyki'),
('Coleccionismo','Kolekcjonerstwo','el anticuario','antykwariusz / sklep z antykami'),
('Coleccionismo','Kolekcjonerstwo','el mercadillo','pchli targ'),
('Coleccionismo','Kolekcjonerstwo','la subasta','aukcja'),
('Coleccionismo','Kolekcjonerstwo','pujar','licytować'),
('Coleccionismo','Kolekcjonerstwo','el valor','wartość'),
('Coleccionismo','Kolekcjonerstwo','la rareza','rzadkość'),
('Coleccionismo','Kolekcjonerstwo','único','jedyny w swoim rodzaju / unikalny'),
('Coleccionismo','Kolekcjonerstwo','en perfecto estado','w idealnym stanie'),
('Coleccionismo','Kolekcjonerstwo','el catálogo','katalog'),
('Coleccionismo','Kolekcjonerstwo','exhibir','wystawiać / pokazywać'),
('Coleccionismo','Kolekcjonerstwo','la exposición','wystawa'),
('Coleccionismo','Kolekcjonerstwo','el museo','muzeum'),
('Coleccionismo','Kolekcjonerstwo','el tesoro','skarb'),
('Coleccionismo','Kolekcjonerstwo','encontrar','znaleźć'),
('Coleccionismo','Kolekcjonerstwo','descubrir','odkryć'),
('Coleccionismo','Kolekcjonerstwo','conservar','konserwować / zachować'),
('Coleccionismo','Kolekcjonerstwo','restaurar','odrestaurować'),
('Coleccionismo','Kolekcjonerstwo','la vitrina','gablota / witryna'),
('Coleccionismo','Kolekcjonerstwo','el estuche','etui / pudełko kolekcjonerskie'),
('Coleccionismo','Kolekcjonerstwo','la serie limitada','seria limitowana'),
('Coleccionismo','Kolekcjonerstwo','la reliquia','relikwia / pamiątka przeszłości'),
('Coleccionismo','Kolekcjonerstwo','apasionante','pasjonujący'),
('Bricolaje','Majsterkowanie','el bricolaje','majsterkowanie'),
('Bricolaje','Majsterkowanie','la herramienta','narzędzie'),
('Bricolaje','Majsterkowanie','el martillo','młotek'),
('Bricolaje','Majsterkowanie','el clavo','gwoźdź'),
('Bricolaje','Majsterkowanie','el tornillo','śruba / wkręt'),
('Bricolaje','Majsterkowanie','el destornillador','śrubokręt'),
('Bricolaje','Majsterkowanie','el taladro','wiertarka'),
('Bricolaje','Majsterkowanie','la broca','wiertło'),
('Bricolaje','Majsterkowanie','la sierra','piła'),
('Bricolaje','Majsterkowanie','el alicates','kleszcze / szczypce'),
('Bricolaje','Majsterkowanie','la llave inglesa','klucz nastawny'),
('Bricolaje','Majsterkowanie','el metro','miarka / taśma miernicza'),
('Bricolaje','Majsterkowanie','el nivel','poziomnica'),
('Bricolaje','Majsterkowanie','la lija','papier ścierny'),
('Bricolaje','Majsterkowanie','lijar','szlifować'),
('Bricolaje','Majsterkowanie','pintar','malować'),
('Bricolaje','Majsterkowanie','la brocha','pędzel malarski'),
('Bricolaje','Majsterkowanie','el rodillo','wałek malarski'),
('Bricolaje','Majsterkowanie','la pintura','farba'),
('Bricolaje','Majsterkowanie','el barniz','lakier'),
('Bricolaje','Majsterkowanie','barnizar','lakierować'),
('Bricolaje','Majsterkowanie','la madera','drewno'),
('Bricolaje','Majsterkowanie','el tablero','płyta / deska'),
('Bricolaje','Majsterkowanie','cortar','ciąć'),
('Bricolaje','Majsterkowanie','pegar','kleić'),
('Bricolaje','Majsterkowanie','el pegamento','klej'),
('Bricolaje','Majsterkowanie','la escalera','drabina'),
('Bricolaje','Majsterkowanie','la linterna','latarka'),
('Bricolaje','Majsterkowanie','el enchufe','gniazdko elektryczne'),
('Bricolaje','Majsterkowanie','el interruptor','włącznik światła'),
('Bricolaje','Majsterkowanie','el cable','kabel'),
('Bricolaje','Majsterkowanie','la bombilla','żarówka'),
('Bricolaje','Majsterkowanie','el grifo','kran'),
('Bricolaje','Majsterkowanie','la tubería','rura / instalacja wodna'),
('Bricolaje','Majsterkowanie','la fuga','wyciek'),
('Bricolaje','Majsterkowanie','reparar','naprawiać'),
('Bricolaje','Majsterkowanie','arreglar','naprawiać / porządkować'),
('Bricolaje','Majsterkowanie','instalar','instalować'),
('Bricolaje','Majsterkowanie','montar','składać / montować'),
('Bricolaje','Majsterkowanie','desmontar','demontować'),
('Bricolaje','Majsterkowanie','el taller','warsztat'),
('Bricolaje','Majsterkowanie','el banco de trabajo','warsztatowy stół roboczy'),
('Bricolaje','Majsterkowanie','el casco','kask ochronny'),
('Bricolaje','Majsterkowanie','las gafas de protección','okulary ochronne'),
('Bricolaje','Majsterkowanie','los guantes','rękawice ochronne'),
('Bricolaje','Majsterkowanie','el desván','poddasze'),
('Bricolaje','Majsterkowanie','el garaje','garaż'),
('Bricolaje','Majsterkowanie','la reforma','remont'),
('Bricolaje','Majsterkowanie','reformar','remontować'),
('Bricolaje','Majsterkowanie','el manitas','złota rączka / majsterkowicz'),
('Jardinería','Ogrodnictwo','la jardinería','ogrodnictwo'),
('Jardinería','Ogrodnictwo','el jardín','ogród'),
('Jardinería','Ogrodnictwo','el jardinero','ogrodnik'),
('Jardinería','Ogrodnictwo','la planta','roślina'),
('Jardinería','Ogrodnictwo','la flor','kwiat'),
('Jardinería','Ogrodnictwo','el árbol','drzewo'),
('Jardinería','Ogrodnictwo','el arbusto','krzew'),
('Jardinería','Ogrodnictwo','el césped','trawnik'),
('Jardinería','Ogrodnictwo','cortar el césped','kosić trawnik'),
('Jardinería','Ogrodnictwo','el cortacésped','kosiarka'),
('Jardinería','Ogrodnictwo','la tierra','ziemia / gleba'),
('Jardinería','Ogrodnictwo','el abono','nawóz'),
('Jardinería','Ogrodnictwo','abonar','nawozić'),
('Jardinería','Ogrodnictwo','regar','podlewać'),
('Jardinería','Ogrodnictwo','la regadera','konewka'),
('Jardinería','Ogrodnictwo','la manguera','wąż ogrodowy'),
('Jardinería','Ogrodnictwo','la maceta','doniczka'),
('Jardinería','Ogrodnictwo','el tiesto','doniczka / donica'),
('Jardinería','Ogrodnictwo','la semilla','nasiono'),
('Jardinería','Ogrodnictwo','sembrar','siać'),
('Jardinería','Ogrodnictwo','plantar','sadzić'),
('Jardinería','Ogrodnictwo','el bulbo','cebulka kwiatowa'),
('Jardinería','Ogrodnictwo','la azada','motyka'),
('Jardinería','Ogrodnictwo','la pala','łopata'),
('Jardinería','Ogrodnictwo','el rastrillo','grabie'),
('Jardinería','Ogrodnictwo','la carretilla','taczka'),
('Jardinería','Ogrodnictwo','las tijeras de podar','sekator'),
('Jardinería','Ogrodnictwo','podar','przycinać / podcinać'),
('Jardinería','Ogrodnictwo','las malas hierbas','chwisty'),
('Jardinería','Ogrodnictwo','quitar las malas hierbas','pielić'),
('Jardinería','Ogrodnictwo','la plaga','szkodnik / plaga'),
('Jardinería','Ogrodnictwo','el insecticida','insektycyd / środek owadobójczy'),
('Jardinería','Ogrodnictwo','el invernadero','szklarnia'),
('Jardinería','Ogrodnictwo','la pérgola','pergola'),
('Jardinería','Ogrodnictwo','el est】.co','oczko wodne'),
('Jardinería','Ogrodnictwo','la fuente','fontanna'),
('Jardinería','Ogrodnictwo','florecer','kwitnąć'),
('Jardinería','Ogrodnictwo','la floración','kwitnienie'),
('Jardinería','Ogrodnictwo','marchitarse','więdnąć'),
('Jardinería','Ogrodnictwo','las hojas','liście'),
('Jardinería','Ogrodnictwo','la raíz','korzeń'),
('Jardinería','Ogrodnictwo','el tallo','łodyga'),
('Jardinería','Ogrodnictwo','el abono orgánico','kompost / nawóz organiczny'),
('Jardinería','Ogrodnictwo','el mantillo','ściółka'),
('Jardinería','Ogrodnictwo','el paisajismo','architektura krajobrazu'),
('Jardinería','Ogrodnictwo','el diseño de jardines','projektowanie ogrodów'),
('Jardinería','Ogrodnictwo','la terraza','taras'),
('Jardinería','Ogrodnictwo','el balcón','balkon'),
('Jardinería','Ogrodnictwo','exótico','egzotyczny'),
('Jardinería','Ogrodnictwo','perenne','wiecznie zielony / wieloletni');
