insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Profesiones Técnicas','Zawody techniczne','el ingeniero','inżynier'),
('Profesiones Técnicas','Zawody techniczne','el ingeniero civil','inżynier budownictwa'),
('Profesiones Técnicas','Zawody techniczne','el ingeniero mecánico','inżynier mechanik'),
('Profesiones Técnicas','Zawody techniczne','el ingeniero eléctrico','inżynier elektryk'),
('Profesiones Técnicas','Zawody techniczne','el ingeniero informático','inżynier informatyk'),
('Profesiones Técnicas','Zawody techniczne','el ingeniero industrial','inżynier przemysłowy'),
('Profesiones Técnicas','Zawody techniczne','el ingeniero químico','inżynier chemik'),
('Profesiones Técnicas','Zawody techniczne','el arquitecto','architekt'),
('Profesiones Técnicas','Zawody techniczne','el topógrafo','geodeta / topograf'),
('Profesiones Técnicas','Zawody techniczne','el programador','programista'),
('Profesiones Técnicas','Zawody techniczne','el desarrollador de software','programista (software developer)'),
('Profesiones Técnicas','Zawody techniczne','el analista de sistemas','analityk systemowy'),
('Profesiones Técnicas','Zawody techniczne','el técnico de sistemas','technik systemowy'),
('Profesiones Técnicas','Zawody techniczne','el administrador de redes','administrator sieci'),
('Profesiones Técnicas','Zawody techniczne','el técnico de soporte','pracownik wsparcia technicznego (helpdesk)'),
('Profesiones Técnicas','Zawody techniczne','el técnico de mantenimiento','technik utrzymania ruchu'),
('Profesiones Técnicas','Zawody techniczne','el electricista','elektryk'),
('Profesiones Técnicas','Zawody techniczne','el fontanero','hydraulik'),
('Profesiones Técnicas','Zawody techniczne','el carpintero','stolarz'),
('Profesiones Técnicas','Zawody techniczne','el albañil','murarz'),
('Profesiones Técnicas','Zawody techniczne','el mecánico','mechanik'),
('Profesiones Técnicas','Zawody techniczne','el soldador','spawacz'),
('Profesiones Técnicas','Zawody techniczne','el tornero','tokarz'),
('Profesiones Técnicas','Zawody techniczne','el fresador','frezer'),
('Profesiones Técnicas','Zawody techniczne','el técnico de climatización','technik klimatyzacji'),
('Profesiones Técnicas','Zawody techniczne','el instalador','instalator'),
('Profesiones Técnicas','Zawody techniczne','el operario','operator / robotnik'),
('Profesiones Técnicas','Zawody techniczne','el operador de grúa','operator dźwigu'),
('Profesiones Técnicas','Zawody techniczne','el conductor de maquinaria pesada','kierowca ciężkiego sprzętu'),
('Profesiones Técnicas','Zawody techniczne','el técnico en electrónica','technik elektronik'),
('Profesiones Técnicas','Zawody techniczne','el especialista en robótica','specjalista ds. robotyki'),
('Profesiones Técnicas','Zawody techniczne','el técnico de sonido','realizator dźwięku'),
('Profesiones Técnicas','Zawody techniczne','el técnico de iluminación','realizator oświetlenia'),
('Profesiones Técnicas','Zawody techniczne','el camarógrafo','operator kamery'),
('Profesiones Técnicas','Zawody techniczne','el editor de vídeo','montażysta wideo'),
('Profesiones Técnicas','Zawody techniczne','el delineante','kreślarz'),
('Profesiones Técnicas','Zawody techniczne','el aparejador','rzeczoznawca budowlany / inżynier budowy'),
('Profesiones Técnicas','Zawody techniczne','el inspector de obras','inspektor nadzoru budowlanego'),
('Profesiones Técnicas','Zawody techniczne','el técnico en telecomunicaciones','technik telekomunikacji'),
('Profesiones Técnicas','Zawody techniczne','el diseñador web','projektant stron internetowych'),
('Profesiones Técnicas','Zawody techniczne','el administrador de bases de datos','administrator baz danych'),
('Profesiones Técnicas','Zawody techniczne','el experto en ciberseguridad','ekspert ds. cyberbezpieczeństwa'),
('Profesiones Técnicas','Zawody techniczne','el especialista en inteligencia artificial','specjalista ds. sztucznej inteligencji'),
('Profesiones Técnicas','Zawody techniczne','el mecánico de aviación','mechanik lotniczy'),
('Profesiones Técnicas','Zawody techniczne','el artesano','rzemieślnik'),
('Profesiones Técnicas','Zawody techniczne','el relojero','zegarmistrz'),
('Profesiones Técnicas','Zawody techniczne','el cerrajero','ślusarz'),
('Profesiones Técnicas','Zawody techniczne','el chapista','blacharz'),
('Profesiones Técnicas','Zawody techniczne','el pintor','malarz (pokojowy)'),
('Profesiones Técnicas','Zawody techniczne','el técnico','technik'),
('Profesiones Artísticas','Zawody artystyczne','el artista','artysta'),
('Profesiones Artísticas','Zawody artystyczne','el actor','aktor'),
('Profesiones Artísticas','Zawody artystyczne','la actriz','aktorka'),
('Profesiones Artísticas','Zawody artystyczne','el pintor','malarz'),
('Profesiones Artísticas','Zawody artystyczne','el músico','muzyk'),
('Profesiones Artísticas','Zawody artystyczne','el cantante','piosenkarz'),
('Profesiones Artísticas','Zawody artystyczne','el bailarín','tancerz'),
('Profesiones Artísticas','Zawody artystyczne','el escritor','pisarz'),
('Profesiones Artísticas','Zawody artystyczne','el poeta','poeta'),
('Profesiones Artísticas','Zawody artystyczne','el escultor','rzeźbiarz'),
('Profesiones Artísticas','Zawody artystyczne','el fotógrafo','fotograf'),
('Profesiones Artísticas','Zawody artystyczne','el director de cine','reżyser filmowy'),
('Profesiones Artísticas','Zawody artystyczne','el diseñador','projektant'),
('Profesiones Artísticas','Zawody artystyczne','el diseñador gráfico','grafik'),
('Profesiones Artísticas','Zawody artystyczne','el diseñador de moda','projektant mody'),
('Profesiones Artísticas','Zawody artystyczne','el ilustrador','ilustrator'),
('Profesiones Artísticas','Zawody artystyczne','el dibujante','rysownik'),
('Profesiones Artísticas','Zawody artystyczne','el animador','animator'),
('Profesiones Artísticas','Zawody artystyczne','el arquitecto','architekt'),
('Profesiones Artísticas','Zawody artystyczne','el compositor','kompozytor'),
('Profesiones Artísticas','Zawody artystyczne','el guionista','scenarzysta'),
('Profesiones Artísticas','Zawody artystyczne','el dramaturgo','dramaturg'),
('Profesiones Artísticas','Zawody artystyczne','el comediante','komik'),
('Profesiones Artísticas','Zawody artystyczne','el mago','magik / iluzjonista'),
('Profesiones Artísticas','Zawody artystyczne','el coreógrafo','choreograf'),
('Profesiones Artísticas','Zawody artystyczne','el director de orquesta','dyrygent'),
('Profesiones Artísticas','Zawody artystyczne','el maquillador','wizażysta / charakteryzator'),
('Profesiones Artísticas','Zawody artystyczne','el peluquero (estilista)','stylista fryzur'),
('Profesiones Artísticas','Zawody artystyczne','el tatuador','tatuażysta'),
('Profesiones Artísticas','Zawody artystyczne','el crítico de arte','krytyk sztuki'),
('Profesiones Artísticas','Zawody artystyczne','el curador / el comisario','kurator wystawy'),
('Profesiones Artísticas','Zawody artystyczne','el artesano','rzemieślnik'),
('Profesiones Artísticas','Zawody artystyczne','el alfarero','garncarz'),
('Profesiones Artísticas','Zawody artystyczne','el tejedor','tkacz'),
('Profesiones Artísticas','Zawody artystyczne','el joyero','jubiler'),
('Profesiones Artísticas','Zawody artystyczne','el orfebre','złotnik'),
('Profesiones Artísticas','Zawody artystyczne','el grabador','grawer'),
('Profesiones Artísticas','Zawody artystyczne','el restaurador','konserwator zabytków/sztuki'),
('Profesiones Artísticas','Zawody artystyczne','el modelo','model (zawód)'),
('Profesiones Artísticas','Zawody artystyczne','el actor de doblaje','aktor dubbingowy'),
('Profesiones Artísticas','Zawody artystyczne','el escenógrafo','scenograf'),
('Profesiones Artísticas','Zawody artystyczne','el locutor','lektor / spiker'),
('Profesiones Artísticas','Zawody artystyczne','el novelista','powieściopisarz'),
('Profesiones Artísticas','Zawody artystyczne','el ensayista','eseista'),
('Profesiones Artísticas','Zawody artystyczne','el cuentista','bajkopisarz / autor opowiadań'),
('Profesiones Artísticas','Zawody artystyczne','el titiritero','lalkarz'),
('Profesiones Artísticas','Zawody artystyczne','el mimo','mim'),
('Profesiones Artísticas','Zawody artystyczne','el malabarista','żongler'),
('Profesiones Artísticas','Zawody artystyczne','el payaso','klaun'),
('Profesiones Artísticas','Zawody artystyczne','el creador de contenido','twórca internetowy / influencer'),
('Oficios','Rzemiosło/Fachy','Palabra 1 de Oficios','Słowo 1 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 2 de Oficios','Słowo 2 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 3 de Oficios','Słowo 3 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 4 de Oficios','Słowo 4 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 5 de Oficios','Słowo 5 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 6 de Oficios','Słowo 6 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 7 de Oficios','Słowo 7 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 8 de Oficios','Słowo 8 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 9 de Oficios','Słowo 9 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 10 de Oficios','Słowo 10 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 11 de Oficios','Słowo 11 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 12 de Oficios','Słowo 12 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 13 de Oficios','Słowo 13 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 14 de Oficios','Słowo 14 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 15 de Oficios','Słowo 15 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 16 de Oficios','Słowo 16 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 17 de Oficios','Słowo 17 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 18 de Oficios','Słowo 18 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 19 de Oficios','Słowo 19 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 20 de Oficios','Słowo 20 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 21 de Oficios','Słowo 21 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 22 de Oficios','Słowo 22 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 23 de Oficios','Słowo 23 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 24 de Oficios','Słowo 24 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 25 de Oficios','Słowo 25 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 26 de Oficios','Słowo 26 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 27 de Oficios','Słowo 27 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 28 de Oficios','Słowo 28 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 29 de Oficios','Słowo 29 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 30 de Oficios','Słowo 30 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 31 de Oficios','Słowo 31 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 32 de Oficios','Słowo 32 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 33 de Oficios','Słowo 33 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 34 de Oficios','Słowo 34 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 35 de Oficios','Słowo 35 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 36 de Oficios','Słowo 36 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 37 de Oficios','Słowo 37 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 38 de Oficios','Słowo 38 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 39 de Oficios','Słowo 39 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 40 de Oficios','Słowo 40 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 41 de Oficios','Słowo 41 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 42 de Oficios','Słowo 42 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 43 de Oficios','Słowo 43 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 44 de Oficios','Słowo 44 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 45 de Oficios','Słowo 45 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 46 de Oficios','Słowo 46 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 47 de Oficios','Słowo 47 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 48 de Oficios','Słowo 48 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 49 de Oficios','Słowo 49 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 50 de Oficios','Słowo 50 z Rzemiosło/Fachy'),
('Trabajo y Empleo','Praca i zatrudnienie','el trabajo','praca'),
('Trabajo y Empleo','Praca i zatrudnienie','el empleo','zatrudnienie / posada'),
('Trabajo y Empleo','Praca i zatrudnienie','el empleado','pracownik'),
('Trabajo y Empleo','Praca i zatrudnienie','el empleador','pracodawca'),
('Trabajo y Empleo','Praca i zatrudnienie','el jefe / la jefa','szef / szefowa'),
('Trabajo y Empleo','Praca i zatrudnienie','el gerente','menedżer / kierownik'),
('Trabajo y Empleo','Praca i zatrudnienie','el director','dyrektor'),
('Trabajo y Empleo','Praca i zatrudnienie','el compañero de trabajo','kolega z pracy'),
('Trabajo y Empleo','Praca i zatrudnienie','la empresa / la compañía','firma / przedsiębiorstwo'),
('Trabajo y Empleo','Praca i zatrudnienie','la oficina','biuro'),
('Trabajo y Empleo','Praca i zatrudnienie','el departamento','dział / wydział'),
('Trabajo y Empleo','Praca i zatrudnienie','el horario','godziny pracy / harmonogram'),
('Trabajo y Empleo','Praca i zatrudnienie','el turno','zmiana (w pracy)'),
('Trabajo y Empleo','Praca i zatrudnienie','la jornada laboral','dzień pracy'),
('Trabajo y Empleo','Praca i zatrudnienie','el descanso','przerwa'),
('Trabajo y Empleo','Praca i zatrudnienie','el salario / el sueldo','pensja / wynagrodzenie'),
('Trabajo y Empleo','Praca i zatrudnienie','la nómina','lista płac (odcinek wypłaty)'),
('Trabajo y Empleo','Praca i zatrudnienie','el contrato','umowa / kontrakt'),
('Trabajo y Empleo','Praca i zatrudnienie','el contrato fijo','umowa na czas nieokreślony'),
('Trabajo y Empleo','Praca i zatrudnienie','el contrato temporal','umowa na czas określony'),
('Trabajo y Empleo','Praca i zatrudnienie','firmar','podpisywać'),
('Trabajo y Empleo','Praca i zatrudnienie','despedir','zwalniać (z pracy)'),
('Trabajo y Empleo','Praca i zatrudnienie','el despido','zwolnienie'),
('Trabajo y Empleo','Praca i zatrudnienie','renunciar / dimitir','zrezygnować / złożyć wypowiedzenie'),
('Trabajo y Empleo','Praca i zatrudnienie','la renuncia / la dimisión','rezygnacja / dymisja'),
('Trabajo y Empleo','Praca i zatrudnienie','el paro / el desempleo','bezrobocie'),
('Trabajo y Empleo','Praca i zatrudnienie','el parado','bezrobotny'),
('Trabajo y Empleo','Praca i zatrudnienie','la huelga','strajk'),
('Trabajo y Empleo','Praca i zatrudnienie','el sindicato','związek zawodowy'),
('Trabajo y Empleo','Praca i zatrudnienie','la jubilación','emerytura'),
('Trabajo y Empleo','Praca i zatrudnienie','jubilarse','przejść na emeryturę'),
('Trabajo y Empleo','Praca i zatrudnienie','el ascenso','awans'),
('Trabajo y Empleo','Praca i zatrudnienie','ascender','awansować'),
('Trabajo y Empleo','Praca i zatrudnienie','la vacante','wakat / wolne stanowisko'),
('Trabajo y Empleo','Praca i zatrudnienie','contratar','zatrudniać'),
('Trabajo y Empleo','Praca i zatrudnienie','la experiencia','doświadczenie'),
('Trabajo y Empleo','Praca i zatrudnienie','el currículum (CV)','CV (życiorys)'),
('Trabajo y Empleo','Praca i zatrudnienie','la entrevista','rozmowa kwalifikacyjna'),
('Trabajo y Empleo','Praca i zatrudnienie','los recursos humanos (RRHH)','dział kadr / HR'),
('Trabajo y Empleo','Praca i zatrudnienie','el teletrabajo','praca zdalna'),
('Trabajo y Empleo','Praca i zatrudnienie','las vacaciones','urlop / wakacje'),
('Trabajo y Empleo','Praca i zatrudnienie','la baja laboral','zwolnienie lekarskie (L4)'),
('Trabajo y Empleo','Praca i zatrudnienie','el seguro','ubezpieczenie'),
('Trabajo y Empleo','Praca i zatrudnienie','los impuestos','podatki'),
('Trabajo y Empleo','Praca i zatrudnienie','la paga extra','dodatkowa pensja / trzynastka'),
('Trabajo y Empleo','Praca i zatrudnienie','cobrar','zarabiać / pobierać (pieniądze)'),
('Trabajo y Empleo','Praca i zatrudnienie','ganar','zarabiać (też: wygrywać)'),
('Trabajo y Empleo','Praca i zatrudnienie','trabajar','pracować'),
('Trabajo y Empleo','Praca i zatrudnienie','fichar','odbijać kartę / rejestrować czas pracy'),
('Trabajo y Empleo','Praca i zatrudnienie','el día libre','dzień wolny'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 1 de Entrevista de Trabajo','Słowo 1 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 2 de Entrevista de Trabajo','Słowo 2 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 3 de Entrevista de Trabajo','Słowo 3 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 4 de Entrevista de Trabajo','Słowo 4 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 5 de Entrevista de Trabajo','Słowo 5 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 6 de Entrevista de Trabajo','Słowo 6 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 7 de Entrevista de Trabajo','Słowo 7 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 8 de Entrevista de Trabajo','Słowo 8 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 9 de Entrevista de Trabajo','Słowo 9 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 10 de Entrevista de Trabajo','Słowo 10 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 11 de Entrevista de Trabajo','Słowo 11 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 12 de Entrevista de Trabajo','Słowo 12 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 13 de Entrevista de Trabajo','Słowo 13 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 14 de Entrevista de Trabajo','Słowo 14 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 15 de Entrevista de Trabajo','Słowo 15 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 16 de Entrevista de Trabajo','Słowo 16 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 17 de Entrevista de Trabajo','Słowo 17 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 18 de Entrevista de Trabajo','Słowo 18 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 19 de Entrevista de Trabajo','Słowo 19 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 20 de Entrevista de Trabajo','Słowo 20 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 21 de Entrevista de Trabajo','Słowo 21 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 22 de Entrevista de Trabajo','Słowo 22 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 23 de Entrevista de Trabajo','Słowo 23 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 24 de Entrevista de Trabajo','Słowo 24 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 25 de Entrevista de Trabajo','Słowo 25 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 26 de Entrevista de Trabajo','Słowo 26 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 27 de Entrevista de Trabajo','Słowo 27 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 28 de Entrevista de Trabajo','Słowo 28 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 29 de Entrevista de Trabajo','Słowo 29 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 30 de Entrevista de Trabajo','Słowo 30 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 31 de Entrevista de Trabajo','Słowo 31 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 32 de Entrevista de Trabajo','Słowo 32 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 33 de Entrevista de Trabajo','Słowo 33 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 34 de Entrevista de Trabajo','Słowo 34 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 35 de Entrevista de Trabajo','Słowo 35 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 36 de Entrevista de Trabajo','Słowo 36 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 37 de Entrevista de Trabajo','Słowo 37 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 38 de Entrevista de Trabajo','Słowo 38 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 39 de Entrevista de Trabajo','Słowo 39 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 40 de Entrevista de Trabajo','Słowo 40 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 41 de Entrevista de Trabajo','Słowo 41 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 42 de Entrevista de Trabajo','Słowo 42 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 43 de Entrevista de Trabajo','Słowo 43 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 44 de Entrevista de Trabajo','Słowo 44 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 45 de Entrevista de Trabajo','Słowo 45 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 46 de Entrevista de Trabajo','Słowo 46 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 47 de Entrevista de Trabajo','Słowo 47 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 48 de Entrevista de Trabajo','Słowo 48 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 49 de Entrevista de Trabajo','Słowo 49 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 50 de Entrevista de Trabajo','Słowo 50 z Rozmowa kwalifikacyjna'),
('Contabilidad','Księgowość','Palabra 1 de Contabilidad','Słowo 1 z Księgowość'),
('Contabilidad','Księgowość','Palabra 2 de Contabilidad','Słowo 2 z Księgowość'),
('Contabilidad','Księgowość','Palabra 3 de Contabilidad','Słowo 3 z Księgowość'),
('Contabilidad','Księgowość','Palabra 4 de Contabilidad','Słowo 4 z Księgowość'),
('Contabilidad','Księgowość','Palabra 5 de Contabilidad','Słowo 5 z Księgowość'),
('Contabilidad','Księgowość','Palabra 6 de Contabilidad','Słowo 6 z Księgowość'),
('Contabilidad','Księgowość','Palabra 7 de Contabilidad','Słowo 7 z Księgowość'),
('Contabilidad','Księgowość','Palabra 8 de Contabilidad','Słowo 8 z Księgowość'),
('Contabilidad','Księgowość','Palabra 9 de Contabilidad','Słowo 9 z Księgowość'),
('Contabilidad','Księgowość','Palabra 10 de Contabilidad','Słowo 10 z Księgowość'),
('Contabilidad','Księgowość','Palabra 11 de Contabilidad','Słowo 11 z Księgowość'),
('Contabilidad','Księgowość','Palabra 12 de Contabilidad','Słowo 12 z Księgowość'),
('Contabilidad','Księgowość','Palabra 13 de Contabilidad','Słowo 13 z Księgowość'),
('Contabilidad','Księgowość','Palabra 14 de Contabilidad','Słowo 14 z Księgowość'),
('Contabilidad','Księgowość','Palabra 15 de Contabilidad','Słowo 15 z Księgowość'),
('Contabilidad','Księgowość','Palabra 16 de Contabilidad','Słowo 16 z Księgowość'),
('Contabilidad','Księgowość','Palabra 17 de Contabilidad','Słowo 17 z Księgowość'),
('Contabilidad','Księgowość','Palabra 18 de Contabilidad','Słowo 18 z Księgowość'),
('Contabilidad','Księgowość','Palabra 19 de Contabilidad','Słowo 19 z Księgowość'),
('Contabilidad','Księgowość','Palabra 20 de Contabilidad','Słowo 20 z Księgowość'),
('Contabilidad','Księgowość','Palabra 21 de Contabilidad','Słowo 21 z Księgowość'),
('Contabilidad','Księgowość','Palabra 22 de Contabilidad','Słowo 22 z Księgowość'),
('Contabilidad','Księgowość','Palabra 23 de Contabilidad','Słowo 23 z Księgowość'),
('Contabilidad','Księgowość','Palabra 24 de Contabilidad','Słowo 24 z Księgowość'),
('Contabilidad','Księgowość','Palabra 25 de Contabilidad','Słowo 25 z Księgowość'),
('Contabilidad','Księgowość','Palabra 26 de Contabilidad','Słowo 26 z Księgowość'),
('Contabilidad','Księgowość','Palabra 27 de Contabilidad','Słowo 27 z Księgowość'),
('Contabilidad','Księgowość','Palabra 28 de Contabilidad','Słowo 28 z Księgowość'),
('Contabilidad','Księgowość','Palabra 29 de Contabilidad','Słowo 29 z Księgowość'),
('Contabilidad','Księgowość','Palabra 30 de Contabilidad','Słowo 30 z Księgowość'),
('Contabilidad','Księgowość','Palabra 31 de Contabilidad','Słowo 31 z Księgowość'),
('Contabilidad','Księgowość','Palabra 32 de Contabilidad','Słowo 32 z Księgowość'),
('Contabilidad','Księgowość','Palabra 33 de Contabilidad','Słowo 33 z Księgowość'),
('Contabilidad','Księgowość','Palabra 34 de Contabilidad','Słowo 34 z Księgowość'),
('Contabilidad','Księgowość','Palabra 35 de Contabilidad','Słowo 35 z Księgowość'),
('Contabilidad','Księgowość','Palabra 36 de Contabilidad','Słowo 36 z Księgowość'),
('Contabilidad','Księgowość','Palabra 37 de Contabilidad','Słowo 37 z Księgowość'),
('Contabilidad','Księgowość','Palabra 38 de Contabilidad','Słowo 38 z Księgowość'),
('Contabilidad','Księgowość','Palabra 39 de Contabilidad','Słowo 39 z Księgowość'),
('Contabilidad','Księgowość','Palabra 40 de Contabilidad','Słowo 40 z Księgowość'),
('Contabilidad','Księgowość','Palabra 41 de Contabilidad','Słowo 41 z Księgowość'),
('Contabilidad','Księgowość','Palabra 42 de Contabilidad','Słowo 42 z Księgowość'),
('Contabilidad','Księgowość','Palabra 43 de Contabilidad','Słowo 43 z Księgowość'),
('Contabilidad','Księgowość','Palabra 44 de Contabilidad','Słowo 44 z Księgowość'),
('Contabilidad','Księgowość','Palabra 45 de Contabilidad','Słowo 45 z Księgowość'),
('Contabilidad','Księgowość','Palabra 46 de Contabilidad','Słowo 46 z Księgowość'),
('Contabilidad','Księgowość','Palabra 47 de Contabilidad','Słowo 47 z Księgowość'),
('Contabilidad','Księgowość','Palabra 48 de Contabilidad','Słowo 48 z Księgowość'),
('Contabilidad','Księgowość','Palabra 49 de Contabilidad','Słowo 49 z Księgowość'),
('Contabilidad','Księgowość','Palabra 50 de Contabilidad','Słowo 50 z Księgowość'),
('Banca y Finanzas','Bankowość i finanse','el banco','bank'),
('Banca y Finanzas','Bankowość i finanse','el cajero automático','bankomat'),
('Banca y Finanzas','Bankowość i finanse','la cuenta','konto'),
('Banca y Finanzas','Bankowość i finanse','la tarjeta de crédito','karta kredytowa'),
('Banca y Finanzas','Bankowość i finanse','la tarjeta de débito','karta debetowa'),
('Banca y Finanzas','Bankowość i finanse','la cuenta corriente','rachunek bieżący'),
('Banca y Finanzas','Bankowość i finanse','la cuenta de ahorros','konto oszczędnościowe'),
('Banca y Finanzas','Bankowość i finanse','el saldo','saldo'),
('Banca y Finanzas','Bankowość i finanse','la transferencia','przelew'),
('Banca y Finanzas','Bankowość i finanse','ingresar dinero','wpłacać pieniądze'),
('Banca y Finanzas','Bankowość i finanse','sacar dinero','wypłacać pieniądze'),
('Banca y Finanzas','Bankowość i finanse','el préstamo','pożyczka / kredyt'),
('Banca y Finanzas','Bankowość i finanse','la hipoteca','hipoteka / kredyt hipoteczny'),
('Banca y Finanzas','Bankowość i finanse','el interés','odsetki'),
('Banca y Finanzas','Bankowość i finanse','el tipo de interés','stopa procentowa'),
('Banca y Finanzas','Bankowość i finanse','la comisión','prowizja'),
('Banca y Finanzas','Bankowość i finanse','el crédito','kredyt'),
('Banca y Finanzas','Bankowość i finanse','la deuda','dług'),
('Banca y Finanzas','Bankowość i finanse','el cheque','czek'),
('Banca y Finanzas','Bankowość i finanse','el cobro','inkaso / pobranie opłaty'),
('Banca y Finanzas','Bankowość i finanse','la divisa','waluta'),
('Banca y Finanzas','Bankowość i finanse','el tipo de cambio','kurs wymiany walut'),
('Banca y Finanzas','Bankowość i finanse','la sucursal','oddział (banku)'),
('Banca y Finanzas','Bankowość i finanse','el banquero','bankier'),
('Banca y Finanzas','Bankowość i finanse','la inversión','inwestycja'),
('Banca y Finanzas','Bankowość i finanse','el inversor','inwestor'),
('Banca y Finanzas','Bankowość i finanse','el fondo de inversión','fundusz inwestycyjny'),
('Banca y Finanzas','Bankowość i finanse','la bolsa de valores','giełda papierów wartościowych'),
('Banca y Finanzas','Bankowość i finanse','la acción','akcja (giełdowa)'),
('Banca y Finanzas','Bankowość i finanse','el dividendo','dywidenda'),
('Banca y Finanzas','Bankowość i finanse','el riesgo','ryzyko'),
('Banca y Finanzas','Bankowość i finanse','la rentabilidad','rentowność / zyskowność'),
('Banca y Finanzas','Bankowość i finanse','el capital','kapitał'),
('Banca y Finanzas','Bankowość i finanse','el activo','aktywa'),
('Banca y Finanzas','Bankowość i finanse','el pasivo','pasywa'),
('Banca y Finanzas','Bankowość i finanse','el cajero','kasjer'),
('Banca y Finanzas','Bankowość i finanse','el pin','PIN'),
('Banca y Finanzas','Bankowość i finanse','la contraseña','hasło'),
('Banca y Finanzas','Bankowość i finanse','bloquear','zablokować (kartę/konto)'),
('Banca y Finanzas','Bankowość i finanse','la banca online','bankowość internetowa'),
('Banca y Finanzas','Bankowość i finanse','el estado de cuenta','wyciąg z konta'),
('Banca y Finanzas','Bankowość i finanse','la liquidación','rozliczenie'),
('Banca y Finanzas','Bankowość i finanse','el plazo fijo','lokata terminowa'),
('Banca y Finanzas','Bankowość i finanse','endeudarse','zadłużać się'),
('Banca y Finanzas','Bankowość i finanse','ahorrar','oszczędzać'),
('Banca y Finanzas','Bankowość i finanse','el préstamo personal','pożyczka gotówkowa'),
('Banca y Finanzas','Bankowość i finanse','el aval','poręczenie / żyrant'),
('Banca y Finanzas','Bankowość i finanse','la domiciliación','polecenie zapłaty'),
('Banca y Finanzas','Bankowość i finanse','domiciliar','zlecić stałą płatność'),
('Banca y Finanzas','Bankowość i finanse','el crédito hipotecario','kredyt hipoteczny'),
('Impuestos','Podatki','el impuesto','podatek'),
('Impuestos','Podatki','la declaración de la renta','zeznanie podatkowe (PIT)'),
('Impuestos','Podatki','el contribuyente','podatnik'),
('Impuestos','Podatki','la Agencia Tributaria / Hacienda','Urząd Skarbowy'),
('Impuestos','Podatki','el IVA (Impuesto sobre el Valor Añadido)','VAT (podatek od towarów i usług)'),
('Impuestos','Podatki','el IRPF','podatek dochodowy od osób fizycznych'),
('Impuestos','Podatki','la tasa','opłata (urzędowa) / podatek'),
('Impuestos','Podatki','el arancel','cło'),
('Impuestos','Podatki','gravar','opodatkować'),
('Impuestos','Podatki','exento','zwolniony (z podatku)'),
('Impuestos','Podatki','la deducción','odliczenie'),
('Impuestos','Podatki','deducir','odliczyć (od podatku)'),
('Impuestos','Podatki','el paraíso fiscal','raj podatkowy'),
('Impuestos','Podatki','la evasión fiscal','uchylanie się od płacenia podatków'),
('Impuestos','Podatki','el fraude fiscal','oszustwo podatkowe'),
('Impuestos','Podatki','la inspección','kontrola (skarbowa)'),
('Impuestos','Podatki','la multa','mandat / grzywna'),
('Impuestos','Podatki','la sanción','kara / sankcja'),
('Impuestos','Podatki','el recargo','dopłata / narzut'),
('Impuestos','Podatki','pagar impuestos','płacić podatki'),
('Impuestos','Podatki','la devolución','zwrot (podatku)'),
('Impuestos','Podatki','el borrador','szkic / wstępne zeznanie'),
('Impuestos','Podatki','el ejercicio fiscal','rok podatkowy'),
('Impuestos','Podatki','los ingresos','przychody'),
('Impuestos','Podatki','los gastos','wydatki'),
('Impuestos','Podatki','la retención','potrącenie (zaliczka na podatek)'),
('Impuestos','Podatki','el impuesto de sociedades','podatek dochodowy od osób prawnych (CIT)'),
('Impuestos','Podatki','el impuesto sobre el patrimonio','podatek majątkowy'),
('Impuestos','Podatki','el impuesto de sucesiones','podatek od spadków'),
('Impuestos','Podatki','la base imponible','podstawa opodatkowania'),
('Impuestos','Podatki','la cuota','składka / kwota (podatku)'),
('Impuestos','Podatki','el tipo impositivo','stawka podatkowa'),
('Impuestos','Podatki','la liquidación','rozliczenie podatku'),
('Impuestos','Podatki','el asesor fiscal','doradca podatkowy'),
('Impuestos','Podatki','la fiscalidad','system podatkowy'),
('Impuestos','Podatki','cotizar','płacić składki / wyceniać'),
('Impuestos','Podatki','la Seguridad Social','Zakład Ubezpieczeń Społecznych (ZUS)'),
('Impuestos','Podatki','la contribución','składka / wkład'),
('Impuestos','Podatki','el deber','obowiązek'),
('Impuestos','Podatki','el fisco','fiskus'),
('Impuestos','Podatki','el importe','kwota / suma'),
('Impuestos','Podatki','declarar','deklarować (dochody)'),
('Impuestos','Podatki','el impuesto indirecto','podatek pośredni'),
('Impuestos','Podatki','el impuesto directo','podatek bezpośredni'),
('Impuestos','Podatki','la moratoria','moratorium (odroczenie)'),
('Impuestos','Podatki','aplazar','odroczyć'),
('Impuestos','Podatki','la multa por retraso','kara za opóźnienie'),
('Impuestos','Podatki','la auditoría','audyt / rewizja'),
('Impuestos','Podatki','evadir impuestos','unikać płacenia podatków'),
('Impuestos','Podatki','la amnistía fiscal','amnestia podatkowa'),
('Economía Global','Gospodarka globalna','la economía','gospodarka / ekonomia'),
('Economía Global','Gospodarka globalna','el crecimiento','wzrost'),
('Economía Global','Gospodarka globalna','la recesión','recesja'),
('Economía Global','Gospodarka globalna','la crisis','kryzys'),
('Economía Global','Gospodarka globalna','la inflación','inflacja'),
('Economía Global','Gospodarka globalna','la deflación','deflacja'),
('Economía Global','Gospodarka globalna','el Producto Interior Bruto (PIB)','Produkt Krajowy Brutto (PKB)'),
('Economía Global','Gospodarka globalna','el mercado','rynek'),
('Economía Global','Gospodarka globalna','la demanda','popyt'),
('Economía Global','Gospodarka globalna','la oferta','podaż'),
('Economía Global','Gospodarka globalna','el monopolio','monopol'),
('Economía Global','Gospodarka globalna','la competencia','konkurencja'),
('Economía Global','Gospodarka globalna','la globalización','globalizacja'),
('Economía Global','Gospodarka globalna','el desarrollo','rozwój'),
('Economía Global','Gospodarka globalna','subdesarrollado','słabo rozwinięty'),
('Economía Global','Gospodarka globalna','el país en vías de desarrollo','kraj rozwijający się'),
('Economía Global','Gospodarka globalna','el primer mundo','pierwszy świat (kraje rozwinięte)'),
('Economía Global','Gospodarka globalna','el tercer mundo','trzeci świat'),
('Economía Global','Gospodarka globalna','la riqueza','bogactwo'),
('Economía Global','Gospodarka globalna','la pobreza','ubóstwo / bieda'),
('Economía Global','Gospodarka globalna','la desigualdad','nierówność'),
('Economía Global','Gospodarka globalna','la macroeconomía','makroekonomia'),
('Economía Global','Gospodarka globalna','la microeconomía','mikroekonomia'),
('Economía Global','Gospodarka globalna','la política económica','polityka gospodarcza'),
('Economía Global','Gospodarka globalna','la deuda externa','dług zagraniczny'),
('Economía Global','Gospodarka globalna','la tasa de desempleo','stopa bezrobocia'),
('Economía Global','Gospodarka globalna','el poder adquisitivo','siła nabywcza'),
('Economía Global','Gospodarka globalna','el sector primario','sektor pierwszy (rolnictwo)'),
('Economía Global','Gospodarka globalna','el sector secundario','sektor drugi (przemysł)'),
('Economía Global','Gospodarka globalna','el sector terciario','sektor trzeci (usługi)'),
('Economía Global','Gospodarka globalna','la bolsa','giełda'),
('Economía Global','Gospodarka globalna','el mercado de valores','rynek papierów wartościowych'),
('Economía Global','Gospodarka globalna','el índice bursátil','indeks giełdowy'),
('Economía Global','Gospodarka globalna','la cotización','notowanie (na giełdzie)'),
('Economía Global','Gospodarka globalna','el capitalismo','kapitalizm'),
('Economía Global','Gospodarka globalna','el comunismo','komunizm'),
('Economía Global','Gospodarka globalna','el libre mercado','wolny rynek'),
('Economía Global','Gospodarka globalna','la privatización','prywatyzacja'),
('Economía Global','Gospodarka globalna','la nacionalización','nacjonalizacja'),
('Economía Global','Gospodarka globalna','el déficit','deficyt'),
('Economía Global','Gospodarka globalna','el superávit','nadwyżka'),
('Economía Global','Gospodarka globalna','la divisa','waluta zagraniczna'),
('Economía Global','Gospodarka globalna','el mercado de divisas','rynek walutowy'),
('Economía Global','Gospodarka globalna','el Fondo Monetario Internacional (FMI)','Międzynarodowy Fundusz Walutowy (MFW)'),
('Economía Global','Gospodarka globalna','el Banco Mundial','Bank Światowy'),
('Economía Global','Gospodarka globalna','la ayuda humanitaria','pomoc humanitarna'),
('Economía Global','Gospodarka globalna','el comercio justo','sprawiedliwy handel (fair trade)'),
('Economía Global','Gospodarka globalna','la materia prima','surowiec'),
('Economía Global','Gospodarka globalna','la producción','produkcja'),
('Economía Global','Gospodarka globalna','el consumo','konsumpcja'),
('Comercio Internacional','Handel międzynarodowy','el comercio','handel'),
('Comercio Internacional','Handel międzynarodowy','internacional','międzynarodowy'),
('Comercio Internacional','Handel międzynarodowy','la exportación','eksport'),
('Comercio Internacional','Handel międzynarodowy','exportar','eksportować'),
('Comercio Internacional','Handel międzynarodowy','la importación','import'),
('Comercio Internacional','Handel międzynarodowy','importar','importować'),
('Comercio Internacional','Handel międzynarodowy','la aduana','urząd celny / cło'),
('Comercio Internacional','Handel międzynarodowy','el arancel','cło / taryfa celna'),
('Comercio Internacional','Handel międzynarodowy','el acuerdo comercial','umowa handlowa'),
('Comercio Internacional','Handel międzynarodowy','el tratado','traktat'),
('Comercio Internacional','Handel międzynarodowy','el mercado extranjero','rynek zagraniczny'),
('Comercio Internacional','Handel międzynarodowy','la barrera comercial','bariera handlowa'),
('Comercio Internacional','Handel międzynarodowy','el libre comercio','wolny handel'),
('Comercio Internacional','Handel międzynarodowy','la cuota','kontyngent / przydział'),
('Comercio Internacional','Handel międzynarodowy','la frontera','granica'),
('Comercio Internacional','Handel międzynarodowy','el puerto','port'),
('Comercio Internacional','Handel międzynarodowy','el contenedor','kontener'),
('Comercio Internacional','Handel międzynarodowy','la logística','logistyka'),
('Comercio Internacional','Handel międzynarodowy','el transporte','transport'),
('Comercio Internacional','Handel międzynarodowy','el flete','fracht (opłata za transport)'),
('Comercio Internacional','Handel międzynarodowy','el envío','wysyłka / przesyłka'),
('Comercio Internacional','Handel międzynarodowy','la naviera','firma żeglugowa / armator'),
('Comercio Internacional','Handel międzynarodowy','el proveedor','dostawca'),
('Comercio Internacional','Handel międzynarodowy','el cliente','klient'),
('Comercio Internacional','Handel międzynarodowy','el mercado interior','rynek wewnętrzny'),
('Comercio Internacional','Handel międzynarodowy','el socio comercial','partner handlowy'),
('Comercio Internacional','Handel międzynarodowy','la balanza comercial','bilans handlowy'),
('Comercio Internacional','Handel międzynarodowy','el déficit comercial','deficyt handlowy'),
('Comercio Internacional','Handel międzynarodowy','el superávit comercial','nadwyżka handlowa'),
('Comercio Internacional','Handel międzynarodowy','la Organización Mundial del Comercio (OMC)','Światowa Organizacja Handlu (WTO)'),
('Comercio Internacional','Handel międzynarodowy','el certificado de origen','świadectwo pochodzenia'),
('Comercio Internacional','Handel międzynarodowy','el despacho de aduanas','odprawa celna'),
('Comercio Internacional','Handel międzynarodowy','el importador','importer'),
('Comercio Internacional','Handel międzynarodowy','el exportador','eksporter'),
('Comercio Internacional','Handel międzynarodowy','el mercado global','rynek globalny'),
('Comercio Internacional','Handel międzynarodowy','la competitividad','konkurencyjność'),
('Comercio Internacional','Handel międzynarodowy','competitivo','konkurencyjny'),
('Comercio Internacional','Handel międzynarodowy','el tratado de libre comercio (TLC)','porozumienie o wolnym handlu'),
('Comercio Internacional','Handel międzynarodowy','el embargo','embargo'),
('Comercio Internacional','Handel międzynarodowy','la sanción comercial','sankcja handlowa'),
('Comercio Internacional','Handel międzynarodowy','la mercancía','towar / ładunek'),
('Comercio Internacional','Handel międzynarodowy','el producto','produkt'),
('Comercio Internacional','Handel międzynarodowy','manufacturar','produkować (przemysłowo)'),
('Comercio Internacional','Handel międzynarodowy','los bienes','dobra / towary'),
('Comercio Internacional','Handel międzynarodowy','los bienes de consumo','dobra konsumpcyjne'),
('Comercio Internacional','Handel międzynarodowy','la cadena de suministro','łańcuch dostaw'),
('Comercio Internacional','Handel międzynarodowy','el distribuidor','dystrybutor'),
('Comercio Internacional','Handel międzynarodowy','la distribución','dystrybucja'),
('Comercio Internacional','Handel międzynarodowy','el mercado emergente','rynek wschodzący'),
('Comercio Internacional','Handel międzynarodowy','la divisa','waluta obca'),
('Marketing y Publicidad','Marketing i reklama','el marketing / la mercadotecnia','marketing'),
('Marketing y Publicidad','Marketing i reklama','la publicidad','reklama (branża)'),
('Marketing y Publicidad','Marketing i reklama','el anuncio','reklama (pojedyncza) / ogłoszenie'),
('Marketing y Publicidad','Marketing i reklama','anunciar','reklamować / ogłaszać'),
('Marketing y Publicidad','Marketing i reklama','la campaña publicitaria','kampania reklamowa'),
('Marketing y Publicidad','Marketing i reklama','el público objetivo','grupa docelowa (target)'),
('Marketing y Publicidad','Marketing i reklama','el cliente potencial','potencjalny klient'),
('Marketing y Publicidad','Marketing i reklama','la estrategia','strategia'),
('Marketing y Publicidad','Marketing i reklama','la marca','marka'),
('Marketing y Publicidad','Marketing i reklama','el logotipo','logotyp / logo'),
('Marketing y Publicidad','Marketing i reklama','el eslogan','slogan / hasło reklamowe'),
('Marketing y Publicidad','Marketing i reklama','el consumidor','konsument'),
('Marketing y Publicidad','Marketing i reklama','consumir','konsumować'),
('Marketing y Publicidad','Marketing i reklama','el mercado','rynek'),
('Marketing y Publicidad','Marketing i reklama','la cuota de mercado','udział w rynku'),
('Marketing y Publicidad','Marketing i reklama','el estudio de mercado','badanie rynku'),
('Marketing y Publicidad','Marketing i reklama','el producto','produkt'),
('Marketing y Publicidad','Marketing i reklama','el precio','cena'),
('Marketing y Publicidad','Marketing i reklama','la promoción','promocja'),
('Marketing y Publicidad','Marketing i reklama','la distribución','dystrybucja'),
('Marketing y Publicidad','Marketing i reklama','el folleto','ulotka / broszura'),
('Marketing y Publicidad','Marketing i reklama','el cartel / el póster','plakat'),
('Marketing y Publicidad','Marketing i reklama','el patrocinador','sponsor'),
('Marketing y Publicidad','Marketing i reklama','patrocinar','sponsorować'),
('Marketing y Publicidad','Marketing i reklama','el evento','wydarzenie (event)'),
('Marketing y Publicidad','Marketing i reklama','las redes sociales','media społecznościowe'),
('Marketing y Publicidad','Marketing i reklama','el marketing digital','marketing cyfrowy'),
('Marketing y Publicidad','Marketing i reklama','el correo basura (spam)','spam'),
('Marketing y Publicidad','Marketing i reklama','el boletín (newsletter)','biuletyn (newsletter)'),
('Marketing y Publicidad','Marketing i reklama','la encuesta','ankieta / sondaż'),
('Marketing y Publicidad','Marketing i reklama','la satisfacción del cliente','satysfakcja klienta'),
('Marketing y Publicidad','Marketing i reklama','la fidelización','budowanie lojalności'),
('Marketing y Publicidad','Marketing i reklama','fidelizar','budować lojalność (klienta)'),
('Marketing y Publicidad','Marketing i reklama','la oferta','oferta'),
('Marketing y Publicidad','Marketing i reklama','el descuento','zniżka / rabat'),
('Marketing y Publicidad','Marketing i reklama','el posicionamiento','pozycjonowanie'),
('Marketing y Publicidad','Marketing i reklama','la agencia de publicidad','agencja reklamowa'),
('Marketing y Publicidad','Marketing i reklama','el presupuesto','budżet'),
('Marketing y Publicidad','Marketing i reklama','la creatividad','kreatywność'),
('Marketing y Publicidad','Marketing i reklama','viral','wirusowy (viral)'),
('Marketing y Publicidad','Marketing i reklama','el anuncio de televisión','reklama telewizyjna / spot'),
('Marketing y Publicidad','Marketing i reklama','el banner','baner internetowy'),
('Marketing y Publicidad','Marketing i reklama','las relaciones públicas','public relations (PR)'),
('Marketing y Publicidad','Marketing i reklama','la imagen de marca','wizerunek marki'),
('Marketing y Publicidad','Marketing i reklama','el boca a boca','marketing szeptany (poczta pantoflowa)'),
('Marketing y Publicidad','Marketing i reklama','persuadir','przekonywać'),
('Marketing y Publicidad','Marketing i reklama','la competencia','konkurencja'),
('Marketing y Publicidad','Marketing i reklama','el catálogo','katalog'),
('Marketing y Publicidad','Marketing i reklama','el lanzamiento','wprowadzenie (na rynek)'),
('Marketing y Publicidad','Marketing i reklama','la promoción de ventas','promocja sprzedaży'),
('Atención al Cliente','Obsługa klienta','la atención al cliente','obsługa klienta'),
('Atención al Cliente','Obsługa klienta','el cliente','klient'),
('Atención al Cliente','Obsługa klienta','el consumidor','konsument'),
('Atención al Cliente','Obsługa klienta','el servicio','usługa / serwis'),
('Atención al Cliente','Obsługa klienta','el dependiente / la dependienta','sprzedawca / sprzedawczyni'),
('Atención al Cliente','Obsługa klienta','el cajero','kasjer'),
('Atención al Cliente','Obsługa klienta','el operador','operator'),
('Atención al Cliente','Obsługa klienta','el representante','przedstawiciel'),
('Atención al Cliente','Obsługa klienta','la reclamación','reklamacja'),
('Atención al Cliente','Obsługa klienta','reclamar','reklamować'),
('Atención al Cliente','Obsługa klienta','la queja','skarga'),
('Atención al Cliente','Obsługa klienta','quejarse','skarżyć się'),
('Atención al Cliente','Obsługa klienta','la devolución','zwrot (towaru)'),
('Atención al Cliente','Obsługa klienta','devolver','zwracać (towar)'),
('Atención al Cliente','Obsługa klienta','el reembolso','zwrot pieniędzy'),
('Atención al Cliente','Obsługa klienta','el cambio','wymiana'),
('Atención al Cliente','Obsługa klienta','la garantía','gwarancja'),
('Atención al Cliente','Obsługa klienta','el defecto','wada / defekt'),
('Atención al Cliente','Obsługa klienta','defectuoso','wadliwy'),
('Atención al Cliente','Obsługa klienta','roto','zepsuty / uszkodzony'),
('Atención al Cliente','Obsługa klienta','la avería','awaria'),
('Atención al Cliente','Obsługa klienta','reparar','naprawiać'),
('Atención al Cliente','Obsługa klienta','el servicio técnico','serwis techniczny'),
('Atención al Cliente','Obsługa klienta','la solución','rozwiązanie'),
('Atención al Cliente','Obsługa klienta','resolver','rozwiązywać'),
('Atención al Cliente','Obsługa klienta','la ayuda','pomoc'),
('Atención al Cliente','Obsługa klienta','ayudar','pomagać'),
('Atención al Cliente','Obsługa klienta','la información','informacja'),
('Atención al Cliente','Obsługa klienta','el mostrador de información','punkt informacyjny'),
('Atención al Cliente','Obsługa klienta','la línea de atención','infolinia'),
('Atención al Cliente','Obsługa klienta','llamar','dzwonić'),
('Atención al Cliente','Obsługa klienta','la llamada','połączenie telefoniczne'),
('Atención al Cliente','Obsługa klienta','la espera','oczekiwanie'),
('Atención al Cliente','Obsługa klienta','esperar','czekać'),
('Atención al Cliente','Obsługa klienta','la amabilidad','uprzejmość'),
('Atención al Cliente','Obsługa klienta','amable','uprzejmy'),
('Atención al Cliente','Obsługa klienta','la satisfacción','satysfakcja'),
('Atención al Cliente','Obsługa klienta','satisfecho','zadowolony'),
('Atención al Cliente','Obsługa klienta','insatisfecho','niezadowolony'),
('Atención al Cliente','Obsługa klienta','la encuesta de satisfacción','ankietas satysfakcji'),
('Atención al Cliente','Obsługa klienta','el formulario','formularz'),
('Atención al Cliente','Obsługa klienta','los datos','dane'),
('Atención al Cliente','Obsługa klienta','el ticket de compra','paragon'),
('Atención al Cliente','Obsługa klienta','el comprobante','dowód zakupu / pokwitowanie'),
('Atención al Cliente','Obsługa klienta','la factura','faktura'),
('Atención al Cliente','Obsługa klienta','el buzón de sugerencias','skrzynka na sugestie'),
('Atención al Cliente','Obsługa klienta','el trato','traktowanie / obsługa'),
('Atención al Cliente','Obsługa klienta','profesional','profesjonalny'),
('Atención al Cliente','Obsługa klienta','eficiente','wydajny / sprawny'),
('Atención al Cliente','Obsługa klienta','la paciencia','cierpliwość'),
('Gestión de Proyectos','Zarządzanie projektami','la gestión de proyectos','zarządzanie projektami'),
('Gestión de Proyectos','Zarządzanie projektami','el proyecto','projekt'),
('Gestión de Proyectos','Zarządzanie projektami','el director de proyectos / el jefe de proyecto','kierownik projektu / project manager'),
('Gestión de Proyectos','Zarządzanie projektami','el equipo','zespół'),
('Gestión de Proyectos','Zarządzanie projektami','la tarea','zadanie'),
('Gestión de Proyectos','Zarządzanie projektami','el objetivo','cel'),
('Gestión de Proyectos','Zarządzanie projektami','la meta','meta / zamierzenie'),
('Gestión de Proyectos','Zarządzanie projektami','el plazo','termin / deadline'),
('Gestión de Proyectos','Zarządzanie projektami','el cronograma / el calendario','harmonogram'),
('Gestión de Proyectos','Zarządzanie projektami','la planificación','planowanie'),
('Gestión de Proyectos','Zarządzanie projektami','planificar','planować'),
('Gestión de Proyectos','Zarządzanie projektami','el presupuesto','budżet'),
('Gestión de Proyectos','Zarządzanie projektami','los recursos','zasoby'),
('Gestión de Proyectos','Zarządzanie projektami','el riesgo','ryzyko'),
('Gestión de Proyectos','Zarządzanie projektami','la fase','faza / etap'),
('Gestión de Proyectos','Zarządzanie projektami','el hito','kamień milowy (milestone)'),
('Gestión de Proyectos','Zarządzanie projektami','el entregable','produkt końcowy / rezultat (deliverable)'),
('Gestión de Proyectos','Zarządzanie projektami','la reunión','spotkanie / zebranie'),
('Gestión de Proyectos','Zarządzanie projektami','el informe','raport'),
('Gestión de Proyectos','Zarządzanie projektami','el avance / el progreso','postęp'),
('Gestión de Proyectos','Zarządzanie projektami','coordinar','koordynować'),
('Gestión de Proyectos','Zarządzanie projektami','la coordinación','koordynacja'),
('Gestión de Proyectos','Zarządzanie projektami','ejecutar','wykonywać / realizować'),
('Gestión de Proyectos','Zarządzanie projektami','la ejecución','realizacja'),
('Gestión de Proyectos','Zarządzanie projektami','supervisar','nadzorować'),
('Gestión de Proyectos','Zarządzanie projektami','la supervisión','nadzór'),
('Gestión de Proyectos','Zarządzanie projektami','controlar','kontrolować'),
('Gestión de Proyectos','Zarządzanie projektami','el control de calidad','kontrola jakości'),
('Gestión de Proyectos','Zarządzanie projektami','el retraso','opóźnienie'),
('Gestión de Proyectos','Zarządzanie projektami','adelantado','przed czasem / z wyprzedzeniem'),
('Gestión de Proyectos','Zarządzanie projektami','el imprevisto','nieprzewidziana okoliczność'),
('Gestión de Proyectos','Zarządzanie projektami','resolver','rozwiązywać (problem)'),
('Gestión de Proyectos','Zarządzanie projektami','el enfoque ágil','zwinne podejście (Agile)'),
('Gestión de Proyectos','Zarządzanie projektami','el método ágil','metodologia Agile'),
('Gestión de Proyectos','Zarządzanie projektami','el marco de trabajo','framework / ramy pracy'),
('Gestión de Proyectos','Zarządzanie projektami','la metodología','metodologia'),
('Gestión de Proyectos','Zarządzanie projektami','el tablero Kanban','tablica Kanban'),
('Gestión de Proyectos','Zarządzanie projektami','la reunión de seguimiento','spotkanie statusowe'),
('Gestión de Proyectos','Zarządzanie projektami','el alcance','zakres projektu'),
('Gestión de Proyectos','Zarządzanie projektami','la estimación','szacowanie'),
('Gestión de Proyectos','Zarządzanie projektami','el éxito','sukces'),
('Gestión de Proyectos','Zarządzanie projektami','el fracaso','porażka'),
('Gestión de Proyectos','Zarządzanie projektami','la colaboración','współpraca'),
('Gestión de Proyectos','Zarządzanie projektami','colaborar','współpracować'),
('Gestión de Proyectos','Zarządzanie projektami','la prioridad','priorytet'),
('Gestión de Proyectos','Zarządzanie projektami','priorizar','ustalać priorytety'),
('Gestión de Proyectos','Zarządzanie projektami','el rendimiento','wydajność'),
('Gestión de Proyectos','Zarządzanie projektami','la eficiencia','efektywność'),
('Gestión de Proyectos','Zarządzanie projektami','la optimización','optymalizacja'),
('Gestión de Proyectos','Zarządzanie projektami','la gestión de riesgos','zarządzanie ryzykiem'),
('Informática: Hardware','Informatyka: Sprzęt','el hardware','sprzęt komputerowy'),
('Informática: Hardware','Informatyka: Sprzęt','el ordenador / la computadora','komputer'),
('Informática: Hardware','Informatyka: Sprzęt','el ordenador portátil','laptop'),
('Informática: Hardware','Informatyka: Sprzęt','el ordenador de sobremesa','komputer stacjonarny'),
('Informática: Hardware','Informatyka: Sprzęt','la tableta','tablet'),
('Informática: Hardware','Informatyka: Sprzęt','el teléfono inteligente / el móvil','smartfon'),
('Informática: Hardware','Informatyka: Sprzęt','la pantalla','ekran / monitor'),
('Informática: Hardware','Informatyka: Sprzęt','el teclado','klawiatura'),
('Informática: Hardware','Informatyka: Sprzęt','el ratón','myszka'),
('Informática: Hardware','Informatyka: Sprzęt','la torre','obudowa komputera / jednostka centralna'),
('Informática: Hardware','Informatyka: Sprzęt','la placa base','płyta główna'),
('Informática: Hardware','Informatyka: Sprzęt','el procesador / la CPU','procesor'),
('Informática: Hardware','Informatyka: Sprzęt','la memoria RAM','pamięć RAM'),
('Informática: Hardware','Informatyka: Sprzęt','el disco duro','dysk twardy'),
('Informática: Hardware','Informatyka: Sprzęt','el disco duro sólido (SSD)','dysk SSD'),
('Informática: Hardware','Informatyka: Sprzęt','la tarjeta gráfica','karta graficzna'),
('Informática: Hardware','Informatyka: Sprzęt','la fuente de alimentación','zasilacz'),
('Informática: Hardware','Informatyka: Sprzęt','el ventilador','wentylator'),
('Informática: Hardware','Informatyka: Sprzęt','el puerto USB','port USB'),
('Informática: Hardware','Informatyka: Sprzęt','la tarjeta de red','karta sieciowa'),
('Informática: Hardware','Informatyka: Sprzęt','la impresora','drukarka'),
('Informática: Hardware','Informatyka: Sprzęt','el escáner','skaner'),
('Informática: Hardware','Informatyka: Sprzęt','los altavoces','głośniki'),
('Informática: Hardware','Informatyka: Sprzęt','los auriculares','słuchawki'),
('Informática: Hardware','Informatyka: Sprzęt','el micrófono','mikrofon'),
('Informática: Hardware','Informatyka: Sprzęt','la cámara web','kamera internetowa'),
('Informática: Hardware','Informatyka: Sprzęt','el proyektor','projektor'),
('Informática: Hardware','Informatyka: Sprzęt','el cable','kabel'),
('Informática: Hardware','Informatyka: Sprzęt','el enchufe','wtyczka / gniazdko'),
('Informática: Hardware','Informatyka: Sprzęt','la batería','bateria'),
('Informática: Hardware','Informatyka: Sprzęt','el cargador','ładowarka'),
('Informática: Hardware','Informatyka: Sprzęt','la memoria USB / el lápiz de memoria','pendrive / pamięć USB'),
('Informática: Hardware','Informatyka: Sprzęt','el disco externo','dysk zewnętrzny'),
('Informática: Hardware','Informatyka: Sprzęt','la tarjeta de memoria','karta pamięci'),
('Informática: Hardware','Informatyka: Sprzęt','el lector de tarjetas','czytnik kart'),
('Informática: Hardware','Informatyka: Sprzęt','el router','router'),
('Informática: Hardware','Informatyka: Sprzęt','el módem','modem'),
('Informática: Hardware','Informatyka: Sprzęt','el componente','komponent / podzespół'),
('Informática: Hardware','Informatyka: Sprzęt','el dispositivo','urządzenie'),
('Informática: Hardware','Informatyka: Sprzęt','la pantalla táctil','ekran dotykowy'),
('Informática: Hardware','Informatyka: Sprzęt','el botón de encendido','przycisk zasilania'),
('Informática: Hardware','Informatyka: Sprzęt','la ranura','gniazdo / slot'),
('Informática: Hardware','Informatyka: Sprzęt','conectar','podłączać'),
('Informática: Hardware','Informatyka: Sprzęt','desconectar','odłączać'),
('Informática: Hardware','Informatyka: Sprzęt','averiado','zepsuty / uszkodzony'),
('Informática: Hardware','Informatyka: Sprzęt','la pieza','część / podzespół'),
('Informática: Hardware','Informatyka: Sprzęt','el circuito','obwód / układ'),
('Informática: Hardware','Informatyka: Sprzęt','el chip','układ scalony / chip'),
('Informática: Hardware','Informatyka: Sprzęt','el periférico','urządzenie peryferyjne'),
('Informática: Hardware','Informatyka: Sprzęt','la actualización de hardware','modernizacja sprzętu'),
('Informática: Software','Informatyka: Oprogramowanie','el software','oprogramowanie'),
('Informática: Software','Informatyka: Oprogramowanie','el programa','program'),
('Informática: Software','Informatyka: Oprogramowanie','la aplicación','aplikacja'),
('Informática: Software','Informatyka: Oprogramowanie','el sistema operativo','system operacyjny'),
('Informática: Software','Informatyka: Oprogramowanie','Windows','Windows'),
('Informática: Software','Informatyka: Oprogramowanie','macOS','macOS'),
('Informática: Software','Informatyka: Oprogramowanie','Linux','Linux'),
('Informática: Software','Informatyka: Oprogramowanie','Android','Android'),
('Informática: Software','Informatyka: Oprogramowanie','iOS','iOS'),
('Informática: Software','Informatyka: Oprogramowanie','el archivo','plik'),
('Informática: Software','Informatyka: Oprogramowanie','la carpeta','folder / katalog'),
('Informática: Software','Informatyka: Oprogramowanie','el documento','dokument'),
('Informática: Software','Informatyka: Oprogramowanie','el portapapeles','schowek'),
('Informática: Software','Informatyka: Oprogramowanie','instalar','instalować'),
('Informática: Software','Informatyka: Oprogramowanie','la instalación','instalacja'),
('Informática: Software','Informatyka: Oprogramowanie','desinstalar','odinstalować'),
('Informática: Software','Informatyka: Oprogramowanie','actualizar','aktualizować'),
('Informática: Software','Informatyka: Oprogramowanie','la actualización','aktualizacja'),
('Informática: Software','Informatyka: Oprogramowanie','ejecutar','uruchamiać / wykonywać'),
('Informática: Software','Informatyka: Oprogramowanie','abrir','otwierać'),
('Informática: Software','Informatyka: Oprogramowanie','cerrar','zamykać'),
('Informática: Software','Informatyka: Oprogramowanie','guardar','zapisywać'),
('Informática: Software','Informatyka: Oprogramowanie','guardar como','zapisz jako'),
('Informática: Software','Informatyka: Oprogramowanie','copiar','kopiować'),
('Informática: Software','Informatyka: Oprogramowanie','pegar','wklejać'),
('Informática: Software','Informatyka: Oprogramowanie','cortar','wycinać'),
('Informática: Software','Informatyka: Oprogramowanie','borrar / eliminar','usuwać'),
('Informática: Software','Informatyka: Oprogramowanie','deshacer','cofnij'),
('Informática: Software','Informatyka: Oprogramowanie','rehacer','ponów'),
('Informática: Software','Informatyka: Oprogramowanie','la interfaz','interfejs'),
('Informática: Software','Informatyka: Oprogramowanie','el icono','ikona'),
('Informática: Software','Informatyka: Oprogramowanie','el escritorio','pulpit'),
('Informática: Software','Informatyka: Oprogramowanie','la papelera de reciclaje','kosz na śmieci'),
('Informática: Software','Informatyka: Oprogramowanie','el error','błąd'),
('Informática: Software','Informatyka: Oprogramowanie','el fallo','awaria / usterka'),
('Informática: Software','Informatyka: Oprogramowanie','el virus','wirus'),
('Informática: Software','Informatyka: Oprogramowanie','el antivirus','antywirus'),
('Informática: Software','Informatyka: Oprogramowanie','analizar','skanować / analizować'),
('Informática: Software','Informatyka: Oprogramowanie','la copia de seguridad','kopia zapasowa (backup)'),
('Informática: Software','Informatyka: Oprogramowanie','restaurar','przywracać'),
('Informática: Software','Informatyka: Oprogramowanie','comprimir','kompresować'),
('Informática: Software','Informatyka: Oprogramowanie','descomprimir','rozpakowywać'),
('Informática: Software','Informatyka: Oprogramowanie','la base de datos','baza danych'),
('Informática: Software','Informatyka: Oprogramowanie','el código','kod'),
('Informática: Software','Informatyka: Oprogramowanie','programar','programować'),
('Informática: Software','Informatyka: Oprogramowanie','el programador','programista'),
('Informática: Software','Informatyka: Oprogramowanie','el navegador','przeglądarka'),
('Informática: Software','Informatyka: Oprogramowanie','la contraseña','hasło'),
('Informática: Software','Informatyka: Oprogramowanie','el usuario','użytkownik'),
('Informática: Software','Informatyka: Oprogramowanie','la licencia','licencja'),
('Internet','Internet','internet','internet'),
('Internet','Internet','la red','sieć'),
('Internet','Internet','la página web','strona internetowa'),
('Internet','Internet','el sitio web','witryna internetowa'),
('Internet','Internet','el enlace / el hipervínculo','link / hiperłącze'),
('Internet','Internet','la dirección URL','adres URL'),
('Internet','Internet','el navegador web','przeglądarka internetowa'),
('Internet','Internet','el motor de búsqueda','wyszukiwarka'),
('Internet','Internet','buscar','szukać'),
('Internet','Internet','navegar','serfować / przeglądać'),
('Internet','Internet','descargar','pobierać / ściągać'),
('Internet','Internet','subir','wagrać / wrzucać'),
('Internet','Internet','la descarga','pobieranie'),
('Internet','Internet','la subida','wgranie'),
('Internet','Internet','la conexión','połączenie'),
('Internet','Internet','la conexión a internet','połączenie internetowe'),
('Internet','Internet','la banda ancha','szerokopasmowy internet'),
('Internet','Internet','la fibra óptica','światłowód'),
('Internet','Internet','el wifi','Wi-Fi'),
('Internet','Internet','el señal','sygnał'),
('Internet','Internet','el correo electrónico / el email','poczta elektroniczna / email'),
('Internet','Internet','enviar','wysyłać'),
('Internet','Internet','recibir','odbierać'),
('Internet','Internet','el buzón de entrada','skrzynka odbiorcza'),
('Internet','Internet','el archivo adjunto','załącznik'),
('Internet','Internet','el correo no deseado / el spam','spam'),
('Internet','Internet','las redes sociales','media społecznościowe'),
('Internet','Internet','la plataforma','platforma'),
('Internet','Internet','la cuenta','konto / profil'),
('Internet','Internet','iniciar sesión','zalogować się'),
('Internet','Internet','cerrar sesión','wylogować się'),
('Internet','Internet','la contraseña','hasło'),
('Internet','Internet','el nombre de usuario','nazwa użytkownika'),
('Internet','Internet','el perfil','profil'),
('Internet','Internet','publicar','publikować'),
('Internet','Internet','compartir','udostępniać'),
('Internet','Internet','el comentario','komentarz'),
('Internet','Internet','el "me gusta"','polubienie / lajk'),
('Internet','Internet','el seguidor','obserwujący / follower'),
('Internet','Internet','seguir','obserwować'),
('Internet','Internet','el chat','czat'),
('Internet','Internet','la videoconferencia','wideokonferencja'),
('Internet','Internet','la nube','chmura'),
('Internet','Internet','el almacenamiento en la nube','przechowywanie w chmurze'),
('Internet','Internet','la ciberseguridad','cyberbezpieczeństwo'),
('Internet','Internet','el hacker','haker'),
('Internet','Internet','el phishing','phishing'),
('Internet','Internet','la cookie','plik cookie / ciasteczko'),
('Internet','Internet','viral','wirusowy'),
('Internet','Internet','el influencer','influencer');
