insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Juegos','Gry','el juego','gra'),
('Juegos','Gry','el juguete','zabawka'),
('Juegos','Gry','el juego de mesa','gra planszowa'),
('Juegos','Gry','las cartas','karty'),
('Juegos','Gry','la baraja','talia kart'),
('Juegos','Gry','el ajedrez','szachy'),
('Juegos','Gry','las damas','warcaby'),
('Juegos','Gry','el dominó','domino'),
('Juegos','Gry','el rompecabezas / el puzzle','puzzle'),
('Juegos','Gry','el dado','kostka do gry'),
('Juegos','Gry','el tablero','plansza'),
('Juegos','Gry','la ficha','pionek'),
('Juegos','Gry','el videojuego','gra wideo'),
('Juegos','Gry','la consola','konsola'),
('Juegos','Gry','el mando','kontroler / pad'),
('Juegos','Gry','el jugador','gracz'),
('Juegos','Gry','jugar','grać'),
('Juegos','Gry','ganar','wygrać'),
('Juegos','Gry','perder','przegrać'),
('Juegos','Gry','el ganador','zwycięzca'),
('Juegos','Gry','el perdedor','przegrany'),
('Juegos','Gry','el empate','remis'),
('Juegos','Gry','empatar','remisować'),
('Juegos','Gry','el punto','punkt'),
('Juegos','Gry','la puntuación','wynik'),
('Juegos','Gry','el nivel','poziom'),
('Juegos','Gry','la regla','zasada / reguła'),
('Juegos','Gry','hacer trampa','oszukiwać'),
('Juegos','Gry','el tramposo','oszust'),
('Juegos','Gry','el turno','kolej'),
('Juegos','Gry','tirar','rzucać (np. kostką)'),
('Juegos','Gry','mezclar','tasować'),
('Juegos','Gry','repartir','rozdawać (karty)'),
('Juegos','Gry','el escondite','chowanego'),
('Juegos','Gry','el pilla-pilla','berek'),
('Juegos','Gry','saltar a la comba','skakać przez skakankę'),
('Juegos','Gry','el columpio','huśtawka'),
('Juegos','Gry','el tobogán','zjeżdżalnia'),
('Juegos','Gry','el casino','kasyno'),
('Juegos','Gry','la ruleta','ruletka'),
('Juegos','Gry','apostar','obstawiać'),
('Juegos','Gry','la apuesta','zakład'),
('Juegos','Gry','el bingo','bingo'),
('Juegos','Gry','la lotería','loteria'),
('Juegos','Gry','el premio','nagroda'),
('Juegos','Gry','el campeonato','mistrzostwa'),
('Juegos','Gry','el torneo','turniej'),
('Juegos','Gry','divertido','zabawny / fajny'),
('Juegos','Gry','aburrido','nudny'),
('Juegos','Gry','el equipo','drużyna'),
('Las Fiestas','Święta','la fiesta','impreza / święto'),
('Las Fiestas','Święta','el festival','festiwal'),
('Las Fiestas','Święta','la celebración','obchody / świętowanie'),
('Las Fiestas','Święta','celebrar','świętować'),
('Las Fiestas','Święta','festejar','świętować / bawić się'),
('Las Fiestas','Święta','el cumpleaños','urodziny'),
('Las Fiestas','Święta','el santo','imieniny'),
('Las Fiestas','Święta','la boda','ślub / wesele'),
('Las Fiestas','Święta','el aniversario','rocznica'),
('Las Fiestas','Święta','la invitación','zaproszenie'),
('Las Fiestas','Święta','invitar','zapraszać'),
('Las Fiestas','Święta','el invitado','gość'),
('Las Fiestas','Święta','el regalo','prezent'),
('Las Fiestas','Święta','regalar','dawać w prezencie'),
('Las Fiestas','Święta','la tarta / el pastel','tort'),
('Las Fiestas','Święta','la vela','świeczka'),
('Las Fiestas','Święta','soplar','dmuchać'),
('Las Fiestas','Święta','la sorpresa','niespodzianka'),
('Las Fiestas','Święta','el globo','balon'),
('Las Fiestas','Święta','la decoración','dekoracja'),
('Las Fiestas','Święta','la música','muzyka'),
('Las Fiestas','Święta','bailar','tańczyć'),
('Las Fiestas','Święta','el brindis','toast'),
('Las Fiestas','Święta','brindar','wznosić toast'),
('Las Fiestas','Święta','la Navidad','Boże Narodzenie'),
('Las Fiestas','Święta','la Nochebuena','Wigilia'),
('Las Fiestas','Święta','la Nochevieja','Sylwester'),
('Las Fiestas','Święta','el Año Nuevo','Nowy Rok'),
('Las Fiestas','Święta','los Reyes Magos','Trzej Królowie'),
('Las Fiestas','Święta','la Semana Santa','Wielki Tydzień / Wielkanoc'),
('Las Fiestas','Święta','el carnaval','karnawał'),
('Las Fiestas','Święta','el disfraz','przebranie'),
('Las Fiestas','Święta','disfrazarse','przebierać się'),
('Las Fiestas','Święta','la máscara','maska'),
('Las Fiestas','Święta','el desfile','parada / pochód'),
('Las Fiestas','Święta','los fuegos artificiales','fajerwerki'),
('Las Fiestas','Święta','la tradición','tradycja'),
('Las Fiestas','Święta','tradicional','tradycyjny'),
('Las Fiestas','Święta','las vacaciones','wakacje / ferie'),
('Las Fiestas','Święta','el día festivo','dzień wolny od pracy'),
('Las Fiestas','Święta','la religión','religia'),
('Las Fiestas','Święta','la misa','msza'),
('Las Fiestas','Święta','la familia','rodzina'),
('Las Fiestas','Święta','el amigo','przyjaciel'),
('Las Fiestas','Święta','la comida','jedzenie / obiad'),
('Las Fiestas','Święta','la bebida','napój'),
('Las Fiestas','Święta','el vino','wino'),
('Las Fiestas','Święta','el champán','szampan'),
('Las Fiestas','Święta','alegre','radosny'),
('Las Fiestas','Święta','¡Felicidades!','Wszystkiego najlepszego! / Gratulacje!'),
('La Oficina','Biuro','la oficina','biuro'),
('La Oficina','Biuro','el escritorio','biurko'),
('La Oficina','Biuro','la silla','krzesło'),
('La Oficina','Biuro','el ordenador','komputer'),
('La Oficina','Biuro','el teclado','klawiatura'),
('La Oficina','Biuro','el ratón','myszka'),
('La Oficina','Biuro','la pantalla','ekran'),
('La Oficina','Biuro','el teléfono','telefon'),
('La Oficina','Biuro','la impresora','drukarka'),
('La Oficina','Biuro','el escáner','skaner'),
('La Oficina','Biuro','la fotocopiadora','kserokopiarka'),
('La Oficina','Biuro','el papel','papier'),
('La Oficina','Biuro','el documento','dokument'),
('La Oficina','Biuro','la carpeta','teczka / folder'),
('La Oficina','Biuro','el archivo','archiwum / segregator'),
('La Oficina','Biuro','el cajón','szuflada'),
('La Oficina','Biuro','el bolígrafo','długopis'),
('La Oficina','Biuro','el lápiz','ołówek'),
('La Oficina','Biuro','la grapadora','zszywacz'),
('La Oficina','Biuro','la grapa','zszywka'),
('La Oficina','Biuro','el clip','spinacz'),
('La Oficina','Biuro','el celo','taśma klejąca'),
('La Oficina','Biuro','las tijeras','nożyczki'),
('La Oficina','Biuro','el sobre','koperta'),
('La Oficina','Biuro','el sello','znaczek pocztowy'),
('La Oficina','Biuro','el correo','poczta'),
('La Oficina','Biuro','el correo electrónico','e-mail'),
('La Oficina','Biuro','la agenda','kalendarz (notatnik)'),
('La Oficina','Biuro','el calendario','kalendarz'),
('La Oficina','Biuro','la reunión','spotkanie / zebranie'),
('La Oficina','Biuro','la sala de reuniones','sala konferencyjna'),
('La Oficina','Biuro','el jefe','szef'),
('La Oficina','Biuro','el compañero de trabajo','kolega z pracy'),
('La Oficina','Biuro','el empleado','pracownik'),
('La Oficina','Biuro','el horario','godziny pracy / harmonogram'),
('La Oficina','Biuro','el descanso','przerwa'),
('La Oficina','Biuro','la cita','wizyta / spotkanie'),
('La Oficina','Biuro','el contrato','umowa'),
('La Oficina','Biuro','la firma','podpis'),
('La Oficina','Biuro','firmar','podpisywać'),
('La Oficina','Biuro','imprimir','drukować'),
('La Oficina','Biuro','fotocopiar','kserować'),
('La Oficina','Biuro','archivar','archiwizować'),
('La Oficina','Biuro','enviar','wysyłać'),
('La Oficina','Biuro','recibir','otrzymywać'),
('La Oficina','Biuro','el proyecto','projekt'),
('La Oficina','Biuro','la presentación','prezentacja'),
('La Oficina','Biuro','el informe','raport'),
('La Oficina','Biuro','el sello de caucho','pieczątka'),
('La Oficina','Biuro','la papelera','kosz na śmieci'),
('Negocios','Biznes','el negocio','biznes'),
('Negocios','Biznes','la empresa','firma / przedsiębiorstwo'),
('Negocios','Biznes','el empresario','przedsiębiorca'),
('Negocios','Biznes','el gerente','menedżer'),
('Negocios','Biznes','el director','dyrektor'),
('Negocios','Biznes','el cliente','klient'),
('Negocios','Biznes','el socio','wspólnik / partner'),
('Negocios','Biznes','el mercado','rynek'),
('Negocios','Biznes','la industria','przemysł'),
('Negocios','Biznes','el producto','produkt'),
('Negocios','Biznes','el servicio','usługa'),
('Negocios','Biznes','la marca','marka'),
('Negocios','Biznes','la competencia','konkurencja'),
('Negocios','Biznes','el competidor','konkurent'),
('Negocios','Biznes','el precio','cena'),
('Negocios','Biznes','el coste','koszt'),
('Negocios','Biznes','el presupuesto','budżet'),
('Negocios','Biznes','el ingreso','przychód'),
('Negocios','Biznes','el gasto','wydatek'),
('Negocios','Biznes','el beneficio','zysk'),
('Negocios','Biznes','la pérdida','strata'),
('Negocios','Biznes','la inversión','inwestycja'),
('Negocios','Biznes','el inversor','inwestor'),
('Negocios','Biznes','invertir','inwestować'),
('Negocios','Biznes','el capital','kapitał'),
('Negocios','Biznes','la acción','akcja (giełdowa)'),
('Negocios','Biznes','la bolsa','giełda'),
('Negocios','Biznes','el banco','bank'),
('Negocios','Biznes','el préstamo','pożyczka'),
('Negocios','Biznes','el crédito','kredyt'),
('Negocios','Biznes','la deuda','dług'),
('Negocios','Biznes','el contrato','kontrakt'),
('Negocios','Biznes','el acuerdo','porozumienie'),
('Negocios','Biznes','negociar','negocjować'),
('Negocios','Biznes','la negociación','negocjacje'),
('Negocios','Biznes','el éxito','sukces'),
('Negocios','Biznes','el fracaso','porażka'),
('Negocios','Biznes','quebrar','zbankrutować'),
('Negocios','Biznes','la bancarrota','bankructwo'),
('Negocios','Biznes','comprar','kupować'),
('Negocios','Biznes','vender','sprzedawać'),
('Negocios','Biznes','la venta','sprzedaż'),
('Negocios','Biznes','el marketing','marketing'),
('Negocios','Biznes','la publicidad','reklama'),
('Negocios','Biznes','el plan de negocio','biznesplan'),
('Negocios','Biznes','exportar','eksportować'),
('Negocios','Biznes','importar','importować'),
('Negocios','Biznes','la calidad','jakość'),
('Negocios','Biznes','el proveedor','dostawca'),
('Negocios','Biznes','la factura','faktura'),
('Derecho y Ley','Prawo y Ustawa','el derecho','prawo (dziedzina)'),
('Derecho y Ley','Prawo y Ustawa','la ley','ustawa / prawo'),
('Derecho y Ley','Prawo y Ustawa','legal','legalny'),
('Derecho y Ley','Prawo y Ustawa','ilegal','nielegalny'),
('Derecho y Ley','Prawo y Ustawa','el abogado','prawnik / adwokat'),
('Derecho y Ley','Prawo y Ustawa','el juez','sędzia'),
('Derecho y Ley','Prawo y Ustawa','el tribunal','sąd'),
('Derecho y Ley','Prawo y Ustawa','el juicio','proces sądowy / rozprawa'),
('Derecho y Ley','Prawo y Ustawa','el jurado','ława przysięgłych'),
('Derecho y Ley','Prawo y Ustawa','el testigo','świadek'),
('Derecho y Ley','Prawo y Ustawa','el testimonio','zeznanie'),
('Derecho y Ley','Prawo y Ustawa','la prueba','dowód'),
('Derecho y Ley','Prawo y Ustawa','el delito','przestępstwo'),
('Derecho y Ley','Prawo y Ustawa','el crimen','zbrodnia'),
('Derecho y Ley','Prawo y Ustawa','el criminal','przestępca'),
('Derecho y Ley','Prawo y Ustawa','el ladrón','złodziej'),
('Derecho y Ley','Prawo y Ustawa','el asesinato','morderstwo'),
('Derecho y Ley','Prawo y Ustawa','el asesino','morderca'),
('Derecho y Ley','Prawo y Ustawa','el robo','kradzież'),
('Derecho y Ley','Prawo y Ustawa','la estafa','oszustwo'),
('Derecho y Ley','Prawo y Ustawa','el sospechoso','podejrzany'),
('Derecho y Ley','Prawo y Ustawa','culpable','winny'),
('Derecho y Ley','Prawo y Ustawa','inocente','niewinny'),
('Derecho y Ley','Prawo y Ustawa','la culpa','wina'),
('Derecho y Ley','Prawo y Ustawa','la víctima','ofiara'),
('Derecho y Ley','Prawo y Ustawa','la policía','policja'),
('Derecho y Ley','Prawo y Ustawa','el policía','policjant'),
('Derecho y Ley','Prawo y Ustawa','arrestar','aresztować'),
('Derecho y Ley','Prawo y Ustawa','la cárcel / la prisión','więzienie'),
('Derecho y Ley','Prawo y Ustawa','el prisionero','więzień'),
('Derecho y Ley','Prawo y Ustawa','la celda','cela'),
('Derecho y Ley','Prawo y Ustawa','la demanda','pozew'),
('Derecho y Ley','Prawo y Ustawa','demandar','pozwać'),
('Derecho y Ley','Prawo y Ustawa','la defensa','obrona'),
('Derecho y Ley','Prawo y Ustawa','la acusación','oskarżenie'),
('Derecho y Ley','Prawo y Ustawa','acusar','oskarżać'),
('Derecho y Ley','Prawo y Ustawa','la sentencia','wyrok'),
('Derecho y Ley','Prawo y Ustawa','el castigo','kara'),
('Derecho y Ley','Prawo y Ustawa','la multa','mandat / grzywna'),
('Derecho y Ley','Prawo y Ustawa','la apelación','apelacja'),
('Derecho y Ley','Prawo y Ustawa','los derechos humanos','prawa człowieka'),
('Derecho y Ley','Prawo y Ustawa','la constitución','konstytucja'),
('Derecho y Ley','Prawo y Ustawa','el contrato','umowa'),
('Derecho y Ley','Prawo y Ustawa','firmar','podpisać'),
('Derecho y Ley','Prawo y Ustawa','la justicia','sprawiedliwość'),
('Derecho y Ley','Prawo y Ustawa','injusto','niesprawiedliwy'),
('Derecho y Ley','Prawo y Ustawa','la libertad','wolność'),
('Derecho y Ley','Prawo y Ustawa','el fiscal','prokurator'),
('Derecho y Ley','Prawo y Ustawa','el jurista','prawnik (teoretyk)'),
('Derecho y Ley','Prawo y Ustawa','el notario','notariusz'),
('El Ejército','Wojsko','el ejército','wojsko / armia'),
('El Ejército','Wojsko','las fuerzas armadas','siły zbrojne'),
('El Ejército','Wojsko','el soldado','żołnierz'),
('El Ejército','Wojsko','el oficial','oficer'),
('El Ejército','Wojsko','el general','generał'),
('El Ejército','Wojsko','el capitán','kapitan'),
('El Ejército','Wojsko','el comandante','dowódca / komendant'),
('El Ejército','Wojsko','el sargento','sierżant'),
('El Ejército','Wojsko','el uniforme','mundur'),
('El Ejército','Wojsko','la base militar','baza wojskowa'),
('El Ejército','Wojsko','la guerra','wojna'),
('El Ejército','Wojsko','la paz','pokój'),
('El Ejército','Wojsko','la batalla','bitwa'),
('El Ejército','Wojsko','el ataque','atak'),
('El Ejército','Wojsko','atacar','atakować'),
('El Ejército','Wojsko','la defensa','obrona'),
('El Ejército','Wojsko','defender','bronić'),
('El Ejército','Wojsko','el enemigo','wróg'),
('El Ejército','Wojsko','el aliado','sojusznik'),
('El Ejército','Wojsko','la victoria','zwycięstwo'),
('El Ejército','Wojsko','la derrota','porażka'),
('El Ejército','Wojsko','el arma','broń'),
('El Ejército','Wojsko','la pistola','pistolet'),
('El Ejército','Wojsko','el rifle / el fusil','karabin'),
('El Ejército','Wojsko','la bala','kula / pocisk'),
('El Ejército','Wojsko','la bomba','bomba'),
('El Ejército','Wojsko','el misil','pocisk rakietowy'),
('El Ejército','Wojsko','el tanque','czołg'),
('El Ejército','Wojsko','el avión de caza','myśliwiec'),
('El Ejército','Wojsko','el helicóptero','helikopter'),
('El Ejército','Wojsko','la marina','marynarka wojenna'),
('El Ejército','Wojsko','el barco de guerra','okręt wojenny'),
('El Ejército','Wojsko','el submarino','okręt podwodny'),
('El Ejército','Wojsko','la fuerza aérea','lotnictwo wojskowe'),
('El Ejército','Wojsko','el recluta','rekrut'),
('El Ejército','Wojsko','el veterano','weteran'),
('El Ejército','Wojsko','la medalla','medal'),
('El Ejército','Wojsko','el rango','stopień wojskowy'),
('El Ejército','Wojsko','la orden','rozkaz'),
('El Ejército','Wojsko','disparar','strzelać'),
('El Ejército','Wojsko','explotar','wybuchać'),
('El Ejército','Wojsko','la explosión','eksplozja'),
('El Ejército','Wojsko','el prisionero de guerra','jeździec wojenny / jeniec'),
('El Ejército','Wojsko','la trinchera','okop'),
('El Ejército','Wojsko','la estrategia','strategia'),
('El Ejército','Wojsko','el campamento','obóz'),
('El Ejército','Wojsko','rendirse','poddać się'),
('El Ejército','Wojsko','la tregua','zawieszenie broni'),
('El Ejército','Wojsko','el francotirador','snajper'),
('El Ejército','Wojsko','la munición','amunicja'),
('Instrumentos Musicales','Instrumenty muzyczne','el instrumento musical','instrument muzyczny'),
('Instrumentos Musicales','Instrumenty muzyczne','la guitarra','gitara'),
('Instrumentos Musicales','Instrumenty muzyczne','la guitarra eléctrica','gitara elektryczna'),
('Instrumentos Musicales','Instrumenty muzyczne','la guitarra acústica','gitara akustyczna'),
('Instrumentos Musicales','Instrumenty muzyczne','el bajo','gitara basowa'),
('Instrumentos Musicales','Instrumenty muzyczne','el piano','pianino'),
('Instrumentos Musicales','Instrumenty muzyczne','el teclado','keyboard / instrument klawiszowy'),
('Instrumentos Musicales','Instrumenty muzyczne','el violín','skrzypce'),
('Instrumentos Musicales','Instrumenty muzyczne','la viola','altówka'),
('Instrumentos Musicales','Instrumenty muzyczne','el violonchelo','wiolonczela'),
('Instrumentos Musicales','Instrumenty muzyczne','el contrabajo','kontrabas'),
('Instrumentos Musicales','Instrumenty muzyczne','el arpa','harfa'),
('Instrumentos Musicales','Instrumenty muzyczne','la batería','perkusja'),
('Instrumentos Musicales','Instrumenty muzyczne','el tambor','bęben'),
('Instrumentos Musicales','Instrumenty muzyczne','los platillos','talerze (instrument)'),
('Instrumentos Musicales','Instrumenty muzyczne','la trompeta','trąbka'),
('Instrumentos Musicales','Instrumenty muzyczne','el trombón','puzon'),
('Instrumentos Musicales','Instrumenty muzyczne','la tuba','tuba'),
('Instrumentos Musicales','Instrumenty muzyczne','el saxofón','saksofon'),
('Instrumentos Musicales','Instrumenty muzyczne','la flauta','flet'),
('Instrumentos Musicales','Instrumenty muzyczne','el clarinete','klarnet'),
('Instrumentos Musicales','Instrumenty muzyczne','el oboe','obój'),
('Instrumentos Musicales','Instrumenty muzyczne','el fagot','fagot'),
('Instrumentos Musicales','Instrumenty muzyczne','el acordeón','akordeon'),
('Instrumentos Musicales','Instrumenty muzyczne','la armónica','harmonijka ustna'),
('Instrumentos Musicales','Instrumenty muzyczne','la pandereta','tamburyn'),
('Instrumentos Musicales','Instrumenty muzyczne','las maracas','marakasy'),
('Instrumentos Musicales','Instrumenty muzyczne','el xilófono','ksylofon'),
('Instrumentos Musicales','Instrumenty muzyczne','el triángulo','trójkąt (instrument)'),
('Instrumentos Musicales','Instrumenty muzyczne','el órgano','organy'),
('Instrumentos Musicales','Instrumenty muzyczne','el sintetizador','syntezator'),
('Instrumentos Musicales','Instrumenty muzyczne','el laúd','lutnia'),
('Instrumentos Musicales','Instrumenty muzyczne','la mandolina','mandolina'),
('Instrumentos Musicales','Instrumenty muzyczne','el ukelele','ukulele'),
('Instrumentos Musicales','Instrumenty muzyczne','el bongó','bongo'),
('Instrumentos Musicales','Instrumenty muzyczne','las congas','kongi'),
('Instrumentos Musicales','Instrumenty muzyczne','las castañuelas','kastaniety'),
('Instrumentos Musicales','Instrumenty muzyczne','la gaita','dudy'),
('Instrumentos Musicales','Instrumenty muzyczne','la baqueta','pałeczka perkusyjna'),
('Instrumentos Musicales','Instrumenty muzyczne','la cuerda','struna'),
('Instrumentos Musicales','Instrumenty muzyczne','el arco','smyczek'),
('Instrumentos Musicales','Instrumenty muzyczne','el pedal','pedał'),
('Instrumentos Musicales','Instrumenty muzyczne','la tecla','klawisz'),
('Instrumentos Musicales','Instrumenty muzyczne','tocar','grać (na instrumencie)'),
('Instrumentos Musicales','Instrumenty muzyczne','afinar','stroić'),
('Instrumentos Musicales','Instrumenty muzyczne','el afinador','stroik'),
('Instrumentos Musicales','Instrumenty muzyczne','el músico','muzyk'),
('Instrumentos Musicales','Instrumenty muzyczne','la orquesta','orkiestra'),
('Instrumentos Musicales','Instrumenty muzyczne','el conservatorio','konserwatorium'),
('Instrumentos Musicales','Instrumenty muzyczne','la melodía','melodia'),
('Las Verduras','Warzywa','la verdura','warzywo'),
('Las Verduras','Warzywa','el tomate','pomidor'),
('Las Verduras','Warzywa','la cebolla','cebula'),
('Las Verduras','Warzywa','el ajo','czosnek'),
('Las Verduras','Warzywa','la patata / la papa','ziemniak'),
('Las Verduras','Warzywa','la zanahoria','marchewka'),
('Las Verduras','Warzywa','el pepino','ogórek'),
('Las Verduras','Warzywa','el pimiento','papryka'),
('Las Verduras','Warzywa','la lechuga','sałata'),
('Las Verduras','Warzywa','la col / el repollo','kapusta'),
('Las Verduras','Warzywa','el brócoli','brokuł'),
('Las Verduras','Warzywa','la coliflor','kalafior'),
('Las Verduras','Warzywa','la espinaca','szpinak'),
('Las Verduras','Warzywa','el calabacín','cukinia'),
('Las Verduras','Warzywa','la berenjena','bakłażan'),
('Las Verduras','Warzywa','la calabaza','dynia'),
('Las Verduras','Warzywa','el guisante','groszek'),
('Las Verduras','Warzywa','la judía verde','fasolka szparagowa'),
('Las Verduras','Warzywa','el maíz','kukurydza'),
('Las Verduras','Warzywa','el champiñón','pieczarka'),
('Las Verduras','Warzywa','la seta','grzyb'),
('Las Verduras','Warzywa','el rábano','rzodkiewka'),
('Las Verduras','Warzywa','el apio','seler'),
('Las Verduras','Warzywa','el espárrago','szparag'),
('Las Verduras','Warzywa','el puerro','por'),
('Las Verduras','Warzywa','la remolacha','burak'),
('Las Verduras','Warzywa','la alcachofa','karczoch'),
('Las Verduras','Warzywa','la batata / el boniato','batat / słodki ziemniak'),
('Las Verduras','Warzywa','el aguacate','awokado'),
('Las Verduras','Warzywa','el perejil','pietruszka (nać)'),
('Las Verduras','Warzywa','el cilantro','kolendra'),
('Las Verduras','Warzywa','la albahaca','bazylia'),
('Las Verduras','Warzywa','el romero','rozmaryn'),
('Las Verduras','Warzywa','el tomillo','tymianek'),
('Las Verduras','Warzywa','el orégano','oregano'),
('Las Verduras','Warzywa','el laurel','liść laurowy'),
('Las Verduras','Warzywa','la menta','mięta'),
('Las Verduras','Warzywa','el eneldo','koperek'),
('Las Verduras','Warzywa','el cebollino','szczypiorek'),
('Las Verduras','Warzywa','el pimentón','papryka w proszku'),
('Las Verduras','Warzywa','el chile','papryczka chili'),
('Las Verduras','Warzywa','el jalapeño','jalapeño'),
('Las Verduras','Warzywa','el nabo','rzepa'),
('Las Verduras','Warzywa','el hinojo','koper włoski'),
('Las Verduras','Warzywa','la acelga','boćwina'),
('Las Verduras','Warzywa','el berro','rukiew wodna'),
('Las Verduras','Warzywa','la rúcula','rukola'),
('Las Verduras','Warzywa','el germinado','kiełek'),
('Las Verduras','Warzywa','la trufa','trufla'),
('Las Verduras','Warzywa','la legumbre','roślina strączkowa'),
('Las Frutas','Owoce','la fruta','owoc'),
('Las Frutas','Owoce','la manzana','jabłko'),
('Las Frutas','Owoce','la pera','gruszka'),
('Las Frutas','Owoce','el plátano / la banana','banan'),
('Las Frutas','Owoce','la naranja','pomarańcza'),
('Las Frutas','Owoce','el limón','cytryna'),
('Las Frutas','Owoce','la mandarina','mandarynka'),
('Las Frutas','Owoce','el pomelo','grejpfrut'),
('Las Frutas','Owoce','la uva','winogrono'),
('Las Frutas','Owoce','la fresa','truskawka'),
('Las Frutas','Owoce','la frambuesa','malina'),
('Las Frutas','Owoce','el arándano','borówka / jagoda'),
('Las Frutas','Owoce','la mora','jeżyna'),
('Las Frutas','Owoce','la cereza','czereśnia / wiśnia'),
('Las Frutas','Owoce','la ciruela','śliwka'),
('Las Frutas','Owoce','el melocotón','brzoskwinia'),
('Las Frutas','Owoce','el albaricoque','morela'),
('Las Frutas','Owoce','la nectarina','nektarynka'),
('Las Frutas','Owoce','la sandía','arbuz'),
('Las Frutas','Owoce','el melón','melon'),
('Las Frutas','Owoce','la piña','ananas'),
('Las Frutas','Owoce','el mango','mango'),
('Las Frutas','Owoce','la papaya','papaja'),
('Las Frutas','Owoce','el coco','kokos'),
('Las Frutas','Owoce','el kiwi','kiwi'),
('Las Frutas','Owoce','el higo','figa'),
('Las Frutas','Owoce','la granada','granat (owoc)'),
('Las Frutas','Owoce','el maracuyá','marakuja'),
('Las Frutas','Owoce','la guayaba','gujawa'),
('Las Frutas','Owoce','la lima','limonka'),
('Las Frutas','Owoce','el caqui','persymona / kaki'),
('Las Frutas','Owoce','el membrillo','pigwa'),
('Las Frutas','Owoce','el dátil','daktyl'),
('Las Frutas','Owoce','la pasa','rodzynka'),
('Las Frutas','Owoce','la almendra','migdał'),
('Las Frutas','Owoce','la nuez','orzech włoski'),
('Las Frutas','Owoce','la avellana','orzech laskowy'),
('Las Frutas','Owoce','el cacahuete / el maní','orzeszek ziemny'),
('Las Frutas','Owoce','el pistacho','pistacja'),
('Las Frutas','Owoce','la castaña','kasztan'),
('Las Frutas','Owoce','la semilla','nasiono'),
('Las Frutas','Owoce','la pepita','pestka'),
('Las Frutas','Owoce','la cáscara','skórka / łupina'),
('Las Frutas','Owoce','la pulpa','miąższ'),
('Las Frutas','Owoce','el zumo / el jugo','sok'),
('Las Frutas','Owoce','maduro','dojrzały'),
('Las Frutas','Owoce','verde (inmaduro)','niedojrzały'),
('Las Frutas','Owoce','dulce','słodki'),
('Las Frutas','Owoce','ácido','kwaśny'),
('Las Frutas','Owoce','pelar','obierać'),
('La Carne','Mięso','la carne','mięso'),
('La Carne','Mięso','el cerdo','wieprzowina'),
('La Carne','Mięso','la ternera','cielęcina'),
('La Carne','Mięso','la vaca','wołowina'),
('La Carne','Mięso','el buey','mięso wołowe (z wołu)'),
('La Carne','Mięso','el pollo','kurczak'),
('La Carne','Mięso','el pavo','indyk'),
('La Carne','Mięso','el pato','kaczka'),
('La Carne','Mięso','el cordero','jagnięcina'),
('La Carne','Mięso','la oveja','baranina'),
('La Carne','Mięso','el conejo','królik'),
('La Carne','Mięso','el venado','dziczyzna (jeleń)'),
('La Carne','Mięso','el jabalí','dzik'),
('La Carne','Mięso','el filete','filet / stek'),
('La Carne','Mięso','la chuleta','kotlet z kością'),
('La Carne','Mięso','el lomo','schab / polędwica'),
('La Carne','Mięso','la costilla','żeberko'),
('La Carne','Mięso','la carne picada','mięso mielone'),
('La Carne','Mięso','la salchicha','parówka / kiełbaska'),
('La Carne','Mięso','el chorizo','chorizo (kiełbasa)'),
('La Carne','Mięso','el jamón','szynka'),
('La Carne','Mięso','el jamón serrano','szynka dojrzewająca'),
('La Carne','Mięso','el jamón cocido','szynka gotowana'),
('La Carne','Mięso','el tocino / el bacon','boczek'),
('La Carne','Mięso','el salami','salami'),
('La Carne','Mięso','la morcilla','kaszanka'),
('La Carne','Mięso','el paté','pasztet'),
('La Carne','Mięso','el asado','pieczeń'),
('La Carne','Mięso','la pechuga','pierś (np. z kurczaka)'),
('La Carne','Mięso','el muslo','udo / udko'),
('La Carne','Mięso','la alita','skrzydełko'),
('La Carne','Mięso','la casquería','podroby'),
('La Carne','Mięso','el hígado','wątróbka'),
('La Carne','Mięso','el corazón','serce'),
('La Carne','Mięso','la lengua','język (mięso)'),
('La Carne','Mięso','los callos','flaki'),
('La Carne','Mięso','la carne asada','mięso pieczone'),
('La Carne','Mięso','la carne frita','mięso smażone'),
('La Carne','Mięso','el estofado','gulasz'),
('La Carne','Mięso','el guiso','potrawka / duszony posiłek'),
('La Carne','Mięso','crudo','surowy'),
('La Carne','Mięso','poco hecho','słabo wysmażony (krwisty)'),
('La Carne','Mięso','en su punto','średnio wysmażony'),
('La Carne','Mięso','muy hecho','dobrze wysmażony'),
('La Carne','Mięso','tierno','miękki / kruchy (o mięsie)'),
('La Carne','Mięso','duro','twardy / żylasty'),
('La Carne','Mięso','el carnicero','rzeźnik'),
('La Carne','Mięso','la carnicería','sklep mięsny'),
('La Carne','Mięso','el ave','drób'),
('La Carne','Mięso','el embutido','wędlina'),
('El Pescado y Marisco','Ryby i Owoce morza','el pescado','ryba (do jedzenia)'),
('El Pescado y Marisco','Ryby i Owoce morza','el marisco','owoce morza'),
('El Pescado y Marisco','Ryby i Owoce morza','el salmón','łosoś'),
('El Pescado y Marisco','Ryby i Owoce morza','el atún','tuńczyk'),
('El Pescado y Marisco','Ryby i Owoce morza','el bacalao','dorsz'),
('El Pescado y Marisco','Ryby i Owoce morza','la merluza','morszczuk'),
('El Pescado y Marisco','Ryby i Owoce morza','la sardina','sardynka'),
('El Pescado y Marisco','Ryby i Owoce morza','el boquerón','sardela / anchois'),
('El Pescado y Marisco','Ryby i Owoce morza','la trucha','pstrąg'),
('El Pescado y Marisco','Ryby i Owoce morza','la dorada','dorada'),
('El Pescado y Marisco','Ryby i Owoce morza','la lubina','okoń morski'),
('El Pescado y Marisco','Ryby i Owoce morza','el pez espada','miecznik'),
('El Pescado y Marisco','Ryby i Owoce morza','el lenguado','sola'),
('El Pescado y Marisco','Ryby i Owoce morza','el rodaballo','turbot'),
('El Pescado y Marisco','Ryby i Owoce morza','la caballa','makrela'),
('El Pescado y Marisco','Ryby i Owoce morza','la anguila','węgorz'),
('El Pescado y Marisco','Ryby i Owoce morza','el rape','żabnica'),
('El Pescado y Marisco','Ryby i Owoce morza','el pulpo','ośmiornica'),
('El Pescado y Marisco','Ryby i Owoce morza','el calamar','kalamar'),
('El Pescado y Marisco','Ryby i Owoce morza','la sepia','mątwa'),
('El Pescado y Marisco','Ryby i Owoce morza','la gamba','krewetka (mniejsza)'),
('El Pescado y Marisco','Ryby i Owoce morza','el langostino','krewetka (większa)'),
('El Pescado y Marisco','Ryby i Owoce morza','la langosta','langusta'),
('El Pescado y Marisco','Ryby i Owoce morza','el cangrejo','krab'),
('El Pescado y Marisco','Ryby i Owoce morza','el mejillón','omułek / małż'),
('El Pescado y Marisco','Ryby i Owoce morza','la ostra','ostryga'),
('El Pescado y Marisco','Ryby i Owoce morza','la almeja','małż (zwyczajny)'),
('El Pescado y Marisco','Ryby i Owoce morza','la vieira','przegrzebek'),
('El Pescado y Marisco','Ryby i Owoce morza','el berberecho','sercówka'),
('El Pescado y Marisco','Ryby i Owoce morza','el erizo de mar','jeżowiec'),
('El Pescado y Marisco','Ryby i Owoce morza','el caviar','kawior'),
('El Pescado y Marisco','Ryby i Owoce morza','la espina','ość'),
('El Pescado y Marisco','Ryby i Owoce morza','la escama','łuska'),
('El Pescado y Marisco','Ryby i Owoce morza','la aleta','płetwa'),
('El Pescado y Marisco','Ryby i Owoce morza','las agallas','skrzela'),
('El Pescado y Marisco','Ryby i Owoce morza','la cola','ogon'),
('El Pescado y Marisco','Ryby i Owoce morza','pescar','łowić ryby'),
('El Pescado y Marisco','Ryby i Owoce morza','el pescador','rybak / wędkarz'),
('El Pescado y Marisco','Ryby i Owoce morza','la pescadería','sklep rybny'),
('El Pescado y Marisco','Ryby i Owoce morza','fresco','świeży'),
('El Pescado y Marisco','Ryby i Owoce morza','congelado','mrożony'),
('El Pescado y Marisco','Ryby i Owoce morza','ahumado','wędzony'),
('El Pescado y Marisco','Ryby i Owoce morza','enlatado','w puszce / konserwowy'),
('El Pescado y Marisco','Ryby i Owoce morza','el filete de pescado','filet rybny'),
('El Pescado y Marisco','Ryby i Owoce morza','el sushi','sushi'),
('El Pescado y Marisco','Ryby i Owoce morza','la mariscada','półmisek owoców morza'),
('El Pescado y Marisco','Ryby i Owoce morza','la red','sieć rybacka'),
('El Pescado y Marisco','Ryby i Owoce morza','el anzuelo','haczyk (na ryby)'),
('El Pescado y Marisco','Ryby i Owoce morza','la caña de pescar','wędka'),
('El Pescado y Marisco','Ryby i Owoce morza','el mar y montaña','danie mięsno-rybne (surf and turf)'),
('Los Postres','Desery','el postre','deser'),
('Los Postres','Desery','la tarta / el pastel','ciasto / tort'),
('Los Postres','Desery','el bizcocho','biszkopt / babka'),
('Los Postres','Desery','la galleta','ciastko'),
('Los Postres','Desery','el helado','lody'),
('Los Postres','Desery','el chocolate','czekolada'),
('Los Postres','Desery','el caramelo','cukierek / karmel'),
('Los Postres','Desery','el bombón','pralina / czekoladka'),
('Los Postres','Desery','el chicle','guma do żucia'),
('Los Postres','Desery','la gominola','żelek'),
('Los Postres','Desery','el flan','flan (krem karmelowy)'),
('Los Postres','Desery','las natillas','krem budyniowy'),
('Los Postres','Desery','el arroz con leche','ryż na mleku'),
('Los Postres','Desery','la crema catalana','krem kataloński'),
('Los Postres','Desery','el churro','churro'),
('Los Postres','Desery','el buñuelo','pączek hiszpański'),
('Los Postres','Desery','la magdalena','muffinka / magdalenka'),
('Los Postres','Desery','el cruasán','rogalik / croissant'),
('Los Postres','Desery','la ensaimada','drożdżówka z Majorki'),
('Los Postres','Desery','el turrón','nugat / turron'),
('Los Postres','Desery','el mazapán','marcepan'),
('Los Postres','Desery','el polvorón','kruche ciastko świąteczne'),
('Los Postres','Desery','el roscón','ciasto w kształcie pierścienia'),
('Los Postres','Desery','el gofre','gofr'),
('Los Postres','Desery','el crep','naleśnik'),
('Los Postres','Desery','la tortita','pankejk / placuszek'),
('Los Postres','Desery','la mermelada','dżem / marmolada'),
('Los Postres','Desery','la miel','miód'),
('Los Postres','Desery','el sirope','syrop'),
('Los Postres','Desery','la nata','bita śmietana'),
('Los Postres','Desery','la crema','krem'),
('Los Postres','Desery','la vainilla','wanilia'),
('Los Postres','Desery','la canela','cynamon'),
('Los Postres','Desery','el azúcar','cukier'),
('Los Postres','Desery','el azúcar glas','cukier puder'),
('Los Postres','Desery','el edulcorante','słodzik'),
('Los Postres','Desery','dulce','słodki'),
('Los Postres','Desery','el postre casero','domowy deser'),
('Los Postres','Desery','la repostería','cukiernictwo / wypieki'),
('Los Postres','Desery','el pastelero','cukiernik'),
('Los Postres','Desery','la pastelería','cukiernia'),
('Los Postres','Desery','la panadería','piekarnia'),
('Los Postres','Desery','hornear','piec (w piekarniku)'),
('Los Postres','Desery','la masa','ciasto (masa)'),
('Los Postres','Desery','la harina','mąka'),
('Los Postres','Desery','la levadura','drożdże / proszek do pieczenia'),
('Los Postres','Desery','el horno','piekarnik'),
('Los Postres','Desery','derretir','roztapiać (np. czekoladę)'),
('Los Postres','Desery','espolvorear','posypywać'),
('Los Postres','Desery','rellenar','nadziewać'),
('Condimentos','Przyprawy','el condimento','przyprawa'),
('Condimentos','Przyprawy','la sal','sól'),
('Condimentos','Przyprawy','la pimienta','pieprz'),
('Condimentos','Przyprawy','el azúcar','cukier'),
('Condimentos','Przyprawy','el vinagre','ocet'),
('Condimentos','Przyprawy','el aceite','olej / oliwa'),
('Condimentos','Przyprawy','la mostaza','musztarda'),
('Condimentos','Przyprawy','el kétchup','keczup'),
('Condimentos','Przyprawy','la mayonesa','majonez'),
('Condimentos','Przyprawy','el ajo en polvo','czosnek niedźwiedzi / w proszku'),
('Condimentos','Przyprawy','la cebolla en polvo','cebula w proszku'),
('Condimentos','Przyprawy','el pimentón','papryka (przyprawa)'),
('Condimentos','Przyprawy','el orégano','oregano'),
('Condimentos','Przyprawy','la albahaca','bazylia'),
('Condimentos','Przyprawy','el tomillo','tymianek'),
('Condimentos','Przyprawy','el romero','rozmaryn'),
('Condimentos','Przyprawy','el comino','kmin rzymski'),
('Condimentos','Przyprawy','el curry','curry'),
('Condimentos','Przyprawy','la cúrcuma','kurkuma'),
('Condimentos','Przyprawy','el jengibre','imbir'),
('Condimentos','Przyprawy','la canela','cynamon'),
('Condimentos','Przyprawy','el clavo','goździk (przyprawa)'),
('Condimentos','Przyprawy','la nuez moscada','gałka muszkatołowa'),
('Condimentos','Przyprawy','el azafrán','szafran'),
('Condimentos','Przyprawy','el cilantro','kolendra'),
('Condimentos','Przyprawy','el perejil','pietruszka (przyprawa)'),
('Condimentos','Przyprawy','el eneldo','koperek'),
('Condimentos','Przyprawy','el laurel','liść laurowy'),
('Condimentos','Przyprawy','el anís','anyż'),
('Condimentos','Przyprawy','la vainilla','wanilia'),
('Condimentos','Przyprawy','la salsa de soja','sos sojowy'),
('Condimentos','Przyprawy','el tabasco','tabasco'),
('Condimentos','Przyprawy','el chile','chili'),
('Condimentos','Przyprawy','el jalapeño','jalapeño'),
('Condimentos','Przyprawy','la sal marina','sól morska'),
('Condimentos','Przyprawy','la pimienta negra','pieprz czarny'),
('Condimentos','Przyprawy','la pimienta blanca','pieprz biały'),
('Condimentos','Przyprawy','las hierbas provenzales','zioła prowansalskie'),
('Condimentos','Przyprawy','la guindilla','ostra papryczka'),
('Condimentos','Przyprawy','el sésamo','sezam'),
('Condimentos','Przyprawy','la semilla de amapola','mak (ziarno)'),
('Condimentos','Przyprawy','sazonar','doprawiać'),
('Condimentos','Przyprawy','salar','solić'),
('Condimentos','Przyprawy','condimentar','przyprawiać'),
('Condimentos','Przyprawy','aderezar','okraszać / doprawiać'),
('Condimentos','Przyprawy','el aderezo','dressing / przyprawa'),
('Condimentos','Przyprawy','picante','pikantny'),
('Condimentos','Przyprawy','salado','słony'),
('Condimentos','Przyprawy','sabroso','smaczny'),
('Condimentos','Przyprawy','la salsa','sos'),
('En la Cocina','W kuchni','la cocina','kuchnia (pomieszczenie/mebel)'),
('En la Cocina','W kuchni','la olla','garnek'),
('En la Cocina','W kuchni','la sartén','patelnia'),
('En la Cocina','W kuchni','la cacerola','rondel'),
('En la Cocina','W kuchni','la tapadera','pokrywka'),
('En la Cocina','W kuchni','el cazo','chochla / rondelik'),
('En la Cocina','W kuchni','el cuchillo','nóż'),
('En la Cocina','W kuchni','la tabla de cortar','deska do krojenia'),
('En la Cocina','W kuchni','el cucharón','wielka łyżka / chochla'),
('En la Cocina','W kuchni','la espumadera','łyżka cedzakowa / szumówka'),
('En la Cocina','W kuchni','el rallador','tarka'),
('En la Cocina','W kuchni','el colador','sitko / durszlak'),
('En la Cocina','W kuchni','el escurridor','ociekacz / durszlak'),
('En la Cocina','W kuchni','el mortero','moździerz'),
('En la Cocina','W kuchni','el rodillo','wałek do ciasta'),
('En la Cocina','W kuchni','el bol','miska'),
('En la Cocina','W kuchni','la fuente','półmisek / naczynie żaroodporne'),
('En la Cocina','W kuchni','la bandeja','taca'),
('En la Cocina','W kuchni','el molde','forma do pieczenia'),
('En la Cocina','W kuchni','el delantal','fartuch'),
('En la Cocina','W kuchni','el paño de cocina','ścierka kuchenna'),
('En la Cocina','W kuchni','la esponja','gąbka'),
('En la Cocina','W kuchni','el estropajo','druciak / szorstka gąbka'),
('En la Cocina','W kuchni','el lavavajillas','zmywarka / płyn do naczyń'),
('En la Cocina','W kuchni','el horno','piekarnik'),
('En la Cocina','W kuchni','el microondas','mikrofalówka'),
('En la Cocina','W kuchni','el frigorífico / la nevera','lodówka'),
('En la Cocina','W kuchni','el congelador','zamrażarka'),
('En la Cocina','W kuchni','la batidora','blender / mikser'),
('En la Cocina','W kuchni','la tostadora','toster'),
('En la Cocina','W kuchni','la báscula de cocina','waga kuchenna'),
('En la Cocina','W kuchni','pelar','obierać'),
('En la Cocina','W kuchni','cortar','kroić / ciąć'),
('En la Cocina','W kuchni','picar','siekać'),
('En la Cocina','W kuchni','rallar','ścierać (na tarce)'),
('En la Cocina','W kuchni','batir','ubijać'),
('En la Cocina','W kuchni','mezclar','mieszać'),
('En la Cocina','W kuchni','freír','smażyć'),
('En la Cocina','W kuchni','hervir','gotować (wodę)'),
('En la Cocina','W kuchni','cocer','gotować (potrawę)'),
('En la Cocina','W kuchni','asar','piec (mięso)'),
('En la Cocina','W kuchni','hornear','piec (ciasto)'),
('En la Cocina','W kuchni','calentar','podgrzewać'),
('En la Cocina','W kuchni','descongelar','rozmrażać'),
('En la Cocina','W kuchni','la receta','przepis'),
('En la Cocina','W kuchni','el ingrediente','składnik'),
('En la Cocina','W kuchni','el chef','szef kuchni'),
('En la Cocina','W kuchni','preparar','przygotowywać'),
('En la Cocina','W kuchni','servir','serwować / podawać'),
('En la Cocina','W kuchni','lavar los platos','zmywać naczynia'),
('Higiene Personal','Higiena osobista','la higiene','higiena'),
('Higiene Personal','Higiena osobista','el baño','łazienka / kąpiel'),
('Higiene Personal','Higiena osobista','la ducha','prysznic'),
('Higiene Personal','Higiena osobista','la bañera','wanna'),
('Higiene Personal','Higiena osobista','el lavabo','umywalka'),
('Higiene Personal','Higiena osobista','el váter / el inodoro','toaleta / muszla klozetowa'),
('Higiene Personal','Higiena osobista','el jabón','mydło'),
('Higiene Personal','Higiena osobista','el gel de ducha','żel pod prysznic'),
('Higiene Personal','Higiena osobista','el champú','szampon'),
('Higiene Personal','Higiena osobista','el acondicionador','odżywka (do włosów)'),
('Higiene Personal','Higiena osobista','la esponja','gąbka'),
('Higiene Personal','Higiena osobista','la toalla','ręcznik'),
('Higiene Personal','Higiena osobista','el albornoz','szlafrok'),
('Higiene Personal','Higiena osobista','el cepillo de dientes','szczoteczka do zębów'),
('Higiene Personal','Higiena osobista','la pasta de dientes','pasta do zębów'),
('Higiene Personal','Higiena osobista','el enjuague bucal','płyn do płukania ust'),
('Higiene Personal','Higiena osobista','el hilo dental','nić dentystyczna'),
('Higiene Personal','Higiena osobista','el desodorante','dezodorant'),
('Higiene Personal','Higiena osobista','el perfume','perfumy'),
('Higiene Personal','Higiena osobista','la colonia','woda kolońska'),
('Higiene Personal','Higiena osobista','el cepillo','szczotka'),
('Higiene Personal','Higiena osobista','el peine','grzebień'),
('Higiene Personal','Higiena osobista','peinarse','czesać się'),
('Higiene Personal','Higiena osobista','lavarse','myć się'),
('Higiene Personal','Higiena osobista','ducharse','brać prysznic'),
('Higiene Personal','Higiena osobista','bañarse','kąpać się'),
('Higiene Personal','Higiena osobista','el papel higiénico','papier toaletowy'),
('Higiene Personal','Higiena osobista','el pañuelo','chusteczka'),
('Higiene Personal','Higiena osobista','el bastoncillo','patyczek higieniczny'),
('Higiene Personal','Higiena osobista','la maquinilla de afeitar','maszynka do golenia'),
('Higiene Personal','Higiena osobista','la espuma de afeitar','pianka do golenia'),
('Higiene Personal','Higiena osobista','afeitarse','golić się'),
('Higiene Personal','Higiena osobista','la crema hidratante','krem nawilżający'),
('Higiene Personal','Higiena osobista','el cortauñas','obcinacz do paznokci'),
('Higiene Personal','Higiena osobista','la lima','pilnik (do paznokci)'),
('Higiene Personal','Higiena osobista','las tijeras','nożyczki'),
('Higiene Personal','Higiena osobista','el secador de pelo','suszarka do włosów'),
('Higiene Personal','Higiena osobista','limpio','czysty'),
('Higiene Personal','Higiena osobista','sucio','brudny'),
('Higiene Personal','Higiena osobista','secarse','wycierać się / suszyć się'),
('Higiene Personal','Higiena osobista','el sudor','pot'),
('Higiene Personal','Higiena osobista','sudar','pocić się'),
('Higiene Personal','Higiena osobista','la pastilla de jabón','kostka mydła'),
('Higiene Personal','Higiena osobista','la toallita','chusteczka nawilżana'),
('Higiene Personal','Higiena osobista','el gel hidroalcohólico','żel antybakteryjny'),
('Higiene Personal','Higiena osobista','la higiene íntima','higiena intymna'),
('Higiene Personal','Higiena osobista','el espejo','lustro'),
('Higiene Personal','Higiena osobista','el grifo','kran'),
('Higiene Personal','Higiena osobista','el agua','woda'),
('Higiene Personal','Higiena osobista','la salud','zdrowie'),
('Cosméticos','Kosmetyki','el cosmético','kosmetyk'),
('Cosméticos','Kosmetyki','el maquillaje','makijaż'),
('Cosméticos','Kosmetyki','la crema','krem'),
('Cosméticos','Kosmetyki','la loción','balsam / lotion'),
('Cosméticos','Kosmetyki','el sérum','serum'),
('Cosméticos','Kosmetyki','el tónico','tonik'),
('Cosméticos','Kosmetyki','el desmaquillante','płyn do demakijażu'),
('Cosméticos','Kosmetyki','el algodón','wacik / bawełna'),
('Cosméticos','Kosmetyki','la base de maquillaje','podkład'),
('Cosméticos','Kosmetyki','el corrector','korektor'),
('Cosméticos','Kosmetyki','los polvos','puder'),
('Cosméticos','Kosmetyki','el colorete','róż do policzków'),
('Cosméticos','Kosmetyki','el bronceador','bronzer'),
('Cosméticos','Kosmetyki','el iluminador','rozświetlacz'),
('Cosméticos','Kosmetyki','la sombra de ojos','cień do powiek'),
('Cosméticos','Kosmetyki','el delineador','eyeliner / konturówka'),
('Cosméticos','Kosmetyki','el rímel','tusz do rzęs'),
('Cosméticos','Kosmetyki','el lápiz de labios','konturówka do ust'),
('Cosméticos','Kosmetyki','el pintalabios','szminka'),
('Cosméticos','Kosmetyki','el brillo de labios','błyszczyk'),
('Cosméticos','Kosmetyki','el bálsamo labial','balsam do ust'),
('Cosméticos','Kosmetyki','el esmalte de uñas','lakier do paznokci'),
('Cosméticos','Kosmetyki','el quitaesmalte','zmywacz do paznokci'),
('Cosméticos','Kosmetyki','el pincel','pędzelek (np. do cieni)'),
('Cosméticos','Kosmetyki','la brocha','pędzel (np. do pudru)'),
('Cosméticos','Kosmetyki','la esponja de maquillaje','gąbeczka do makijażu'),
('Cosméticos','Kosmetyki','el neceser','kosmetyczka'),
('Cosméticos','Kosmetyki','el perfume','perfumy'),
('Cosméticos','Kosmetyki','la mascarilla','maseczka'),
('Cosméticos','Kosmetyki','la exfoliación','peeling (zabieg)'),
('Cosméticos','Kosmetyki','el exfoliante','peeling (produkt)'),
('Cosméticos','Kosmetyki','la crema antiedad','krem przeciwzmarszczkowy'),
('Cosméticos','Kosmetyki','el protector solar','krem z filtrem'),
('Cosméticos','Kosmetyki','maquillarse','malować się'),
('Cosméticos','Kosmetyki','desmaquillarse','zmywać makijaż'),
('Cosméticos','Kosmetyki','aplicarse','nakładać (np. krem)'),
('Cosméticos','Kosmetyki','difuminar','blendować / rozcierać'),
('Cosméticos','Kosmetyki','el tono','odcień'),
('Cosméticos','Kosmetyki','el cutis','cera'),
('Cosméticos','Kosmetyki','la piel','skóra'),
('Cosméticos','Kosmetyki','la ojera','cień pod okiem'),
('Cosméticos','Kosmetyki','la arruga','zmarszczka'),
('Cosméticos','Kosmetyki','el grano / el acné','krosta / trądzik'),
('Cosméticos','Kosmetyki','la belleza','uroda'),
('Cosméticos','Kosmetyki','el salón de belleza','salon kosmetyczny'),
('Cosméticos','Kosmetyki','la estética','estetyka'),
('Cosméticos','Kosmetyki','la manicura','manicure'),
('Cosméticos','Kosmetyki','la pedicura','pedicure'),
('Cosméticos','Kosmetyki','teñir','farbować'),
('Cosméticos','Kosmetyki','el tinte','farba do włosów');
