insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Expresiones de Cortesía','Zwroty grzecznościowe','por favor','proszę (prosząc)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','gracias','dziękuję'),
('Expresiones de Cortesía','Zwroty grzecznościowe','muchas gracias','bardzo dziękuję'),
('Expresiones de Cortesía','Zwroty grzecznościowe','muchísimas gracias','stokrotnie dziękuję'),
('Expresiones de Cortesía','Zwroty grzecznościowe','de nada','nie ma za co'),
('Expresiones de Cortesía','Zwroty grzecznościowe','no hay de qué','nie ma o co (nie ma za co)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','perdón','przepraszam'),
('Expresiones de Cortesía','Zwroty grzecznościowe','perdone','przepraszam (Pana/Panią)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','perdona','przepraszam (cię)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','lo siento','przykro mi / przepraszam'),
('Expresiones de Cortesía','Zwroty grzecznościowe','disculpe','przepraszam (Pana/Panią - zwrócenie uwagi)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','disculpa','przepraszam (cię - zwrócenie uwagi)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','con permiso','za pozwoleniem (przechodząc)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','pase','proszę wejść / przejść'),
('Expresiones de Cortesía','Zwroty grzecznościowe','adelante','proszę wejść / naprzód'),
('Expresiones de Cortesía','Zwroty grzecznościowe','buen provecho','smacznego'),
('Expresiones de Cortesía','Zwroty grzecznościowe','que aproveche','smacznego'),
('Expresiones de Cortesía','Zwroty grzecznościowe','salud','na zdrowie (kichnięcie / toast)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','Jesús','na zdrowie (po kichnięciu)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','bienvenido','witaj / mile widziany'),
('Expresiones de Cortesía','Zwroty grzecznościowe','encantado','miło mi (mówi mężczyzna)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','encantada','miło mi (mówi kobieta)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','mucho gusto','bardzo mi miło'),
('Expresiones de Cortesía','Zwroty grzecznościowe','el gusto es mío','cała przyjemność po mojej stronie'),
('Expresiones de Cortesía','Zwroty grzecznościowe','igualmente','nawzajem'),
('Expresiones de Cortesía','Zwroty grzecznościowe','felicidades','gratulacje / wszystkiego najlepszego'),
('Expresiones de Cortesía','Zwroty grzecznościowe','enhorabuena','gratulacje'),
('Expresiones de Cortesía','Zwroty grzecznościowe','feliz cumpleaños','wszystkiego najlepszego z okazji urodzin'),
('Expresiones de Cortesía','Zwroty grzecznościowe','buen viaje','miłej podróży'),
('Expresiones de Cortesía','Zwroty grzecznościowe','felices fiestas','wesołych świąt'),
('Expresiones de Cortesía','Zwroty grzecznościowe','que te mejores','wracaj do zdrowia'),
('Expresiones de Cortesía','Zwroty grzecznościowe','buena suerte','powdzenia'),
('Expresiones de Cortesía','Zwroty grzecznościowe','¡ánimo!','głowa do góry! / śmiało!'),
('Expresiones de Cortesía','Zwroty grzecznościowe','cuidado','ostrożnie / uwaga'),
('Expresiones de Cortesía','Zwroty grzecznościowe','no se preocupe','proszę się nie martwić'),
('Expresiones de Cortesía','Zwroty grzecznościowe','no te preocupes','nie martw się'),
('Expresiones de Cortesía','Zwroty grzecznościowe','¿puedo ayudarle?','w czym mogę pomóc?'),
('Expresiones de Cortesía','Zwroty grzecznościowe','a su servicio','do usług'),
('Expresiones de Cortesía','Zwroty grzecznościowe','es muy amable','to bardzo miłe (z Pana/Pani strony)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','gracias por su ayuda','dziękuję za pomoc'),
('Expresiones de Cortesía','Zwroty grzecznościowe','un placer','przyjemność (po mojej stronie)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','buen fin de semana','miłego weekendu'),
('Expresiones de Cortesía','Zwroty grzecznościowe','buen día','miłego dnia'),
('Expresiones de Cortesía','Zwroty grzecznościowe','que le vaya bien','powodzenia (niech się Panu dobrze wiedzie)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','que te vaya bien','powodzenia (niech ci się dobrze wiedzie)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','a ti','tobie również (w odpowiedzi na podziękowanie)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','a usted','Panu/Pani również'),
('Expresiones de Cortesía','Zwroty grzecznościowe','claro','jasne / oczywiście'),
('Expresiones de Cortesía','Zwroty grzecznościowe','por supuesto','oczywiście'),
('Expresiones de Cortesía','Zwroty grzecznościowe','desde luego','oczywiście / jak najbardziej'),
('Saludos y Despedidas','Powitania i pożegnania','hola','cześć (powitanie)'),
('Saludos y Despedidas','Powitania i pożegnania','adiós','do widzenia'),
('Saludos y Despedidas','Powitania i pożegnania','buenos días','dzień dobry (rano)'),
('Saludos y Despedidas','Powitania i pożegnania','buenas tardes','dzień dobry (po południu)'),
('Saludos y Despedidas','Powitania i pożegnania','buenas noches','dobry wieczór / dobranoc'),
('Saludos y Despedidas','Powitania i pożegnania','hasta luego','do zobaczenia (później)'),
('Saludos y Despedidas','Powitania i pożegnania','hasta pronto','do zobaczenia wkrótce'),
('Saludos y Despedidas','Powitania i pożegnania','hasta mañana','do jutra'),
('Saludos y Despedidas','Powitania i pożegnania','hasta la vista','do zobaczenia'),
('Saludos y Despedidas','Powitania i pożegnania','hasta ahora','na razie / do zobaczenia za chwilę'),
('Saludos y Despedidas','Powitania i pożegnania','nos vemos','widzimy się / do zobaczenia'),
('Saludos y Despedidas','Powitania i pożegnania','chao / chau','cześć (pożegnanie)'),
('Saludos y Despedidas','Powitania i pożegnania','qué tal','jak tam? / co słychać?'),
('Saludos y Despedidas','Powitania i pożegnania','cómo estás','jak się masz?'),
('Saludos y Despedidas','Powitania i pożegnania','cómo está','jak się Pan/Pani ma?'),
('Saludos y Despedidas','Powitania i pożegnania','cómo te va','jak ci leci?'),
('Saludos y Despedidas','Powitania i pożegnania','qué pasa','co słychać? / co się dzieje?'),
('Saludos y Despedidas','Powitania i pożegnania','qué hay','co słychać?'),
('Saludos y Despedidas','Powitania i pożegnania','qué cuentas','co powiesz? / co słychać?'),
('Saludos y Despedidas','Powitania i pożegnania','bien','dobrze'),
('Saludos y Despedidas','Powitania i pożegnania','muy bien','bardzo dobrze'),
('Saludos y Despedidas','Powitania i pożegnania','mal','źle'),
('Saludos y Despedidas','Powitania i pożegnania','regular','tak sobie'),
('Saludos y Despedidas','Powitania i pożegnania','tirando','jakoś leci'),
('Saludos y Despedidas','Powitania i pożegnania','todo bien','wszystko dobrze'),
('Saludos y Despedidas','Powitania i pożegnania','y tú','a ty?'),
('Saludos y Despedidas','Powitania i pożegnania','y usted','a Pan/Pani?'),
('Saludos y Despedidas','Powitania i pożegnania','saludos','pozdrowienia'),
('Saludos y Despedidas','Powitania i pożegnania','recuerdos a','pozdrowienia dla'),
('Saludos y Despedidas','Powitania i pożegnania','un abrazo','uściski (dosł. uścisk)'),
('Saludos y Despedidas','Powitania i pożegnania','un beso','buziak (dosł. pocałunek)'),
('Saludos y Despedidas','Powitania i pożegnania','besos','buziaki'),
('Saludos y Despedidas','Powitania i pożegnania','cuidaros','trzymajcie się'),
('Saludos y Despedidas','Powitania i pożegnania','cuídate','trzymaj się'),
('Saludos y Despedidas','Powitania i pożegnania','cuídese','niech Pan/Pani trzyma się'),
('Saludos y Despedidas','Powitania i pożegnania','buenas','dzień dobry / cześć (potocznie)'),
('Saludos y Despedidas','Powitania i pożegnania','hasta la próxima','do następnego razu'),
('Saludos y Despedidas','Powitania i pożegnania','hasta siempre','żegnaj na zawsze'),
('Saludos y Despedidas','Powitania i pożegnania','bienvenido','witaj (do mężczyzny)'),
('Saludos y Despedidas','Powitania i pożegnania','bienvenida','witaj (do kobiety)'),
('Saludos y Despedidas','Powitania i pożegnania','bienvenidos','witajcie (l.mn.)'),
('Saludos y Despedidas','Powitania i pożegnania','pase','proszę wejść'),
('Saludos y Despedidas','Powitania i pożegnania','qué alegría verte','jak miło cię widzieć'),
('Saludos y Despedidas','Powitania i pożegnania','cuánto tiempo','kopę lat / ile to czasu'),
('Saludos y Despedidas','Powitania i pożegnania','hace mucho que no nos vemos','dawno się nie widzieliśmy'),
('Saludos y Despedidas','Powitania i pożegnania','me alegro de verte','cieszę się, że cię widzę'),
('Saludos y Despedidas','Powitania i pożegnania','que tengas un buen día','miłego dnia'),
('Saludos y Despedidas','Powitania i pożegnania','feliz día','szczęśliwego dnia'),
('Saludos y Despedidas','Powitania i pożegnania','despidirse','żegnać się'),
('Saludos y Despedidas','Powitania i pożegnania','saludar','witać / pozdrawiać'),
('La Infancia','Dzieciństwo','la infancia','dzieciństwo'),
('La Infancia','Dzieciństwo','el niño','chłopiec / dziecko'),
('La Infancia','Dzieciństwo','la niña','dziewczynka'),
('La Infancia','Dzieciństwo','el bebé','niemowlę'),
('La Infancia','Dzieciństwo','el recién nacido','noworodek'),
('La Infancia','Dzieciństwo','el chupete','smoczek'),
('La Infancia','Dzieciństwo','el biberón','butelka ze smoczkiem'),
('La Infancia','Dzieciństwo','el pañal','pielucha'),
('La Infancia','Dzieciństwo','la cuna','łóżeczko dziecięce'),
('La Infancia','Dzieciństwo','el cochecito','wózek dziecięcy'),
('La Infancia','Dzieciństwo','el juguete','zabawka'),
('La Infancia','Dzieciństwo','el peluche','pluszak'),
('La Infancia','Dzieciństwo','el muñeco','lalka / figurka'),
('La Infancia','Dzieciństwo','la muñeca','lalka (zabawka)'),
('La Infancia','Dzieciństwo','el sonajero','grzechotka'),
('La Infancia','Dzieciństwo','el cuento','bajka / opowiadanie'),
('La Infancia','Dzieciństwo','gatear','raczkować'),
('La Infancia','Dzieciństwo','llorar','płakać'),
('La Infancia','Dzieciństwo','reír','śmiać się'),
('La Infancia','Dzieciństwo','sonreír','uśmiechać się'),
('La Infancia','Dzieciństwo','jugar','bawić się / grać'),
('La Infancia','Dzieciństwo','crecer','rosnąć'),
('La Infancia','Dzieciństwo','nacer','urodzić się'),
('La Infancia','Dzieciństwo','dar a luz','urodzić (wydać na świat)'),
('La Infancia','Dzieciństwo','el embarazo','ciąża'),
('La Infancia','Dzieciństwo','embarazada','w ciąży'),
('La Infancia','Dzieciństwo','la guardería','żłobek / przedszkole'),
('La Infancia','Dzieciństwo','el colegio','szkoła (podstawowa)'),
('La Infancia','Dzieciństwo','la niñera','niania'),
('La Infancia','Dzieciństwo','el patio de recreo','plac zabaw'),
('La Infancia','Dzieciństwo','el columpio','huśtawka'),
('La Infancia','Dzieciństwo','el tobogán','zjeżdżalnia'),
('La Infancia','Dzieciństwo','el arenero','piaskownica'),
('La Infancia','Dzieciństwo','el escondite','chowanego'),
('La Infancia','Dzieciństwo','travieso','niegrzeczny / psotny'),
('La Infancia','Dzieciństwo','obediente','posłuszny'),
('La Infancia','Dzieciństwo','desobediente','nieposłuszny'),
('La Infancia','Dzieciństwo','castigar','karać'),
('La Infancia','Dzieciństwo','el castigo','kara'),
('La Infancia','Dzieciństwo','portarse bien','zachowywać się dobrze'),
('La Infancia','Dzieciństwo','portarse mal','zachowywać się źle'),
('La Infancia','Dzieciństwo','mimar','rozpieszczać'),
('La Infancia','Dzieciństwo','el mimo','pieszczota'),
('La Infancia','Dzieciństwo','abrazar','przytulać'),
('La Infancia','Dzieciństwo','el abrazo','uścisk / przytulenie'),
('La Infancia','Dzieciństwo','la inocencia','niewinność'),
('La Infancia','Dzieciństwo','el huérfano','sierota'),
('La Infancia','Dzieciństwo','la nana','kołysanka'),
('La Infancia','Dzieciństwo','el parque infantil','plac zabaw (park)'),
('La Infancia','Dzieciństwo','amamantar','karmić piersią'),
('La Vejez','Starość','la vejez','starość'),
('La Vejez','Starość','el anciano','starzec / starszy pan'),
('La Vejez','Starość','la anciana','starsza pani'),
('La Vejez','Starość','mayor','starszy'),
('La Vejez','Starość','el abuelo','dziadek'),
('La Vejez','Starość','la abuela','babcia'),
('La Vejez','Starość','los abuelos','dziadkowie'),
('La Vejez','Starość','envejecer','starzeć się'),
('La Vejez','Starość','la arruga','zmarszczka'),
('La Vejez','Starość','arrugado','pomarszczony'),
('La Vejez','Starość','la cana','siwy włos'),
('La Vejez','Starość','canoso','siwy'),
('La Vejez','Starość','calvo','łysy'),
('La Vejez','Starość','la pensión','emerytura (pieniądze)'),
('La Vejez','Starość','la jubilación','emerytura (stan)'),
('La Vejez','Starość','jubilarse','przejść na emeryturę'),
('La Vejez','Starość','el jubilado','emeryt'),
('La Vejez','Starość','el bastón','laska'),
('La Vejez','Starość','la silla de ruedas','wózek inwalidzki'),
('La Vejez','Starość','las gafas','okulary'),
('La Vejez','Starość','el audífono','aparat słuchowy'),
('La Vejez','Starość','la dentadura postiza','sztuczna szczęka'),
('La Vejez','Starość','la residencia de ancianos','dom spokojnej starości'),
('La Vejez','Starość','el asilo','przytułek'),
('La Vejez','Starość','cuidar','opiekować się'),
('La Vejez','Starość','el cuidador','opiekun'),
('La Vejez','Starość','la sabiduría','mądrość'),
('La Vejez','Starość','sabio','mądry'),
('La Vejez','Starość','la experiencia','doświadczenie'),
('La Vejez','Starość','la memoria','pamięć'),
('La Vejez','Starość','olvidar','zapominać'),
('La Vejez','Starość','la enfermedad','choroba'),
('La Vejez','Starość','sordo','głuchy'),
('La Vejez','Starość','ciego','ślepy / niewidomy'),
('La Vejez','Starość','la soledad','samotność'),
('La Vejez','Starość','solitario','samotny'),
('La Vejez','Starość','el respeto','szacunek'),
('La Vejez','Starość','respetar','szanować'),
('La Vejez','Starość','la generación','pokolenie'),
('La Vejez','Starość','el nieto','wnuk'),
('La Vejez','Starość','la nieta','wnuczka'),
('La Vejez','Starość','la esperanza de vida','długość życia'),
('La Vejez','Starość','longevo','długowieczny'),
('La Vejez','Starość','frágil','kruchy'),
('La Vejez','Starość','la salud','zdrowie'),
('La Vejez','Starość','la edad','wiek'),
('La Vejez','Starość','cumplir años','kończyć lata / mieć urodziny'),
('La Vejez','Starość','el testamento','testament'),
('La Vejez','Starość','la herencia','spadek'),
('La Vejez','Starość','viudo','wdowiec'),
('El Matrimonio','Małżeństwo','el matrimonio','małżeństwo'),
('El Matrimonio','Małżeństwo','la boda','ślub / wesele'),
('El Matrimonio','Małżeństwo','casarse','brać ślub'),
('El Matrimonio','Małżeństwo','el marido','mąż'),
('El Matrimonio','Małżeństwo','la mujer','żona / kobieta'),
('El Matrimonio','Małżeństwo','el esposo','małżonek'),
('El Matrimonio','Małżeństwo','la esposa','małżonka'),
('El Matrimonio','Małżeństwo','el novio','pan młody / chłopak (sympatia)'),
('El Matrimonio','Małżeństwo','la novia','panna młoda / dziewczyna (sympatia)'),
('El Matrimonio','Małżeństwo','los novios','para młoda / narzeczeni'),
('El Matrimonio','Małżeństwo','el anillo','pierścionek'),
('El Matrimonio','Małżeństwo','la alianza','obrączka'),
('El Matrimonio','Małżeństwo','el vestido de novia','suknia ślubna'),
('El Matrimonio','Małżeństwo','el ramo','bukiet'),
('El Matrimonio','Małżeństwo','el velo','welon'),
('El Matrimonio','Małżeństwo','el traje','garnitur'),
('El Matrimonio','Małżeństwo','la iglesia','kościół'),
('El Matrimonio','Małżeństwo','el juzgado','urząd stanu cywilnego / sąd'),
('El Matrimonio','Małżeństwo','el cura','ksiądz'),
('El Matrimonio','Małżeństwo','el juez','sędzia'),
('El Matrimonio','Małżeństwo','el testigo','świadek'),
('El Matrimonio','Małżeństwo','el padrino','świadek / ojciec chrzestny'),
('El Matrimonio','Małżeństwo','la madrina','świadkowa / matka chrzestna'),
('El Matrimonio','Małżeństwo','la invitación','zaproszenie'),
('El Matrimonio','Małżeństwo','el invitado','gość'),
('El Matrimonio','Małżeństwo','el banquete','bankiet / przyjęcie'),
('El Matrimonio','Małżeństwo','el brindis','toast'),
('El Matrimonio','Małżeństwo','la tarta nupcial','tort weselny'),
('El Matrimonio','Małżeństwo','la luna de miel','podróż poślubna / miodowy miesiąc'),
('El Matrimonio','Małżeństwo','el viaje de novios','podróż poślubna'),
('El Matrimonio','Małżeństwo','enamorarse','zakochać się'),
('El Matrimonio','Małżeństwo','el amor','miłość'),
('El Matrimonio','Małżeństwo','querer','kochać / chcieć'),
('El Matrimonio','Małżeństwo','amar','kochać (głęboko)'),
('El Matrimonio','Małżeństwo','la pareja','para / partner'),
('El Matrimonio','Małżeństwo','el compromiso','zaręczyny / zobowiązanie'),
('El Matrimonio','Małżeństwo','prometerse','zaręczyć się'),
('El Matrimonio','Małżeństwo','el aniversario','rocznica'),
('El Matrimonio','Małżeństwo','las bodas de plata','srebrne gody (25 lat)'),
('El Matrimonio','Małżeństwo','las bodas de oro','złote gody (50 lat)'),
('El Matrimonio','Małżeństwo','la felicidad','szczęście'),
('El Matrimonio','Małżeństwo','fiel','wierny'),
('El Matrimonio','Małżeństwo','infiel','niewierny'),
('El Matrimonio','Małżeństwo','los celos','zazdrość'),
('El Matrimonio','Małżeństwo','discutir','kłócić się'),
('El Matrimonio','Małżeństwo','la separación','separacja'),
('El Matrimonio','Małżeństwo','separarse','separować się / rozstawać się'),
('El Matrimonio','Małżeństwo','el divorcio','rozwód'),
('El Matrimonio','Małżeństwo','divorciarse','rozwodzić się'),
('El Matrimonio','Małżeństwo','soltero','kawaler / singiel'),
('El Divorcio','Rozwód','el divorcio','rozwód'),
('El Divorcio','Rozwód','la separación','separacja'),
('El Divorcio','Rozwód','divorciarse','rozwodzić się'),
('El Divorcio','Rozwód','separarse','rozstawać się / separować się'),
('El Divorcio','Rozwód','el exmarido','były mąż'),
('El Divorcio','Rozwód','la exmujer','była żona'),
('El Divorcio','Rozwód','la expareja','były partner / była partnerka'),
('El Divorcio','Rozwód','el abogado','prawnik'),
('El Divorcio','Rozwód','el juez','sędzia'),
('El Divorcio','Rozwód','el tribunal','sąd'),
('El Divorcio','Rozwód','la demanda','pozew'),
('El Divorcio','Rozwód','el acuerdo','porozumienie'),
('El Divorcio','Rozwód','el desacuerdo','brak porozumienia'),
('El Divorcio','Rozwód','la firma','podpis'),
('El Divorcio','Rozwód','los papeles','papiery / dokumenty'),
('El Divorcio','Rozwód','el proceso','proces'),
('El Divorcio','Rozwód','la pensión alimenticia','alimenty'),
('El Divorcio','Rozwód','la custodia','opieka nad dziećmi'),
('El Divorcio','Rozwód','la custodia compartida','opieka naprzemienna'),
('El Divorcio','Rozwód','el régimen de visitas','ustalone wizyty (z dziećmi)'),
('El Divorcio','Rozwód','los bienes','majątek / dobra'),
('El Divorcio','Rozwód','la separación de bienes','rozdzielność majątkowa'),
('El Divorcio','Rozwód','el patrimonio','patrymonium / majątek'),
('El Divorcio','Rozwód','la crisis','kryzys'),
('El Divorcio','Rozwód','el conflicto','konflikt'),
('El Divorcio','Rozwód','la discusión','kłótnia'),
('El Divorcio','Rozwód','pelear','kłócić się / walczyć'),
('El Divorcio','Rozwód','la ruptura','zerwanie / rozpad'),
('El Divorcio','Rozwód','romper','zrywać'),
('El Divorcio','Rozwód','dejar','zostawiać (kogoś)'),
('El Divorcio','Rozwód','la infidelidad','niewierność'),
('El Divorcio','Rozwód','el engaño','oszustwo / zdrada'),
('El Divorcio','Rozwód','engañar','zdradzać / oszukiwać'),
('El Divorcio','Rozwód','el amante','kochanek'),
('El Divorcio','Rozwód','sufrir','cierpieć'),
('El Divorcio','Rozwód','llorar','płakać'),
('El Divorcio','Rozwód','el dolor','ból'),
('El Divorcio','Rozwód','superar','przezwyciężyć'),
('El Divorcio','Rozwód','olvidar','zapomnieć'),
('El Divorcio','Rozwód','perdonar','wybaczyć'),
('El Divorcio','Rozwód','rehacer la vida','ułożyć sobie życie na nowo'),
('El Divorcio','Rozwód','soltero','kawaler / singiel'),
('El Divorcio','Rozwód','el apoyo','wsparcie'),
('El Divorcio','Rozwód','la familia','rodzina'),
('El Divorcio','Rozwód','el mediador','mediator'),
('El Divorcio','Rozwód','el fallo','orzeczenie sądu'),
('El Divorcio','Rozwód','el estrés','stres'),
('El Divorcio','Rozwód','la tensión','napięcie'),
('El Divorcio','Rozwód','la reconciliación','pojednanie'),
('El Divorcio','Rozwód','el fin','koniec'),
('Relaciones de Pareja','Relacje partnerskie','la relación','relacja / związek'),
('Relaciones de Pareja','Relacje partnerskie','la pareja','para / partner'),
('Relaciones de Pareja','Relacje partnerskie','el novio','chłopak'),
('Relaciones de Pareja','Relacje partnerskie','la novia','dziewczyna'),
('Relaciones de Pareja','Relacje partnerskie','el compañero','partner życiowy'),
('Relaciones de Pareja','Relacje partnerskie','salir','spotykać się / chodzić z kimś'),
('Relaciones de Pareja','Relacje partnerskie','la cita','randka'),
('Relaciones de Pareja','Relacje partnerskie','conocer','poznać'),
('Relaciones de Pareja','Relacje partnerskie','enamorarse','zakochać się'),
('Relaciones de Pareja','Relacje partnerskie','el amor','miłość'),
('Relaciones de Pareja','Relacje partnerskie','el cariño','czułość'),
('Relaciones de Pareja','Relacje partnerskie','querer','kochać / lubić'),
('Relaciones de Pareja','Relacje partnerskie','amar','kochać'),
('Relaciones de Pareja','Relacje partnerskie','el beso','pocałunek'),
('Relaciones de Pareja','Relacje partnerskie','besar','całować'),
('Relaciones de Pareja','Relacje partnerskie','el abrazo','uścisk / przytulenie'),
('Relaciones de Pareja','Relacje partnerskie','abrazar','przytulać'),
('Relaciones de Pareja','Relacje partnerskie','la caricia','pieszczota'),
('Relaciones de Pareja','Relacje partnerskie','acariciar','pieścić / głaskać'),
('Relaciones de Pareja','Relacje partnerskie','la pasión','pasja / namiętność'),
('Relaciones de Pareja','Relacje partnerskie','el romance','romans'),
('Relaciones de Pareja','Relacje partnerskie','romántico','romantyczny'),
('Relaciones de Pareja','Relacje partnerskie','la intimidad','intymność'),
('Relaciones de Pareja','Relacje partnerskie','el sexo','seks'),
('Relaciones de Pareja','Relacje partnerskie','hacer el amor','uprawiać miłość'),
('Relaciones de Pareja','Relacje partnerskie','la confianza','zaufanie'),
('Relaciones de Pareja','Relacje partnerskie','confiar','ufać'),
('Relaciones de Pareja','Relacje partnerskie','la fidelidad','wierność'),
('Relaciones de Pareja','Relacje partnerskie','fiel','wierny'),
('Relaciones de Pareja','Relacje partnerskie','el respeto','szacunek'),
('Relaciones de Pareja','Relacje partnerskie','respetar','szanować'),
('Relaciones de Pareja','Relacje partnerskie','la comunicación','komunikacja'),
('Relaciones de Pareja','Relacje partnerskie','el apoyo','wsparcie'),
('Relaciones de Pareja','Relacje partnerskie','apoyar','wspierać'),
('Relaciones de Pareja','Relacje partnerskie','compartir','dzielić'),
('Relaciones de Pareja','Relacje partnerskie','la convivencia','wspólne życie'),
('Relaciones de Pareja','Relacje partnerskie','convivir','żyć razem'),
('Relaciones de Pareja','Relacje partnerskie','el compromiso','zaangażowanie / zaręczyny'),
('Relaciones de Pareja','Relacje partnerskie','comprometerse','zaręczyć się / zaangażować'),
('Relaciones de Pareja','Relacje partnerskie','la comprensión','zrozumienie'),
('Relaciones de Pareja','Relacje partnerskie','comprender','rozumieć'),
('Relaciones de Pareja','Relacje partnerskie','perdonar','wybaczać'),
('Relaciones de Pareja','Relacje partnerskie','pedir perdón','prosić o wybaczenie'),
('Relaciones de Pareja','Relacje partnerskie','los celos','zazdrość'),
('Relaciones de Pareja','Relacje partnerskie','celoso','zazdrosny'),
('Relaciones de Pareja','Relacje partnerskie','pelear','kłócić się'),
('Relaciones de Pareja','Relacje partnerskie','reconciliarse','godzić się'),
('Relaciones de Pareja','Relacje partnerskie','la media naranja','druga połówka (dosł. pół pomarańczy)'),
('Relaciones de Pareja','Relacje partnerskie','atraer','przyciągać'),
('Relaciones de Pareja','Relacje partnerskie','el flechazo','miłość od pierwszego wejrzenia (strzała amora)'),
('Sentimientos Positivos','Pozytywne uczucia','la felicidad','szczęście'),
('Sentimientos Positivos','Pozytywne uczucia','feliz','szczęśliwy'),
('Sentimientos Positivos','Pozytywne uczucia','la alegría','radość'),
('Sentimientos Positivos','Pozytywne uczucia','alegre','radosny'),
('Sentimientos Positivos','Pozytywne uczucia','el optimismo','optymizm'),
('Sentimientos Positivos','Pozytywne uczucia','optimista','optymistyczny'),
('Sentimientos Positivos','Pozytywne uczucia','la esperanza','nadzieja'),
('Sentimientos Positivos','Pozytywne uczucia','esperanzado','pełen nadziei'),
('Sentimientos Positivos','Pozytywne uczucia','la ilusión','ekscytacja / złudzenie'),
('Sentimientos Positivos','Pozytywne uczucia','ilusionado','podekscytowany'),
('Sentimientos Positivos','Pozytywne uczucia','el entusiasmo','entuzjazm'),
('Sentimientos Positivos','Pozytywne uczucia','entusiasta','entuzjastyczny'),
('Sentimientos Positivos','Pozytywne uczucia','la paz','pokój'),
('Sentimientos Positivos','Pozytywne uczucia','pacífico','spokojny / pokojowy'),
('Sentimientos Positivos','Pozytywne uczucia','la tranquilidad','spokój'),
('Sentimientos Positivos','Pozytywne uczucia','tranquilo','spokojny'),
('Sentimientos Positivos','Pozytywne uczucia','la calma','cisza / spokój'),
('Sentimientos Positivos','Pozytywne uczucia','calmado','opanowany'),
('Sentimientos Positivos','Pozytywne uczucia','la satisfacción','satysfakcja'),
('Sentimientos Positivos','Pozytywne uczucia','satisfecho','zadowolony'),
('Sentimientos Positivos','Pozytywne uczucia','el orgullo','duma'),
('Sentimientos Positivos','Pozytywne uczucia','orgulloso','dumny'),
('Sentimientos Positivos','Pozytywne uczucia','la gratitud','wdzięczność'),
('Sentimientos Positivos','Pozytywne uczucia','agradecido','wdzięczny'),
('Sentimientos Positivos','Pozytywne uczucia','el alivio','ulga'),
('Sentimientos Positivos','Pozytywne uczucia','aliviado','odczuwający ulgę'),
('Sentimientos Positivos','Pozytywne uczucia','la admiración','podziw'),
('Sentimientos Positivos','Pozytywne uczucia','admirado','zachwycony'),
('Sentimientos Positivos','Pozytywne uczucia','el asombro','zdumienie / podziw'),
('Sentimientos Positivos','Pozytywne uczucia','asombrado','zdumiony'),
('Sentimientos Positivos','Pozytywne uczucia','el cariño','czułość / sympatia'),
('Sentimientos Positivos','Pozytywne uczucia','cariñoso','czuły'),
('Sentimientos Positivos','Pozytywne uczucia','la ternura','tkliwość'),
('Sentimientos Positivos','Pozytywne uczucia','tierno','tkliwy / czuły'),
('Sentimientos Positivos','Pozytywne uczucia','la empatía','empatia'),
('Sentimientos Positivos','Pozytywne uczucia','empático','empatyczny'),
('Sentimientos Positivos','Pozytywne uczucia','la simpatía','sympatia'),
('Sentimientos Positivos','Pozytywne uczucia','simpático','sympatyczny'),
('Sentimientos Positivos','Pozytywne uczucia','la confianza','zaufanie / pewność'),
('Sentimientos Positivos','Pozytywne uczucia','confiado','ufny / pewny siebie'),
('Sentimientos Positivos','Pozytywne uczucia','la seguridad','bezpieczeństwo / pewność'),
('Sentimientos Positivos','Pozytywne uczucia','seguro','pewny'),
('Sentimientos Positivos','Pozytywne uczucia','la motivación','motywacja'),
('Sentimientos Positivos','Pozytywne uczucia','motivado','zmotywowany'),
('Sentimientos Positivos','Pozytywne uczucia','la inspiración','inspiracja'),
('Sentimientos Positivos','Pozytywne uczucia','inspirado','zainspirowany'),
('Sentimientos Positivos','Pozytywne uczucia','la pasión','pasja'),
('Sentimientos Positivos','Pozytywne uczucia','apasionado','pełen pasji'),
('Sentimientos Positivos','Pozytywne uczucia','la valentía','odwaga'),
('Sentimientos Positivos','Pozytywne uczucia','valiente','odważny'),
('Sentimientos Negativos','Negatywne uczucia','la tristeza','smutek'),
('Sentimientos Negativos','Negatywne uczucia','triste','smutny'),
('Sentimientos Negativos','Negatywne uczucia','la depresión','depresja'),
('Sentimientos Negativos','Negatywne uczucia','deprimido','zdołowany'),
('Sentimientos Negativos','Negatywne uczucia','el dolor','ból'),
('Sentimientos Negativos','Negatywne uczucia','dolido','zraniony'),
('Sentimientos Negativos','Negatywne uczucia','la pena','smutek / żal'),
('Sentimientos Negativos','Negatywne uczucia','apenado','zasmucony'),
('Sentimientos Negativos','Negatywne uczucia','la melancolía','melancholia'),
('Sentimientos Negativos','Negatywne uczucia','melancólico','melancholijny'),
('Sentimientos Negativos','Negatywne uczucia','el llanto','płacz'),
('Sentimientos Negativos','Negatywne uczucia','la ira','gniew'),
('Sentimientos Negativos','Negatywne uczucia','iracundo','gniewny'),
('Sentimientos Negativos','Negatywne uczucia','el enfado','złość'),
('Sentimientos Negativos','Negatywne uczucia','enfadado','zły'),
('Sentimientos Negativos','Negatywne uczucia','el enojo','złość'),
('Sentimientos Negativos','Negatywne uczucia','enojado','zły'),
('Sentimientos Negativos','Negatywne uczucia','el odio','nienawiść'),
('Sentimientos Negativos','Negatywne uczucia','el rencor','uraza'),
('Sentimientos Negativos','Negatywne uczucia','rencoroso','pamiętliwy / mściwy'),
('Sentimientos Negativos','Negatywne uczucia','la amargura','gorycz'),
('Sentimientos Negativos','Negatywne uczucia','amargado','zgorzkniały'),
('Sentimientos Negativos','Negatywne uczucia','el miedo','strach'),
('Sentimientos Negativos','Negatywne uczucia','miedoso','strachliwy'),
('Sentimientos Negativos','Negatywne uczucia','el temor','obawa'),
('Sentimientos Negativos','Negatywne uczucia','temeroso','bojaźliwy'),
('Sentimientos Negativos','Negatywne uczucia','el pánico','panika'),
('Sentimientos Negativos','Negatywne uczucia','el terror','przerażenie'),
('Sentimientos Negativos','Negatywne uczucia','aterrorizado','przerażony'),
('Sentimientos Negativos','Negatywne uczucia','la ansiedad','niepokój'),
('Sentimientos Negativos','Negatywne uczucia','ansioso','zaniepokojony'),
('Sentimientos Negativos','Negatywne uczucia','la angustia','udręka / lęk'),
('Sentimientos Negativos','Negatywne uczucia','angustiado','udręczony'),
('Sentimientos Negativos','Negatywne uczucia','el estrés','stres'),
('Sentimientos Negativos','Negatywne uczucia','estresado','zestresowany'),
('Sentimientos Negativos','Negatywne uczucia','la frustración','frustracja'),
('Sentimientos Negativos','Negatywne uczucia','frustrado','sfrustrowany'),
('Sentimientos Negativos','Negatywne uczucia','la decepción','rozczarowanie'),
('Sentimientos Negativos','Negatywne uczucia','decepcionado','rozczarowany'),
('Sentimientos Negativos','Negatywne uczucia','la culpa','wina'),
('Sentimientos Negativos','Negatywne uczucia','culpable','winny'),
('Sentimientos Negativos','Negatywne uczucia','la vergüenza','wstyd'),
('Sentimientos Negativos','Negatywne uczucia','avergonzado','zawstydzony'),
('Sentimientos Negativos','Negatywne uczucia','el aburrimiento','nuda'),
('Sentimientos Negativos','Negatywne uczucia','aburrido','znudzony'),
('Sentimientos Negativos','Negatywne uczucia','la envidia','zazdrość (zawiść)'),
('Sentimientos Negativos','Negatywne uczucia','envidioso','zawistny'),
('Sentimientos Negativos','Negatywne uczucia','la apatía','apatia'),
('Sentimientos Negativos','Negatywne uczucia','apático','apatyczny'),
('Sentimientos Negativos','Negatywne uczucia','la soledad','samotność'),
('Características Físicas','Cechy fizyczne','el aspecto','wygląd'),
('Características Físicas','Cechy fizyczne','la apariencia','aparycja'),
('Características Físicas','Cechy fizyczne','alto','wysoki'),
('Características Físicas','Cechy fizyczne','bajo','niski'),
('Características Físicas','Cechy fizyczne','de estatura media','średniego wzrostu'),
('Características Físicas','Cechy fizyczne','gordo','gruby'),
('Características Físicas','Cechy fizyczne','con sobrepeso','z nadwagą'),
('Características Físicas','Cechy fizyczne','delgado','szczupły'),
('Características Físicas','Cechy fizyczne','flaco','chudy'),
('Características Físicas','Cechy fizyczne','fuerte','silny'),
('Características Físicas','Cechy fizyczne','débil','słaby'),
('Características Físicas','Cechy fizyczne','musculoso','umięśniony'),
('Características Físicas','Cechy fizyczne','guapo','przystojny / ładny'),
('Características Físicas','Cechy fizyczne','feo','brzydki'),
('Características Físicas','Cechy fizyczne','hermoso','piękny'),
('Características Físicas','Cechy fizyczne','atractivo','atrakcyjny'),
('Características Físicas','Cechy fizyczne','joven','młody'),
('Características Físicas','Cechy fizyczne','viejo','stary'),
('Características Físicas','Cechy fizyczne','mayor','starszy'),
('Características Físicas','Cechy fizyczne','de mediana edad','w średnim wieku'),
('Características Físicas','Cechy fizyczne','el pelo','włosy'),
('Características Físicas','Cechy fizyczne','rubio','blond'),
('Características Físicas','Cechy fizyczne','moreno','brunet'),
('Características Físicas','Cechy fizyczne','castaño','szatyn'),
('Características Físicas','Cechy fizyczne','pelirrojo','rudy'),
('Características Físicas','Cechy fizyczne','calvo','łysy'),
('Características Físicas','Cechy fizyczne','el pelo largo','długie włosy'),
('Características Físicas','Cechy fizyczne','el pelo corto','krótkie włosy'),
('Características Físicas','Cechy fizyczne','el pelo liso','proste włosy'),
('Características Físicas','Cechy fizyczne','el pelo rizado','kręcone włosy'),
('Características Físicas','Cechy fizyczne','el pelo ondulado','falowane włosy'),
('Características Físicas','Cechy fizyczne','la piel','skóra'),
('Características Físicas','Cechy fizyczne','claro','jasny'),
('Características Físicas','Cechy fizyczne','oscuro','ciemny'),
('Características Físicas','Cechy fizyczne','pálido','blady'),
('Características Físicas','Cechy fizyczne','bronceado','opalony'),
('Características Físicas','Cechy fizyczne','los ojos','oczy'),
('Características Físicas','Cechy fizyczne','los ojos azules','niebieskie oczy'),
('Características Físicas','Cechy fizyczne','los ojos verdes','zielone oczy'),
('Características Físicas','Cechy fizyczne','los ojos marrones','brązowe oczy'),
('Características Físicas','Cechy fizyczne','las gafas','okulary'),
('Características Físicas','Cechy fizyczne','la barba','broda'),
('Características Físicas','Cechy fizyczne','el bigote','wąsy'),
('Características Físicas','Cechy fizyczne','la peca','pieg'),
('Características Físicas','Cechy fizyczne','el lunar','pieprzyk'),
('Características Físicas','Cechy fizyczne','la arruga','zmarszczka'),
('Características Físicas','Cechy fizyczne','la cicatriz','blizna'),
('Características Físicas','Cechy fizyczne','el tatuaje','tatuaż'),
('Características Físicas','Cechy fizyczne','la sonrisa','uśmiech'),
('Características Físicas','Cechy fizyczne','el rostro / la cara','twarz'),
('El Cabello','Włosy (Rodzaje)','el cabello / el pelo','włosy'),
('El Cabello','Włosy (Rodzaje)','el peinado','fryzura'),
('El Cabello','Włosy (Rodzaje)','el corte de pelo','strzyżenie / fryzura'),
('El Cabello','Włosy (Rodzaje)','rubio','blond'),
('El Cabello','Włosy (Rodzaje)','moreno','ciemnowłosy / brunet'),
('El Cabello','Włosy (Rodzaje)','castaño','szatyn'),
('El Cabello','Włosy (Rodzaje)','pelirrojo','rudy'),
('El Cabello','Włosy (Rodzaje)','teñido','farbowany'),
('El Cabello','Włosy (Rodzaje)','las mechas','pasemka'),
('El Cabello','Włosy (Rodzaje)','liso','prosty (o włosach)'),
('El Cabello','Włosy (Rodzaje)','rizado','kręcony'),
('El Cabello','Włosy (Rodzaje)','ondulado','falowany'),
('El Cabello','Włosy (Rodzaje)','corto','krótki'),
('El Cabello','Włosy (Rodzaje)','largo','długi'),
('El Cabello','Włosy (Rodzaje)','suelto','rozpuszczony'),
('El Cabello','Włosy (Rodzaje)','recogido','związany / upięty'),
('El Cabello','Włosy (Rodzaje)','la trenza','warkocz'),
('El Cabello','Włosy (Rodzaje)','la coleta','kucyk'),
('El Cabello','Włosy (Rodzaje)','el moño','kok'),
('El Cabello','Włosy (Rodzaje)','el flequillo','grzywka'),
('El Cabello','Włosy (Rodzaje)','la raya','przedziałek'),
('El Cabello','Włosy (Rodzaje)','la calva','łysina'),
('El Cabello','Włosy (Rodzaje)','calvo','łysy'),
('El Cabello','Włosy (Rodzaje)','la caspa','łupież'),
('El Cabello','Włosy (Rodzaje)','el champú','szampon'),
('El Cabello','Włosy (Rodzaje)','el acondicionador','odżywka do włosów'),
('El Cabello','Włosy (Rodzaje)','el secador','suszarka do włosów'),
('El Cabello','Włosy (Rodzaje)','la plancha de pelo','prostownica'),
('El Cabello','Włosy (Rodzaje)','el peine','grzebień'),
('El Cabello','Włosy (Rodzaje)','el cepillo','szczotka'),
('El Cabello','Włosy (Rodzaje)','peinar','czesać (grzebieniem)'),
('El Cabello','Włosy (Rodzaje)','cepillar','szczotkować'),
('El Cabello','Włosy (Rodzaje)','cortar','obcinać'),
('El Cabello','Włosy (Rodzaje)','teñir','farbować'),
('El Cabello','Włosy (Rodzaje)','lavar','myć'),
('El Cabello','Włosy (Rodzaje)','la peluquería','salon fryzjerski'),
('El Cabello','Włosy (Rodzaje)','el peluquero / la peluquera','fryzjer / fryzjerka'),
('El Cabello','Włosy (Rodzaje)','la laca','lakier do włosów'),
('El Cabello','Włosy (Rodzaje)','el gel / la gomina','żel do włosów'),
('El Cabello','Włosy (Rodzaje)','la mascarilla capilar','maska do włosów'),
('El Cabello','Włosy (Rodzaje)','las tijeras','nożyczki'),
('El Cabello','Włosy (Rodzaje)','la peluca','peruka'),
('El Cabello','Włosy (Rodzaje)','las extensiones','doczepiane włosy'),
('El Cabello','Włosy (Rodzaje)','el rizo','lok'),
('El Cabello','Włosy (Rodzaje)','la raíz','cebulka / odrost'),
('El Cabello','Włosy (Rodzaje)','la punta','końcówka (włosa)'),
('El Cabello','Włosy (Rodzaje)','el volumen','objętość'),
('El Cabello','Włosy (Rodzaje)','brillante','lśniący'),
('El Cabello','Włosy (Rodzaje)','seco','suchy'),
('El Cabello','Włosy (Rodzaje)','graso','przetłuszczający się / tłusty'),
('Ropa de Invierno','Ubrania zimowe','el invierno','zima'),
('Ropa de Invierno','Ubrania zimowe','el frío','zimno'),
('Ropa de Invierno','Ubrania zimowe','el abrigo','płaszcz'),
('Ropa de Invierno','Ubrania zimowe','la chaqueta','kurtka'),
('Ropa de Invierno','Ubrania zimowe','el anorak','kurtka zimowa (anorak)'),
('Ropa de Invierno','Ubrania zimowe','el plumífero','kurtka puchowa'),
('Ropa de Invierno','Ubrania zimowe','el jersey','sweter (przez głowę)'),
('Ropa de Invierno','Ubrania zimowe','el suéter','sweter'),
('Ropa de Invierno','Ubrania zimowe','la sudadera','bluza'),
('Ropa de Invierno','Ubrania zimowe','el cárdigan','rozpinany sweter'),
('Ropa de Invierno','Ubrania zimowe','el forro polar','polar (ubranie)'),
('Ropa de Invierno','Ubrania zimowe','el chaleco','kamizelka'),
('Ropa de Invierno','Ubrania zimowe','los pantalones de pana','spodnie sztruksowe'),
('Ropa de Invierno','Ubrania zimowe','la bufanda','szalik'),
('Ropa de Invierno','Ubrania zimowe','el gorro','czapka (zimowa)'),
('Ropa de Invierno','Ubrania zimowe','los guantes','rękawiczki'),
('Ropa de Invierno','Ubrania zimowe','las manoplas','rękawice z jednym palcem'),
('Ropa de Invierno','Ubrania zimowe','las orejeras','nauszniki'),
('Ropa de Invierno','Ubrania zimowe','los calcetines gruesos','grube skarpety'),
('Ropa de Invierno','Ubrania zimowe','los leotardos','rajstopy (grube)'),
('Ropa de Invierno','Ubrania zimowe','las mallas','getry / legginsy'),
('Ropa de Invierno','Ubrania zimowe','las botas','kozaki / buty zimowe'),
('Ropa de Invierno','Ubrania zimowe','las botas de nieve','śniegowce'),
('Ropa de Invierno','Ubrania zimowe','el cuello alto','golf (kołnierz)'),
('Ropa de Invierno','Ubrania zimowe','abrigarse','ciepło się ubierać'),
('Ropa de Invierno','Ubrania zimowe','de lana','z wełny'),
('Ropa de Invierno','Ubrania zimowe','térmico','termiczny'),
('Ropa de Invierno','Ubrania zimowe','la ropa térmica','odzież termiczna'),
('Ropa de Invierno','Ubrania zimowe','la manta','koc'),
('Ropa de Invierno','Ubrania zimowe','el pasamontañas','kominiarka'),
('Ropa de Invierno','Ubrania zimowe','el impermeable','płaszcz przeciwdeszczowy'),
('Ropa de Invierno','Ubrania zimowe','la gabardina','trencz'),
('Ropa de Invierno','Ubrania zimowe','la capa','peleryna'),
('Ropa de Invierno','Ubrania zimowe','esquiar','jeździć na nartach'),
('Ropa de Invierno','Ubrania zimowe','la ropa de esquí','odzież narciarska'),
('Ropa de Invierno','Ubrania zimowe','de punto','z dzianiny / robiony na drutach'),
('Ropa de Invierno','Ubrania zimowe','la manga larga','długi rękaw'),
('Ropa de Invierno','Ubrania zimowe','la capucha','kaptur'),
('Ropa de Invierno','Ubrania zimowe','abotonar','zapinać na guziki'),
('Ropa de Invierno','Ubrania zimowe','la cremallera','zamek błyskawiczny'),
('Ropa de Invierno','Ubrania zimowe','el bolsillo','kieszeń'),
('Ropa de Invierno','Ubrania zimowe','grueso','gruby (materiał)'),
('Ropa de Invierno','Ubrania zimowe','calentito','cieplutki'),
('Ropa de Invierno','Ubrania zimowe','la nieve','śnieg'),
('Ropa de Invierno','Ubrania zimowe','proteger','chronić'),
('Ropa de Invierno','Ubrania zimowe','el polar','polar (materiał)'),
('Ropa de Invierno','Ubrania zimowe','el copo de nieve','płatek śniegu'),
('Ropa de Invierno','Ubrania zimowe','abrigado','ciepło ubrany'),
('Ropa de Invierno','Ubrania zimowe','congelado','zmarznięty'),
('Ropa de Invierno','Ubrania zimowe','tiritar','trząść się (z zimna)'),
('Ropa de Verano','Ubrania letnie','el verano','lato'),
('Ropa de Verano','Ubrania letnie','el calor','upał / gorąco'),
('Ropa de Verano','Ubrania letnie','la camiseta','koszulka / t-shirt'),
('Ropa de Verano','Ubrania letnie','el tirante','ramiączko'),
('Ropa de Verano','Ubrania letnie','la camiseta de tirantes','koszulka na ramiączkach / top'),
('Ropa de Verano','Ubrania letnie','el top','krótki top'),
('Ropa de Verano','Ubrania letnie','el pantalón corto','krótkie spodenki'),
('Ropa de Verano','Ubrania letnie','las bermudas','bermudy'),
('Ropa de Verano','Ubrania letnie','el vestido','sukienka'),
('Ropa de Verano','Ubrania letnie','el vestido de verano','letnia sukienka'),
('Ropa de Verano','Ubrania letnie','la falda','spódnica'),
('Ropa de Verano','Ubrania letnie','el bañador','strój kąpielowy jednoczęściowy / kąpielówki'),
('Ropa de Verano','Ubrania letnie','el bikini','bikini'),
('Ropa de Verano','Ubrania letnie','las sandalias','sandały'),
('Ropa de Verano','Ubrania letnie','las chanclas','klapki / japonki'),
('Ropa de Verano','Ubrania letnie','las alpargatas','espadryle'),
('Ropa de Verano','Ubrania letnie','el sombrero','kapelusz'),
('Ropa de Verano','Ubrania letnie','la gorra','czapka z daszkiem'),
('Ropa de Verano','Ubrania letnie','las gafas de sol','okulary przeciwsłoneczne'),
('Ropa de Verano','Ubrania letnie','de lino','lniany'),
('Ropa de Verano','Ubrania letnie','el lino','len'),
('Ropa de Verano','Ubrania letnie','el algodón','bawełna'),
('Ropa de Verano','Ubrania letnie','la manga corta','krótki rękaw'),
('Ropa de Verano','Ubrania letnie','sin mangas','bez rękawów'),
('Ropa de Verano','Ubrania letnie','fresco','chłodny / przewiewny'),
('Ropa de Verano','Ubrania letnie','ligero','lekki'),
('Ropa de Verano','Ubrania letnie','sudar','pocić się'),
('Ropa de Verano','Ubrania letnie','la piscina','basen'),
('Ropa de Verano','Ubrania letnie','la playa','plaża'),
('Ropa de Verano','Ubrania letnie','el pareo','pareo / chusta plażowa'),
('Ropa de Verano','Ubrania letnie','el caftán','kaftan / tunika'),
('Ropa de Verano','Ubrania letnie','la blusa','bluzka'),
('Ropa de Verano','Ubrania letnie','la camisa de manga corta','koszula z krótkim rękawem'),
('Ropa de Verano','Ubrania letnie','los zapatos abiertos','odkryte buty'),
('Ropa de Verano','Ubrania letnie','el capazo','torba plażowa / koszyk'),
('Ropa de Verano','Ubrania letnie','la toalla','ręcznik (plażowy)'),
('Ropa de Verano','Ubrania letnie','el protector solar','krem z filtrem'),
('Ropa de Verano','Ubrania letnie','broncearse','opalać się'),
('Ropa de Verano','Ubrania letnie','nadar','pływać'),
('Ropa de Verano','Ubrania letnie','el traje de baño','strój kąpielowy'),
('Ropa de Verano','Ubrania letnie','la ropa ligera','lekka odzież'),
('Ropa de Verano','Ubrania letnie','descalzo','boso'),
('Ropa de Verano','Ubrania letnie','holgado','luźny (o ubraniu)'),
('Ropa de Verano','Ubrania letnie','ajustado','obcisły / dopasowany'),
('Ropa de Verano','Ubrania letnie','floreado','w kwiaty (wzór)'),
('Ropa de Verano','Ubrania letnie','el estampado','nadruk / wzór'),
('Ropa de Verano','Ubrania letnie','transpirable','oddychający (materiał)'),
('Ropa de Verano','Ubrania letnie','el abanico','wachlarz'),
('Ropa de Verano','Ubrania letnie','refrescar','chłodzić'),
('Ropa de Verano','Ubrania letnie','descubierto','odkryty'),
('Calzado','Obuwie','el calzado','obuwie'),
('Calzado','Obuwie','el zapato','but'),
('Calzado','Obuwie','los zapatos','buty'),
('Calzado','Obuwie','las zapatillas','trampki / tenisówki'),
('Calzado','Obuwie','las zapatillas de deporte','buty sportowe'),
('Calzado','Obuwie','los tenis','adidasy / buty sportowe'),
('Calzado','Obuwie','las botas','kozaki / buty wysokie'),
('Calzado','Obuwie','los botines','botki'),
('Calzado','Obuwie','las sandalias','sandały'),
('Calzado','Obuwie','las chanclas','klapki / japonki'),
('Calzado','Obuwie','los tacones','obcasy'),
('Calzado','Obuwie','los zapatos de tacón','buty na obcasie'),
('Calzado','Obuwie','los zapatos planos','płaskie buty'),
('Calzado','Obuwie','las bailarinas','baleriny'),
('Calzado','Obuwie','los mocasines','mokasyny'),
('Calzado','Obuwie','los zapatos de cordones','buty sznurowane'),
('Calzado','Obuwie','los zapatos de piel','buty skórzane'),
('Calzado','Obuwie','las alpargatas','espadryle'),
('Calzado','Obuwie','las pantuflas','kapcie'),
('Calzado','Obuwie','las botas de agua','kalosze'),
('Calzado','Obuwie','las botas de nieve','śniegowce'),
('Calzado','Obuwie','el cordón','sznurówka'),
('Calzado','Obuwie','atar','wiązać'),
('Calzado','Obuwie','desatar','rozwiązywać'),
('Calzado','Obuwie','la suela','podeszwa'),
('Calzado','Obuwie','el tacón','obcas'),
('Calzado','Obuwie','la punta','czubek (buta)'),
('Calzado','Obuwie','el empeine','podbicie'),
('Calzado','Obuwie','la plantilla','wkładka (do butów)'),
('Calzado','Obuwie','el betún','pasta do butów'),
('Calzado','Obuwie','limpiar los zapatos','czyścić buty / pastować'),
('Calzado','Obuwie','el zapatero','szewc'),
('Calzado','Obuwie','la zapatería','sklep obuwniczy'),
('Calzado','Obuwie','probarse','przymierzać'),
('Calzado','Obuwie','la talla','rozmiar (odzieży / butów ogólnie)'),
('Calzado','Obuwie','el número','rozmiar (buta)'),
('Calzado','Obuwie','calzar','nosić buty w rozmiarze...'),
('Calzado','Obuwie','apretar','uwierać / cisnąć'),
('Calzado','Obuwie','holgado','luźny'),
('Calzado','Obuwie','cómodo','wygodny'),
('Calzado','Obuwie','incómodo','niewygodny'),
('Calzado','Obuwie','de cuero','ze skóry'),
('Calzado','Obuwie','de ante','z zamszu'),
('Calzado','Obuwie','de tela','z materiału'),
('Calzado','Obuwie','caminar','chodzić'),
('Calzado','Obuwie','el roce','otarcie'),
('Calzado','Obuwie','la ampolla','pęcherz / bąbel (na skórze)'),
('Calzado','Obuwie','el calcetín','skarpetka'),
('Calzado','Obuwie','calzarse','wkładać buty'),
('Calzado','Obuwie','descalzarse','zdejmować buty'),
('Accesorios','Akcesoria','el accesorio','akcesorium / dodatek'),
('Accesorios','Akcesoria','el complemento','dodatek (do ubioru)'),
('Accesorios','Akcesoria','el cinturón','pasek'),
('Accesorios','Akcesoria','la corbata','krawat'),
('Accesorios','Akcesoria','la pajarita','mucha (do garnituru)'),
('Accesorios','Akcesoria','el pañuelo','chustka / apaszka'),
('Accesorios','Akcesoria','la bufanda','szalik'),
('Accesorios','Akcesoria','el guante','rękawiczka'),
('Accesorios','Akcesoria','el gorro','czapka'),
('Accesorios','Akcesoria','el sombrero','kapelusz'),
('Accesorios','Akcesoria','la gorra','czapka z daszkiem'),
('Accesorios','Akcesoria','el bolso','torebka'),
('Accesorios','Akcesoria','la cartera','portfel / teczka'),
('Accesorios','Akcesoria','el monedero','portmonetka'),
('Accesorios','Akcesoria','la mochila','plecak'),
('Accesorios','Akcesoria','el maletín','aktówka / walizeczka'),
('Accesorios','Akcesoria','la maleta','walizka'),
('Accesorios','Akcesoria','el paraguas','parasol'),
('Accesorios','Akcesoria','las gafas','okulary (korekcyjne)'),
('Accesorios','Akcesoria','las gafas de sol','okulary przeciwsłoneczne'),
('Accesorios','Akcesoria','el reloj','zegarek (na rękę)'),
('Accesorios','Akcesoria','el abanico','wachlarz'),
('Accesorios','Akcesoria','la joya','klejnot / biżuteria'),
('Accesorios','Akcesoria','el anillo','pierścionek'),
('Accesorios','Akcesoria','el collar','naszyjnik'),
('Accesorios','Akcesoria','la pulsera','bransoletka'),
('Accesorios','Akcesoria','el pendiente','kolczyk'),
('Accesorios','Akcesoria','el broche','broszka'),
('Accesorios','Akcesoria','el pasador','spinka (do włosów)'),
('Accesorios','Akcesoria','la diadema','opaska na włosy'),
('Accesorios','Akcesoria','la goma de pelo','gumka do włosów'),
('Accesorios','Akcesoria','de cuero','ze skóry'),
('Accesorios','Akcesoria','de seda','z jedwabiu'),
('Accesorios','Akcesoria','de oro','ze złota'),
('Accesorios','Akcesoria','de plata','ze srebra'),
('Accesorios','Akcesoria','de plástico','z plastiku'),
('Accesorios','Akcesoria','llevar','nosić'),
('Accesorios','Akcesoria','ponerse','zakładać (na siebie)'),
('Accesorios','Akcesoria','quitarse','zdejmować'),
('Accesorios','Akcesoria','combinar','pasować (o ubraniach) / łączyć'),
('Accesorios','Akcesoria','de moda','modny'),
('Accesorios','Akcesoria','pasado de moda','niemodny'),
('Accesorios','Akcesoria','elegante','elegancki'),
('Accesorios','Akcesoria','casual','nieformalny / casualowy'),
('Accesorios','Akcesoria','el adorno','ozdoba'),
('Accesorios','Akcesoria','el detalle','detal / szczegół'),
('Accesorios','Akcesoria','la hebilla','klamra (od paska)'),
('Accesorios','Akcesoria','el colgante','wisiorek'),
('Accesorios','Akcesoria','adornar','ozdabiać'),
('Accesorios','Akcesoria','regalar','dawać w prezencie'),
('Joyería','Biżuteria','la joyería','biżuteria / jubiler (sklep)'),
('Joyería','Biżuteria','el joyero','szkatułka na biżuterię / jubiler (zawód)'),
('Joyería','Biżuteria','la joya','klejnot / biżuteria'),
('Joyería','Biżuteria','el anillo','pierścionek'),
('Joyería','Biżuteria','la alianza','obrączka'),
('Joyería','Biżuteria','el collar','naszyjnik'),
('Joyería','Biżuteria','la pulsera','bransoletka'),
('Joyería','Biżuteria','el pendiente','kolczyk'),
('Joyería','Biżuteria','el aro','kolczyk w kształcie koła'),
('Joyería','Biżuteria','el broche','broszka'),
('Joyería','Biżuteria','el colgante','wisiorek'),
('Joyería','Biżuteria','la cadena','łańcuszek'),
('Joyería','Biżuteria','el diamante','diament'),
('Joyería','Biżuteria','la perla','perła'),
('Joyería','Biżuteria','el rubí','rubin'),
('Joyería','Biżuteria','la esmeralda','szmaragd'),
('Joyería','Biżuteria','el zafiro','szafir'),
('Joyería','Biżuteria','el cristal','kryształ'),
('Joyería','Biżuteria','el oro','złoto'),
('Joyería','Biżuteria','la plata','srebro'),
('Joyería','Biżuteria','el platino','platyna'),
('Joyería','Biżuteria','el cobre','miedź'),
('Joyería','Biżuteria','el acero inoxidable','stal nierdzewna'),
('Joyería','Biżuteria','la piedra preciosa','kamień szlachetny'),
('Joyería','Biżuteria','el reloj de pulsera','zegarek na rękę'),
('Joyería','Biżuteria','la corona','korona'),
('Joyería','Biżuteria','la tiara','tiara'),
('Joyería','Biżuteria','el camafeo','kamea'),
('Joyería','Biżuteria','el cierre','zapięcie'),
('Joyería','Biżuteria','el esmalte','emalia'),
('Joyería','Biżuteria','tallar','szlifować'),
('Joyería','Biżuteria','brillar','błyszczeć'),
('Joyería','Biżuteria','el brillo','blask'),
('Joyería','Biżuteria','valioso','wartościowy'),
('Joyería','Biżuteria','caro','drogi'),
('Joyería','Biżuteria','barato','tani'),
('Joyería','Biżuteria','antiguo','antyczny / zabytkowy'),
('Joyería','Biżuteria','moderno','nowoczesny'),
('Joyería','Biżuteria','heredar','odziedziczyć'),
('Joyería','Biżuteria','la herencia','spadek / pamiątka'),
('Joyería','Biżuteria','regalar','dawać w prezencie'),
('Joyería','Biżuteria','el quilate','karat'),
('Joyería','Biżuteria','auténtico','autentyczny / prawdziwy'),
('Joyería','Biżuteria','falso','sztuczny / fałszywy'),
('Joyería','Biżuteria','la bisutería','sztuczna biżuteria'),
('Joyería','Biżuteria','el diseñador','projektant'),
('Joyería','Biżuteria','el engaste','oprawa (kamienia)'),
('Joyería','Biżuteria','la gema','klejnot / gema'),
('Joyería','Biżuteria','el amuleto','amulet'),
('Joyería','Biżuteria','el talismán','talizman');
