insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Telas y Tejidos','Tkaniny i materiały','la tela','tkanina / materiał'),
('Telas y Tejidos','Tkaniny i materiały','el tejido','tkactwo / materiał'),
('Telas y Tejidos','Tkaniny i materiały','el algodón','bawełna'),
('Telas y Tejidos','Tkaniny i materiały','la lana','wełna'),
('Telas y Tejidos','Tkaniny i materiały','la seda','jedwab'),
('Telas y Tejidos','Tkaniny i materiały','el lino','len'),
('Telas y Tejidos','Tkaniny i materiały','el poliéster','poliester'),
('Telas y Tejidos','Tkaniny i materiały','el nailon','nylon'),
('Telas y Tejidos','Tkaniny i materiały','el terciopelo','aksamit'),
('Telas y Tejidos','Tkaniny i materiały','la pana','sztruks'),
('Telas y Tejidos','Tkaniny i materiały','el cuero','skóra (materiał)'),
('Telas y Tejidos','Tkaniny i materiały','el ante','zamsz'),
('Telas y Tejidos','Tkaniny i materiały','la mezclilla / el vaquero','jeans / dżins'),
('Telas y Tejidos','Tkaniny i materiały','el encaje','koronka'),
('Telas y Tejidos','Tkaniny i materiały','el tul','tiul'),
('Telas y Tejidos','Tkaniny i materiały','el satén','satyna'),
('Telas y Tejidos','Tkaniny i materiały','la gasa','gaza / szyfon'),
('Telas y Tejidos','Tkaniny i materiały','la lycra','lycra'),
('Telas y Tejidos','Tkaniny i materiały','el fieltro','filc'),
('Telas y Tejidos','Tkaniny i materiały','la franela','flanela'),
('Telas y Tejidos','Tkaniny i materiały','el cachemir','kaszmir'),
('Telas y Tejidos','Tkaniny i materiały','el acrílico','akryl'),
('Telas y Tejidos','Tkaniny i materiały','la viscosa','wiskoza'),
('Telas y Tejidos','Tkaniny i materiały','el rayón','sztuczny jedwab / wiskoza'),
('Telas y Tejidos','Tkaniny i materiały','tejer','tkać / robić na drutach'),
('Telas y Tejidos','Tkaniny i materiały','coser','szyć'),
('Telas y Tejidos','Tkaniny i materiały','bordar','haftować'),
('Telas y Tejidos','Tkaniny i materiały','el hilo','nić'),
('Telas y Tejidos','Tkaniny i materiały','la aguja','igła'),
('Telas y Tejidos','Tkaniny i materiały','el patrón','wzór (krawiecki)'),
('Telas y Tejidos','Tkaniny i materiały','suave','miękki / gładki'),
('Telas y Tejidos','Tkaniny i materiały','áspero','szorstki'),
('Telas y Tejidos','Tkaniny i materiały','grueso','gruby (o materiale)'),
('Telas y Tejidos','Tkaniny i materiały','fino','cienki / delikatny'),
('Telas y Tejidos','Tkaniny i materiały','transparente','przezroczysty'),
('Telas y Tejidos','Tkaniny i materiały','elástico','elastyczny'),
('Telas y Tejidos','Tkaniny i materiały','resistente','wytrzymały'),
('Telas y Tejidos','Tkaniny i materiały','el tinte','barwnik'),
('Telas y Tejidos','Tkaniny i materiały','teñir','farbować (materiał)'),
('Telas y Tejidos','Tkaniny i materiały','estampado','wzorzysty / z nadrukiem'),
('Telas y Tejidos','Tkaniny i materiały','liso','gładki / jednolity (bez wzoru)'),
('Telas y Tejidos','Tkaniny i materiały','a rayas','w paski'),
('Telas y Tejidos','Tkaniny i materiały','a cuadros','w kratkę'),
('Telas y Tejidos','Tkaniny i materiały','de lunares','w grochy'),
('Telas y Tejidos','Tkaniny i materiały','el metro','metr (bieżący)'),
('Telas y Tejidos','Tkaniny i materiały','la textura','tekstura / faktura'),
('Telas y Tejidos','Tkaniny i materiały','la fibra','włókno'),
('Telas y Tejidos','Tkaniny i materiały','la fibra sintética','włókno syntetyczne'),
('Telas y Tejidos','Tkaniny i materiały','la costura','szew / szycie'),
('Telas y Tejidos','Tkaniny i materiały','el retal','ścinka / resztka materiału'),
('Partes de la Casa','Części domu','la casa','dom'),
('Partes de la Casa','Części domu','el piso','mieszkanie / piętro'),
('Partes de la Casa','Części domu','el apartamento','apartament'),
('Partes de la Casa','Części domu','el edificio','budynek'),
('Partes de la Casa','Części domu','la fachada','fasada / elewacja'),
('Partes de la Casa','Części domu','el tejado','dach'),
('Partes de la Casa','Części domu','la chimenea','komin / kominek'),
('Partes de la Casa','Części domu','la pared','ściana'),
('Partes de la Casa','Części domu','el suelo','podłoga / ziemia'),
('Partes de la Casa','Części domu','el techo','sufit'),
('Partes de la Casa','Części domu','la puerta','drzwi'),
('Partes de la Casa','Części domu','la ventana','okno'),
('Partes de la Casa','Części domu','el cristal','szyba'),
('Partes de la Casa','Części domu','la persiana','roleta / żaluzja'),
('Partes de la Casa','Części domu','el balcón','balkon'),
('Partes de la Casa','Części domu','la terraza','taras'),
('Partes de la Casa','Części domu','el pasillo','korytarz'),
('Partes de la Casa','Części domu','el recibidor','przedpokój'),
('Partes de la Casa','Części domu','el salón','salon'),
('Partes de la Casa','Części domu','el comedor','jadalnia'),
('Partes de la Casa','Części domu','la cocina','kuchnia'),
('Partes de la Casa','Części domu','el dormitorio','sypialnia'),
('Partes de la Casa','Części domu','el baño','łazienka'),
('Partes de la Casa','Części domu','el aseo','toaleta (pomieszczenie)'),
('Partes de la Casa','Części domu','el sótano','piwnica'),
('Partes de la Casa','Części domu','el ático / la buhardilla','strych / poddasze'),
('Partes de la Casa','Części domu','el garaje','garaż'),
('Partes de la Casa','Części domu','el jardín','ogród'),
('Partes de la Casa','Części domu','el patio','dziedziniec / podwórko'),
('Partes de la Casa','Części domu','la escalera','schody'),
('Partes de la Casa','Części domu','el escalón','stopień'),
('Partes de la Casa','Części domu','el ascensor','winda'),
('Partes de la Casa','Części domu','el timbre','dzwonek'),
('Partes de la Casa','Części domu','la cerradura','zamek (w drzwiach)'),
('Partes de la Casa','Części domu','la llave','klucz'),
('Partes de la Casa','Części domu','la habitación','pokój'),
('Partes de la Casa','Części domu','el cuarto','pokój / pomieszczenie'),
('Partes de la Casa','Części domu','la despensa','spiżarnia'),
('Partes de la Casa','Części domu','el lavadero','pralnia (w domu)'),
('Partes de la Casa','Części domu','el trastero','schowek / graciarnia'),
('Partes de la Casa','Części domu','la valla','ogrodzenie / płot'),
('Partes de la Casa','Części domu','el porche','ganek'),
('Partes de la Casa','Części domu','la entrada','wejście'),
('Partes de la Casa','Części domu','la salida','wyjście'),
('Partes de la Casa','Części domu','la planta baja','parter'),
('Partes de la Casa','Części domu','el primer piso','pierwsze piętro'),
('Partes de la Casa','Części domu','la baldosa','płytka podłogowa / kafel'),
('Partes de la Casa','Części domu','el ladrillo','cegła'),
('Partes de la Casa','Części domu','el cimiento','fundament'),
('Partes de la Casa','Części domu','la viga','belka'),
('El Jardín','Ogród','el jardín','ogród'),
('El Jardín','Ogród','el césped','trawnik'),
('El Jardín','Ogród','la hierba','trawa'),
('El Jardín','Ogród','la planta','roślina'),
('El Jardín','Ogród','la flor','kwiat'),
('El Jardín','Ogród','la rosa','róża'),
('El Jardín','Ogród','el tulipán','tulipan'),
('El Jardín','Ogród','el clavel','goździk (kwiat)'),
('El Jardín','Ogród','la margarita','stokrotka'),
('El Jardín','Ogród','el arbusto','krzew'),
('El Jardín','Ogród','el árbol','drzewo'),
('El Jardín','Ogród','la rama','gałąź'),
('El Jardín','Ogród','la hoja','liść'),
('El Jardín','Ogród','la raíz','korzeń'),
('El Jardín','Ogród','la semilla','nasiono'),
('El Jardín','Ogród','la tierra','ziemia'),
('El Jardín','Ogród','el abono','nawóz'),
('El Jardín','Ogród','la maceta','doniczka'),
('El Jardín','Ogród','la regadera','konewka'),
('El Jardín','Ogród','la manguera','wąż ogrodowy'),
('El Jardín','Ogród','el cortacésped','kosiarka'),
('El Jardín','Ogród','las tijeras de podar','sekator'),
('El Jardín','Ogród','la pala','łopata'),
('El Jardín','Ogród','el rastrillo','grabie'),
('El Jardín','Ogród','la azada','motyka'),
('El Jardín','Ogród','la carretilla','taczka'),
('El Jardín','Ogród','el invernadero','szklarnia'),
('El Jardín','Ogród','el huerto','warzywniak / sad'),
('El Jardín','Ogród','la fuente','fontanna'),
('El Jardín','Ogród','el estanque','staw / oczko wodne'),
('El Jardín','Ogród','el camino','ścieżka'),
('El Jardín','Ogród','la valla','płot / ogrodzenie'),
('El Jardín','Ogród','el seto','żywopłot'),
('El Jardín','Ogród','la maleza / el abrojo','chwasty'),
('El Jardín','Ogród','regar','podlewać'),
('El Jardín','Ogród','plantar','sadzić'),
('El Jardín','Ogród','sembrar','siać'),
('El Jardín','Ogród','podar','przycinać (rośliny)'),
('El Jardín','Ogród','cavar','kopać'),
('El Jardín','Ogród','cortar el césped','kosić trawnik'),
('El Jardín','Ogród','crecer','rosnąć'),
('El Jardín','Ogród','florecer','kwitnąć'),
('El Jardín','Ogród','marchitarse','więdnąć'),
('El Jardín','Ogród','arrancar','wyrywać'),
('El Jardín','Ogród','cultivar','uprawiać'),
('El Jardín','Ogród','el jardinero','ogrodnik'),
('El Jardín','Ogród','la primavera','wiosna'),
('El Jardín','Ogród','el capullo','pąk'),
('El Jardín','Ogród','el polen','pyłek'),
('El Jardín','Ogród','la plaga','plaga / szkodniki'),
('El Baño','Łazienka','el baño','łazienka (z wanną/prysznicem)'),
('El Baño','Łazienka','el cuarto de baño','łazienka'),
('El Baño','Łazienka','el aseo','ubikacja (często bez prysznica)'),
('El Baño','Łazienka','la ducha','prysznic'),
('El Baño','Łazienka','la bañera','wanna'),
('El Baño','Łazienka','el lavabo','umywalka'),
('El Baño','Łazienka','el váter / el inodoro','muszla klozetowa / toaleta'),
('El Baño','Łazienka','el bidé','bidet'),
('El Baño','Łazienka','el grifo','kran'),
('El Baño','Łazienka','el desagüe','odpływ'),
('El Baño','Łazienka','el espejo','lustro'),
('El Baño','Łazienka','el azulejo','kafelek / glazura'),
('El Baño','Łazienka','la toalla','ręcznik'),
('El Baño','Łazienka','el albornoz','szlafrok'),
('El Baño','Łazienka','la alfombrilla','dywanik łazienkowy'),
('El Baño','Łazienka','la cortina de ducha','zasłona prysznicowa'),
('El Baño','Łazienka','la mampara','kabina prysznicowa / ścianka'),
('El Baño','Łazienka','el jabón','mydło'),
('El Baño','Łazienka','el champú','szampon'),
('El Baño','Łazienka','la esponja','gąbka'),
('El Baño','Łazienka','el papel higiénico','papier toaletowy'),
('El Baño','Łazienka','el cepillo de dientes','szczoteczka do zębów'),
('El Baño','Łazienka','la pasta de dientes','pasta do zębów'),
('El Baño','Łazienka','el enjuague bucal','płyn do płukania ust'),
('El Baño','Łazienka','el hilo dental','nić dentystyczna'),
('El Baño','Łazienka','el peine','grzebień'),
('El Baño','Łazienka','el cepillo','szczotka (np. do włosów)'),
('El Baño','Łazienka','el secador de pelo','suszarka do włosów'),
('El Baño','Łazienka','la cuchilla de afeitar','maszynka do golenia'),
('El Baño','Łazienka','la espuma de afeitar','pianka do golenia'),
('El Baño','Łazienka','la loción','balsam'),
('El Baño','Łazienka','el desodorante','dezodorant'),
('El Baño','Łazienka','la báscula','waga (łazienkowa)'),
('El Baño','Łazienka','el cubo de basura','kosz na śmieci'),
('El Baño','Łazienka','tirar de la cadena','spuszczać wodę (w toalecie)'),
('El Baño','Łazienka','lavarse','myć się'),
('El Baño','Łazienka','ducharse','brać prysznic'),
('El Baño','Łazienka','bañarse','kąpać się'),
('El Baño','Łazienka','secarse','wycierać się / suszyć się'),
('El Baño','Łazienka','peinarse','czesać się'),
('El Baño','Łazienka','afeitarse','golić się'),
('El Baño','Łazienka','maquillarse','malować się'),
('El Baño','Łazienka','desmaquillarse','zmywać makijaż'),
('El Baño','Łazienka','la higiene','higiena'),
('El Baño','Łazienka','limpio','czysty'),
('El Baño','Łazienka','sucio','brudny'),
('El Baño','Łazienka','el agua caliente','gorąca woda'),
('El Baño','Łazienka','el agua fría','zimna woda'),
('El Baño','Łazienka','el fontanero','hydraulik'),
('El Baño','Łazienka','el tapón','korek (do wanny/zlewu)'),
('El Dormitorio','Sypialnia','el dormitorio','sypialnia'),
('El Dormitorio','Sypialnia','la cama','łóżko'),
('El Dormitorio','Sypialnia','el colchón','materac'),
('El Dormitorio','Sypialnia','la almohada','poduszka (do spania)'),
('El Dormitorio','Sypialnia','la sábana','prześcieradło'),
('El Dormitorio','Sypialnia','la manta','koc'),
('El Dormitorio','Sypialnia','el edredón','kołdra'),
('El Dormitorio','Sypialnia','la funda','poszewka'),
('El Dormitorio','Sypialnia','el cabecero','wezgłowie'),
('El Dormitorio','Sypialnia','la mesita de noche','stolik nocny'),
('El Dormitorio','Sypialnia','la lámpara','lampa'),
('El Dormitorio','Sypialnia','el despertador','budzik'),
('El Dormitorio','Sypialnia','el armario','szafa'),
('El Dormitorio','Sypialnia','la percha','wieszak (do szafy)'),
('El Dormitorio','Sypialnia','la cómoda','komoda'),
('El Dormitorio','Sypialnia','el cajón','szuflada'),
('El Dormitorio','Sypialnia','el espejo','lustro'),
('El Dormitorio','Sypialnia','la alfombra','dywan'),
('El Dormitorio','Sypialnia','la cortina','zasłona'),
('El Dormitorio','Sypialnia','la persiana','roleta / żaluzja'),
('El Dormitorio','Sypialnia','la ventana','okno'),
('El Dormitorio','Sypialnia','la puerta','drzwi'),
('El Dormitorio','Sypialnia','el interruptor','włącznik'),
('El Dormitorio','Sypialnia','el enchufe','gniazdko'),
('El Dormitorio','Sypialnia','el techo','sufit'),
('El Dormitorio','Sypialnia','el suelo','podłoga'),
('El Dormitorio','Sypialnia','la pared','ściana'),
('El Dormitorio','Sypialnia','el pijama','piżama'),
('El Dormitorio','Sypialnia','el camisón','koszula nocna'),
('El Dormitorio','Sypialnia','las zapatillas de casa','kapcie'),
('El Dormitorio','Sypialnia','dormir','spać'),
('El Dormitorio','Sypialnia','despertar','budzić (się)'),
('El Dormitorio','Sypialnia','roncar','chrapać'),
('El Dormitorio','Sypialnia','soñar','śnić / marzyć'),
('El Dormitorio','Sypialnia','el sueño','sen'),
('El Dormitorio','Sypialnia','la pesadilla','koszmar'),
('El Dormitorio','Sypialnia','descansar','odpoczywać'),
('El Dormitorio','Sypialnia','hacer la cama','ścielić łóżko'),
('El Dormitorio','Sypialnia','deshacer la cama','rozkładać łóżko'),
('El Dormitorio','Sypialnia','la cuna','łóżeczko dziecięce'),
('El Dormitorio','Sypialnia','la litera','łóżko piętrowe'),
('El Dormitorio','Sypialnia','el cojín','poduszka (dekoracyjna)'),
('El Dormitorio','Sypialnia','la colcha','narzuta'),
('El Dormitorio','Sypialnia','el tocador','toaletka'),
('El Dormitorio','Sypialnia','el joyero','szkatułka na biżuterię'),
('El Dormitorio','Sypialnia','la ropa de cama','pościel'),
('El Dormitorio','Sypialnia','apagar la luz','gasić światło'),
('El Dormitorio','Sypialnia','encender la luz','zapalać światło'),
('El Dormitorio','Sypialnia','el insomnio','bezsenność'),
('El Dormitorio','Sypialnia','madrugar','wstawać wcześnie'),
('El Salón','Salon','el salón','salon'),
('El Salón','Salon','la sala de estar','pokój dzienny'),
('El Salón','Salon','el sofá','kanapa'),
('El Salón','Salon','el sillón','fotel'),
('El Salón','Salon','la butaca','fotel (wypoczynkowy/teatralny)'),
('El Salón','Salon','la mesa de centro','stolik kawowy'),
('El Salón','Salon','el mueble','mebel'),
('El Salón','Salon','la estantería','regał'),
('El Salón','Salon','la televisión / la tele','telewizor / telewizja'),
('El Salón','Salon','el mando a distancia','pilot'),
('El Salón','Salon','la alfombra','dywan'),
('El Salón','Salon','la cortina','zasłona'),
('El Salón','Salon','el cuadro','obraz'),
('El Salón','Salon','el póster','plakat'),
('El Salón','Salon','el jarrón','wazon'),
('El Salón','Salon','la planta','roślina'),
('El Salón','Salon','el cojín','poduszka (ozdobna)'),
('El Salón','Salon','la chimenea','kominek'),
('El Salón','Salon','la leña','drewno na opał'),
('El Salón','Salon','el fuego','ogień'),
('El Salón','Salon','la lámpara de pie','lampa stojąca'),
('El Salón','Salon','la lámpara de techo','lampa sufitowa'),
('El Salón','Salon','sentarse','siadać'),
('El Salón','Salon','descansar','odpoczywać'),
('El Salón','Salon','ver la tele','oglądać telewizję'),
('El Salón','Salon','charlar','rozmawiać / gadać'),
('El Salón','Salon','el reposabrazos','podłokietnik'),
('El Salón','Salon','el respaldo','oparcie'),
('El Salón','Salon','el puf / el puff','pufa'),
('El Salón','Salon','la vitrina','witryna (mebel)'),
('El Salón','Salon','el reloj de pared','zegar ścienny'),
('El Salón','Salon','la decoración','dekoracja'),
('El Salón','Salon','decorar','dekorować'),
('El Salón','Salon','el cenicero','popielniczka'),
('El Salón','Salon','el radiador','kaloryfer'),
('El Salón','Salon','el aire acondicionado','klimatyzacja'),
('El Salón','Salon','el ventilador','wentylator'),
('El Salón','Salon','la revista','magazyn / czasopismo'),
('El Salón','Salon','el periódico','gazeta'),
('El Salón','Salon','la mesa de comedor','stół w jadalni'),
('El Salón','Salon','la silla','krzesło'),
('El Salón','Salon','la manta','koc (na kanapę)'),
('El Salón','Salon','la pantalla','ekran'),
('El Salón','Salon','el equipo de música','wieża stereo'),
('El Salón','Salon','el altavoz','głośnik'),
('El Salón','Salon','acogedor','przytulny'),
('El Salón','Salon','amplio','przestronny'),
('El Salón','Salon','el sofá cama','sofa rozkładana'),
('El Salón','Salon','recibir visitas','przyjmować gości'),
('El Salón','Salon','el rincón','kąt / róg (pokoju)'),
('Limpieza del Hogar','Sprzątanie domu','la limpieza','sprzątanie'),
('Limpieza del Hogar','Sprzątanie domu','limpiar','czyścić / sprzątać'),
('Limpieza del Hogar','Sprzątanie domu','ensuciar','brudzić'),
('Limpieza del Hogar','Sprzątanie domu','barrer','zamiatać'),
('Limpieza del Hogar','Sprzątanie domu','la escoba','miotła'),
('Limpieza del Hogar','Sprzątanie domu','el recogedor','szufelka'),
('Limpieza del Hogar','Sprzątanie domu','fregar','myć (podłogę/naczynia)'),
('Limpieza del Hogar','Sprzątanie domu','la fregona','mop'),
('Limpieza del Hogar','Sprzątanie domu','el cubo','wiadro'),
('Limpieza del Hogar','Sprzątanie domu','el agua','woda'),
('Limpieza del Hogar','Sprzątanie domu','el jabón','mydło'),
('Limpieza del Hogar','Sprzątanie domu','el detergente','detergent'),
('Limpieza del Hogar','Sprzątanie domu','la lejía','wybielacz'),
('Limpieza del Hogar','Sprzątanie domu','el desinfectante','środek dezynfekujący'),
('Limpieza del Hogar','Sprzątanie domu','el estropajo','druciak / szorstka gąbka'),
('Limpieza del Hogar','Sprzątanie domu','la bayeta / el trapo','ścierka'),
('Limpieza del Hogar','Sprzątanie domu','la esponja','gąbka'),
('Limpieza del Hogar','Sprzątanie domu','aspirar','odkurzać'),
('Limpieza del Hogar','Sprzątanie domu','la aspiradora','odkurzacz'),
('Limpieza del Hogar','Sprzątanie domu','el polvo','kurz'),
('Limpieza del Hogar','Sprzątanie domu','quitar el polvo','ścierać kurz'),
('Limpieza del Hogar','Sprzątanie domu','el plumero','miotelka do kurzu'),
('Limpieza del Hogar','Sprzątanie domu','planchar','prasować'),
('Limpieza del Hogar','Sprzątanie domu','la plancha','żelazko'),
('Limpieza del Hogar','Sprzątanie domu','la tabla de planchar','deska do prasowania'),
('Limpieza del Hogar','Sprzątanie domu','lavar','myć / prać'),
('Limpieza del Hogar','Sprzątanie domu','la lavadora','pralka'),
('Limpieza del Hogar','Sprzątanie domu','tender la ropa','rozwieszać pranie'),
('Limpieza del Hogar','Sprzątanie domu','la pinza','klammerka (do prania)'),
('Limpieza del Hogar','Sprzątanie domu','el tendedero','suszarka na pranie (stojak)'),
('Limpieza del Hogar','Sprzątanie domu','secar','suszyć'),
('Limpieza del Hogar','Sprzątanie domu','la secadora','suszarka (do ubrań)'),
('Limpieza del Hogar','Sprzątanie domu','el lavavajillas','zmywarka'),
('Limpieza del Hogar','Sprzątanie domu','la basura','śmieci'),
('Limpieza del Hogar','Sprzątanie domu','el cubo de basura','kosz na śmieci'),
('Limpieza del Hogar','Sprzątanie domu','reciclar','recyklingować'),
('Limpieza del Hogar','Sprzątanie domu','la bolsa de basura','worek na śmieci'),
('Limpieza del Hogar','Sprzątanie domu','ordenar','porządkować'),
('Limpieza del Hogar','Sprzątanie domu','recoger','zbierać / sprzątać'),
('Limpieza del Hogar','Sprzątanie domu','el desorden','bałagan'),
('Limpieza del Hogar','Sprzątanie domu','el orden','porządek'),
('Limpieza del Hogar','Sprzątanie domu','sucio','brudny'),
('Limpieza del Hogar','Sprzątanie domu','limpio','czysty'),
('Limpieza del Hogar','Sprzątanie domu','manchar','plamić'),
('Limpieza del Hogar','Sprzątanie domu','la mancha','plama'),
('Limpieza del Hogar','Sprzątanie domu','el quitamanchas','odplamiacz'),
('Limpieza del Hogar','Sprzątanie domu','ventilar','wietrzyć'),
('Limpieza del Hogar','Sprzątanie domu','el cristal','szyba / szkło'),
('Limpieza del Hogar','Sprzątanie domu','el limpiacristales','płyn do szyb'),
('Limpieza del Hogar','Sprzątanie domu','el cepillo','szczotka'),
('Mascotas','Zwierzęta domowe','la mascota','zwierzę domowe'),
('Mascotas','Zwierzęta domowe','el perro','pies'),
('Mascotas','Zwierzęta domowe','el gato','kot'),
('Mascotas','Zwierzęta domowe','el cachorro','szczeniak / młode'),
('Mascotas','Zwierzęta domowe','el gatito','kociak'),
('Mascotas','Zwierzęta domowe','ladrar','szczekać'),
('Mascotas','Zwierzęta domowe','maullar','miauczeć'),
('Mascotas','Zwierzęta domowe','morder','gryźć'),
('Mascotas','Zwierzęta domowe','arañar','drapać'),
('Mascotas','Zwierzęta domowe','el collar','obroża'),
('Mascotas','Zwierzęta domowe','la correa','smycz'),
('Mascotas','Zwierzęta domowe','el bozal','kaganiec'),
('Mascotas','Zwierzęta domowe','el hueso','kość'),
('Mascotas','Zwierzęta domowe','el pienso','sucha karma'),
('Mascotas','Zwierzęta domowe','el comedero','miska na jedzenie'),
('Mascotas','Zwierzęta domowe','el bebedero','miska na wodę'),
('Mascotas','Zwierzęta domowe','la cama','legowisko'),
('Mascotas','Zwierzęta domowe','la jaula','klatka'),
('Mascotas','Zwierzęta domowe','el pájaro','ptak'),
('Mascotas','Zwierzęta domowe','el loro','papuga'),
('Mascotas','Zwierzęta domowe','el canario','kanarek'),
('Mascotas','Zwierzęta domowe','el pez','rybka'),
('Mascotas','Zwierzęta domowe','el acuario / la pecera','akwarium'),
('Mascotas','Zwierzęta domowe','el hámster','chomik'),
('Mascotas','Zwierzęta domowe','la cobaya','świnka morska'),
('Mascotas','Zwierzęta domowe','el conejo','królik'),
('Mascotas','Zwierzęta domowe','el ratón','mysz'),
('Mascotas','Zwierzęta domowe','la tortuga','żółw'),
('Mascotas','Zwierzęta domowe','el lagarto','jaszczurka'),
('Mascotas','Zwierzęta domowe','la serpiente','wąż'),
('Mascotas','Zwierzęta domowe','el veterinario','weterynarz'),
('Mascotas','Zwierzęta domowe','la vacuna','szczepionka'),
('Mascotas','Zwierzęta domowe','vacunar','szczepić'),
('Mascotas','Zwierzęta domowe','acariciar','głaskać'),
('Mascotas','Zwierzęta domowe','el pelo','sierść / włosy'),
('Mascotas','Zwierzęta domowe','soltar pelo','gubić sierść / linieć'),
('Mascotas','Zwierzęta domowe','cepillar','szczotkować'),
('Mascotas','Zwierzęta domowe','pasear (al perro)','wyprowadzać (psa)'),
('Mascotas','Zwierzęta domowe','el juguete','zabawka'),
('Mascotas','Zwierzęta domowe','la arena (para gatos)','żwirek (dla kotów)'),
('Mascotas','Zwierzęta domowe','el arenero','kuweta'),
('Mascotas','Zwierzęta domowe','la pulga','pchła'),
('Mascotas','Zwierzęta domowe','la garrapata','kleszcz'),
('Mascotas','Zwierzęta domowe','el microchip','czip'),
('Mascotas','Zwierzęta domowe','la raza','rasa'),
('Mascotas','Zwierzęta domowe','de pura raza','rasowy'),
('Mascotas','Zwierzęta domowe','el mestizo','kundel / mieszaniec'),
('Mascotas','Zwierzęta domowe','adoptar','adoptować'),
('Mascotas','Zwierzęta domowe','la adopción','adopcja'),
('Mascotas','Zwierzęta domowe','domesticar','oswoić'),
('Animales Salvajes','Zwierzęta dzikie','el animal salvaje','dzikie zwierzę'),
('Animales Salvajes','Zwierzęta dzikie','el león','lew'),
('Animales Salvajes','Zwierzęta dzikie','el tigre','tygrys'),
('Animales Salvajes','Zwierzęta dzikie','el leopardo','leopard'),
('Animales Salvajes','Zwierzęta dzikie','el guepardo','gepard'),
('Animales Salvajes','Zwierzęta dzikie','el elefante','słoń'),
('Animales Salvajes','Zwierzęta dzikie','el rinoceronte','nosorożec'),
('Animales Salvajes','Zwierzęta dzikie','el hipopótamo','hipopotam'),
('Animales Salvajes','Zwierzęta dzikie','la jirafa','żyrafa'),
('Animales Salvajes','Zwierzęta dzikie','la cebra','zebra'),
('Animales Salvajes','Zwierzęta dzikie','el mono','małpa'),
('Animales Salvajes','Zwierzęta dzikie','el gorila','goryl'),
('Animales Salvajes','Zwierzęta dzikie','el chimpancé','szympans'),
('Animales Salvajes','Zwierzęta dzikie','el oso','niedźwiedź'),
('Animales Salvajes','Zwierzęta dzikie','el oso polar','niedźwiedź polarny'),
('Animales Salvajes','Zwierzęta dzikie','el oso panda','panda'),
('Animales Salvajes','Zwierzęta dzikie','el lobo','wilk'),
('Animales Salvajes','Zwierzęta dzikie','el zorro','lis'),
('Animales Salvajes','Zwierzęta dzikie','el ciervo','jeleń'),
('Animales Salvajes','Zwierzęta dzikie','el alce','łoś'),
('Animales Salvajes','Zwierzęta dzikie','el jabalí','dzik'),
('Animales Salvajes','Zwierzęta dzikie','el canguro','kangur'),
('Animales Salvajes','Zwierzęta dzikie','el koala','koala'),
('Animales Salvajes','Zwierzęta dzikie','el camello','wielbłąd'),
('Animales Salvajes','Zwierzęta dzikie','el dromedario','dromader'),
('Animales Salvajes','Zwierzęta dzikie','el cocodrilo','krokodyl'),
('Animales Salvajes','Zwierzęta dzikie','el caimán','kajman'),
('Animales Salvajes','Zwierzęta dzikie','la serpiente','wąż'),
('Animales Salvajes','Zwierzęta dzikie','la cobra','kobra'),
('Animales Salvajes','Zwierzęta dzikie','la pitón','pyton'),
('Animales Salvajes','Zwierzęta dzikie','la rana','żaba'),
('Animales Salvajes','Zwierzęta dzikie','el sapo','ropucha'),
('Animales Salvajes','Zwierzęta dzikie','el murciélago','nietoperz'),
('Animales Salvajes','Zwierzęta dzikie','la ardilla','wiewiórka'),
('Animales Salvajes','Zwierzęta dzikie','el castor','bóbr'),
('Animales Salvajes','Zwierzęta dzikie','el águila','orzeł'),
('Animales Salvajes','Zwierzęta dzikie','el halcón','sokół'),
('Animales Salvajes','Zwierzęta dzikie','el buitre','sęp'),
('Animales Salvajes','Zwierzęta dzikie','el avestruz','struś'),
('Animales Salvajes','Zwierzęta dzikie','el pingüino','pingwin'),
('Animales Salvajes','Zwierzęta dzikie','la selva','dżungla / puszcza'),
('Animales Salvajes','Zwierzęta dzikie','el bosque','las'),
('Animales Salvajes','Zwierzęta dzikie','la sabana','sawanna'),
('Animales Salvajes','Zwierzęta dzikie','el zoológico / el zoo','zoo'),
('Animales Salvajes','Zwierzęta dzikie','cazar','polować'),
('Animales Salvajes','Zwierzęta dzikie','el cazador','myśliwy'),
('Animales Salvajes','Zwierzęta dzikie','la presa','ofiara / zdobycz'),
('Animales Salvajes','Zwierzęta dzikie','el depredador','drapieżnik'),
('Animales Salvajes','Zwierzęta dzikie','en peligro de extinción','zagrożony wyginięciem'),
('Animales Salvajes','Zwierzęta dzikie','el hábitat','siedlisko / środowisko naturalne'),
('Aves','Ptaki','el ave / el pájaro','ptak'),
('Aves','Ptaki','el águila','orzeł'),
('Aves','Ptaki','el halcón','sokół'),
('Aves','Ptaki','el búho','sowa / puchacz'),
('Aves','Ptaki','la lechuza','sowa płomykówka'),
('Aves','Ptaki','el cuervo','kruk / wrona'),
('Aves','Ptaki','la paloma','gołąb'),
('Aves','Ptaki','el cisne','łabędź'),
('Aves','Ptaki','el pato','kaczka'),
('Aves','Ptaki','el ganso','gęś'),
('Aves','Ptaki','el pingüino','pingwin'),
('Aves','Ptaki','el avestruz','struś'),
('Aves','Ptaki','el loro','papuga'),
('Aves','Ptaki','la cotorra','papużka'),
('Aves','Ptaki','el canario','kanarek'),
('Aves','Ptaki','el jilguero','szczygieł'),
('Aves','Ptaki','el ruiseñor','słowik'),
('Aves','Ptaki','el gorrión','wróbel'),
('Aves','Ptaki','la golondrina','jaskółka'),
('Aves','Ptaki','la cigüeña','bocian'),
('Aves','Ptaki','el flamenco','flaming'),
('Aves','Ptaki','el pelícano','pelikan'),
('Aves','Ptaki','la gaviota','mewa'),
('Aves','Ptaki','el albatros','albatros'),
('Aves','Ptaki','el pavo real','paw'),
('Aves','Ptaki','el pavo','indyk'),
('Aves','Ptaki','la gallina','kura'),
('Aves','Ptaki','el gallo','kogut'),
('Aves','Ptaki','el pollito','kurczak / pisklę'),
('Aves','Ptaki','el colibrí','koliber'),
('Aves','Ptaki','el tucán','tukan'),
('Aves','Ptaki','el pájaro carpintero','dzięcioł'),
('Aves','Ptaki','el Martín pescador','zimorodek'),
('Aves','Ptaki','el nido','gniazdo'),
('Aves','Ptaki','la pluma','pióro'),
('Aves','Ptaki','el pico','dziób'),
('Aves','Ptaki','el ala','skrzydło'),
('Aves','Ptaki','volar','latać'),
('Aves','Ptaki','piar','ćwierkać / piszczeć'),
('Aves','Ptaki','el canto','śpiew'),
('Aves','Ptaki','cantar','śpiewać'),
('Aves','Ptaki','poner un huevo','znieść jajko'),
('Aves','Ptaki','el huevo','jajko'),
('Aves','Ptaki','la cáscara','skorupka'),
('Aves','Ptaki','el polluelo','pisklę'),
('Aves','Ptaki','la bandada','stado (ptaków)'),
('Aves','Ptaki','emigrar','emigrować / odlatywać'),
('Aves','Ptaki','la jaula','klatka'),
('Aves','Ptaki','el comedero','karmnik'),
('Aves','Ptaki','el plumaje','upierzenie'),
('Insectos','Owady','el insecto','owad'),
('Insectos','Owady','el bicho','robal / żyjątko'),
('Insectos','Owady','la mosca','mucha'),
('Insectos','Owady','el mosquito','komar'),
('Insectos','Owady','la abeja','pszczoła'),
('Insectos','Owady','la avispa','osa'),
('Insectos','Owady','la hormiga','mrówka'),
('Insectos','Owady','la araña','pająk'),
('Insectos','Owady','la mariposa','motyl'),
('Insectos','Owady','la polilla','ćma / mól'),
('Insectos','Owady','el escarabajo','chrząszcz / żuk'),
('Insectos','Owady','la mariquita','biedronka'),
('Insectos','Owady','el saltamontes','konik polny'),
('Insectos','Owady','el grillo','świerszcz'),
('Insectos','Owady','la cucaracha','karaluch'),
('Insectos','Owady','el ciempiés','stonoga'),
('Insectos','Owady','el gusano','robak / dżdżownica'),
('Insectos','Owady','la oruga','gąsienica'),
('Insectos','Owady','la libélula','ważka'),
('Insectos','Owady','la mantis religiosa','modliszka'),
('Insectos','Owady','la pulga','pchła'),
('Insectos','Owady','la garrapata','kleszcz'),
('Insectos','Owady','el piojo','wesz'),
('Insectos','Owady','la chinche','pluskwa'),
('Insectos','Owady','el escorpión / el alacrán','skorpion'),
('Insectos','Owady','el caracol','ślimak'),
('Insectos','Owady','la babosa','śliźniak'),
('Insectos','Owady','la tela de araña','pajęczyna'),
('Insectos','Owady','picar','żądlić / gryźć (o owadzie)'),
('Insectos','Owady','la picadura','ukąszenie / użądlenie'),
('Insectos','Owady','zumbar','bzyczeć'),
('Insectos','Owady','el zumbido','bzyczenie'),
('Insectos','Owady','el enjambre','rój'),
('Insectos','Owady','la colmena','ul'),
('Insectos','Owady','la miel','miód'),
('Insectos','Owady','el polen','pyłek'),
('Insectos','Owady','polinizar','zapylać'),
('Insectos','Owady','la antena','czułek'),
('Insectos','Owady','arrastrarse','pełzać'),
('Insectos','Owady','la larva','larwa'),
('Insectos','Owady','el capullo','kokon'),
('Insectos','Owady','venenoso','jadowity / trujący'),
('Insectos','Owady','la plaga','plaga / szkodniki'),
('Insectos','Owady','el repelente','środek odstraszający (repelent)'),
('Insectos','Owady','el insecticida','środek owadobójczy'),
('Insectos','Owady','aplastar','rozgnieść'),
('Insectos','Owady','molesto','irytujący / uciążliwy'),
('Insectos','Owady','el aguijón','żądło'),
('Insectos','Owady','el hormiguero','mrowisko'),
('Insectos','Owady','inofensivo','nieszkodliwy'),
('Animales Marinos','Zwierzęta morskie','el animal marino','zwierzę morskie'),
('Animales Marinos','Zwierzęta morskie','el pez','ryba (żywa)'),
('Animales Marinos','Zwierzęta morskie','el tiburón','rekin'),
('Animales Marinos','Zwierzęta morskie','la ballena','wieloryb'),
('Animales Marinos','Zwierzęta morskie','el delfín','delfin'),
('Animales Marinos','Zwierzęta morskie','la orca','orka'),
('Animales Marinos','Zwierzęta morskie','el pulpo','ośmiornica'),
('Animales Marinos','Zwierzęta morskie','el calamar','kałamarnica'),
('Animales Marinos','Zwierzęta morskie','la medusa','meduza'),
('Animales Marinos','Zwierzęta morskie','la estrella de mar','rozgwiazda'),
('Animales Marinos','Zwierzęta morskie','el caballito de mar','konik morski'),
('Animales Marinos','Zwierzęta morskie','la tortuga marina','żółw morski'),
('Animales Marinos','Zwierzęta morskie','el cangrejo','krab'),
('Animales Marinos','Zwierzęta morskie','la langosta','homar / langusta'),
('Animales Marinos','Zwierzęta morskie','la gamba','krewetka (mała)'),
('Animales Marinos','Zwierzęta morskie','el langostino','krewetka (duża)'),
('Animales Marinos','Zwierzęta morskie','la ostra','ostryga'),
('Animales Marinos','Zwierzęta morskie','el mejillón','omułek'),
('Animales Marinos','Zwierzęta morskie','la almeja','małż'),
('Animales Marinos','Zwierzęta morskie','el caracol de mar','ślimak morski'),
('Animales Marinos','Zwierzęta morskie','la foca','foka'),
('Animales Marinos','Zwierzęta morskie','la morsa','mors'),
('Animales Marinos','Zwierzęta morskie','el león marino','lew morski'),
('Animales Marinos','Zwierzęta morskie','el manatí','manat'),
('Animales Marinos','Zwierzęta morskie','la raya','płaszczka'),
('Animales Marinos','Zwierzęta morskie','el pez espada','miecznik'),
('Animales Marinos','Zwierzęta morskie','el pez payaso','błazenek (rybka)'),
('Animales Marinos','Zwierzęta morskie','el coral','koral'),
('Animales Marinos','Zwierzęta morskie','el arrecife','rafa (koralowa)'),
('Animales Marinos','Zwierzęta morskie','la concha','muszla'),
('Animales Marinos','Zwierzęta morskie','la aleta','płetwa'),
('Animales Marinos','Zwierzęta morskie','las agallas','skrzela'),
('Animales Marinos','Zwierzęta morskie','la escama','łuska'),
('Animales Marinos','Zwierzęta morskie','la cola','ogon'),
('Animales Marinos','Zwierzęta morskie','el océano','ocean'),
('Animales Marinos','Zwierzęta morskie','el mar','morze'),
('Animales Marinos','Zwierzęta morskie','nadar','pływać'),
('Animales Marinos','Zwierzęta morskie','bucear','nurkować'),
('Animales Marinos','Zwierzęta morskie','sumergirse','zanurzać się'),
('Animales Marinos','Zwierzęta morskie','el acuario','akwarium (budynek / zbiornik)'),
('Animales Marinos','Zwierzęta morskie','el plancton','plankton'),
('Animales Marinos','Zwierzęta morskie','el alga','glon / alga'),
('Animales Marinos','Zwierzęta morskie','salado','słony'),
('Animales Marinos','Zwierzęta morskie','la profundidad','głębia / głębokość'),
('Animales Marinos','Zwierzęta morskie','la marea','pływ (przypływ/odpływ)'),
('Animales Marinos','Zwierzęta morskie','la ola','fala'),
('Animales Marinos','Zwierzęta morskie','la costa','wybrzeże'),
('Animales Marinos','Zwierzęta morskie','el tentáculo','macka'),
('Animales Marinos','Zwierzęta morskie','el caparazón','pancerz / skorupa'),
('Animales Marinos','Zwierzęta morskie','la anémona','ukwiał'),
('Árboles','Drzewa','el árbol','drzewo'),
('Árboles','Drzewa','el tronco','pień'),
('Árboles','Drzewa','la rama','gałąź'),
('Árboles','Drzewa','la hoja','liść'),
('Árboles','Drzewa','la raíz','korzeń'),
('Árboles','Drzewa','la corteza','kora'),
('Árboles','Drzewa','la savia','sok (drzewny)'),
('Árboles','Drzewa','el roble','dąb'),
('Árboles','Drzewa','el pino','sosna'),
('Árboles','Drzewa','el abeto','jodła'),
('Árboles','Drzewa','el haya','buk'),
('Árboles','Drzewa','el abedul','brzoza'),
('Árboles','Drzewa','el sauce','wierzba'),
('Árboles','Drzewa','el sauce llorón','wierzba płacząca'),
('Árboles','Drzewa','el álamo','topola'),
('Árboles','Drzewa','el fresno','jesion'),
('Árboles','Drzewa','el olmo','wiąz'),
('Árboles','Drzewa','el arce','klon'),
('Árboles','Drzewa','el castaño','kasztanowiec'),
('Árboles','Drzewa','el nogal','orzech (drzewo)'),
('Árboles','Drzewa','el almendro','migdałowiec'),
('Árboles','Drzewa','el olivo','drzewo oliwne / oliwka'),
('Árboles','Drzewa','el manzano','jabłoń'),
('Árboles','Drzewa','el peral','grusza'),
('Árboles','Drzewa','el ciruelo','śliwa'),
('Árboles','Drzewa','el cerezo','czereśnia / wiśnia (drzewo)'),
('Árboles','Drzewa','el limonero','drzewo cytrynowe'),
('Árboles','Drzewa','el naranjo','drzewo pomarańczowe'),
('Árboles','Drzewa','el melocotonero','brzoskwinia (drzewo)'),
('Árboles','Drzewa','la palmera','palma'),
('Árboles','Drzewa','el eucalipto','eukaliptus'),
('Árboles','Drzewa','el baobab','baobab'),
('Árboles','Drzewa','el bonsái','bonsai'),
('Árboles','Drzewa','el bosque','las'),
('Árboles','Drzewa','la selva','puszcza / dżungla'),
('Árboles','Drzewa','plantar','sadzić'),
('Árboles','Drzewa','talar','ścinać (drzewa)'),
('Árboles','Drzewa','la madera','drewno'),
('Árboles','Drzewa','la leña','drewno na opał'),
('Árboles','Drzewa','el tocón','pniak'),
('Árboles','Drzewa','el bosque de coníferas','las iglasty'),
('Árboles','Drzewa','el bosque de hoja caduca','las liściasty'),
('Árboles','Drzewa','la hoja perenne','liść zimozielony'),
('Árboles','Drzewa','la hoja caduca','liść opadający'),
('Árboles','Drzewa','dar sombra','dawać cień'),
('Árboles','Drzewa','el fruto','owoc'),
('Árboles','Drzewa','la semilla','nasiono'),
('Árboles','Drzewa','la piña','szyszka / ananas'),
('Árboles','Drzewa','florecer','kwitnąć'),
('Árboles','Drzewa','el follaje','listowie / korona drzewa'),
('Flores','Kwiaty','la flor','kwiat'),
('Flores','Kwiaty','el pétalo','płatek'),
('Flores','Kwiaty','el tallo','łodyga'),
('Flores','Kwiaty','la espina','kolec'),
('Flores','Kwiaty','la hoja','liść'),
('Flores','Kwiaty','el capullo','pąk'),
('Flores','Kwiaty','el polen','pyłek'),
('Flores','Kwiaty','el néctar','nektar'),
('Flores','Kwiaty','la rosa','róża'),
('Flores','Kwiaty','el tulipán','tulipan'),
('Flores','Kwiaty','la margarita','stokrotka / margaretka'),
('Flores','Kwiaty','el clavel','goździk'),
('Flores','Kwiaty','el girasol','słonecznik'),
('Flores','Kwiaty','la orquídea','orchidea / storczyk'),
('Flores','Kwiaty','el lirio','lilia / irys'),
('Flores','Kwiaty','la azucena','lilia (biała)'),
('Flores','Kwiaty','la violeta','fiołek'),
('Flores','Kwiaty','el pensamiento','bratek'),
('Flores','Kwiaty','la amapola','mak'),
('Flores','Kwiaty','el jazmín','jaśmin'),
('Flores','Kwiaty','la lavanda','lawenda'),
('Flores','Kwiaty','la lila','bez (lilak)'),
('Flores','Kwiaty','la camelia','kamelia'),
('Flores','Kwiaty','el loto','lotos'),
('Flores','Kwiaty','la peonía','piwonia'),
('Flores','Kwiaty','el narciso','narcyz'),
('Flores','Kwiaty','el crisantemo','chryzantema'),
('Flores','Kwiaty','el diente de león','mniszek lekarski (mlecz)'),
('Flores','Kwiaty','la begonia','begonia'),
('Flores','Kwiaty','el geranio','pelargonia / geranium'),
('Flores','Kwiaty','la dalia','dalia'),
('Flores','Kwiaty','el gladiolo','mieczyk (gladiola)'),
('Flores','Kwiaty','la anémona','zawilec (anemon)'),
('Flores','Kwiaty','la magnolia','magnolia'),
('Flores','Kwiaty','el hibisco','hibiskus'),
('Flores','Kwiaty','florecer','kwitnąć'),
('Flores','Kwiaty','marchitarse','więdnąć'),
('Flores','Kwiaty','oler','pachnieć / wąchać'),
('Flores','Kwiaty','el aroma','aromat / zapach'),
('Flores','Kwiaty','el ramo','bukiet'),
('Flores','Kwiaty','el florero / el jarrón','wazon'),
('Flores','Kwiaty','plantar','sadzić'),
('Flores','Kwiaty','regar','podlewać'),
('Flores','Kwiaty','el jardín','ogród'),
('Flores','Kwiaty','la maceta','doniczka'),
('Flores','Kwiaty','la floristería','kwiaciarnia'),
('Flores','Kwiaty','el florista','florysta / kwiaciarz'),
('Flores','Kwiaty','silvestre','dziki / polny'),
('Flores','Kwiaty','cultivar','uprawiać (rośliny)'),
('Flores','Kwiaty','la corona de flores','wieniec z kwiatów'),
('Accidentes Geográficos','Ukształtowanie terenu','el accidente geográfico','ukształtowanie terenu'),
('Accidentes Geográficos','Ukształtowanie terenu','la montaña','góra'),
('Accidentes Geográficos','Ukształtowanie terenu','la cordillera','łańcuch górski'),
('Accidentes Geográficos','Ukształtowanie terenu','el volcán','wulkan'),
('Accidentes Geográficos','Ukształtowanie terenu','la colina / el cerro','wzgórze'),
('Accidentes Geográficos','Ukształtowanie terenu','el valle','dolina'),
('Accidentes Geográficos','Ukształtowanie terenu','la llanura','równina'),
('Accidentes Geográficos','Ukształtowanie terenu','la meseta','płaskowyż'),
('Accidentes Geográficos','Ukształtowanie terenu','el cañón','kanion / wąwóz'),
('Accidentes Geográficos','Ukształtowanie terenu','el barranco','jar / wąwóz'),
('Accidentes Geográficos','Ukształtowanie terenu','el precipicio','przepaść'),
('Accidentes Geográficos','Ukształtowanie terenu','el acantilado','klif'),
('Accidentes Geográficos','Ukształtowanie terenu','la costa','wybrzeże'),
('Accidentes Geográficos','Ukształtowanie terenu','la playa','plaża'),
('Accidentes Geográficos','Ukształtowanie terenu','el cabo','przylądek'),
('Accidentes Geográficos','Ukształtowanie terenu','la península','półwysep'),
('Accidentes Geográficos','Ukształtowanie terenu','el istmo','przesmyk'),
('Accidentes Geográficos','Ukształtowanie terenu','la isla','wyspa'),
('Accidentes Geográficos','Ukształtowanie terenu','el archipiélago','archipelag'),
('Accidentes Geográficos','Ukształtowanie terenu','el golfo','zatoka (duża)'),
('Accidentes Geográficos','Ukształtowanie terenu','la bahía','zatoka (mniejsza)'),
('Accidentes Geográficos','Ukształtowanie terenu','la cala','zatoczka'),
('Accidentes Geográficos','Ukształtowanie terenu','el estrecho','cieśnina'),
('Accidentes Geográficos','Ukształtowanie terenu','el océano','ocean'),
('Accidentes Geográficos','Ukształtowanie terenu','el mar','morze'),
('Accidentes Geográficos','Ukształtowanie terenu','el lago','jezioro'),
('Accidentes Geográficos','Ukształtowanie terenu','la laguna','laguna / jeziorko'),
('Accidentes Geográficos','Ukształtowanie terenu','el río','rzeka'),
('Accidentes Geográficos','Ukształtowanie terenu','el arroyo','strumień'),
('Accidentes Geográficos','Ukształtowanie terenu','el manantial','źródło'),
('Accidentes Geográficos','Ukształtowanie terenu','la cascada / la catarata','wodospad'),
('Accidentes Geográficos','Ukształtowanie terenu','el delta','delta (rzeki)'),
('Accidentes Geográficos','Ukształtowanie terenu','el estuario','estuarium'),
('Accidentes Geográficos','Ukształtowanie terenu','el pantano / la marisma','bagno / moczary'),
('Accidentes Geográficos','Ukształtowanie terenu','el glaciar','lodowiec'),
('Accidentes Geográficos','Ukształtowanie terenu','el fiordo','fiord'),
('Accidentes Geográficos','Ukształtowanie terenu','el desierto','pustynia'),
('Accidentes Geográficos','Ukształtowanie terenu','el oasis','oaza'),
('Accidentes Geográficos','Ukształtowanie terenu','la duna','wydma'),
('Accidentes Geográficos','Ukształtowanie terenu','la selva','dżungla'),
('Accidentes Geográficos','Ukształtowanie terenu','el bosque','las'),
('Accidentes Geográficos','Ukształtowanie terenu','la cueva / la caverna','jaskinia'),
('Accidentes Geográficos','Ukształtowanie terenu','la sima','rozpadlina'),
('Accidentes Geográficos','Ukształtowanie terenu','el pico / la cima','szczyt (góry)'),
('Accidentes Geográficos','Ukształtowanie terenu','la ladera','zbocze'),
('Accidentes Geográficos','Ukształtowanie terenu','la falda (de la montaña)','podnóże (góry)'),
('Accidentes Geográficos','Ukształtowanie terenu','el cráter','krater'),
('Accidentes Geográficos','Ukształtowanie terenu','el arrecife','rafa'),
('Accidentes Geográficos','Ukształtowanie terenu','el atolón','atol'),
('Accidentes Geográficos','Ukształtowanie terenu','la depresión','depresja (terenowa)'),
('Catástrofes Naturales','Katastrofy naturalne','la catástrofe natural','katastrofa naturalna'),
('Catástrofes Naturales','Katastrofy naturalne','el desastre','katastrofa / klęska'),
('Catástrofes Naturales','Katastrofy naturalne','el terremoto / el seísmo','trzęsienie ziemi'),
('Catástrofes Naturales','Katastrofy naturalne','el temblor','wstrząs'),
('Catástrofes Naturales','Katastrofy naturalne','la réplica','wstrząs wtórny'),
('Catástrofes Naturales','Katastrofy naturalne','el epicentro','epicentrum'),
('Catástrofes Naturales','Katastrofy naturalne','la magnitud','magnituda / siła'),
('Catástrofes Naturales','Katastrofy naturalne','el maremoto','trzęsienie ziemi pod wodą'),
('Catástrofes Naturales','Katastrofy naturalne','el tsunami','tsunami'),
('Catástrofes Naturales','Katastrofy naturalne','la erupción volcánica','erupcja wulkanu'),
('Catástrofes Naturales','Katastrofy naturalne','la lava','lawa'),
('Catástrofes Naturales','Katastrofy naturalne','la ceniza','popiół'),
('Catástrofes Naturales','Katastrofy naturalne','el huracán','huragan'),
('Catástrofes Naturales','Katastrofy naturalne','el tornado','tornado'),
('Catástrofes Naturales','Katastrofy naturalne','el tifón','tajfun'),
('Catástrofes Naturales','Katastrofy naturalne','el ciclón','cyklon'),
('Catástrofes Naturales','Katastrofy naturalne','la tormenta','burza'),
('Catástrofes Naturales','Katastrofy naturalne','la tormenta tropical','burza tropikalna'),
('Catástrofes Naturales','Katastrofy naturalne','la tormenta de arena','burza piaskowa'),
('Catástrofes Naturales','Katastrofy naturalne','la tormenta de nieve','burza śnieżna'),
('Catástrofes Naturales','Katastrofy naturalne','la ventisca','zamieć'),
('Catástrofes Naturales','Katastrofy naturalne','el granizo / la granizada','grad / gradobicie'),
('Catástrofes Naturales','Katastrofy naturalne','la inundación','powódź'),
('Catástrofes Naturales','Katastrofy naturalne','desbordarse','wystąpić z brzegów'),
('Catástrofes Naturales','Katastrofy naturalne','la sequía','susza'),
('Catástrofes Naturales','Katastrofy naturalne','el incendio forestal','pożar lasu'),
('Catástrofes Naturales','Katastrofy naturalne','la avalancha / el alud','lawina'),
('Catástrofes Naturales','Katastrofy naturalne','el deslizamiento de tierra','osuwisko'),
('Catástrofes Naturales','Katastrofy naturalne','la ola de calor','fala upałów'),
('Catástrofes Naturales','Katastrofy naturalne','la ola de frío','fala mrozów'),
('Catástrofes Naturales','Katastrofy naturalne','el rayo','piorun / promień'),
('Catástrofes Naturales','Katastrofy naturalne','el relámpago','błyskawica'),
('Catástrofes Naturales','Katastrofy naturalne','el trueno','grzmot'),
('Catástrofes Naturales','Katastrofy naturalne','la emergencia','nagły wypadek / stan wyjątkowy'),
('Catástrofes Naturales','Katastrofy naturalne','la alarma','alarm'),
('Catástrofes Naturales','Katastrofy naturalne','la sirena','syrena'),
('Catástrofes Naturales','Katastrofy naturalne','el refugio','schron'),
('Catástrofes Naturales','Katastrofy naturalne','el rescate','ratunek'),
('Catástrofes Naturales','Katastrofy naturalne','rescatar','ratować'),
('Catástrofes Naturales','Katastrofy naturalne','el rescatista','ratownik'),
('Catástrofes Naturales','Katastrofy naturalne','el bombero','strażak'),
('Catástrofes Naturales','Katastrofy naturalne','la víctima','ofiara'),
('Catástrofes Naturales','Katastrofy naturalne','el herido','ranny'),
('Catástrofes Naturales','Katastrofy naturalne','el superviviente','ocalały'),
('Catástrofes Naturales','Katastrofy naturalne','el refugiado','uchodźca'),
('Catástrofes Naturales','Katastrofy naturalne','la evacuación','ewakuacja'),
('Catástrofes Naturales','Katastrofy naturalne','evacuar','ewakuować'),
('Catástrofes Naturales','Katastrofy naturalne','destruir','niszczyć'),
('Catástrofes Naturales','Katastrofy naturalne','la ruina','ruina'),
('Catástrofes Naturales','Katastrofy naturalne','los escombros','gruzy');
