insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Condimentos','Przyprawy','el condimento','przyprawa'),
('Condimentos','Przyprawy','la sal','sól'),
('Condimentos','Przyprawy','la pimienta','pieprz'),
('Condimentos','Przyprawy','el azúcar','cukier'),
('Condimentos','Przyprawy','el vinagre','ocet'),
('Condimentos','Przyprawy','el aceite','olej / oliwa'),
('Condimentos','Przyprawy','la mostaza','musztarda'),
('Condimentos','Przyprawy','el kétchup','keczup'),
('Condimentos','Przyprawy','la mayonesa','majonez'),
('Condimentos','Przyprawy','el ajo en polvo','czosnek niedźwiedzi / w proszku'),
('Condimentos','Przyprawy','la cebolla en polvo','cebula w proszku'),
('Condimentos','Przyprawy','el pimentón','papryka (przyprawa)'),
('Condimentos','Przyprawy','el orégano','oregano'),
('Condimentos','Przyprawy','la albahaca','bazylia'),
('Condimentos','Przyprawy','el tomillo','tymianek'),
('Condimentos','Przyprawy','el romero','rozmaryn'),
('Condimentos','Przyprawy','el comino','kmin rzymski'),
('Condimentos','Przyprawy','el curry','curry'),
('Condimentos','Przyprawy','la cúrcuma','kurkuma'),
('Condimentos','Przyprawy','el jengibre','imbir'),
('Condimentos','Przyprawy','la canela','cynamon'),
('Condimentos','Przyprawy','el clavo','goździk (przyprawa)'),
('Condimentos','Przyprawy','la nuez moscada','gałka muszkatołowa'),
('Condimentos','Przyprawy','el azafrán','szafran'),
('Condimentos','Przyprawy','el cilantro','kolendra'),
('Condimentos','Przyprawy','el perejil','pietruszka (przyprawa)'),
('Condimentos','Przyprawy','el eneldo','koperek'),
('Condimentos','Przyprawy','el laurel','liść laurowy'),
('Condimentos','Przyprawy','el anís','anyż'),
('Condimentos','Przyprawy','la vainilla','wanilia'),
('Condimentos','Przyprawy','la salsa de soja','sos sojowy'),
('Condimentos','Przyprawy','el tabasco','tabasco'),
('Condimentos','Przyprawy','el chile','chili'),
('Condimentos','Przyprawy','el jalapeño','jalapeño'),
('Condimentos','Przyprawy','la sal marina','sól morska'),
('Condimentos','Przyprawy','la pimienta negra','pieprz czarny'),
('Condimentos','Przyprawy','la pimienta blanca','pieprz biały'),
('Condimentos','Przyprawy','las hierbas provenzales','zioła prowansalskie'),
('Condimentos','Przyprawy','la guindilla','ostra papryczka'),
('Condimentos','Przyprawy','el sésamo','sezam'),
('Condimentos','Przyprawy','la semilla de amapola','mak (ziarno)'),
('Condimentos','Przyprawy','sazonar','doprawiać'),
('Condimentos','Przyprawy','salar','solić'),
('Condimentos','Przyprawy','condimentar','przyprawiać'),
('Condimentos','Przyprawy','aderezar','okraszać / doprawiać'),
('Condimentos','Przyprawy','el aderezo','dressing / przyprawa'),
('Condimentos','Przyprawy','picante','pikantny'),
('Condimentos','Przyprawy','salado','słony'),
('Condimentos','Przyprawy','sabroso','smaczny'),
('Condimentos','Przyprawy','la salsa','sos'),
('En la Cocina','W kuchni','la cocina','kuchnia (pomieszczenie/mebel)'),
('En la Cocina','W kuchni','la olla','garnek'),
('En la Cocina','W kuchni','la sartén','patelnia'),
('En la Cocina','W kuchni','la cacerola','rondel'),
('En la Cocina','W kuchni','la tapadera','pokrywka'),
('En la Cocina','W kuchni','el cazo','chochla / rondelik'),
('En la Cocina','W kuchni','el cuchillo','nóż'),
('En la Cocina','W kuchni','la tabla de cortar','deska do krojenia'),
('En la Cocina','W kuchni','el cucharón','wielka łyżka / chochla'),
('En la Cocina','W kuchni','la espumadera','łyżka cedzakowa / szumówka'),
('En la Cocina','W kuchni','el rallador','tarka'),
('En la Cocina','W kuchni','el colador','sitko / durszlak'),
('En la Cocina','W kuchni','el escurridor','ociekacz / durszlak'),
('En la Cocina','W kuchni','el mortero','moździerz'),
('En la Cocina','W kuchni','el rodillo','wałek do ciasta'),
('En la Cocina','W kuchni','el bol','miska'),
('En la Cocina','W kuchni','la fuente','półmisek / naczynie żaroodporne'),
('En la Cocina','W kuchni','la bandeja','taca'),
('En la Cocina','W kuchni','el molde','forma do pieczenia'),
('En la Cocina','W kuchni','el delantal','fartuch'),
('En la Cocina','W kuchni','el paño de cocina','ścierka kuchenna'),
('En la Cocina','W kuchni','la esponja','gąbka'),
('En la Cocina','W kuchni','el estropajo','druciak / szorstka gąbka'),
('En la Cocina','W kuchni','el lavavajillas','zmywarka / płyn do naczyń'),
('En la Cocina','W kuchni','el horno','piekarnik'),
('En la Cocina','W kuchni','el microondas','mikrofalówka'),
('En la Cocina','W kuchni','el frigorífico / la nevera','lodówka'),
('En la Cocina','W kuchni','el congelador','zamrażarka'),
('En la Cocina','W kuchni','la batidora','blender / mikser'),
('En la Cocina','W kuchni','la tostadora','toster'),
('En la Cocina','W kuchni','la báscula de cocina','waga kuchenna'),
('En la Cocina','W kuchni','pelar','obierać'),
('En la Cocina','W kuchni','cortar','kroić / ciąć'),
('En la Cocina','W kuchni','picar','siekać'),
('En la Cocina','W kuchni','rallar','ścierać (na tarce)'),
('En la Cocina','W kuchni','batir','ubijać'),
('En la Cocina','W kuchni','mezclar','mieszać'),
('En la Cocina','W kuchni','freír','smażyć'),
('En la Cocina','W kuchni','hervir','gotować (wodę)'),
('En la Cocina','W kuchni','cocer','gotować (potrawę)'),
('En la Cocina','W kuchni','asar','piec (mięso)'),
('En la Cocina','W kuchni','hornear','piec (ciasto)'),
('En la Cocina','W kuchni','calentar','podgrzewać'),
('En la Cocina','W kuchni','descongelar','rozmrażać'),
('En la Cocina','W kuchni','la receta','przepis'),
('En la Cocina','W kuchni','el ingrediente','składnik'),
('En la Cocina','W kuchni','el chef','szef kuchni'),
('En la Cocina','W kuchni','preparar','przygotowywać'),
('En la Cocina','W kuchni','servir','serwować / podawać'),
('En la Cocina','W kuchni','lavar los platos','zmywać naczynia'),
('Higiene Personal','Higiena osobista','la higiene','higiena'),
('Higiene Personal','Higiena osobista','el baño','łazienka / kąpiel'),
('Higiene Personal','Higiena osobista','la ducha','prysznic'),
('Higiene Personal','Higiena osobista','la bañera','wanna'),
('Higiene Personal','Higiena osobista','el lavabo','umywalka'),
('Higiene Personal','Higiena osobista','el váter / el inodoro','toaleta / muszla klozetowa'),
('Higiene Personal','Higiena osobista','el jabón','mydło'),
('Higiene Personal','Higiena osobista','el gel de ducha','żel pod prysznic'),
('Higiene Personal','Higiena osobista','el champú','szampon'),
('Higiene Personal','Higiena osobista','el acondicionador','odżywka (do włosów)'),
('Higiene Personal','Higiena osobista','la esponja','gąbka'),
('Higiene Personal','Higiena osobista','la toalla','ręcznik'),
('Higiene Personal','Higiena osobista','el albornoz','szlafrok'),
('Higiene Personal','Higiena osobista','el cepillo de dientes','szczoteczka do zębów'),
('Higiene Personal','Higiena osobista','la pasta de dientes','pasta do zębów'),
('Higiene Personal','Higiena osobista','el enjuague bucal','płyn do płukania ust'),
('Higiene Personal','Higiena osobista','el hilo dental','nić dentystyczna'),
('Higiene Personal','Higiena osobista','el desodorante','dezodorant'),
('Higiene Personal','Higiena osobista','el perfume','perfumy'),
('Higiene Personal','Higiena osobista','la colonia','woda kolońska'),
('Higiene Personal','Higiena osobista','el cepillo','szczotka'),
('Higiene Personal','Higiena osobista','el peine','grzebień'),
('Higiene Personal','Higiena osobista','peinarse','czesać się'),
('Higiene Personal','Higiena osobista','lavarse','myć się'),
('Higiene Personal','Higiena osobista','ducharse','brać prysznic'),
('Higiene Personal','Higiena osobista','bañarse','kąpać się'),
('Higiene Personal','Higiena osobista','el papel higiénico','papier toaletowy'),
('Higiene Personal','Higiena osobista','el pañuelo','chusteczka'),
('Higiene Personal','Higiena osobista','el bastoncillo','patyczek higieniczny'),
('Higiene Personal','Higiena osobista','la maquinilla de afeitar','maszynka do golenia'),
('Higiene Personal','Higiena osobista','la espuma de afeitar','pianka do golenia'),
('Higiene Personal','Higiena osobista','afeitarse','golić się'),
('Higiene Personal','Higiena osobista','la crema hidratante','krem nawilżający'),
('Higiene Personal','Higiena osobista','el cortauñas','obcinacz do paznokci'),
('Higiene Personal','Higiena osobista','la lima','pilnik (do paznokci)'),
('Higiene Personal','Higiena osobista','las tijeras','nożyczki'),
('Higiene Personal','Higiena osobista','el secador de pelo','suszarka do włosów'),
('Higiene Personal','Higiena osobista','limpio','czysty'),
('Higiene Personal','Higiena osobista','sucio','brudny'),
('Higiene Personal','Higiena osobista','secarse','wycierać się / suszyć się'),
('Higiene Personal','Higiena osobista','el sudor','pot'),
('Higiene Personal','Higiena osobista','sudar','pocić się'),
('Higiene Personal','Higiena osobista','la pastilla de jabón','kostka mydła'),
('Higiene Personal','Higiena osobista','la toallita','chusteczka nawilżana'),
('Higiene Personal','Higiena osobista','el gel hidroalcohólico','żel antybakteryjny'),
('Higiene Personal','Higiena osobista','la higiene íntima','higiena intymna'),
('Higiene Personal','Higiena osobista','el espejo','lustro'),
('Higiene Personal','Higiena osobista','el grifo','kran'),
('Higiene Personal','Higiena osobista','el agua','woda'),
('Higiene Personal','Higiena osobista','la salud','zdrowie'),
('Cosméticos','Kosmetyki','el cosmético','kosmetyk'),
('Cosméticos','Kosmetyki','el maquillaje','makijaż'),
('Cosméticos','Kosmetyki','la crema','krem'),
('Cosméticos','Kosmetyki','la loción','balsam / lotion'),
('Cosméticos','Kosmetyki','el sérum','serum'),
('Cosméticos','Kosmetyki','el tónico','tonik'),
('Cosméticos','Kosmetyki','el desmaquillante','płyn do demakijażu'),
('Cosméticos','Kosmetyki','el algodón','wacik / bawełna'),
('Cosméticos','Kosmetyki','la base de maquillaje','podkład'),
('Cosméticos','Kosmetyki','el corrector','korektor'),
('Cosméticos','Kosmetyki','los polvos','puder'),
('Cosméticos','Kosmetyki','el colorete','róż do policzków'),
('Cosméticos','Kosmetyki','el bronceador','bronzer'),
('Cosméticos','Kosmetyki','el iluminador','rozświetlacz'),
('Cosméticos','Kosmetyki','la sombra de ojos','cień do powiek'),
('Cosméticos','Kosmetyki','el delineador','eyeliner / konturówka'),
('Cosméticos','Kosmetyki','el rímel','tusz do rzęs'),
('Cosméticos','Kosmetyki','el lápiz de labios','konturówka do ust'),
('Cosméticos','Kosmetyki','el pintalabios','szminka'),
('Cosméticos','Kosmetyki','el brillo de labios','błyszczyk'),
('Cosméticos','Kosmetyki','el bálsamo labial','balsam do ust'),
('Cosméticos','Kosmetyki','el esmalte de uñas','lakier do paznokci'),
('Cosméticos','Kosmetyki','el quitaesmalte','zmywacz do paznokci'),
('Cosméticos','Kosmetyki','el pincel','pędzelek (np. do cieni)'),
('Cosméticos','Kosmetyki','la brocha','pędzel (np. do pudru)'),
('Cosméticos','Kosmetyki','la esponja de maquillaje','gąbeczka do makijażu'),
('Cosméticos','Kosmetyki','el neceser','kosmetyczka'),
('Cosméticos','Kosmetyki','el perfume','perfumy'),
('Cosméticos','Kosmetyki','la mascarilla','maseczka'),
('Cosméticos','Kosmetyki','la exfoliación','peeling (zabieg)'),
('Cosméticos','Kosmetyki','el exfoliante','peeling (produkt)'),
('Cosméticos','Kosmetyki','la crema antiedad','krem przeciwzmarszczkowy'),
('Cosméticos','Kosmetyki','el protector solar','krem z filtrem'),
('Cosméticos','Kosmetyki','maquillarse','malować się'),
('Cosméticos','Kosmetyki','desmaquillarse','zmywać makijaż'),
('Cosméticos','Kosmetyki','aplicarse','nakładać (np. krem)'),
('Cosméticos','Kosmetyki','difuminar','blendować / rozcierać'),
('Cosméticos','Kosmetyki','el tono','odcień'),
('Cosméticos','Kosmetyki','el cutis','cera'),
('Cosméticos','Kosmetyki','la piel','skóra'),
('Cosméticos','Kosmetyki','la ojera','cień pod okiem'),
('Cosméticos','Kosmetyki','la arruga','zmarszczka'),
('Cosméticos','Kosmetyki','el grano / el acné','krosta / trądzik'),
('Cosméticos','Kosmetyki','la belleza','uroda'),
('Cosméticos','Kosmetyki','el salón de belleza','salon kosmetyczny'),
('Cosméticos','Kosmetyki','la estética','estetyka'),
('Cosméticos','Kosmetyki','la manicura','manicure'),
('Cosméticos','Kosmetyki','la pedicura','pedicure'),
('Cosméticos','Kosmetyki','teñir','farbować'),
('Cosméticos','Kosmetyki','el tinte','farba do włosów');
