insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Juegos','Gry','el juego','gra'),
('Juegos','Gry','el juguete','zabawka'),
('Juegos','Gry','el juego de mesa','gra planszowa'),
('Juegos','Gry','las cartas','karty'),
('Juegos','Gry','la baraja','talia kart'),
('Juegos','Gry','el ajedrez','szachy'),
('Juegos','Gry','las damas','warcaby'),
('Juegos','Gry','el dominó','domino'),
('Juegos','Gry','el rompecabezas / el puzzle','puzzle'),
('Juegos','Gry','el dado','kostka do gry'),
('Juegos','Gry','el tablero','plansza'),
('Juegos','Gry','la ficha','pionek'),
('Juegos','Gry','el videojuego','gra wideo'),
('Juegos','Gry','la consola','konsola'),
('Juegos','Gry','el mando','kontroler / pad'),
('Juegos','Gry','el jugador','gracz'),
('Juegos','Gry','jugar','grać'),
('Juegos','Gry','ganar','wygrać'),
('Juegos','Gry','perder','przegrać'),
('Juegos','Gry','el ganador','zwycięzca'),
('Juegos','Gry','el perdedor','przegrany'),
('Juegos','Gry','el empate','remis'),
('Juegos','Gry','empatar','remisować'),
('Juegos','Gry','el punto','punkt'),
('Juegos','Gry','la puntuación','wynik'),
('Juegos','Gry','el nivel','poziom'),
('Juegos','Gry','la regla','zasada / reguła'),
('Juegos','Gry','hacer trampa','oszukiwać'),
('Juegos','Gry','el tramposo','oszust'),
('Juegos','Gry','el turno','kolej'),
('Juegos','Gry','tirar','rzucać (np. kostką)'),
('Juegos','Gry','mezclar','tasować'),
('Juegos','Gry','repartir','rozdawać (karty)'),
('Juegos','Gry','el escondite','chowanego'),
('Juegos','Gry','el pilla-pilla','berek'),
('Juegos','Gry','saltar a la comba','skakać przez skakankę'),
('Juegos','Gry','el columpio','huśtawka'),
('Juegos','Gry','el tobogán','zjeżdżalnia'),
('Juegos','Gry','el casino','kasyno'),
('Juegos','Gry','la ruleta','ruletka'),
('Juegos','Gry','apostar','obstawiać'),
('Juegos','Gry','la apuesta','zakład'),
('Juegos','Gry','el bingo','bingo'),
('Juegos','Gry','la lotería','loteria'),
('Juegos','Gry','el premio','nagroda'),
('Juegos','Gry','el campeonato','mistrzostwa'),
('Juegos','Gry','el torneo','turniej'),
('Juegos','Gry','divertido','zabawny / fajny'),
('Juegos','Gry','aburrido','nudny'),
('Juegos','Gry','el equipo','drużyna'),
('Las Fiestas','Święta','la fiesta','impreza / święto'),
('Las Fiestas','Święta','el festival','festiwal'),
('Las Fiestas','Święta','la celebración','obchody / świętowanie'),
('Las Fiestas','Święta','celebrar','świętować'),
('Las Fiestas','Święta','festejar','świętować / bawić się'),
('Las Fiestas','Święta','el cumpleaños','urodziny'),
('Las Fiestas','Święta','el santo','imieniny'),
('Las Fiestas','Święta','la boda','ślub / wesele'),
('Las Fiestas','Święta','el aniversario','rocznica'),
('Las Fiestas','Święta','la invitación','zaproszenie'),
('Las Fiestas','Święta','invitar','zapraszać'),
('Las Fiestas','Święta','el invitado','gość'),
('Las Fiestas','Święta','el regalo','prezent'),
('Las Fiestas','Święta','regalar','dawać w prezencie'),
('Las Fiestas','Święta','la tarta / el pastel','tort'),
('Las Fiestas','Święta','la vela','świeczka'),
('Las Fiestas','Święta','soplar','dmuchać'),
('Las Fiestas','Święta','la sorpresa','niespodzianka'),
('Las Fiestas','Święta','el globo','balon'),
('Las Fiestas','Święta','la decoración','dekoracja'),
('Las Fiestas','Święta','la música','muzyka'),
('Las Fiestas','Święta','bailar','tańczyć'),
('Las Fiestas','Święta','el brindis','toast'),
('Las Fiestas','Święta','brindar','wznosić toast'),
('Las Fiestas','Święta','la Navidad','Boże Narodzenie'),
('Las Fiestas','Święta','la Nochebuena','Wigilia'),
('Las Fiestas','Święta','la Nochevieja','Sylwester'),
('Las Fiestas','Święta','el Año Nuevo','Nowy Rok'),
('Las Fiestas','Święta','los Reyes Magos','Trzej Królowie'),
('Las Fiestas','Święta','la Semana Santa','Wielki Tydzień / Wielkanoc'),
('Las Fiestas','Święta','el carnaval','karnawał'),
('Las Fiestas','Święta','el disfraz','przebranie'),
('Las Fiestas','Święta','disfrazarse','przebierać się'),
('Las Fiestas','Święta','la máscara','maska'),
('Las Fiestas','Święta','el desfile','parada / pochód'),
('Las Fiestas','Święta','los fuegos artificiales','fajerwerki'),
('Las Fiestas','Święta','la tradición','tradycja'),
('Las Fiestas','Święta','tradicional','tradycyjny'),
('Las Fiestas','Święta','las vacaciones','wakacje / ferie'),
('Las Fiestas','Święta','el día festivo','dzień wolny od pracy'),
('Las Fiestas','Święta','la religión','religia'),
('Las Fiestas','Święta','la misa','msza'),
('Las Fiestas','Święta','la familia','rodzina'),
('Las Fiestas','Święta','el amigo','przyjaciel'),
('Las Fiestas','Święta','la comida','jedzenie / obiad'),
('Las Fiestas','Święta','la bebida','napój'),
('Las Fiestas','Święta','el vino','wino'),
('Las Fiestas','Święta','el champán','szampan'),
('Las Fiestas','Święta','alegre','radosny'),
('Las Fiestas','Święta','¡Felicidades!','Wszystkiego najlepszego! / Gratulacje!'),
('La Oficina','Biuro','la oficina','biuro'),
('La Oficina','Biuro','el escritorio','biurko'),
('La Oficina','Biuro','la silla','krzesło'),
('La Oficina','Biuro','el ordenador','komputer'),
('La Oficina','Biuro','el teclado','klawiatura'),
('La Oficina','Biuro','el ratón','myszka'),
('La Oficina','Biuro','la pantalla','ekran'),
('La Oficina','Biuro','el teléfono','telefon'),
('La Oficina','Biuro','la impresora','drukarka'),
('La Oficina','Biuro','el escáner','skaner'),
('La Oficina','Biuro','la fotocopiadora','kserokopiarka'),
('La Oficina','Biuro','el papel','papier'),
('La Oficina','Biuro','el documento','dokument'),
('La Oficina','Biuro','la carpeta','teczka / folder'),
('La Oficina','Biuro','el archivo','archiwum / segregator'),
('La Oficina','Biuro','el cajón','szuflada'),
('La Oficina','Biuro','el bolígrafo','długopis'),
('La Oficina','Biuro','el lápiz','ołówek'),
('La Oficina','Biuro','la grapadora','zszywacz'),
('La Oficina','Biuro','la grapa','zszywka'),
('La Oficina','Biuro','el clip','spinacz'),
('La Oficina','Biuro','el celo','taśma klejąca'),
('La Oficina','Biuro','las tijeras','nożyczki'),
('La Oficina','Biuro','el sobre','koperta'),
('La Oficina','Biuro','el sello','znaczek pocztowy'),
('La Oficina','Biuro','el correo','poczta'),
('La Oficina','Biuro','el correo electrónico','e-mail'),
('La Oficina','Biuro','la agenda','kalendarz (notatnik)'),
('La Oficina','Biuro','el calendario','kalendarz'),
('La Oficina','Biuro','la reunión','spotkanie / zebranie'),
('La Oficina','Biuro','la sala de reuniones','sala konferencyjna'),
('La Oficina','Biuro','el jefe','szef'),
('La Oficina','Biuro','el compañero de trabajo','kolega z pracy'),
('La Oficina','Biuro','el empleado','pracownik'),
('La Oficina','Biuro','el horario','godziny pracy / harmonogram'),
('La Oficina','Biuro','el descanso','przerwa'),
('La Oficina','Biuro','la cita','wizyta / spotkanie'),
('La Oficina','Biuro','el contrato','umowa'),
('La Oficina','Biuro','la firma','podpis'),
('La Oficina','Biuro','firmar','podpisywać'),
('La Oficina','Biuro','imprimir','drukować'),
('La Oficina','Biuro','fotocopiar','kserować'),
('La Oficina','Biuro','archivar','archiwizować'),
('La Oficina','Biuro','enviar','wysyłać'),
('La Oficina','Biuro','recibir','otrzymywać'),
('La Oficina','Biuro','el proyecto','projekt'),
('La Oficina','Biuro','la presentación','prezentacja'),
('La Oficina','Biuro','el informe','raport'),
('La Oficina','Biuro','el sello de caucho','pieczątka'),
('La Oficina','Biuro','la papelera','kosz na śmieci'),
('Negocios','Biznes','el negocio','biznes'),
('Negocios','Biznes','la empresa','firma / przedsiębiorstwo'),
('Negocios','Biznes','el empresario','przedsiębiorca'),
('Negocios','Biznes','el gerente','menedżer'),
('Negocios','Biznes','el director','dyrektor'),
('Negocios','Biznes','el cliente','klient'),
('Negocios','Biznes','el socio','wspólnik / partner'),
('Negocios','Biznes','el mercado','rynek'),
('Negocios','Biznes','la industria','przemysł'),
('Negocios','Biznes','el producto','produkt'),
('Negocios','Biznes','el servicio','usługa'),
('Negocios','Biznes','la marca','marka'),
('Negocios','Biznes','la competencia','konkurencja'),
('Negocios','Biznes','el competidor','konkurent'),
('Negocios','Biznes','el precio','cena'),
('Negocios','Biznes','el coste','koszt'),
('Negocios','Biznes','el presupuesto','budżet'),
('Negocios','Biznes','el ingreso','przychód'),
('Negocios','Biznes','el gasto','wydatek'),
('Negocios','Biznes','el beneficio','zysk'),
('Negocios','Biznes','la pérdida','strata'),
('Negocios','Biznes','la inversión','inwestycja'),
('Negocios','Biznes','el inversor','inwestor'),
('Negocios','Biznes','invertir','inwestować'),
('Negocios','Biznes','el capital','kapitał'),
('Negocios','Biznes','la acción','akcja (giełdowa)'),
('Negocios','Biznes','la bolsa','giełda'),
('Negocios','Biznes','el banco','bank'),
('Negocios','Biznes','el préstamo','pożyczka'),
('Negocios','Biznes','el crédito','kredyt'),
('Negocios','Biznes','la deuda','dług'),
('Negocios','Biznes','el contrato','kontrakt'),
('Negocios','Biznes','el acuerdo','porozumienie'),
('Negocios','Biznes','negociar','negocjować'),
('Negocios','Biznes','la negociación','negocjacje'),
('Negocios','Biznes','el éxito','sukces'),
('Negocios','Biznes','el fracaso','porażka'),
('Negocios','Biznes','quebrar','zbankrutować'),
('Negocios','Biznes','la bancarrota','bankructwo'),
('Negocios','Biznes','comprar','kupować'),
('Negocios','Biznes','vender','sprzedawać'),
('Negocios','Biznes','la venta','sprzedaż'),
('Negocios','Biznes','el marketing','marketing'),
('Negocios','Biznes','la publicidad','reklama'),
('Negocios','Biznes','el plan de negocio','biznesplan'),
('Negocios','Biznes','exportar','eksportować'),
('Negocios','Biznes','importar','importować'),
('Negocios','Biznes','la calidad','jakość'),
('Negocios','Biznes','el proveedor','dostawca'),
('Negocios','Biznes','la factura','faktura');
