insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Manualidades','Rękodzieło','el arte','sztuka'),
('Manualidades','Rękodzieło','la artesanía','rzemiosło'),
('Manualidades','Rękodzieło','crear','tworzyć'),
('Manualidades','Rękodzieło','hacer a mano','robić ręcznie'),
('Manualidades','Rękodzieło','el DIY (hazlo tú mismo)','zrób to sam (DIY)'),
('Manualidades','Rękodzieło','el papel','papier'),
('Manualidades','Rękodzieło','la cartulina','karton / brystol'),
('Manualidades','Rękodzieło','las tijeras','nożyczki'),
('Manualidades','Rękodzieło','el pegamento','klej'),
('Manualidades','Rękodzieło','la pistola de pegamento caliente','pistolet do kleju na gorąco'),
('Manualidades','Rękodzieło','la cinta adhesiva','taśma klejąca'),
('Manualidades','Rękodzieło','el hilo','nić'),
('Manualidades','Rękodzieło','la aguja','igła'),
('Manualidades','Rękodzieło','coser','szyć'),
('Manualidades','Rękodzieło','tejer','robić na drutach / szydełkować'),
('Manualidades','Rękodzieło','el ganchillo','szydełkowanie'),
('Manualidades','Rękodzieło','la lana','włóczka / wełna'),
('Manualidades','Rękodzieło','la tela','tkanina / materiał'),
('Manualidades','Rękodzieło','el fieltro','filc'),
('Manualidades','Rękodzieło','la arcilla','glina'),
('Manualidades','Rękodzieło','la porcelana fría','porcelana plastyczna / zimna'),
('Manualidades','Rękodzieło','la plastelina','plastelina'),
('Manualidades','Rękodzieło','pintar','malować'),
('Manualidades','Rękodzieło','el pincel','pędzel'),
('Manualidades','Rękodzieło','las pinturas','farby'),
('Manualidades','Rękodzieło','el abalorio','koralik'),
('Manualidades','Rękodzieło','la bisutería','biżuteria artystyczna'),
('Manualidades','Rękodzieło','el collar','naszyjnik'),
('Manualidades','Rękodzieło','la pulsera','bransoletka'),
('Manualidades','Rękodzieło','el papel de regalo','papier do pakowania prezentów'),
('Manualidades','Rękodzieło','la caja','pudełko'),
('Manualidades','Rękodzieło','decorar','dekorować'),
('Manualidades','Rękodzieło','la decoración','dekoracja'),
('Manualidades','Rękodzieło','reciclar','recyklingować (materiały do prac)'),
('Manualidades','Rękodzieło','el cartón','tektura'),
('Manualidades','Rękodzieło','la madera','drewno'),
('Manualidades','Rękodzieło','tallar','rzeźbić'),
('Manualidades','Rękodzieło','el pegamento de contacto','klej montażowy'),
('Manualidades','Rękodzieło','el patrón','wzór / szablon'),
('Manualidades','Rękodzieło','la aguja de coser','igła do szycia'),
('Manualidades','Rękodzieło','el dedal','naparstek'),
('Manualidades','Rękodzieło','el botón','guzik'),
('Manualidades','Rękodzieło','la cremallera','zamek błyskawiczny'),
('Manualidades','Rękodzieło','la lana de vidrio','wata szklana'),
('Manualidades','Rękodzieło','barnizar','lakierować'),
('Manualidades','Rękodzieło','lijar','szlifować'),
('Manualidades','Rękodzieło','el molde','forma / odlew'),
('Manualidades','Rękodzieło','original','oryginalny'),
('Manualidades','Rękodzieło','creativo','kreatywny'),
('Coleccionismo','Kolekcjonerstwo','el coleccionismo','kolekcjonerstwo'),
('Coleccionismo','Kolekcjonerstwo','el coleccionista','kolekcjoner'),
('Coleccionismo','Kolekcjonerstwo','la colección','kolekcja'),
('Coleccionismo','Kolekcjonerstwo','coleccionar','kolekcjonować'),
('Coleccionismo','Kolekcjonerstwo','el sello','znaczek pocztorski'),
('Coleccionismo','Kolekcjonerstwo','la filatelia','filatelistika'),
('Coleccionismo','Kolekcjonerstwo','la moneda','moneta'),
('Coleccionismo','Kolekcjonerstwo','la numismática','numizmatyka'),
('Coleccionismo','Kolekcjonerstwo','el billete','banknot'),
('Coleccionismo','Kolekcjonerstwo','la tarjeta postal','pocztówka'),
('Coleccionismo','Kolekcjonerstwo','el cromo','kolekcjonerska karta / naklejka'),
('Coleccionismo','Kolekcjonerstwo','el tebeo / el cómic','komiks'),
('Coleccionismo','Kolekcjonerstwo','el libro antiguo','stara książka / biały kruk'),
('Coleccionismo','Kolekcjonerstwo','el vinylo','płyta winylowa'),
('Coleccionismo','Kolekcjonerstwo','el CD','płyta CD'),
('Coleccionismo','Kolekcjonerstwo','el casete','kaseta magnetofonowa'),
('Coleccionismo','Kolekcjonerstwo','el juguete antiguo','stara zabawka'),
('Coleccionismo','Kolekcjonerstwo','la miniatura','miniatura'),
('Coleccionismo','Kolekcjonerstwo','el modelo a escala','model w skali'),
('Coleccionismo','Kolekcjonerstwo','la maqueta','makieta'),
('Coleccionismo','Kolekcjonerstwo','el coche de juguete','samochodzik'),
('Coleccionismo','Kolekcjonerstwo','el tren eléctrico','kolejka elektryczna'),
('Coleccionismo','Kolekcjonerstwo','la figura de acción','figurka akcji'),
('Coleccionismo','Kolekcjonerstwo','la piedra preciosa','kamień szlachetny'),
('Coleccionismo','Kolekcjonerstwo','el mineral','minerał'),
('Coleccionismo','Kolekcjonerstwo','el fósil','skamieniałość'),
('Coleccionismo','Kolekcjonerstwo','la concha','muszla'),
('Coleccionismo','Kolekcjonerstwo','la antigüedades','antyki'),
('Coleccionismo','Kolekcjonerstwo','el anticuario','antykwariusz / sklep z antykami'),
('Coleccionismo','Kolekcjonerstwo','el mercadillo','pchli targ'),
('Coleccionismo','Kolekcjonerstwo','la subasta','aukcja'),
('Coleccionismo','Kolekcjonerstwo','pujar','licytować'),
('Coleccionismo','Kolekcjonerstwo','el valor','wartość'),
('Coleccionismo','Kolekcjonerstwo','la rareza','rzadkość'),
('Coleccionismo','Kolekcjonerstwo','único','jedyny w swoim rodzaju / unikalny'),
('Coleccionismo','Kolekcjonerstwo','en perfecto estado','w idealnym stanie'),
('Coleccionismo','Kolekcjonerstwo','el catálogo','katalog'),
('Coleccionismo','Kolekcjonerstwo','exhibir','wystawiać / pokazywać'),
('Coleccionismo','Kolekcjonerstwo','la exposición','wystawa'),
('Coleccionismo','Kolekcjonerstwo','el museo','muzeum'),
('Coleccionismo','Kolekcjonerstwo','el tesoro','skarb'),
('Coleccionismo','Kolekcjonerstwo','encontrar','znaleźć'),
('Coleccionismo','Kolekcjonerstwo','descubrir','odkryć'),
('Coleccionismo','Kolekcjonerstwo','conservar','konserwować / zachować'),
('Coleccionismo','Kolekcjonerstwo','restaurar','odrestaurować'),
('Coleccionismo','Kolekcjonerstwo','la vitrina','gablota / witryna'),
('Coleccionismo','Kolekcjonerstwo','el estuche','etui / pudełko kolekcjonerskie'),
('Coleccionismo','Kolekcjonerstwo','la serie limitada','seria limitowana'),
('Coleccionismo','Kolekcjonerstwo','la reliquia','relikwia / pamiątka przeszłości'),
('Coleccionismo','Kolekcjonerstwo','apasionante','pasjonujący'),
('Bricolaje','Majsterkowanie','el bricolaje','majsterkowanie'),
('Bricolaje','Majsterkowanie','la herramienta','narzędzie'),
('Bricolaje','Majsterkowanie','el martillo','młotek'),
('Bricolaje','Majsterkowanie','el clavo','gwoźdź'),
('Bricolaje','Majsterkowanie','el tornillo','śruba / wkręt'),
('Bricolaje','Majsterkowanie','el destornillador','śrubokręt'),
('Bricolaje','Majsterkowanie','el taladro','wiertarka'),
('Bricolaje','Majsterkowanie','la broca','wiertło'),
('Bricolaje','Majsterkowanie','la sierra','piła'),
('Bricolaje','Majsterkowanie','el alicates','kleszcze / szczypce'),
('Bricolaje','Majsterkowanie','la llave inglesa','klucz nastawny'),
('Bricolaje','Majsterkowanie','el metro','miarka / taśma miernicza'),
('Bricolaje','Majsterkowanie','el nivel','poziomnica'),
('Bricolaje','Majsterkowanie','la lija','papier ścierny'),
('Bricolaje','Majsterkowanie','lijar','szlifować'),
('Bricolaje','Majsterkowanie','pintar','malować'),
('Bricolaje','Majsterkowanie','la brocha','pędzel malarski'),
('Bricolaje','Majsterkowanie','el rodillo','wałek malarski'),
('Bricolaje','Majsterkowanie','la pintura','farba'),
('Bricolaje','Majsterkowanie','el barniz','lakier'),
('Bricolaje','Majsterkowanie','barnizar','lakierować'),
('Bricolaje','Majsterkowanie','la madera','drewno'),
('Bricolaje','Majsterkowanie','el tablero','płyta / deska'),
('Bricolaje','Majsterkowanie','cortar','ciąć'),
('Bricolaje','Majsterkowanie','pegar','kleić'),
('Bricolaje','Majsterkowanie','el pegamento','klej'),
('Bricolaje','Majsterkowanie','la escalera','drabina'),
('Bricolaje','Majsterkowanie','la linterna','latarka'),
('Bricolaje','Majsterkowanie','el enchufe','gniazdko elektryczne'),
('Bricolaje','Majsterkowanie','el interruptor','włącznik światła'),
('Bricolaje','Majsterkowanie','el cable','kabel'),
('Bricolaje','Majsterkowanie','la bombilla','żarówka'),
('Bricolaje','Majsterkowanie','el grifo','kran'),
('Bricolaje','Majsterkowanie','la tubería','rura / instalacja wodna'),
('Bricolaje','Majsterkowanie','la fuga','wyciek'),
('Bricolaje','Majsterkowanie','reparar','naprawiać'),
('Bricolaje','Majsterkowanie','arreglar','naprawiać / porządkować'),
('Bricolaje','Majsterkowanie','instalar','instalować'),
('Bricolaje','Majsterkowanie','montar','składać / montować'),
('Bricolaje','Majsterkowanie','desmontar','demontować'),
('Bricolaje','Majsterkowanie','el taller','warsztat'),
('Bricolaje','Majsterkowanie','el banco de trabajo','warsztatowy stół roboczy'),
('Bricolaje','Majsterkowanie','el casco','kask ochronny'),
('Bricolaje','Majsterkowanie','las gafas de protección','okulary ochronne'),
('Bricolaje','Majsterkowanie','los guantes','rękawice ochronne'),
('Bricolaje','Majsterkowanie','el desván','poddasze'),
('Bricolaje','Majsterkowanie','el garaje','garaż'),
('Bricolaje','Majsterkowanie','la reforma','remont'),
('Bricolaje','Majsterkowanie','reformar','remontować'),
('Bricolaje','Majsterkowanie','el manitas','złota rączka / majsterkowicz'),
('Jardinería','Ogrodnictwo','la jardinería','ogrodnictwo'),
('Jardinería','Ogrodnictwo','el jardín','ogród'),
('Jardinería','Ogrodnictwo','el jardinero','ogrodnik'),
('Jardinería','Ogrodnictwo','la planta','roślina'),
('Jardinería','Ogrodnictwo','la flor','kwiat'),
('Jardinería','Ogrodnictwo','el árbol','drzewo'),
('Jardinería','Ogrodnictwo','el arbusto','krzew'),
('Jardinería','Ogrodnictwo','el césped','trawnik'),
('Jardinería','Ogrodnictwo','cortar el césped','kosić trawnik'),
('Jardinería','Ogrodnictwo','el cortacésped','kosiarka'),
('Jardinería','Ogrodnictwo','la tierra','ziemia / gleba'),
('Jardinería','Ogrodnictwo','el abono','nawóz'),
('Jardinería','Ogrodnictwo','abonar','nawozić'),
('Jardinería','Ogrodnictwo','regar','podlewać'),
('Jardinería','Ogrodnictwo','la regadera','konewka'),
('Jardinería','Ogrodnictwo','la manguera','wąż ogrodowy'),
('Jardinería','Ogrodnictwo','la maceta','doniczka'),
('Jardinería','Ogrodnictwo','el tiesto','doniczka / donica'),
('Jardinería','Ogrodnictwo','la semilla','nasiono'),
('Jardinería','Ogrodnictwo','sembrar','siać'),
('Jardinería','Ogrodnictwo','plantar','sadzić'),
('Jardinería','Ogrodnictwo','el bulbo','cebulka kwiatowa'),
('Jardinería','Ogrodnictwo','la azada','motyka'),
('Jardinería','Ogrodnictwo','la pala','łopata'),
('Jardinería','Ogrodnictwo','el rastrillo','grabie'),
('Jardinería','Ogrodnictwo','la carretilla','taczka'),
('Jardinería','Ogrodnictwo','las tijeras de podar','sekator'),
('Jardinería','Ogrodnictwo','podar','przycinać / podcinać'),
('Jardinería','Ogrodnictwo','las malas hierbas','chwisty'),
('Jardinería','Ogrodnictwo','quitar las malas hierbas','pielić'),
('Jardinería','Ogrodnictwo','la plaga','szkodnik / plaga'),
('Jardinería','Ogrodnictwo','el insecticida','insektycyd / środek owadobójczy'),
('Jardinería','Ogrodnictwo','el invernadero','szklarnia'),
('Jardinería','Ogrodnictwo','la pérgola','pergola'),
('Jardinería','Ogrodnictwo','el est】.co','oczko wodne'),
('Jardinería','Ogrodnictwo','la fuente','fontanna'),
('Jardinería','Ogrodnictwo','florecer','kwitnąć'),
('Jardinería','Ogrodnictwo','la floración','kwitnienie'),
('Jardinería','Ogrodnictwo','marchitarse','więdnąć'),
('Jardinería','Ogrodnictwo','las hojas','liście'),
('Jardinería','Ogrodnictwo','la raíz','korzeń'),
('Jardinería','Ogrodnictwo','el tallo','łodyga'),
('Jardinería','Ogrodnictwo','el abono orgánico','kompost / nawóz organiczny'),
('Jardinería','Ogrodnictwo','el mantillo','ściółka'),
('Jardinería','Ogrodnictwo','el paisajismo','architektura krajobrazu'),
('Jardinería','Ogrodnictwo','el diseño de jardines','projektowanie ogrodów'),
('Jardinería','Ogrodnictwo','la terraza','taras'),
('Jardinería','Ogrodnictwo','el balcón','balkon'),
('Jardinería','Ogrodnictwo','exótico','egzotyczny'),
('Jardinería','Ogrodnictwo','perenne','wiecznie zielony / wieloletni');
