insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Sociología','Socjologia','la sociología','socjologia'),
('Sociología','Socjologia','la sociedad','społeczeństwo'),
('Sociología','Socjologia','el grupo social','grupa społeczna'),
('Sociología','Socjologia','la comunidad','społeczność / wspólnota'),
('Sociología','Socjologia','la cultura','kultura'),
('Sociología','Socjologia','la norma','norma społeczna'),
('Sociología','Socjologia','el valor','wartość'),
('Sociología','Socjologia','la costumbre','obyczaj / zwyczaj'),
('Sociología','Socjologia','la tradición','tradycja'),
('Sociología','Socjologia','la clase social','klasa społeczna'),
('Sociología','Socjologia','la clase alta','klasa wyższa'),
('Sociología','Socjologia','la clase media','klasa średnia'),
('Sociología','Socjologia','la clase baja','klasa niższa'),
('Sociología','Socjologia','la estratificación','warstwowanie społeczne'),
('Sociología','Socjologia','la desigualdad','nierówność społeczna'),
('Sociología','Socjologia','la movilidad social','mobilność społeczna'),
('Sociología','Socjologia','la pobreza','ubóstwo'),
('Sociología','Socjologia','la riqueza','bogactwo'),
('Sociología','Socjologia','la marginación','marginalizacja'),
('Sociología','Socjologia','la exclusión social','wykluczenie społeczne'),
('Sociología','Socjologia','la integración','integracja'),
('Sociología','Socjologia','la asimilación','asymilacja'),
('Sociología','Socjologia','la inmigración','imigracja'),
('Sociología','Socjologia','la emigración','emigracja'),
('Sociología','Socjologia','el demografía','demografia'),
('Sociología','Socjologia','la población','populacja / ludność'),
('Sociología','Socjologia','el censo','spis powszechny'),
('Sociología','Socjologia','la natalidad','urodzenia / wskaźnik urodzeń'),
('Sociología','Socjologia','la mortalidad','śmiertelność'),
('Sociología','Socjologia','la urbanización','urbanizacja'),
('Sociología','Socjologia','el cambio social','zmiana społeczna'),
('Sociología','Socjologia','el conflicto social','konflikt społeczny'),
('Sociología','Socjologia','la interacción','interakcja'),
('Sociología','Socjologia','la socialización','socjalizacja'),
('Sociología','Socjologia','el rol social','rola społeczna'),
('Sociología','Socjologia','el estatus','status społeczny'),
('Sociología','Socjologia','la opinión pública','opinia publiczna'),
('Sociología','Socjologia','los medios de comunicación','media masowe'),
('Sociología','Socjologia','la globalización','globalizacja'),
('Sociología','Socjologia','la multiculturalidad','multikulturowość'),
('Sociología','Socjologia','el género','płeć społeczno-kulturowa (gender)'),
('Sociología','Socjologia','el feminismo','feminizm'),
('Sociología','Socjologia','el patriarcado','patriarchat'),
('Sociología','Socjologia','la familia','rodzina'),
('Sociología','Socjologia','el matrimonio','małżeństwo'),
('Sociología','Socjologia','el individuo','jednostka'),
('Sociología','Socjologia','la colectividad','zbiorowość'),
('Sociología','Socjologia','la red social','sieć społeczna'),
('Sociología','Socjologia','la burocracia','biurokracja'),
('Sociología','Socjologia','la institución','instytucja'),
('Geografía Política','Geografia polityczna','la geografía política','geografia polityczna'),
('Geografía Política','Geografia polityczna','el estado','państwo'),
('Geografía Política','Geografia polityczna','la nación','naród'),
('Geografía Política','Geografia polityczna','la frontera','granica'),
('Geografía Política','Geografia polityczna','el territorio','terytorium'),
('Geografía Política','Geografia polityczna','la soberanía','suwerenność'),
('Geografía Política','Geografia polityczna','el gobierno','rząd'),
('Geografía Política','Geografia polityczna','la capital','stolica'),
('Geografía Política','Geografia polityczna','la provincia','prowincja'),
('Geografía Política','Geografia polityczna','la región','region'),
('Geografía Política','Geografia polityczna','el municipio','gmina / miasto'),
('Geografía Política','Geografia polityczna','la autonomía','autonomia'),
('Geografía Política','Geografia polityczna','la federación','federacja'),
('Geografía Política','Geografia polityczna','el estado federal','państwo federacyjne'),
('Geografía Política','Geografia polityczna','la república','republika'),
('Geografía Política','Geografia polityczna','la monarquía','monarchia'),
('Geografía Política','Geografia polityczna','el imperio','imperium'),
('Geografía Política','Geografia polityczna','la colonia','kolonia'),
('Geografía Política','Geografia polityczna','el protectorado','protektorat'),
('Geografía Política','Geografia polityczna','el enclave','enklawa'),
('Geografía Política','Geografia polityczna','el exclave','eksklawa'),
('Geografía Política','Geografia polityczna','el conflicto fronterizo','konflikt graniczny'),
('Geografía Política','Geografia polityczna','la disputa territorial','spór terytorialny'),
('Geografía Política','Geografia polityczna','la geopolítica','geopolitika'),
('Geografía Política','Geografia polityczna','la influencia','wpływ / strefa wpływów'),
('Geografía Política','Geografia polityczna','la alianza','sojusz'),
('Geografía Política','Geografia polityczna','el tratado','traktat międzynarodowy'),
('Geografía Política','Geografia polityczna','la organización internacional','organizacja międzynarodowa'),
('Geografía Política','Geografia polityczna','la diplomacia','dyplomacja'),
('Geografía Política','Geografia polityczna','la embajada','ambasada'),
('Geografía Política','Geografia polityczna','el consulado','konsulat'),
('Geografía Política','Geografia polityczna','el embajador','ambasador'),
('Geografía Política','Geografia polityczna','el pasaporte','paszport'),
('Geografía Política','Geografia polityczna','el visado','wiza'),
('Geografía Política','Geografia polityczna','el control fronterizio','kontrola graniczna'),
('Geografía Política','Geografia polityczna','la independencia','niepodległość'),
('Geografía Política','Geografia polityczna','la secesja','secesja'),
('Geografía Política','Geografia polityczna','el referéndum','referendum'),
('Geografía Política','Geografia polityczna','el mapa político','mapa polityczna'),
('Geografía Política','Geografia polityczna','el hemisferio','półkula'),
('Geografía Política','Geografia polityczna','el bloque','blok (polityczny)'),
('Geografía Política','Geografia polityczna','la superpotencia','supermocarstwo'),
('Geografía Política','Geografia polityczna','el país en desarrollo','kraj rozwijający się'),
('Geografía Política','Geografia polityczna','el país desarrollado','kraj rozwinięty'),
('Geografía Política','Geografia polityczna','la descolonización','dekolonizacja'),
('Geografía Política','Geografia polityczna','la unificación','zjednoczenie'),
('Geografía Política','Geografia polityczna','la particja','podział / rozbiór'),
('Geografía Política','Geografia polityczna','la expansión','ekspansja'),
('Geografía Política','Geografia polityczna','la hegemonía','hegemonia'),
('Geografía Política','Geografia polityczna','la globalización','globalizacja'),
('Países y Nacionalidades','Kraje i narodowości','el país','kraj'),
('Países y Nacionalidades','Kraje i narodowości','la nacionalidad','narodowość'),
('Países y Nacionalidades','Kraje i narodowości','el extranjero','zagranica / obcokrajowiec'),
('Países y Nacionalidades','Kraje i narodowości','España','Hiszpania'),
('Países y Nacionalidades','Kraje i narodowości','español / española','hiszpański / hiszpanka'),
('Países y Nacionalidades','Kraje i narodowości','Polonia','Polska'),
('Países y Nacionalidades','Kraje i narodowości','polaco / polaca','polski / polka'),
('Países y Nacionalidades','Kraje i narodowości','México','Meksyk'),
('Países y Nacionalidades','Kraje i narodowości','mexicano / mexicana','meksykański / meksykanka'),
('Países y Nacionalidades','Kraje i narodowości','Argentina','Argentyna'),
('Países y Nacionalidades','Kraje i narodowości','argentino / argentina','argentyński / argentyntka'),
('Países y Nacionalidades','Kraje i narodowości','Colombia','Kolumbia'),
('Países y Nacionalidades','Kraje i narodowości','colombiano / colombiana','kolumbijski / kolumbijka'),
('Países y Nacionalidades','Kraje i narodowości','Estados Unidos','Stany Zjednoczone'),
('Países y Nacionalidades','Kraje i narodowości','estadounidense','amerykański / amerykańska'),
('Países y Nacionalidades','Kraje i narodowości','Francia','Francja'),
('Países y Nacionalidades','Kraje i narodowości','francés / francesa','francuski / francuzka'),
('Países y Nacionalidades','Kraje i narodowości','Alemania','Niemcy'),
('Países y Nacionalidades','Kraje i narodowości','alemán / alemana','niemiecki / niemka'),
('Países y Nacionalidades','Kraje i narodowości','Italia','Włochy'),
('Países y Nacionalidades','Kraje i narodowości','italiano / italiana','włoski / włoszka'),
('Países y Nacionalidades','Kraje i narodowości','Reino Unido','Wielka Brytania'),
('Países y Nacionalidades','Kraje i narodowości','británico / británica','brytyjski / brytyjka'),
('Países y Nacionalidades','Kraje i narodowości','China','Chiny'),
('Países y Nacionalidades','Kraje i narodowości','chino / china','chiński / Chinka'),
('Países y Nacionalidades','Kraje i narodowości','Japón','Japonia'),
('Países y Nacionalidades','Kraje i narodowości','japonés / japonesa','japoński / japonka'),
('Países y Nacionalidades','Kraje i narodowości','Brasil','Brazylia'),
('Países y Nacionalidades','Kraje i narodowości','brasileño / brasileña','brazylijski / brazylijka'),
('Países y Nacionalidades','Kraje i narodowości','Rusia','Rosja'),
('Países y Nacionalidades','Kraje i narodowości','ruso / rusa','rosyjski / rosjanka'),
('Países y Nacionalidades','Kraje i narodowości','Canadá','Kanada'),
('Países y Nacionalidades','Kraje i narodowości','canadiense','kanadyjski / kanadyjka'),
('Países y Nacionalidades','Kraje i narodowości','Australia','Australia'),
('Países y Nacionalidades','Kraje i narodowości','australiano / australiana','australijski / australijka'),
('Países y Nacionalidades','Kraje i narodowości','Egipto','Egipt'),
('Países y Nacionalidades','Kraje i narodowości','egipcio / egipcia','egipski / egipcjanka'),
('Países y Nacionalidades','Kraje i narodowości','India','Indie'),
('Países y Nacionalidades','Kraje i narodowości','indio / india','indyjski / indyjka'),
('Países y Nacionalidades','Kraje i narodowości','Grecia','Grecja'),
('Países y Nacionalidades','Kraje i narodowości','griego / griega','grecki / greczynka'),
('Países y Nacionalidades','Kraje i narodowości','Turquía','Turcja'),
('Países y Nacionalidades','Kraje i narodowości','turco / turca','turecki / turczynka'),
('Países y Nacionalidades','Kraje i narodowości','Portugal','Portugalia'),
('Países y Nacionalidades','Kraje i narodowości','portugués / portuguesa','portugalski / portugalka'),
('Países y Nacionalidades','Kraje i narodowości','Suecia','Szwecja'),
('Países y Nacionalidades','Kraje i narodowości','sueco / sueca','szwedzki / szwedka'),
('Países y Nacionalidades','Kraje i narodowości','Suiza','Szwajcaria'),
('Países y Nacionalidades','Kraje i narodowości','suizo / suiza','szwajcarski / szwajcarka'),
('Idiomas','Języki','el idioma','język'),
('Idiomas','Języki','la lengua','język (mowa)'),
('Idiomas','Języki','el español / el castellano','język hiszpanśki'),
('Idiomas','Języki','el polaco','język polski'),
('Idiomas','Języki','el inglés','język angielski'),
('Idiomas','Języki','el francés','język francuski'),
('Idiomas','Języki','el alemán','język niemiecki'),
('Idiomas','Języki','el italiano','język włoski'),
('Idiomas','Języki','el portugués','język portugalski'),
('Idiomas','Języki','el ruso','język rosyjski'),
('Idiomas','Języki','el chino','język chiński'),
('Idiomas','Języki','el japonés','język japoński'),
('Idiomas','Języki','el árabe','język arabski'),
('Idiomas','Języki','el hindi','język hindi'),
('Idiomas','Języki','el latín','łacina'),
('Idiomas','Języki','el griego','grecki'),
('Idiomas','Języki','la lengua materna','język ojczysty'),
('Idiomas','Języki','el idioma extranjero','język obcy'),
('Idiomas','Języki','bilingüe','dwujęzyczny'),
('Idiomas','Języki','multilingüe','wielojęzyczny'),
('Idiomas','Języki','la gramática','gramatyka'),
('Idiomas','Języki','el vocabulario','słownictwo'),
('Idiomas','Języki','la pronunciación','wymowa'),
('Idiomas','Języki','la ortografía','ortografia'),
('Idiomas','Języki','el acento','akcent'),
('Idiomas','Języki','el dialecto','dialekt'),
('Idiomas','Języki','la jerga','żargon / slang'),
('Idiomas','Języki','la traducción','tłumaczenie'),
('Idiomas','Języki','traducir','tłumaczyć'),
('Idiomas','Języki','el traductor','tłumacz'),
('Idiomas','Języki','el intérprete','tłumacz ustny'),
('Idiomas','Języki','aprender','uczyć się'),
('Idiomas','Języki','enseñar','uczyć / uczyć innych'),
('Idiomas','Języki','hablar','mówić'),
('Idiomas','Języki','entender','rozumieć'),
('Idiomas','Języki','escribir','pisać'),
('Idiomas','Języki','leer','czytać'),
('Idiomas','Języki','escuchar','słuchać'),
('Idiomas','Języki','la fluidez','płynność'),
('Idiomas','Języki','fluido','płynny'),
('Idiomas','Języki','el nivel','poziom'),
('Idiomas','Języki','el curso','kurs'),
('Idiomas','Języki','la academia','akademia / szkoła językowa'),
('Idiomas','Języki','el intercambio','wymiana (językowa)'),
('Idiomas','Języki','la competencia','kompetencja'),
('Idiomas','Języki','la comunicación','komunikacja'),
('Idiomas','Języki','expresarse','wyrażać się'),
('Idiomas','Języki','la palabra','słowo'),
('Idiomas','Języki','la frase','zdanie'),
('Idiomas','Języki','el significado','znaczenie'),
('Continentes y Océanos','Kontynenty i oceany','el continente','kontynent');
