insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Expresiones de Cortesía','Zwroty grzecznościowe','por favor','proszę (prosząc)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','gracias','dziękuję'),
('Expresiones de Cortesía','Zwroty grzecznościowe','muchas gracias','bardzo dziękuję'),
('Expresiones de Cortesía','Zwroty grzecznościowe','muchísimas gracias','stokrotnie dziękuję'),
('Expresiones de Cortesía','Zwroty grzecznościowe','de nada','nie ma za co'),
('Expresiones de Cortesía','Zwroty grzecznościowe','no hay de qué','nie ma o co (nie ma za co)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','perdón','przepraszam'),
('Expresiones de Cortesía','Zwroty grzecznościowe','perdone','przepraszam (Pana/Panią)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','perdona','przepraszam (cię)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','lo siento','przykro mi / przepraszam'),
('Expresiones de Cortesía','Zwroty grzecznościowe','disculpe','przepraszam (Pana/Panią - zwrócenie uwagi)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','disculpa','przepraszam (cię - zwrócenie uwagi)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','con permiso','za pozwoleniem (przechodząc)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','pase','proszę wejść / przejść'),
('Expresiones de Cortesía','Zwroty grzecznościowe','adelante','proszę wejść / naprzód'),
('Expresiones de Cortesía','Zwroty grzecznościowe','buen provecho','smacznego'),
('Expresiones de Cortesía','Zwroty grzecznościowe','que aproveche','smacznego'),
('Expresiones de Cortesía','Zwroty grzecznościowe','salud','na zdrowie (kichnięcie / toast)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','Jesús','na zdrowie (po kichnięciu)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','bienvenido','witaj / mile widziany'),
('Expresiones de Cortesía','Zwroty grzecznościowe','encantado','miło mi (mówi mężczyzna)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','encantada','miło mi (mówi kobieta)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','mucho gusto','bardzo mi miło'),
('Expresiones de Cortesía','Zwroty grzecznościowe','el gusto es mío','cała przyjemność po mojej stronie'),
('Expresiones de Cortesía','Zwroty grzecznościowe','igualmente','nawzajem'),
('Expresiones de Cortesía','Zwroty grzecznościowe','felicidades','gratulacje / wszystkiego najlepszego'),
('Expresiones de Cortesía','Zwroty grzecznościowe','enhorabuena','gratulacje'),
('Expresiones de Cortesía','Zwroty grzecznościowe','feliz cumpleaños','wszystkiego najlepszego z okazji urodzin'),
('Expresiones de Cortesía','Zwroty grzecznościowe','buen viaje','miłej podróży'),
('Expresiones de Cortesía','Zwroty grzecznościowe','felices fiestas','wesołych świąt'),
('Expresiones de Cortesía','Zwroty grzecznościowe','que te mejores','wracaj do zdrowia'),
('Expresiones de Cortesía','Zwroty grzecznościowe','buena suerte','powdzenia'),
('Expresiones de Cortesía','Zwroty grzecznościowe','¡ánimo!','głowa do góry! / śmiało!'),
('Expresiones de Cortesía','Zwroty grzecznościowe','cuidado','ostrożnie / uwaga'),
('Expresiones de Cortesía','Zwroty grzecznościowe','no se preocupe','proszę się nie martwić'),
('Expresiones de Cortesía','Zwroty grzecznościowe','no te preocupes','nie martw się'),
('Expresiones de Cortesía','Zwroty grzecznościowe','¿puedo ayudarle?','w czym mogę pomóc?'),
('Expresiones de Cortesía','Zwroty grzecznościowe','a su servicio','do usług'),
('Expresiones de Cortesía','Zwroty grzecznościowe','es muy amable','to bardzo miłe (z Pana/Pani strony)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','gracias por su ayuda','dziękuję za pomoc'),
('Expresiones de Cortesía','Zwroty grzecznościowe','un placer','przyjemność (po mojej stronie)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','buen fin de semana','miłego weekendu'),
('Expresiones de Cortesía','Zwroty grzecznościowe','buen día','miłego dnia'),
('Expresiones de Cortesía','Zwroty grzecznościowe','que le vaya bien','powodzenia (niech się Panu dobrze wiedzie)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','que te vaya bien','powodzenia (niech ci się dobrze wiedzie)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','a ti','tobie również (w odpowiedzi na podziękowanie)'),
('Expresiones de Cortesía','Zwroty grzecznościowe','a usted','Panu/Pani również'),
('Expresiones de Cortesía','Zwroty grzecznościowe','claro','jasne / oczywiście'),
('Expresiones de Cortesía','Zwroty grzecznościowe','por supuesto','oczywiście'),
('Expresiones de Cortesía','Zwroty grzecznościowe','desde luego','oczywiście / jak najbardziej'),
('Saludos y Despedidas','Powitania i pożegnania','hola','cześć (powitanie)'),
('Saludos y Despedidas','Powitania i pożegnania','adiós','do widzenia'),
('Saludos y Despedidas','Powitania i pożegnania','buenos días','dzień dobry (rano)'),
('Saludos y Despedidas','Powitania i pożegnania','buenas tardes','dzień dobry (po południu)'),
('Saludos y Despedidas','Powitania i pożegnania','buenas noches','dobry wieczór / dobranoc'),
('Saludos y Despedidas','Powitania i pożegnania','hasta luego','do zobaczenia (później)'),
('Saludos y Despedidas','Powitania i pożegnania','hasta pronto','do zobaczenia wkrótce'),
('Saludos y Despedidas','Powitania i pożegnania','hasta mañana','do jutra'),
('Saludos y Despedidas','Powitania i pożegnania','hasta la vista','do zobaczenia'),
('Saludos y Despedidas','Powitania i pożegnania','hasta ahora','na razie / do zobaczenia za chwilę'),
('Saludos y Despedidas','Powitania i pożegnania','nos vemos','widzimy się / do zobaczenia'),
('Saludos y Despedidas','Powitania i pożegnania','chao / chau','cześć (pożegnanie)'),
('Saludos y Despedidas','Powitania i pożegnania','qué tal','jak tam? / co słychać?'),
('Saludos y Despedidas','Powitania i pożegnania','cómo estás','jak się masz?'),
('Saludos y Despedidas','Powitania i pożegnania','cómo está','jak się Pan/Pani ma?'),
('Saludos y Despedidas','Powitania i pożegnania','cómo te va','jak ci leci?'),
('Saludos y Despedidas','Powitania i pożegnania','qué pasa','co słychać? / co się dzieje?'),
('Saludos y Despedidas','Powitania i pożegnania','qué hay','co słychać?'),
('Saludos y Despedidas','Powitania i pożegnania','qué cuentas','co powiesz? / co słychać?'),
('Saludos y Despedidas','Powitania i pożegnania','bien','dobrze'),
('Saludos y Despedidas','Powitania i pożegnania','muy bien','bardzo dobrze'),
('Saludos y Despedidas','Powitania i pożegnania','mal','źle'),
('Saludos y Despedidas','Powitania i pożegnania','regular','tak sobie'),
('Saludos y Despedidas','Powitania i pożegnania','tirando','jakoś leci'),
('Saludos y Despedidas','Powitania i pożegnania','todo bien','wszystko dobrze'),
('Saludos y Despedidas','Powitania i pożegnania','y tú','a ty?'),
('Saludos y Despedidas','Powitania i pożegnania','y usted','a Pan/Pani?'),
('Saludos y Despedidas','Powitania i pożegnania','saludos','pozdrowienia'),
('Saludos y Despedidas','Powitania i pożegnania','recuerdos a','pozdrowienia dla'),
('Saludos y Despedidas','Powitania i pożegnania','un abrazo','uściski (dosł. uścisk)'),
('Saludos y Despedidas','Powitania i pożegnania','un beso','buziak (dosł. pocałunek)'),
('Saludos y Despedidas','Powitania i pożegnania','besos','buziaki'),
('Saludos y Despedidas','Powitania i pożegnania','cuidaros','trzymajcie się'),
('Saludos y Despedidas','Powitania i pożegnania','cuídate','trzymaj się'),
('Saludos y Despedidas','Powitania i pożegnania','cuídese','niech Pan/Pani trzyma się'),
('Saludos y Despedidas','Powitania i pożegnania','buenas','dzień dobry / cześć (potocznie)'),
('Saludos y Despedidas','Powitania i pożegnania','hasta la próxima','do następnego razu'),
('Saludos y Despedidas','Powitania i pożegnania','hasta siempre','żegnaj na zawsze'),
('Saludos y Despedidas','Powitania i pożegnania','bienvenido','witaj (do mężczyzny)'),
('Saludos y Despedidas','Powitania i pożegnania','bienvenida','witaj (do kobiety)'),
('Saludos y Despedidas','Powitania i pożegnania','bienvenidos','witajcie (l.mn.)'),
('Saludos y Despedidas','Powitania i pożegnania','pase','proszę wejść'),
('Saludos y Despedidas','Powitania i pożegnania','qué alegría verte','jak miło cię widzieć'),
('Saludos y Despedidas','Powitania i pożegnania','cuánto tiempo','kopę lat / ile to czasu'),
('Saludos y Despedidas','Powitania i pożegnania','hace mucho que no nos vemos','dawno się nie widzieliśmy'),
('Saludos y Despedidas','Powitania i pożegnania','me alegro de verte','cieszę się, że cię widzę'),
('Saludos y Despedidas','Powitania i pożegnania','que tengas un buen día','miłego dnia'),
('Saludos y Despedidas','Powitania i pożegnania','feliz día','szczęśliwego dnia'),
('Saludos y Despedidas','Powitania i pożegnania','despidirse','żegnać się'),
('Saludos y Despedidas','Powitania i pożegnania','saludar','witać / pozdrawiać'),
('La Infancia','Dzieciństwo','la infancia','dzieciństwo'),
('La Infancia','Dzieciństwo','el niño','chłopiec / dziecko'),
('La Infancia','Dzieciństwo','la niña','dziewczynka'),
('La Infancia','Dzieciństwo','el bebé','niemowlę'),
('La Infancia','Dzieciństwo','el recién nacido','noworodek'),
('La Infancia','Dzieciństwo','el chupete','smoczek'),
('La Infancia','Dzieciństwo','el biberón','butelka ze smoczkiem'),
('La Infancia','Dzieciństwo','el pañal','pielucha'),
('La Infancia','Dzieciństwo','la cuna','łóżeczko dziecięce'),
('La Infancia','Dzieciństwo','el cochecito','wózek dziecięcy'),
('La Infancia','Dzieciństwo','el juguete','zabawka'),
('La Infancia','Dzieciństwo','el peluche','pluszak'),
('La Infancia','Dzieciństwo','el muñeco','lalka / figurka'),
('La Infancia','Dzieciństwo','la muñeca','lalka (zabawka)'),
('La Infancia','Dzieciństwo','el sonajero','grzechotka'),
('La Infancia','Dzieciństwo','el cuento','bajka / opowiadanie'),
('La Infancia','Dzieciństwo','gatear','raczkować'),
('La Infancia','Dzieciństwo','llorar','płakać'),
('La Infancia','Dzieciństwo','reír','śmiać się'),
('La Infancia','Dzieciństwo','sonreír','uśmiechać się'),
('La Infancia','Dzieciństwo','jugar','bawić się / grać'),
('La Infancia','Dzieciństwo','crecer','rosnąć'),
('La Infancia','Dzieciństwo','nacer','urodzić się'),
('La Infancia','Dzieciństwo','dar a luz','urodzić (wydać na świat)'),
('La Infancia','Dzieciństwo','el embarazo','ciąża'),
('La Infancia','Dzieciństwo','embarazada','w ciąży'),
('La Infancia','Dzieciństwo','la guardería','żłobek / przedszkole'),
('La Infancia','Dzieciństwo','el colegio','szkoła (podstawowa)'),
('La Infancia','Dzieciństwo','la niñera','niania'),
('La Infancia','Dzieciństwo','el patio de recreo','plac zabaw'),
('La Infancia','Dzieciństwo','el columpio','huśtawka'),
('La Infancia','Dzieciństwo','el tobogán','zjeżdżalnia'),
('La Infancia','Dzieciństwo','el arenero','piaskownica'),
('La Infancia','Dzieciństwo','el escondite','chowanego'),
('La Infancia','Dzieciństwo','travieso','niegrzeczny / psotny'),
('La Infancia','Dzieciństwo','obediente','posłuszny'),
('La Infancia','Dzieciństwo','desobediente','nieposłuszny'),
('La Infancia','Dzieciństwo','castigar','karać'),
('La Infancia','Dzieciństwo','el castigo','kara'),
('La Infancia','Dzieciństwo','portarse bien','zachowywać się dobrze'),
('La Infancia','Dzieciństwo','portarse mal','zachowywać się źle'),
('La Infancia','Dzieciństwo','mimar','rozpieszczać'),
('La Infancia','Dzieciństwo','el mimo','pieszczota'),
('La Infancia','Dzieciństwo','abrazar','przytulać'),
('La Infancia','Dzieciństwo','el abrazo','uścisk / przytulenie'),
('La Infancia','Dzieciństwo','la inocencia','niewinność'),
('La Infancia','Dzieciństwo','el huérfano','sierota'),
('La Infancia','Dzieciństwo','la nana','kołysanka'),
('La Infancia','Dzieciństwo','el parque infantil','plac zabaw (park)'),
('La Infancia','Dzieciństwo','amamantar','karmić piersią'),
('La Vejez','Starość','la vejez','starość'),
('La Vejez','Starość','el anciano','starzec / starszy pan'),
('La Vejez','Starość','la anciana','starsza pani'),
('La Vejez','Starość','mayor','starszy'),
('La Vejez','Starość','el abuelo','dziadek'),
('La Vejez','Starość','la abuela','babcia'),
('La Vejez','Starość','los abuelos','dziadkowie'),
('La Vejez','Starość','envejecer','starzeć się'),
('La Vejez','Starość','la arruga','zmarszczka'),
('La Vejez','Starość','arrugado','pomarszczony'),
('La Vejez','Starość','la cana','siwy włos'),
('La Vejez','Starość','canoso','siwy'),
('La Vejez','Starość','calvo','łysy'),
('La Vejez','Starość','la pensión','emerytura (pieniądze)'),
('La Vejez','Starość','la jubilación','emerytura (stan)'),
('La Vejez','Starość','jubilarse','przejść na emeryturę'),
('La Vejez','Starość','el jubilado','emeryt'),
('La Vejez','Starość','el bastón','laska'),
('La Vejez','Starość','la silla de ruedas','wózek inwalidzki'),
('La Vejez','Starość','las gafas','okulary'),
('La Vejez','Starość','el audífono','aparat słuchowy'),
('La Vejez','Starość','la dentadura postiza','sztuczna szczęka'),
('La Vejez','Starość','la residencia de ancianos','dom spokojnej starości'),
('La Vejez','Starość','el asilo','przytułek'),
('La Vejez','Starość','cuidar','opiekować się'),
('La Vejez','Starość','el cuidador','opiekun'),
('La Vejez','Starość','la sabiduría','mądrość'),
('La Vejez','Starość','sabio','mądry'),
('La Vejez','Starość','la experiencia','doświadczenie'),
('La Vejez','Starość','la memoria','pamięć'),
('La Vejez','Starość','olvidar','zapominać'),
('La Vejez','Starość','la enfermedad','choroba'),
('La Vejez','Starość','sordo','głuchy'),
('La Vejez','Starość','ciego','ślepy / niewidomy'),
('La Vejez','Starość','la soledad','samotność'),
('La Vejez','Starość','solitario','samotny'),
('La Vejez','Starość','el respeto','szacunek'),
('La Vejez','Starość','respetar','szanować'),
('La Vejez','Starość','la generación','pokolenie'),
('La Vejez','Starość','el nieto','wnuk'),
('La Vejez','Starość','la nieta','wnuczka'),
('La Vejez','Starość','la esperanza de vida','długość życia'),
('La Vejez','Starość','longevo','długowieczny'),
('La Vejez','Starość','frágil','kruchy'),
('La Vejez','Starość','la salud','zdrowie'),
('La Vejez','Starość','la edad','wiek'),
('La Vejez','Starość','cumplir años','kończyć lata / mieć urodziny'),
('La Vejez','Starość','el testamento','testament'),
('La Vejez','Starość','la herencia','spadek'),
('La Vejez','Starość','viudo','wdowiec');
