insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Preposiciones','Przyimki','a','do / na / w (kierunek, czas)'),
('Preposiciones','Przyimki','ante','wobec / przed (np. sądem)'),
('Preposiciones','Przyimki','bajo','pod'),
('Preposiciones','Przyimki','cabe','obok (archaiczne)'),
('Preposiciones','Przyimki','con','z'),
('Preposiciones','Przyimki','contra','przeciw / przeciwko'),
('Preposiciones','Przyimki','de','z / od / o (kogoś/czegoś)'),
('Preposiciones','Przyimki','desde','od (czas/miejsce)'),
('Preposiciones','Przyimki','durante','podczas'),
('Preposiciones','Przyimki','en','w / na'),
('Preposiciones','Przyimki','entre','między / pomiędzy'),
('Preposiciones','Przyimki','hacia','w kierunku / ku'),
('Preposiciones','Przyimki','hasta','do / aż do'),
('Preposiciones','Przyimki','mediante','za pomocą / poprzez'),
('Preposiciones','Przyimki','para','dla / żeby'),
('Preposiciones','Przyimki','por','przez / za / dla'),
('Preposiciones','Przyimki','según','według / zgodnie z'),
('Preposiciones','Przyimki','sin','bez'),
('Preposiciones','Przyimki','so','pod (archaiczne)'),
('Preposiciones','Przyimki','sobre','na / o (temat)'),
('Preposiciones','Przyimki','tras','za / po'),
('Preposiciones','Przyimki','versus','kontra / przeciwko'),
('Preposiciones','Przyimki','vía','przez (trasę)'),
('Preposiciones','Przyimki','acerca de','na temat / o'),
('Preposiciones','Przyimki','además de','oprócz'),
('Preposiciones','Przyimki','alrededor de','wokół'),
('Preposiciones','Przyimki','antes de','przed (czas)'),
('Preposiciones','Przyimki','a pesar de','pomimo'),
('Preposiciones','Przyimki','cerca de','blisko'),
('Preposiciones','Przyimki','con respecto a','w odniesieniu do'),
('Preposiciones','Przyimki','debajo de','pod (pod spodem)'),
('Preposiciones','Przyimki','delante de','przed (miejsce)'),
('Preposiciones','Przyimki','dentro de','wewnątrz / w (czas)'),
('Preposiciones','Przyimki','después de','po (czas)'),
('Preposiciones','Przyimki','detrás de','za (miejsce)'),
('Preposiciones','Przyimki','en contra de','przeciwko'),
('Preposiciones','Przyimki','en medio de','w środku / pomiędzy'),
('Preposiciones','Przyimki','en lugar de','zamiast'),
('Preposiciones','Przyimki','en vez de','zamiast'),
('Preposiciones','Przyimki','encima de','nad / na'),
('Preposiciones','Przyimki','frente a','naprzeciwko / wobec'),
('Preposiciones','Przyimki','fuera de','poza'),
('Preposiciones','Przyimki','gracias a','dzięki'),
('Preposiciones','Przyimki','junto a','obok'),
('Preposiciones','Przyimki','lejos de','daleko od'),
('Preposiciones','Przyimki','por causa de','z powodu'),
('Preposiciones','Przyimki','por culpa de','przez (z winy)'),
('Preposiciones','Przyimki','a través de','poprzez'),
('Preposiciones','Przyimki','con el fin de','w celu'),
('Preposiciones','Przyimki','a favor de','na rzecz / za'),
('Conjunciones','Spójniki','y','i / oraz'),
('Conjunciones','Spójniki','e','i / oraz (przed wyrazem na i/hi)'),
('Conjunciones','Spójniki','ni','ani'),
('Conjunciones','Spójniki','que','że / który'),
('Conjunciones','Spójniki','o','albo / lub'),
('Conjunciones','Spójniki','u','albo / lub (przed wyrazem na o/ho)'),
('Conjunciones','Spójniki','pero','ale'),
('Conjunciones','Spójniki','mas','lecz / ale (literackie)'),
('Conjunciones','Spójniki','sino','lecz (po przeczeniu)'),
('Conjunciones','Spójniki','porque','ponieważ / bo'),
('Conjunciones','Spójniki','pues','zatem / bo'),
('Conjunciones','Spójniki','ya que','skoro / jako że'),
('Conjunciones','Spójniki','puesto que','ponieważ / skoro'),
('Conjunciones','Spójniki','dado que','zważywszy że'),
('Conjunciones','Spójniki','como','jako / ponieważ / jak'),
('Conjunciones','Spójniki','si','jeśli / czy'),
('Conjunciones','Spójniki','siempre que','zawsze gdy / pod warunkiem że'),
('Conjunciones','Spójniki','con tal (de) que','pod warunkiem że'),
('Conjunciones','Spójniki','a condición de que','pod warunkiem że'),
('Conjunciones','Spójniki','aunque','chociaż / mimo że'),
('Conjunciones','Spójniki','a pesar de que','pomimo że'),
('Conjunciones','Spójniki','aun cuando','nawet jeśli'),
('Conjunciones','Spójniki','por más que','nie ważne jak / chociaż'),
('Conjunciones','Spójniki','para que','aby / żeby'),
('Conjunciones','Spójniki','a fin de que','w tym celu żeby'),
('Conjunciones','Spójniki','luego','więc / toteż'),
('Conjunciones','Spójniki','conque','a więc / wobec tego'),
('Conjunciones','Spójniki','así que','więc / tak więc'),
('Conjunciones','Spójniki','por lo tanto','dlatego też'),
('Conjunciones','Spójniki','por consiguiente','w konsekwencji'),
('Conjunciones','Spójniki','sea... sea','czy to... czy to'),
('Conjunciones','Spójniki','ya... ya','raz... raz'),
('Conjunciones','Spójniki','bien... bien','albo... albo'),
('Conjunciones','Spójniki','mientras','podczas gdy'),
('Conjunciones','Spójniki','cuando','kiedy / gdy'),
('Conjunciones','Spójniki','antes de que','zanim'),
('Conjunciones','Spójniki','después de que','po tym jak'),
('Conjunciones','Spójniki','hasta que','aż / dopóki no'),
('Conjunciones','Spójniki','desde que','odkąd'),
('Conjunciones','Spójniki','luego que','skoro tylko'),
('Conjunciones','Spójniki','tan pronto como','jak tylko'),
('Conjunciones','Spójniki','apenas','zaledwie'),
('Conjunciones','Spójniki','es decir','to znaczy'),
('Conjunciones','Spójniki','o sea','czyli / to znaczy'),
('Conjunciones','Spójniki','esto es','to jest'),
('Conjunciones','Spójniki','sin embargo','jednakże / mimo to'),
('Conjunciones','Spójniki','no obstante','niemniej jednak'),
('Conjunciones','Spójniki','salvo','z wyjątkiem'),
('Conjunciones','Spójniki','excepto','oprócz / wyjąwszy'),
('Conjunciones','Spójniki','además','ponadto'),
('Pronombres','Zaimki','yo','ja'),
('Pronombres','Zaimki','tú','ty'),
('Pronombres','Zaimki','él','on'),
('Pronombres','Zaimki','ella','ona'),
('Pronombres','Zaimki','usted','pan / pani'),
('Pronombres','Zaimki','nosotros','my (mężczyźni/mieszane)'),
('Pronombres','Zaimki','nosotras','my (kobiety)'),
('Pronombres','Zaimki','vosotros','wy (mężczyźni/mieszane - Hiszpania)'),
('Pronombres','Zaimki','vosotras','wy (kobiety - Hiszpania)'),
('Pronombres','Zaimki','ellos','oni'),
('Pronombres','Zaimki','ellas','one'),
('Pronombres','Zaimki','ustedes','państwo (wy)'),
('Pronombres','Zaimki','me','mi / mnie'),
('Pronombres','Zaimki','te','ci / ciebie'),
('Pronombres','Zaimki','le','jemu / jej / panu (celownik)'),
('Pronombres','Zaimki','lo','go / jego / to (biernik)'),
('Pronombres','Zaimki','la','ją (biernik)'),
('Pronombres','Zaimki','nos','nam / nas'),
('Pronombres','Zaimki','os','wam / was'),
('Pronombres','Zaimki','les','im / państwu (celownik)'),
('Pronombres','Zaimki','los','ich (biernik r.m.)'),
('Pronombres','Zaimki','las','je (biernik r.ż.)'),
('Pronombres','Zaimki','se','się / sobie'),
('Pronombres','Zaimki','mí','mnie (po przyimku)'),
('Pronombres','Zaimki','ti','tobie (po przyimku)'),
('Pronombres','Zaimki','sí','sobie / nim (po przyimku)'),
('Pronombres','Zaimki','conmigo','ze mną'),
('Pronombres','Zaimki','contigo','z tobą'),
('Pronombres','Zaimki','consigo','z nim / ze sobą'),
('Pronombres','Zaimki','mío / mía','mój / moja'),
('Pronombres','Zaimki','tuyo / tuya','twój / twoja'),
('Pronombres','Zaimki','suyo / suya','jego / jej / ich'),
('Pronombres','Zaimki','nuestro / nuestra','nasz / nasza'),
('Pronombres','Zaimki','vuestro / vuestra','wasz / wasza'),
('Pronombres','Zaimki','este','ten'),
('Pronombres','Zaimki','esta','ta'),
('Pronombres','Zaimki','esto','to'),
('Pronombres','Zaimki','ese','tamten'),
('Pronombres','Zaimki','esa','tamta'),
('Pronombres','Zaimki','eso','tamto'),
('Pronombres','Zaimki','aquel','ów (daleki)'),
('Pronombres','Zaimki','aquella','owa (daleka)'),
('Pronombres','Zaimki','aquello','owo (dalekie)'),
('Pronombres','Zaimki','quien','kto / ten, kto'),
('Pronombres','Zaimki','quienes','którzy / ci, którzy'),
('Pronombres','Zaimki','que','który / co'),
('Pronombres','Zaimki','cual','który / jaki'),
('Pronombres','Zaimki','cuales','które / jacy'),
('Pronombres','Zaimki','alguien','ktoś'),
('Pronombres','Zaimki','nadie','nikt'),
('Verbos Regulares AR','Czasowniki regularne AR','hablar','mówić / rozmawiać'),
('Verbos Regulares AR','Czasowniki regularne AR','trabajar','pracować'),
('Verbos Regulares AR','Czasowniki regularne AR','estudiar','uczyć się / studiować'),
('Verbos Regulares AR','Czasowniki regularne AR','amar','kochać'),
('Verbos Regulares AR','Czasowniki regularne AR','viajar','podróżować'),
('Verbos Regulares AR','Czasowniki regularne AR','cantar','śpiewać'),
('Verbos Regulares AR','Czasowniki regularne AR','bailar','tańczyć'),
('Verbos Regulares AR','Czasowniki regularne AR','escuchar','słuchać'),
('Verbos Regulares AR','Czasowniki regularne AR','mirar','patrzeć'),
('Verbos Regulares AR','Czasowniki regularne AR','comprar','kupować'),
('Verbos Regulares AR','Czasowniki regularne AR','pagar','płacić'),
('Verbos Regulares AR','Czasowniki regularne AR','tomar','brać / pić'),
('Verbos Regulares AR','Czasowniki regularne AR','llevar','nieść / nosić'),
('Verbos Regulares AR','Czasowniki regularne AR','dejar','zostawiać / pozwalać'),
('Verbos Regulares AR','Czasowniki regularne AR','ayudar','pomagać'),
('Verbos Regulares AR','Czasowniki regularne AR','preparar','przygotowywać'),
('Verbos Regulares AR','Czasowniki regularne AR','cocinar','gotować'),
('Verbos Regulares AR','Czasowniki regularne AR','entrar','wchodzić'),
('Verbos Regulares AR','Czasowniki regularne AR','llegar','przybierać / docierać'),
('Verbos Regulares AR','Czasowniki regularne AR','pasar','spędzać / mijać'),
('Verbos Regulares AR','Czasowniki regularne AR','mandar','wysyłać / rozkazywać'),
('Verbos Regulares AR','Czasowniki regularne AR','preguntar','pytać'),
('Verbos Regulares AR','Czasowniki regularne AR','contestar','odpowiadać'),
('Verbos Regulares AR','Czasowniki regularne AR','necesitar','potrzebować'),
('Verbos Regulares AR','Czasowniki regularne AR','usar','używać'),
('Verbos Regulares AR','Czasowniki regularne AR','explicar','wyjaśniać'),
('Verbos Regulares AR','Czasowniki regularne AR','ganar','wygrywać / zarabiać'),
('Verbos Regulares AR','Czasowniki regularne AR','llorar','płakać'),
('Verbos Regulares AR','Czasowniki regularne AR','nadar','pływać'),
('Verbos Regulares AR','Czasowniki regularne AR','caminar','spacerować / chodzić'),
('Verbos Regulares AR','Czasowniki regularne AR','descansar','odpoczywać'),
('Verbos Regulares AR','Czasowniki regularne AR','terminar','kończyć'),
('Verbos Regulares AR','Czasowniki regularne AR','olvidar','zapominać'),
('Verbos Regulares AR','Czasowniki regularne AR','pintar','malować'),
('Verbos Regulares AR','Czasowniki regularne AR','limpiar','sprzątać / czyścić'),
('Verbos Regulares AR','Czasowniki regularne AR','lavar','myć / prać'),
('Verbos Regulares AR','Czasowniki regularne AR','desayunar','jeść śniadanie'),
('Verbos Regulares AR','Czasowniki regularne AR','cenar','jeść kolację'),
('Verbos Regulares AR','Czasowniki regularne AR','saludar','pozdrawiać / witać'),
('Verbos Regulares AR','Czasowniki regularne AR','invitar','zapraszać'),
('Verbos Regulares AR','Czasowniki regularne AR','arreglar','naprawiać / porządkować'),
('Verbos Regulares AR','Czasowniki regularne AR','buscar','szukać'),
('Verbos Regulares AR','Czasowniki regularne AR','aceptar','akceptować / przyjmować'),
('Verbos Regulares AR','Czasowniki regularne AR','acompañar','towarzyszyć'),
('Verbos Regulares AR','Czasowniki regularne AR','esperar','czekać / mieć nadzieję'),
('Verbos Regulares AR','Czasowniki regularne AR','llamar','dzwonić / wołać'),
('Verbos Regulares AR','Czasowniki regularne AR','cuidar','opiekować się / dbać'),
('Verbos Regulares AR','Czasowniki regularne AR','pasear','spacerować'),
('Verbos Regulares AR','Czasowniki regularne AR','tocar','dotykać / grać (na instrumencie)'),
('Verbos Regulares AR','Czasowniki regularne AR','bajar','schodzić / obniżać');
