insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('La Familia','Rodzina','la madre','matka'),
('La Familia','Rodzina','el padre','ojciec'),
('La Familia','Rodzina','el hijo','syn'),
('La Familia','Rodzina','la hija','córka'),
('La Familia','Rodzina','el hermano','brat'),
('La Familia','Rodzina','la hermana','siostra'),
('La Familia','Rodzina','el abuelo','dziadek'),
('La Familia','Rodzina','la abuela','babcia'),
('La Familia','Rodzina','el nieto','wnuk'),
('La Familia','Rodzina','la nieta','wnuczka'),
('La Familia','Rodzina','el tío','wujek'),
('La Familia','Rodzina','la tía','ciocia'),
('La Familia','Rodzina','el primo','kuzyn'),
('La Familia','Rodzina','la prima','kuzynka'),
('La Familia','Rodzina','el sobrino','siostrzeniec/bratanek'),
('La Familia','Rodzina','la sobrina','siostrzenica/bratanica'),
('La Familia','Rodzina','el esposo','mąż'),
('La Familia','Rodzina','la esposa','żona'),
('La Familia','Rodzina','el marido','mąż'),
('La Familia','Rodzina','la mujer','kobieta/żona'),
('La Familia','Rodzina','el suegro','teść'),
('La Familia','Rodzina','la suegra','teściowa'),
('La Familia','Rodzina','el yerno','zięć'),
('La Familia','Rodzina','la nuera','synowa'),
('La Familia','Rodzina','el cuñado','szwagier'),
('La Familia','Rodzina','la cuñada','szwagierka'),
('La Familia','Rodzina','el padrastro','ojczym'),
('La Familia','Rodzina','la madrastra','macocha'),
('La Familia','Rodzina','el hijastro','pasierb'),
('La Familia','Rodzina','la hijastra','pasierbica'),
('La Familia','Rodzina','el hermanastro','przyrodni brat'),
('La Familia','Rodzina','la hermanastra','przyrodnia siostra'),
('La Familia','Rodzina','el padrino','ojciec chrzestny'),
('La Familia','Rodzina','la madrina','matka chrzestna'),
('La Familia','Rodzina','el ahijado','chrześniak'),
('La Familia','Rodzina','la ahijada','chrześniaczka'),
('La Familia','Rodzina','los padres','rodzice'),
('La Familia','Rodzina','los hijos','dzieci'),
('La Familia','Rodzina','los abuelos','dziadkowie'),
('La Familia','Rodzina','los suegros','teściowie'),
('La Familia','Rodzina','el pariente','krewny'),
('La Familia','Rodzina','la parienta','krewna'),
('La Familia','Rodzina','el huérfano','sierota (chłopiec)'),
('La Familia','Rodzina','la huérfana','sierota (dziewczynka)'),
('La Familia','Rodzina','los gemelos','bliźniacy'),
('La Familia','Rodzina','las gemelas','bliźniaczki'),
('La Familia','Rodzina','el primogénito','pierworodny'),
('La Familia','Rodzina','la familia política','rodzina ze strony męża/żony'),
('La Familia','Rodzina','el antepasado','przodek'),
('La Familia','Rodzina','la descendencia','potomstwo'),
('El Cuerpo Humano','Ciało ludzkie','la cabeza','głowa'),
('El Cuerpo Humano','Ciało ludzkie','el pelo','włosy'),
('El Cuerpo Humano','Ciało ludzkie','la cara','twarz'),
('El Cuerpo Humano','Ciało ludzkie','la frente','czoło'),
('El Cuerpo Humano','Ciało ludzkie','el ojo','oko'),
('El Cuerpo Humano','Ciało ludzkie','la ceja','brew'),
('El Cuerpo Humano','Ciało ludzkie','la pestaña','rzęsa'),
('El Cuerpo Humano','Ciało ludzkie','la nariz','nos'),
('El Cuerpo Humano','Ciało ludzkie','la boca','usta'),
('El Cuerpo Humano','Ciało ludzkie','el labio','warga'),
('El Cuerpo Humano','Ciało ludzkie','el diente','ząb'),
('El Cuerpo Humano','Ciało ludzkie','la lengua','język'),
('El Cuerpo Humano','Ciało ludzkie','la oreja','ucho (zewnętrzne)'),
('El Cuerpo Humano','Ciało ludzkie','el oído','ucho (wewnętrzne)'),
('El Cuerpo Humano','Ciało ludzkie','la mejilla','policzek'),
('El Cuerpo Humano','Ciało ludzkie','la barbilla','broda (część twarzy)'),
('El Cuerpo Humano','Ciało ludzkie','el cuello','szyja'),
('El Cuerpo Humano','Ciało ludzkie','la garganta','gardło'),
('El Cuerpo Humano','Ciało ludzkie','el hombro','ramię (staw)'),
('El Cuerpo Humano','Ciało ludzkie','el brazo','ręka (od ramienia do dłoni)'),
('El Cuerpo Humano','Ciało ludzkie','el codo','łokieć'),
('El Cuerpo Humano','Ciało ludzkie','la muñeca','nadgarstek'),
('El Cuerpo Humano','Ciało ludzkie','la mano','dłoń'),
('El Cuerpo Humano','Ciało ludzkie','el dedo','palec (u ręki)'),
('El Cuerpo Humano','Ciało ludzkie','la uña','paznokieć'),
('El Cuerpo Humano','Ciało ludzkie','el pecho','klatka piersiowa'),
('El Cuerpo Humano','Ciało ludzkie','el corazón','serce'),
('El Cuerpo Humano','Ciało ludzkie','el estómago','żołądek'),
('El Cuerpo Humano','Ciało ludzkie','la barriga','brzuch'),
('El Cuerpo Humano','Ciało ludzkie','el ombligo','pępek'),
('El Cuerpo Humano','Ciało ludzkie','la espalda','plecy'),
('El Cuerpo Humano','Ciało ludzkie','la columna vertebral','kręgosłup'),
('El Cuerpo Humano','Ciało ludzkie','la cintura','talia'),
('El Cuerpo Humano','Ciało ludzkie','la cadera','biodro'),
('El Cuerpo Humano','Ciało ludzkie','el trasero','pośladki'),
('El Cuerpo Humano','Ciało ludzkie','la pierna','noga'),
('El Cuerpo Humano','Ciało ludzkie','el muslo','udo'),
('El Cuerpo Humano','Ciało ludzkie','la rodilla','kolano'),
('El Cuerpo Humano','Ciało ludzkie','el tobillo','kostka'),
('El Cuerpo Humano','Ciało ludzkie','el pie','stopa'),
('El Cuerpo Humano','Ciało ludzkie','el dedo del pie','palec u nogi'),
('El Cuerpo Humano','Ciało ludzkie','el talón','pięta'),
('El Cuerpo Humano','Ciało ludzkie','la piel','skóra'),
('El Cuerpo Humano','Ciało ludzkie','el hueso','kość'),
('El Cuerpo Humano','Ciało ludzkie','el músculo','mięsień'),
('El Cuerpo Humano','Ciało ludzkie','la sangre','krew'),
('El Cuerpo Humano','Ciało ludzkie','la vena','żyła'),
('El Cuerpo Humano','Ciało ludzkie','el pulmón','płuco'),
('El Cuerpo Humano','Ciało ludzkie','el cerebro','mózg'),
('El Cuerpo Humano','Ciało ludzkie','el hígado','wątroba'),
('La Ciudad','Miasto','la ciudad','miasto'),
('La Ciudad','Miasto','el pueblo','wioska/miasteczko'),
('La Ciudad','Miasto','el centro','centrum'),
('La Ciudad','Miasto','el barrio','dzielnica'),
('La Ciudad','Miasto','las afueras','przedmieścia'),
('La Ciudad','Miasto','la calle','ulica'),
('La Ciudad','Miasto','la avenida','aleja'),
('La Ciudad','Miasto','la plaza','plac'),
('La Ciudad','Miasto','el parque','park'),
('La Ciudad','Miasto','el jardín','ogród'),
('La Ciudad','Miasto','el edificio','budynek'),
('La Ciudad','Miasto','el rascacielos','drapacz chmur'),
('La Ciudad','Miasto','la casa','dom'),
('La Ciudad','Miasto','el apartamento','apartament/mieszkanie'),
('La Ciudad','Miasto','la tienda','sklep'),
('La Ciudad','Miasto','el centro comercial','centrum handlowe'),
('La Ciudad','Miasto','el supermercado','supermarket'),
('La Ciudad','Miasto','el mercado','rynek/targ'),
('La Ciudad','Miasto','la panadería','piekarnia'),
('La Ciudad','Miasto','la carnicería','rzeźnik'),
('La Ciudad','Miasto','la farmacia','apteka'),
('La Ciudad','Miasto','el hospital','szpital'),
('La Ciudad','Miasto','la clínica','klinika'),
('La Ciudad','Miasto','la escuela','szkoła'),
('La Ciudad','Miasto','el colegio','szkoła podstawowa/średnia'),
('La Ciudad','Miasto','la universidad','uniwersytet'),
('La Ciudad','Miasto','la biblioteca','biblioteka'),
('La Ciudad','Miasto','el museo','muzeum'),
('La Ciudad','Miasto','el teatro','teatr'),
('La Ciudad','Miasto','el cine','kino'),
('La Ciudad','Miasto','el restaurante','restauracja'),
('La Ciudad','Miasto','el café','kawiarnia'),
('La Ciudad','Miasto','el bar','bar'),
('La Ciudad','Miasto','el banco','bank'),
('La Ciudad','Miasto','el cajero automático','bankomat'),
('La Ciudad','Miasto','la oficina de correos','poczta'),
('La Ciudad','Miasto','la comisaría','posterunek policji'),
('La Ciudad','Miasto','la estación de bomberos','remiza strażacka'),
('La Ciudad','Miasto','el ayuntamiento','ratusz'),
('La Ciudad','Miasto','la iglesia','kościół'),
('La Ciudad','Miasto','la catedral','katedra'),
('La Ciudad','Miasto','la estación de tren','stacja kolejowa'),
('La Ciudad','Miasto','la estación de autobuses','dworzec autobusowy'),
('La Ciudad','Miasto','el aeropuerto','lotnisko'),
('La Ciudad','Miasto','el puente','most'),
('La Ciudad','Miasto','el monumento','pomnik'),
('La Ciudad','Miasto','la fuente','fontanna'),
('La Ciudad','Miasto','el semáforo','sygnalizacja świetlna'),
('La Ciudad','Miasto','la acera','chodnik'),
('La Ciudad','Miasto','el paso de cebra','przejście dla pieszych'),
('La Casa','Dom','la casa','dom'),
('La Casa','Dom','el piso','mieszkanie/piętro'),
('La Casa','Dom','el edificio','budynek'),
('La Casa','Dom','el tejado','dach'),
('La Casa','Dom','la chimenea','komin'),
('La Casa','Dom','la pared','ściana'),
('La Casa','Dom','el suelo','podłoga'),
('La Casa','Dom','el techo','sufit'),
('La Casa','Dom','la ventana','okno'),
('La Casa','Dom','la puerta','drzwi'),
('La Casa','Dom','el balcón','balkon'),
('La Casa','Dom','la terraza','taras'),
('La Casa','Dom','el jardín','ogród'),
('La Casa','Dom','el garaje','garaż'),
('La Casa','Dom','el sótano','piwnica'),
('La Casa','Dom','el ático','strych'),
('La Casa','Dom','la escalera','schody'),
('La Casa','Dom','el ascensor','winda'),
('La Casa','Dom','el pasillo','korytarz'),
('La Casa','Dom','el recibidor','przedpokój'),
('La Casa','Dom','el salón','salon'),
('La Casa','Dom','el comedor','jadalnia'),
('La Casa','Dom','la cocina','kuchnia'),
('La Casa','Dom','el dormitorio','sypialnia'),
('La Casa','Dom','el cuarto de baño','łazienka'),
('La Casa','Dom','el aseo','toaleta'),
('La Casa','Dom','el estudio','gabinet'),
('La Casa','Dom','el cuarto de invitados','pokój gościnny'),
('La Casa','Dom','el mueble','mebel'),
('La Casa','Dom','la silla','krzesło'),
('La Casa','Dom','la mesa','stół'),
('La Casa','Dom','el sofá','kanapa'),
('La Casa','Dom','el sillón','fotel'),
('La Casa','Dom','la estantería','regał'),
('La Casa','Dom','el armario','szafa'),
('La Casa','Dom','la cama','łóżko'),
('La Casa','Dom','la mesita de noche','stolik nocny'),
('La Casa','Dom','el escritorio','biurko'),
('La Casa','Dom','la lámpara','lampa'),
('La Casa','Dom','la alfombra','dywan'),
('La Casa','Dom','el espejo','lustro'),
('La Casa','Dom','el cuadro','obraz'),
('La Casa','Dom','la cortina','zasłona'),
('La Casa','Dom','la persiana','roleta'),
('La Casa','Dom','el cojín','poduszka (dekoracyjna)'),
('La Casa','Dom','la almohada','poduszka (do spania)'),
('La Casa','Dom','la manta','koc'),
('La Casa','Dom','la sábana','prześcieradło'),
('La Casa','Dom','la calefacción','ogrzewanie'),
('La Casa','Dom','el aire acondicionado','klimatyzacja');
