insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la delincuencia','przestępczość'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el delincuente','przestępca'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el crimen','przestępstwo / zbrodnia'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el delito','przestępstwo'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la falta','wykroczenie'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el robo','kradzież'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','robar','kraść'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el ladrón','złodziej'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el asalto','napad'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','asaltar','napadać'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el hurto','kradzież bez przemocy'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el asesinato','zabójstwo / morderstwo'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','asesinar','zamordować'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el asesino','morderca'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el secuestro','porwanie'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','secuestrar','porwać'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la extorsión','wymuszenie / szantaż'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el soborno','łapówka'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el fraude','oszustwo'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la estafa','wyłudzenie'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el estafador','oszust'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el narcotráfico','handel narkotykami'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el narcotraficante','handlarz narkotykami'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la corrupción','korupcja'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el vandalismo','wandalizm'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la violencia','przemoc'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la agresión','agresja / napaść'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','agredir','zaatakować'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la víctima','ofiara'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el testigo','świadek'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el sospechoso','podejrzany'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la prueba','dowód'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la investigación','śledztwo'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','investigcar','prowadzić śledztwo'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el juez','sędzia'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el tribunal','sąd'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la sentencia','wyrok'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','condenar','skazać'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la condena','skazanie / wyrok'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la cárcel','więzienie'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el preso','więzień'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la prisión','areszt / więzienie'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la multa','grzywna'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la libertad condicional','warunkowe zwolnienie'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el abogado','prawnik / adwokat'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el fiscal','prokurator'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la fiscalía','prokuratura'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la ley','prawo'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','el código penal','kodeks karny'),
('Delincuencia y Justicia','Przestępczość i sprawiedliwość','la justicia','sprawiedliwość'),
('Policía','Policja','la policía','policja'),
('Policía','Policja','el policía','policjant'),
('Policía','Policja','el agente','funkcjonariusz'),
('Policía','Policja','la comisaría','komisariat policji'),
('Policía','Policja','el coche de patrulla','radiowóz'),
('Policía','Policja','la sirena','syrena'),
('Policía','Policja','la patrulla','patrol'),
('Policía','Policja','patrullar','patrolować'),
('Policía','Policja','el uniforme','mundur'),
('Policía','Policja','la placa','odznaka'),
('Policía','Policja','las esposas','kajdanki'),
('Policía','Policja','esposar','zakładać kajdanki'),
('Policía','Policja','el arresto','aresztowanie'),
('Policía','Policja','detener','zatrzymać / aresztować'),
('Policía','Policja','la detención','zatrzymanie'),
('Policía','Policja','el control de carretera','kontrola drogowa'),
('Policía','Policja','el radar','radar'),
('Policía','Policja','la multa','mandat'),
('Policía','Policja','poner una multa','wystawić mandat'),
('Policía','Policja','el alcoholímetro','alkomat'),
('Policía','Policja','la prueba de alcoholemia','badanie alkomatem'),
('Policía','Policja','el tráfico','ruch drogowy'),
('Policía','Policja','el orden público','porządek publiczny'),
('Policía','Policja','la seguridad ciudadana','bezpieczeństwo publiczne'),
('Policía','Policja','la investigación','dochodzenie'),
('Policía','Policja','interrogar','przesłuchiwać'),
('Policía','Policja','el interrogatorio','przesłuchanie'),
('Policía','Policja','la pista','trop / ślad'),
('Policía','Policja','el sospechoso','podejrzany'),
('Policía','Policja','la huella dactilar','odcisk palca'),
('Policía','Policja','la escena del crimen','miejsce zbrodni'),
('Policía','Policja','la persecución','pościg'),
('Policía','Policja','perseguir','ścigać'),
('Policía','Policja','disparar','strzelać'),
('Policía','Policja','el disparo','strzał'),
('Policía','Policja','el arma de fuego','broń palna'),
('Policía','Policja','el chaleco antibalas','kamizelka kuloodporna'),
('Policía','Policja','la comisaría central','komisariat centralny'),
('Policía','Policja','el turno','zmiana'),
('Policía','Policja','el rescate','ratunek'),
('Policía','Policja','la llamada de emergencia','zgłoszenie alarmowe'),
('Policía','Policja','el número de emergencia','numer alarmowy'),
('Policía','Policja','el antidisturbios','oddział prewencji'),
('Policía','Policja','la manifestación','zgromadzenie'),
('Policía','Policja','disolver','rozpędzić tłum'),
('Policía','Policja','la seguridad','bezpieczeństwo'),
('Policía','Policja','proteger','chronić'),
('Policía','Policja','auxiliar','udzielać pomocy'),
('Policía','Policja','el parte policial','raport policyjny'),
('Policía','Policja','la autoridad','władza / organ ścigania'),
('En el Tribunal','W sądzie','el tribunal','sąd'),
('En el Tribunal','W sądzie','el juzgado','urząd sądowy'),
('En el Tribunal','W sądzie','la sala de audiencias','sala rozpraw'),
('En el Tribunal','W sądzie','el juez','sędzia'),
('En el Tribunal','W sądzie','el magistrado','sędzia trybunału'),
('En el Tribunal','W sądzie','el fiscal','prokurator'),
('En el Tribunal','W sądzie','el abogado','adwokat'),
('En el Tribunal','W sądzie','el abogado defensor','obrońca'),
('En el Tribunal','W sądzie','el acusado','oskarżony'),
('En el Tribunal','W sądzie','el demandante','powód'),
('En el Tribunal','W sądzie','el demandado','pozwany'),
('En el Tribunal','W sądzie','la demanda','pozew'),
('En el Tribunal','W sądzie','la acusación','oskarżenie'),
('En el Tribunal','W sądzie','el testigo','świadek'),
('En el Tribunal','W sądzie','el perito','biegły sądowy'),
('En el Tribunal','W sądzie','el jurado','ław przysięgłych'),
('En el Tribunal','W sądzie','el miembro del jurado','przysięgły'),
('En el Tribunal','W sądzie','la prueba','dowód'),
('En el Tribunal','W sądzie','la evidencia','dowód rzeczowy'),
('En el Tribunal','W sądzie','el testimonio','zeznanie'),
('En el Tribunal','W sądzie','declarar','składać zeznania'),
('En el Tribunal','W sądzie','el interrogatorio','przesłuchanie'),
('En el Tribunal','W sądzie','interrogar','przesłuchiwać'),
('En el Tribunal','W sądzie','la objeción','sprzeciw'),
('En el Tribunal','W sądzie','objetar','zgłaszać sprzeciw'),
('En el Tribunal','W sądzie','el veredicto','werdykt'),
('En el Tribunal','W sądzie','la sentencia','wyrok'),
('En el Tribunal','W sądzie','condenar','skazać'),
('En el Tribunal','W sądzie','absolver','uniewinnić'),
('En el Tribunal','W sądzie','la absolución','uniewinnienie'),
('En el Tribunal','W sądzie','la condena','wyrok skazujący'),
('En el Tribunal','W sądzie','la apelación','apelacja'),
('En el Tribunal','W sądzie','apelar','składać apelację'),
('En el Tribunal','W sądzie','el recurso','środek odwoławczy'),
('En el Tribunal','W sądzie','el caso','sprawa'),
('En el Tribunal','W sądzie','la vista','rozprawa'),
('En el Tribunal','W sądzie','el juicio','proces sądowy'),
('En el Tribunal','W sądzie','la coartada','alibi'),
('En el Tribunal','W sądzie','el secreto de sumario','tajemnica śledztwa'),
('En el Tribunal','W sądzie','firmar','podpisać'),
('En el Tribunal','W sądzie','dictar sentencia','wydać wyrok'),
('En el Tribunal','W sądzie','el magistrado presidente','przewodniczący składu'),
('En el Tribunal','W sądzie','la indemnización','odszkodowanie'),
('En el Tribunal','W sądzie','los daños y perjuicios','odszkodowanie za straty'),
('En el Tribunal','W sądzie','culpable','winny'),
('En el Tribunal','W sądzie','inocente','niewinny'),
('En el Tribunal','W sądzie','la culpabilidad','wina'),
('En el Tribunal','W sądzie','la inocencia','niewinność'),
('En el Tribunal','W sądzie','el acta','protokół'),
('En el Tribunal','W sądzie','el secretario judicial','sekretarz sądowy'),
('Prisión','Więzienie','la prisión','więzienie'),
('Prisión','Więzienie','la cárcel','więzienie / areszt'),
('Prisión','Więzienie','la penitenciaría','zakład karny'),
('Prisión','Więzienie','el calabozo','karcer / loch / celi policyjna'),
('Prisión','Więzienie','la celda','cela'),
('Prisión','Więzienie','el recluso / el preso','więziec / osadzony'),
('Prisión','Więzienie','el criminal','przestępca'),
('Prisión','Więzienie','el delincuente','skazany'),
('Prisión','Więzienie','el alcaide','naczelnik więzienia'),
('Prisión','Więzienie','el guardia','strażnik więzienny'),
('Prisión','Więzienie','el carcelero','dozorca więzienny'),
('Prisión','Więzienie','la condena','wyrok skazujący'),
('Prisión','Więzienie','cumplic condena','odsiadwać wyrok'),
('Prisión','Więzienie','la cadena perpetua','dożywocie'),
('Prisión','Więzienie','la celda de aislamiento','cela izolacyjna'),
('Prisión','Więzienie','el patio','dziedziniec więzienny'),
('Prisión','Więzienie','el 3er grado','przepustka / wolność kontrolowada'),
('Prisión','Więzienie','la libertad condicional','warunkowe przedterminowe zwolnienie'),
('Prisión','Więzienie','la fuga','ucieczka'),
('Prisión','Więzienie','fugarse','uciec z więzienia'),
('Prisión','Więzienie','el preso fugado','zbieg'),
('Prisión','Więzienie','la visita','widzenie (w więzieniu)'),
('Prisión','Więzienie','el vis a vis','widzenie intymne / bez nadzoru'),
('Prisión','Więzienie','la huelga de hambre','strajk głodowy'),
('Prisión','Więzienie','la revuelta','bunt (więzienny)'),
('Prisión','Więzienie','el motín','zamieszki / bunt'),
('Prisión','Więzienie','la rehabilitación','resocjalizacja'),
('Prisión','Więzienie','rehabitarse','resocjalizować się'),
('Prisión','Więzienie','el régimen penitenciario','system penitencjarny'),
('Prisión','Więzienie','la condena condicional','wyrok w zawieszeniu'),
('Prisión','Więzienie','el brazalete electrónico','obrączka elektroniczna'),
('Prisión','Więzienie','la condena de trabajos','prace społeczne'),
('Prisión','Więzienie','el indulto','ułaskawienie'),
('Prisión','Więzienie','indultar','ułaskawić'),
('Prisión','Więzienie','la amnistía','amnestia'),
('Prisión','Więzienie','el expediente','akta / kartoteka'),
('Prisión','Więzienie','el ingreso en prisión','osadzenie w zakładzie karnym'),
('Prisión','Więzienie','la libertad','wolność'),
('Prisión','Więzienie','salir en libertad','wyjść na wolność'),
('Prisión','Więzienie','el reincidente','recydywista'),
('Prisión','Więzienie','la reincidencia','recydywa'),
('Prisión','Więzienie','el delito menor','wykroczenie / drobny przestępca'),
('Prisión','Więzienie','la seguridad','bezpieczeństwo'),
('Prisión','Więzienie','el control','kontrola'),
('Prisión','Więzienie','el cacheo','rewizja osobistia'),
('Prisión','Więzienie','la requisa','przeszukanie celi'),
('Prisión','Więzienie','el contrabando','kontrabanda'),
('Prisión','Więzienie','el aislamiento','izolacja'),
('Prisión','Więzienie','el grillete','kajdanki na nogi'),
('Prisión','Więzienie','la llave','klucz');
