insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Sentimientos Negativos','Negatywne uczucia','la tristeza','smutek'),
('Sentimientos Negativos','Negatywne uczucia','triste','smutny'),
('Sentimientos Negativos','Negatywne uczucia','la depresión','depresja'),
('Sentimientos Negativos','Negatywne uczucia','deprimido','zdołowany'),
('Sentimientos Negativos','Negatywne uczucia','el dolor','ból'),
('Sentimientos Negativos','Negatywne uczucia','dolido','zraniony'),
('Sentimientos Negativos','Negatywne uczucia','la pena','smutek / żal'),
('Sentimientos Negativos','Negatywne uczucia','apenado','zasmucony'),
('Sentimientos Negativos','Negatywne uczucia','la melancolía','melancholia'),
('Sentimientos Negativos','Negatywne uczucia','melancólico','melancholijny'),
('Sentimientos Negativos','Negatywne uczucia','el llanto','płacz'),
('Sentimientos Negativos','Negatywne uczucia','la ira','gniew'),
('Sentimientos Negativos','Negatywne uczucia','iracundo','gniewny'),
('Sentimientos Negativos','Negatywne uczucia','el enfado','złość'),
('Sentimientos Negativos','Negatywne uczucia','enfadado','zły'),
('Sentimientos Negativos','Negatywne uczucia','el enojo','złość'),
('Sentimientos Negativos','Negatywne uczucia','enojado','zły'),
('Sentimientos Negativos','Negatywne uczucia','el odio','nienawiść'),
('Sentimientos Negativos','Negatywne uczucia','el rencor','uraza'),
('Sentimientos Negativos','Negatywne uczucia','rencoroso','pamiętliwy / mściwy'),
('Sentimientos Negativos','Negatywne uczucia','la amargura','gorycz'),
('Sentimientos Negativos','Negatywne uczucia','amargado','zgorzkniały'),
('Sentimientos Negativos','Negatywne uczucia','el miedo','strach'),
('Sentimientos Negativos','Negatywne uczucia','miedoso','strachliwy'),
('Sentimientos Negativos','Negatywne uczucia','el temor','obawa'),
('Sentimientos Negativos','Negatywne uczucia','temeroso','bojaźliwy'),
('Sentimientos Negativos','Negatywne uczucia','el pánico','panika'),
('Sentimientos Negativos','Negatywne uczucia','el terror','przerażenie'),
('Sentimientos Negativos','Negatywne uczucia','aterrorizado','przerażony'),
('Sentimientos Negativos','Negatywne uczucia','la ansiedad','niepokój'),
('Sentimientos Negativos','Negatywne uczucia','ansioso','zaniepokojony'),
('Sentimientos Negativos','Negatywne uczucia','la angustia','udręka / lęk'),
('Sentimientos Negativos','Negatywne uczucia','angustiado','udręczony'),
('Sentimientos Negativos','Negatywne uczucia','el estrés','stres'),
('Sentimientos Negativos','Negatywne uczucia','estresado','zestresowany'),
('Sentimientos Negativos','Negatywne uczucia','la frustración','frustracja'),
('Sentimientos Negativos','Negatywne uczucia','frustrado','sfrustrowany'),
('Sentimientos Negativos','Negatywne uczucia','la decepción','rozczarowanie'),
('Sentimientos Negativos','Negatywne uczucia','decepcionado','rozczarowany'),
('Sentimientos Negativos','Negatywne uczucia','la culpa','wina'),
('Sentimientos Negativos','Negatywne uczucia','culpable','winny'),
('Sentimientos Negativos','Negatywne uczucia','la vergüenza','wstyd'),
('Sentimientos Negativos','Negatywne uczucia','avergonzado','zawstydzony'),
('Sentimientos Negativos','Negatywne uczucia','el aburrimiento','nuda'),
('Sentimientos Negativos','Negatywne uczucia','aburrido','znudzony'),
('Sentimientos Negativos','Negatywne uczucia','la envidia','zazdrość (zawiść)'),
('Sentimientos Negativos','Negatywne uczucia','envidioso','zawistny'),
('Sentimientos Negativos','Negatywne uczucia','la apatía','apatia'),
('Sentimientos Negativos','Negatywne uczucia','apático','apatyczny'),
('Sentimientos Negativos','Negatywne uczucia','la soledad','samotność'),
('Características Físicas','Cechy fizyczne','el aspecto','wygląd'),
('Características Físicas','Cechy fizyczne','la apariencia','aparycja'),
('Características Físicas','Cechy fizyczne','alto','wysoki'),
('Características Físicas','Cechy fizyczne','bajo','niski'),
('Características Físicas','Cechy fizyczne','de estatura media','średniego wzrostu'),
('Características Físicas','Cechy fizyczne','gordo','gruby'),
('Características Físicas','Cechy fizyczne','con sobrepeso','z nadwagą'),
('Características Físicas','Cechy fizyczne','delgado','szczupły'),
('Características Físicas','Cechy fizyczne','flaco','chudy'),
('Características Físicas','Cechy fizyczne','fuerte','silny'),
('Características Físicas','Cechy fizyczne','débil','słaby'),
('Características Físicas','Cechy fizyczne','musculoso','umięśniony'),
('Características Físicas','Cechy fizyczne','guapo','przystojny / ładny'),
('Características Físicas','Cechy fizyczne','feo','brzydki'),
('Características Físicas','Cechy fizyczne','hermoso','piękny'),
('Características Físicas','Cechy fizyczne','atractivo','atrakcyjny'),
('Características Físicas','Cechy fizyczne','joven','młody'),
('Características Físicas','Cechy fizyczne','viejo','stary'),
('Características Físicas','Cechy fizyczne','mayor','starszy'),
('Características Físicas','Cechy fizyczne','de mediana edad','w średnim wieku'),
('Características Físicas','Cechy fizyczne','el pelo','włosy'),
('Características Físicas','Cechy fizyczne','rubio','blond'),
('Características Físicas','Cechy fizyczne','moreno','brunet'),
('Características Físicas','Cechy fizyczne','castaño','szatyn'),
('Características Físicas','Cechy fizyczne','pelirrojo','rudy'),
('Características Físicas','Cechy fizyczne','calvo','łysy'),
('Características Físicas','Cechy fizyczne','el pelo largo','długie włosy'),
('Características Físicas','Cechy fizyczne','el pelo corto','krótkie włosy'),
('Características Físicas','Cechy fizyczne','el pelo liso','proste włosy'),
('Características Físicas','Cechy fizyczne','el pelo rizado','kręcone włosy'),
('Características Físicas','Cechy fizyczne','el pelo ondulado','falowane włosy'),
('Características Físicas','Cechy fizyczne','la piel','skóra'),
('Características Físicas','Cechy fizyczne','claro','jasny'),
('Características Físicas','Cechy fizyczne','oscuro','ciemny'),
('Características Físicas','Cechy fizyczne','pálido','blady'),
('Características Físicas','Cechy fizyczne','bronceado','opalony'),
('Características Físicas','Cechy fizyczne','los ojos','oczy'),
('Características Físicas','Cechy fizyczne','los ojos azules','niebieskie oczy'),
('Características Físicas','Cechy fizyczne','los ojos verdes','zielone oczy'),
('Características Físicas','Cechy fizyczne','los ojos marrones','brązowe oczy'),
('Características Físicas','Cechy fizyczne','las gafas','okulary'),
('Características Físicas','Cechy fizyczne','la barba','broda'),
('Características Físicas','Cechy fizyczne','el bigote','wąsy'),
('Características Físicas','Cechy fizyczne','la peca','pieg'),
('Características Físicas','Cechy fizyczne','el lunar','pieprzyk'),
('Características Físicas','Cechy fizyczne','la arruga','zmarszczka'),
('Características Físicas','Cechy fizyczne','la cicatriz','blizna'),
('Características Físicas','Cechy fizyczne','el tatuaje','tatuaż'),
('Características Físicas','Cechy fizyczne','la sonrisa','uśmiech'),
('Características Físicas','Cechy fizyczne','el rostro / la cara','twarz'),
('El Cabello','Włosy (Rodzaje)','el cabello / el pelo','włosy'),
('El Cabello','Włosy (Rodzaje)','el peinado','fryzura'),
('El Cabello','Włosy (Rodzaje)','el corte de pelo','strzyżenie / fryzura'),
('El Cabello','Włosy (Rodzaje)','rubio','blond'),
('El Cabello','Włosy (Rodzaje)','moreno','ciemnowłosy / brunet'),
('El Cabello','Włosy (Rodzaje)','castaño','szatyn'),
('El Cabello','Włosy (Rodzaje)','pelirrojo','rudy'),
('El Cabello','Włosy (Rodzaje)','teñido','farbowany'),
('El Cabello','Włosy (Rodzaje)','las mechas','pasemka'),
('El Cabello','Włosy (Rodzaje)','liso','prosty (o włosach)'),
('El Cabello','Włosy (Rodzaje)','rizado','kręcony'),
('El Cabello','Włosy (Rodzaje)','ondulado','falowany'),
('El Cabello','Włosy (Rodzaje)','corto','krótki'),
('El Cabello','Włosy (Rodzaje)','largo','długi'),
('El Cabello','Włosy (Rodzaje)','suelto','rozpuszczony'),
('El Cabello','Włosy (Rodzaje)','recogido','związany / upięty'),
('El Cabello','Włosy (Rodzaje)','la trenza','warkocz'),
('El Cabello','Włosy (Rodzaje)','la coleta','kucyk'),
('El Cabello','Włosy (Rodzaje)','el moño','kok'),
('El Cabello','Włosy (Rodzaje)','el flequillo','grzywka'),
('El Cabello','Włosy (Rodzaje)','la raya','przedziałek'),
('El Cabello','Włosy (Rodzaje)','la calva','łysina'),
('El Cabello','Włosy (Rodzaje)','calvo','łysy'),
('El Cabello','Włosy (Rodzaje)','la caspa','łupież'),
('El Cabello','Włosy (Rodzaje)','el champú','szampon'),
('El Cabello','Włosy (Rodzaje)','el acondicionador','odżywka do włosów'),
('El Cabello','Włosy (Rodzaje)','el secador','suszarka do włosów'),
('El Cabello','Włosy (Rodzaje)','la plancha de pelo','prostownica'),
('El Cabello','Włosy (Rodzaje)','el peine','grzebień'),
('El Cabello','Włosy (Rodzaje)','el cepillo','szczotka'),
('El Cabello','Włosy (Rodzaje)','peinar','czesać (grzebieniem)'),
('El Cabello','Włosy (Rodzaje)','cepillar','szczotkować'),
('El Cabello','Włosy (Rodzaje)','cortar','obcinać'),
('El Cabello','Włosy (Rodzaje)','teñir','farbować'),
('El Cabello','Włosy (Rodzaje)','lavar','myć'),
('El Cabello','Włosy (Rodzaje)','la peluquería','salon fryzjerski'),
('El Cabello','Włosy (Rodzaje)','el peluquero / la peluquera','fryzjer / fryzjerka'),
('El Cabello','Włosy (Rodzaje)','la laca','lakier do włosów'),
('El Cabello','Włosy (Rodzaje)','el gel / la gomina','żel do włosów'),
('El Cabello','Włosy (Rodzaje)','la mascarilla capilar','maska do włosów'),
('El Cabello','Włosy (Rodzaje)','las tijeras','nożyczki'),
('El Cabello','Włosy (Rodzaje)','la peluca','peruka'),
('El Cabello','Włosy (Rodzaje)','las extensiones','doczepiane włosy'),
('El Cabello','Włosy (Rodzaje)','el rizo','lok'),
('El Cabello','Włosy (Rodzaje)','la raíz','cebulka / odrost'),
('El Cabello','Włosy (Rodzaje)','la punta','końcówka (włosa)'),
('El Cabello','Włosy (Rodzaje)','el volumen','objętość'),
('El Cabello','Włosy (Rodzaje)','brillante','lśniący'),
('El Cabello','Włosy (Rodzaje)','seco','suchy'),
('El Cabello','Włosy (Rodzaje)','graso','przetłuszczający się / tłusty'),
('Ropa de Invierno','Ubrania zimowe','el invierno','zima'),
('Ropa de Invierno','Ubrania zimowe','el frío','zimno'),
('Ropa de Invierno','Ubrania zimowe','el abrigo','płaszcz'),
('Ropa de Invierno','Ubrania zimowe','la chaqueta','kurtka'),
('Ropa de Invierno','Ubrania zimowe','el anorak','kurtka zimowa (anorak)'),
('Ropa de Invierno','Ubrania zimowe','el plumífero','kurtka puchowa'),
('Ropa de Invierno','Ubrania zimowe','el jersey','sweter (przez głowę)'),
('Ropa de Invierno','Ubrania zimowe','el suéter','sweter'),
('Ropa de Invierno','Ubrania zimowe','la sudadera','bluza'),
('Ropa de Invierno','Ubrania zimowe','el cárdigan','rozpinany sweter'),
('Ropa de Invierno','Ubrania zimowe','el forro polar','polar (ubranie)'),
('Ropa de Invierno','Ubrania zimowe','el chaleco','kamizelka'),
('Ropa de Invierno','Ubrania zimowe','los pantalones de pana','spodnie sztruksowe'),
('Ropa de Invierno','Ubrania zimowe','la bufanda','szalik'),
('Ropa de Invierno','Ubrania zimowe','el gorro','czapka (zimowa)'),
('Ropa de Invierno','Ubrania zimowe','los guantes','rękawiczki'),
('Ropa de Invierno','Ubrania zimowe','las manoplas','rękawice z jednym palcem'),
('Ropa de Invierno','Ubrania zimowe','las orejeras','nauszniki'),
('Ropa de Invierno','Ubrania zimowe','los calcetines gruesos','grube skarpety'),
('Ropa de Invierno','Ubrania zimowe','los leotardos','rajstopy (grube)'),
('Ropa de Invierno','Ubrania zimowe','las mallas','getry / legginsy'),
('Ropa de Invierno','Ubrania zimowe','las botas','kozaki / buty zimowe'),
('Ropa de Invierno','Ubrania zimowe','las botas de nieve','śniegowce'),
('Ropa de Invierno','Ubrania zimowe','el cuello alto','golf (kołnierz)'),
('Ropa de Invierno','Ubrania zimowe','abrigarse','ciepło się ubierać'),
('Ropa de Invierno','Ubrania zimowe','de lana','z wełny'),
('Ropa de Invierno','Ubrania zimowe','térmico','termiczny'),
('Ropa de Invierno','Ubrania zimowe','la ropa térmica','odzież termiczna'),
('Ropa de Invierno','Ubrania zimowe','la manta','koc'),
('Ropa de Invierno','Ubrania zimowe','el pasamontañas','kominiarka'),
('Ropa de Invierno','Ubrania zimowe','el impermeable','płaszcz przeciwdeszczowy'),
('Ropa de Invierno','Ubrania zimowe','la gabardina','trencz'),
('Ropa de Invierno','Ubrania zimowe','la capa','peleryna'),
('Ropa de Invierno','Ubrania zimowe','esquiar','jeździć na nartach'),
('Ropa de Invierno','Ubrania zimowe','la ropa de esquí','odzież narciarska'),
('Ropa de Invierno','Ubrania zimowe','de punto','z dzianiny / robiony na drutach'),
('Ropa de Invierno','Ubrania zimowe','la manga larga','długi rękaw'),
('Ropa de Invierno','Ubrania zimowe','la capucha','kaptur'),
('Ropa de Invierno','Ubrania zimowe','abotonar','zapinać na guziki'),
('Ropa de Invierno','Ubrania zimowe','la cremallera','zamek błyskawiczny'),
('Ropa de Invierno','Ubrania zimowe','el bolsillo','kieszeń'),
('Ropa de Invierno','Ubrania zimowe','grueso','gruby (materiał)'),
('Ropa de Invierno','Ubrania zimowe','calentito','cieplutki'),
('Ropa de Invierno','Ubrania zimowe','la nieve','śnieg'),
('Ropa de Invierno','Ubrania zimowe','proteger','chronić'),
('Ropa de Invierno','Ubrania zimowe','el polar','polar (materiał)'),
('Ropa de Invierno','Ubrania zimowe','el copo de nieve','płatek śniegu'),
('Ropa de Invierno','Ubrania zimowe','abrigado','ciepło ubrany'),
('Ropa de Invierno','Ubrania zimowe','congelado','zmarznięty'),
('Ropa de Invierno','Ubrania zimowe','tiritar','trząść się (z zimna)');
