insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Derecho y Ley','Prawo y Ustawa','el derecho','prawo (dziedzina)'),
('Derecho y Ley','Prawo y Ustawa','la ley','ustawa / prawo'),
('Derecho y Ley','Prawo y Ustawa','legal','legalny'),
('Derecho y Ley','Prawo y Ustawa','ilegal','nielegalny'),
('Derecho y Ley','Prawo y Ustawa','el abogado','prawnik / adwokat'),
('Derecho y Ley','Prawo y Ustawa','el juez','sędzia'),
('Derecho y Ley','Prawo y Ustawa','el tribunal','sąd'),
('Derecho y Ley','Prawo y Ustawa','el juicio','proces sądowy / rozprawa'),
('Derecho y Ley','Prawo y Ustawa','el jurado','ława przysięgłych'),
('Derecho y Ley','Prawo y Ustawa','el testigo','świadek'),
('Derecho y Ley','Prawo y Ustawa','el testimonio','zeznanie'),
('Derecho y Ley','Prawo y Ustawa','la prueba','dowód'),
('Derecho y Ley','Prawo y Ustawa','el delito','przestępstwo'),
('Derecho y Ley','Prawo y Ustawa','el crimen','zbrodnia'),
('Derecho y Ley','Prawo y Ustawa','el criminal','przestępca'),
('Derecho y Ley','Prawo y Ustawa','el ladrón','złodziej'),
('Derecho y Ley','Prawo y Ustawa','el asesinato','morderstwo'),
('Derecho y Ley','Prawo y Ustawa','el asesino','morderca'),
('Derecho y Ley','Prawo y Ustawa','el robo','kradzież'),
('Derecho y Ley','Prawo y Ustawa','la estafa','oszustwo'),
('Derecho y Ley','Prawo y Ustawa','el sospechoso','podejrzany'),
('Derecho y Ley','Prawo y Ustawa','culpable','winny'),
('Derecho y Ley','Prawo y Ustawa','inocente','niewinny'),
('Derecho y Ley','Prawo y Ustawa','la culpa','wina'),
('Derecho y Ley','Prawo y Ustawa','la víctima','ofiara'),
('Derecho y Ley','Prawo y Ustawa','la policía','policja'),
('Derecho y Ley','Prawo y Ustawa','el policía','policjant'),
('Derecho y Ley','Prawo y Ustawa','arrestar','aresztować'),
('Derecho y Ley','Prawo y Ustawa','la cárcel / la prisión','więzienie'),
('Derecho y Ley','Prawo y Ustawa','el prisionero','więzień'),
('Derecho y Ley','Prawo y Ustawa','la celda','cela'),
('Derecho y Ley','Prawo y Ustawa','la demanda','pozew'),
('Derecho y Ley','Prawo y Ustawa','demandar','pozwać'),
('Derecho y Ley','Prawo y Ustawa','la defensa','obrona'),
('Derecho y Ley','Prawo y Ustawa','la acusación','oskarżenie'),
('Derecho y Ley','Prawo y Ustawa','acusar','oskarżać'),
('Derecho y Ley','Prawo y Ustawa','la sentencia','wyrok'),
('Derecho y Ley','Prawo y Ustawa','el castigo','kara'),
('Derecho y Ley','Prawo y Ustawa','la multa','mandat / grzywna'),
('Derecho y Ley','Prawo y Ustawa','la apelación','apelacja'),
('Derecho y Ley','Prawo y Ustawa','los derechos humanos','prawa człowieka'),
('Derecho y Ley','Prawo y Ustawa','la constitución','konstytucja'),
('Derecho y Ley','Prawo y Ustawa','el contrato','umowa'),
('Derecho y Ley','Prawo y Ustawa','firmar','podpisać'),
('Derecho y Ley','Prawo y Ustawa','la justicia','sprawiedliwość'),
('Derecho y Ley','Prawo y Ustawa','injusto','niesprawiedliwy'),
('Derecho y Ley','Prawo y Ustawa','la libertad','wolność'),
('Derecho y Ley','Prawo y Ustawa','el fiscal','prokurator'),
('Derecho y Ley','Prawo y Ustawa','el jurista','prawnik (teoretyk)'),
('Derecho y Ley','Prawo y Ustawa','el notario','notariusz'),
('El Ejército','Wojsko','el ejército','wojsko / armia'),
('El Ejército','Wojsko','las fuerzas armadas','siły zbrojne'),
('El Ejército','Wojsko','el soldado','żołnierz'),
('El Ejército','Wojsko','el oficial','oficer'),
('El Ejército','Wojsko','el general','generał'),
('El Ejército','Wojsko','el capitán','kapitan'),
('El Ejército','Wojsko','el comandante','dowódca / komendant'),
('El Ejército','Wojsko','el sargento','sierżant'),
('El Ejército','Wojsko','el uniforme','mundur'),
('El Ejército','Wojsko','la base militar','baza wojskowa'),
('El Ejército','Wojsko','la guerra','wojna'),
('El Ejército','Wojsko','la paz','pokój'),
('El Ejército','Wojsko','la batalla','bitwa'),
('El Ejército','Wojsko','el ataque','atak'),
('El Ejército','Wojsko','atacar','atakować'),
('El Ejército','Wojsko','la defensa','obrona'),
('El Ejército','Wojsko','defender','bronić'),
('El Ejército','Wojsko','el enemigo','wróg'),
('El Ejército','Wojsko','el aliado','sojusznik'),
('El Ejército','Wojsko','la victoria','zwycięstwo'),
('El Ejército','Wojsko','la derrota','porażka'),
('El Ejército','Wojsko','el arma','broń'),
('El Ejército','Wojsko','la pistola','pistolet'),
('El Ejército','Wojsko','el rifle / el fusil','karabin'),
('El Ejército','Wojsko','la bala','kula / pocisk'),
('El Ejército','Wojsko','la bomba','bomba'),
('El Ejército','Wojsko','el misil','pocisk rakietowy'),
('El Ejército','Wojsko','el tanque','czołg'),
('El Ejército','Wojsko','el avión de caza','myśliwiec'),
('El Ejército','Wojsko','el helicóptero','helikopter'),
('El Ejército','Wojsko','la marina','marynarka wojenna'),
('El Ejército','Wojsko','el barco de guerra','okręt wojenny'),
('El Ejército','Wojsko','el submarino','okręt podwodny'),
('El Ejército','Wojsko','la fuerza aérea','lotnictwo wojskowe'),
('El Ejército','Wojsko','el recluta','rekrut'),
('El Ejército','Wojsko','el veterano','weteran'),
('El Ejército','Wojsko','la medalla','medal'),
('El Ejército','Wojsko','el rango','stopień wojskowy'),
('El Ejército','Wojsko','la orden','rozkaz'),
('El Ejército','Wojsko','disparar','strzelać'),
('El Ejército','Wojsko','explotar','wybuchać'),
('El Ejército','Wojsko','la explosión','eksplozja'),
('El Ejército','Wojsko','el prisionero de guerra','jeździec wojenny / jeniec'),
('El Ejército','Wojsko','la trinchera','okop'),
('El Ejército','Wojsko','la estrategia','strategia'),
('El Ejército','Wojsko','el campamento','obóz'),
('El Ejército','Wojsko','rendirse','poddać się'),
('El Ejército','Wojsko','la tregua','zawieszenie broni'),
('El Ejército','Wojsko','el francotirador','snajper'),
('El Ejército','Wojsko','la munición','amunicja'),
('Instrumentos Musicales','Instrumenty muzyczne','el instrumento musical','instrument muzyczny'),
('Instrumentos Musicales','Instrumenty muzyczne','la guitarra','gitara'),
('Instrumentos Musicales','Instrumenty muzyczne','la guitarra eléctrica','gitara elektryczna'),
('Instrumentos Musicales','Instrumenty muzyczne','la guitarra acústica','gitara akustyczna'),
('Instrumentos Musicales','Instrumenty muzyczne','el bajo','gitara basowa'),
('Instrumentos Musicales','Instrumenty muzyczne','el piano','pianino'),
('Instrumentos Musicales','Instrumenty muzyczne','el teclado','keyboard / instrument klawiszowy'),
('Instrumentos Musicales','Instrumenty muzyczne','el violín','skrzypce'),
('Instrumentos Musicales','Instrumenty muzyczne','la viola','altówka'),
('Instrumentos Musicales','Instrumenty muzyczne','el violonchelo','wiolonczela'),
('Instrumentos Musicales','Instrumenty muzyczne','el contrabajo','kontrabas'),
('Instrumentos Musicales','Instrumenty muzyczne','el arpa','harfa'),
('Instrumentos Musicales','Instrumenty muzyczne','la batería','perkusja'),
('Instrumentos Musicales','Instrumenty muzyczne','el tambor','bęben'),
('Instrumentos Musicales','Instrumenty muzyczne','los platillos','talerze (instrument)'),
('Instrumentos Musicales','Instrumenty muzyczne','la trompeta','trąbka'),
('Instrumentos Musicales','Instrumenty muzyczne','el trombón','puzon'),
('Instrumentos Musicales','Instrumenty muzyczne','la tuba','tuba'),
('Instrumentos Musicales','Instrumenty muzyczne','el saxofón','saksofon'),
('Instrumentos Musicales','Instrumenty muzyczne','la flauta','flet'),
('Instrumentos Musicales','Instrumenty muzyczne','el clarinete','klarnet'),
('Instrumentos Musicales','Instrumenty muzyczne','el oboe','obój'),
('Instrumentos Musicales','Instrumenty muzyczne','el fagot','fagot'),
('Instrumentos Musicales','Instrumenty muzyczne','el acordeón','akordeon'),
('Instrumentos Musicales','Instrumenty muzyczne','la armónica','harmonijka ustna'),
('Instrumentos Musicales','Instrumenty muzyczne','la pandereta','tamburyn'),
('Instrumentos Musicales','Instrumenty muzyczne','las maracas','marakasy'),
('Instrumentos Musicales','Instrumenty muzyczne','el xilófono','ksylofon'),
('Instrumentos Musicales','Instrumenty muzyczne','el triángulo','trójkąt (instrument)'),
('Instrumentos Musicales','Instrumenty muzyczne','el órgano','organy'),
('Instrumentos Musicales','Instrumenty muzyczne','el sintetizador','syntezator'),
('Instrumentos Musicales','Instrumenty muzyczne','el laúd','lutnia'),
('Instrumentos Musicales','Instrumenty muzyczne','la mandolina','mandolina'),
('Instrumentos Musicales','Instrumenty muzyczne','el ukelele','ukulele'),
('Instrumentos Musicales','Instrumenty muzyczne','el bongó','bongo'),
('Instrumentos Musicales','Instrumenty muzyczne','las congas','kongi'),
('Instrumentos Musicales','Instrumenty muzyczne','las castañuelas','kastaniety'),
('Instrumentos Musicales','Instrumenty muzyczne','la gaita','dudy'),
('Instrumentos Musicales','Instrumenty muzyczne','la baqueta','pałeczka perkusyjna'),
('Instrumentos Musicales','Instrumenty muzyczne','la cuerda','struna'),
('Instrumentos Musicales','Instrumenty muzyczne','el arco','smyczek'),
('Instrumentos Musicales','Instrumenty muzyczne','el pedal','pedał'),
('Instrumentos Musicales','Instrumenty muzyczne','la tecla','klawisz'),
('Instrumentos Musicales','Instrumenty muzyczne','tocar','grać (na instrumencie)'),
('Instrumentos Musicales','Instrumenty muzyczne','afinar','stroić'),
('Instrumentos Musicales','Instrumenty muzyczne','el afinador','stroik'),
('Instrumentos Musicales','Instrumenty muzyczne','el músico','muzyk'),
('Instrumentos Musicales','Instrumenty muzyczne','la orquesta','orkiestra'),
('Instrumentos Musicales','Instrumenty muzyczne','el conservatorio','konserwatorium'),
('Instrumentos Musicales','Instrumenty muzyczne','la melodía','melodia'),
('Las Verduras','Warzywa','la verdura','warzywo'),
('Las Verduras','Warzywa','el tomate','pomidor'),
('Las Verduras','Warzywa','la cebolla','cebula'),
('Las Verduras','Warzywa','el ajo','czosnek'),
('Las Verduras','Warzywa','la patata / la papa','ziemniak'),
('Las Verduras','Warzywa','la zanahoria','marchewka'),
('Las Verduras','Warzywa','el pepino','ogórek'),
('Las Verduras','Warzywa','el pimiento','papryka'),
('Las Verduras','Warzywa','la lechuga','sałata'),
('Las Verduras','Warzywa','la col / el repollo','kapusta'),
('Las Verduras','Warzywa','el brócoli','brokuł'),
('Las Verduras','Warzywa','la coliflor','kalafior'),
('Las Verduras','Warzywa','la espinaca','szpinak'),
('Las Verduras','Warzywa','el calabacín','cukinia'),
('Las Verduras','Warzywa','la berenjena','bakłażan'),
('Las Verduras','Warzywa','la calabaza','dynia'),
('Las Verduras','Warzywa','el guisante','groszek'),
('Las Verduras','Warzywa','la judía verde','fasolka szparagowa'),
('Las Verduras','Warzywa','el maíz','kukurydza'),
('Las Verduras','Warzywa','el champiñón','pieczarka'),
('Las Verduras','Warzywa','la seta','grzyb'),
('Las Verduras','Warzywa','el rábano','rzodkiewka'),
('Las Verduras','Warzywa','el apio','seler'),
('Las Verduras','Warzywa','el espárrago','szparag'),
('Las Verduras','Warzywa','el puerro','por'),
('Las Verduras','Warzywa','la remolacha','burak'),
('Las Verduras','Warzywa','la alcachofa','karczoch'),
('Las Verduras','Warzywa','la batata / el boniato','batat / słodki ziemniak'),
('Las Verduras','Warzywa','el aguacate','awokado'),
('Las Verduras','Warzywa','el perejil','pietruszka (nać)'),
('Las Verduras','Warzywa','el cilantro','kolendra'),
('Las Verduras','Warzywa','la albahaca','bazylia'),
('Las Verduras','Warzywa','el romero','rozmaryn'),
('Las Verduras','Warzywa','el tomillo','tymianek'),
('Las Verduras','Warzywa','el orégano','oregano'),
('Las Verduras','Warzywa','el laurel','liść laurowy'),
('Las Verduras','Warzywa','la menta','mięta'),
('Las Verduras','Warzywa','el eneldo','koperek'),
('Las Verduras','Warzywa','el cebollino','szczypiorek'),
('Las Verduras','Warzywa','el pimentón','papryka w proszku'),
('Las Verduras','Warzywa','el chile','papryczka chili'),
('Las Verduras','Warzywa','el jalapeño','jalapeño'),
('Las Verduras','Warzywa','el nabo','rzepa'),
('Las Verduras','Warzywa','el hinojo','koper włoski'),
('Las Verduras','Warzywa','la acelga','boćwina'),
('Las Verduras','Warzywa','el berro','rukiew wodna'),
('Las Verduras','Warzywa','la rúcula','rukola'),
('Las Verduras','Warzywa','el germinado','kiełek'),
('Las Verduras','Warzywa','la trufa','trufla'),
('Las Verduras','Warzywa','la legumbre','roślina strączkowa');
