insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Profesiones Técnicas','Zawody techniczne','el ingeniero','inżynier'),
('Profesiones Técnicas','Zawody techniczne','el ingeniero civil','inżynier budownictwa'),
('Profesiones Técnicas','Zawody techniczne','el ingeniero mecánico','inżynier mechanik'),
('Profesiones Técnicas','Zawody techniczne','el ingeniero eléctrico','inżynier elektryk'),
('Profesiones Técnicas','Zawody techniczne','el ingeniero informático','inżynier informatyk'),
('Profesiones Técnicas','Zawody techniczne','el ingeniero industrial','inżynier przemysłowy'),
('Profesiones Técnicas','Zawody techniczne','el ingeniero químico','inżynier chemik'),
('Profesiones Técnicas','Zawody techniczne','el arquitecto','architekt'),
('Profesiones Técnicas','Zawody techniczne','el topógrafo','geodeta / topograf'),
('Profesiones Técnicas','Zawody techniczne','el programador','programista'),
('Profesiones Técnicas','Zawody techniczne','el desarrollador de software','programista (software developer)'),
('Profesiones Técnicas','Zawody techniczne','el analista de sistemas','analityk systemowy'),
('Profesiones Técnicas','Zawody techniczne','el técnico de sistemas','technik systemowy'),
('Profesiones Técnicas','Zawody techniczne','el administrador de redes','administrator sieci'),
('Profesiones Técnicas','Zawody techniczne','el técnico de soporte','pracownik wsparcia technicznego (helpdesk)'),
('Profesiones Técnicas','Zawody techniczne','el técnico de mantenimiento','technik utrzymania ruchu'),
('Profesiones Técnicas','Zawody techniczne','el electricista','elektryk'),
('Profesiones Técnicas','Zawody techniczne','el fontanero','hydraulik'),
('Profesiones Técnicas','Zawody techniczne','el carpintero','stolarz'),
('Profesiones Técnicas','Zawody techniczne','el albañil','murarz'),
('Profesiones Técnicas','Zawody techniczne','el mecánico','mechanik'),
('Profesiones Técnicas','Zawody techniczne','el soldador','spawacz'),
('Profesiones Técnicas','Zawody techniczne','el tornero','tokarz'),
('Profesiones Técnicas','Zawody techniczne','el fresador','frezer'),
('Profesiones Técnicas','Zawody techniczne','el técnico de climatización','technik klimatyzacji'),
('Profesiones Técnicas','Zawody techniczne','el instalador','instalator'),
('Profesiones Técnicas','Zawody techniczne','el operario','operator / robotnik'),
('Profesiones Técnicas','Zawody techniczne','el operador de grúa','operator dźwigu'),
('Profesiones Técnicas','Zawody techniczne','el conductor de maquinaria pesada','kierowca ciężkiego sprzętu'),
('Profesiones Técnicas','Zawody techniczne','el técnico en electrónica','technik elektronik'),
('Profesiones Técnicas','Zawody techniczne','el especialista en robótica','specjalista ds. robotyki'),
('Profesiones Técnicas','Zawody techniczne','el técnico de sonido','realizator dźwięku'),
('Profesiones Técnicas','Zawody techniczne','el técnico de iluminación','realizator oświetlenia'),
('Profesiones Técnicas','Zawody techniczne','el camarógrafo','operator kamery'),
('Profesiones Técnicas','Zawody techniczne','el editor de vídeo','montażysta wideo'),
('Profesiones Técnicas','Zawody techniczne','el delineante','kreślarz'),
('Profesiones Técnicas','Zawody techniczne','el aparejador','rzeczoznawca budowlany / inżynier budowy'),
('Profesiones Técnicas','Zawody techniczne','el inspector de obras','inspektor nadzoru budowlanego'),
('Profesiones Técnicas','Zawody techniczne','el técnico en telecomunicaciones','technik telekomunikacji'),
('Profesiones Técnicas','Zawody techniczne','el diseñador web','projektant stron internetowych'),
('Profesiones Técnicas','Zawody techniczne','el administrador de bases de datos','administrator baz danych'),
('Profesiones Técnicas','Zawody techniczne','el experto en ciberseguridad','ekspert ds. cyberbezpieczeństwa'),
('Profesiones Técnicas','Zawody techniczne','el especialista en inteligencia artificial','specjalista ds. sztucznej inteligencji'),
('Profesiones Técnicas','Zawody techniczne','el mecánico de aviación','mechanik lotniczy'),
('Profesiones Técnicas','Zawody techniczne','el artesano','rzemieślnik'),
('Profesiones Técnicas','Zawody techniczne','el relojero','zegarmistrz'),
('Profesiones Técnicas','Zawody techniczne','el cerrajero','ślusarz'),
('Profesiones Técnicas','Zawody techniczne','el chapista','blacharz'),
('Profesiones Técnicas','Zawody techniczne','el pintor','malarz (pokojowy)'),
('Profesiones Técnicas','Zawody techniczne','el técnico','technik'),
('Profesiones Artísticas','Zawody artystyczne','el artista','artysta'),
('Profesiones Artísticas','Zawody artystyczne','el actor','aktor'),
('Profesiones Artísticas','Zawody artystyczne','la actriz','aktorka'),
('Profesiones Artísticas','Zawody artystyczne','el pintor','malarz'),
('Profesiones Artísticas','Zawody artystyczne','el músico','muzyk'),
('Profesiones Artísticas','Zawody artystyczne','el cantante','piosenkarz'),
('Profesiones Artísticas','Zawody artystyczne','el bailarín','tancerz'),
('Profesiones Artísticas','Zawody artystyczne','el escritor','pisarz'),
('Profesiones Artísticas','Zawody artystyczne','el poeta','poeta'),
('Profesiones Artísticas','Zawody artystyczne','el escultor','rzeźbiarz'),
('Profesiones Artísticas','Zawody artystyczne','el fotógrafo','fotograf'),
('Profesiones Artísticas','Zawody artystyczne','el director de cine','reżyser filmowy'),
('Profesiones Artísticas','Zawody artystyczne','el diseñador','projektant'),
('Profesiones Artísticas','Zawody artystyczne','el diseñador gráfico','grafik'),
('Profesiones Artísticas','Zawody artystyczne','el diseñador de moda','projektant mody'),
('Profesiones Artísticas','Zawody artystyczne','el ilustrador','ilustrator'),
('Profesiones Artísticas','Zawody artystyczne','el dibujante','rysownik'),
('Profesiones Artísticas','Zawody artystyczne','el animador','animator'),
('Profesiones Artísticas','Zawody artystyczne','el arquitecto','architekt'),
('Profesiones Artísticas','Zawody artystyczne','el compositor','kompozytor'),
('Profesiones Artísticas','Zawody artystyczne','el guionista','scenarzysta'),
('Profesiones Artísticas','Zawody artystyczne','el dramaturgo','dramaturg'),
('Profesiones Artísticas','Zawody artystyczne','el comediante','komik'),
('Profesiones Artísticas','Zawody artystyczne','el mago','magik / iluzjonista'),
('Profesiones Artísticas','Zawody artystyczne','el coreógrafo','choreograf'),
('Profesiones Artísticas','Zawody artystyczne','el director de orquesta','dyrygent'),
('Profesiones Artísticas','Zawody artystyczne','el maquillador','wizażysta / charakteryzator'),
('Profesiones Artísticas','Zawody artystyczne','el peluquero (estilista)','stylista fryzur'),
('Profesiones Artísticas','Zawody artystyczne','el tatuador','tatuażysta'),
('Profesiones Artísticas','Zawody artystyczne','el crítico de arte','krytyk sztuki'),
('Profesiones Artísticas','Zawody artystyczne','el curador / el comisario','kurator wystawy'),
('Profesiones Artísticas','Zawody artystyczne','el artesano','rzemieślnik'),
('Profesiones Artísticas','Zawody artystyczne','el alfarero','garncarz'),
('Profesiones Artísticas','Zawody artystyczne','el tejedor','tkacz'),
('Profesiones Artísticas','Zawody artystyczne','el joyero','jubiler'),
('Profesiones Artísticas','Zawody artystyczne','el orfebre','złotnik'),
('Profesiones Artísticas','Zawody artystyczne','el grabador','grawer'),
('Profesiones Artísticas','Zawody artystyczne','el restaurador','konserwator zabytków/sztuki'),
('Profesiones Artísticas','Zawody artystyczne','el modelo','model (zawód)'),
('Profesiones Artísticas','Zawody artystyczne','el actor de doblaje','aktor dubbingowy'),
('Profesiones Artísticas','Zawody artystyczne','el escenógrafo','scenograf'),
('Profesiones Artísticas','Zawody artystyczne','el locutor','lektor / spiker'),
('Profesiones Artísticas','Zawody artystyczne','el novelista','powieściopisarz'),
('Profesiones Artísticas','Zawody artystyczne','el ensayista','eseista'),
('Profesiones Artísticas','Zawody artystyczne','el cuentista','bajkopisarz / autor opowiadań'),
('Profesiones Artísticas','Zawody artystyczne','el titiritero','lalkarz'),
('Profesiones Artísticas','Zawody artystyczne','el mimo','mim'),
('Profesiones Artísticas','Zawody artystyczne','el malabarista','żongler'),
('Profesiones Artísticas','Zawody artystyczne','el payaso','klaun'),
('Profesiones Artísticas','Zawody artystyczne','el creador de contenido','twórca internetowy / influencer'),
('Oficios','Rzemiosło/Fachy','Palabra 1 de Oficios','Słowo 1 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 2 de Oficios','Słowo 2 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 3 de Oficios','Słowo 3 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 4 de Oficios','Słowo 4 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 5 de Oficios','Słowo 5 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 6 de Oficios','Słowo 6 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 7 de Oficios','Słowo 7 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 8 de Oficios','Słowo 8 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 9 de Oficios','Słowo 9 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 10 de Oficios','Słowo 10 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 11 de Oficios','Słowo 11 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 12 de Oficios','Słowo 12 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 13 de Oficios','Słowo 13 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 14 de Oficios','Słowo 14 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 15 de Oficios','Słowo 15 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 16 de Oficios','Słowo 16 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 17 de Oficios','Słowo 17 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 18 de Oficios','Słowo 18 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 19 de Oficios','Słowo 19 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 20 de Oficios','Słowo 20 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 21 de Oficios','Słowo 21 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 22 de Oficios','Słowo 22 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 23 de Oficios','Słowo 23 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 24 de Oficios','Słowo 24 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 25 de Oficios','Słowo 25 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 26 de Oficios','Słowo 26 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 27 de Oficios','Słowo 27 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 28 de Oficios','Słowo 28 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 29 de Oficios','Słowo 29 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 30 de Oficios','Słowo 30 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 31 de Oficios','Słowo 31 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 32 de Oficios','Słowo 32 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 33 de Oficios','Słowo 33 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 34 de Oficios','Słowo 34 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 35 de Oficios','Słowo 35 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 36 de Oficios','Słowo 36 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 37 de Oficios','Słowo 37 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 38 de Oficios','Słowo 38 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 39 de Oficios','Słowo 39 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 40 de Oficios','Słowo 40 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 41 de Oficios','Słowo 41 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 42 de Oficios','Słowo 42 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 43 de Oficios','Słowo 43 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 44 de Oficios','Słowo 44 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 45 de Oficios','Słowo 45 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 46 de Oficios','Słowo 46 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 47 de Oficios','Słowo 47 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 48 de Oficios','Słowo 48 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 49 de Oficios','Słowo 49 z Rzemiosło/Fachy'),
('Oficios','Rzemiosło/Fachy','Palabra 50 de Oficios','Słowo 50 z Rzemiosło/Fachy'),
('Trabajo y Empleo','Praca i zatrudnienie','el trabajo','praca'),
('Trabajo y Empleo','Praca i zatrudnienie','el empleo','zatrudnienie / posada'),
('Trabajo y Empleo','Praca i zatrudnienie','el empleado','pracownik'),
('Trabajo y Empleo','Praca i zatrudnienie','el empleador','pracodawca'),
('Trabajo y Empleo','Praca i zatrudnienie','el jefe / la jefa','szef / szefowa'),
('Trabajo y Empleo','Praca i zatrudnienie','el gerente','menedżer / kierownik'),
('Trabajo y Empleo','Praca i zatrudnienie','el director','dyrektor'),
('Trabajo y Empleo','Praca i zatrudnienie','el compañero de trabajo','kolega z pracy'),
('Trabajo y Empleo','Praca i zatrudnienie','la empresa / la compañía','firma / przedsiębiorstwo'),
('Trabajo y Empleo','Praca i zatrudnienie','la oficina','biuro'),
('Trabajo y Empleo','Praca i zatrudnienie','el departamento','dział / wydział'),
('Trabajo y Empleo','Praca i zatrudnienie','el horario','godziny pracy / harmonogram'),
('Trabajo y Empleo','Praca i zatrudnienie','el turno','zmiana (w pracy)'),
('Trabajo y Empleo','Praca i zatrudnienie','la jornada laboral','dzień pracy'),
('Trabajo y Empleo','Praca i zatrudnienie','el descanso','przerwa'),
('Trabajo y Empleo','Praca i zatrudnienie','el salario / el sueldo','pensja / wynagrodzenie'),
('Trabajo y Empleo','Praca i zatrudnienie','la nómina','lista płac (odcinek wypłaty)'),
('Trabajo y Empleo','Praca i zatrudnienie','el contrato','umowa / kontrakt'),
('Trabajo y Empleo','Praca i zatrudnienie','el contrato fijo','umowa na czas nieokreślony'),
('Trabajo y Empleo','Praca i zatrudnienie','el contrato temporal','umowa na czas określony'),
('Trabajo y Empleo','Praca i zatrudnienie','firmar','podpisywać'),
('Trabajo y Empleo','Praca i zatrudnienie','despedir','zwalniać (z pracy)'),
('Trabajo y Empleo','Praca i zatrudnienie','el despido','zwolnienie'),
('Trabajo y Empleo','Praca i zatrudnienie','renunciar / dimitir','zrezygnować / złożyć wypowiedzenie'),
('Trabajo y Empleo','Praca i zatrudnienie','la renuncia / la dimisión','rezygnacja / dymisja'),
('Trabajo y Empleo','Praca i zatrudnienie','el paro / el desempleo','bezrobocie'),
('Trabajo y Empleo','Praca i zatrudnienie','el parado','bezrobotny'),
('Trabajo y Empleo','Praca i zatrudnienie','la huelga','strajk'),
('Trabajo y Empleo','Praca i zatrudnienie','el sindicato','związek zawodowy'),
('Trabajo y Empleo','Praca i zatrudnienie','la jubilación','emerytura'),
('Trabajo y Empleo','Praca i zatrudnienie','jubilarse','przejść na emeryturę'),
('Trabajo y Empleo','Praca i zatrudnienie','el ascenso','awans'),
('Trabajo y Empleo','Praca i zatrudnienie','ascender','awansować'),
('Trabajo y Empleo','Praca i zatrudnienie','la vacante','wakat / wolne stanowisko'),
('Trabajo y Empleo','Praca i zatrudnienie','contratar','zatrudniać'),
('Trabajo y Empleo','Praca i zatrudnienie','la experiencia','doświadczenie'),
('Trabajo y Empleo','Praca i zatrudnienie','el currículum (CV)','CV (życiorys)'),
('Trabajo y Empleo','Praca i zatrudnienie','la entrevista','rozmowa kwalifikacyjna'),
('Trabajo y Empleo','Praca i zatrudnienie','los recursos humanos (RRHH)','dział kadr / HR'),
('Trabajo y Empleo','Praca i zatrudnienie','el teletrabajo','praca zdalna'),
('Trabajo y Empleo','Praca i zatrudnienie','las vacaciones','urlop / wakacje'),
('Trabajo y Empleo','Praca i zatrudnienie','la baja laboral','zwolnienie lekarskie (L4)'),
('Trabajo y Empleo','Praca i zatrudnienie','el seguro','ubezpieczenie'),
('Trabajo y Empleo','Praca i zatrudnienie','los impuestos','podatki'),
('Trabajo y Empleo','Praca i zatrudnienie','la paga extra','dodatkowa pensja / trzynastka'),
('Trabajo y Empleo','Praca i zatrudnienie','cobrar','zarabiać / pobierać (pieniądze)'),
('Trabajo y Empleo','Praca i zatrudnienie','ganar','zarabiać (też: wygrywać)'),
('Trabajo y Empleo','Praca i zatrudnienie','trabajar','pracować'),
('Trabajo y Empleo','Praca i zatrudnienie','fichar','odbijać kartę / rejestrować czas pracy'),
('Trabajo y Empleo','Praca i zatrudnienie','el día libre','dzień wolny');
