insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Árboles','Drzewa','el árbol','drzewo'),
('Árboles','Drzewa','el tronco','pień'),
('Árboles','Drzewa','la rama','gałąź'),
('Árboles','Drzewa','la hoja','liść'),
('Árboles','Drzewa','la raíz','korzeń'),
('Árboles','Drzewa','la corteza','kora'),
('Árboles','Drzewa','la savia','sok (drzewny)'),
('Árboles','Drzewa','el roble','dąb'),
('Árboles','Drzewa','el pino','sosna'),
('Árboles','Drzewa','el abeto','jodła'),
('Árboles','Drzewa','el haya','buk'),
('Árboles','Drzewa','el abedul','brzoza'),
('Árboles','Drzewa','el sauce','wierzba'),
('Árboles','Drzewa','el sauce llorón','wierzba płacząca'),
('Árboles','Drzewa','el álamo','topola'),
('Árboles','Drzewa','el fresno','jesion'),
('Árboles','Drzewa','el olmo','wiąz'),
('Árboles','Drzewa','el arce','klon'),
('Árboles','Drzewa','el castaño','kasztanowiec'),
('Árboles','Drzewa','el nogal','orzech (drzewo)'),
('Árboles','Drzewa','el almendro','migdałowiec'),
('Árboles','Drzewa','el olivo','drzewo oliwne / oliwka'),
('Árboles','Drzewa','el manzano','jabłoń'),
('Árboles','Drzewa','el peral','grusza'),
('Árboles','Drzewa','el ciruelo','śliwa'),
('Árboles','Drzewa','el cerezo','czereśnia / wiśnia (drzewo)'),
('Árboles','Drzewa','el limonero','drzewo cytrynowe'),
('Árboles','Drzewa','el naranjo','drzewo pomarańczowe'),
('Árboles','Drzewa','el melocotonero','brzoskwinia (drzewo)'),
('Árboles','Drzewa','la palmera','palma'),
('Árboles','Drzewa','el eucalipto','eukaliptus'),
('Árboles','Drzewa','el baobab','baobab'),
('Árboles','Drzewa','el bonsái','bonsai'),
('Árboles','Drzewa','el bosque','las'),
('Árboles','Drzewa','la selva','puszcza / dżungla'),
('Árboles','Drzewa','plantar','sadzić'),
('Árboles','Drzewa','talar','ścinać (drzewa)'),
('Árboles','Drzewa','la madera','drewno'),
('Árboles','Drzewa','la leña','drewno na opał'),
('Árboles','Drzewa','el tocón','pniak'),
('Árboles','Drzewa','el bosque de coníferas','las iglasty'),
('Árboles','Drzewa','el bosque de hoja caduca','las liściasty'),
('Árboles','Drzewa','la hoja perenne','liść zimozielony'),
('Árboles','Drzewa','la hoja caduca','liść opadający'),
('Árboles','Drzewa','dar sombra','dawać cień'),
('Árboles','Drzewa','el fruto','owoc'),
('Árboles','Drzewa','la semilla','nasiono'),
('Árboles','Drzewa','la piña','szyszka / ananas'),
('Árboles','Drzewa','florecer','kwitnąć'),
('Árboles','Drzewa','el follaje','listowie / korona drzewa'),
('Flores','Kwiaty','la flor','kwiat'),
('Flores','Kwiaty','el pétalo','płatek'),
('Flores','Kwiaty','el tallo','łodyga'),
('Flores','Kwiaty','la espina','kolec'),
('Flores','Kwiaty','la hoja','liść'),
('Flores','Kwiaty','el capullo','pąk'),
('Flores','Kwiaty','el polen','pyłek'),
('Flores','Kwiaty','el néctar','nektar'),
('Flores','Kwiaty','la rosa','róża'),
('Flores','Kwiaty','el tulipán','tulipan'),
('Flores','Kwiaty','la margarita','stokrotka / margaretka'),
('Flores','Kwiaty','el clavel','goździk'),
('Flores','Kwiaty','el girasol','słonecznik'),
('Flores','Kwiaty','la orquídea','orchidea / storczyk'),
('Flores','Kwiaty','el lirio','lilia / irys'),
('Flores','Kwiaty','la azucena','lilia (biała)'),
('Flores','Kwiaty','la violeta','fiołek'),
('Flores','Kwiaty','el pensamiento','bratek'),
('Flores','Kwiaty','la amapola','mak'),
('Flores','Kwiaty','el jazmín','jaśmin'),
('Flores','Kwiaty','la lavanda','lawenda'),
('Flores','Kwiaty','la lila','bez (lilak)'),
('Flores','Kwiaty','la camelia','kamelia'),
('Flores','Kwiaty','el loto','lotos'),
('Flores','Kwiaty','la peonía','piwonia'),
('Flores','Kwiaty','el narciso','narcyz'),
('Flores','Kwiaty','el crisantemo','chryzantema'),
('Flores','Kwiaty','el diente de león','mniszek lekarski (mlecz)'),
('Flores','Kwiaty','la begonia','begonia'),
('Flores','Kwiaty','el geranio','pelargonia / geranium'),
('Flores','Kwiaty','la dalia','dalia'),
('Flores','Kwiaty','el gladiolo','mieczyk (gladiola)'),
('Flores','Kwiaty','la anémona','zawilec (anemon)'),
('Flores','Kwiaty','la magnolia','magnolia'),
('Flores','Kwiaty','el hibisco','hibiskus'),
('Flores','Kwiaty','florecer','kwitnąć'),
('Flores','Kwiaty','marchitarse','więdnąć'),
('Flores','Kwiaty','oler','pachnieć / wąchać'),
('Flores','Kwiaty','el aroma','aromat / zapach'),
('Flores','Kwiaty','el ramo','bukiet'),
('Flores','Kwiaty','el florero / el jarrón','wazon'),
('Flores','Kwiaty','plantar','sadzić'),
('Flores','Kwiaty','regar','podlewać'),
('Flores','Kwiaty','el jardín','ogród'),
('Flores','Kwiaty','la maceta','doniczka'),
('Flores','Kwiaty','la floristería','kwiaciarnia'),
('Flores','Kwiaty','el florista','florysta / kwiaciarz'),
('Flores','Kwiaty','silvestre','dziki / polny'),
('Flores','Kwiaty','cultivar','uprawiać (rośliny)'),
('Flores','Kwiaty','la corona de flores','wieniec z kwiatów'),
('Accidentes Geográficos','Ukształtowanie terenu','el accidente geográfico','ukształtowanie terenu'),
('Accidentes Geográficos','Ukształtowanie terenu','la montaña','góra'),
('Accidentes Geográficos','Ukształtowanie terenu','la cordillera','łańcuch górski'),
('Accidentes Geográficos','Ukształtowanie terenu','el volcán','wulkan'),
('Accidentes Geográficos','Ukształtowanie terenu','la colina / el cerro','wzgórze'),
('Accidentes Geográficos','Ukształtowanie terenu','el valle','dolina'),
('Accidentes Geográficos','Ukształtowanie terenu','la llanura','równina'),
('Accidentes Geográficos','Ukształtowanie terenu','la meseta','płaskowyż'),
('Accidentes Geográficos','Ukształtowanie terenu','el cañón','kanion / wąwóz'),
('Accidentes Geográficos','Ukształtowanie terenu','el barranco','jar / wąwóz'),
('Accidentes Geográficos','Ukształtowanie terenu','el precipicio','przepaść'),
('Accidentes Geográficos','Ukształtowanie terenu','el acantilado','klif'),
('Accidentes Geográficos','Ukształtowanie terenu','la costa','wybrzeże'),
('Accidentes Geográficos','Ukształtowanie terenu','la playa','plaża'),
('Accidentes Geográficos','Ukształtowanie terenu','el cabo','przylądek'),
('Accidentes Geográficos','Ukształtowanie terenu','la península','półwysep'),
('Accidentes Geográficos','Ukształtowanie terenu','el istmo','przesmyk'),
('Accidentes Geográficos','Ukształtowanie terenu','la isla','wyspa'),
('Accidentes Geográficos','Ukształtowanie terenu','el archipiélago','archipelag'),
('Accidentes Geográficos','Ukształtowanie terenu','el golfo','zatoka (duża)'),
('Accidentes Geográficos','Ukształtowanie terenu','la bahía','zatoka (mniejsza)'),
('Accidentes Geográficos','Ukształtowanie terenu','la cala','zatoczka'),
('Accidentes Geográficos','Ukształtowanie terenu','el estrecho','cieśnina'),
('Accidentes Geográficos','Ukształtowanie terenu','el océano','ocean'),
('Accidentes Geográficos','Ukształtowanie terenu','el mar','morze'),
('Accidentes Geográficos','Ukształtowanie terenu','el lago','jezioro'),
('Accidentes Geográficos','Ukształtowanie terenu','la laguna','laguna / jeziorko'),
('Accidentes Geográficos','Ukształtowanie terenu','el río','rzeka'),
('Accidentes Geográficos','Ukształtowanie terenu','el arroyo','strumień'),
('Accidentes Geográficos','Ukształtowanie terenu','el manantial','źródło'),
('Accidentes Geográficos','Ukształtowanie terenu','la cascada / la catarata','wodospad'),
('Accidentes Geográficos','Ukształtowanie terenu','el delta','delta (rzeki)'),
('Accidentes Geográficos','Ukształtowanie terenu','el estuario','estuarium'),
('Accidentes Geográficos','Ukształtowanie terenu','el pantano / la marisma','bagno / moczary'),
('Accidentes Geográficos','Ukształtowanie terenu','el glaciar','lodowiec'),
('Accidentes Geográficos','Ukształtowanie terenu','el fiordo','fiord'),
('Accidentes Geográficos','Ukształtowanie terenu','el desierto','pustynia'),
('Accidentes Geográficos','Ukształtowanie terenu','el oasis','oaza'),
('Accidentes Geográficos','Ukształtowanie terenu','la duna','wydma'),
('Accidentes Geográficos','Ukształtowanie terenu','la selva','dżungla'),
('Accidentes Geográficos','Ukształtowanie terenu','el bosque','las'),
('Accidentes Geográficos','Ukształtowanie terenu','la cueva / la caverna','jaskinia'),
('Accidentes Geográficos','Ukształtowanie terenu','la sima','rozpadlina'),
('Accidentes Geográficos','Ukształtowanie terenu','el pico / la cima','szczyt (góry)'),
('Accidentes Geográficos','Ukształtowanie terenu','la ladera','zbocze'),
('Accidentes Geográficos','Ukształtowanie terenu','la falda (de la montaña)','podnóże (góry)'),
('Accidentes Geográficos','Ukształtowanie terenu','el cráter','krater'),
('Accidentes Geográficos','Ukształtowanie terenu','el arrecife','rafa'),
('Accidentes Geográficos','Ukształtowanie terenu','el atolón','atol'),
('Accidentes Geográficos','Ukształtowanie terenu','la depresión','depresja (terenowa)'),
('Catástrofes Naturales','Katastrofy naturalne','la catástrofe natural','katastrofa naturalna'),
('Catástrofes Naturales','Katastrofy naturalne','el desastre','katastrofa / klęska'),
('Catástrofes Naturales','Katastrofy naturalne','el terremoto / el seísmo','trzęsienie ziemi'),
('Catástrofes Naturales','Katastrofy naturalne','el temblor','wstrząs'),
('Catástrofes Naturales','Katastrofy naturalne','la réplica','wstrząs wtórny'),
('Catástrofes Naturales','Katastrofy naturalne','el epicentro','epicentrum'),
('Catástrofes Naturales','Katastrofy naturalne','la magnitud','magnituda / siła'),
('Catástrofes Naturales','Katastrofy naturalne','el maremoto','trzęsienie ziemi pod wodą'),
('Catástrofes Naturales','Katastrofy naturalne','el tsunami','tsunami'),
('Catástrofes Naturales','Katastrofy naturalne','la erupción volcánica','erupcja wulkanu'),
('Catástrofes Naturales','Katastrofy naturalne','la lava','lawa'),
('Catástrofes Naturales','Katastrofy naturalne','la ceniza','popiół'),
('Catástrofes Naturales','Katastrofy naturalne','el huracán','huragan'),
('Catástrofes Naturales','Katastrofy naturalne','el tornado','tornado'),
('Catástrofes Naturales','Katastrofy naturalne','el tifón','tajfun'),
('Catástrofes Naturales','Katastrofy naturalne','el ciclón','cyklon'),
('Catástrofes Naturales','Katastrofy naturalne','la tormenta','burza'),
('Catástrofes Naturales','Katastrofy naturalne','la tormenta tropical','burza tropikalna'),
('Catástrofes Naturales','Katastrofy naturalne','la tormenta de arena','burza piaskowa'),
('Catástrofes Naturales','Katastrofy naturalne','la tormenta de nieve','burza śnieżna'),
('Catástrofes Naturales','Katastrofy naturalne','la ventisca','zamieć'),
('Catástrofes Naturales','Katastrofy naturalne','el granizo / la granizada','grad / gradobicie'),
('Catástrofes Naturales','Katastrofy naturalne','la inundación','powódź'),
('Catástrofes Naturales','Katastrofy naturalne','desbordarse','wystąpić z brzegów'),
('Catástrofes Naturales','Katastrofy naturalne','la sequía','susza'),
('Catástrofes Naturales','Katastrofy naturalne','el incendio forestal','pożar lasu'),
('Catástrofes Naturales','Katastrofy naturalne','la avalancha / el alud','lawina'),
('Catástrofes Naturales','Katastrofy naturalne','el deslizamiento de tierra','osuwisko'),
('Catástrofes Naturales','Katastrofy naturalne','la ola de calor','fala upałów'),
('Catástrofes Naturales','Katastrofy naturalne','la ola de frío','fala mrozów'),
('Catástrofes Naturales','Katastrofy naturalne','el rayo','piorun / promień'),
('Catástrofes Naturales','Katastrofy naturalne','el relámpago','błyskawica'),
('Catástrofes Naturales','Katastrofy naturalne','el trueno','grzmot'),
('Catástrofes Naturales','Katastrofy naturalne','la emergencia','nagły wypadek / stan wyjątkowy'),
('Catástrofes Naturales','Katastrofy naturalne','la alarma','alarm'),
('Catástrofes Naturales','Katastrofy naturalne','la sirena','syrena'),
('Catástrofes Naturales','Katastrofy naturalne','el refugio','schron'),
('Catástrofes Naturales','Katastrofy naturalne','el rescate','ratunek'),
('Catástrofes Naturales','Katastrofy naturalne','rescatar','ratować'),
('Catástrofes Naturales','Katastrofy naturalne','el rescatista','ratownik'),
('Catástrofes Naturales','Katastrofy naturalne','el bombero','strażak'),
('Catástrofes Naturales','Katastrofy naturalne','la víctima','ofiara'),
('Catástrofes Naturales','Katastrofy naturalne','el herido','ranny'),
('Catástrofes Naturales','Katastrofy naturalne','el superviviente','ocalały'),
('Catástrofes Naturales','Katastrofy naturalne','el refugiado','uchodźca'),
('Catástrofes Naturales','Katastrofy naturalne','la evacuación','ewakuacja'),
('Catástrofes Naturales','Katastrofy naturalne','evacuar','ewakuować'),
('Catástrofes Naturales','Katastrofy naturalne','destruir','niszczyć'),
('Catástrofes Naturales','Katastrofy naturalne','la ruina','ruina'),
('Catástrofes Naturales','Katastrofy naturalne','los escombros','gruzy');
