insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Verbos Regulares ER','Czasowniki regularne ER','comer','jeść'),
('Verbos Regulares ER','Czasowniki regularne ER','beber','pić'),
('Verbos Regulares ER','Czasowniki regularne ER','comprender','rozumieć (głęboko)'),
('Verbos Regulares ER','Czasowniki regularne ER','aprender','uczyć się (przyswajać)'),
('Verbos Regulares ER','Czasowniki regularne ER','leer','czytać'),
('Verbos Regulares ER','Czasowniki regularne ER','vender','sprzedawać'),
('Verbos Regulares ER','Czasowniki regularne ER','responder','odpowiadać'),
('Verbos Regulares ER','Czasowniki regularne ER','correr','biec / biegać'),
('Verbos Regulares ER','Czasowniki regularne ER','deber','musieć / mieć powinność'),
('Verbos Regulares ER','Czasowniki regularne ER','esconder','chować / ukrywać'),
('Verbos Regulares ER','Czasowniki regularne ER','prometer','obiecywać'),
('Verbos Regulares ER','Czasowniki regularne ER','creer','wierzyć / sądzić'),
('Verbos Regulares ER','Czasowniki regularne ER','romper','psuć / łamać / rwać'),
('Verbos Regulares ER','Czasowniki regularne ER','meter','wkładać'),
('Verbos Regulares ER','Czasowniki regularne ER','cometer','popełniać (np. błąd)'),
('Verbos Regulares ER','Czasowniki regularne ER','depender','zależeć'),
('Verbos Regulares ER','Czasowniki regularne ER','ofender','obrażać'),
('Verbos Regulares ER','Czasowniki regularne ER','proceder','postępować / pochodzić'),
('Verbos Regulares ER','Czasowniki regularne ER','suceder','dziać się / następować'),
('Verbos Regulares ER','Czasowniki regularne ER','toser','kasłać'),
('Verbos Regulares ER','Czasowniki regularne ER','tejer','tkać / robić na drutach'),
('Verbos Regulares ER','Czasowniki regularne ER','sorprender','zaskakiwać'),
('Verbos Regulares ER','Czasowniki regularne ER','emprender','podejmować (działanie)'),
('Verbos Regulares ER','Czasowniki regularne ER','barrer','zamiatać'),
('Verbos Regulares ER','Czasowniki regularne ER','pretender','zamierzać / pretendować'),
('Verbos Regulares ER','Czasowniki regularne ER','ceder','ustępować'),
('Verbos Regulares ER','Czasowniki regularne ER','conceder','przyznawać / udzielać'),
('Verbos Regulares ER','Czasowniki regularne ER','someter','poddawać (kogoś czemuś)'),
('Verbos Regulares ER','Czasowniki regularne ER','temer','bać się'),
('Verbos Regulares ER','Czasowniki regularne ER','poseer','posiadać'),
('Verbos Regulares ER','Czasowniki regularne ER','lamer','lizać'),
('Verbos Regulares ER','Czasowniki regularne ER','absorber','absorbować / wchłaniać'),
('Verbos Regulares ER','Czasowniki regularne ER','acceder','uzyskiwać dostęp / zgadzać się'),
('Verbos Regulares ER','Czasowniki regularne ER','anteceder','poprzedzać'),
('Verbos Regulares ER','Czasowniki regularne ER','expeler','wydalać / wyrzucać'),
('Verbos Regulares ER','Czasowniki regularne ER','repeler','odstręczać / odpychać'),
('Verbos Regulares ER','Czasowniki regularne ER','proveer','zaopatrywać'),
('Verbos Regulares ER','Czasowniki regularne ER','suspender','oblewać (egzamin) / zawieszać'),
('Verbos Regulares ER','Czasowniki regularne ER','coser','szyć'),
('Verbos Regulares ER','Czasowniki regularne ER','prender','zapalać (np. światło) / łapać'),
('Verbos Regulares ER','Czasowniki regularne ER','defender','bronić (zmienna samogłoska w niektórych czasach, ale reg. ER w strukturze)'),
('Verbos Regulares ER','Czasowniki regularne ER','encender','włączać / zapalać'),
('Verbos Regulares ER','Czasowniki regularne ER','entender','rozumieć'),
('Verbos Regulares ER','Czasowniki regularne ER','perder','gubić / tracić'),
('Verbos Regulares ER','Czasowniki regularne ER','atender','obsługiwać / uważać'),
('Verbos Regulares ER','Czasowniki regularne ER','extender','rozciągać / poszerzać'),
('Verbos Regulares ER','Czasowniki regularne ER','resolver','rozwiązywać'),
('Verbos Regulares ER','Czasowniki regularne ER','volver','wracać'),
('Verbos Regulares ER','Czasowniki regularne ER','devolver','zwracać (coś)'),
('Verbos Regulares ER','Czasowniki regularne ER','envolver','owijać / pakować'),
('Verbos Regulares IR','Czasowniki regularne IR','vivir','żyć / mieszkać'),
('Verbos Regulares IR','Czasowniki regularne IR','escribir','pisać'),
('Verbos Regulares IR','Czasowniki regularne IR','abrir','otwierać'),
('Verbos Regulares IR','Czasowniki regularne IR','recibir','otrzymywać'),
('Verbos Regulares IR','Czasowniki regularne IR','permitir','pozwalać'),
('Verbos Regulares IR','Czasowniki regularne IR','subir','wchodzić (do góry) / wsiadać'),
('Verbos Regulares IR','Czasowniki regularne IR','dividir','dzielić'),
('Verbos Regulares IR','Czasowniki regularne IR','decidir','decydować'),
('Verbos Regulares IR','Czasowniki regularne IR','descubrir','odkrywać'),
('Verbos Regulares IR','Czasowniki regularne IR','sufrir','cierpieć'),
('Verbos Regulares IR','Czasowniki regularne IR','existir','istnieć'),
('Verbos Regulares IR','Czasowniki regularne IR','añadir','dodawać'),
('Verbos Regulares IR','Czasowniki regularne IR','admitir','przyznawać / wpuszczać'),
('Verbos Regulares IR','Czasowniki regularne IR','describir','opisywać'),
('Verbos Regulares IR','Czasowniki regularne IR','ocurrir','wydarzyć się / dziać się'),
('Verbos Regulares IR','Czasowniki regularne IR','asistir','uczestniczyć / brać udział'),
('Verbos Regulares IR','Czasowniki regularne IR','definir','definiować'),
('Verbos Regulares IR','Czasowniki regularne IR','discutir','kłócić się / dyskutować'),
('Verbos Regulares IR','Czasowniki regularne IR','insistir','nalegać'),
('Verbos Regulares IR','Czasowniki regularne IR','partir','kroić / wyruszać'),
('Verbos Regulares IR','Czasowniki regularne IR','imprimir','drukować'),
('Verbos Regulares IR','Czasowniki regularne IR','prohibir','zabraniać'),
('Verbos Regulares IR','Czasowniki regularne IR','resumir','podsumowywać'),
('Verbos Regulares IR','Czasowniki regularne IR','unir','łączyć'),
('Verbos Regulares IR','Czasowniki regularne IR','asumir','zakładać / przejmować'),
('Verbos Regulares IR','Czasowniki regularne IR','compartir','dzielić się (czymś)'),
('Verbos Regulares IR','Czasowniki regularne IR','cumplir','spełniać / kończyć (lata)'),
('Verbos Regulares IR','Czasowniki regularne IR','batir','ubijać / bić (rekord)'),
('Verbos Regulares IR','Czasowniki regularne IR','exprimir','wyciskać'),
('Verbos Regulares IR','Czasowniki regularne IR','hundir','topić / zatapiać'),
('Verbos Regulares IR','Czasowniki regularne IR','crujir','chrupać / skrzypieć'),
('Verbos Regulares IR','Czasowniki regularne IR','nutrir','odżywiać'),
('Verbos Regulares IR','Czasowniki regularne IR','omitir','pomijać'),
('Verbos Regulares IR','Czasowniki regularne IR','percibir','postrzegać'),
('Verbos Regulares IR','Czasowniki regularne IR','persistir','wytrwać / utrzymywać się'),
('Verbos Regulares IR','Czasowniki regularne IR','persuadir','przekonywać'),
('Verbos Regulares IR','Czasowniki regularne IR','presumir','chwalić się / zakładać'),
('Verbos Regulares IR','Czasowniki regularne IR','coincidir','zbiegać się / zgadzać się'),
('Verbos Regulares IR','Czasowniki regularne IR','confundir','mylić'),
('Verbos Regulares IR','Czasowniki regularne IR','deprimir','dołować / deprimować'),
('Verbos Regulares IR','Czasowniki regularne IR','evadir','unikać'),
('Verbos Regulares IR','Czasowniki regularne IR','fundir','topić (metal/ser)'),
('Verbos Regulares IR','Czasowniki regularne IR','presidir','przewodniczyć'),
('Verbos Regulares IR','Czasowniki regularne IR','rebatir','zbijać (argument)'),
('Verbos Regulares IR','Czasowniki regularne IR','recurrir','uciekać się do / odwoływać się'),
('Verbos Regulares IR','Czasowniki regularne IR','resistir','stawiać opór / wytrzymywać'),
('Verbos Regulares IR','Czasowniki regularne IR','sacudir','potrząsać'),
('Verbos Regulares IR','Czasowniki regularne IR','sobrevivir','przeżyć / przetrwać'),
('Verbos Regulares IR','Czasowniki regularne IR','suplir','zastępować / uzupełniać'),
('Verbos Regulares IR','Czasowniki regularne IR','latir','bić (o sercu)'),
('Verbos Irregulares','Czasowniki nieregularne','ser','być (cechy stałe)'),
('Verbos Irregulares','Czasowniki nieregularne','estar','być (stany, lokalizacja)'),
('Verbos Irregulares','Czasowniki nieregularne','ir','iść / jechać'),
('Verbos Irregulares','Czasowniki nieregularne','tener','mieć'),
('Verbos Irregulares','Czasowniki nieregularne','hacer','robić'),
('Verbos Irregulares','Czasowniki nieregularne','decir','mówić / powiedzieć'),
('Verbos Irregulares','Czasowniki nieregularne','poder','móc'),
('Verbos Irregulares','Czasowniki nieregularne','querer','chcieć / kochać'),
('Verbos Irregulares','Czasowniki nieregularne','saber','wiedzieć / umieć'),
('Verbos Irregulares','Czasowniki nieregularne','venir','przychodzić / przyjeżdżać'),
('Verbos Irregulares','Czasowniki nieregularne','ver','widzieć'),
('Verbos Irregulares','Czasowniki nieregularne','dar','dawać'),
('Verbos Irregulares','Czasowniki nieregularne','poner','kłaść / umieszczać'),
('Verbos Irregulares','Czasowniki nieregularne','salir','wychodzić / wyjeżdżać'),
('Verbos Irregulares','Czasowniki nieregularne','traer','przynosić'),
('Verbos Irregulares','Czasowniki nieregularne','oír','słyszeć'),
('Verbos Irregulares','Czasowniki nieregularne','jugar','grać / bawić się'),
('Verbos Irregulares','Czasowniki nieregularne','pensar','myśleć'),
('Verbos Irregulares','Czasowniki nieregularne','volver','wracać'),
('Verbos Irregulares','Czasowniki nieregularne','dormir','spać'),
('Verbos Irregulares','Czasowniki nieregularne','pedir','prosić / zamawiać'),
('Verbos Irregulares','Czasowniki nieregularne','sentir','czuć / żałować'),
('Verbos Irregulares','Czasowniki nieregularne','caer','spadać / upadać'),
('Verbos Irregulares','Czasowniki nieregularne','conocer','znać / poznawać'),
('Verbos Irregulares','Czasowniki nieregularne','conducir','prowadzić (pojazd)'),
('Verbos Irregulares','Czasowniki nieregularne','seguir','śledzić / kontynuować / podążać'),
('Verbos Irregulares','Czasowniki nieregularne','cerrar','zamykać'),
('Verbos Irregulares','Czasowniki nieregularne','empezar','zaczynać'),
('Verbos Irregulares','Czasowniki nieregularne','encontrar','znajdować'),
('Verbos Irregulares','Czasowniki nieregularne','recordar','pamiętać / przypominać'),
('Verbos Irregulares','Czasowniki nieregularne','perder','tracić / gubić'),
('Verbos Irregulares','Czasowniki nieregularne','contar','liczyć / opowiadać'),
('Verbos Irregulares','Czasowniki nieregularne','entender','rozumieć'),
('Verbos Irregulares','Czasowniki nieregularne','servir','służyć / serwować'),
('Verbos Irregulares','Czasowniki nieregularne','reír','śmiać się'),
('Verbos Irregulares','Czasowniki nieregularne','volar','latać'),
('Verbos Irregulares','Czasowniki nieregularne','mover','ruszać / poruszać'),
('Verbos Irregulares','Czasowniki nieregularne','elegir','wybierać'),
('Verbos Irregulares','Czasowniki nieregularne','nacer','rodzić się'),
('Verbos Irregulares','Czasowniki nieregularne','morir','umierać'),
('Verbos Irregulares','Czasowniki nieregularne','traducir','tłumaczyć (język)'),
('Verbos Irregulares','Czasowniki nieregularne','producir','produkować'),
('Verbos Irregulares','Czasowniki nieregularne','caber','mieścić się'),
('Verbos Irregulares','Czasowniki nieregularne','valer','kosztować / być wartym'),
('Verbos Irregulares','Czasowniki nieregularne','andar','chodzić / spacerować'),
('Verbos Irregulares','Czasowniki nieregularne','construir','budować'),
('Verbos Irregulares','Czasowniki nieregularne','huir','uciekać'),
('Verbos Irregulares','Czasowniki nieregularne','influir','wpływać (na coś)'),
('Verbos Irregulares','Czasowniki nieregularne','destruir','niszczyć'),
('Verbos Irregulares','Czasowniki nieregularne','oler','pachnieć / wąchać'),
('Verbos Reflexivos','Czasowniki zwrotne','lavarse','myć się'),
('Verbos Reflexivos','Czasowniki zwrotne','ducharse','brać prysznic'),
('Verbos Reflexivos','Czasowniki zwrotne','bañarse','kąpać się'),
('Verbos Reflexivos','Czasowniki zwrotne','peinarse','czesać się'),
('Verbos Reflexivos','Czasowniki zwrotne','afeitarse','golić się'),
('Verbos Reflexivos','Czasowniki zwrotne','despertarse','budzić się'),
('Verbos Reflexivos','Czasowniki zwrotne','levantarse','wstawać'),
('Verbos Reflexivos','Czasowniki zwrotne','acostarse','kłaść się (spać)'),
('Verbos Reflexivos','Czasowniki zwrotne','dormirse','zasypiać'),
('Verbos Reflexivos','Czasowniki zwrotne','vestirse','ubierać się'),
('Verbos Reflexivos','Czasowniki zwrotne','desvestirse','rozbierać się'),
('Verbos Reflexivos','Czasowniki zwrotne','quitarse','zdejmować (z siebie)'),
('Verbos Reflexivos','Czasowniki zwrotne','ponerse','zakładać (na siebie) / stawać się'),
('Verbos Reflexivos','Czasowniki zwrotne','maquillarse','malować się'),
('Verbos Reflexivos','Czasowniki zwrotne','cepillarse','szczotkować (np. zęby)'),
('Verbos Reflexivos','Czasowniki zwrotne','sentarse','siadać'),
('Verbos Reflexivos','Czasowniki zwrotne','llamarse','nazywać się'),
('Verbos Reflexivos','Czasowniki zwrotne','casarse','brać ślub / hajtasz się'),
('Verbos Reflexivos','Czasowniki zwrotne','divorciarse','rozwodzić się'),
('Verbos Reflexivos','Czasowniki zwrotne','enamorarse','zakochać się'),
('Verbos Reflexivos','Czasowniki zwrotne','enfadarse','złościć się / obrażać się'),
('Verbos Reflexivos','Czasowniki zwrotne','alegrarse','cieszyć się'),
('Verbos Reflexivos','Czasowniki zwrotne','aburrirse','nudzić się'),
('Verbos Reflexivos','Czasowniki zwrotne','preocuparse','martwić się'),
('Verbos Reflexivos','Czasowniki zwrotne','quejarse','narzekać / skarżyć się'),
('Verbos Reflexivos','Czasowniki zwrotne','relajarse','relaksować się'),
('Verbos Reflexivos','Czasowniki zwrotne','quedarse','zostawać'),
('Verbos Reflexivos','Czasowniki zwrotne','irse','iść sobie / odchodzić'),
('Verbos Reflexivos','Czasowniki zwrotne','acercarse','zbliżać się'),
('Verbos Reflexivos','Czasowniki zwrotne','alejarse','oddalać się'),
('Verbos Reflexivos','Czasowniki zwrotne','acordarse','pamiętać / przypominać sobie'),
('Verbos Reflexivos','Czasowniki zwrotne','olvidarse','zapominać'),
('Verbos Reflexivos','Czasowniki zwrotne','despedirse','żegnać się'),
('Verbos Reflexivos','Czasowniki zwrotne','reunirse','spotykać się / gromadzić się'),
('Verbos Reflexivos','Czasowniki zwrotne','darse','zdarzać się / poddawać się'),
('Verbos Reflexivos','Czasowniki zwrotne','atreverse','odważać się'),
('Verbos Reflexivos','Czasowniki zwrotne','equivocarse','mielić się / popełniać błąd'),
('Verbos Reflexivos','Czasowniki zwrotne','arrepentirse','żałować (za grzechy / błędy)'),
('Verbos Reflexivos','Czasowniki zwrotne','enterarse','dowiadywać się'),
('Verbos Reflexivos','Czasowniki zwrotne','fijarse','zwracać uwagę / przyglądać się'),
('Verbos Reflexivos','Czasowniki zwrotne','burlarse','naigrawać się / drwić'),
('Verbos Reflexivos','Czasowniki zwrotne','reírse','śmiać się (z czegoś)'),
('Verbos Reflexivos','Czasowniki zwrotne','darse cuenta','zdawać sobie sprawę'),
('Verbos Reflexivos','Czasowniki zwrotne','mudarse','przeprowadzać się'),
('Verbos Reflexivos','Czasowniki zwrotne','prepararse','przygotowywać się'),
('Verbos Reflexivos','Czasowniki zwrotne','secarse','wycierać się / suszyć się'),
('Verbos Reflexivos','Czasowniki zwrotne','cortarse','zaciąć się (np. przy goleniu)'),
('Verbos Reflexivos','Czasowniki zwrotne','quemarse','oparzyć się / spalić się'),
('Verbos Reflexivos','Czasowniki zwrotne','caerse','przewrócić się / upaść'),
('Verbos Reflexivos','Czasowniki zwrotne','esconderse','chować się');
