insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('La Comida','Jedzenie','el desayuno','śniadanie'),
('La Comida','Jedzenie','el almuerzo','drugie śniadanie/lunch'),
('La Comida','Jedzenie','la comida','obiad/jedzenie'),
('La Comida','Jedzenie','la cena','kolacja'),
('La Comida','Jedzenie','el plato','danie/talerz'),
('La Comida','Jedzenie','el primer plato','pierwsze danie'),
('La Comida','Jedzenie','el segundo plato','drugie danie'),
('La Comida','Jedzenie','el postre','deser'),
('La Comida','Jedzenie','el pan','chleb'),
('La Comida','Jedzenie','el panecillo','bułka'),
('La Comida','Jedzenie','la mantequilla','masło'),
('La Comida','Jedzenie','el queso','ser'),
('La Comida','Jedzenie','el huevo','jajko'),
('La Comida','Jedzenie','la carne','mięso'),
('La Comida','Jedzenie','el pollo','kurczak'),
('La Comida','Jedzenie','el cerdo','wieprzowina'),
('La Comida','Jedzenie','la ternera','cielęcina'),
('La Comida','Jedzenie','el pescado','ryba'),
('La Comida','Jedzenie','el marisco','owoce morza'),
('La Comida','Jedzenie','la sopa','zupa'),
('La Comida','Jedzenie','la ensalada','sałatka'),
('La Comida','Jedzenie','la pasta','makaron'),
('La Comida','Jedzenie','el arroz','ryż'),
('La Comida','Jedzenie','la patata','ziemniak'),
('La Comida','Jedzenie','la verdura','warzywo'),
('La Comida','Jedzenie','el tomate','pomidor'),
('La Comida','Jedzenie','la cebolla','cebula'),
('La Comida','Jedzenie','el ajo','czosnek'),
('La Comida','Jedzenie','la fruta','owoc'),
('La Comida','Jedzenie','la manzana','jabłko'),
('La Comida','Jedzenie','el plátano','banan'),
('La Comida','Jedzenie','la naranja','pomarańcza'),
('La Comida','Jedzenie','el limón','cytryna'),
('La Comida','Jedzenie','la fresa','truskawka'),
('La Comida','Jedzenie','la uva','winogrono'),
('La Comida','Jedzenie','el azúcar','cukier'),
('La Comida','Jedzenie','la sal','sól'),
('La Comida','Jedzenie','la pimienta','pieprz'),
('La Comida','Jedzenie','el aceite','olej/oliwa'),
('La Comida','Jedzenie','el vinagre','ocet'),
('La Comida','Jedzenie','la salsa','sos'),
('La Comida','Jedzenie','el chocolate','czekolada'),
('La Comida','Jedzenie','el caramelo','cukierek'),
('La Comida','Jedzenie','el helado','lody'),
('La Comida','Jedzenie','el pastel','ciasto'),
('La Comida','Jedzenie','la galleta','ciastko'),
('La Comida','Jedzenie','el bocadillo','kanapka (z bagietki)'),
('La Comida','Jedzenie','el sándwich','kanapka (z chleba tostowego)'),
('La Comida','Jedzenie','la hamburguesa','hamburger'),
('La Comida','Jedzenie','la pizza','pizza'),
('Las Bebidas','Napoje','el agua','woda'),
('Las Bebidas','Napoje','el agua mineral','woda mineralna'),
('Las Bebidas','Napoje','el agua con gas','woda gazowana'),
('Las Bebidas','Napoje','el agua sin gas','woda niegazowana'),
('Las Bebidas','Napoje','el té','herbata'),
('Las Bebidas','Napoje','el té negro','czarna herbata'),
('Las Bebidas','Napoje','el té verde','zielona herbata'),
('Las Bebidas','Napoje','el café','kawa'),
('Las Bebidas','Napoje','el café solo','czarna kawa'),
('Las Bebidas','Napoje','el café con leche','kawa z mlekiem'),
('Las Bebidas','Napoje','el cortado','kawa z odrobiną mleka'),
('Las Bebidas','Napoje','el capuchino','cappuccino'),
('Las Bebidas','Napoje','el zumo / el jugo','sok'),
('Las Bebidas','Napoje','el zumo de naranja','sok pomarańczowy'),
('Las Bebidas','Napoje','el zumo de manzana','sok jabłkowy'),
('Las Bebidas','Napoje','el zumo de piña','sok ananasowy'),
('Las Bebidas','Napoje','la leche','mleko'),
('Las Bebidas','Napoje','el batido','koktajl mleczny / szejk'),
('Las Bebidas','Napoje','el refresco','napój gazowany'),
('Las Bebidas','Napoje','la cola','cola'),
('Las Bebidas','Napoje','la limonada','lemoniada'),
('Las Bebidas','Napoje','la naranjada','oranżada'),
('Las Bebidas','Napoje','el jarabe','syrop'),
('Las Bebidas','Napoje','la cerveza','piwo'),
('Las Bebidas','Napoje','la cerveza rubia','jasne piwo'),
('Las Bebidas','Napoje','la cerveza negra','ciemne piwo'),
('Las Bebidas','Napoje','el vino','wino'),
('Las Bebidas','Napoje','el vino tinto','czerwone wino'),
('Las Bebidas','Napoje','el vino blanco','białe wino'),
('Las Bebidas','Napoje','el vino rosado','różowe wino'),
('Las Bebidas','Napoje','el champán','szampan'),
('Las Bebidas','Napoje','el cava','wino musujące'),
('Las Bebidas','Napoje','el licor','likier'),
('Las Bebidas','Napoje','el ron','rum'),
('Las Bebidas','Napoje','el vodka','wódka'),
('Las Bebidas','Napoje','el whisky','whisky'),
('Las Bebidas','Napoje','la ginebra','dżin'),
('Las Bebidas','Napoje','el cóctel','koktajl (alkoholowy)'),
('Las Bebidas','Napoje','el aguardiente','wódka / bimber'),
('Las Bebidas','Napoje','el vermú','wermut'),
('Las Bebidas','Napoje','la sangría','sangria'),
('Las Bebidas','Napoje','el chocolate caliente','gorąca czekolada'),
('Las Bebidas','Napoje','el hielo','lód'),
('Las Bebidas','Napoje','la bebida isotónica','napój izotoniczny'),
('Las Bebidas','Napoje','la infusión','napar'),
('Las Bebidas','Napoje','el vaso','szklanka'),
('Las Bebidas','Napoje','la taza','filiżanka'),
('Las Bebidas','Napoje','la botella','butelka'),
('Las Bebidas','Napoje','la jarra','dzbanek'),
('Las Bebidas','Napoje','la lata','puszka'),
('La Ropa','Ubrania','la camisa','koszula'),
('La Ropa','Ubrania','la camiseta','koszulka / t-shirt'),
('La Ropa','Ubrania','el pantalón','spodnie'),
('La Ropa','Ubrania','los vaqueros','dżinsy'),
('La Ropa','Ubrania','la falda','spódnica'),
('La Ropa','Ubrania','el vestido','sukienka'),
('La Ropa','Ubrania','el traje','garnitur'),
('La Ropa','Ubrania','la chaqueta','kurtka / marynarka'),
('La Ropa','Ubrania','el abrigo','płaszcz'),
('La Ropa','Ubrania','el jersey / el suéter','sweter'),
('La Ropa','Ubrania','la sudadera','bluza'),
('La Ropa','Ubrania','el chaleco','kamizelka'),
('La Ropa','Ubrania','los pantalones cortos','krótkie spodenki'),
('La Ropa','Ubrania','la ropa interior','bielizna'),
('La Ropa','Ubrania','las bragas','majtki (damskie)'),
('La Ropa','Ubrania','los calzoncillos','majtki (męskie)'),
('La Ropa','Ubrania','el sujetador','biustonosz'),
('La Ropa','Ubrania','los calcetines','skarpetki'),
('La Ropa','Ubrania','las medias','rajstopy / pończochy'),
('La Ropa','Ubrania','el pijama','piżama'),
('La Ropa','Ubrania','el camisón','koszula nocna'),
('La Ropa','Ubrania','el albornoz','szlafrok'),
('La Ropa','Ubrania','el bañador','strój kąpielowy'),
('La Ropa','Ubrania','el bikini','bikini'),
('La Ropa','Ubrania','los zapatos','buty'),
('La Ropa','Ubrania','las zapatillas de deporte','buty sportowe'),
('La Ropa','Ubrania','las botas','kozaki / buty za kostkę'),
('La Ropa','Ubrania','las sandalias','sandały'),
('La Ropa','Ubrania','los tacones','buty na obcasie'),
('La Ropa','Ubrania','las zapatillas de casa','kapcie'),
('La Ropa','Ubrania','el gorro','czapka'),
('La Ropa','Ubrania','el sombrero','kapelusz'),
('La Ropa','Ubrania','la bufanda','szalik'),
('La Ropa','Ubrania','los guantes','rękawiczki'),
('La Ropa','Ubrania','el cinturón','pasek'),
('La Ropa','Ubrania','la corbata','krawat'),
('La Ropa','Ubrania','la pajarita','mucha (do garnituru)'),
('La Ropa','Ubrania','el pañuelo','chustka'),
('La Ropa','Ubrania','el bolso','torebka'),
('La Ropa','Ubrania','la cartera','portfel'),
('La Ropa','Ubrania','la mochila','plecak'),
('La Ropa','Ubrania','el paraguas','parasol'),
('La Ropa','Ubrania','las gafas de sol','okulary przeciwsłoneczne'),
('La Ropa','Ubrania','el botón','guzik'),
('La Ropa','Ubrania','la cremallera','zamek błyskawiczny'),
('La Ropa','Ubrania','el bolsillo','kieszeń'),
('La Ropa','Ubrania','la manga','rękaw'),
('La Ropa','Ubrania','el cuello','kołnierzyk'),
('La Ropa','Ubrania','el algodón','bawełna'),
('La Ropa','Ubrania','la lana','wełna'),
('Los Colores','Kolory','el color','kolor'),
('Los Colores','Kolory','rojo','czerwony'),
('Los Colores','Kolory','azul','niebieski'),
('Los Colores','Kolory','amarillo','żółty'),
('Los Colores','Kolory','verde','zielony'),
('Los Colores','Kolory','negro','czarny'),
('Los Colores','Kolory','blanco','biały'),
('Los Colores','Kolory','gris','szary'),
('Los Colores','Kolory','marrón / café','brązowy'),
('Los Colores','Kolory','naranja','pomarańczowy'),
('Los Colores','Kolory','rosa','różowy'),
('Los Colores','Kolory','morado / púrpura','fioletowy'),
('Los Colores','Kolory','violeta','fiołkowy'),
('Los Colores','Kolory','celeste','błękitny'),
('Los Colores','Kolory','azul marino','granatowy'),
('Los Colores','Kolory','verde oliva','oliwkowy'),
('Los Colores','Kolory','verde esmeralda','szmaragdowy'),
('Los Colores','Kolory','beige','beżowy'),
('Los Colores','Kolory','granate / burdeos','bordowy'),
('Los Colores','Kolory','fucsia','fuksja'),
('Los Colores','Kolory','turquesa','turkusowy'),
('Los Colores','Kolory','coral','koralowy'),
('Los Colores','Kolory','magenta','magenta'),
('Los Colores','Kolory','lila','liliowy'),
('Los Colores','Kolory','dorado','złoty'),
('Los Colores','Kolory','plateado','srebrny'),
('Los Colores','Kolory','bronce','brązowy (odlew) / spiżowy'),
('Los Colores','Kolory','cobre','miedziany'),
('Los Colores','Kolory','claro','jasny'),
('Los Colores','Kolory','oscuro','ciemny'),
('Los Colores','Kolory','brillante','błyszczący'),
('Los Colores','Kolory','mate','matowy'),
('Los Colores','Kolory','pálido','blady'),
('Los Colores','Kolory','vivo','żywy / jaskrawy'),
('Los Colores','Kolory','intenso','intensywny'),
('Los Colores','Kolory','pastel','pastelowy'),
('Los Colores','Kolory','multicolor','wielokolorowy'),
('Los Colores','Kolory','a rayas','w paski'),
('Los Colores','Kolory','a cuadros','w kratkę'),
('Los Colores','Kolory','a lunares','w grochy'),
('Los Colores','Kolory','liso','gładki / jednolity'),
('Los Colores','Kolory','teñir','farbować'),
('Los Colores','Kolory','pintar','malować'),
('Los Colores','Kolory','el tono','odcień'),
('Los Colores','Kolory','el matiz','tonacja / niuans'),
('Los Colores','Kolory','el arcoíris','tęcza'),
('Los Colores','Kolory','transparente','przezroczysty'),
('Los Colores','Kolory','opaco','nieprzezroczysty'),
('Los Colores','Kolory','translúcido','półprzezroczysty'),
('Los Colores','Kolory','fosforescente','fosforyzujący');
