insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('La Informática','Informatyka','la informática','informatyka'),
('La Informática','Informatyka','el ordenador','komputer'),
('La Informática','Informatyka','el portátil','laptop'),
('La Informática','Informatyka','el ratón','myszka'),
('La Informática','Informatyka','el teclado','klawiatura'),
('La Informática','Informatyka','la pantalla','ekran'),
('La Informática','Informatyka','el monitor','monitor'),
('La Informática','Informatyka','el hardware','sprzęt komputerowy'),
('La Informática','Informatyka','el software','oprogramowanie'),
('La Informática','Informatyka','el sistema operativo','system operacyjny'),
('La Informática','Informatyka','el archivo','plik'),
('La Informática','Informatyka','la carpeta','folder'),
('La Informática','Informatyka','el documento','dokument'),
('La Informática','Informatyka','el servidor','serwer'),
('La Informática','Informatyka','la nube','chmura (internetowa)'),
('La Informática','Informatyka','el disco duro','dysk twardy'),
('La Informática','Informatyka','la memoria USB / el pendrive','pendrive'),
('La Informática','Informatyka','el procesador','procesor'),
('La Informática','Informatyka','la placa base','płyta główna'),
('La Informática','Informatyka','el virus','wirus'),
('La Informática','Informatyka','el antivirus','antywirus'),
('La Informática','Informatyka','el código','kod'),
('La Informática','Informatyka','el programador','programista'),
('La Informática','Informatyka','programar','programować'),
('La Informática','Informatyka','la base de datos','baza danych'),
('La Informática','Informatyka','la red','sieć'),
('La Informática','Informatyka','el wifi','wi-fi'),
('La Informática','Informatyka','la conexión','połączenie'),
('La Informática','Informatyka','guardar','zapisywać'),
('La Informática','Informatyka','borrar','usuwać'),
('La Informática','Informatyka','copiar','kopiować'),
('La Informática','Informatyka','pegar','wklejać'),
('La Informática','Informatyka','cortar','wycinać'),
('La Informática','Informatyka','imprimir','drukować'),
('La Informática','Informatyka','hacer clic','klikać'),
('La Informática','Informatyka','arrastrar','przeciągać'),
('La Informática','Informatyka','reiniciar','restartować'),
('La Informática','Informatyka','encender','włączać'),
('La Informática','Informatyka','apagar','wyłączać'),
('La Informática','Informatyka','actualizar','aktualizować'),
('La Informática','Informatyka','la actualización','aktualizacja'),
('La Informática','Informatyka','el enlace / el link','link / odnośnik'),
('La Informática','Informatyka','el navegador','przeglądarka internetowa'),
('La Informática','Informatyka','el buscador','wyszukiwarka'),
('La Informática','Informatyka','el correo electrónico','e-mail'),
('La Informática','Informatyka','la arroba','małpa (@)'),
('La Informática','Informatyka','el punto','kropka (w adresie web)'),
('La Informática','Informatyka','descargar','pobierać'),
('La Informática','Informatyka','subir','wysyłać / wgrywać'),
('La Informática','Informatyka','la contraseña','hasło'),
('Redes Sociales','Media społecznościowe','la red social','sieć społecznościowa'),
('Redes Sociales','Media społecznościowe','el perfil','profil'),
('Redes Sociales','Media społecznościowe','la cuenta','konto'),
('Redes Sociales','Media społecznościowe','el usuario','użytkownik'),
('Redes Sociales','Media społecznościowe','la contraseña','hasło'),
('Redes Sociales','Media społecznościowe','iniciar sesión','zalogować się'),
('Redes Sociales','Media społecznościowe','cerrar sesión','wylogować się'),
('Redes Sociales','Media społecznościowe','la publicación','post / publikacja'),
('Redes Sociales','Media społecznościowe','publicar','publikować'),
('Redes Sociales','Media społecznościowe','el seguidor','obserwujący (follower)'),
('Redes Sociales','Media społecznościowe','seguir','obserwować (kogoś)'),
('Redes Sociales','Media społecznościowe','el me gusta','lajk / lubię to'),
('Redes Sociales','Media społecznościowe','dar me gusta','dać lajka'),
('Redes Sociales','Media społecznościowe','el comentario','komentarz'),
('Redes Sociales','Media społecznościowe','comentar','komentować'),
('Redes Sociales','Media społecznościowe','compartir','udostępniać'),
('Redes Sociales','Media społecznościowe','el mensaje','wiadomość'),
('Redes Sociales','Media społecznościowe','enviar','wysyłać'),
('Redes Sociales','Media społecznościowe','recibir','otrzymywać'),
('Redes Sociales','Media społecznościowe','el chat','czat'),
('Redes Sociales','Media społecznościowe','chatear','czatować'),
('Redes Sociales','Media społecznościowe','la notificación','powiadomienie'),
('Redes Sociales','Media społecznościowe','la foto','zdjęcie'),
('Redes Sociales','Media społecznościowe','el vídeo','wideo'),
('Redes Sociales','Media społecznościowe','el estado','status'),
('Redes Sociales','Media społecznościowe','la historia','story / relacja'),
('Redes Sociales','Media społecznościowe','la etiqueta','tag / znacznik'),
('Redes Sociales','Media społecznościowe','etiquetar','oznaczać (kogoś)'),
('Redes Sociales','Media społecznościowe','el hashtag','hasztag'),
('Redes Sociales','Media społecznościowe','el enlace','link'),
('Redes Sociales','Media społecznościowe','en línea','online / dostępny'),
('Redes Sociales','Media społecznościowe','desconectado','offline / niedostępny'),
('Redes Sociales','Media społecznościowe','bloquear','blokować'),
('Redes Sociales','Media społecznościowe','desbloquear','odblokować'),
('Redes Sociales','Media społecznościowe','el grupo','grupa'),
('Redes Sociales','Media społecznościowe','la página','strona'),
('Redes Sociales','Media społecznościowe','el muro','tablica (na profilu)'),
('Redes Sociales','Media społecznościowe','el influencer','influencer'),
('Redes Sociales','Media społecznościowe','viral','wirusowy / viralowy'),
('Redes Sociales','Media społecznościowe','hacerse viral','stać się viralem'),
('Redes Sociales','Media społecznościowe','el algoritmo','algorytm'),
('Redes Sociales','Media społecznościowe','la privacidad','prywatność'),
('Redes Sociales','Media społecznościowe','público','publiczny'),
('Redes Sociales','Media społecznościowe','privado','prywatny'),
('Redes Sociales','Media społecznościowe','el avatar','awatar / zdjęcie profilowe'),
('Redes Sociales','Media społecznościowe','el filtro','filtr (do zdjęć)'),
('Redes Sociales','Media społecznościowe','la solicitud de amistad','zaproszenie do znajomych'),
('Redes Sociales','Media społecznościowe','agregar','dodawać (znajomego)'),
('Redes Sociales','Media społecznościowe','eliminar','usuwać'),
('Redes Sociales','Media społecznościowe','silenciar','wyciszać'),
('La Religión','Religia','la religión','religia'),
('La Religión','Religia','Dios','Bóg'),
('La Religión','Religia','Jesús','Jezus'),
('La Religión','Religia','la cruz','krzyż'),
('La Religión','Religia','la iglesia','kościół'),
('La Religión','Religia','el templo','świątynia'),
('La Religión','Religia','la catedral','katedra'),
('La Religión','Religia','la mezquita','meczet'),
('La Religión','Religia','la sinagoga','synagoga'),
('La Religión','Religia','el sacerdote / el cura','ksiądz'),
('La Religión','Religia','el obispo','biskup'),
('La Religión','Religia','el papa','papież'),
('La Religión','Religia','el monje','mnich'),
('La Religión','Religia','la monja','zakonnica'),
('La Religión','Religia','el fiel','wierny'),
('La Religión','Religia','la fe','wiara'),
('La Religión','Religia','creer','wierzyć'),
('La Religión','Religia','la oración','modlitwa'),
('La Religión','Religia','rezar','modlić się'),
('La Religión','Religia','el pecado','grzech'),
('La Religión','Religia','pecar','grzeszyć'),
('La Religión','Religia','el perdón','przebaczenie'),
('La Religión','Religia','perdonar','przebaczać'),
('La Religión','Religia','el cielo','niebo (raj)'),
('La Religión','Religia','el infierno','piekło'),
('La Religión','Religia','el diablo / el demonio','diabeł / demon'),
('La Religión','Religia','el ángel','anioł'),
('La Religión','Religia','el alma','dusza'),
('La Religión','Religia','el espíritu','duch'),
('La Religión','Religia','el Espíritu Santo','Duch Święty'),
('La Religión','Religia','sagrado','święty (rzecz)'),
('La Religión','Religia','el santo','święty (osoba)'),
('La Religión','Religia','la Biblia','Biblia'),
('La Religión','Religia','el Corán','Koran'),
('La Religión','Religia','la misa','msza'),
('La Religión','Religia','el bautismo','chrzest'),
('La Religión','Religia','bautizar','chrzcić'),
('La Religión','Religia','la comunión','komunia'),
('La Religión','Religia','el matrimonio','małżeństwo / ślub kościelny'),
('La Religión','Religia','el funeral','pogrzeb'),
('La Religión','Religia','el cementerio','cmentarz'),
('La Religión','Religia','el milagro','cud'),
('La Religión','Religia','la peregrinación','pielgrzymka'),
('La Religión','Religia','el peregrino','pielgrzym'),
('La Religión','Religia','la procesión','procesja'),
('La Religión','Religia','el altar','ołtarz'),
('La Religión','Religia','el incienso','kadzidło'),
('La Religión','Religia','el creador','stwórca'),
('La Religión','Religia','ateo','ateista'),
('La Religión','Religia','creyente','wierzący'),
('La Ciencia','Nauka','la ciencia','nauka (dziedzina)'),
('La Ciencia','Nauka','el científico / la científica','naukowiec'),
('La Ciencia','Nauka','el investigador','badacz'),
('La Ciencia','Nauka','la investigación','badanie / śledztwo'),
('La Ciencia','Nauka','el experimento','eksperyment'),
('La Ciencia','Nauka','experimentar','eksperymentować'),
('La Ciencia','Nauka','el laboratorio','laboratorium'),
('La Ciencia','Nauka','el descubrimiento','odkrycie'),
('La Ciencia','Nauka','descubrir','odkrywać'),
('La Ciencia','Nauka','la teoría','teoria'),
('La Ciencia','Nauka','la hipótesis','hipoteza'),
('La Ciencia','Nauka','el análisis','analiza'),
('La Ciencia','Nauka','analizar','analizować'),
('La Ciencia','Nauka','el resultado','wynik'),
('La Ciencia','Nauka','la prueba','dowód / test'),
('La Ciencia','Nauka','el método','metoda'),
('La Ciencia','Nauka','observar','obserwować'),
('La Ciencia','Nauka','medir','mierzyć'),
('La Ciencia','Nauka','la fórmula','wzór / formuła'),
('La Ciencia','Nauka','el microscopio','mikroskop'),
('La Ciencia','Nauka','el tubo de ensayo','probówka'),
('La Ciencia','Nauka','la química','chemia'),
('La Ciencia','Nauka','la física','fizyka'),
('La Ciencia','Nauka','la biología','biologia'),
('La Ciencia','Nauka','la astronomía','astronomia'),
('La Ciencia','Nauka','las matemáticas','matematyka'),
('La Ciencia','Nauka','el átomo','atom'),
('La Ciencia','Nauka','la molécula','cząsteczka'),
('La Ciencia','Nauka','la célula','komórka'),
('La Ciencia','Nauka','el ADN','DNA'),
('La Ciencia','Nauka','la genética','genetyka'),
('La Ciencia','Nauka','el gen','gen'),
('La Ciencia','Nauka','el elemento','pierwiastek'),
('La Ciencia','Nauka','la gravedad','grawitacja'),
('La Ciencia','Nauka','la energía','energia'),
('La Ciencia','Nauka','la masa','masa'),
('La Ciencia','Nauka','la materia','materia'),
('La Ciencia','Nauka','el invento','wynalazek'),
('La Ciencia','Nauka','inventar','wynaleźć'),
('La Ciencia','Nauka','el inventor','wynalazca'),
('La Ciencia','Nauka','la patente','patent'),
('La Ciencia','Nauka','el congreso','kongres / konferencja'),
('La Ciencia','Nauka','la publicación','publikacja'),
('La Ciencia','Nauka','el premio Nobel','nagroda Nobla'),
('La Ciencia','Nauka','demostrar','udowadniać'),
('La Ciencia','Nauka','el fenómeno','zjawisko'),
('La Ciencia','Nauka','exacto','dokładny'),
('La Ciencia','Nauka','empírico','empiryczny'),
('La Ciencia','Nauka','la evolución','ewolucja'),
('La Ciencia','Nauka','el estudio','badanie / studium');
