insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 1 de Entrevista de Trabajo','Słowo 1 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 2 de Entrevista de Trabajo','Słowo 2 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 3 de Entrevista de Trabajo','Słowo 3 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 4 de Entrevista de Trabajo','Słowo 4 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 5 de Entrevista de Trabajo','Słowo 5 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 6 de Entrevista de Trabajo','Słowo 6 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 7 de Entrevista de Trabajo','Słowo 7 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 8 de Entrevista de Trabajo','Słowo 8 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 9 de Entrevista de Trabajo','Słowo 9 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 10 de Entrevista de Trabajo','Słowo 10 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 11 de Entrevista de Trabajo','Słowo 11 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 12 de Entrevista de Trabajo','Słowo 12 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 13 de Entrevista de Trabajo','Słowo 13 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 14 de Entrevista de Trabajo','Słowo 14 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 15 de Entrevista de Trabajo','Słowo 15 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 16 de Entrevista de Trabajo','Słowo 16 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 17 de Entrevista de Trabajo','Słowo 17 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 18 de Entrevista de Trabajo','Słowo 18 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 19 de Entrevista de Trabajo','Słowo 19 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 20 de Entrevista de Trabajo','Słowo 20 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 21 de Entrevista de Trabajo','Słowo 21 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 22 de Entrevista de Trabajo','Słowo 22 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 23 de Entrevista de Trabajo','Słowo 23 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 24 de Entrevista de Trabajo','Słowo 24 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 25 de Entrevista de Trabajo','Słowo 25 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 26 de Entrevista de Trabajo','Słowo 26 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 27 de Entrevista de Trabajo','Słowo 27 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 28 de Entrevista de Trabajo','Słowo 28 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 29 de Entrevista de Trabajo','Słowo 29 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 30 de Entrevista de Trabajo','Słowo 30 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 31 de Entrevista de Trabajo','Słowo 31 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 32 de Entrevista de Trabajo','Słowo 32 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 33 de Entrevista de Trabajo','Słowo 33 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 34 de Entrevista de Trabajo','Słowo 34 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 35 de Entrevista de Trabajo','Słowo 35 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 36 de Entrevista de Trabajo','Słowo 36 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 37 de Entrevista de Trabajo','Słowo 37 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 38 de Entrevista de Trabajo','Słowo 38 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 39 de Entrevista de Trabajo','Słowo 39 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 40 de Entrevista de Trabajo','Słowo 40 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 41 de Entrevista de Trabajo','Słowo 41 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 42 de Entrevista de Trabajo','Słowo 42 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 43 de Entrevista de Trabajo','Słowo 43 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 44 de Entrevista de Trabajo','Słowo 44 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 45 de Entrevista de Trabajo','Słowo 45 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 46 de Entrevista de Trabajo','Słowo 46 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 47 de Entrevista de Trabajo','Słowo 47 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 48 de Entrevista de Trabajo','Słowo 48 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 49 de Entrevista de Trabajo','Słowo 49 z Rozmowa kwalifikacyjna'),
('Entrevista de Trabajo','Rozmowa kwalifikacyjna','Palabra 50 de Entrevista de Trabajo','Słowo 50 z Rozmowa kwalifikacyjna'),
('Contabilidad','Księgowość','Palabra 1 de Contabilidad','Słowo 1 z Księgowość'),
('Contabilidad','Księgowość','Palabra 2 de Contabilidad','Słowo 2 z Księgowość'),
('Contabilidad','Księgowość','Palabra 3 de Contabilidad','Słowo 3 z Księgowość'),
('Contabilidad','Księgowość','Palabra 4 de Contabilidad','Słowo 4 z Księgowość'),
('Contabilidad','Księgowość','Palabra 5 de Contabilidad','Słowo 5 z Księgowość'),
('Contabilidad','Księgowość','Palabra 6 de Contabilidad','Słowo 6 z Księgowość'),
('Contabilidad','Księgowość','Palabra 7 de Contabilidad','Słowo 7 z Księgowość'),
('Contabilidad','Księgowość','Palabra 8 de Contabilidad','Słowo 8 z Księgowość'),
('Contabilidad','Księgowość','Palabra 9 de Contabilidad','Słowo 9 z Księgowość'),
('Contabilidad','Księgowość','Palabra 10 de Contabilidad','Słowo 10 z Księgowość'),
('Contabilidad','Księgowość','Palabra 11 de Contabilidad','Słowo 11 z Księgowość'),
('Contabilidad','Księgowość','Palabra 12 de Contabilidad','Słowo 12 z Księgowość'),
('Contabilidad','Księgowość','Palabra 13 de Contabilidad','Słowo 13 z Księgowość'),
('Contabilidad','Księgowość','Palabra 14 de Contabilidad','Słowo 14 z Księgowość'),
('Contabilidad','Księgowość','Palabra 15 de Contabilidad','Słowo 15 z Księgowość'),
('Contabilidad','Księgowość','Palabra 16 de Contabilidad','Słowo 16 z Księgowość'),
('Contabilidad','Księgowość','Palabra 17 de Contabilidad','Słowo 17 z Księgowość'),
('Contabilidad','Księgowość','Palabra 18 de Contabilidad','Słowo 18 z Księgowość'),
('Contabilidad','Księgowość','Palabra 19 de Contabilidad','Słowo 19 z Księgowość'),
('Contabilidad','Księgowość','Palabra 20 de Contabilidad','Słowo 20 z Księgowość'),
('Contabilidad','Księgowość','Palabra 21 de Contabilidad','Słowo 21 z Księgowość'),
('Contabilidad','Księgowość','Palabra 22 de Contabilidad','Słowo 22 z Księgowość'),
('Contabilidad','Księgowość','Palabra 23 de Contabilidad','Słowo 23 z Księgowość'),
('Contabilidad','Księgowość','Palabra 24 de Contabilidad','Słowo 24 z Księgowość'),
('Contabilidad','Księgowość','Palabra 25 de Contabilidad','Słowo 25 z Księgowość'),
('Contabilidad','Księgowość','Palabra 26 de Contabilidad','Słowo 26 z Księgowość'),
('Contabilidad','Księgowość','Palabra 27 de Contabilidad','Słowo 27 z Księgowość'),
('Contabilidad','Księgowość','Palabra 28 de Contabilidad','Słowo 28 z Księgowość'),
('Contabilidad','Księgowość','Palabra 29 de Contabilidad','Słowo 29 z Księgowość'),
('Contabilidad','Księgowość','Palabra 30 de Contabilidad','Słowo 30 z Księgowość'),
('Contabilidad','Księgowość','Palabra 31 de Contabilidad','Słowo 31 z Księgowość'),
('Contabilidad','Księgowość','Palabra 32 de Contabilidad','Słowo 32 z Księgowość'),
('Contabilidad','Księgowość','Palabra 33 de Contabilidad','Słowo 33 z Księgowość'),
('Contabilidad','Księgowość','Palabra 34 de Contabilidad','Słowo 34 z Księgowość'),
('Contabilidad','Księgowość','Palabra 35 de Contabilidad','Słowo 35 z Księgowość'),
('Contabilidad','Księgowość','Palabra 36 de Contabilidad','Słowo 36 z Księgowość'),
('Contabilidad','Księgowość','Palabra 37 de Contabilidad','Słowo 37 z Księgowość'),
('Contabilidad','Księgowość','Palabra 38 de Contabilidad','Słowo 38 z Księgowość'),
('Contabilidad','Księgowość','Palabra 39 de Contabilidad','Słowo 39 z Księgowość'),
('Contabilidad','Księgowość','Palabra 40 de Contabilidad','Słowo 40 z Księgowość'),
('Contabilidad','Księgowość','Palabra 41 de Contabilidad','Słowo 41 z Księgowość'),
('Contabilidad','Księgowość','Palabra 42 de Contabilidad','Słowo 42 z Księgowość'),
('Contabilidad','Księgowość','Palabra 43 de Contabilidad','Słowo 43 z Księgowość'),
('Contabilidad','Księgowość','Palabra 44 de Contabilidad','Słowo 44 z Księgowość'),
('Contabilidad','Księgowość','Palabra 45 de Contabilidad','Słowo 45 z Księgowość'),
('Contabilidad','Księgowość','Palabra 46 de Contabilidad','Słowo 46 z Księgowość'),
('Contabilidad','Księgowość','Palabra 47 de Contabilidad','Słowo 47 z Księgowość'),
('Contabilidad','Księgowość','Palabra 48 de Contabilidad','Słowo 48 z Księgowość'),
('Contabilidad','Księgowość','Palabra 49 de Contabilidad','Słowo 49 z Księgowość'),
('Contabilidad','Księgowość','Palabra 50 de Contabilidad','Słowo 50 z Księgowość'),
('Banca y Finanzas','Bankowość i finanse','el banco','bank'),
('Banca y Finanzas','Bankowość i finanse','el cajero automático','bankomat'),
('Banca y Finanzas','Bankowość i finanse','la cuenta','konto'),
('Banca y Finanzas','Bankowość i finanse','la tarjeta de crédito','karta kredytowa'),
('Banca y Finanzas','Bankowość i finanse','la tarjeta de débito','karta debetowa'),
('Banca y Finanzas','Bankowość i finanse','la cuenta corriente','rachunek bieżący'),
('Banca y Finanzas','Bankowość i finanse','la cuenta de ahorros','konto oszczędnościowe'),
('Banca y Finanzas','Bankowość i finanse','el saldo','saldo'),
('Banca y Finanzas','Bankowość i finanse','la transferencia','przelew'),
('Banca y Finanzas','Bankowość i finanse','ingresar dinero','wpłacać pieniądze'),
('Banca y Finanzas','Bankowość i finanse','sacar dinero','wypłacać pieniądze'),
('Banca y Finanzas','Bankowość i finanse','el préstamo','pożyczka / kredyt'),
('Banca y Finanzas','Bankowość i finanse','la hipoteca','hipoteka / kredyt hipoteczny'),
('Banca y Finanzas','Bankowość i finanse','el interés','odsetki'),
('Banca y Finanzas','Bankowość i finanse','el tipo de interés','stopa procentowa'),
('Banca y Finanzas','Bankowość i finanse','la comisión','prowizja'),
('Banca y Finanzas','Bankowość i finanse','el crédito','kredyt'),
('Banca y Finanzas','Bankowość i finanse','la deuda','dług'),
('Banca y Finanzas','Bankowość i finanse','el cheque','czek'),
('Banca y Finanzas','Bankowość i finanse','el cobro','inkaso / pobranie opłaty'),
('Banca y Finanzas','Bankowość i finanse','la divisa','waluta'),
('Banca y Finanzas','Bankowość i finanse','el tipo de cambio','kurs wymiany walut'),
('Banca y Finanzas','Bankowość i finanse','la sucursal','oddział (banku)'),
('Banca y Finanzas','Bankowość i finanse','el banquero','bankier'),
('Banca y Finanzas','Bankowość i finanse','la inversión','inwestycja'),
('Banca y Finanzas','Bankowość i finanse','el inversor','inwestor'),
('Banca y Finanzas','Bankowość i finanse','el fondo de inversión','fundusz inwestycyjny'),
('Banca y Finanzas','Bankowość i finanse','la bolsa de valores','giełda papierów wartościowych'),
('Banca y Finanzas','Bankowość i finanse','la acción','akcja (giełdowa)'),
('Banca y Finanzas','Bankowość i finanse','el dividendo','dywidenda'),
('Banca y Finanzas','Bankowość i finanse','el riesgo','ryzyko'),
('Banca y Finanzas','Bankowość i finanse','la rentabilidad','rentowność / zyskowność'),
('Banca y Finanzas','Bankowość i finanse','el capital','kapitał'),
('Banca y Finanzas','Bankowość i finanse','el activo','aktywa'),
('Banca y Finanzas','Bankowość i finanse','el pasivo','pasywa'),
('Banca y Finanzas','Bankowość i finanse','el cajero','kasjer'),
('Banca y Finanzas','Bankowość i finanse','el pin','PIN'),
('Banca y Finanzas','Bankowość i finanse','la contraseña','hasło'),
('Banca y Finanzas','Bankowość i finanse','bloquear','zablokować (kartę/konto)'),
('Banca y Finanzas','Bankowość i finanse','la banca online','bankowość internetowa'),
('Banca y Finanzas','Bankowość i finanse','el estado de cuenta','wyciąg z konta'),
('Banca y Finanzas','Bankowość i finanse','la liquidación','rozliczenie'),
('Banca y Finanzas','Bankowość i finanse','el plazo fijo','lokata terminowa'),
('Banca y Finanzas','Bankowość i finanse','endeudarse','zadłużać się'),
('Banca y Finanzas','Bankowość i finanse','ahorrar','oszczędzać'),
('Banca y Finanzas','Bankowość i finanse','el préstamo personal','pożyczka gotówkowa'),
('Banca y Finanzas','Bankowość i finanse','el aval','poręczenie / żyrant'),
('Banca y Finanzas','Bankowość i finanse','la domiciliación','polecenie zapłaty'),
('Banca y Finanzas','Bankowość i finanse','domiciliar','zlecić stałą płatność'),
('Banca y Finanzas','Bankowość i finanse','el crédito hipotecario','kredyt hipoteczny'),
('Impuestos','Podatki','el impuesto','podatek'),
('Impuestos','Podatki','la declaración de la renta','zeznanie podatkowe (PIT)'),
('Impuestos','Podatki','el contribuyente','podatnik'),
('Impuestos','Podatki','la Agencia Tributaria / Hacienda','Urząd Skarbowy'),
('Impuestos','Podatki','el IVA (Impuesto sobre el Valor Añadido)','VAT (podatek od towarów i usług)'),
('Impuestos','Podatki','el IRPF','podatek dochodowy od osób fizycznych'),
('Impuestos','Podatki','la tasa','opłata (urzędowa) / podatek'),
('Impuestos','Podatki','el arancel','cło'),
('Impuestos','Podatki','gravar','opodatkować'),
('Impuestos','Podatki','exento','zwolniony (z podatku)'),
('Impuestos','Podatki','la deducción','odliczenie'),
('Impuestos','Podatki','deducir','odliczyć (od podatku)'),
('Impuestos','Podatki','el paraíso fiscal','raj podatkowy'),
('Impuestos','Podatki','la evasión fiscal','uchylanie się od płacenia podatków'),
('Impuestos','Podatki','el fraude fiscal','oszustwo podatkowe'),
('Impuestos','Podatki','la inspección','kontrola (skarbowa)'),
('Impuestos','Podatki','la multa','mandat / grzywna'),
('Impuestos','Podatki','la sanción','kara / sankcja'),
('Impuestos','Podatki','el recargo','dopłata / narzut'),
('Impuestos','Podatki','pagar impuestos','płacić podatki'),
('Impuestos','Podatki','la devolución','zwrot (podatku)'),
('Impuestos','Podatki','el borrador','szkic / wstępne zeznanie'),
('Impuestos','Podatki','el ejercicio fiscal','rok podatkowy'),
('Impuestos','Podatki','los ingresos','przychody'),
('Impuestos','Podatki','los gastos','wydatki'),
('Impuestos','Podatki','la retención','potrącenie (zaliczka na podatek)'),
('Impuestos','Podatki','el impuesto de sociedades','podatek dochodowy od osób prawnych (CIT)'),
('Impuestos','Podatki','el impuesto sobre el patrimonio','podatek majątkowy'),
('Impuestos','Podatki','el impuesto de sucesiones','podatek od spadków'),
('Impuestos','Podatki','la base imponible','podstawa opodatkowania'),
('Impuestos','Podatki','la cuota','składka / kwota (podatku)'),
('Impuestos','Podatki','el tipo impositivo','stawka podatkowa'),
('Impuestos','Podatki','la liquidación','rozliczenie podatku'),
('Impuestos','Podatki','el asesor fiscal','doradca podatkowy'),
('Impuestos','Podatki','la fiscalidad','system podatkowy'),
('Impuestos','Podatki','cotizar','płacić składki / wyceniać'),
('Impuestos','Podatki','la Seguridad Social','Zakład Ubezpieczeń Społecznych (ZUS)'),
('Impuestos','Podatki','la contribución','składka / wkład'),
('Impuestos','Podatki','el deber','obowiązek'),
('Impuestos','Podatki','el fisco','fiskus'),
('Impuestos','Podatki','el importe','kwota / suma'),
('Impuestos','Podatki','declarar','deklarować (dochody)'),
('Impuestos','Podatki','el impuesto indirecto','podatek pośredni'),
('Impuestos','Podatki','el impuesto directo','podatek bezpośredni'),
('Impuestos','Podatki','la moratoria','moratorium (odroczenie)'),
('Impuestos','Podatki','aplazar','odroczyć'),
('Impuestos','Podatki','la multa por retraso','kara za opóźnienie'),
('Impuestos','Podatki','la auditoría','audyt / rewizja'),
('Impuestos','Podatki','evadir impuestos','unikać płacenia podatków'),
('Impuestos','Podatki','la amnistía fiscal','amnestia podatkowa');
