insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Gestión de Proyectos','Zarządzanie projektami','la gestión de proyectos','zarządzanie projektami'),
('Gestión de Proyectos','Zarządzanie projektami','el proyecto','projekt'),
('Gestión de Proyectos','Zarządzanie projektami','el director de proyectos / el jefe de proyecto','kierownik projektu / project manager'),
('Gestión de Proyectos','Zarządzanie projektami','el equipo','zespół'),
('Gestión de Proyectos','Zarządzanie projektami','la tarea','zadanie'),
('Gestión de Proyectos','Zarządzanie projektami','el objetivo','cel'),
('Gestión de Proyectos','Zarządzanie projektami','la meta','meta / zamierzenie'),
('Gestión de Proyectos','Zarządzanie projektami','el plazo','termin / deadline'),
('Gestión de Proyectos','Zarządzanie projektami','el cronograma / el calendario','harmonogram'),
('Gestión de Proyectos','Zarządzanie projektami','la planificación','planowanie'),
('Gestión de Proyectos','Zarządzanie projektami','planificar','planować'),
('Gestión de Proyectos','Zarządzanie projektami','el presupuesto','budżet'),
('Gestión de Proyectos','Zarządzanie projektami','los recursos','zasoby'),
('Gestión de Proyectos','Zarządzanie projektami','el riesgo','ryzyko'),
('Gestión de Proyectos','Zarządzanie projektami','la fase','faza / etap'),
('Gestión de Proyectos','Zarządzanie projektami','el hito','kamień milowy (milestone)'),
('Gestión de Proyectos','Zarządzanie projektami','el entregable','produkt końcowy / rezultat (deliverable)'),
('Gestión de Proyectos','Zarządzanie projektami','la reunión','spotkanie / zebranie'),
('Gestión de Proyectos','Zarządzanie projektami','el informe','raport'),
('Gestión de Proyectos','Zarządzanie projektami','el avance / el progreso','postęp'),
('Gestión de Proyectos','Zarządzanie projektami','coordinar','koordynować'),
('Gestión de Proyectos','Zarządzanie projektami','la coordinación','koordynacja'),
('Gestión de Proyectos','Zarządzanie projektami','ejecutar','wykonywać / realizować'),
('Gestión de Proyectos','Zarządzanie projektami','la ejecución','realizacja'),
('Gestión de Proyectos','Zarządzanie projektami','supervisar','nadzorować'),
('Gestión de Proyectos','Zarządzanie projektami','la supervisión','nadzór'),
('Gestión de Proyectos','Zarządzanie projektami','controlar','kontrolować'),
('Gestión de Proyectos','Zarządzanie projektami','el control de calidad','kontrola jakości'),
('Gestión de Proyectos','Zarządzanie projektami','el retraso','opóźnienie'),
('Gestión de Proyectos','Zarządzanie projektami','adelantado','przed czasem / z wyprzedzeniem'),
('Gestión de Proyectos','Zarządzanie projektami','el imprevisto','nieprzewidziana okoliczność'),
('Gestión de Proyectos','Zarządzanie projektami','resolver','rozwiązywać (problem)'),
('Gestión de Proyectos','Zarządzanie projektami','el enfoque ágil','zwinne podejście (Agile)'),
('Gestión de Proyectos','Zarządzanie projektami','el método ágil','metodologia Agile'),
('Gestión de Proyectos','Zarządzanie projektami','el marco de trabajo','framework / ramy pracy'),
('Gestión de Proyectos','Zarządzanie projektami','la metodología','metodologia'),
('Gestión de Proyectos','Zarządzanie projektami','el tablero Kanban','tablica Kanban'),
('Gestión de Proyectos','Zarządzanie projektami','la reunión de seguimiento','spotkanie statusowe'),
('Gestión de Proyectos','Zarządzanie projektami','el alcance','zakres projektu'),
('Gestión de Proyectos','Zarządzanie projektami','la estimación','szacowanie'),
('Gestión de Proyectos','Zarządzanie projektami','el éxito','sukces'),
('Gestión de Proyectos','Zarządzanie projektami','el fracaso','porażka'),
('Gestión de Proyectos','Zarządzanie projektami','la colaboración','współpraca'),
('Gestión de Proyectos','Zarządzanie projektami','colaborar','współpracować'),
('Gestión de Proyectos','Zarządzanie projektami','la prioridad','priorytet'),
('Gestión de Proyectos','Zarządzanie projektami','priorizar','ustalać priorytety'),
('Gestión de Proyectos','Zarządzanie projektami','el rendimiento','wydajność'),
('Gestión de Proyectos','Zarządzanie projektami','la eficiencia','efektywność'),
('Gestión de Proyectos','Zarządzanie projektami','la optimización','optymalizacja'),
('Gestión de Proyectos','Zarządzanie projektami','la gestión de riesgos','zarządzanie ryzykiem'),
('Informática: Hardware','Informatyka: Sprzęt','el hardware','sprzęt komputerowy'),
('Informática: Hardware','Informatyka: Sprzęt','el ordenador / la computadora','komputer'),
('Informática: Hardware','Informatyka: Sprzęt','el ordenador portátil','laptop'),
('Informática: Hardware','Informatyka: Sprzęt','el ordenador de sobremesa','komputer stacjonarny'),
('Informática: Hardware','Informatyka: Sprzęt','la tableta','tablet'),
('Informática: Hardware','Informatyka: Sprzęt','el teléfono inteligente / el móvil','smartfon'),
('Informática: Hardware','Informatyka: Sprzęt','la pantalla','ekran / monitor'),
('Informática: Hardware','Informatyka: Sprzęt','el teclado','klawiatura'),
('Informática: Hardware','Informatyka: Sprzęt','el ratón','myszka'),
('Informática: Hardware','Informatyka: Sprzęt','la torre','obudowa komputera / jednostka centralna'),
('Informática: Hardware','Informatyka: Sprzęt','la placa base','płyta główna'),
('Informática: Hardware','Informatyka: Sprzęt','el procesador / la CPU','procesor'),
('Informática: Hardware','Informatyka: Sprzęt','la memoria RAM','pamięć RAM'),
('Informática: Hardware','Informatyka: Sprzęt','el disco duro','dysk twardy'),
('Informática: Hardware','Informatyka: Sprzęt','el disco duro sólido (SSD)','dysk SSD'),
('Informática: Hardware','Informatyka: Sprzęt','la tarjeta gráfica','karta graficzna'),
('Informática: Hardware','Informatyka: Sprzęt','la fuente de alimentación','zasilacz'),
('Informática: Hardware','Informatyka: Sprzęt','el ventilador','wentylator'),
('Informática: Hardware','Informatyka: Sprzęt','el puerto USB','port USB'),
('Informática: Hardware','Informatyka: Sprzęt','la tarjeta de red','karta sieciowa'),
('Informática: Hardware','Informatyka: Sprzęt','la impresora','drukarka'),
('Informática: Hardware','Informatyka: Sprzęt','el escáner','skaner'),
('Informática: Hardware','Informatyka: Sprzęt','los altavoces','głośniki'),
('Informática: Hardware','Informatyka: Sprzęt','los auriculares','słuchawki'),
('Informática: Hardware','Informatyka: Sprzęt','el micrófono','mikrofon'),
('Informática: Hardware','Informatyka: Sprzęt','la cámara web','kamera internetowa'),
('Informática: Hardware','Informatyka: Sprzęt','el proyektor','projektor'),
('Informática: Hardware','Informatyka: Sprzęt','el cable','kabel'),
('Informática: Hardware','Informatyka: Sprzęt','el enchufe','wtyczka / gniazdko'),
('Informática: Hardware','Informatyka: Sprzęt','la batería','bateria'),
('Informática: Hardware','Informatyka: Sprzęt','el cargador','ładowarka'),
('Informática: Hardware','Informatyka: Sprzęt','la memoria USB / el lápiz de memoria','pendrive / pamięć USB'),
('Informática: Hardware','Informatyka: Sprzęt','el disco externo','dysk zewnętrzny'),
('Informática: Hardware','Informatyka: Sprzęt','la tarjeta de memoria','karta pamięci'),
('Informática: Hardware','Informatyka: Sprzęt','el lector de tarjetas','czytnik kart'),
('Informática: Hardware','Informatyka: Sprzęt','el router','router'),
('Informática: Hardware','Informatyka: Sprzęt','el módem','modem'),
('Informática: Hardware','Informatyka: Sprzęt','el componente','komponent / podzespół'),
('Informática: Hardware','Informatyka: Sprzęt','el dispositivo','urządzenie'),
('Informática: Hardware','Informatyka: Sprzęt','la pantalla táctil','ekran dotykowy'),
('Informática: Hardware','Informatyka: Sprzęt','el botón de encendido','przycisk zasilania'),
('Informática: Hardware','Informatyka: Sprzęt','la ranura','gniazdo / slot'),
('Informática: Hardware','Informatyka: Sprzęt','conectar','podłączać'),
('Informática: Hardware','Informatyka: Sprzęt','desconectar','odłączać'),
('Informática: Hardware','Informatyka: Sprzęt','averiado','zepsuty / uszkodzony'),
('Informática: Hardware','Informatyka: Sprzęt','la pieza','część / podzespół'),
('Informática: Hardware','Informatyka: Sprzęt','el circuito','obwód / układ'),
('Informática: Hardware','Informatyka: Sprzęt','el chip','układ scalony / chip'),
('Informática: Hardware','Informatyka: Sprzęt','el periférico','urządzenie peryferyjne'),
('Informática: Hardware','Informatyka: Sprzęt','la actualización de hardware','modernizacja sprzętu'),
('Informática: Software','Informatyka: Oprogramowanie','el software','oprogramowanie'),
('Informática: Software','Informatyka: Oprogramowanie','el programa','program'),
('Informática: Software','Informatyka: Oprogramowanie','la aplicación','aplikacja'),
('Informática: Software','Informatyka: Oprogramowanie','el sistema operativo','system operacyjny'),
('Informática: Software','Informatyka: Oprogramowanie','Windows','Windows'),
('Informática: Software','Informatyka: Oprogramowanie','macOS','macOS'),
('Informática: Software','Informatyka: Oprogramowanie','Linux','Linux'),
('Informática: Software','Informatyka: Oprogramowanie','Android','Android'),
('Informática: Software','Informatyka: Oprogramowanie','iOS','iOS'),
('Informática: Software','Informatyka: Oprogramowanie','el archivo','plik'),
('Informática: Software','Informatyka: Oprogramowanie','la carpeta','folder / katalog'),
('Informática: Software','Informatyka: Oprogramowanie','el documento','dokument'),
('Informática: Software','Informatyka: Oprogramowanie','el portapapeles','schowek'),
('Informática: Software','Informatyka: Oprogramowanie','instalar','instalować'),
('Informática: Software','Informatyka: Oprogramowanie','la instalación','instalacja'),
('Informática: Software','Informatyka: Oprogramowanie','desinstalar','odinstalować'),
('Informática: Software','Informatyka: Oprogramowanie','actualizar','aktualizować'),
('Informática: Software','Informatyka: Oprogramowanie','la actualización','aktualizacja'),
('Informática: Software','Informatyka: Oprogramowanie','ejecutar','uruchamiać / wykonywać'),
('Informática: Software','Informatyka: Oprogramowanie','abrir','otwierać'),
('Informática: Software','Informatyka: Oprogramowanie','cerrar','zamykać'),
('Informática: Software','Informatyka: Oprogramowanie','guardar','zapisywać'),
('Informática: Software','Informatyka: Oprogramowanie','guardar como','zapisz jako'),
('Informática: Software','Informatyka: Oprogramowanie','copiar','kopiować'),
('Informática: Software','Informatyka: Oprogramowanie','pegar','wklejać'),
('Informática: Software','Informatyka: Oprogramowanie','cortar','wycinać'),
('Informática: Software','Informatyka: Oprogramowanie','borrar / eliminar','usuwać'),
('Informática: Software','Informatyka: Oprogramowanie','deshacer','cofnij'),
('Informática: Software','Informatyka: Oprogramowanie','rehacer','ponów'),
('Informática: Software','Informatyka: Oprogramowanie','la interfaz','interfejs'),
('Informática: Software','Informatyka: Oprogramowanie','el icono','ikona'),
('Informática: Software','Informatyka: Oprogramowanie','el escritorio','pulpit'),
('Informática: Software','Informatyka: Oprogramowanie','la papelera de reciclaje','kosz na śmieci'),
('Informática: Software','Informatyka: Oprogramowanie','el error','błąd'),
('Informática: Software','Informatyka: Oprogramowanie','el fallo','awaria / usterka'),
('Informática: Software','Informatyka: Oprogramowanie','el virus','wirus'),
('Informática: Software','Informatyka: Oprogramowanie','el antivirus','antywirus'),
('Informática: Software','Informatyka: Oprogramowanie','analizar','skanować / analizować'),
('Informática: Software','Informatyka: Oprogramowanie','la copia de seguridad','kopia zapasowa (backup)'),
('Informática: Software','Informatyka: Oprogramowanie','restaurar','przywracać'),
('Informática: Software','Informatyka: Oprogramowanie','comprimir','kompresować'),
('Informática: Software','Informatyka: Oprogramowanie','descomprimir','rozpakowywać'),
('Informática: Software','Informatyka: Oprogramowanie','la base de datos','baza danych'),
('Informática: Software','Informatyka: Oprogramowanie','el código','kod'),
('Informática: Software','Informatyka: Oprogramowanie','programar','programować'),
('Informática: Software','Informatyka: Oprogramowanie','el programador','programista'),
('Informática: Software','Informatyka: Oprogramowanie','el navegador','przeglądarka'),
('Informática: Software','Informatyka: Oprogramowanie','la contraseña','hasło'),
('Informática: Software','Informatyka: Oprogramowanie','el usuario','użytkownik'),
('Informática: Software','Informatyka: Oprogramowanie','la licencia','licencja'),
('Internet','Internet','internet','internet'),
('Internet','Internet','la red','sieć'),
('Internet','Internet','la página web','strona internetowa'),
('Internet','Internet','el sitio web','witryna internetowa'),
('Internet','Internet','el enlace / el hipervínculo','link / hiperłącze'),
('Internet','Internet','la dirección URL','adres URL'),
('Internet','Internet','el navegador web','przeglądarka internetowa'),
('Internet','Internet','el motor de búsqueda','wyszukiwarka'),
('Internet','Internet','buscar','szukać'),
('Internet','Internet','navegar','serfować / przeglądać'),
('Internet','Internet','descargar','pobierać / ściągać'),
('Internet','Internet','subir','wagrać / wrzucać'),
('Internet','Internet','la descarga','pobieranie'),
('Internet','Internet','la subida','wgranie'),
('Internet','Internet','la conexión','połączenie'),
('Internet','Internet','la conexión a internet','połączenie internetowe'),
('Internet','Internet','la banda ancha','szerokopasmowy internet'),
('Internet','Internet','la fibra óptica','światłowód'),
('Internet','Internet','el wifi','Wi-Fi'),
('Internet','Internet','el señal','sygnał'),
('Internet','Internet','el correo electrónico / el email','poczta elektroniczna / email'),
('Internet','Internet','enviar','wysyłać'),
('Internet','Internet','recibir','odbierać'),
('Internet','Internet','el buzón de entrada','skrzynka odbiorcza'),
('Internet','Internet','el archivo adjunto','załącznik'),
('Internet','Internet','el correo no deseado / el spam','spam'),
('Internet','Internet','las redes sociales','media społecznościowe'),
('Internet','Internet','la plataforma','platforma'),
('Internet','Internet','la cuenta','konto / profil'),
('Internet','Internet','iniciar sesión','zalogować się'),
('Internet','Internet','cerrar sesión','wylogować się'),
('Internet','Internet','la contraseña','hasło'),
('Internet','Internet','el nombre de usuario','nazwa użytkownika'),
('Internet','Internet','el perfil','profil'),
('Internet','Internet','publicar','publikować'),
('Internet','Internet','compartir','udostępniać'),
('Internet','Internet','el comentario','komentarz'),
('Internet','Internet','el "me gusta"','polubienie / lajk'),
('Internet','Internet','el seguidor','obserwujący / follower'),
('Internet','Internet','seguir','obserwować'),
('Internet','Internet','el chat','czat'),
('Internet','Internet','la videoconferencia','wideokonferencja'),
('Internet','Internet','la nube','chmura'),
('Internet','Internet','el almacenamiento en la nube','przechowywanie w chmurze'),
('Internet','Internet','la ciberseguridad','cyberbezpieczeństwo'),
('Internet','Internet','el hacker','haker'),
('Internet','Internet','el phishing','phishing'),
('Internet','Internet','la cookie','plik cookie / ciasteczko'),
('Internet','Internet','viral','wirusowy'),
('Internet','Internet','el influencer','influencer');
