insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('En el Gimnasio','Na siłowni','el gimnasio','siłownia'),
('En el Gimnasio','Na siłowni','el entrenamiento','trening'),
('En el Gimnasio','Na siłowni','entrenar','trenować'),
('En el Gimnasio','Na siłowni','hacer ejercicio','ćwiczyć'),
('En el Gimnasio','Na siłowni','estar en forma','być w formie'),
('En el Gimnasio','Na siłowni','la salud','zdrowie'),
('En el Gimnasio','Na siłowni','la condición física','kondycja fizyczna'),
('En el Gimnasio','Na siłowni','el entrenador personal','trener personalny'),
('En el Gimnasio','Na siłowni','el instructor','instruktor'),
('En el Gimnasio','Na siłowni','el músculo','mięsień'),
('En el Gimnasio','Na siłowni','la fuerza','siła'),
('En el Gimnasio','Na siłowni','la resistencia','wytrzymałość'),
('En el Gimnasio','Na siłowni','el calentamiento','rozgrzewka'),
('En el Gimnasio','Na siłowni','calentar','rozgrzewać się'),
('En el Gimnasio','Na siłowni','el estiramiento','rozciągananie'),
('En el Gimnasio','Na siłowni','estirar','rozciągać się'),
('En el Gimnasio','Na siłowni','la máquina','maszyna / sprzęt (do ćwiczeń)'),
('En el Gimnasio','Na siłowni','la cinta de correr','bieżnia'),
('En el Gimnasio','Na siłowni','la bicicleta estática','rowerek stacjonarny'),
('En el Gimnasio','Na siłowni','la elíptica','orbitrek / maszyna eliptyczna'),
('En el Gimnasio','Na siłowni','las pesas','ciężary'),
('En el Gimnasio','Na siłowni','levantar pesas','podnosić ciężary'),
('En el Gimnasio','Na siłowni','la mancuerna','hantel'),
('En el Gimnasio','Na siłowni','la pesa rusa / la kettlebell','odważnik kulowy (kettlebell)'),
('En el Gimnasio','Na siłowni','la barra','sztanga'),
('En el Gimnasio','Na siłowni','la repetición','powtórzenie'),
('En el Gimnasio','Na siłowni','la serie','seria'),
('En el Gimnasio','Na siłowni','el descanso','odpoczynek'),
('En el Gimnasio','Na siłowni','sudar','pocić się'),
('En el Gimnasio','Na siłowni','el sudor','pot'),
('En el Gimnasio','Na siłowni','la toalla','ręcznik'),
('En el Gimnasio','Na siłowni','la botella de agua','butelka wody'),
('En el Gimnasio','Na siłowni','el vestuario','szatnia'),
('En el Gimnasio','Na siłowni','la taquilla','szafka (w szatni)'),
('En el Gimnasio','Na siłowni','la ducha','prysznic'),
('En el Gimnasio','Na siłowni','la clase dirigida','zajęcia grupowe'),
('En el Gimnasio','Na siłowni','el yoga','joga'),
('En el Gimnasio','Na siłowni','el pilates','pilates'),
('En el Gimnasio','Na siłowni','el aeróbic','aerobik'),
('En el Gimnasio','Na siłowni','el zumba','zumba'),
('En el Gimnasio','Na siłowni','el spinning','spinning'),
('En el Gimnasio','Na siłowni','la esterilla','mata do ćwiczeń'),
('En el Gimnasio','Na siłowni','los abdominales','brzuszki (ćwiczenie) / mięśnie brzucha'),
('En el Gimnasio','Na siłowni','las flexiones','pompki (ćwiczenie)'),
('En el Gimnasio','Na siłowni','las sentadillas','przysiady'),
('En el Gimnasio','Na siłowni','perder peso','schudnąć / tracić na wadze'),
('En el Gimnasio','Na siłowni','ganar masa muscular','budować masę mięśniową'),
('En el Gimnasio','Na siłowni','la dieta','dieta'),
('En el Gimnasio','Na siłowni','la proteína','białko'),
('En el Gimnasio','Na siłowni','la motivación','motywacja'),
('Artes Marciales','Sztuki walki','las artes marciales','sztuki walki'),
('Artes Marciales','Sztuki walki','el kárate','karate'),
('Artes Marciales','Sztuki walki','el judo','judo'),
('Artes Marciales','Sztuki walki','el taekwondo','taekwondo'),
('Artes Marciales','Sztuki walki','el boxeo','boks'),
('Artes Marciales','Sztuki walki','el kickboxing','kick-boxing'),
('Artes Marciales','Sztuki walki','el muay thai','muay thai (boks tajski)'),
('Artes Marciales','Sztuki walki','el jiu-jitsu','jiu-jitsu'),
('Artes Marciales','Sztuki walki','el kung fu','kung fu'),
('Artes Marciales','Sztuki walki','la esgrima','szermierka'),
('Artes Marciales','Sztuki walki','la lucha libre','zapasy'),
('Artes Marciales','Sztuki walki','el combate','walka / starcie'),
('Artes Marciales','Sztuki walki','el asalto / el round','runda'),
('Artes Marciales','Sztuki walki','el cuadrilátero / el ring','ring'),
('Artes Marciales','Sztuki walki','el tatami','mata (tatami)'),
('Artes Marciales','Sztuki walki','el luchador','wojownik / zapaśnik'),
('Artes Marciales','Sztuki walki','el boxeador','bokser'),
('Artes Marciales','Sztuki walki','el maestro / el sensei','mistrz / nauczyciel'),
('Artes Marciales','Sztuki walki','el oponente / el rival','przeciwnik / rywal'),
('Artes Marciales','Sztuki walki','el árbitro','sędzia'),
('Artes Marciales','Sztuki walki','atacar','atakować'),
('Artes Marciales','Sztuki walki','el ataque','atak'),
('Artes Marciales','Sztuki walki','defender','bronić'),
('Artes Marciales','Sztuki walki','la defensa','obrona'),
('Artes Marciales','Sztuki walki','bloquear','blokować'),
('Artes Marciales','Sztuki walki','el bloqueo','blok (ciosu)'),
('Artes Marciales','Sztuki walki','golpear','uderzać'),
('Artes Marciales','Sztuki walki','el golpe','cios / uderzenie'),
('Artes Marciales','Sztuki walki','el puñetazo','uderzenie pięścią'),
('Artes Marciales','Sztuki walki','la patada','kopnięcie'),
('Artes Marciales','Sztuki walki','el gancho','sierpowy / hak (cios)'),
('Artes Marciales','Sztuki walki','esquivar','unikać (ciosu)'),
('Artes Marciales','Sztuki walki','derribar','powalić / obalić'),
('Artes Marciales','Sztuki walki','el agarre','chwyt'),
('Artes Marciales','Sztuki walki','la llave','dźwignia'),
('Artes Marciales','Sztuki walki','la sumisión','poddanie'),
('Artes Marciales','Sztuki walki','rendirse','poddać się'),
('Artes Marciales','Sztuki walki','ganar','wygrać'),
('Artes Marciales','Sztuki walki','perder','przegrać'),
('Artes Marciales','Sztuki walki','el nocaut (KO)','nokaut (KO)'),
('Artes Marciales','Sztuki walki','la disciplina','dyscyplina'),
('Artes Marciales','Sztuki walki','el respeto','szacunek'),
('Artes Marciales','Sztuki walki','la concentración','koncentracja'),
('Artes Marciales','Sztuki walki','el kimono / el dobok','kimono'),
('Artes Marciales','Sztuki walki','el cinturón','pas'),
('Artes Marciales','Sztuki walki','el cinturón negro','czarny pas'),
('Artes Marciales','Sztuki walki','el guante de boxeo','rękawica bokserska'),
('Artes Marciales','Sztuki walki','el saco de boxeo','worek treningowy'),
('Artes Marciales','Sztuki walki','la técnica','technika'),
('Artes Marciales','Sztuki walki','el torneo','turniej'),
('Música Clásica','Muzyka klasyczna','la música clásica','muzyka klasyczna'),
('Música Clásica','Muzyka klasyczna','la música','muzyka'),
('Música Clásica','Muzyka klasyczna','el músico','muzyk'),
('Música Clásica','Muzyka klasyczna','el compositor','kompozytor'),
('Música Clásica','Muzyka klasyczna','componer','komponować'),
('Música Clásica','Muzyka klasyczna','la obra','dzieło'),
('Música Clásica','Muzyka klasyczna','la pieza musical','utwór muzyczny'),
('Música Clásica','Muzyka klasyczna','la sinfonía','symfonia'),
('Música Clásica','Muzyka klasyczna','el concierto','koncert'),
('Música Clásica','Muzyka klasyczna','la sonata','sonata'),
('Música Clásica','Muzyka klasyczna','la ópera','opera'),
('Música Clásica','Muzyka klasyczna','el ballet','balet'),
('Música Clásica','Muzyka klasyczna','la orquesta','orkiestra'),
('Música Clásica','Muzyka klasyczna','la orquesta sinfónica','orkiestra symfoniczna'),
('Música Clásica','Muzyka klasyczna','el director de orquesta','dyrygent'),
('Música Clásica','Muzyka klasyczna','la batuta','batuta'),
('Música Clásica','Muzyka klasyczna','el ensayo','próba'),
('Música Clásica','Muzyka klasyczna','ensayar','robić próbę / ćwiczyć'),
('Música Clásica','Muzyka klasyczna','el escenario','scena'),
('Música Clásica','Muzyka klasyczna','el público','publiczność'),
('Música Clásica','Muzyka klasyczna','aplaudir','klaskać'),
('Música Clásica','Muzyka klasyczna','el aplauso','oklaski / brawa'),
('Música Clásica','Muzyka klasyczna','el teatro','teatr'),
('Música Clásica','Muzyka klasyczna','el auditorio','audytorium / sala koncertowa'),
('Música Clásica','Muzyka klasyczna','el instrumento','instrument'),
('Música Clásica','Muzyka klasyczna','el violín','skrzypce'),
('Música Clásica','Muzyka klasyczna','la viola','altówka'),
('Música Clásica','Muzyka klasyczna','el violonchelo','wiolonczela'),
('Música Clásica','Muzyka klasyczna','el contrabajo','kontrabas'),
('Música Clásica','Muzyka klasyczna','el piano','pianino / fortepian'),
('Música Clásica','Muzyka klasyczna','la flauta','flet'),
('Música Clásica','Muzyka klasyczna','el clarinete','klarnet'),
('Música Clásica','Muzyka klasyczna','el oboe','obój'),
('Música Clásica','Muzyka klasyczna','la trompeta','trąbka'),
('Música Clásica','Muzyka klasyczna','el trombón','puzon'),
('Música Clásica','Muzyka klasyczna','la trompa','waltornia'),
('Música Clásica','Muzyka klasyczna','los timbales','kotły (instrument)'),
('Música Clásica','Muzyka klasyczna','el arpa','harfa'),
('Música Clásica','Muzyka klasyczna','afinar','stroić'),
('Música Clásica','Muzyka klasyczna','tocar','grać (na instrumencie)'),
('Música Clásica','Muzyka klasyczna','la melodía','melodia'),
('Música Clásica','Muzyka klasyczna','la armonía','harmonia'),
('Música Clásica','Muzyka klasyczna','el ritmo','rytm'),
('Música Clásica','Muzyka klasyczna','la partitura','partytura / zapis nutowy'),
('Música Clásica','Muzyka klasyczna','la nota','nuta'),
('Música Clásica','Muzyka klasyczna','el atril','pulpit (na nuty)'),
('Música Clásica','Muzyka klasyczna','el coro','chór'),
('Música Clásica','Muzyka klasyczna','cantar','śpiewać'),
('Música Clásica','Muzyka klasyczna','el soprano','sopran'),
('Música Clásica','Muzyka klasyczna','el tenor','tenor'),
('Géneros Musicales','Gatunki muzyczne','el género musical','gatunek muzyczny'),
('Géneros Musicales','Gatunki muzyczne','el pop','pop'),
('Géneros Musicales','Gatunki muzyczne','el rock','rock'),
('Géneros Musicales','Gatunki muzyczne','el jazz','jazz'),
('Géneros Musicales','Gatunki muzyczne','el blues','blues'),
('Géneros Musicales','Gatunki muzyczne','la música clásica','muzyka klasyczna'),
('Géneros Musicales','Gatunki muzyczne','el hip hop','hip hop'),
('Géneros Musicales','Gatunki muzyczne','el rap','rap'),
('Géneros Musicales','Gatunki muzyczne','el reguetón','reggaeton'),
('Géneros Musicales','Gatunki muzyczne','la salsa','salsa'),
('Géneros Musicales','Gatunki muzyczne','la bachata','bachata'),
('Géneros Musicales','Gatunki muzyczne','el merengue','merengue'),
('Géneros Musicales','Gatunki muzyczne','la cumbia','cumbia'),
('Géneros Musicales','Gatunki muzyczne','el flamenco','flamenco'),
('Géneros Musicales','Gatunki muzyczne','el tango','tango'),
('Géneros Musicales','Gatunki muzyczne','el country','country'),
('Géneros Musicales','Gatunki muzyczne','el heavy metal','heavy metal'),
('Géneros Musicales','Gatunki muzyczne','el punk','punk'),
('Géneros Musicales','Gatunki muzyczne','la música electrónica','muzyka elektroniczna'),
('Géneros Musicales','Gatunki muzyczne','el tecno','techno'),
('Géneros Musicales','Gatunki muzyczne','el house','house'),
('Géneros Musicales','Gatunki muzyczne','la música disco','muzyka disco'),
('Géneros Musicales','Gatunki muzyczne','el reggae','reggae'),
('Géneros Musicales','Gatunki muzyczne','el soul','soul'),
('Géneros Musicales','Gatunki muzyczne','el R&B','R&B'),
('Géneros Musicales','Gatunki muzyczne','la música indie','muzyka indie'),
('Géneros Musicales','Gatunki muzyczne','el folk / la música folclórica','muzyka folkowa / ludowa'),
('Géneros Musicales','Gatunki muzyczne','la ópera','opera'),
('Géneros Musicales','Gatunki muzyczne','la zarzuela','zarzuela (hiszpańska operetka)'),
('Géneros Musicales','Gatunki muzyczne','el gospel','gospel'),
('Géneros Musicales','Gatunki muzyczne','el funk','funk'),
('Géneros Musicales','Gatunki muzyczne','el ska','ska'),
('Géneros Musicales','Gatunki muzyczne','la música ambiental','muzyka ambient / tła'),
('Géneros Musicales','Gatunki muzyczne','el villancico','kolęda'),
('Géneros Musicales','Gatunki muzyczne','el himno','hymn'),
('Géneros Musicales','Gatunki muzyczne','la balada','balada'),
('Géneros Musicales','Gatunki muzyczne','el bolero','bolero'),
('Géneros Musicales','Gatunki muzyczne','la ranchera','ranchera'),
('Géneros Musicales','Gatunki muzyczne','el mariachi','muzyka mariachi'),
('Géneros Musicales','Gatunki muzyczne','la música de cámara','muzyka kameralna'),
('Géneros Musicales','Gatunki muzyczne','la sinfonía','symfonia'),
('Géneros Musicales','Gatunki muzyczne','la música instrumental','muzyka instrumentalna'),
('Géneros Musicales','Gatunki muzyczne','la música vocal','muzyka wokalna'),
('Géneros Musicales','Gatunki muzyczne','el ritmo','rytm'),
('Géneros Musicales','Gatunki muzyczne','el compás','takt / metrum'),
('Géneros Musicales','Gatunki muzyczne','el acorde','akord'),
('Géneros Musicales','Gatunki muzyczne','la melodía','melodia'),
('Géneros Musicales','Gatunki muzyczne','el estribillo','refren'),
('Géneros Musicales','Gatunki muzyczne','la estrofa','zwrotka'),
('Géneros Musicales','Gatunki muzyczne','el estilo','styl (muzyczny)');
