insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Enfermedades','Choroby','la enfermedad','choroba'),
('Enfermedades','Choroby','el resfriado','przeziębienie'),
('Enfermedades','Choroby','la gripe','grypa'),
('Enfermedades','Choroby','la fiebre','gorączka'),
('Enfermedades','Choroby','la tos','kaszel'),
('Enfermedades','Choroby','el dolor de cabeza','ból głowy'),
('Enfermedades','Choroby','el dolor de garganta','ból gardła'),
('Enfermedades','Choroby','el dolor de estómago','ból brzucha'),
('Enfermedades','Choroby','la infección','infekcja'),
('Enfermedades','Choroby','la inflamación','stan zapalny'),
('Enfermedades','Choroby','el virus','wirus'),
('Enfermedades','Choroby','la bacteria','bakteria'),
('Enfermedades','Choroby','el asma','astma'),
('Enfermedades','Choroby','la alergia','alergia'),
('Enfermedades','Choroby','la diabetes','cukrzyca'),
('Enfermedades','Choroby','el cáncer','rak (choroba)'),
('Enfermedades','Choroby','el infarto','zawał'),
('Enfermedades','Choroby','el derrame cerebral','udar mózgu'),
('Enfermedades','Choroby','la neumonía','zapalenie płuc'),
('Enfermedades','Choroby','la bronquitis','zapalenie oskrzeli'),
('Enfermedades','Choroby','la artritis','artretyzm'),
('Enfermedades','Choroby','el reumatismo','reumatyzm'),
('Enfermedades','Choroby','la hipertensión','nadciśnienie'),
('Enfermedades','Choroby','el colesterol','cholesterol'),
('Enfermedades','Choroby','la obesidad','otyłość'),
('Enfermedades','Choroby','el trastorno','zaburzenie'),
('Enfermedades','Choroby','la depresión','depresja'),
('Enfermedades','Choroby','la ansiedad','niepokój / stany lękowe'),
('Enfermedades','Choroby','el estrés','stres'),
('Enfermedades','Choroby','el insomnio','bezsenność'),
('Enfermedades','Choroby','la migraña','migrena'),
('Enfermedades','Choroby','la diarrea','biegunka'),
('Enfermedades','Choroby','el vómito','wymioty'),
('Enfermedades','Choroby','el mareo','zawroty głowy / choroba lokomocyjna'),
('Enfermedades','Choroby','la náusea','mdłości'),
('Enfermedades','Choroby','la fractura','złamanie'),
('Enfermedades','Choroby','el esguince','skręcenie'),
('Enfermedades','Choroby','la cicatriz','blizna'),
('Enfermedades','Choroby','la herida','rana'),
('Enfermedades','Choroby','el síntoma','objaw'),
('Enfermedades','Choroby','el diagnóstico','diagnoza'),
('Enfermedades','Choroby','contagiarse','zarazić się'),
('Enfermedades','Choroby','el contagio','zarażenie'),
('Enfermedades','Choroby','la epidemia','epidemia'),
('Enfermedades','Choroby','la pandemia','pandemia'),
('Enfermedades','Choroby','crónico','przewlekły'),
('Enfermedades','Choroby','agudo','ostry (np. ból)'),
('Enfermedades','Choroby','leve','lekki (np. przebieg)'),
('Enfermedades','Choroby','grave','ciężki / poważny'),
('Enfermedades','Choroby','incurable','nieuleczalny'),
('Partes del Día','Pory dnia','el amanecer','świt'),
('Partes del Día','Pory dnia','la madrugada','wczesny ranek'),
('Partes del Día','Pory dnia','la mañana','poranek'),
('Partes del Día','Pory dnia','el mediodía','południe'),
('Partes del Día','Pory dnia','la tarde','popołudnie'),
('Partes del Día','Pory dnia','el atardecer','późne popołudnie / zachód słońca'),
('Partes del Día','Pory dnia','el anochecer','zmierzch'),
('Partes del Día','Pory dnia','la noche','noc'),
('Partes del Día','Pory dnia','la medianoche','północ'),
('Partes del Día','Pory dnia','de madrugada','nad ranem'),
('Partes del Día','Pory dnia','por la mañana','rano'),
('Partes del Día','Pory dnia','al mediodía','w południe'),
('Partes del Día','Pory dnia','por la tarde','po południu'),
('Partes del Día','Pory dnia','por la noche','w nocy'),
('Partes del Día','Pory dnia','el alba','brzask'),
('Partes del Día','Pory dnia','la puesta de sol','zachód słońca'),
('Partes del Día','Pory dnia','la salida del sol','wschód słońca'),
('Partes del Día','Pory dnia','el crepúsculo','zmrok'),
('Partes del Día','Pory dnia','la oscuridad','ciemność'),
('Partes del Día','Pory dnia','la luz','światło'),
('Partes del Día','Pory dnia','el día','dzień'),
('Partes del Día','Pory dnia','la jornada','dzień pracy'),
('Partes del Día','Pory dnia','el reloj','zegar'),
('Partes del Día','Pory dnia','la hora','godzina'),
('Partes del Día','Pory dnia','el minuto','minuta'),
('Partes del Día','Pory dnia','el segundo','sekunda'),
('Partes del Día','Pory dnia','el instante','chwila / moment'),
('Partes del Día','Pory dnia','el rato','chwila (krótki czas)'),
('Partes del Día','Pory dnia','temprano','wcześnie'),
('Partes del Día','Pory dnia','tarde','późno'),
('Partes del Día','Pory dnia','puntual','punktualny'),
('Partes del Día','Pory dnia','el retraso','opóźnienie'),
('Partes del Día','Pory dnia','a tiempo','na czas'),
('Partes del Día','Pory dnia','la siesta','drzemka poobiednia'),
('Partes del Día','Pory dnia','el desayuno','śniadanie (pora)'),
('Partes del Día','Pory dnia','la comida','obiad (pora)'),
('Partes del Día','Pory dnia','la cena','kolacja (pora)'),
('Partes del Día','Pory dnia','despertarse','budzić się'),
('Partes del Día','Pory dnia','levantarse','wstawać'),
('Partes del Día','Pory dnia','acostarse','kłaść się spać'),
('Partes del Día','Pory dnia','trasnochar','zarywać noc'),
('Partes del Día','Pory dnia','madrugar','wstawać wcześnie rano'),
('Partes del Día','Pory dnia','el turno de mañana','poranna zmiana'),
('Partes del Día','Pory dnia','el turno de tarde','popołudniowa zmiana'),
('Partes del Día','Pory dnia','el turno de noche','nocna zmiana'),
('Partes del Día','Pory dnia','diario','codzienny'),
('Partes del Día','Pory dnia','nocturno','nocny'),
('Partes del Día','Pory dnia','matutino','poranny'),
('Partes del Día','Pory dnia','vespertino','popołudniowy / wieczorny'),
('Partes del Día','Pory dnia','24 horas / todo el día','całą dobę / cały dzień'),
('Días de la Semana','Dni tygodnia','el día de la semana','dzień tygodnia'),
('Días de la Semana','Dni tygodnia','el lunes','poniedziałek'),
('Días de la Semana','Dni tygodnia','el martes','wtorek'),
('Días de la Semana','Dni tygodnia','el miércoles','środa'),
('Días de la Semana','Dni tygodnia','el jueves','czwartek'),
('Días de la Semana','Dni tygodnia','el viernes','piątek'),
('Días de la Semana','Dni tygodnia','el sábado','sobota'),
('Días de la Semana','Dni tygodnia','el domingo','niedziela'),
('Días de la Semana','Dni tygodnia','el fin de semana','weekend'),
('Días de la Semana','Dni tygodnia','el día laborable / el día hábil','dzień roboczy'),
('Días de la Semana','Dni tygodnia','el día festivo','dzień świąteczny'),
('Días de la Semana','Dni tygodnia','el puente','długi weekend'),
('Días de la Semana','Dni tygodnia','ayer','wczoraj'),
('Días de la Semana','Dni tygodnia','hoy','dzisiaj'),
('Días de la Semana','Dni tygodnia','mañana','jutro'),
('Días de la Semana','Dni tygodnia','anteayer / antes de ayer','przedwczoraj'),
('Días de la Semana','Dni tygodnia','pasado mañana','pojutrze'),
('Días de la Semana','Dni tygodnia','el día anterior','poprzedni dzień'),
('Días de la Semana','Dni tygodnia','el día siguiente','następny dzień'),
('Días de la Semana','Dni tygodnia','todos los días','codziennie'),
('Días de la Semana','Dni tygodnia','cada lunes','w każdy poniedziałek'),
('Días de la Semana','Dni tygodnia','el próximo lunes','w przyszły poniedziałek'),
('Días de la Semana','Dni tygodnia','el lunes pasado','w zeszły poniedziałek'),
('Días de la Semana','Dni tygodnia','a mediados de semana','w środku tygodnia'),
('Días de la Semana','Dni tygodnia','el calendario','kalendarz'),
('Días de la Semana','Dni tygodnia','la semana','tydzień'),
('Días de la Semana','Dni tygodnia','la semana que viene','przyszły tydzień'),
('Días de la Semana','Dni tygodnia','la semana pasada','zeszły tydzień'),
('Días de la Semana','Dni tygodnia','una quincena','dwa tygodnie'),
('Días de la Semana','Dni tygodnia','semanal','tygodniowy'),
('Días de la Semana','Dni tygodnia','el horario','harmonogram / plan lekcji'),
('Días de la Semana','Dni tygodnia','la agenda','terminarz / kalendarz'),
('Días de la Semana','Dni tygodnia','la fecha','data'),
('Días de la Semana','Dni tygodnia','¿Qué día es hoy?','Jaki dziś dzień?'),
('Días de la Semana','Dni tygodnia','trabajar','pracować'),
('Días de la Semana','Dni tygodnia','descansar','odpoczywać'),
('Días de la Semana','Dni tygodnia','la rutina','rutyna'),
('Días de la Semana','Dni tygodnia','el festivo','święto'),
('Días de la Semana','Dni tygodnia','de lunes a viernes','od poniedziałku do piątku'),
('Días de la Semana','Dni tygodnia','entre semana','w dni robocze / w tygodniu'),
('Días de la Semana','Dni tygodnia','el puente festivo','długi weekend świąteczny'),
('Días de la Semana','Dni tygodnia','librar','mieć dzień wolny'),
('Días de la Semana','Dni tygodnia','el día libre','dzień wolny'),
('Días de la Semana','Dni tygodnia','semanalmente','co tydzień'),
('Días de la Semana','Dni tygodnia','el inicio de semana','początek tygodnia'),
('Días de la Semana','Dni tygodnia','el fin de mes','koniec miesiąca'),
('Días de la Semana','Dni tygodnia','la jornada laboral','dzień pracy'),
('Días de la Semana','Dni tygodnia','bisemanal','dwutygodniowy'),
('Días de la Semana','Dni tygodnia','cada semana','każdego tygodnia'),
('Días de la Semana','Dni tygodnia','diariamente','codziennie'),
('Meses del Año','Miesiące','el mes','miesiąc'),
('Meses del Año','Miesiące','enero','styczeń'),
('Meses del Año','Miesiące','febrero','luty'),
('Meses del Año','Miesiące','marzo','marzec'),
('Meses del Año','Miesiące','abril','kwiecień'),
('Meses del Año','Miesiące','mayo','maj'),
('Meses del Año','Miesiące','junio','czerwiec'),
('Meses del Año','Miesiące','julio','lipiec'),
('Meses del Año','Miesiące','agosto','sierpień'),
('Meses del Año','Miesiące','septiembre','wrzesień'),
('Meses del Año','Miesiące','octubre','październik'),
('Meses del Año','Miesiące','noviembre','listopad'),
('Meses del Año','Miesiące','diciembre','grudzień'),
('Meses del Año','Miesiące','el año','rok'),
('Meses del Año','Miesiące','el año bisiesto','rok przestępny'),
('Meses del Año','Miesiące','a principios de','na początku'),
('Meses del Año','Miesiące','a mediados de','w połowie'),
('Meses del Año','Miesiące','a finales de','pod koniec'),
('Meses del Año','Miesiące','el próximo mes','w przyszłym miesiącu'),
('Meses del Año','Miesiące','el mes pasado','w zeszłym miesiącu'),
('Meses del Año','Miesiące','mensual','miesięczny'),
('Meses del Año','Miesiące','mensualmente','co miesiąc'),
('Meses del Año','Miesiące','el trimestre','kwartał'),
('Meses del Año','Miesiące','el semestre','półrocze'),
('Meses del Año','Miesiące','la temporada','sezon'),
('Meses del Año','Miesiące','el aniversario','rocznica'),
('Meses del Año','Miesiące','anual','roczny'),
('Meses del Año','Miesiące','anualmente','corocznie'),
('Meses del Año','Miesiące','el año que viene','w przyszłym roku'),
('Meses del Año','Miesiące','el año pasado','w zeszłym roku'),
('Meses del Año','Miesiące','la década','dekada'),
('Meses del Año','Miesiące','el siglo','wiek / stulecie'),
('Meses del Año','Miesiące','el milenio','tysiąclecie'),
('Meses del Año','Miesiące','el calendario','kalendarz'),
('Meses del Año','Miesiące','bimensual','dwumiesięczny'),
('Meses del Año','Miesiące','trimestral','kwartalny'),
('Meses del Año','Miesiące','semestral','półroczny'),
('Meses del Año','Miesiące','el fin de año','koniec roku / sylwester'),
('Meses del Año','Miesiące','el comienzo de año','początek roku'),
('Meses del Año','Miesiące','la fecha de nacimiento','data urodzenia'),
('Meses del Año','Miesiące','caducar','wygasać / tracić ważność'),
('Meses del Año','Miesiące','la fecha de caducidad','data ważności'),
('Meses del Año','Miesiące','enero cuesta arriba','styczniowa bieda / ciężki styczeń'),
('Meses del Año','Miesiące','en enero','w styczniu'),
('Meses del Año','Miesiące','desde febrero','od lutego'),
('Meses del Año','Miesiące','hasta marzo','do marca'),
('Meses del Año','Miesiące','cada mes','każdego miesiąca'),
('Meses del Año','Miesiące','un par de meses','kilka miesięcy'),
('Meses del Año','Miesiące','hace un mes','miesiąc temu'),
('Meses del Año','Miesiące','dentro de un mes','za miesiąc');
