insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Las Frutas','Owoce','la fruta','owoc'),
('Las Frutas','Owoce','la manzana','jabłko'),
('Las Frutas','Owoce','la pera','gruszka'),
('Las Frutas','Owoce','el plátano / la banana','banan'),
('Las Frutas','Owoce','la naranja','pomarańcza'),
('Las Frutas','Owoce','el limón','cytryna'),
('Las Frutas','Owoce','la mandarina','mandarynka'),
('Las Frutas','Owoce','el pomelo','grejpfrut'),
('Las Frutas','Owoce','la uva','winogrono'),
('Las Frutas','Owoce','la fresa','truskawka'),
('Las Frutas','Owoce','la frambuesa','malina'),
('Las Frutas','Owoce','el arándano','borówka / jagoda'),
('Las Frutas','Owoce','la mora','jeżyna'),
('Las Frutas','Owoce','la cereza','czereśnia / wiśnia'),
('Las Frutas','Owoce','la ciruela','śliwka'),
('Las Frutas','Owoce','el melocotón','brzoskwinia'),
('Las Frutas','Owoce','el albaricoque','morela'),
('Las Frutas','Owoce','la nectarina','nektarynka'),
('Las Frutas','Owoce','la sandía','arbuz'),
('Las Frutas','Owoce','el melón','melon'),
('Las Frutas','Owoce','la piña','ananas'),
('Las Frutas','Owoce','el mango','mango'),
('Las Frutas','Owoce','la papaya','papaja'),
('Las Frutas','Owoce','el coco','kokos'),
('Las Frutas','Owoce','el kiwi','kiwi'),
('Las Frutas','Owoce','el higo','figa'),
('Las Frutas','Owoce','la granada','granat (owoc)'),
('Las Frutas','Owoce','el maracuyá','marakuja'),
('Las Frutas','Owoce','la guayaba','gujawa'),
('Las Frutas','Owoce','la lima','limonka'),
('Las Frutas','Owoce','el caqui','persymona / kaki'),
('Las Frutas','Owoce','el membrillo','pigwa'),
('Las Frutas','Owoce','el dátil','daktyl'),
('Las Frutas','Owoce','la pasa','rodzynka'),
('Las Frutas','Owoce','la almendra','migdał'),
('Las Frutas','Owoce','la nuez','orzech włoski'),
('Las Frutas','Owoce','la avellana','orzech laskowy'),
('Las Frutas','Owoce','el cacahuete / el maní','orzeszek ziemny'),
('Las Frutas','Owoce','el pistacho','pistacja'),
('Las Frutas','Owoce','la castaña','kasztan'),
('Las Frutas','Owoce','la semilla','nasiono'),
('Las Frutas','Owoce','la pepita','pestka'),
('Las Frutas','Owoce','la cáscara','skórka / łupina'),
('Las Frutas','Owoce','la pulpa','miąższ'),
('Las Frutas','Owoce','el zumo / el jugo','sok'),
('Las Frutas','Owoce','maduro','dojrzały'),
('Las Frutas','Owoce','verde (inmaduro)','niedojrzały'),
('Las Frutas','Owoce','dulce','słodki'),
('Las Frutas','Owoce','ácido','kwaśny'),
('Las Frutas','Owoce','pelar','obierać'),
('La Carne','Mięso','la carne','mięso'),
('La Carne','Mięso','el cerdo','wieprzowina'),
('La Carne','Mięso','la ternera','cielęcina'),
('La Carne','Mięso','la vaca','wołowina'),
('La Carne','Mięso','el buey','mięso wołowe (z wołu)'),
('La Carne','Mięso','el pollo','kurczak'),
('La Carne','Mięso','el pavo','indyk'),
('La Carne','Mięso','el pato','kaczka'),
('La Carne','Mięso','el cordero','jagnięcina'),
('La Carne','Mięso','la oveja','baranina'),
('La Carne','Mięso','el conejo','królik'),
('La Carne','Mięso','el venado','dziczyzna (jeleń)'),
('La Carne','Mięso','el jabalí','dzik'),
('La Carne','Mięso','el filete','filet / stek'),
('La Carne','Mięso','la chuleta','kotlet z kością'),
('La Carne','Mięso','el lomo','schab / polędwica'),
('La Carne','Mięso','la costilla','żeberko'),
('La Carne','Mięso','la carne picada','mięso mielone'),
('La Carne','Mięso','la salchicha','parówka / kiełbaska'),
('La Carne','Mięso','el chorizo','chorizo (kiełbasa)'),
('La Carne','Mięso','el jamón','szynka'),
('La Carne','Mięso','el jamón serrano','szynka dojrzewająca'),
('La Carne','Mięso','el jamón cocido','szynka gotowana'),
('La Carne','Mięso','el tocino / el bacon','boczek'),
('La Carne','Mięso','el salami','salami'),
('La Carne','Mięso','la morcilla','kaszanka'),
('La Carne','Mięso','el paté','pasztet'),
('La Carne','Mięso','el asado','pieczeń'),
('La Carne','Mięso','la pechuga','pierś (np. z kurczaka)'),
('La Carne','Mięso','el muslo','udo / udko'),
('La Carne','Mięso','la alita','skrzydełko'),
('La Carne','Mięso','la casquería','podroby'),
('La Carne','Mięso','el hígado','wątróbka'),
('La Carne','Mięso','el corazón','serce'),
('La Carne','Mięso','la lengua','język (mięso)'),
('La Carne','Mięso','los callos','flaki'),
('La Carne','Mięso','la carne asada','mięso pieczone'),
('La Carne','Mięso','la carne frita','mięso smażone'),
('La Carne','Mięso','el estofado','gulasz'),
('La Carne','Mięso','el guiso','potrawka / duszony posiłek'),
('La Carne','Mięso','crudo','surowy'),
('La Carne','Mięso','poco hecho','słabo wysmażony (krwisty)'),
('La Carne','Mięso','en su punto','średnio wysmażony'),
('La Carne','Mięso','muy hecho','dobrze wysmażony'),
('La Carne','Mięso','tierno','miękki / kruchy (o mięsie)'),
('La Carne','Mięso','duro','twardy / żylasty'),
('La Carne','Mięso','el carnicero','rzeźnik'),
('La Carne','Mięso','la carnicería','sklep mięsny'),
('La Carne','Mięso','el ave','drób'),
('La Carne','Mięso','el embutido','wędlina'),
('El Pescado y Marisco','Ryby i Owoce morza','el pescado','ryba (do jedzenia)'),
('El Pescado y Marisco','Ryby i Owoce morza','el marisco','owoce morza'),
('El Pescado y Marisco','Ryby i Owoce morza','el salmón','łosoś'),
('El Pescado y Marisco','Ryby i Owoce morza','el atún','tuńczyk'),
('El Pescado y Marisco','Ryby i Owoce morza','el bacalao','dorsz'),
('El Pescado y Marisco','Ryby i Owoce morza','la merluza','morszczuk'),
('El Pescado y Marisco','Ryby i Owoce morza','la sardina','sardynka'),
('El Pescado y Marisco','Ryby i Owoce morza','el boquerón','sardela / anchois'),
('El Pescado y Marisco','Ryby i Owoce morza','la trucha','pstrąg'),
('El Pescado y Marisco','Ryby i Owoce morza','la dorada','dorada'),
('El Pescado y Marisco','Ryby i Owoce morza','la lubina','okoń morski'),
('El Pescado y Marisco','Ryby i Owoce morza','el pez espada','miecznik'),
('El Pescado y Marisco','Ryby i Owoce morza','el lenguado','sola'),
('El Pescado y Marisco','Ryby i Owoce morza','el rodaballo','turbot'),
('El Pescado y Marisco','Ryby i Owoce morza','la caballa','makrela'),
('El Pescado y Marisco','Ryby i Owoce morza','la anguila','węgorz'),
('El Pescado y Marisco','Ryby i Owoce morza','el rape','żabnica'),
('El Pescado y Marisco','Ryby i Owoce morza','el pulpo','ośmiornica'),
('El Pescado y Marisco','Ryby i Owoce morza','el calamar','kalamar'),
('El Pescado y Marisco','Ryby i Owoce morza','la sepia','mątwa'),
('El Pescado y Marisco','Ryby i Owoce morza','la gamba','krewetka (mniejsza)'),
('El Pescado y Marisco','Ryby i Owoce morza','el langostino','krewetka (większa)'),
('El Pescado y Marisco','Ryby i Owoce morza','la langosta','langusta'),
('El Pescado y Marisco','Ryby i Owoce morza','el cangrejo','krab'),
('El Pescado y Marisco','Ryby i Owoce morza','el mejillón','omułek / małż'),
('El Pescado y Marisco','Ryby i Owoce morza','la ostra','ostryga'),
('El Pescado y Marisco','Ryby i Owoce morza','la almeja','małż (zwyczajny)'),
('El Pescado y Marisco','Ryby i Owoce morza','la vieira','przegrzebek'),
('El Pescado y Marisco','Ryby i Owoce morza','el berberecho','sercówka'),
('El Pescado y Marisco','Ryby i Owoce morza','el erizo de mar','jeżowiec'),
('El Pescado y Marisco','Ryby i Owoce morza','el caviar','kawior'),
('El Pescado y Marisco','Ryby i Owoce morza','la espina','ość'),
('El Pescado y Marisco','Ryby i Owoce morza','la escama','łuska'),
('El Pescado y Marisco','Ryby i Owoce morza','la aleta','płetwa'),
('El Pescado y Marisco','Ryby i Owoce morza','las agallas','skrzela'),
('El Pescado y Marisco','Ryby i Owoce morza','la cola','ogon'),
('El Pescado y Marisco','Ryby i Owoce morza','pescar','łowić ryby'),
('El Pescado y Marisco','Ryby i Owoce morza','el pescador','rybak / wędkarz'),
('El Pescado y Marisco','Ryby i Owoce morza','la pescadería','sklep rybny'),
('El Pescado y Marisco','Ryby i Owoce morza','fresco','świeży'),
('El Pescado y Marisco','Ryby i Owoce morza','congelado','mrożony'),
('El Pescado y Marisco','Ryby i Owoce morza','ahumado','wędzony'),
('El Pescado y Marisco','Ryby i Owoce morza','enlatado','w puszce / konserwowy'),
('El Pescado y Marisco','Ryby i Owoce morza','el filete de pescado','filet rybny'),
('El Pescado y Marisco','Ryby i Owoce morza','el sushi','sushi'),
('El Pescado y Marisco','Ryby i Owoce morza','la mariscada','półmisek owoców morza'),
('El Pescado y Marisco','Ryby i Owoce morza','la red','sieć rybacka'),
('El Pescado y Marisco','Ryby i Owoce morza','el anzuelo','haczyk (na ryby)'),
('El Pescado y Marisco','Ryby i Owoce morza','la caña de pescar','wędka'),
('El Pescado y Marisco','Ryby i Owoce morza','el mar y montaña','danie mięsno-rybne (surf and turf)'),
('Los Postres','Desery','el postre','deser'),
('Los Postres','Desery','la tarta / el pastel','ciasto / tort'),
('Los Postres','Desery','el bizcocho','biszkopt / babka'),
('Los Postres','Desery','la galleta','ciastko'),
('Los Postres','Desery','el helado','lody'),
('Los Postres','Desery','el chocolate','czekolada'),
('Los Postres','Desery','el caramelo','cukierek / karmel'),
('Los Postres','Desery','el bombón','pralina / czekoladka'),
('Los Postres','Desery','el chicle','guma do żucia'),
('Los Postres','Desery','la gominola','żelek'),
('Los Postres','Desery','el flan','flan (krem karmelowy)'),
('Los Postres','Desery','las natillas','krem budyniowy'),
('Los Postres','Desery','el arroz con leche','ryż na mleku'),
('Los Postres','Desery','la crema catalana','krem kataloński'),
('Los Postres','Desery','el churro','churro'),
('Los Postres','Desery','el buñuelo','pączek hiszpański'),
('Los Postres','Desery','la magdalena','muffinka / magdalenka'),
('Los Postres','Desery','el cruasán','rogalik / croissant'),
('Los Postres','Desery','la ensaimada','drożdżówka z Majorki'),
('Los Postres','Desery','el turrón','nugat / turron'),
('Los Postres','Desery','el mazapán','marcepan'),
('Los Postres','Desery','el polvorón','kruche ciastko świąteczne'),
('Los Postres','Desery','el roscón','ciasto w kształcie pierścienia'),
('Los Postres','Desery','el gofre','gofr'),
('Los Postres','Desery','el crep','naleśnik'),
('Los Postres','Desery','la tortita','pankejk / placuszek'),
('Los Postres','Desery','la mermelada','dżem / marmolada'),
('Los Postres','Desery','la miel','miód'),
('Los Postres','Desery','el sirope','syrop'),
('Los Postres','Desery','la nata','bita śmietana'),
('Los Postres','Desery','la crema','krem'),
('Los Postres','Desery','la vainilla','wanilia'),
('Los Postres','Desery','la canela','cynamon'),
('Los Postres','Desery','el azúcar','cukier'),
('Los Postres','Desery','el azúcar glas','cukier puder'),
('Los Postres','Desery','el edulcorante','słodzik'),
('Los Postres','Desery','dulce','słodki'),
('Los Postres','Desery','el postre casero','domowy deser'),
('Los Postres','Desery','la repostería','cukiernictwo / wypieki'),
('Los Postres','Desery','el pastelero','cukiernik'),
('Los Postres','Desery','la pastelería','cukiernia'),
('Los Postres','Desery','la panadería','piekarnia'),
('Los Postres','Desery','hornear','piec (w piekarniku)'),
('Los Postres','Desery','la masa','ciasto (masa)'),
('Los Postres','Desery','la harina','mąka'),
('Los Postres','Desery','la levadura','drożdże / proszek do pieczenia'),
('Los Postres','Desery','el horno','piekarnik'),
('Los Postres','Desery','derretir','roztapiać (np. czekoladę)'),
('Los Postres','Desery','espolvorear','posypywać'),
('Los Postres','Desery','rellenar','nadziewać');
