insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Guerra y Paz','Wojna i pokój','la guerra','wojna'),
('Guerra y Paz','Wojna i pokój','la paz','pokój'),
('Guerra y Paz','Wojna i pokój','el conflicto','konflikt'),
('Guerra y Paz','Wojna i pokój','la batalla','bitwa'),
('Guerra y Paz','Wojna i pokój','el combate','walka / starcie'),
('Guerra y Paz','Wojna i pokój','el ejército','armia / wojsko'),
('Guerra y Paz','Wojna i pokój','el soldado','żołnierza'),
('Guerra y Paz','Wojna i pokój','el oficial','oficer'),
('Guerra y Paz','Wojna i pokój','el general','generał'),
('Guerra y Paz','Wojna i pokój','el comandante','dowódca / komendant'),
('Guerra y Paz','Wojna i pokój','el enemigo','wróg'),
('Guerra y Paz','Wojna i pokój','el aliado','sojusznik'),
('Guerra y Paz','Wojna i pokój','la alianza','sojusz'),
('Guerra y Paz','Wojna i pokój','la tregua','zawieszenie broni / rozejm'),
('Guerra y Paz','Wojna i pokój','el tratado de paz','traktat pokojowy'),
('Guerra y Paz','Wojna i pokój','la rendición','kapitulacja'),
('Guerra y Paz','Wojna i pokój','rendirse','poddać się'),
('Guerra y Paz','Wojna i pokój','la victoria','zwycięstwo'),
('Guerra y Paz','Wojna i pokój','la derrota','porażka'),
('Guerra y Paz','Wojna i pokój','el arma','broń'),
('Guerra y Paz','Wojna i pokój','el arma de fuego','broń palna'),
('Guerra y Paz','Wojna i pokój','el rifle','karabin'),
('Guerra y Paz','Wojna i pokój','la pistola','pistolet'),
('Guerra y Paz','Wojna i pokój','la espada','miecz'),
('Guerra y Paz','Wojna i pokój','la bomba','bomba'),
('Guerra y Paz','Wojna i pokój','el misil','pocisk rakietowy'),
('Guerra y Paz','Wojna i pokój','el tanque','czołg'),
('Guerra y Paz','Wojna i pokój','el avión de combate','samolot myśliwski / myśliwiec'),
('Guerra y Paz','Wojna i pokój','el buque de guerra','okręt wojenny'),
('Guerra y Paz','Wojna i pokój','la base militar','baza wojskowa'),
('Guerra y Paz','Wojna i pokój','la trinchera','okop'),
('Guerra y Paz','Wojna i pokój','el frente','front'),
('Guerra y Paz','Wojna i pokój','la estrategia','strategia'),
('Guerra y Paz','Wojna i pokój','la táctica','taktyka'),
('Guerra y Paz','Wojna i pokój','el espía','szpieg'),
('Guerra y Paz','Wojna i pokój','el espionaje','szpiegostwo'),
('Guerra y Paz','Wojna i pokój','la inteligencia','wywiad (służba)'),
('Guerra y Paz','Wojna i pokój','el prisionero de guerra','jeeniec wojenny'),
('Guerra y Paz','Wojna i pokój','el refugiado','uchodźca'),
('Guerra y Paz','Wojna i pokój','la víctima','ofiara'),
('Guerra y Paz','Wojna i pokój','el herido','ranny'),
('Guerra y Paz','Wojna i pokój','el hospital de campaña','szpital polowy'),
('Guerra y Paz','Wojna i pokój','la destrucción','zniszczenie'),
('Guerra y Paz','Wojna i pokój','los escombros','gruzy'),
('Guerra y Paz','Wojna i pokój','la amenaza','zagrożenie'),
('Guerra y Paz','Wojna i pokój','la tensión','napięcie'),
('Guerra y Paz','Wojna i pokój','la diplomacia','dyplomacja'),
('Guerra y Paz','Wojna i pokój','el desarme','rozbrojenie'),
('Guerra y Paz','Wojna i pokój','la seguridad','bezpieczeństwo'),
('Guerra y Paz','Wojna i pokój','el monumento a los caídos','pomnik poległych'),
('Sistema Político','System polityczny','el sistema político','system polityczny'),
('Sistema Político','System polityczny','la política','polityka'),
('Sistema Político','System polityczny','el gobierno','rząd'),
('Sistema Político','System polityczny','el Estado','państwo'),
('Sistema Político','System polityczny','la democracia','demokracja'),
('Sistema Político','System polityczny','la dictadura','dyktatura'),
('Sistema Político','System polityczny','la monarquía','monarchia'),
('Sistema Político','System polityczny','la república','republika'),
('Sistema Político','System polityczny','la constitución','konstytucja'),
('Sistema Político','System polityczny','las leyes','prawa / ustawy'),
('Sistema Político','System polityczny','el poder','władza'),
('Sistema Político','System polityczny','la división de poderes','trójpodział władzy'),
('Sistema Político','System polityczny','el poder ejecutivo','władza wykonawcza'),
('Sistema Político','System polityczny','el poder legislativo','władza ustawodawcza'),
('Sistema Político','System polityczny','el poder judicial','władza sądownicza'),
('Sistema Político','System polityczny','el parlamento','parlament'),
('Sistema Político','System polityczny','el congreso','kongres'),
('Sistema Político','System polityczny','el senado','senat'),
('Sistema Político','System polityczny','el diputado','poseł'),
('Sistema Político','System polityczny','el senador','senator'),
('Sistema Político','System polityczny','el presidente','prezident'),
('Sistema Político','System polityczny','el primer ministro','premier'),
('Sistema Político','System polityczny','el ministro','minister'),
('Sistema Político','System polityczny','el ministerio','ministerstwo'),
('Sistema Político','System polityczny','el partido político','partia polityczna'),
('Sistema Político','System polityczny','las elecciones','wybory'),
('Sistema Político','System polityczny','votar','głosować'),
('Sistema Político','System polityczny','el voto','głos'),
('Sistema Político','System polityczny','el electorado','elektorat / wyborcy'),
('Sistema Político','System polityczny','la campaña electoral','kampania wyborcza'),
('Sistema Político','System polityczny','el candidato','kandydat'),
('Sistema Político','System polityczny','la oposición','opozycja'),
('Sistema Político','System polityczny','la mayoría','większość'),
('Sistema Político','System polityczny','la minoría','mniejszość'),
('Sistema Político','System polityczny','la coalición','koalicja'),
('Sistema Político','System polityczny','el ayuntamiento','urząd miasta / ratusz'),
('Sistema Político','System polityczny','el alcalde','burmistrz / prezydent miasta'),
('Sistema Político','System polityczny','la diplomacia','dyplomacja'),
('Sistema Político','System polityczny','el embajador','ambasador'),
('Sistema Político','System polityczny','la embajada','ambasada'),
('Sistema Político','System polityczny','el derecho','prawo'),
('Sistema Político','System polityczny','la libertad','wolność'),
('Sistema Político','System polityczny','la igualdad','równość'),
('Sistema Político','System polityczny','la justicia','sprawiedliwość'),
('Sistema Político','System polityczny','la corrupción','korupcja'),
('Sistema Político','System polityczny','el ciudadano','obywatel'),
('Sistema Político','System polityczny','la ciudadanía','obywatelstwo'),
('Sistema Político','System polityczny','la reforma','reforma'),
('Sistema Político','System polityczny','la crisis política','kryzys polityczny'),
('Sistema Político','System polityczny','la soberanía','suwerenność'),
('Elecciones','Wybory','las elecciones','wybory'),
('Elecciones','Wybory','el voto','głos'),
('Elecciones','Wybory','votar','głosować'),
('Elecciones','Wybory','el votante','wyborca'),
('Elecciones','Wybory','el electorado','elektorat'),
('Elecciones','Wybory','el colegio electoral','lokal wyborczy'),
('Elecciones','Wybory','la urna','urna wyborcza'),
('Elecciones','Wybory','la papeleta','karta do głosowania'),
('Elecciones','Wybory','el candidato','kandydat'),
('Elecciones','Wybory','el partido político','partia polityczna'),
('Elecciones','Wybory','la campaña electoral','kampania wyborcza'),
('Elecciones','Wybory','el mitin','wiec wyborczy'),
('Elecciones','Wybory','el debate','debata'),
('Elecciones','Wybory','el programa electoral','program wyborczy'),
('Elecciones','Wybory','la encuesta','sondaż / ankieta'),
('Elecciones','Wybory','el sondeo de opinión','sondaż opinii publicznej'),
('Elecciones','Wybory','la mayoría','większość'),
('Elecciones','Wybory','la minoría','mniejszość'),
('Elecciones','Wybory','la coalición','koalicja'),
('Elecciones','Wybory','el escaño','mandat / miejsce w parlamencie'),
('Elecciones','Wybory','el parlamento','parlament'),
('Elecciones','Wybory','el congreso','kongres'),
('Elecciones','Wybory','el senado','senat'),
('Elecciones','Wybory','el diputado','poseł'),
('Elecciones','Wybory','el senador','senator'),
('Elecciones','Wybory','el alcalde','burmistrz / prezydent miasta'),
('Elecciones','Wybory','el presidente','prezydent'),
('Elecciones','Wybory','el primer ministro','premier'),
('Elecciones','Wybory','el gobierno','rząd'),
('Elecciones','Wybory','la oposición','opozycja'),
('Elecciones','Wybory','ganar','wygrać'),
('Elecciones','Wybory','perder','przegrać'),
('Elecciones','Wybory','el resultado','wynik'),
('Elecciones','Wybory','la victoria','zwycięstwo'),
('Elecciones','Wybory','la derrota','porażka'),
('Elecciones','Wybory','el recuento','przeliczanie głosów'),
('Elecciones','Wybory','la abstención','abstencja'),
('Elecciones','Wybory','el censo electoral','spis wyborców'),
('Elecciones','Wybory','el sufragio','prawo głosu'),
('Elecciones','Wybory','el sufragio universal','wybory powszechne'),
('Elecciones','Wybory','la circunscripción','okręg wyborczy'),
('Elecciones','Wybory','la jornada electoral','dzień wyborów'),
('Elecciones','Wybory','el escrutinio','skrutynium / podsumowanie głosów'),
('Elecciones','Wybory','proclamar','ogłosić / proklamować'),
('Elecciones','Wybory','jurar','składać przysięgę'),
('Elecciones','Wybory','la investidura','zaprzysiężenie'),
('Elecciones','Wybory','el mandato','kadencja / mandat'),
('Elecciones','Wybory','la reelección','reelekcja / ponowny wybór'),
('Elecciones','Wybory','fraudulento','sfałszowany / oszukańczy'),
('Elecciones','Wybory','democrático','demokratyczny'),
('Derechos Humanos','Prawa człowieka','los derechos humanos','prawa człowieka'),
('Derechos Humanos','Prawa człowieka','el derecho','prawo'),
('Derechos Humanos','Prawa człowieka','la libertad','wolność'),
('Derechos Humanos','Prawa człowieka','la igualdad','równość'),
('Derechos Humanos','Prawa człowieka','la dignidad','godność'),
('Derechos Humanos','Prawa człowieka','la justicia','sprawiedliwość'),
('Derechos Humanos','Prawa człowieka','la discriminación','dyskryminacja'),
('Derechos Humanos','Prawa człowieka','discriminar','dyskryminować'),
('Derechos Humanos','Prawa człowieka','el racismo','rasizm'),
('Derechos Humanos','Prawa człowieka','racista','rasistowski'),
('Derechos Humanos','Prawa człowieka','la xenofobia','ksenofobia'),
('Derechos Humanos','Prawa człowieka','el sexismo','seksizm'),
('Derechos Humanos','Prawa człowieka','la igualdad de género','równość płci'),
('Derechos Humanos','Prawa człowieka','la tolerancia','tolerancja'),
('Derechos Humanos','Prawa człowieka','tolerar','tolerować'),
('Derechos Humanos','Prawa człowieka','la opresión','ucisk / uciemiężenie'),
('Derechos Humanos','Prawa człowieka','oprimir','uciskać'),
('Derechos Humanos','Prawa człowieka','la persecución','prześladowanie'),
('Derechos Humanos','Prawa człowieka','perseguir','prześladować'),
('Derechos Humanos','Prawa człowieka','la libertad de expresión','wolność słowa'),
('Derechos Humanos','Prawa człowieka','la libertad de prensa','wolność prasy'),
('Derechos Humanos','Prawa człowieka','la libertad religiosa','wolność religijna'),
('Derechos Humanos','Prawa człowieka','la libertad de reunión','wolność zgromadzeń'),
('Derechos Humanos','Prawa człowieka','el asilo','azyl'),
('Derechos Humanos','Prawa człowieka','el refugiado','uchodźca'),
('Derechos Humanos','Prawa człowieka','el asilado','azylant'),
('Derechos Humanos','Prawa człowieka','la tortura','tortura'),
('Derechos Humanos','Prawa człowieka','torturar','torturować'),
('Derechos Humanos','Prawa człowieka','la esclavitud','niewolnictwo'),
('Derechos Humanos','Prawa człowieka','el esclavo','niewolnik'),
('Derechos Humanos','Prawa człowieka','la Declaración Universal','Powszechna Deklaracja'),
('Derechos Humanos','Prawa człowieka','Amnistía Internacional','Amnesty International'),
('Derechos Humanos','Prawa człowieka','el activista','aktywista'),
('Derechos Humanos','Prawa człowieka','la manifestación','manifestacja'),
('Derechos Humanos','Prawa człowieka','manifestarse','manifestować'),
('Derechos Humanos','Prawa człowieka','la protesta','protest'),
('Derechos Humanos','Prawa człowieka','protestar','protestować'),
('Derechos Humanos','Prawa człowieka','la huelga','strajk'),
('Derechos Humanos','Prawa człowieka','la censura','cenzura'),
('Derechos Humanos','Prawa człowieka','censurar','cenzurować'),
('Derechos Humanos','Prawa człowieka','la igualdad de oportunidades','równość szans'),
('Derechos Humanos','Prawa człowieka','el derecho al voto','prawo do głosowania'),
('Derechos Humanos','Prawa człowieka','la dignidad humana','godność ludzka'),
('Derechos Humanos','Prawa człowieka','el respeto','szacunek'),
('Derechos Humanos','Prawa człowieka','respetar','szanować'),
('Derechos Humanos','Prawa człowieka','la vulnerabilidad','wrażliwość / podatność'),
('Derechos Humanos','Prawa człowieka','vulnerable','wrażliwy / podatny'),
('Derechos Humanos','Prawa człowieka','la injusticia','niesprawiedliwość'),
('Derechos Humanos','Prawa człowieka','la impunidad','bezkarność'),
('Derechos Humanos','Prawa człowieka','la paz','pokój');
