insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Religiones del Mundo','Religie świata','la religión','religión'),
('Religiones del Mundo','Religie świata','la religión','religia'),
('Religiones del Mundo','Religie świata','la fe','wiara'),
('Religiones del Mundo','Religie świata','la creencia','przekonanie / wierzenie'),
('Religiones del Mundo','Religie świata','el dios','bóg'),
('Religiones del Mundo','Religie świata','la diosa','bogini'),
('Religiones del Mundo','Religie świata','lo divino','boskość'),
('Religiones del Mundo','Religie świata','el culto','kult'),
('Religiones del Mundo','Religie świata','el rito','rytuał'),
('Religiones del Mundo','Religie świata','la ceremonia','ceremonia'),
('Religiones del Mundo','Religie świata','la oración','modlitwa'),
('Religiones del Mundo','Religie świata','orar','modlić się'),
('Religiones del Mundo','Religie świata','el templo','świątynia'),
('Religiones del Mundo','Religie świata','la iglesia','kościół'),
('Religiones del Mundo','Religie świata','la mezquita','meczet'),
('Religiones del Mundo','Religie świata','la sinagoga','synagoga'),
('Religiones del Mundo','Religie świata','el templo budista','świątynia buddyjska'),
('Religiones del Mundo','Religie świata','el sacerdote','kapłan'),
('Religiones del Mundo','Religie świata','el pastor','pastor'),
('Religiones del Mundo','Religie świata','el imán','imam'),
('Religiones del Mundo','Religie świata','el rabino','rabin'),
('Religiones del Mundo','Religie świata','el monje','mnich'),
('Religiones del Mundo','Religie świata','la monja','mianich'),
('Religiones del Mundo','Religie świata','el papa','papież'),
('Religiones del Mundo','Religie świata','el obispo','biskup'),
('Religiones del Mundo','Religie świata','el cristiano','chrześcijanin'),
('Religiones del Mundo','Religie świata','el católico','katolik'),
('Religiones del Mundo','Religie świata','el protestante','protestant'),
('Religiones del Mundo','Religie świata','el musulmán','muzułmanin'),
('Religiones del Mundo','Religie świata','el judío','żyd'),
('Religiones del Mundo','Religie świata','el budista','buddysta'),
('Religiones del Mundo','Religie świata','el hinduista','hinduista'),
('Religiones del Mundo','Religie świata','la Biblia','Biblia'),
('Religiones del Mundo','Religie świata','el Corán','Koran'),
('Religiones del Mundo','Religie świata','la Torá','Tora'),
('Religiones del Mundo','Religie świata','el dogma','dogmat'),
('Religiones del Mundo','Religie świata','la salvación','zbawienie'),
('Religiones del Mundo','Religie świata','el pecado','grzech'),
('Religiones del Mundo','Religie świata','pecar','grzeszyć'),
('Religiones del Mundo','Religie świata','el perdón','przebaczenie'),
('Religiones del Mundo','Religie świata','el cielo','niebo'),
('Religiones del Mundo','Religie świata','el infierno','piekło'),
('Religiones del Mundo','Religie świata','el alma','dusza'),
('Religiones del Mundo','Religie świata','la reencarnación','reinkarnacja'),
('Religiones del Mundo','Religie świata','el milagro','cud'),
('Religiones del Mundo','Religie świata','la profecía','proroctwo'),
('Religiones del Mundo','Religie świata','el profeta','prorok'),
('Religiones del Mundo','Religie świata','la espiritualidad','duchowość'),
('Religiones del Mundo','Religie świata','el ateo','ateista'),
('Religiones del Mundo','Religie świata','el agnóstico','agnostyk'),
('Mitología','Mitologia','la mitología','mitologia'),
('Mitología','Mitologia','el mito','mit'),
('Mitología','Mitologia','la leyenda','legenda'),
('Mitología','Mitologia','el dios','bóg'),
('Mitología','Mitologia','la diosa','bogini'),
('Mitología','Mitologia','el semidiós','półbóg'),
('Mitología','Mitologia','el Héroe','bohater'),
('Mitología','Mitologia','el monstruo','potwór'),
('Mitología','Mitologia','el titán','tytan'),
('Mitología','Mitologia','la ninfa','nimfa'),
('Mitología','Mitologia','el dragón','smok'),
('Mitología','Mitologia','el Olimpo','Olimp'),
('Mitología','Mitologia','el inframundo','zaświaty / podziemia'),
('Mitología','Mitologia','el destino','przeznaczenie'),
('Mitología','Mitologia','la profecía','proroctwo'),
('Mitología','Mitologia','el hechizo','klątwa / czar'),
('Mitología','Mitologia','la magia','magia'),
('Mitología','Mitologia','la inmortalidad','nieśmiertelność'),
('Mitología','Mitologia','inmortal','nieśmiertelny'),
('Mitología','Mitologia','el Olimpo griego','grecki Olimp'),
('Mitología','Mitologia','Zeus','Zeus'),
('Mitología','Mitologia','Hera','Hera'),
('Mitología','Mitologia','Poseidón','Posejdon'),
('Mitología','Mitologia','Hades','Hades'),
('Mitología','Mitologia','Atenea','Ateny / Atena'),
('Mitología','Mitologia','Apolo','Apolo'),
('Mitología','Mitologia','Afrodita','Afrodyta'),
('Mitología','Mitologia','Ares','Ares'),
('Mitología','Mitologia','Hermes','Hermes'),
('Mitología','Mitologia','Dionisio','Dionizjusz / Dionizos'),
('Mitología','Mitologia','Hércules','Herkules'),
('Mitología','Mitologia','Aquiles','Achilles'),
('Mitología','Mitologia','Ulises / Odiseo','Odyseusz'),
('Mitología','Mitologia','Prometeo','Prometeusz'),
('Mitología','Mitologia','Medusa','Muza / Meduza'),
('Mitología','Mitologia','el Minotauro','Minotaur'),
('Mitología','Mitologia','el Pegaso','Pegaz'),
('Mitología','Mitologia','la Hidra','Hydra'),
('Mitología','Mitologia','la Quimera','Chimera'),
('Mitología','Mitologia','el laberinto','labirynt'),
('Mitología','Mitologia','el tridente','trójząb'),
('Mitología','Mitologia','el rayo','piorun (boga)'),
('Mitología','Mitologia','la ambrosía','ambrozja'),
('Mitología','Mitologia','el néctar','nektar (bogów)'),
('Mitología','Mitologia','la metamorfosis','metamorfoza'),
('Mitología','Mitologia','el panteón','panteon'),
('Mitología','Mitologia','la ofrenda','ofiara'),
('Mitología','Mitologia','el sacrificio','składanie ofiary'),
('Mitología','Mitologia','la epopeya','epopeja'),
('Mitología','Mitologia','el relato épico','opowieść epicka'),
('Filosofía','Filozofia','la filosofía','filozofia'),
('Filosofía','Filozofia','el filósofo','filozof'),
('Filosofía','Filozofia','pensar','myśleć'),
('Filosofía','Filozofia','el pensamiento','myśl'),
('Filosofía','Filozofia','la lógica','logika'),
('Filosofía','Filozofia','la ética','etyka'),
('Filosofía','Filozofia','la moral','moralność'),
('Filosofía','Filozofia','la metafísica','metafizyka'),
('Filosofía','Filozofia','la epistemología','epistemologia'),
('Filosofía','Filozofia','la ontología','ontologia'),
('Filosofía','Filozofia','la estética','estetyka'),
('Filosofía','Filozofia','la verdad','prawda'),
('Filosofía','Filozofia','la mentira','kłamstwo'),
('Filosofía','Filozofia','la realidad','rzeczywistość'),
('Filosofía','Filozofia','la existencia','egzystencja / istnienie'),
('Filosofía','Filozofia','el ser','byt / istota'),
('Filosofía','Filozofia','la conciencia','świadomość'),
('Filosofía','Filozofia','el conocimiento','wiedza'),
('Filosofía','Filozofia','la razón','rozum'),
('Filosofía','Filozofia','la sabiduría','mądrość'),
('Filosofía','Filozofia','el alma','dusza'),
('Filosofía','Filozofia','el espíritu','duch'),
('Filosofía','Filozofia','el libre albedrío','wolna wola'),
('Filosofía','Filozofia','el determinismo','determinizm'),
('Filosofía','Filozofia','el escepticismo','sceptycyzm'),
('Filosofía','Filozofia','el empirismo','empiryzm'),
('Filosofía','Filozofia','el racionalismo','racjonalizm'),
('Filosofía','Filozofia','el existencialismo','egzystencjalizm'),
('Filosofía','Filozofia','el estoicismo','stoicyzm'),
('Filosofía','Filozofia','el hedonismo','hedonizm'),
('Filosofía','Filozofia','el nihilismo','nihilizm'),
('Filosofía','Filozofia','el idealismo','idealizm'),
('Filosofía','Filozofia','el materialismo','materializm'),
('Filosofía','Filozofia','la dialéctica','dialektyka'),
('Filosofía','Filozofia','el argumento','argument'),
('Filosofía','Filozofia','la premisa','przesłanka'),
('Filosofía','Filozofia','la conclusión','wniosek'),
('Filosofía','Filozofia','la paradoja','paradoks'),
('Filosofía','Filozofia','el dilema','dylemat'),
('Filosofía','Filozofia','la hipótesis','hipoteza'),
('Filosofía','Filozofia','el sentido','sens'),
('Filosofía','Filozofia','el absurdo','absurd'),
('Filosofía','Filozofia','la libertad','wolność'),
('Filosofía','Filozofia','la justicia','sprawiedliwość'),
('Filosofía','Filozofia','la virtud','cnota'),
('Filosofía','Filozofia','el vicio','wada / grzech'),
('Filosofía','Filozofia','la felicidad','szczęście'),
('Filosofía','Filozofia','el bien','dobro'),
('Filosofía','Filozofia','el mal','zło'),
('Filosofía','Filozofia','la duda','wątpliwość'),
('Psicología','Psychologia','la psicología','psychologia'),
('Psicología','Psychologia','el psicólogo','psycholog'),
('Psicología','Psychologia','el psiquiatra','psychiatra'),
('Psicología','Psychologia','el psicoanálisis','psychoanaliza'),
('Psicología','Psychologia','la mente','umysł'),
('Psicología','Psychologia','el cerebro','mózg'),
('Psicología','Psychologia','la conducta','zachowanie'),
('Psicología','Psychologia','el comportamiento','postawa / zachowanie'),
('Psicología','Psychologia','la emoción','emocja'),
('Psicología','Psychologia','el sentimiento','uczucie'),
('Psicología','Psychologia','la personalidad','osobowość'),
('Psicología','Psychologia','el carácter','charakter'),
('Psicología','Psychologia','el temperamento','temperament'),
('Psicología','Psychologia','el subconsciente','podświadomość'),
('Psicología','Psychologia','el inconsciente','nieświadomość'),
('Psicología','Psychologia','el trauma','trauma'),
('Psicología','Psychologia','la ansiedad','lęk / stan lękowy'),
('Psicología','Psychologia','la depresión','depresja'),
('Psicología','Psychologia','el estrés','stres'),
('Psicología','Psychologia','la terapia','terapia'),
('Psicología','Psychologia','el terapeuta','terapeuta'),
('Psicología','Psychologia','la psicoterapia','psychoterapia'),
('Psicología','Psychologia','el trastorno','zaburzenie'),
('Psicología','Psychologia','la fobia','fobia'),
('Psicología','Psychologia','la obsesión','obsesja'),
('Psicología','Psychologia','la compulsión','kompulsja'),
('Psicología','Psychologia','la autoestima','poczucie własnej wartości'),
('Psicología','Psychologia','el ego','ego'),
('Psicología','Psychologia','la empatía','empatia'),
('Psicología','Psychologia','la motivación','motywacja'),
('Psicología','Psychologia','el estímulo','bodziec'),
('Psicología','Psychologia','la respuesta','reakcja'),
('Psicología','Psychologia','el aprendizaje','nauka / uczenie się'),
('Psicología','Psychologia','la memoria','pamięć'),
('Psicología','Psychologia','el olvido','zapominanie'),
('Psicología','Psychologia','la percepción','percepcja'),
('Psicología','Psychologia','la cognición','poznanie / kognicja'),
('Psicología','Psychologia','el desarrollo','rozwój'),
('Psicología','Psychologia','la inteligencia','inteligencja'),
('Psicología','Psychologia','la creatividad','kreatywność'),
('Psicología','Psychologia','el complejo','kompleks'),
('Psicología','Psychologia','la introversión','introwersja'),
('Psicología','Psychologia','la extroversión','ekstrawersja'),
('Psicología','Psychologia','la frustracion','frustracja'),
('Psicología','Psychologia','el conflicto','konflikt'),
('Psicología','Psychologia','la defensa','obrona (psychologiczna)'),
('Psicología','Psychologia','la resiliencia','odporność psychiczna / rezyliencja'),
('Psicología','Psychologia','la psicosis','psychoza'),
('Psicología','Psychologia','la neurosis','neuroza'),
('Psicología','Psychologia','el bienestar','dobrostan');
