insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Los Animales','Zwierzęta','el animal','zwierzę'),
('Los Animales','Zwierzęta','el perro','pies'),
('Los Animales','Zwierzęta','el gato','kot'),
('Los Animales','Zwierzęta','el ratón','mysz'),
('Los Animales','Zwierzęta','el caballo','koń'),
('Los Animales','Zwierzęta','la vaca','krowa'),
('Los Animales','Zwierzęta','el cerdo','świnia'),
('Los Animales','Zwierzęta','la oveja','owca'),
('Los Animales','Zwierzęta','la cabra','koza'),
('Los Animales','Zwierzęta','el burro','osioł'),
('Los Animales','Zwierzęta','la gallina','kura'),
('Los Animales','Zwierzęta','el gallo','kogut'),
('Los Animales','Zwierzęta','el pato','kaczka'),
('Los Animales','Zwierzęta','el pájaro','ptak'),
('Los Animales','Zwierzęta','el pez','ryba'),
('Los Animales','Zwierzęta','la rana','żaba'),
('Los Animales','Zwierzęta','la serpiente','wąż'),
('Los Animales','Zwierzęta','el cocodrilo','krokodyl'),
('Los Animales','Zwierzęta','la tortuga','żółw'),
('Los Animales','Zwierzęta','el león','lew'),
('Los Animales','Zwierzęta','el tigre','tygrys'),
('Los Animales','Zwierzęta','el elefante','słoń'),
('Los Animales','Zwierzęta','la jirafa','żyrafa'),
('Los Animales','Zwierzęta','el mono','małpa'),
('Los Animales','Zwierzęta','el oso','niedźwiedź'),
('Los Animales','Zwierzęta','el lobo','wilk'),
('Los Animales','Zwierzęta','el zorro','lis'),
('Los Animales','Zwierzęta','el ciervo','jeleń'),
('Los Animales','Zwierzęta','el conejo','królik'),
('Los Animales','Zwierzęta','la liebre','zając'),
('Los Animales','Zwierzęta','el murciélago','nietoperz'),
('Los Animales','Zwierzęta','la mariposa','motyl'),
('Los Animales','Zwierzęta','la mosca','mucha'),
('Los Animales','Zwierzęta','el mosquito','komar'),
('Los Animales','Zwierzęta','la abeja','pszczoła'),
('Los Animales','Zwierzęta','la araña','pająk'),
('Los Animales','Zwierzęta','la hormiga','mrówka'),
('Los Animales','Zwierzęta','el gusano','robak / dżdżownica'),
('Los Animales','Zwierzęta','el caracol','ślimak'),
('Los Animales','Zwierzęta','el cangrejo','krab'),
('Los Animales','Zwierzęta','la ballena','wieloryb'),
('Los Animales','Zwierzęta','el delfín','delfin'),
('Los Animales','Zwierzęta','el tiburón','rekin'),
('Los Animales','Zwierzęta','el pulpo','ośmiornica'),
('Los Animales','Zwierzęta','la foca','foka'),
('Los Animales','Zwierzęta','el pingüino','pingwin'),
('Los Animales','Zwierzęta','el búho','sowa'),
('Los Animales','Zwierzęta','el águila','orzeł'),
('Los Animales','Zwierzęta','el loro','papuga'),
('Los Animales','Zwierzęta','la mascota','zwierzę domowe'),
('Las Profesiones','Zawody','la profesión','zawód'),
('Las Profesiones','Zawody','el trabajo','praca'),
('Las Profesiones','Zawody','el médico / la médica','lekarz / lekarka'),
('Las Profesiones','Zawody','el enfermero / la enfermera','pielęgniarz / pielęgniarka'),
('Las Profesiones','Zawody','el dentista','dentysta'),
('Las Profesiones','Zawody','el veterinario','weterynarz'),
('Las Profesiones','Zawody','el profesor / la profesora','nauczyciel / nauczycielka'),
('Las Profesiones','Zawody','el estudiante','student / uczeń'),
('Las Profesiones','Zawody','el abogado / la abogada','prawnik / prawniczka'),
('Las Profesiones','Zawody','el juez / la jueza','sędzia'),
('Las Profesiones','Zawody','el policía','policjant'),
('Las Profesiones','Zawody','el bombero','strażak'),
('Las Profesiones','Zawody','el soldado','żołnierz'),
('Las Profesiones','Zawody','el ingeniero / la ingeniera','inżynier'),
('Las Profesiones','Zawody','el arquitecto','architekt'),
('Las Profesiones','Zawody','el informático','informatyk'),
('Las Profesiones','Zawody','el científico','naukowiec'),
('Las Profesiones','Zawody','el periodista','dziennikarz'),
('Las Profesiones','Zawody','el escritor / la escritora','pisarz / pisarka'),
('Las Profesiones','Zawody','el actor / la actriz','aktor / aktorka'),
('Las Profesiones','Zawody','el cantante','piosenkarz'),
('Las Profesiones','Zawody','el músico','muzyk'),
('Las Profesiones','Zawody','el artista','artysta'),
('Las Profesiones','Zawody','el pintor / la pintora','malarz / malarka'),
('Las Profesiones','Zawody','el fotógrafo','fotograf'),
('Las Profesiones','Zawody','el cocinero / la cocinera','kucharz / kucharka'),
('Las Profesiones','Zawody','el camarero / la camarera','kelner / kelnerka'),
('Las Profesiones','Zawody','el panadero','piekarz'),
('Las Profesiones','Zawody','el carnicero','rzeźnik'),
('Las Profesiones','Zawody','el peluquero / la peluquera','fryzjer / fryzjerka'),
('Las Profesiones','Zawody','el mecánico','mechanik'),
('Las Profesiones','Zawody','el conductor','kierowca'),
('Las Profesiones','Zawody','el piloto','pilot'),
('Las Profesiones','Zawody','el albañil','murarz'),
('Las Profesiones','Zawody','el electricista','elektryk'),
('Las Profesiones','Zawody','el fontanero','hydraulik'),
('Las Profesiones','Zawody','el carpintero','stolarz'),
('Las Profesiones','Zawody','el agricultor','rolnik'),
('Las Profesiones','Zawody','el jardinero','ogrodnik'),
('Las Profesiones','Zawody','el cartero','listonosz'),
('Las Profesiones','Zawody','el vendedor / la vendedora','sprzedawca / sprzedawczyni'),
('Las Profesiones','Zawody','el dependiente','ekspedient'),
('Las Profesiones','Zawody','el cajero / la cajera','kasjer / kasjerka'),
('Las Profesiones','Zawody','el contable','księgowy'),
('Las Profesiones','Zawody','el secretario / la secretaria','sekretarz / sekretarka'),
('Las Profesiones','Zawody','el jefe / la jefa','szef / szefowa'),
('Las Profesiones','Zawody','el empleado / la empleada','pracownik / pracownica'),
('Las Profesiones','Zawody','el empresario','przedsiębiorca'),
('Las Profesiones','Zawody','el político','polityk'),
('Las Profesiones','Zawody','el gerente','menedżer / kierownik'),
('La Educación','Edukacja','la educación','edukacja'),
('La Educación','Edukacja','la escuela','szkoła'),
('La Educación','Edukacja','el colegio','szkoła (podstawowa)'),
('La Educación','Edukacja','el instituto','liceum / szkoła średnia'),
('La Educación','Edukacja','la universidad','uniwersytet'),
('La Educación','Edukacja','la clase','klasa / lekcja'),
('La Educación','Edukacja','el aula','sala lekcyjna'),
('La Educación','Edukacja','el curso','kurs / rok szkolny'),
('La Educación','Edukacja','la asignatura','przedmiot szkolny'),
('La Educación','Edukacja','el recreo','przerwa'),
('La Educación','Edukacja','el maestro / la maestra','nauczyciel / nauczycielka (klas młodszych)'),
('La Educación','Edukacja','el alumno / la alumna','uczeń / uczennica'),
('La Educación','Edukacja','el compañero de clase','kolega z klasy'),
('La Educación','Edukacja','el director','dyrektor'),
('La Educación','Edukacja','el libro','książka'),
('La Educación','Edukacja','el cuaderno','zeszyt'),
('La Educación','Edukacja','el estuche','piórnik'),
('La Educación','Edukacja','el bolígrafo / el boli','długopis'),
('La Educación','Edukacja','el lápiz','ołówek'),
('La Educación','Edukacja','la goma de borrar','gumka do ścierania'),
('La Educación','Edukacja','el rotulador','flamaster / mazak'),
('La Educación','Edukacja','la regla','linijka'),
('La Educación','Edukacja','la mochila','plecak'),
('La Educación','Edukacja','la pizarra','tablica'),
('La Educación','Edukacja','la tiza','kreda'),
('La Educación','Edukacja','el borrador','gąbka do tablicy'),
('La Educación','Edukacja','el pupitre','ławka szkolna'),
('La Educación','Edukacja','el escritorio','biurko'),
('La Educación','Edukacja','la biblioteca','biblioteka'),
('La Educación','Edukacja','el gimnasio','sala gimnastyczna'),
('La Educación','Edukacja','el comedor','stołówka'),
('La Educación','Edukacja','el examen','egzamin'),
('La Educación','Edukacja','la prueba','sprawdzian'),
('La Educación','Edukacja','el test','test'),
('La Educación','Edukacja','la nota','ocena'),
('La Educación','Edukacja','el sobresaliente','ocena bardzo dobra / celująca'),
('La Educación','Edukacja','el aprobado','ocena dostateczna / zdany'),
('La Educación','Edukacja','el suspenso','ocena niedostateczna / oblany'),
('La Educación','Edukacja','los deberes','praca domowa'),
('La Educación','Edukacja','la tarea','zadanie (domowe)'),
('La Educación','Edukacja','estudiar','uczyć się (nauka)'),
('La Educación','Edukacja','aprender','uczyć się (przyswajać wiedzę)'),
('La Educación','Edukacja','enseñar','nauczać'),
('La Educación','Edukacja','leer','czytać'),
('La Educación','Edukacja','escribir','pisać'),
('La Educación','Edukacja','preguntar','pytać'),
('La Educación','Edukacja','responder','odpowiadać'),
('La Educación','Edukacja','el conocimiento','wiedza'),
('La Educación','Edukacja','el título','tytuł / dyplom'),
('La Educación','Edukacja','la beca','stypendium'),
('La Salud','Zdrowie','la salud','zdrowie'),
('La Salud','Zdrowie','la enfermedad','choroba'),
('La Salud','Zdrowie','el dolor','ból'),
('La Salud','Zdrowie','el paciente','pacjent'),
('La Salud','Zdrowie','la pastilla / la píldora','tabletka / pigułka'),
('La Salud','Zdrowie','el jarabe','syrop'),
('La Salud','Zdrowie','la inyección','zastrzyk'),
('La Salud','Zdrowie','la receta','recepta'),
('La Salud','Zdrowie','el termómetro','termometr'),
('La Salud','Zdrowie','la fiebre','gorączka'),
('La Salud','Zdrowie','la tos','kaszel'),
('La Salud','Zdrowie','el resfriado','przeziębienie'),
('La Salud','Zdrowie','la gripe','grypa'),
('La Salud','Zdrowie','el síntoma','objaw / symptom'),
('La Salud','Zdrowie','la tirita / la curita','plaster'),
('La Salud','Zdrowie','el vendaje','bandaż / opatrunek'),
('La Salud','Zdrowie','la sangre','krew'),
('La Salud','Zdrowie','sangrar','krwawić'),
('La Salud','Zdrowie','respirar','oddychać'),
('La Salud','Zdrowie','desmayarse','zemdleć'),
('La Salud','Zdrowie','vomitar','wymiotować'),
('La Salud','Zdrowie','mareado','mający mdłości / zawroty głowy'),
('La Salud','Zdrowie','la alergia','alergia'),
('La Salud','Zdrowie','la vacuna','szczepionka'),
('La Salud','Zdrowie','el virus','wirus'),
('La Salud','Zdrowie','la bacteria','bakteria'),
('La Salud','Zdrowie','la infección','infekcja'),
('La Salud','Zdrowie','la cicatriz','blizna'),
('La Salud','Zdrowie','la herida','rana'),
('La Salud','Zdrowie','el pulso','tętno / puls'),
('La Salud','Zdrowie','la presión arterial','ciśnienie krwi'),
('La Salud','Zdrowie','el infarto','zawał'),
('La Salud','Zdrowie','el asma','astma'),
('La Salud','Zdrowie','el cáncer','rak (choroba)'),
('La Salud','Zdrowie','la operación','operacja'),
('La Salud','Zdrowie','el cirujano','chirurg'),
('La Salud','Zdrowie','la sala de emergencias','ostry dyżur / SOR'),
('La Salud','Zdrowie','la camilla','nosze'),
('La Salud','Zdrowie','la silla de ruedas','wózek inwalidzki'),
('La Salud','Zdrowie','la muleta','kula (ortopedyczna)'),
('La Salud','Zdrowie','el yeso / la escayola','gips'),
('La Salud','Zdrowie','romperse','złamać sobie (coś)'),
('La Salud','Zdrowie','curar','leczyć / uzdrawiać'),
('La Salud','Zdrowie','el botiquín','apteczka'),
('La Salud','Zdrowie','la clínica','klinika'),
('La Salud','Zdrowie','sano','zdrowy'),
('La Salud','Zdrowie','enfermo','chory'),
('La Salud','Zdrowie','recuperarse','wracać do zdrowia'),
('La Salud','Zdrowie','el tratamiento','leczenie'),
('La Salud','Zdrowie','el diagnóstico','diagnoza');
