insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Migración','Migracja','el migrante','migrant'),
('Migración','Migracja','el inmigrante','imigrant'),
('Migración','Migracja','el emigrante','emigrant'),
('Migración','Migracja','emigrar','emigrować'),
('Migración','Migracja','inmigrar','imigrować'),
('Migración','Migracja','el refugiado','uchodźca'),
('Migración','Migracja','el asilado','azylant'),
('Migración','Migracja','el solicitante de asilo','osoba ubiegająca się o azyl'),
('Migración','Migracja','el exiliado','wygnaniec'),
('Migración','Migracja','el exilio','wygnanie / emigracja polityczna'),
('Migración','Migracja','la diáspora','diaspora'),
('Migración','Migracja','la frontera','granica'),
('Migración','Migracja','el control fronterizo','kontrola graniczna'),
('Migración','Migracja','el visado','wiza'),
('Migración','Migracja','el pasaporte','paszport'),
('Migración','Migracja','el permiso de residencia','zezwolenie na pobyt'),
('Migración','Migracja','el permiso de trabajo','zezwolenie na pracę'),
('Migración','Migracja','la residencia','pobyt / rezydentura'),
('Migración','Migracja','la deportación','deportacja'),
('Migración','Migracja','deportar','deportować'),
('Migración','Migracja','la expulsión','wydalenie'),
('Migración','Migracja','expulsar','wydalać'),
('Migración','Migracja','la integración','integracja'),
('Migración','Migracja','integrar','integrować'),
('Migración','Migracja','la asimilación','asymilacja'),
('Migración','Migracja','la asimilación cultural','asymilacja kulturowa'),
('Migración','Migracja','la multiculturalidad','multikulturalizm'),
('Migración','Migracja','la xenofobia','ksenofobia'),
('Migración','Migracja','el racismo','rasizm'),
('Migración','Migracja','la discriminación','dyskryminacja'),
('Migración','Migracja','el traficante de personas','przemytnik ludzi'),
('Migración','Migracja','la patera','łódź pontonowa (imigrantów)'),
('Migración','Migracja','el cayuco','łódź rybacka (migrancka)'),
('Migración','Migracja','el naufragio','katastrofa morska'),
('Migración','Migracja','la ruta migratoria','szlak migracyjny'),
('Migración','Migracja','la acogida','przyjęcie / gościnność'),
('Migración','Migracja','acoger','przyjmować'),
('Migración','Migracja','el centro de acogida','ośrodek dla uchodźców'),
('Migración','Migracja','la repatriación','repatriacja'),
('Migración','Migracja','repatriar','repatriować'),
('Migración','Migracja','la crisis migratoria','kryzys migracyjny'),
('Migración','Migracja','la llegada','przybycie'),
('Migración','Migracja','la salida','wyjazd'),
('Migración','Migracja','el flujo migratorio','przepływ migracyjny'),
('Migración','Migracja','la remesa','przekaz pieniężny'),
('Migración','Migracja','la mano de obra','siła robocza'),
('Migración','Migracja','la clandestinidad','nielegalność'),
('Migración','Migracja','clandestino','nielegalny'),
('Migración','Migracja','la barrera','bariera'),
('Educación Infantil','Edukacja wczesnoszkolna','la educación infantil','edukacja przedszkolna'),
('Educación Infantil','Edukacja wczesnoszkolna','la guardería','żłobek'),
('Educación Infantil','Edukacja wczesnoszkolna','el jardín de infancia','przedszkole'),
('Educación Infantil','Edukacja wczesnoszkolna','la escuela infantil','szkoła przedszkolna'),
('Educación Infantil','Edukacja wczesnoszkolna','el parvulario','oddział przedszkolny'),
('Educación Infantil','Edukacja wczesnoszkolna','el niño','dziecko'),
('Educación Infantil','Edukacja wczesnoszkolna','la niña','dziewczynka'),
('Educación Infantil','Edukacja wczesnoszkolna','el infante','niemowlę / małe dziecko'),
('Educación Infantil','Edukacja wczesnoszkolna','el párvulo','przedszkolak'),
('Educación Infantil','Edukacja wczesnoszkolna','el educador','wychowawca'),
('Educación Infantil','Edukacja wczesnoszkolna','la educadora','wychowawczyni'),
('Educación Infantil','Edukacja wczesnoszkolna','el maestro de infantil','nauczyciel przedszkola'),
('Educación Infantil','Edukacja wczesnoszkolna','la maestra','nauczycielka'),
('Educación Infantil','Edukacja wczesnoszkolna','la ludoteca','świetlica / sala zabaw'),
('Educación Infantil','Edukacja wczesnoszkolna','el juego','zabawa'),
('Educación Infantil','Edukacja wczesnoszkolna','jugar','bawić się'),
('Educación Infantil','Edukacja wczesnoszkolna','el juguete','zabawka'),
('Educación Infantil','Edukacja wczesnoszkolna','el dibujo','rysunek'),
('Educación Infantil','Edukacja wczesnoszkolna','pintar','rysować / malować'),
('Educación Infantil','Edukacja wczesnoszkolna','colorear','kolorować'),
('Educación Infantil','Edukacja wczesnoszkolna','la plastelina','plastelina'),
('Educación Infantil','Edukacja wczesnoszkolna','el cuento','bajka'),
('Educación Infantil','Edukacja wczesnoszkolna','contantar un cuento','opowiadać bajkę'),
('Educación Infantil','Edukacja wczesnoszkolna','la canción','piosenka'),
('Educación Infantil','Edukacja wczesnoszkolna','cantar','śpiewać'),
('Educación Infantil','Edukacja wczesnoszkolna','bailar','tańczyć'),
('Educación Infantil','Edukacja wczesnoszkolna','el aprendizaje','nauka'),
('Educación Infantil','Edukacja wczesnoszkolna','aprender','uczyć się'),
('Educación Infantil','Edukacja wczesnoszkolna','la socialización','socjalizacja'),
('Educación Infantil','Edukacja wczesnoszkolna','compartir','dzielić się'),
('Educación Infantil','Edukacja wczesnoszkolna','el compañerismo','koleżeństwo'),
('Educación Infantil','Edukacja wczesnoszkolna','el patio','plac zabaw'),
('Educación Infantil','Edukacja wczesnoszkolna','el tobogán','zjeżdżalnia'),
('Educación Infantil','Edukacja wczesnoszkolna','el columpio','huśtawka'),
('Educación Infantil','Edukacja wczesnoszkolna','el arenero','piaskownica'),
('Educación Infantil','Edukacja wczesnoszkolna','la siesta','drzemka'),
('Educación Infantil','Edukacja wczesnoszkolna','dormir','spać'),
('Educación Infantil','Edukacja wczesnoszkolna','comer','jeść'),
('Educación Infantil','Edukacja wczesnoszkolna','el almuerzo','drugie śniadanie'),
('Educación Infantil','Edukacja wczesnoszkolna','la merienda','podwieczorek'),
('Educación Infantil','Edukacja wczesnoszkolna','el pañal','pielucha'),
('Educación Infantil','Edukacja wczesnoszkolna','el orinal','nocnik'),
('Educación Infantil','Edukacja wczesnoszkolna','el biberón','butelka dla dziecka'),
('Educación Infantil','Edukacja wczesnoszkolna','el desarrollo','rozwój'),
('Educación Infantil','Edukacja wczesnoszkolna','la motricidad','motoryka'),
('Educación Infantil','Edukacja wczesnoszkolna','la creatividad','kreatywność'),
('Educación Infantil','Edukacja wczesnoszkolna','la imaginación','wyobraźnia'),
('Educación Infantil','Edukacja wczesnoszkolna','el abecedario','alfabet'),
('Educación Infantil','Edukacja wczesnoszkolna','los números','liczby'),
('Educación Infantil','Edukacja wczesnoszkolna','los colores','kolory'),
('Educación Secundaria','Edukacja średnia','la educación secundaria','edukacja średnia / gimnazjum i liceum'),
('Educación Secundaria','Edukacja średnia','el instituto','liceum / szkoła średnia'),
('Educación Secundaria','Edukacja średnia','el colegio','szkoła'),
('Educación Secundaria','Edukacja średnia','el alumno / la alumna','uczeń / uczennica'),
('Educación Secundaria','Edukacja średnia','el estudiante','student / uczeń'),
('Educación Secundaria','Edukacja średnia','el profesor / la profesora','nauczyciel / profesor'),
('Educación Secundaria','Edukacja średnia','el docente','nauczyciel / wykładowca'),
('Educación Secundaria','Edukacja średnia','el director','dyrektor szkoły'),
('Educación Secundaria','Edukacja średnia','el tutor','wychowawca / mentor'),
('Educación Secundaria','Edukacja średnia','la clase','klasa / lekcja'),
('Educación Secundaria','Edukacja średnia','el aula','sala lekcyjna'),
('Educación Secundaria','Edukacja średnia','el horario','plan lekcji'),
('Educación Secundaria','Edukacja średnia','la asignatura','przedmiot szkolny'),
('Educación Secundaria','Edukacja średnia','la materia','przedmiot / materia'),
('Educación Secundaria','Edukacja średnia','el examen','egzamin'),
('Educación Secundaria','Edukacja średnia','la prueba','sprawdzian / test'),
('Educación Secundaria','Edukacja średnia','la nota','ocena'),
('Educación Secundaria','Edukacja średnia','la calificación','ocena / kwalifikacja'),
('Educación Secundaria','Edukacja średnia','aprobar','zdać'),
('Educación Secundaria','Edukacja średnia','suspender','zjeść pałę / nie zdać'),
('Educación Secundaria','Edukacja średnia','el boletín de notas','świadectwo / karta ocen'),
('Educación Secundaria','Edukacja średnia','el trimestre','trymestr'),
('Educación Secundaria','Edukacja średnia','el curso escolar','rok szkolny'),
('Educación Secundaria','Edukacja średnia','el recreo','przerwa (międzylekcyjna)'),
('Educación Secundaria','Edukacja średnia','la tarea','zadanie domowe'),
('Educación Secundaria','Edukacja średnia','los deberes','praca domowa'),
('Educación Secundaria','Edukacja średnia','el cuaderno','zeszyt'),
('Educación Secundaria','Edukacja średnia','el libro de texto','podręcznik'),
('Educación Secundaria','Edukacja średnia','el bolígrafo','długopis'),
('Educación Secundaria','Edukacja średnia','el lápiz','ołówek'),
('Educación Secundaria','Edukacja średnia','la goma','gumka do ścierania'),
('Educación Secundaria','Edukacja średnia','la regla','linijka'),
('Educación Secundaria','Edukacja średnia','la mochila','plecak'),
('Educación Secundaria','Edukacja średnia','el estuche','piórnik'),
('Educación Secundaria','Edukacja średnia','la pizarra','tablica'),
('Educación Secundaria','Edukacja średnia','la tiza','kreda'),
('Educación Secundaria','Edukacja średnia','el marcador','marker'),
('Educación Secundaria','Edukacja średnia','el borrador','gąbka do tablicy'),
('Educación Secundaria','Edukacja średnia','el instituto de educación secundaria (IES)','liceum ogólnokształcące'),
('Educación Secundaria','Edukacja średnia','la selectividad / la EBAU','matura (egzamin wstępny na studia)'),
('Educación Secundaria','Edukacja średnia','el bachillerato','liceum (ostatnie lata) / matura'),
('Educación Secundaria','Edukacja średnia','la formación profesional (FP)','szkolenie zawodowe'),
('Educación Secundaria','Edukacja średnia','el título','dyplom / tytuł'),
('Educación Secundaria','Edukacja średnia','el graduado','absolwent'),
('Educación Secundaria','Edukacja średnia','la graduación','ukończenie szkoły / ceremonia absolwencka'),
('Educación Secundaria','Edukacja średnia','el acoso escolar','nękanie / przemoc szkolna'),
('Educación Secundaria','Edukacja średnia','el compañero de clase','kolega z klasy'),
('Educación Secundaria','Edukacja średnia','el delegado de clase','gospodarz klasy'),
('Educación Secundaria','Edukacja średnia','la excursión','wycieczka szkolna'),
('Educación Secundaria','Edukacja średnia','la biblioteca','biblioteka szkolna'),
('Universidad','Uniwersytet','la universidad','uniwersytet'),
('Universidad','Uniwersytet','el campus','kampus uniwersytecki'),
('Universidad','Uniwersytet','el rector','rektor'),
('Universidad','Uniwersytet','el decano','dziekan'),
('Universidad','Uniwersytet','el profesor / la profesora','profesor / wykładowca'),
('Universidad','Uniwersytet','el catedrático','profesor zwyczajny / kierownik katedry'),
('Universidad','Uniwersytet','el investigador','badacza / naukowiec'),
('Universidad','Uniwersytet','el estudiante / el universitario','student'),
('Universidad','Uniwersytet','el alumno','student / uczeń'),
('Universidad','Uniwersytet','la carrera','kierunek studiów'),
('Universidad','Uniwersytet','la licenciatura','licencjat'),
('Universidad','Uniwersytet','el grado','studia licencjackie / stopień'),
('Universidad','Uniwersytet','el máster','studia magisterskie / magister'),
('Universidad','Uniwersytet','el doctorado','doktorat'),
('Universidad','Uniwersytet','el doctor','doktor'),
('Universidad','Uniwersytet','la tesis','praca dyplomowa / rozprawa'),
('Universidad','Uniwersytet','la tesis doctoral','rozprawa doktorska'),
('Universidad','Uniwersytet','la facultad','wydział'),
('Universidad','Uniwersytet','el departamento','katedra / wydział'),
('Universidad','Uniwersytet','el seminarium','seminarium'),
('Universidad','Uniwersytet','la clase magistral','wykład'),
('Universidad','Uniwersytet','el auditorio','aula wykładowa'),
('Universidad','Uniwersytet','el crédito','punkt ECTS / kredyt'),
('Universidad','Uniwersytet','la matrícula','wpis na studia / czesne'),
('Universidad','Uniwersytet','matricularse','zapisać się na studia'),
('Universidad','Uniwersytet','la beca','stypendium'),
('Universidad','Uniwersytet','el becario','stypendysta / stażysta'),
('Universidad','Uniwersytet','la residencia de estudiantes','akademik / dom studencki'),
('Universidad','Uniwersytet','el rectorado','rektorat'),
('Universidad','Uniwersytet','el decanato','dziekanat'),
('Universidad','Uniwersytet','la secretaría','sekretariat uczelni'),
('Universidad','Uniwersytet','el expediente académico','indeks / przebieg studiów'),
('Universidad','Uniwersytet','el examen final','egzamin końcowy'),
('Universidad','Uniwersytet','la convocatoria','termin egzaminu'),
('Universidad','Uniwersytet','suspender','oblać egzamin'),
('Universidad','Uniwersytet','aprobar','zdać'),
('Universidad','Uniwersytet','el título universitario','dyplom uniwersytecki'),
('Universidad','Uniwersytet','el graduado','absolwent'),
('Universidad','Uniwersytet','la ceremonia de graduación','ceremonia rozdania dyplomów'),
('Universidad','Uniwersytet','el intercambio','wymiana studencka (np. Erasmus)'),
('Universidad','Uniwersytet','la investigación','badania naukowe'),
('Universidad','Uniwersytet','publicar','publikować'),
('Universidad','Uniwersytet','el artículo científico','artykuł naukowy'),
('Universidad','Uniwersytet','la conferencia','konferencja'),
('Universidad','Uniwersytet','el laboratorio','laboratorium'),
('Universidad','Uniwersytet','la biblioteca universitaria','biblioteka uniwersytecka'),
('Universidad','Uniwersytet','el rector','rektor'),
('Universidad','Uniwersytet','el campus virtual','wirtualny kampus'),
('Universidad','Uniwersytet','la asignatura optativa','przedmiot do wyboru'),
('Universidad','Uniwersytet','la asignatura obligatoria','przedmiot obowiązkowy'),
('Asignaturas Escolares','Przedmioty szkolne','la asignatura','przedmiot szkolny');
