insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Telefonía Móvil','Telefonia komórkowa','el teléfono móvil / el celular','telefon komórkowy / smartfon'),
('Telefonía Móvil','Telefonia komórkowa','la llamada','połączenie telefoniczne'),
('Telefonía Móvil','Telefonia komórkowa','llamar','dzwonić'),
('Telefonía Móvil','Telefonia komórkowa','contestar','odbierać (telefon)'),
('Telefonía Móvil','Telefonia komórkowa','colgar','rozłączać się'),
('Telefonía Móvil','Telefonia komórkowa','el tono de llamada','dźwięk dzwonka'),
('Telefonía Móvil','Telefonia komórkowa','el buzón de voz','poczta głosowa'),
('Telefonía Móvil','Telefonia komórkowa','el mensaje de texto / el SMS','wiadomość tekstowa / SMS'),
('Telefonía Móvil','Telefonia komórkowa','el mensaje de voz','wiadomość głosowa'),
('Telefonía Móvil','Telefonia komórkowa','la pantalla táctil','ekran dotykowy'),
('Telefonía Móvil','Telefonia komórkowa','la batería','bateria'),
('Telefonía Móvil','Telefonia komórkowa','el cargador','ładowarka'),
('Telefonía Móvil','Telefonia komórkowa','cargar el móvil','ładować telefon'),
('Telefonía Móvil','Telefonia komórkowa','la tarjeta SIM','karta SIM'),
('Telefonía Móvil','Telefonia komórkowa','la cobertura','zasięg'),
('Telefonía Móvil','Telefonia komórkowa','sin cobertura','brak zasięgu'),
('Telefonía Móvil','Telefonia komórkowa','la red móvil','sieć komórkowa'),
('Telefonía Móvil','Telefonia komórkowa','los datos móviles','dane komórkowe'),
('Telefonía Móvil','Telefonia komórkowa','el roaming','roaming'),
('Telefonía Móvil','Telefonia komórkowa','la aplicación / la app','aplikacja'),
('Telefonía Móvil','Telefonia komórkowa','descargar una aplicación','pobrać aplikację'),
('Telefonía Móvil','Telefonia komórkowa','la cámara','aparat (w telefonie)'),
('Telefonía Móvil','Telefonia komórkowa','la cámara frontal','przedni aparat / kamera do selfie'),
('Telefonía Móvil','Telefonia komórkowa','el flash','flesz'),
('Telefonía Móvil','Telefonia komórkowa','la agenda','książka adresowa / kontakty'),
('Telefonía Móvil','Telefonia komórkowa','la videollamada','rozmowa wideo'),
('Telefonía Móvil','Telefonia komórkowa','el chat','czat'),
('Telefonía Móvil','Telefonia komórkowa','la notificación','powiadomienie'),
('Telefonía Móvil','Telefonia komórkowa','el ajuste','ustawienia'),
('Telefonía Móvil','Telefonia komórkowa','el modo avión','tryb samolotowy'),
('Telefonía Móvil','Telefonia komórkowa','el tono de aviso','dźwięk powiadomienia'),
('Telefonía Móvil','Telefonia komórkowa','la funda','etui / pokrowczyk'),
('Telefonía Móvil','Telefonia komórkowa','el protector de pantalla','szkło / folia ochronna na ekran'),
('Telefonía Móvil','Telefonia komórkowa','el manos libres','zestaw głośnomówiący'),
('Telefonía Móvil','Telefonia komórkowa','el auricular','słuchawka'),
('Telefonía Móvil','Telefonia komórkowa','el bluetooth','Bluetooth'),
('Telefonía Móvil','Telefonia komórkowa','el GPS','GPS / nawigacja'),
('Telefonía Móvil','Telefonia komórkowa','la huella dactilar','czytnik linii papilarnych'),
('Telefonía Móvil','Telefonia komórkowa','el reconocimiento facial','rozpoznawanie twarzy'),
('Telefonía Móvil','Telefonia komórkowa','reiniciar','uruchomić ponownie'),
('Telefonía Móvil','Telefonia komórkowa','apagar','wyłączyć'),
('Telefonía Móvil','Telefonia komórkowa','encender','włączyć'),
('Telefonía Móvil','Telefonia komórkowa','bloquear','zablokować'),
('Telefonía Móvil','Telefonia komórkowa','desbloquear','odblokować'),
('Telefonía Móvil','Telefonia komórkowa','la factura de teléfono','rachunek za telefon'),
('Telefonía Móvil','Telefonia komórkowa','la recarga','doładowanie (konta)'),
('Telefonía Móvil','Telefonia komórkowa','el operador de telefonía','operator telefoniczny'),
('Telefonía Móvil','Telefonia komórkowa','la tarifa plana','stawka ryczałtowa / bez limitu'),
('Telefonía Móvil','Telefonia komórkowa','el smartphone','smartfon'),
('Telefonía Móvil','Telefonia komórkowa','la memoria interna','pamięć wewnętrzna'),
('Videojuegos','Gry wideo','el videojuego','gra wideo'),
('Videojuegos','Gry wideo','la consola','konsola do gier'),
('Videojuegos','Gry wideo','el jugador','gracz'),
('Videojuegos','Gry wideo','el mando / el controlador','pad / kontroler'),
('Videojuegos','Gry wideo','la partida','rozgrywka / partida'),
('Videojuegos','Gry wideo','la pantalla','ekran'),
('Videojuegos','Gry wideo','el nivel','poziom'),
('Videojuegos','Gry wideo','la fase','fase / etap'),
('Videojuegos','Gry wideo','el jefe','boss (szef w grze)'),
('Videojuegos','Gry wideo','la puntuación','wynik / punktacja'),
('Videojuegos','Gry wideo','la vida','życie (w grze)'),
('Videojuegos','Gry wideo','el punto de control','punkt kontrolny (checkpoint)'),
('Videojuegos','Gry wideo','el inventario','ekwipunek / inwentarz'),
('Videojuegos','Gry wideo','la misión','misja / zadanie'),
('Videojuegos','Gry wideo','la aventura','przygoda'),
('Videojuegos','Gry wideo','el juego de rol (RPG)','gra RPG'),
('Videojuegos','Gry wideo','el simulador','symulator'),
('Videojuegos','Gry wideo','la estrategia','strategia'),
('Videojuegos','Gry wideo','el modo multijugador','tryb wieloosobowy (multiplayer)'),
('Videojuegos','Gry wideo','el modo individual','tryb dla jednego gracza (singleplayer)'),
('Videojuegos','Gry wideo','la realidad virtual','rzeczywistość wirtualna (VR)'),
('Videojuegos','Gry wideo','el gráfico','grafika'),
('Videojuegos','Gry wideo','la animación','animacja'),
('Videojuegos','Gry wideo','la jugabilidad','rozgrywka (gameplay)'),
('Videojuegos','Gry wideo','jugar','grać'),
('Videojuegos','Gry wideo','ganar','wygrać'),
('Videojuegos','Gry wideo','perder','przegrać'),
('Videojuegos','Gry wideo','morir','zginąć (w grze)'),
('Videojuegos','Gry wideo','revivir','ożywić / odrodzić się'),
('Videojuegos','Gry wideo','la plataforma','platforma do gier'),
('Videojuegos','Gry wideo','el juego en línea','gra online'),
('Videojuegos','Gry wideo','el servidor','serwer'),
('Videojuegos','Gry wideo','el retraso (lag)','opóźnienie (lag)'),
('Videojuegos','Gry wideo','el truco','kod / sztuczka (cheat)'),
('Videojuegos','Gry wideo','la beta','wersja beta'),
('Videojuegos','Gry wideo','el parche','łatka / aktualizacja (patch)'),
('Videojuegos','Gry wideo','la expansión','dodatek do gry (expansion)'),
('Videojuegos','Gry wideo','el estudio de desarrollo','studio deweloperskie'),
('Videojuegos','Gry wideo','el desarrollador','programista / deweloper'),
('Videojuegos','Gry wideo','el lanzamiento','premiera'),
('Videojuegos','Gry wideo','la banda sonora','ścieżka dźwiękowa'),
('Videojuegos','Gry wideo','la historia','fabuła / historia'),
('Videojuegos','Gry wideo','el personaje','postać'),
('Videojuegos','Gry wideo','el avatar','awatar'),
('Videojuegos','Gry wideo','el streaming','streaming'),
('Videojuegos','Gry wideo','el streamer','streamer'),
('Videojuegos','Gry wideo','la transmisión','transmisja'),
('Videojuegos','Gry wideo','la comunidad','społeczność'),
('Videojuegos','Gry wideo','la tabla de clasificación','tabela wyników (leaderboard)'),
('Videojuegos','Gry wideo','la edición coleccionista','edycja kolekcjonerska'),
('Física','Fizyka','la física','fizyka'),
('Física','Fizyka','la materia','materia'),
('Física','Fizyka','la energía','energia'),
('Física','Fizyka','la fuerza','siła'),
('Física','Fizyka','la masa','masa'),
('Física','Fizyka','el peso','ciężar'),
('Física','Fizyka','la velocidad','prędkość'),
('Física','Fizyka','la aceleración','przyspieszenie'),
('Física','Fizyka','la gravedad','grawitacja'),
('Física','Fizyka','el movimiento','ruch'),
('Física','Fizyka','el reposo','spoczynek'),
('Física','Fizyka','la inercia','bezwładność'),
('Física','Fizyka','la ley','prawo (fizyczne)'),
('Física','Fizyka','la teoría','teoria'),
('Física','Fizyka','el átomo','atom'),
('Física','Fizyka','la molécula','cząsteczka'),
('Física','Fizyka','el electrón','elektron'),
('Física','Fizyka','el protón','proton'),
('Física','Fizyka','el neutrón','neutron'),
('Física','Fizyka','la carga eléctrica','ładunek elektryczny'),
('Física','Fizyka','la electricidad','elektryczność'),
('Física','Fizyka','el magnetismo','magnetyzm'),
('Física','Fizyka','la onda','fala'),
('Física','Fizyka','la frecuencia','częstotliwość'),
('Física','Fizyka','la longitud de onda','długość fali'),
('Física','Fizyka','la luz','światło'),
('Física','Fizyka','el sonido','dźwięk'),
('Física','Fizyka','el calor','ciepło / temperatura'),
('Física','Fizyka','la termodinámica','termodynamika'),
('Física','Fizyka','la presión','ciśnienie'),
('Física','Fizyka','el volumen','objętość'),
('Física','Fizyka','la densidad','gęstość'),
('Física','Fizyka','el trabajo','praca (fizyczna)'),
('Física','Fizyka','la potencia','moc'),
('Física','Fizyka','la óptica','optyka'),
('Física','Fizyka','la mecánica','mechanika'),
('Física','Fizyka','la cuántica','fizyka kwantowa'),
('Física','Fizyka','la relatividad','względność'),
('Física','Fizyka','el espacio','przestrzeń'),
('Física','Fizyka','el tiempo','czas'),
('Física','Fizyka','el vacío','próżnia'),
('Física','Fizyka','el experimento','eksperyment'),
('Física','Fizyka','la hipótesis','hipoteza'),
('Física','Fizyka','medir','mierzyć'),
('Física','Fizyka','la unidad','jednostka'),
('Física','Fizyka','el metro','metr'),
('Física','Fizyka','el kilogramo','kilogram'),
('Física','Fizyka','el segundo','sekunda'),
('Física','Fizyka','el newton','niuton'),
('Física','Fizyka','el julio','dżul'),
('Química','Chemia','la química','chemia'),
('Química','Chemia','la sustancia','substancja'),
('Química','Chemia','el elemento','pierwiastek'),
('Química','Chemia','el compuesto','związek chemiczny'),
('Química','Chemia','la tabla periódica','układ okresowy pierwiastków'),
('Química','Chemia','el átomo','atom'),
('Química','Chemia','la molécula','cząsteczka'),
('Química','Chemia','el electrón','elektron'),
('Química','Chemia','el núcleo','jądro atomowe'),
('Química','Chemia','la reacción química','reakcja chemiczna'),
('Química','Chemia','la fórmula','wzór chemiczny'),
('Química','Chemia','el enlace','wiązanie chemiczne'),
('Química','Chemia','el ácido','kwas'),
('Química','Chemia','la base','zasada'),
('Química','Chemia','el pH','pH'),
('Química','Chemia','la solución / la disolución','roztwór'),
('Química','Chemia','el disolvente','rozpuszczalnik'),
('Química','Chemia','el soluto','substancja rozpuszczona'),
('Química','Chemia','la concentración','stężenie'),
('Química','Chemia','el estado de la materia','stan skupienia'),
('Química','Chemia','el estado sólido','stan stały'),
('Química','Chemia','el estado líquido','stan ciekły'),
('Química','Chemia','el estado gaseoso','stan gazowy'),
('Química','Chemia','el gas','gaz'),
('Química','Chemia','el líquido','ciecz'),
('Química','Chemia','el sólido','ciało stałe'),
('Química','Chemia','fundir','topić / stapiać'),
('Química','Chemia','congelar','zamrażać'),
('Química','Chemia','evaporar','odparowywać'),
('Química','Chemia','condensar','skraplać'),
('Química','Chemia','sublimar','sublimować'),
('Química','Chemia','la combustión','spalanie'),
('Química','Chemia','la oxidación','utlenianie'),
('Química','Chemia','la reducción','redukcja'),
('Química','Chemia','el laboratorio','laboratorium'),
('Química','Chemia','el tubo de ensayo','probówka'),
('Química','Chemia','el matraz','kolba laboratoryjna'),
('Química','Chemia','el vaso de precipitados','zlewek laboratoryjny'),
('Química','Chemia','la pipeta','pipeta'),
('Química','Chemia','la balanza','waga laboratoryjna'),
('Química','Chemia','el mechero Bunsen','palnik Bunsen'),
('Química','Chemia','tóxico','toksyczny'),
('Química','Chemia','inflamable','łatwopalny'),
('Química','Chemia','corrosivo','żrący'),
('Química','Chemia','el peligro','niebezpieczeństwo'),
('Química','Chemia','la seguridad','bezpieczeństwo'),
('Química','Chemia','el catalizador','katalizator'),
('Química','Chemia','la orgánica','chemia organiczna'),
('Química','Chemia','la inorgánica','chemia nieorganiczna'),
('Química','Chemia','la bioquímica','biochemia');
