insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Animales Salvajes','Zwierzęta dzikie','el animal salvaje','dzikie zwierzę'),
('Animales Salvajes','Zwierzęta dzikie','el león','lew'),
('Animales Salvajes','Zwierzęta dzikie','el tigre','tygrys'),
('Animales Salvajes','Zwierzęta dzikie','el leopardo','leopard'),
('Animales Salvajes','Zwierzęta dzikie','el guepardo','gepard'),
('Animales Salvajes','Zwierzęta dzikie','el elefante','słoń'),
('Animales Salvajes','Zwierzęta dzikie','el rinoceronte','nosorożec'),
('Animales Salvajes','Zwierzęta dzikie','el hipopótamo','hipopotam'),
('Animales Salvajes','Zwierzęta dzikie','la jirafa','żyrafa'),
('Animales Salvajes','Zwierzęta dzikie','la cebra','zebra'),
('Animales Salvajes','Zwierzęta dzikie','el mono','małpa'),
('Animales Salvajes','Zwierzęta dzikie','el gorila','goryl'),
('Animales Salvajes','Zwierzęta dzikie','el chimpancé','szympans'),
('Animales Salvajes','Zwierzęta dzikie','el oso','niedźwiedź'),
('Animales Salvajes','Zwierzęta dzikie','el oso polar','niedźwiedź polarny'),
('Animales Salvajes','Zwierzęta dzikie','el oso panda','panda'),
('Animales Salvajes','Zwierzęta dzikie','el lobo','wilk'),
('Animales Salvajes','Zwierzęta dzikie','el zorro','lis'),
('Animales Salvajes','Zwierzęta dzikie','el ciervo','jeleń'),
('Animales Salvajes','Zwierzęta dzikie','el alce','łoś'),
('Animales Salvajes','Zwierzęta dzikie','el jabalí','dzik'),
('Animales Salvajes','Zwierzęta dzikie','el canguro','kangur'),
('Animales Salvajes','Zwierzęta dzikie','el koala','koala'),
('Animales Salvajes','Zwierzęta dzikie','el camello','wielbłąd'),
('Animales Salvajes','Zwierzęta dzikie','el dromedario','dromader'),
('Animales Salvajes','Zwierzęta dzikie','el cocodrilo','krokodyl'),
('Animales Salvajes','Zwierzęta dzikie','el caimán','kajman'),
('Animales Salvajes','Zwierzęta dzikie','la serpiente','wąż'),
('Animales Salvajes','Zwierzęta dzikie','la cobra','kobra'),
('Animales Salvajes','Zwierzęta dzikie','la pitón','pyton'),
('Animales Salvajes','Zwierzęta dzikie','la rana','żaba'),
('Animales Salvajes','Zwierzęta dzikie','el sapo','ropucha'),
('Animales Salvajes','Zwierzęta dzikie','el murciélago','nietoperz'),
('Animales Salvajes','Zwierzęta dzikie','la ardilla','wiewiórka'),
('Animales Salvajes','Zwierzęta dzikie','el castor','bóbr'),
('Animales Salvajes','Zwierzęta dzikie','el águila','orzeł'),
('Animales Salvajes','Zwierzęta dzikie','el halcón','sokół'),
('Animales Salvajes','Zwierzęta dzikie','el buitre','sęp'),
('Animales Salvajes','Zwierzęta dzikie','el avestruz','struś'),
('Animales Salvajes','Zwierzęta dzikie','el pingüino','pingwin'),
('Animales Salvajes','Zwierzęta dzikie','la selva','dżungla / puszcza'),
('Animales Salvajes','Zwierzęta dzikie','el bosque','las'),
('Animales Salvajes','Zwierzęta dzikie','la sabana','sawanna'),
('Animales Salvajes','Zwierzęta dzikie','el zoológico / el zoo','zoo'),
('Animales Salvajes','Zwierzęta dzikie','cazar','polować'),
('Animales Salvajes','Zwierzęta dzikie','el cazador','myśliwy'),
('Animales Salvajes','Zwierzęta dzikie','la presa','ofiara / zdobycz'),
('Animales Salvajes','Zwierzęta dzikie','el depredador','drapieżnik'),
('Animales Salvajes','Zwierzęta dzikie','en peligro de extinción','zagrożony wyginięciem'),
('Animales Salvajes','Zwierzęta dzikie','el hábitat','siedlisko / środowisko naturalne'),
('Aves','Ptaki','el ave / el pájaro','ptak'),
('Aves','Ptaki','el águila','orzeł'),
('Aves','Ptaki','el halcón','sokół'),
('Aves','Ptaki','el búho','sowa / puchacz'),
('Aves','Ptaki','la lechuza','sowa płomykówka'),
('Aves','Ptaki','el cuervo','kruk / wrona'),
('Aves','Ptaki','la paloma','gołąb'),
('Aves','Ptaki','el cisne','łabędź'),
('Aves','Ptaki','el pato','kaczka'),
('Aves','Ptaki','el ganso','gęś'),
('Aves','Ptaki','el pingüino','pingwin'),
('Aves','Ptaki','el avestruz','struś'),
('Aves','Ptaki','el loro','papuga'),
('Aves','Ptaki','la cotorra','papużka'),
('Aves','Ptaki','el canario','kanarek'),
('Aves','Ptaki','el jilguero','szczygieł'),
('Aves','Ptaki','el ruiseñor','słowik'),
('Aves','Ptaki','el gorrión','wróbel'),
('Aves','Ptaki','la golondrina','jaskółka'),
('Aves','Ptaki','la cigüeña','bocian'),
('Aves','Ptaki','el flamenco','flaming'),
('Aves','Ptaki','el pelícano','pelikan'),
('Aves','Ptaki','la gaviota','mewa'),
('Aves','Ptaki','el albatros','albatros'),
('Aves','Ptaki','el pavo real','paw'),
('Aves','Ptaki','el pavo','indyk'),
('Aves','Ptaki','la gallina','kura'),
('Aves','Ptaki','el gallo','kogut'),
('Aves','Ptaki','el pollito','kurczak / pisklę'),
('Aves','Ptaki','el colibrí','koliber'),
('Aves','Ptaki','el tucán','tukan'),
('Aves','Ptaki','el pájaro carpintero','dzięcioł'),
('Aves','Ptaki','el Martín pescador','zimorodek'),
('Aves','Ptaki','el nido','gniazdo'),
('Aves','Ptaki','la pluma','pióro'),
('Aves','Ptaki','el pico','dziób'),
('Aves','Ptaki','el ala','skrzydło'),
('Aves','Ptaki','volar','latać'),
('Aves','Ptaki','piar','ćwierkać / piszczeć'),
('Aves','Ptaki','el canto','śpiew'),
('Aves','Ptaki','cantar','śpiewać'),
('Aves','Ptaki','poner un huevo','znieść jajko'),
('Aves','Ptaki','el huevo','jajko'),
('Aves','Ptaki','la cáscara','skorupka'),
('Aves','Ptaki','el polluelo','pisklę'),
('Aves','Ptaki','la bandada','stado (ptaków)'),
('Aves','Ptaki','emigrar','emigrować / odlatywać'),
('Aves','Ptaki','la jaula','klatka'),
('Aves','Ptaki','el comedero','karmnik'),
('Aves','Ptaki','el plumaje','upierzenie'),
('Insectos','Owady','el insecto','owad'),
('Insectos','Owady','el bicho','robal / żyjątko'),
('Insectos','Owady','la mosca','mucha'),
('Insectos','Owady','el mosquito','komar'),
('Insectos','Owady','la abeja','pszczoła'),
('Insectos','Owady','la avispa','osa'),
('Insectos','Owady','la hormiga','mrówka'),
('Insectos','Owady','la araña','pająk'),
('Insectos','Owady','la mariposa','motyl'),
('Insectos','Owady','la polilla','ćma / mól'),
('Insectos','Owady','el escarabajo','chrząszcz / żuk'),
('Insectos','Owady','la mariquita','biedronka'),
('Insectos','Owady','el saltamontes','konik polny'),
('Insectos','Owady','el grillo','świerszcz'),
('Insectos','Owady','la cucaracha','karaluch'),
('Insectos','Owady','el ciempiés','stonoga'),
('Insectos','Owady','el gusano','robak / dżdżownica'),
('Insectos','Owady','la oruga','gąsienica'),
('Insectos','Owady','la libélula','ważka'),
('Insectos','Owady','la mantis religiosa','modliszka'),
('Insectos','Owady','la pulga','pchła'),
('Insectos','Owady','la garrapata','kleszcz'),
('Insectos','Owady','el piojo','wesz'),
('Insectos','Owady','la chinche','pluskwa'),
('Insectos','Owady','el escorpión / el alacrán','skorpion'),
('Insectos','Owady','el caracol','ślimak'),
('Insectos','Owady','la babosa','śliźniak'),
('Insectos','Owady','la tela de araña','pajęczyna'),
('Insectos','Owady','picar','żądlić / gryźć (o owadzie)'),
('Insectos','Owady','la picadura','ukąszenie / użądlenie'),
('Insectos','Owady','zumbar','bzyczeć'),
('Insectos','Owady','el zumbido','bzyczenie'),
('Insectos','Owady','el enjambre','rój'),
('Insectos','Owady','la colmena','ul'),
('Insectos','Owady','la miel','miód'),
('Insectos','Owady','el polen','pyłek'),
('Insectos','Owady','polinizar','zapylać'),
('Insectos','Owady','la antena','czułek'),
('Insectos','Owady','arrastrarse','pełzać'),
('Insectos','Owady','la larva','larwa'),
('Insectos','Owady','el capullo','kokon'),
('Insectos','Owady','venenoso','jadowity / trujący'),
('Insectos','Owady','la plaga','plaga / szkodniki'),
('Insectos','Owady','el repelente','środek odstraszający (repelent)'),
('Insectos','Owady','el insecticida','środek owadobójczy'),
('Insectos','Owady','aplastar','rozgnieść'),
('Insectos','Owady','molesto','irytujący / uciążliwy'),
('Insectos','Owady','el aguijón','żądło'),
('Insectos','Owady','el hormiguero','mrowisko'),
('Insectos','Owady','inofensivo','nieszkodliwy'),
('Animales Marinos','Zwierzęta morskie','el animal marino','zwierzę morskie'),
('Animales Marinos','Zwierzęta morskie','el pez','ryba (żywa)'),
('Animales Marinos','Zwierzęta morskie','el tiburón','rekin'),
('Animales Marinos','Zwierzęta morskie','la ballena','wieloryb'),
('Animales Marinos','Zwierzęta morskie','el delfín','delfin'),
('Animales Marinos','Zwierzęta morskie','la orca','orka'),
('Animales Marinos','Zwierzęta morskie','el pulpo','ośmiornica'),
('Animales Marinos','Zwierzęta morskie','el calamar','kałamarnica'),
('Animales Marinos','Zwierzęta morskie','la medusa','meduza'),
('Animales Marinos','Zwierzęta morskie','la estrella de mar','rozgwiazda'),
('Animales Marinos','Zwierzęta morskie','el caballito de mar','konik morski'),
('Animales Marinos','Zwierzęta morskie','la tortuga marina','żółw morski'),
('Animales Marinos','Zwierzęta morskie','el cangrejo','krab'),
('Animales Marinos','Zwierzęta morskie','la langosta','homar / langusta'),
('Animales Marinos','Zwierzęta morskie','la gamba','krewetka (mała)'),
('Animales Marinos','Zwierzęta morskie','el langostino','krewetka (duża)'),
('Animales Marinos','Zwierzęta morskie','la ostra','ostryga'),
('Animales Marinos','Zwierzęta morskie','el mejillón','omułek'),
('Animales Marinos','Zwierzęta morskie','la almeja','małż'),
('Animales Marinos','Zwierzęta morskie','el caracol de mar','ślimak morski'),
('Animales Marinos','Zwierzęta morskie','la foca','foka'),
('Animales Marinos','Zwierzęta morskie','la morsa','mors'),
('Animales Marinos','Zwierzęta morskie','el león marino','lew morski'),
('Animales Marinos','Zwierzęta morskie','el manatí','manat'),
('Animales Marinos','Zwierzęta morskie','la raya','płaszczka'),
('Animales Marinos','Zwierzęta morskie','el pez espada','miecznik'),
('Animales Marinos','Zwierzęta morskie','el pez payaso','błazenek (rybka)'),
('Animales Marinos','Zwierzęta morskie','el coral','koral'),
('Animales Marinos','Zwierzęta morskie','el arrecife','rafa (koralowa)'),
('Animales Marinos','Zwierzęta morskie','la concha','muszla'),
('Animales Marinos','Zwierzęta morskie','la aleta','płetwa'),
('Animales Marinos','Zwierzęta morskie','las agallas','skrzela'),
('Animales Marinos','Zwierzęta morskie','la escama','łuska'),
('Animales Marinos','Zwierzęta morskie','la cola','ogon'),
('Animales Marinos','Zwierzęta morskie','el océano','ocean'),
('Animales Marinos','Zwierzęta morskie','el mar','morze'),
('Animales Marinos','Zwierzęta morskie','nadar','pływać'),
('Animales Marinos','Zwierzęta morskie','bucear','nurkować'),
('Animales Marinos','Zwierzęta morskie','sumergirse','zanurzać się'),
('Animales Marinos','Zwierzęta morskie','el acuario','akwarium (budynek / zbiornik)'),
('Animales Marinos','Zwierzęta morskie','el plancton','plankton'),
('Animales Marinos','Zwierzęta morskie','el alga','glon / alga'),
('Animales Marinos','Zwierzęta morskie','salado','słony'),
('Animales Marinos','Zwierzęta morskie','la profundidad','głębia / głębokość'),
('Animales Marinos','Zwierzęta morskie','la marea','pływ (przypływ/odpływ)'),
('Animales Marinos','Zwierzęta morskie','la ola','fala'),
('Animales Marinos','Zwierzęta morskie','la costa','wybrzeże'),
('Animales Marinos','Zwierzęta morskie','el tentáculo','macka'),
('Animales Marinos','Zwierzęta morskie','el caparazón','pancerz / skorupa'),
('Animales Marinos','Zwierzęta morskie','la anémona','ukwiał');
