insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('El Matrimonio','Małżeństwo','el matrimonio','małżeństwo'),
('El Matrimonio','Małżeństwo','la boda','ślub / wesele'),
('El Matrimonio','Małżeństwo','casarse','brać ślub'),
('El Matrimonio','Małżeństwo','el marido','mąż'),
('El Matrimonio','Małżeństwo','la mujer','żona / kobieta'),
('El Matrimonio','Małżeństwo','el esposo','małżonek'),
('El Matrimonio','Małżeństwo','la esposa','małżonka'),
('El Matrimonio','Małżeństwo','el novio','pan młody / chłopak (sympatia)'),
('El Matrimonio','Małżeństwo','la novia','panna młoda / dziewczyna (sympatia)'),
('El Matrimonio','Małżeństwo','los novios','para młoda / narzeczeni'),
('El Matrimonio','Małżeństwo','el anillo','pierścionek'),
('El Matrimonio','Małżeństwo','la alianza','obrączka'),
('El Matrimonio','Małżeństwo','el vestido de novia','suknia ślubna'),
('El Matrimonio','Małżeństwo','el ramo','bukiet'),
('El Matrimonio','Małżeństwo','el velo','welon'),
('El Matrimonio','Małżeństwo','el traje','garnitur'),
('El Matrimonio','Małżeństwo','la iglesia','kościół'),
('El Matrimonio','Małżeństwo','el juzgado','urząd stanu cywilnego / sąd'),
('El Matrimonio','Małżeństwo','el cura','ksiądz'),
('El Matrimonio','Małżeństwo','el juez','sędzia'),
('El Matrimonio','Małżeństwo','el testigo','świadek'),
('El Matrimonio','Małżeństwo','el padrino','świadek / ojciec chrzestny'),
('El Matrimonio','Małżeństwo','la madrina','świadkowa / matka chrzestna'),
('El Matrimonio','Małżeństwo','la invitación','zaproszenie'),
('El Matrimonio','Małżeństwo','el invitado','gość'),
('El Matrimonio','Małżeństwo','el banquete','bankiet / przyjęcie'),
('El Matrimonio','Małżeństwo','el brindis','toast'),
('El Matrimonio','Małżeństwo','la tarta nupcial','tort weselny'),
('El Matrimonio','Małżeństwo','la luna de miel','podróż poślubna / miodowy miesiąc'),
('El Matrimonio','Małżeństwo','el viaje de novios','podróż poślubna'),
('El Matrimonio','Małżeństwo','enamorarse','zakochać się'),
('El Matrimonio','Małżeństwo','el amor','miłość'),
('El Matrimonio','Małżeństwo','querer','kochać / chcieć'),
('El Matrimonio','Małżeństwo','amar','kochać (głęboko)'),
('El Matrimonio','Małżeństwo','la pareja','para / partner'),
('El Matrimonio','Małżeństwo','el compromiso','zaręczyny / zobowiązanie'),
('El Matrimonio','Małżeństwo','prometerse','zaręczyć się'),
('El Matrimonio','Małżeństwo','el aniversario','rocznica'),
('El Matrimonio','Małżeństwo','las bodas de plata','srebrne gody (25 lat)'),
('El Matrimonio','Małżeństwo','las bodas de oro','złote gody (50 lat)'),
('El Matrimonio','Małżeństwo','la felicidad','szczęście'),
('El Matrimonio','Małżeństwo','fiel','wierny'),
('El Matrimonio','Małżeństwo','infiel','niewierny'),
('El Matrimonio','Małżeństwo','los celos','zazdrość'),
('El Matrimonio','Małżeństwo','discutir','kłócić się'),
('El Matrimonio','Małżeństwo','la separación','separacja'),
('El Matrimonio','Małżeństwo','separarse','separować się / rozstawać się'),
('El Matrimonio','Małżeństwo','el divorcio','rozwód'),
('El Matrimonio','Małżeństwo','divorciarse','rozwodzić się'),
('El Matrimonio','Małżeństwo','soltero','kawaler / singiel'),
('El Divorcio','Rozwód','el divorcio','rozwód'),
('El Divorcio','Rozwód','la separación','separacja'),
('El Divorcio','Rozwód','divorciarse','rozwodzić się'),
('El Divorcio','Rozwód','separarse','rozstawać się / separować się'),
('El Divorcio','Rozwód','el exmarido','były mąż'),
('El Divorcio','Rozwód','la exmujer','była żona'),
('El Divorcio','Rozwód','la expareja','były partner / była partnerka'),
('El Divorcio','Rozwód','el abogado','prawnik'),
('El Divorcio','Rozwód','el juez','sędzia'),
('El Divorcio','Rozwód','el tribunal','sąd'),
('El Divorcio','Rozwód','la demanda','pozew'),
('El Divorcio','Rozwód','el acuerdo','porozumienie'),
('El Divorcio','Rozwód','el desacuerdo','brak porozumienia'),
('El Divorcio','Rozwód','la firma','podpis'),
('El Divorcio','Rozwód','los papeles','papiery / dokumenty'),
('El Divorcio','Rozwód','el proceso','proces'),
('El Divorcio','Rozwód','la pensión alimenticia','alimenty'),
('El Divorcio','Rozwód','la custodia','opieka nad dziećmi'),
('El Divorcio','Rozwód','la custodia compartida','opieka naprzemienna'),
('El Divorcio','Rozwód','el régimen de visitas','ustalone wizyty (z dziećmi)'),
('El Divorcio','Rozwód','los bienes','majątek / dobra'),
('El Divorcio','Rozwód','la separación de bienes','rozdzielność majątkowa'),
('El Divorcio','Rozwód','el patrimonio','patrymonium / majątek'),
('El Divorcio','Rozwód','la crisis','kryzys'),
('El Divorcio','Rozwód','el conflicto','konflikt'),
('El Divorcio','Rozwód','la discusión','kłótnia'),
('El Divorcio','Rozwód','pelear','kłócić się / walczyć'),
('El Divorcio','Rozwód','la ruptura','zerwanie / rozpad'),
('El Divorcio','Rozwód','romper','zrywać'),
('El Divorcio','Rozwód','dejar','zostawiać (kogoś)'),
('El Divorcio','Rozwód','la infidelidad','niewierność'),
('El Divorcio','Rozwód','el engaño','oszustwo / zdrada'),
('El Divorcio','Rozwód','engañar','zdradzać / oszukiwać'),
('El Divorcio','Rozwód','el amante','kochanek'),
('El Divorcio','Rozwód','sufrir','cierpieć'),
('El Divorcio','Rozwód','llorar','płakać'),
('El Divorcio','Rozwód','el dolor','ból'),
('El Divorcio','Rozwód','superar','przezwyciężyć'),
('El Divorcio','Rozwód','olvidar','zapomnieć'),
('El Divorcio','Rozwód','perdonar','wybaczyć'),
('El Divorcio','Rozwód','rehacer la vida','ułożyć sobie życie na nowo'),
('El Divorcio','Rozwód','soltero','kawaler / singiel'),
('El Divorcio','Rozwód','el apoyo','wsparcie'),
('El Divorcio','Rozwód','la familia','rodzina'),
('El Divorcio','Rozwód','el mediador','mediator'),
('El Divorcio','Rozwód','el fallo','orzeczenie sądu'),
('El Divorcio','Rozwód','el estrés','stres'),
('El Divorcio','Rozwód','la tensión','napięcie'),
('El Divorcio','Rozwód','la reconciliación','pojednanie'),
('El Divorcio','Rozwód','el fin','koniec'),
('Relaciones de Pareja','Relacje partnerskie','la relación','relacja / związek'),
('Relaciones de Pareja','Relacje partnerskie','la pareja','para / partner'),
('Relaciones de Pareja','Relacje partnerskie','el novio','chłopak'),
('Relaciones de Pareja','Relacje partnerskie','la novia','dziewczyna'),
('Relaciones de Pareja','Relacje partnerskie','el compañero','partner życiowy'),
('Relaciones de Pareja','Relacje partnerskie','salir','spotykać się / chodzić z kimś'),
('Relaciones de Pareja','Relacje partnerskie','la cita','randka'),
('Relaciones de Pareja','Relacje partnerskie','conocer','poznać'),
('Relaciones de Pareja','Relacje partnerskie','enamorarse','zakochać się'),
('Relaciones de Pareja','Relacje partnerskie','el amor','miłość'),
('Relaciones de Pareja','Relacje partnerskie','el cariño','czułość'),
('Relaciones de Pareja','Relacje partnerskie','querer','kochać / lubić'),
('Relaciones de Pareja','Relacje partnerskie','amar','kochać'),
('Relaciones de Pareja','Relacje partnerskie','el beso','pocałunek'),
('Relaciones de Pareja','Relacje partnerskie','besar','całować'),
('Relaciones de Pareja','Relacje partnerskie','el abrazo','uścisk / przytulenie'),
('Relaciones de Pareja','Relacje partnerskie','abrazar','przytulać'),
('Relaciones de Pareja','Relacje partnerskie','la caricia','pieszczota'),
('Relaciones de Pareja','Relacje partnerskie','acariciar','pieścić / głaskać'),
('Relaciones de Pareja','Relacje partnerskie','la pasión','pasja / namiętność'),
('Relaciones de Pareja','Relacje partnerskie','el romance','romans'),
('Relaciones de Pareja','Relacje partnerskie','romántico','romantyczny'),
('Relaciones de Pareja','Relacje partnerskie','la intimidad','intymność'),
('Relaciones de Pareja','Relacje partnerskie','el sexo','seks'),
('Relaciones de Pareja','Relacje partnerskie','hacer el amor','uprawiać miłość'),
('Relaciones de Pareja','Relacje partnerskie','la confianza','zaufanie'),
('Relaciones de Pareja','Relacje partnerskie','confiar','ufać'),
('Relaciones de Pareja','Relacje partnerskie','la fidelidad','wierność'),
('Relaciones de Pareja','Relacje partnerskie','fiel','wierny'),
('Relaciones de Pareja','Relacje partnerskie','el respeto','szacunek'),
('Relaciones de Pareja','Relacje partnerskie','respetar','szanować'),
('Relaciones de Pareja','Relacje partnerskie','la comunicación','komunikacja'),
('Relaciones de Pareja','Relacje partnerskie','el apoyo','wsparcie'),
('Relaciones de Pareja','Relacje partnerskie','apoyar','wspierać'),
('Relaciones de Pareja','Relacje partnerskie','compartir','dzielić'),
('Relaciones de Pareja','Relacje partnerskie','la convivencia','wspólne życie'),
('Relaciones de Pareja','Relacje partnerskie','convivir','żyć razem'),
('Relaciones de Pareja','Relacje partnerskie','el compromiso','zaangażowanie / zaręczyny'),
('Relaciones de Pareja','Relacje partnerskie','comprometerse','zaręczyć się / zaangażować'),
('Relaciones de Pareja','Relacje partnerskie','la comprensión','zrozumienie'),
('Relaciones de Pareja','Relacje partnerskie','comprender','rozumieć'),
('Relaciones de Pareja','Relacje partnerskie','perdonar','wybaczać'),
('Relaciones de Pareja','Relacje partnerskie','pedir perdón','prosić o wybaczenie'),
('Relaciones de Pareja','Relacje partnerskie','los celos','zazdrość'),
('Relaciones de Pareja','Relacje partnerskie','celoso','zazdrosny'),
('Relaciones de Pareja','Relacje partnerskie','pelear','kłócić się'),
('Relaciones de Pareja','Relacje partnerskie','reconciliarse','godzić się'),
('Relaciones de Pareja','Relacje partnerskie','la media naranja','druga połówka (dosł. pół pomarańczy)'),
('Relaciones de Pareja','Relacje partnerskie','atraer','przyciągać'),
('Relaciones de Pareja','Relacje partnerskie','el flechazo','miłość od pierwszego wejrzenia (strzała amora)'),
('Sentimientos Positivos','Pozytywne uczucia','la felicidad','szczęście'),
('Sentimientos Positivos','Pozytywne uczucia','feliz','szczęśliwy'),
('Sentimientos Positivos','Pozytywne uczucia','la alegría','radość'),
('Sentimientos Positivos','Pozytywne uczucia','alegre','radosny'),
('Sentimientos Positivos','Pozytywne uczucia','el optimismo','optymizm'),
('Sentimientos Positivos','Pozytywne uczucia','optimista','optymistyczny'),
('Sentimientos Positivos','Pozytywne uczucia','la esperanza','nadzieja'),
('Sentimientos Positivos','Pozytywne uczucia','esperanzado','pełen nadziei'),
('Sentimientos Positivos','Pozytywne uczucia','la ilusión','ekscytacja / złudzenie'),
('Sentimientos Positivos','Pozytywne uczucia','ilusionado','podekscytowany'),
('Sentimientos Positivos','Pozytywne uczucia','el entusiasmo','entuzjazm'),
('Sentimientos Positivos','Pozytywne uczucia','entusiasta','entuzjastyczny'),
('Sentimientos Positivos','Pozytywne uczucia','la paz','pokój'),
('Sentimientos Positivos','Pozytywne uczucia','pacífico','spokojny / pokojowy'),
('Sentimientos Positivos','Pozytywne uczucia','la tranquilidad','spokój'),
('Sentimientos Positivos','Pozytywne uczucia','tranquilo','spokojny'),
('Sentimientos Positivos','Pozytywne uczucia','la calma','cisza / spokój'),
('Sentimientos Positivos','Pozytywne uczucia','calmado','opanowany'),
('Sentimientos Positivos','Pozytywne uczucia','la satisfacción','satysfakcja'),
('Sentimientos Positivos','Pozytywne uczucia','satisfecho','zadowolony'),
('Sentimientos Positivos','Pozytywne uczucia','el orgullo','duma'),
('Sentimientos Positivos','Pozytywne uczucia','orgulloso','dumny'),
('Sentimientos Positivos','Pozytywne uczucia','la gratitud','wdzięczność'),
('Sentimientos Positivos','Pozytywne uczucia','agradecido','wdzięczny'),
('Sentimientos Positivos','Pozytywne uczucia','el alivio','ulga'),
('Sentimientos Positivos','Pozytywne uczucia','aliviado','odczuwający ulgę'),
('Sentimientos Positivos','Pozytywne uczucia','la admiración','podziw'),
('Sentimientos Positivos','Pozytywne uczucia','admirado','zachwycony'),
('Sentimientos Positivos','Pozytywne uczucia','el asombro','zdumienie / podziw'),
('Sentimientos Positivos','Pozytywne uczucia','asombrado','zdumiony'),
('Sentimientos Positivos','Pozytywne uczucia','el cariño','czułość / sympatia'),
('Sentimientos Positivos','Pozytywne uczucia','cariñoso','czuły'),
('Sentimientos Positivos','Pozytywne uczucia','la ternura','tkliwość'),
('Sentimientos Positivos','Pozytywne uczucia','tierno','tkliwy / czuły'),
('Sentimientos Positivos','Pozytywne uczucia','la empatía','empatia'),
('Sentimientos Positivos','Pozytywne uczucia','empático','empatyczny'),
('Sentimientos Positivos','Pozytywne uczucia','la simpatía','sympatia'),
('Sentimientos Positivos','Pozytywne uczucia','simpático','sympatyczny'),
('Sentimientos Positivos','Pozytywne uczucia','la confianza','zaufanie / pewność'),
('Sentimientos Positivos','Pozytywne uczucia','confiado','ufny / pewny siebie'),
('Sentimientos Positivos','Pozytywne uczucia','la seguridad','bezpieczeństwo / pewność'),
('Sentimientos Positivos','Pozytywne uczucia','seguro','pewny'),
('Sentimientos Positivos','Pozytywne uczucia','la motivación','motywacja'),
('Sentimientos Positivos','Pozytywne uczucia','motivado','zmotywowany'),
('Sentimientos Positivos','Pozytywne uczucia','la inspiración','inspiracja'),
('Sentimientos Positivos','Pozytywne uczucia','inspirado','zainspirowany'),
('Sentimientos Positivos','Pozytywne uczucia','la pasión','pasja'),
('Sentimientos Positivos','Pozytywne uczucia','apasionado','pełen pasji'),
('Sentimientos Positivos','Pozytywne uczucia','la valentía','odwaga'),
('Sentimientos Positivos','Pozytywne uczucia','valiente','odważny');
