insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('En el Aeropuerto','Na lotnisku','el aeropuerto','lotnisko'),
('En el Aeropuerto','Na lotnisku','el avión','samolot'),
('En el Aeropuerto','Na lotnisku','el vuelo','lot'),
('En el Aeropuerto','Na lotnisku','la terminal','terminal'),
('En el Aeropuerto','Na lotnisku','la puerta de embarque','bramka (gate)'),
('En el Aeropuerto','Na lotnisku','el mostrador','stanowisko odprawy'),
('En el Aeropuerto','Na lotnisku','la facturación','odprawa biletowa'),
('En el Aeropuerto','Na lotnisku','el billete','bilet'),
('En el Aeropuerto','Na lotnisku','la tarjeta de embarque','karta pokładowa'),
('En el Aeropuerto','Na lotnisku','el pasaporte','paszport'),
('En el Aeropuerto','Na lotnisku','el carné de identidad','dowód osobisty'),
('En el Aeropuerto','Na lotnisku','el visado','wiza'),
('En el Aeropuerto','Na lotnisku','el equipaje','bagaż'),
('En el Aeropuerto','Na lotnisku','la maleta','walizka'),
('En el Aeropuerto','Na lotnisku','el equipaje de mano','bagaż podręczny'),
('En el Aeropuerto','Na lotnisku','la cinta','taśma bagażowa'),
('En el Aeropuerto','Na lotnisku','la aduana','urząd celny / cło'),
('En el Aeropuerto','Na lotnisku','el control de seguridad','kontrola bezpieczeństwa'),
('En el Aeropuerto','Na lotnisku','el pasajero','pasażer'),
('En el Aeropuerto','Na lotnisku','el piloto','pilot'),
('En el Aeropuerto','Na lotnisku','la azafata','stewardesa'),
('En el Aeropuerto','Na lotnisku','el asiento','siedzenie / miejsce'),
('En el Aeropuerto','Na lotnisku','el cinturón de seguridad','pas bezpieczeństwa'),
('En el Aeropuerto','Na lotnisku','despegar','startować'),
('En el Aeropuerto','Na lotnisku','el despegue','start (samolotu)'),
('En el Aeropuerto','Na lotnisku','aterrizar','lądować'),
('En el Aeropuerto','Na lotnisku','el aterrizaje','lądowanie'),
('En el Aeropuerto','Na lotnisku','el retraso','opóźnienie'),
('En el Aeropuerto','Na lotnisku','retrasado','opóźniony'),
('En el Aeropuerto','Na lotnisku','cancelado','odwołany'),
('En el Aeropuerto','Na lotnisku','a tiempo','na czas'),
('En el Aeropuerto','Na lotnisku','la llegada','przylot'),
('En el Aeropuerto','Na lotnisku','la salida','odlot'),
('En el Aeropuerto','Na lotnisku','la escala','międzylądowanie / przesiadka'),
('En el Aeropuerto','Na lotnisku','la compañía aérea','linia lotnicza'),
('En el Aeropuerto','Na lotnisku','el exceso de equipaje','nadbagaż'),
('En el Aeropuerto','Na lotnisku','declarar','clić / deklarować'),
('En el Aeropuerto','Na lotnisku','la pantalla','ekran / tablica odlotów'),
('En el Aeropuerto','Na lotnisku','el vuelo nacional','lot krajowy'),
('En el Aeropuerto','Na lotnisku','el vuelo internacional','lot międzynarodowy'),
('En el Aeropuerto','Na lotnisku','la sala de espera','poczekalnia'),
('En el Aeropuerto','Na lotnisku','el carrito','wózek na bagaż'),
('En el Aeropuerto','Na lotnisku','el asiento de pasillo','miejsce przy korytarzu'),
('En el Aeropuerto','Na lotnisku','el asiento de ventanilla','miejsce przy oknie'),
('En el Aeropuerto','Na lotnisku','la emergencia','awaria / nagły wypadek'),
('En el Aeropuerto','Na lotnisku','el chaleco salvavidas','kamizelka ratunkowa'),
('En el Aeropuerto','Na lotnisku','la máscara de oxígeno','maska tlenowa'),
('En el Aeropuerto','Na lotnisku','volar','latać'),
('En el Aeropuerto','Na lotnisku','el destino','cel podróży'),
('En el Aeropuerto','Na lotnisku','el viaje','podróż'),
('Las Direcciones','Kierunki','la dirección','kierunek / adres'),
('Las Direcciones','Kierunki','la calle','ulica'),
('Las Direcciones','Kierunki','la avenida','aleja'),
('Las Direcciones','Kierunki','la plaza','plac'),
('Las Direcciones','Kierunki','el cruce','skrzyżowanie'),
('Las Direcciones','Kierunki','la esquina','róg'),
('Las Direcciones','Kierunki','el semáforo','sygnalizacja świetlna'),
('Las Direcciones','Kierunki','el paso de cebra','przejście dla pieszych'),
('Las Direcciones','Kierunki','la acera','chodnik'),
('Las Direcciones','Kierunki','el puente','most'),
('Las Direcciones','Kierunki','el túnel','tunel'),
('Las Direcciones','Kierunki','el edificio','budynek'),
('Las Direcciones','Kierunki','el barrio','dzielnica'),
('Las Direcciones','Kierunki','el mapa','mapa'),
('Las Direcciones','Kierunki','el plano','plan (miasta)'),
('Las Direcciones','Kierunki','el GPS','GPS'),
('Las Direcciones','Kierunki','la ruta','trasa'),
('Las Direcciones','Kierunki','el norte','północ'),
('Las Direcciones','Kierunki','el sur','południe'),
('Las Direcciones','Kierunki','el este','wschód'),
('Las Direcciones','Kierunki','el oeste','zachód'),
('Las Direcciones','Kierunki','la derecha','prawa strona'),
('Las Direcciones','Kierunki','la izquierda','lewa strona'),
('Las Direcciones','Kierunki','recto','prosto'),
('Las Direcciones','Kierunki','hacia adelante','naprzód'),
('Las Direcciones','Kierunki','hacia atrás','w tył'),
('Las Direcciones','Kierunki','arriba','w górę / na górze'),
('Las Direcciones','Kierunki','abajo','w dół / na dole'),
('Las Direcciones','Kierunki','cerca','blisko'),
('Las Direcciones','Kierunki','lejos','daleko'),
('Las Direcciones','Kierunki','aquí','tutaj'),
('Las Direcciones','Kierunki','allí / allá','tam'),
('Las Direcciones','Kierunki','enfrente de','naprzeciwko'),
('Las Direcciones','Kierunki','detrás de','za'),
('Las Direcciones','Kierunki','al lado de','obok'),
('Las Direcciones','Kierunki','entre','pomiędzy'),
('Las Direcciones','Kierunki','cruzar','przechodzić / przekraczać'),
('Las Direcciones','Kierunki','girar / torcer','skręcać'),
('Las Direcciones','Kierunki','seguir / continuar','kontynuować / iść dalej'),
('Las Direcciones','Kierunki','parar','zatrzymywać się'),
('Las Direcciones','Kierunki','buscar','szukać'),
('Las Direcciones','Kierunki','encontrar','znaleźć'),
('Las Direcciones','Kierunki','perderse','zgubić się'),
('Las Direcciones','Kierunki','estar perdido','być zagubionym'),
('Las Direcciones','Kierunki','preguntar','pytać'),
('Las Direcciones','Kierunki','la distancia','odległość'),
('Las Direcciones','Kierunki','el kilómetro','kilometr'),
('Las Direcciones','Kierunki','el metro','metr'),
('Las Direcciones','Kierunki','ir','iść / jechać'),
('Las Direcciones','Kierunki','llegar','przybywać / docierać'),
('El Dinero','Pieniądze','el dinero','pieniądze'),
('El Dinero','Pieniądze','el efectivo','gotówka'),
('El Dinero','Pieniądze','la moneda','moneta / waluta'),
('El Dinero','Pieniądze','el billete','banknot'),
('El Dinero','Pieniądze','el sueldo','pensja'),
('El Dinero','Pieniądze','el salario','wynagrodzenie'),
('El Dinero','Pieniądze','la cartera','portfel'),
('El Dinero','Pieniądze','el monedero','portmonetka'),
('El Dinero','Pieniądze','el banco','bank'),
('El Dinero','Pieniądze','la cuenta bancaria','konto bankowe'),
('El Dinero','Pieniądze','la tarjeta de crédito','karta kredytowa'),
('El Dinero','Pieniądze','la tarjeta de débito','karta debetowa'),
('El Dinero','Pieniądze','el cajero automático','bankomat'),
('El Dinero','Pieniądze','el PIN','kod PIN'),
('El Dinero','Pieniądze','el cambio','reszta (z zakupów)'),
('El Dinero','Pieniądze','la divisa','waluta obca'),
('El Dinero','Pieniądze','el euro','euro'),
('El Dinero','Pieniądze','el dólar','dolar'),
('El Dinero','Pieniądze','el zloty','złoty'),
('El Dinero','Pieniądze','el precio','cena'),
('El Dinero','Pieniądze','caro','drogi'),
('El Dinero','Pieniądze','barato','tani'),
('El Dinero','Pieniądze','gratis','za darmo'),
('El Dinero','Pieniądze','costar','kosztować'),
('El Dinero','Pieniądze','pagar','płacić'),
('El Dinero','Pieniądze','cobrar','pobierać opłatę / zarabiać'),
('El Dinero','Pieniądze','comprar','kupować'),
('El Dinero','Pieniądze','vender','sprzedawać'),
('El Dinero','Pieniądze','gastar','wydawać'),
('El Dinero','Pieniądze','ahorrar','oszczędzać'),
('El Dinero','Pieniądze','prestar','pożyczać (komuś)'),
('El Dinero','Pieniądze','pedir prestado','pożyczać (od kogoś)'),
('El Dinero','Pieniądze','deber','być winnym'),
('El Dinero','Pieniądze','la deuda','dług'),
('El Dinero','Pieniądze','la factura','faktura'),
('El Dinero','Pieniądze','el recibo','paragon'),
('El Dinero','Pieniądze','la caja','kasa (w sklepie)'),
('El Dinero','Pieniądze','el descuento','zniżka'),
('El Dinero','Pieniądze','la oferta','oferta / promocja'),
('El Dinero','Pieniądze','la rebaja','wyprzedaż / obniżka'),
('El Dinero','Pieniądze','el porcentaje','procent'),
('El Dinero','Pieniądze','la comisión','prowizja'),
('El Dinero','Pieniądze','el impuesto','podatek'),
('El Dinero','Pieniądze','el interés','odsetki'),
('El Dinero','Pieniądze','rico','bogaty'),
('El Dinero','Pieniądze','pobre','biedny'),
('El Dinero','Pieniądze','la riqueza','bogactwo'),
('El Dinero','Pieniądze','la pobreza','bieda'),
('El Dinero','Pieniądze','la propina','napiwek'),
('El Dinero','Pieniądze','la alcancía / la hucha','skarbonka'),
('De Compras','Na zakupach','ir de compras','iść na zakupy'),
('De Compras','Na zakupach','la tienda','sklep'),
('De Compras','Na zakupach','el centro comercial','centrum handlowe'),
('De Compras','Na zakupach','el mercado','rynek / targ'),
('De Compras','Na zakupach','el supermercado','supermarket'),
('De Compras','Na zakupach','el dependiente / la dependienta','ekspedient / ekspedientka'),
('De Compras','Na zakupach','el cliente / la clienta','klient / klientka'),
('De Compras','Na zakupach','el escaparate','witryna sklepowa'),
('De Compras','Na zakupach','el probador','przymierzalnia'),
('De Compras','Na zakupach','probarse','przymierzać (ubranie)'),
('De Compras','Na zakupach','la talla','rozmiar (ubrania)'),
('De Compras','Na zakupach','el número','rozmiar (buta)'),
('De Compras','Na zakupach','quedar bien','pasować / dobrze leżeć'),
('De Compras','Na zakupach','quedar mal','nie pasować / źle leżeć'),
('De Compras','Na zakupach','el carrito','wózek na zakupy'),
('De Compras','Na zakupach','la cesta','koszyk (na zakupy)'),
('De Compras','Na zakupach','la bolsa','torba / siatka'),
('De Compras','Na zakupach','la caja','kasa'),
('De Compras','Na zakupach','el cajero / la cajera','kasjer / kasjerka'),
('De Compras','Na zakupach','la cola / la fila','kolejka'),
('De Compras','Na zakupach','hacer cola','stać w kolejce'),
('De Compras','Na zakupach','el precio','cena'),
('De Compras','Na zakupach','la etiqueta','etykieta / metka'),
('De Compras','Na zakupach','el descuento','zniżka'),
('De Compras','Na zakupach','la oferta','oferta / promocja'),
('De Compras','Na zakupach','las rebajas','wyprzedaże'),
('De Compras','Na zakupach','barato','tani'),
('De Compras','Na zakupach','caro','drogi'),
('De Compras','Na zakupach','gratis','za darmo'),
('De Compras','Na zakupach','pagar','płacić'),
('De Compras','Na zakupach','en efectivo','gotówką'),
('De Compras','Na zakupach','con tarjeta','kartą'),
('De Compras','Na zakupach','el cambio','reszta (pieniądze)'),
('De Compras','Na zakupach','el recibo / el ticket','paragon'),
('De Compras','Na zakupach','la factura','faktura'),
('De Compras','Na zakupach','la garantía','gwarancja'),
('De Compras','Na zakupach','devolver','zwracać'),
('De Compras','Na zakupach','el reembolso','zwrot pieniędzy'),
('De Compras','Na zakupach','comprar','kupować'),
('De Compras','Na zakupach','vender','sprzedawać'),
('De Compras','Na zakupach','gastar','wydawać (pieniądze)'),
('De Compras','Na zakupach','abierto','otwarty'),
('De Compras','Na zakupach','cerrado','zamknięty'),
('De Compras','Na zakupach','el horario','godziny otwarcia'),
('De Compras','Na zakupach','la marca','marka'),
('De Compras','Na zakupach','de segunda mano','z drugiej ręki / używany'),
('De Compras','Na zakupach','el producto','produkt'),
('De Compras','Na zakupach','la calidad','jakość'),
('De Compras','Na zakupach','envolver','pakować (np. na prezent)'),
('De Compras','Na zakupach','el turno','kolej (w kolejce)');
