insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Continentes y Océanos','Kontynenty i oceany','el océano','ocean'),
('Continentes y Océanos','Kontynenty i oceany','Europa','Europa'),
('Continentes y Océanos','Kontynenty i oceany','Asia','Azja'),
('Continentes y Océanos','Kontynenty i oceany','África','Afryka'),
('Continentes y Océanos','Kontynenty i oceany','América del Norte','Ameryka Północna'),
('Continentes y Océanos','Kontynenty i oceany','América del Sur','Ameryka Południowa'),
('Continentes y Océanos','Kontynenty i oceany','Oceanía','Oceania'),
('Continentes y Océanos','Kontynenty i oceany','la Antártida','Antarktyda'),
('Continentes y Océanos','Kontynenty i oceany','el Océano Pacífico','Ocean Spokojny / Pacyfik'),
('Continentes y Océanos','Kontynenty i oceany','el Océano Atlántico','Ocean Atlantycki'),
('Continentes y Océanos','Kontynenty i oceany','el Océano Índico','Ocean Indyjski'),
('Continentes y Océanos','Kontynenty i oceany','el Océano Ártico','Ocean Arktyczny'),
('Continentes y Océanos','Kontynenty i oceany','el Océano Antártico','Ocean Południowy'),
('Continentes y Océanos','Kontynenty i oceany','el mar','morze'),
('Continentes y Océanos','Kontynenty i oceany','la tierra','ziemia / ląd'),
('Continentes y Océanos','Kontynenty i oceany','la isla','wyspa'),
('Continentes y Océanos','Kontynenty i oceany','el archipiélago','archipelag'),
('Continentes y Océanos','Kontynenty i oceany','la península','półwysep'),
('Continentes y Océanos','Kontynenty i oceany','el istmo','przesmyk'),
('Continentes y Océanos','Kontynenty i oceany','el cabo','przylądek'),
('Continentes y Océanos','Kontynenty i oceany','el golfo','zatoka'),
('Continentes y Océanos','Kontynenty i oceany','la bahía','zatoka (mała)'),
('Continentes y Océanos','Kontynenty i oceany','el estrecho','cieśnina'),
('Continentes y Océanos','Kontynenty i oceany','el ecuador','równik'),
('Continentes y Océanos','Kontynenty i oceany','el meridiano','południk'),
('Continentes y Océanos','Kontynenty i oceany','los trópicos','zwrotniki'),
('Continentes y Océanos','Kontynenty i oceany','el polo norte','biegun północny'),
('Continentes y Océanos','Kontynenty i oceany','el polo sur','biegun południowy'),
('Continentes y Océanos','Kontynenty i oceany','la latitud','szerokość geograficzna'),
('Continentes y Océanos','Kontynenty i oceany','la longitud','długość geograficzna'),
('Continentes y Océanos','Kontynenty i oceany','el hemisferio norte','półkula północna'),
('Continentes y Océanos','Kontynenty i oceany','el hemisferio sur','półkula południowa'),
('Continentes y Océanos','Kontynenty i oceany','el mapa','mapa'),
('Continentes y Océanos','Kontynenty i oceany','el globo terráqueo','globus'),
('Continentes y Océanos','Kontynenty i oceany','la cartografía','kartografia'),
('Continentes y Océanos','Kontynenty i oceany','el atlas','atlas'),
('Continentes y Océanos','Kontynenty i oceany','la brújula','kompas'),
('Continentes y Océanos','Kontynenty i oceany','el relieve','rzeźba terenu'),
('Continentes y Océanos','Kontynenty i oceany','la llanura','równina'),
('Continentes y Océanos','Kontynenty i oceany','la meseta','płaskowyż'),
('Continentes y Océanos','Kontynenty i oceany','la cordillera','łańcuch górski'),
('Continentes y Océanos','Kontynenty i oceany','el valle','dolina'),
('Continentes y Océanos','Kontynenty i oceany','el desierto','pustynia'),
('Continentes y Océanos','Kontynenty i oceany','la selva','dżungla'),
('Continentes y Océanos','Kontynenty i oceany','el bosque','las'),
('Continentes y Océanos','Kontynenty i oceany','la tundra','tundra'),
('Continentes y Océanos','Kontynenty i oceany','la taiga','tajga'),
('Continentes y Océanos','Kontynenty i oceany','la sabana','sawanna'),
('Continentes y Océanos','Kontynenty i oceany','la costa','wybrzeże'),
('Demografía','Demografia','la demografía','demografia'),
('Demografía','Demografia','la población','populacja'),
('Demografía','Demografia','el censo','spis powszechny'),
('Demografía','Demografia','el habitante','mieszkaniec'),
('Demografía','Demografia','el crecimiento demográfico','wzrost demograficzny'),
('Demografía','Demografia','la tasa de natalidad','wskaźnik urodzeń'),
('Demografía','Demografia','la tasa de mortalidad','wskaźnik śmiertelności'),
('Demografía','Demografia','la tasa de fertilidad','wskaźnik dzietności'),
('Demografía','Demografia','la esperanza de vida','średnia długość życia'),
('Demografía','Demografia','la densidad de población','gęstość zaludnienia'),
('Demografía','Demografia','el envejecimiento','starzenie się'),
('Demografía','Demografia','la población activa','ludność aktywna zawodowo'),
('Demografía','Demografia','la población inactiva','ludność nieaktywna zawodowo'),
('Demografía','Demografia','el éxodo rural','migracja ze wsi do miast'),
('Demografía','Demografia','la urbanización','urbanizacja'),
('Demografía','Demografia','la metrópoli','metropolia'),
('Demografía','Demografia','la ciudad','miasto'),
('Demografía','Demografia','el pueblo','wieś / miasteczko'),
('Demografía','Demografia','el suburbio','przedmieście'),
('Demografía','Demografia','la tasa de crecimiento','stopa wzrostu'),
('Demografía','Demografia','la pirámide de población','piramida wieku'),
('Demografía','Demografia','la cohorte','kohorta'),
('Demografía','Demografia','el baby boom','wyż demograficzny'),
('Demografía','Demografia','la tasa de nupcialidad','wskaźnik małżeństw'),
('Demografía','Demografia','la tasa de divorcio','wskaźnik rozwodów'),
('Demografía','Demografia','el hogar','gospodarstwo domowe'),
('Demografía','Demografia','la familia','rodzina'),
('Demografía','Demografia','el soltero','kawaler / singiel'),
('Demografía','Demografia','el casado','żonaty / zamężna'),
('Demografía','Demografia','el divorciado','rozwiedziony'),
('Demografía','Demografia','el viudo','wdowiec'),
('Demografía','Demografia','la tasa de dependencia','wskaźnik obciążenia demograficznego'),
('Demografía','Demografia','la superpoblación','przeludnienie'),
('Demografía','Demografia','el control de la natalidad','kontrola urodzeń'),
('Demografía','Demografia','la planificación familiar','planowanie rodziny'),
('Demografía','Demografia','la migración','migracja'),
('Demografía','Demografia','la inmigración','imigracja'),
('Demografía','Demografia','la emigración','emigracja'),
('Demografía','Demografia','el saldo migratorio','saldo migracji'),
('Demografía','Demografia','el éxodo','eksodus / wędrówka ludów'),
('Demografía','Demografia','el asentamiento','osadnictwo'),
('Demografía','Demografia','la comunidad','wspólnota / społeczność'),
('Demografía','Demografia','la minoría','mniejszość'),
('Demografía','Demografia','la mayoría','większość'),
('Demografía','Demografia','la tasa de mortalidad infantil','śmiertelność niemowląt'),
('Demografía','Demografia','la esperanza de vida al nacer','oczekiwana długość życia przy urodzeniu'),
('Demografía','Demografia','el demógrafo','demograf'),
('Demografía','Demografia','la estadística','statystyka'),
('Demografía','Demografia','el indicador','wskaźnik'),
('Demografía','Demografia','la población total','ludność całkowita'),
('Problemas Sociales','Problemy społeczne','el problema social','problem społeczny'),
('Problemas Sociales','Problemy społeczne','la pobreza','ubóstwo'),
('Problemas Sociales','Problemy społeczne','la desigualdad','nierówność'),
('Problemas Sociales','Problemy społeczne','la discriminación','dyskryminacja'),
('Problemas Sociales','Problemy społeczne','el desempleo','bezrobocie'),
('Problemas Sociales','Problemy społeczne','la delincuencia','przestępczość'),
('Problemas Sociales','Problemy społeczne','la violencia','przemoc'),
('Problemas Sociales','Problemy społeczne','la violencia de género','przemoc ze względu na płeć'),
('Problemas Sociales','Problemy społeczne','el racismo','rasizm'),
('Problemas Sociales','Problemy społeczne','la xenofobia','ksenofobia'),
('Problemas Sociales','Problemy społeczne','la homofobia','homofobia'),
('Problemas Sociales','Problemy społeczne','la marginación','marginalizacja'),
('Problemas Sociales','Problemy społeczne','la exclusión social','wykluczenie społeczne'),
('Problemas Sociales','Problemy społeczne','la adicción','uzależnienie'),
('Problemas Sociales','Problemy społeczne','el alcoholismo','alkoholizm'),
('Problemas Sociales','Problemy społeczne','la drogadicción','narkomania'),
('Problemas Sociales','Problemy społeczne','la ludopatía','uzależnienie od hazardu'),
('Problemas Sociales','Problemy społeczne','la indigencia','bezdomność'),
('Problemas Sociales','Problemy społeczne','el sintecho','bezdomny'),
('Problemas Sociales','Problemy społeczne','la corrupción','korupcja'),
('Problemas Sociales','Problemy społeczne','la delincuencia juvenil','przestępczość nieletnich'),
('Problemas Sociales','Problemy społeczne','el acoso','nękanie'),
('Problemas Sociales','Problemy społeczne','el acoso escolar','przemoc szkolna'),
('Problemas Sociales','Problemy społeczne','el mobbing','mobbing / nękanie w pracy'),
('Problemas Sociales','Problemy społeczne','la explotación infantil','wyzysk dzieci'),
('Problemas Sociales','Problemy społeczne','el trabajo esclavo','praca niewolnicza'),
('Problemas Sociales','Problemy społeczne','la trata de personas','handel ludźmi'),
('Problemas Sociales','Problemy społeczne','la contaminación','zanieczyszczenie'),
('Problemas Sociales','Problemy społeczne','el cambio climático','zmiana klimatu'),
('Problemas Sociales','Problemy społeczne','la crisis económica','kryzys gospodarczy'),
('Problemas Sociales','Problemy społeczne','la inflación','inflacja'),
('Problemas Sociales','Problemy społeczne','la precariedad laboral','niestabilność zatrudnienia'),
('Problemas Sociales','Problemy społeczne','la falta de vivienda','brak mieszkań'),
('Problemas Sociales','Problemy społeczne','el analfabetismo','analfabetyzm'),
('Problemas Sociales','Problemy społeczne','la desnutrición','niedożywienie'),
('Problemas Sociales','Problemy społeczne','la hambruna','głód'),
('Problemas Sociales','Problemy społeczne','el conflicto','konflikt'),
('Problemas Sociales','Problemy społeczne','la guerra','wojna'),
('Problemas Sociales','Problemy społeczne','la delincuencia organizada','zorganizowana przestępczość'),
('Problemas Sociales','Problemy społeczne','la violencia doméstica','przemoc domowa'),
('Problemas Sociales','Problemy społeczne','la discriminación laboral','dyskryminacja w pracy'),
('Problemas Sociales','Problemy społeczne','la brecha salarial','różnica w płacach'),
('Problemas Sociales','Problemy społeczne','la injusticia','niesprawiedliwość'),
('Problemas Sociales','Problemy społeczne','la protesta','protest'),
('Problemas Sociales','Problemy społeczne','la huelga','strajk'),
('Problemas Sociales','Problemy społeczne','la manifestación','manifestacja'),
('Problemas Sociales','Problemy społeczne','la solución','rozwiązanie'),
('Problemas Sociales','Problemy społeczne','la prevención','profilaktyka'),
('Problemas Sociales','Problemy społeczne','el apoyo','wsparcie'),
('Problemas Sociales','Problemy społeczne','la solidaridad','solidarność'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la pobreza','ubóstwo'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la riqueza','bogactwo'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el pobre','biedny'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el rico','bogaty'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la indigencia','skrajna bieda'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la miseria','nędza'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el lujo','luksus'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la opulencia','przepych'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la abundancia','obfitość'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la escasez','niedostatek'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la desigualdad','nierówność'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la brecha social','przepaść społeczna'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el umbral de pobreza','próg ubóstwa'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la pobreza extrema','skrajne ubóstwo'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el hambre','głód'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la desnutrición','niedożywienie'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el sintecho','bezdomny'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la asistencia social','opieka społeczna'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la beneficencia','dobroczynność'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la caridad','miłosierdzie'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la ayuda humanitaria','pomoc humanitarna'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la subvención','dotacja / zapomoga'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el subsidio','zasiłek'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el subsidio de desempleo','zasiłek dla bezrobotnych'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el magnate','magnat'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el millonario','milioner'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el multimillonario','multimilioner'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la fortuna','majątek'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el patrimonio','aktywa / majątek'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la herencia','spadek'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la inversión','inwestycja'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el capital','kapitał'),
('Pobreza y Riqueza','Bóstwo i bogactwo','los ingresos','dochody'),
('Pobreza y Riqueza','Bóstwo i bogactwo','los gastos','wydatki'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la ganancia','zysk'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la pérdida','strata'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la quiebra','bankructwo'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la bancarrota','bancructwo / niewypłacalność'),
('Pobreza y Riqueza','Bóstwo i bogactwo','mendigar','żebrać'),
('Pobreza y Riqueza','Bóstwo i bogactwo','el mendigo','żebrak'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la limosna','jałmużna'),
('Pobreza y Riqueza','Bóstwo i bogactwo','derrochar','roztrwaniać'),
('Pobreza y Riqueza','Bóstwo i bogactwo','malbaratar','marnotrawić'),
('Pobreza y Riqueza','Bóstwo i bogactwo','ahorrar','oszczędzać'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la austeridad','austeryczność'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la generosidad','hojność'),
('Pobreza y Riqueza','Bóstwo i bogactwo','la avaricia','chciwość'),
('Pobreza y Riqueza','Bóstwo i bogactwo','avaro','chciwy'),
('Pobreza y Riqueza','Bóstwo i bogactwo','próspero','pomyślny'),
('Pobreza y Riqueza','Bóstwo i bogactwo','acomodado','zamożny'),
('Migración','Migracja','la migración','migracja');
