insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Telas y Tejidos','Tkaniny i materiały','la tela','tkanina / materiał'),
('Telas y Tejidos','Tkaniny i materiały','el tejido','tkactwo / materiał'),
('Telas y Tejidos','Tkaniny i materiały','el algodón','bawełna'),
('Telas y Tejidos','Tkaniny i materiały','la lana','wełna'),
('Telas y Tejidos','Tkaniny i materiały','la seda','jedwab'),
('Telas y Tejidos','Tkaniny i materiały','el lino','len'),
('Telas y Tejidos','Tkaniny i materiały','el poliéster','poliester'),
('Telas y Tejidos','Tkaniny i materiały','el nailon','nylon'),
('Telas y Tejidos','Tkaniny i materiały','el terciopelo','aksamit'),
('Telas y Tejidos','Tkaniny i materiały','la pana','sztruks'),
('Telas y Tejidos','Tkaniny i materiały','el cuero','skóra (materiał)'),
('Telas y Tejidos','Tkaniny i materiały','el ante','zamsz'),
('Telas y Tejidos','Tkaniny i materiały','la mezclilla / el vaquero','jeans / dżins'),
('Telas y Tejidos','Tkaniny i materiały','el encaje','koronka'),
('Telas y Tejidos','Tkaniny i materiały','el tul','tiul'),
('Telas y Tejidos','Tkaniny i materiały','el satén','satyna'),
('Telas y Tejidos','Tkaniny i materiały','la gasa','gaza / szyfon'),
('Telas y Tejidos','Tkaniny i materiały','la lycra','lycra'),
('Telas y Tejidos','Tkaniny i materiały','el fieltro','filc'),
('Telas y Tejidos','Tkaniny i materiały','la franela','flanela'),
('Telas y Tejidos','Tkaniny i materiały','el cachemir','kaszmir'),
('Telas y Tejidos','Tkaniny i materiały','el acrílico','akryl'),
('Telas y Tejidos','Tkaniny i materiały','la viscosa','wiskoza'),
('Telas y Tejidos','Tkaniny i materiały','el rayón','sztuczny jedwab / wiskoza'),
('Telas y Tejidos','Tkaniny i materiały','tejer','tkać / robić na drutach'),
('Telas y Tejidos','Tkaniny i materiały','coser','szyć'),
('Telas y Tejidos','Tkaniny i materiały','bordar','haftować'),
('Telas y Tejidos','Tkaniny i materiały','el hilo','nić'),
('Telas y Tejidos','Tkaniny i materiały','la aguja','igła'),
('Telas y Tejidos','Tkaniny i materiały','el patrón','wzór (krawiecki)'),
('Telas y Tejidos','Tkaniny i materiały','suave','miękki / gładki'),
('Telas y Tejidos','Tkaniny i materiały','áspero','szorstki'),
('Telas y Tejidos','Tkaniny i materiały','grueso','gruby (o materiale)'),
('Telas y Tejidos','Tkaniny i materiały','fino','cienki / delikatny'),
('Telas y Tejidos','Tkaniny i materiały','transparente','przezroczysty'),
('Telas y Tejidos','Tkaniny i materiały','elástico','elastyczny'),
('Telas y Tejidos','Tkaniny i materiały','resistente','wytrzymały'),
('Telas y Tejidos','Tkaniny i materiały','el tinte','barwnik'),
('Telas y Tejidos','Tkaniny i materiały','teñir','farbować (materiał)'),
('Telas y Tejidos','Tkaniny i materiały','estampado','wzorzysty / z nadrukiem'),
('Telas y Tejidos','Tkaniny i materiały','liso','gładki / jednolity (bez wzoru)'),
('Telas y Tejidos','Tkaniny i materiały','a rayas','w paski'),
('Telas y Tejidos','Tkaniny i materiały','a cuadros','w kratkę'),
('Telas y Tejidos','Tkaniny i materiały','de lunares','w grochy'),
('Telas y Tejidos','Tkaniny i materiały','el metro','metr (bieżący)'),
('Telas y Tejidos','Tkaniny i materiały','la textura','tekstura / faktura'),
('Telas y Tejidos','Tkaniny i materiały','la fibra','włókno'),
('Telas y Tejidos','Tkaniny i materiały','la fibra sintética','włókno syntetyczne'),
('Telas y Tejidos','Tkaniny i materiały','la costura','szew / szycie'),
('Telas y Tejidos','Tkaniny i materiały','el retal','ścinka / resztka materiału'),
('Partes de la Casa','Części domu','la casa','dom'),
('Partes de la Casa','Części domu','el piso','mieszkanie / piętro'),
('Partes de la Casa','Części domu','el apartamento','apartament'),
('Partes de la Casa','Części domu','el edificio','budynek'),
('Partes de la Casa','Części domu','la fachada','fasada / elewacja'),
('Partes de la Casa','Części domu','el tejado','dach'),
('Partes de la Casa','Części domu','la chimenea','komin / kominek'),
('Partes de la Casa','Części domu','la pared','ściana'),
('Partes de la Casa','Części domu','el suelo','podłoga / ziemia'),
('Partes de la Casa','Części domu','el techo','sufit'),
('Partes de la Casa','Części domu','la puerta','drzwi'),
('Partes de la Casa','Części domu','la ventana','okno'),
('Partes de la Casa','Części domu','el cristal','szyba'),
('Partes de la Casa','Części domu','la persiana','roleta / żaluzja'),
('Partes de la Casa','Części domu','el balcón','balkon'),
('Partes de la Casa','Części domu','la terraza','taras'),
('Partes de la Casa','Części domu','el pasillo','korytarz'),
('Partes de la Casa','Części domu','el recibidor','przedpokój'),
('Partes de la Casa','Części domu','el salón','salon'),
('Partes de la Casa','Części domu','el comedor','jadalnia'),
('Partes de la Casa','Części domu','la cocina','kuchnia'),
('Partes de la Casa','Części domu','el dormitorio','sypialnia'),
('Partes de la Casa','Części domu','el baño','łazienka'),
('Partes de la Casa','Części domu','el aseo','toaleta (pomieszczenie)'),
('Partes de la Casa','Części domu','el sótano','piwnica'),
('Partes de la Casa','Części domu','el ático / la buhardilla','strych / poddasze'),
('Partes de la Casa','Części domu','el garaje','garaż'),
('Partes de la Casa','Części domu','el jardín','ogród'),
('Partes de la Casa','Części domu','el patio','dziedziniec / podwórko'),
('Partes de la Casa','Części domu','la escalera','schody'),
('Partes de la Casa','Części domu','el escalón','stopień'),
('Partes de la Casa','Części domu','el ascensor','winda'),
('Partes de la Casa','Części domu','el timbre','dzwonek'),
('Partes de la Casa','Części domu','la cerradura','zamek (w drzwiach)'),
('Partes de la Casa','Części domu','la llave','klucz'),
('Partes de la Casa','Części domu','la habitación','pokój'),
('Partes de la Casa','Części domu','el cuarto','pokój / pomieszczenie'),
('Partes de la Casa','Części domu','la despensa','spiżarnia'),
('Partes de la Casa','Części domu','el lavadero','pralnia (w domu)'),
('Partes de la Casa','Części domu','el trastero','schowek / graciarnia'),
('Partes de la Casa','Części domu','la valla','ogrodzenie / płot'),
('Partes de la Casa','Części domu','el porche','ganek'),
('Partes de la Casa','Części domu','la entrada','wejście'),
('Partes de la Casa','Części domu','la salida','wyjście'),
('Partes de la Casa','Części domu','la planta baja','parter'),
('Partes de la Casa','Części domu','el primer piso','pierwsze piętro'),
('Partes de la Casa','Części domu','la baldosa','płytka podłogowa / kafel'),
('Partes de la Casa','Części domu','el ladrillo','cegła'),
('Partes de la Casa','Części domu','el cimiento','fundament'),
('Partes de la Casa','Części domu','la viga','belka'),
('El Jardín','Ogród','el jardín','ogród'),
('El Jardín','Ogród','el césped','trawnik'),
('El Jardín','Ogród','la hierba','trawa'),
('El Jardín','Ogród','la planta','roślina'),
('El Jardín','Ogród','la flor','kwiat'),
('El Jardín','Ogród','la rosa','róża'),
('El Jardín','Ogród','el tulipán','tulipan'),
('El Jardín','Ogród','el clavel','goździk (kwiat)'),
('El Jardín','Ogród','la margarita','stokrotka'),
('El Jardín','Ogród','el arbusto','krzew'),
('El Jardín','Ogród','el árbol','drzewo'),
('El Jardín','Ogród','la rama','gałąź'),
('El Jardín','Ogród','la hoja','liść'),
('El Jardín','Ogród','la raíz','korzeń'),
('El Jardín','Ogród','la semilla','nasiono'),
('El Jardín','Ogród','la tierra','ziemia'),
('El Jardín','Ogród','el abono','nawóz'),
('El Jardín','Ogród','la maceta','doniczka'),
('El Jardín','Ogród','la regadera','konewka'),
('El Jardín','Ogród','la manguera','wąż ogrodowy'),
('El Jardín','Ogród','el cortacésped','kosiarka'),
('El Jardín','Ogród','las tijeras de podar','sekator'),
('El Jardín','Ogród','la pala','łopata'),
('El Jardín','Ogród','el rastrillo','grabie'),
('El Jardín','Ogród','la azada','motyka'),
('El Jardín','Ogród','la carretilla','taczka'),
('El Jardín','Ogród','el invernadero','szklarnia'),
('El Jardín','Ogród','el huerto','warzywniak / sad'),
('El Jardín','Ogród','la fuente','fontanna'),
('El Jardín','Ogród','el estanque','staw / oczko wodne'),
('El Jardín','Ogród','el camino','ścieżka'),
('El Jardín','Ogród','la valla','płot / ogrodzenie'),
('El Jardín','Ogród','el seto','żywopłot'),
('El Jardín','Ogród','la maleza / el abrojo','chwasty'),
('El Jardín','Ogród','regar','podlewać'),
('El Jardín','Ogród','plantar','sadzić'),
('El Jardín','Ogród','sembrar','siać'),
('El Jardín','Ogród','podar','przycinać (rośliny)'),
('El Jardín','Ogród','cavar','kopać'),
('El Jardín','Ogród','cortar el césped','kosić trawnik'),
('El Jardín','Ogród','crecer','rosnąć'),
('El Jardín','Ogród','florecer','kwitnąć'),
('El Jardín','Ogród','marchitarse','więdnąć'),
('El Jardín','Ogród','arrancar','wyrywać'),
('El Jardín','Ogród','cultivar','uprawiać'),
('El Jardín','Ogród','el jardinero','ogrodnik'),
('El Jardín','Ogród','la primavera','wiosna'),
('El Jardín','Ogród','el capullo','pąk'),
('El Jardín','Ogród','el polen','pyłek'),
('El Jardín','Ogród','la plaga','plaga / szkodniki'),
('El Baño','Łazienka','el baño','łazienka (z wanną/prysznicem)'),
('El Baño','Łazienka','el cuarto de baño','łazienka'),
('El Baño','Łazienka','el aseo','ubikacja (często bez prysznica)'),
('El Baño','Łazienka','la ducha','prysznic'),
('El Baño','Łazienka','la bañera','wanna'),
('El Baño','Łazienka','el lavabo','umywalka'),
('El Baño','Łazienka','el váter / el inodoro','muszla klozetowa / toaleta'),
('El Baño','Łazienka','el bidé','bidet'),
('El Baño','Łazienka','el grifo','kran'),
('El Baño','Łazienka','el desagüe','odpływ'),
('El Baño','Łazienka','el espejo','lustro'),
('El Baño','Łazienka','el azulejo','kafelek / glazura'),
('El Baño','Łazienka','la toalla','ręcznik'),
('El Baño','Łazienka','el albornoz','szlafrok'),
('El Baño','Łazienka','la alfombrilla','dywanik łazienkowy'),
('El Baño','Łazienka','la cortina de ducha','zasłona prysznicowa'),
('El Baño','Łazienka','la mampara','kabina prysznicowa / ścianka'),
('El Baño','Łazienka','el jabón','mydło'),
('El Baño','Łazienka','el champú','szampon'),
('El Baño','Łazienka','la esponja','gąbka'),
('El Baño','Łazienka','el papel higiénico','papier toaletowy'),
('El Baño','Łazienka','el cepillo de dientes','szczoteczka do zębów'),
('El Baño','Łazienka','la pasta de dientes','pasta do zębów'),
('El Baño','Łazienka','el enjuague bucal','płyn do płukania ust'),
('El Baño','Łazienka','el hilo dental','nić dentystyczna'),
('El Baño','Łazienka','el peine','grzebień'),
('El Baño','Łazienka','el cepillo','szczotka (np. do włosów)'),
('El Baño','Łazienka','el secador de pelo','suszarka do włosów'),
('El Baño','Łazienka','la cuchilla de afeitar','maszynka do golenia'),
('El Baño','Łazienka','la espuma de afeitar','pianka do golenia'),
('El Baño','Łazienka','la loción','balsam'),
('El Baño','Łazienka','el desodorante','dezodorant'),
('El Baño','Łazienka','la báscula','waga (łazienkowa)'),
('El Baño','Łazienka','el cubo de basura','kosz na śmieci'),
('El Baño','Łazienka','tirar de la cadena','spuszczać wodę (w toalecie)'),
('El Baño','Łazienka','lavarse','myć się'),
('El Baño','Łazienka','ducharse','brać prysznic'),
('El Baño','Łazienka','bañarse','kąpać się'),
('El Baño','Łazienka','secarse','wycierać się / suszyć się'),
('El Baño','Łazienka','peinarse','czesać się'),
('El Baño','Łazienka','afeitarse','golić się'),
('El Baño','Łazienka','maquillarse','malować się'),
('El Baño','Łazienka','desmaquillarse','zmywać makijaż'),
('El Baño','Łazienka','la higiene','higiena'),
('El Baño','Łazienka','limpio','czysty'),
('El Baño','Łazienka','sucio','brudny'),
('El Baño','Łazienka','el agua caliente','gorąca woda'),
('El Baño','Łazienka','el agua fría','zimna woda'),
('El Baño','Łazienka','el fontanero','hydraulik'),
('El Baño','Łazienka','el tapón','korek (do wanny/zlewu)');
