insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('La Música','Muzyka','la música','muzyka'),
('La Música','Muzyka','la canción','piosenka'),
('La Música','Muzyka','el cantante / la cantante','piosenkarz / piosenkarka'),
('La Música','Muzyka','el instrumento','instrument'),
('La Música','Muzyka','la guitarra','gitara'),
('La Música','Muzyka','el piano','pianino'),
('La Música','Muzyka','el violín','skrzypce'),
('La Música','Muzyka','la batería','perkusja'),
('La Música','Muzyka','el bajo','gitara basowa'),
('La Música','Muzyka','la banda / el grupo','zespół (muzyczny)'),
('La Música','Muzyka','el concierto','koncert'),
('La Música','Muzyka','el escenario','scena'),
('La Música','Muzyka','el micrófono','mikrofon'),
('La Música','Muzyka','el ritmo','rytm'),
('La Música','Muzyka','la melodía','melodia'),
('La Música','Muzyka','la letra','tekst (piosenki)'),
('La Música','Muzyka','el disco','płyta'),
('La Música','Muzyka','el álbum','album'),
('La Música','Muzyka','los auriculares','słuchawki'),
('La Música','Muzyka','el altavoz','głośnik'),
('La Música','Muzyka','la nota','nuta'),
('La Música','Muzyka','el acorde','akord'),
('La Música','Muzyka','el compositor','kompozytor'),
('La Música','Muzyka','tocar (un instrumento)','grać (na instrumencie)'),
('La Música','Muzyka','cantar','śpiewać'),
('La Música','Muzyka','escuchar','słuchać'),
('La Música','Muzyka','el ensayo','próba'),
('La Música','Muzyka','la orquesta','orkiestra'),
('La Música','Muzyka','el coro','chór'),
('La Música','Muzyka','la música clásica','muzyka klasyczna'),
('La Música','Muzyka','el rock','rock'),
('La Música','Muzyka','el pop','pop'),
('La Música','Muzyka','el jazz','jazz'),
('La Música','Muzyka','el flamenco','flamenco'),
('La Música','Muzyka','el reguetón','reggaeton'),
('La Música','Muzyka','la salsa','salsa (taniec/muzyka)'),
('La Música','Muzyka','la partitura','partytura / zapis nutowy'),
('La Música','Muzyka','el afinador','stroik / tuner'),
('La Música','Muzyka','el amplificador','wzmacniacz'),
('La Música','Muzyka','la cuerda','struna'),
('La Música','Muzyka','el teclado','keyboard / instrument klawiszowy'),
('La Música','Muzyka','la trompeta','trąbka'),
('La Música','Muzyka','la flauta','flet'),
('La Música','Muzyka','el saxofón','saksofon'),
('La Música','Muzyka','el DJ','DJ'),
('La Música','Muzyka','el festival','festiwal'),
('La Música','Muzyka','la entrada','bilet wstępu'),
('La Música','Muzyka','el público','publiczność'),
('La Música','Muzyka','grabar','nagrywać'),
('La Música','Muzyka','el sonido','dźwięk'),
('El Cine','Kino','el cine','kino (budynek i sztuka)'),
('El Cine','Kino','la película','film'),
('El Cine','Kino','el actor','aktor'),
('El Cine','Kino','la actriz','aktorka'),
('El Cine','Kino','el director','reżyser'),
('El Cine','Kino','el guion','scenariusz'),
('El Cine','Kino','el guionista','scenarzysta'),
('El Cine','Kino','la pantalla','ekran'),
('El Cine','Kino','la entrada','bilet'),
('El Cine','Kino','la taquilla','kasa biletowa'),
('El Cine','Kino','las palomitas','popcorn'),
('El Cine','Kino','el asiento / la butaca','miejsce / fotel'),
('El Cine','Kino','la fila','rząd'),
('El Cine','Kino','la cartelera','repertuar kinowy'),
('El Cine','Kino','el estreno','premiera'),
('El Cine','Kino','el tráiler','zwiastun'),
('El Cine','Kino','el género','gatunek'),
('El Cine','Kino','la comedia','komedia'),
('El Cine','Kino','el drama','dramat'),
('El Cine','Kino','la película de terror','horror'),
('El Cine','Kino','la película de acción','film akcji'),
('El Cine','Kino','la ciencia ficción','science fiction'),
('El Cine','Kino','el documental','film dokumentalny'),
('El Cine','Kino','la animación','animacja'),
('El Cine','Kino','el personaje','postać'),
('El Cine','Kino','el protagonista','główny bohater'),
('El Cine','Kino','el antagonista','antagonista / czarny charakter'),
('El Cine','Kino','la escena','scena (w filmie)'),
('El Cine','Kino','el rodaje','kręcenie filmu / zdjęcia'),
('El Cine','Kino','la cámara','kamera'),
('El Cine','Kino','la claqueta','klaps'),
('El Cine','Kino','el premio','nagroda'),
('El Cine','Kino','el festival de cine','festiwal filmowy'),
('El Cine','Kino','el Óscar','Oscar (nagroda)'),
('El Cine','Kino','la banda sonora','ścieżka dźwiękowa'),
('El Cine','Kino','el doblaje','dubbing'),
('El Cine','Kino','los subtítulos','napisy'),
('El Cine','Kino','el espectador','widz'),
('El Cine','Kino','el crítico de cine','krytyk filmowy'),
('El Cine','Kino','la reseña','recenzja'),
('El Cine','Kino','los efectos especiales','efekty specjalne'),
('El Cine','Kino','el maquillaje','charakteryzacja / makijaż'),
('El Cine','Kino','el vestuario','kostiumy'),
('El Cine','Kino','la pantalla grande','wielki ekran'),
('El Cine','Kino','un éxito de taquilla','hit kinowy'),
('El Cine','Kino','dirigir','reżyserować'),
('El Cine','Kino','actuar','grać (rolę)'),
('El Cine','Kino','proyectar','wyświetlać'),
('El Cine','Kino','el plano','ujęcie'),
('El Cine','Kino','el cortometraje','film krótkometrażowy'),
('La Literatura','Literatura','la literatura','literatura'),
('La Literatura','Literatura','el libro','książka'),
('La Literatura','Literatura','el autor / la autora','autor / autorka'),
('La Literatura','Literatura','el escritor / la escritora','pisarz / pisarka'),
('La Literatura','Literatura','el poeta / la poetisa','poeta / poetka'),
('La Literatura','Literatura','el poema','wiersz'),
('La Literatura','Literatura','la poesía','poezja'),
('La Literatura','Literatura','la novela','powieść'),
('La Literatura','Literatura','el cuento','opowiadanie / bajka'),
('La Literatura','Literatura','el ensayo','esej'),
('La Literatura','Literatura','la página','strona'),
('La Literatura','Literatura','el capítulo','rozdział'),
('La Literatura','Literatura','la portada','okładka (przednia)'),
('La Literatura','Literatura','la contraportada','tylna okładka'),
('La Literatura','Literatura','el índice','spis treści'),
('La Literatura','Literatura','el título','tytuł'),
('La Literatura','Literatura','la editorial','wydawnictwo'),
('La Literatura','Literatura','la librería','księgarnia'),
('La Literatura','Literatura','la biblioteca','biblioteka'),
('La Literatura','Literatura','leer','czytać'),
('La Literatura','Literatura','escribir','pisać'),
('La Literatura','Literatura','publicar','publikować / wydawać'),
('La Literatura','Literatura','imprimir','drukować'),
('La Literatura','Literatura','el lector / la lectora','czytelnik / czytelniczka'),
('La Literatura','Literatura','el personaje','postać'),
('La Literatura','Literatura','el protagonista','bohater główny'),
('La Literatura','Literatura','el narrador','narrator'),
('La Literatura','Literatura','la trama','fabuła'),
('La Literatura','Literatura','el argumento','streszczenie fabuły'),
('La Literatura','Literatura','el clímax','punkt kulminacyjny'),
('La Literatura','Literatura','el desenlace','zakończenie / rozwiązanie akcji'),
('La Literatura','Literatura','el género','gatunek literacki'),
('La Literatura','Literatura','la ficción','fikcja literacka'),
('La Literatura','Literatura','la biografía','biografia'),
('La Literatura','Literatura','la autobiografía','autobiografia'),
('La Literatura','Literatura','la fantasía','fantasy'),
('La Literatura','Literatura','el misterio','kryminał / tajemnica'),
('La Literatura','Literatura','el romance','romans'),
('La Literatura','Literatura','el cómic','komiks'),
('La Literatura','Literatura','la revista','czasopismo / magazyn'),
('La Literatura','Literatura','el periódico','gazeta'),
('La Literatura','Literatura','el artículo','artykuł'),
('La Literatura','Literatura','la estantería','regał na książki'),
('La Literatura','Literatura','el marcapáginas','zakładka do książki'),
('La Literatura','Literatura','la encuadernación','oprawa'),
('La Literatura','Literatura','el prólogo','prolog / wstęp'),
('La Literatura','Literatura','el epílogo','epilog'),
('La Literatura','Literatura','la traducción','tłumaczenie / przekład'),
('La Literatura','Literatura','el traductor / la traductora','tłumacz / tłumaczka'),
('La Literatura','Literatura','el manuscrito','manuskrypt / rękopis'),
('La Política','Polityka','la política','polityka'),
('La Política','Polityka','el político / la política','polityk'),
('La Política','Polityka','el gobierno','rząd'),
('La Política','Polityka','el presidente / la presidenta','prezydent'),
('La Política','Polityka','el ministro / la ministra','minister'),
('La Política','Polityka','el alcalde / la alcaldesa','burmistrz / prezydent miasta'),
('La Política','Polityka','el parlamento','parlament'),
('La Política','Polityka','el congreso','kongres'),
('La Política','Polityka','el senado','senat'),
('La Política','Polityka','el partido político','partia polityczna'),
('La Política','Polityka','la elección','wybory'),
('La Política','Polityka','el voto','głos (wyborczy)'),
('La Política','Polityka','votar','głosować'),
('La Política','Polityka','la urna','urna wyborcza'),
('La Política','Polityka','la campaña','kampania'),
('La Política','Polityka','el candidato','kandydat'),
('La Política','Polityka','la democracia','demokracja'),
('La Política','Polityka','la dictadura','dyktatura'),
('La Política','Polityka','la república','republika'),
('La Política','Polityka','la monarquía','monarchia'),
('La Política','Polityka','el rey','król'),
('La Política','Polityka','la reina','królowa'),
('La Política','Polityka','la ley','ustawa / prawo'),
('La Política','Polityka','la constitución','konstytucja'),
('La Política','Polityka','el derecho','prawo (ogół norm)'),
('La Política','Polityka','el ciudadano','obywatel'),
('La Política','Polityka','el debate','debata'),
('La Política','Polityka','el discurso','przemówienie'),
('La Política','Polityka','la manifestación','manifestacja / demonstracja'),
('La Política','Polityka','la huelga','strajk'),
('La Política','Polityka','la protesta','protest'),
('La Política','Polityka','la oposición','opozycja'),
('La Política','Polityka','la mayoría','większość'),
('La Política','Polityka','la minoría','mniejszość'),
('La Política','Polityka','la corrupción','korupcja'),
('La Política','Polityka','la crisis','kryzys'),
('La Política','Polityka','la reforma','reforma'),
('La Política','Polityka','el impuesto','podatek'),
('La Política','Polityka','el presupuesto','budżet'),
('La Política','Polityka','el estado','państwo'),
('La Política','Polityka','la nación','naród'),
('La Política','Polityka','la frontera','granica'),
('La Política','Polityka','la embajada','ambasada'),
('La Política','Polityka','el embajador','ambasador'),
('La Política','Polityka','el tratado','traktat / układ'),
('La Política','Polityka','la paz','pokój (stan bez wojny)'),
('La Política','Polityka','la guerra','wojna'),
('La Política','Polityka','la independencia','niepodległość'),
('La Política','Polityka','el poder','władza'),
('La Política','Polityka','el ministerio','ministerstwo');
