insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Asignaturas Escolares','Przedmioty szkolne','las matemáticas','matematyka'),
('Asignaturas Escolares','Przedmioty szkolne','la lengua española','język hiszpański'),
('Asignaturas Escolares','Przedmioty szkolne','la literatura','literatura'),
('Asignaturas Escolares','Przedmioty szkolne','la historia','historia'),
('Asignaturas Escolares','Przedmioty szkolne','la geografía','geografia'),
('Asignaturas Escolares','Przedmioty szkolne','la física','fizyka'),
('Asignaturas Escolares','Przedmioty szkolne','la química','chemia'),
('Asignaturas Escolares','Przedmioty szkolne','la biología','biologia'),
('Asignaturas Escolares','Przedmioty szkolne','la geología','geologia'),
('Asignaturas Escolares','Przedmioty szkolne','el idioma extranjero','język obcy'),
('Asignaturas Escolares','Przedmioty szkolne','el inglés','język angielski'),
('Asignaturas Escolares','Przedmioty szkolne','el francés','język francuski'),
('Asignaturas Escolares','Przedmioty szkolne','el alemán','język niemiecki'),
('Asignaturas Escolares','Przedmioty szkolne','el latín','łacina'),
('Asignaturas Escolares','Przedmioty szkolne','el griego antiguo','greka klasyczna'),
('Asignaturas Escolares','Przedmioty szkolne','la informática','informatyka'),
('Asignaturas Escolares','Przedmioty szkolne','la tecnología','technologia / technika'),
('Asignaturas Escolares','Przedmioty szkolne','la educación física','wychowanie fizyczne (WF)'),
('Asignaturas Escolares','Przedmioty szkolne','la música','muzyka'),
('Asignaturas Escolares','Przedmioty szkolne','el arte','sztuka'),
('Asignaturas Escolares','Przedmioty szkolne','la educación plástica y visual','plastyka'),
('Asignaturas Escolares','Przedmioty szkolne','la filosofía','filozofia'),
('Asignaturas Escolares','Przedmioty szkolne','la economía','ekonomia'),
('Asignaturas Escolares','Przedmioty szkolne','el dibujo técnico','rysunek techniczny'),
('Asignaturas Escolares','Przedmioty szkolne','la religión','religios'),
('Asignaturas Escolares','Przedmioty szkolne','la ética','etyka'),
('Asignaturas Escolares','Przedmioty szkolne','la educación cívica','wos / wiedza o społeczeństwie'),
('Asignaturas Escolares','Przedmioty szkolne','las ciencias sociales','nauki społeczne'),
('Asignaturas Escolares','Przedmioty szkolne','las ciencias naturales','przyroda / nauki przyrodnicze'),
('Asignaturas Escolares','Przedmioty szkolne','el taller','warsztat'),
('Asignaturas Escolares','Przedmioty szkolne','el laboratorio','laboratorium'),
('Asignaturas Escolares','Przedmioty szkolne','el deporte','sport'),
('Asignaturas Escolares','Przedmioty szkolne','el teatro','teatr'),
('Asignaturas Escolares','Przedmioty szkolne','el coro','chór'),
('Asignaturas Escolares','Przedmioty szkolne','la oratoria','retoryka'),
('Asignaturas Escolares','Przedmioty szkolne','la programación','programowanie'),
('Asignaturas Escolares','Przedmioty szkolne','la robótica','robotyka'),
('Asignaturas Escolares','Przedmioty szkolne','la contabilidad','rachunkowość'),
('Asignaturas Escolares','Przedmioty szkolne','la sociología','socjologia'),
('Asignaturas Escolares','Przedmioty szkolne','la psicología','psychologia'),
('Asignaturas Escolares','Przedmioty szkolne','la ecología','ekologia'),
('Asignaturas Escolares','Przedmioty szkolne','la astronomía','astronomia'),
('Asignaturas Escolares','Przedmioty szkolne','la estadística','statystyka'),
('Asignaturas Escolares','Przedmioty szkolne','la asignatura obligatoria','przedmiot obowiązkowy'),
('Asignaturas Escolares','Przedmioty szkolne','la asignatura optativa','przedmiot do wyboru'),
('Asignaturas Escolares','Przedmioty szkolne','el currículo','program nauczania'),
('Asignaturas Escolares','Przedmioty szkolne','el temario','zakres materiału'),
('Asignaturas Escolares','Przedmioty szkolne','la optativa','przedmiot fakultatywny'),
('Asignaturas Escolares','Przedmioty szkolne','la troncal','przedmiot główny / kluczowy'),
('Material Escolar','Przybory szkolne','el material escolar','przybory szkolne'),
('Material Escolar','Przybory szkolne','el bolígrafo','długopis'),
('Material Escolar','Przybory szkolne','el lápiz','ołówek'),
('Material Escolar','Przybory szkolne','el portaminas','ołówek automatyczny'),
('Material Escolar','Przybory szkolne','la goma de borrar','gumka do ścierania'),
('Material Escolar','Przybory szkolne','el sacapuntas','tempérka / temperówka'),
('Material Escolar','Przybory szkolne','la regla','linijka'),
('Material Escolar','Przybory szkolne','la escuadra','ekierka'),
('Material Escolar','Przybory szkolne','el cartabón','ekierka (trójkątna)'),
('Material Escolar','Przybory szkolne','el transportador de ángulos','kątomierz'),
('Material Escolar','Przybory szkolne','el compás','cyrkiel'),
('Material Escolar','Przybory szkolne','el cuaderno','zeszyt'),
('Material Escolar','Przybory szkolne','la libreta','notatnik / zeszyt'),
('Material Escolar','Przybory szkolne','el bloc de notas','blok rysunkowy / notatnik'),
('Material Escolar','Przybory szkolne','el papel','papier'),
('Material Escolar','Przybory szkolne','la carpeta','teczka'),
('Material Escolar','Przybory szkolne','el archivador','segregator'),
('Material Escolar','Przybory szkolne','los folios','kartki papieru (A4)'),
('Material Escolar','Przybory szkolne','el libro de texto','podręcznik'),
('Material Escolar','Przybory szkolne','el diccionario','słownik'),
('Material Escolar','Przybory szkolne','la mochila','plecak'),
('Material Escolar','Przybory szkolne','el estuche','piórnik'),
('Material Escolar','Przybory szkolne','las tijeras','nożyczki'),
('Material Escolar','Przybory szkolne','el pegamento','klej'),
('Material Escolar','Przybory szkolne','la barra de glue','klej w sztyfcie'),
('Material Escolar','Przybory szkolne','la cinta adhesiva','taśma klejąca'),
('Material Escolar','Przybory szkolne','las ceras','kredki świecowe'),
('Material Escolar','Przybory szkolne','los lápices de colores','kredki ołówkowe'),
('Material Escolar','Przybory szkolne','los rotuladores','mazaki / pisaki'),
('Material Escolar','Przybory szkolne','las acuarelas','farby akwarelowe'),
('Material Escolar','Przybory szkolne','la témpera','farby plakatowe / tempery'),
('Material Escolar','Przybory szkolne','el pincel','pędzel'),
('Material Escolar','Przybory szkolne','la paleta','paleta do farb'),
('Material Escolar','Przybory szkolne','el lienzo','płótno'),
('Material Escolar','Przybory szkolne','la plastelina','plastelina'),
('Material Escolar','Przybory szkolne','el corrector líquido','korektor w płynie'),
('Material Escolar','Przybory szkolne','la grapadora','zszywacze'),
('Material Escolar','Przybory szkolne','las grapas','zszywki'),
('Material Escolar','Przybory szkolne','el clip','spinacz biurowy'),
('Material Escolar','Przybory szkolne','la perforadora','dziurkacz'),
('Material Escolar','Przybory szkolne','la calculadora','kalkulator'),
('Material Escolar','Przybory szkolne','el ordenador portátil','laptop szkolny'),
('Material Escolar','Przybory szkolne','la tableta','tablet'),
('Material Escolar','Przybory szkolne','los auriculares','słuchawki'),
('Material Escolar','Przybory szkolne','la pizarra blanca','mała tablica suchościeralna'),
('Material Escolar','Przybory szkolne','el rotulador de pizarra','marker do tablic'),
('Material Escolar','Przybory szkolne','la agenda escolar','dzienniczek / planner szkolny'),
('Material Escolar','Przybory szkolne','el marcapáginas','zakładka do książki'),
('Material Escolar','Przybory szkolne','la cinta correctora','korektor w taśmie'),
('Material Escolar','Przybory szkolne','el portafolios','teczka na dokumenty'),
('Exámenes y Notas','Egzaminy i oceny','el examen','egzamin'),
('Exámenes y Notas','Egzaminy i oceny','la prueba','test / sprawdzian'),
('Exámenes y Notas','Egzaminy i oceny','el control','kartkówka / test kontrolny'),
('Exámenes y Notas','Egzaminy i oceny','el examen parcial','kolokwium / egzamin cząstkowy'),
('Exámenes y Notas','Egzaminy i oceny','el examen final','egzamin końcowy'),
('Exámenes y Notas','Egzaminy i oceny','la nota','ocena'),
('Exámenes y Notas','Egzaminy i oceny','la calificación','ocena / stopień'),
('Exámenes y Notas','Egzaminy i oceny','el sobresaliente','celujący (szóstka)'),
('Exámenes y Notas','Egzaminy i oceny','el notable','bardzo dobry / dobry (czwórka/piątka)'),
('Exámenes y Notas','Egzaminy i oceny','el bien','dostateczny (trójka)'),
('Exámenes y Notas','Egzaminy i oceny','el aprobado','dostateczny / zdany (trójka)'),
('Exámenes y Notas','Egzaminy i oceny','el suspenso','niedostateczny / oblany (jedynka/dwójka)'),
('Exámenes y Notas','Egzaminy i oceny','aprobar','zdać (egzamin)'),
('Exámenes y Notas','Egzaminy i oceny','suspender','oblać / nie zdać'),
('Exámenes y Notas','Egzaminy i oceny','sacar buena nota','dostać dobrą ocenę'),
('Exámenes y Notas','Egzaminy i oceny','sacar mala nota','dostać złą ocenę'),
('Exámenes y Notas','Egzaminy i oceny','el boletín de notas','świadectwo / karta ocen'),
('Exámenes y Notas','Egzaminy i oceny','el suspensso','niedostateczny'),
('Exámenes y Notas','Egzaminy i oceny','copiar','ściągać (na egzaminie)'),
('Exámenes y Notas','Egzaminy i oceny','la chuleta','ściągawka'),
('Exámenes y Notas','Egzaminy i oceny','suspender por copia','zostać przyłapanym na ściąganiu'),
('Exámenes y Notas','Egzaminy i oceny','el profesor','egzaminator / nauczyciel'),
('Exámenes y Notas','Egzaminy i oceny','el tribunal','komisja egzaminacyjna'),
('Exámenes y Notas','Egzaminy i oceny','la convocatoria','termin egzaminu'),
('Exámenes y Notas','Egzaminy i oceny','la nota media','średnia ocen'),
('Exámenes y Notas','Egzaminy i oceny','el suspenso','poprawka (warunek)'),
('Exámenes y Notas','Egzaminy i oceny','el examen de recuperación','egzamin poprawkowy'),
('Exámenes y Notas','Egzaminy i oceny','recuperar','poprawić ocenę'),
('Exámenes y Notas','Egzaminy i oceny','estudiar','uczyć się'),
('Exámenes y Notas','Egzaminy i oceny','repasar','powtarzać materiał'),
('Exámenes y Notas','Egzaminy i oceny','el repaso','powtórka'),
('Exámenes y Notas','Egzaminy i oceny','el temario','zakres materiału'),
('Exámenes y Notas','Egzaminy i oceny','memorizar','zapamiętywać / uczyć się na pamięć'),
('Exámenes y Notas','Egzaminy i oceny','entregar el examen','oddać egzamin'),
('Exámenes y Notas','Egzaminy i oceny','terminar el examen','skończyć egzamin'),
('Exámenes y Notas','Egzaminy i oceny','el tiempo','czas (na egzaminie)'),
('Exámenes y Notas','Egzaminy i oceny','la pregunta','pytanie'),
('Exámenes y Notas','Egzaminy i oceny','la respuesta','odpowiedź'),
('Exámenes y Notas','Egzaminy i oceny','responder','odpowiadać'),
('Exámenes y Notas','Egzaminy i oceny','acertar','trafić / odpowiedzieć poprawnie'),
('Exámenes y Notas','Egzaminy i oceny','fallar','pomylić się / popełnić błąd'),
('Exámenes y Notas','Egzaminy i oceny','el error','błąd'),
('Exámenes y Notas','Egzaminy i oceny','la corrección','poprawianie / korekta'),
('Exámenes y Notas','Egzaminy i oceny','la nota numérica','ocena cyfrowa'),
('Exámenes y Notas','Egzaminy i oceny','la evaluación','ocena / ewaluación'),
('Exámenes y Notas','Egzaminy i oceny','el test psicotécnico','test psychotechniczny'),
('Exámenes y Notas','Egzaminy i oceny','la prueba de acceso','egzamin wstępny'),
('Exámenes y Notas','Egzaminy i oceny','el resultado','wynik'),
('Exámenes y Notas','Egzaminy i oceny','el certificado','certyfikat / zaświadczenie'),
('Exámenes y Notas','Egzaminy i oceny','el éxito','sukces'),
('Aficiones','Zainteresowania','la afición','zainteresowanie / hobby'),
('Aficiones','Zainteresowania','el pasatiempo','hobby / czas wolny'),
('Aficiones','Zainteresowania','el hobby','hobby'),
('Aficiones','Zainteresowania','disfrutar','cieszyć się'),
('Aficiones','Zainteresowania','entretenerse','zabawiać się / spędzać czas'),
('Aficiones','Zainteresowania','el oceno','czas wolny'),
('Aficiones','Zainteresowania','leer','czytać'),
('Aficiones','Zainteresowania','escribir','pisać'),
('Aficiones','Zainteresowania','fotografiar','fotografować'),
('Aficiones','Zainteresowania','pintar','malować'),
('Aficiones','Zainteresowania','dibujar','rysować'),
('Aficiones','Zainteresowania','tocar un instrumento','grać na instrumencie'),
('Aficiones','Zainteresowania','cantar','śpiewać'),
('Aficiones','Zainteresowania','bailar','tańczyć'),
('Aficiones','Zainteresowania','cocinar','gotować'),
('Aficiones','Zainteresowania','hornear','piec (np. ciasta)'),
('Aficiones','Zainteresowania','viajar','podróżować'),
('Aficiones','Zainteresowania','acampar','kempingować'),
('Aficiones','Zainteresowania','senderismo','turystyka piesza / trekking'),
('Aficiones','Zainteresowania','la jardinería','ogrodnictwo'),
('Aficiones','Zainteresowania','el bricolaje','majsterkowanie'),
('Aficiones','Zainteresowania','la costura','szycie'),
('Aficiones','Zainteresowania','tejer','robić na drutach'),
('Aficiones','Zainteresowania','coleccionar','kolekcjonować'),
('Aficiones','Zainteresowania','los videojuegos','gry wideo'),
('Aficiones','Zainteresowania','el ajedrez','szachy'),
('Aficiones','Zainteresowania','los rompecabezas','puzzle / łamigłówki'),
('Aficiones','Zainteresowania','las manualidades','prace ręczne / handmade'),
('Aficiones','Zainteresowania','pescar','łowić ryby'),
('Aficiones','Zainteresowania','cazar','polować'),
('Aficiones','Zainteresowania','patinar','jeździć na łyżwach / rolkach'),
('Aficiones','Zainteresowania','montar en bicicleta','jeździć na rowerze'),
('Aficiones','Zainteresowania','nadar','pływać'),
('Aficiones','Zainteresowania','correr','biegać'),
('Aficiones','Zainteresowania','hacer yoga','uprawiać jogę'),
('Aficiones','Zainteresowania','meditar','medytować'),
('Aficiones','Zainteresowania','el cine','kino (oglądanie filmów)'),
('Aficiones','Zainteresowania','el teatro','teatr'),
('Aficiones','Zainteresowania','los conciertos','koncerty'),
('Aficiones','Zainteresowania','los museos','muzea'),
('Aficiones','Zainteresowania','el voluntariado','wolontariat'),
('Aficiones','Zainteresowania','aprender idiomas','uczyć się języków'),
('Aficiones','Zainteresowania','la astronomia','astronomia (jako hobby)'),
('Aficiones','Zainteresowania','observar aves','obserwowanie ptaków'),
('Aficiones','Zainteresowania','la cerámica','ceramika'),
('Aficiones','Zainteresowania','la carpintería','stolarstwo'),
('Aficiones','Zainteresowania','el diseño','projektowanie'),
('Aficiones','Zainteresowania','la cata de vinos','degustacja wina'),
('Aficiones','Zainteresowania','apasionante','pasjonujący'),
('Aficiones','Zainteresowania','divertido','zabawny / przyjemny'),
('Manualidades','Rękodzieło','las manualidades','rękodzieło / prace ręczne');
