insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Los Verbos de Acción','Czasowniki akcji','hacer','robić'),
('Los Verbos de Acción','Czasowniki akcji','ir','iść / jechać'),
('Los Verbos de Acción','Czasowniki akcji','venir','przychodzić / przyjeżdżać'),
('Los Verbos de Acción','Czasowniki akcji','correr','biegać'),
('Los Verbos de Acción','Czasowniki akcji','caminar / andar','chodzić / spacerować'),
('Los Verbos de Acción','Czasowniki akcji','saltar','skakać'),
('Los Verbos de Acción','Czasowniki akcji','nadar','pływać'),
('Los Verbos de Acción','Czasowniki akcji','volar','latać'),
('Los Verbos de Acción','Czasowniki akcji','caer','spadać / upadać'),
('Los Verbos de Acción','Czasowniki akcji','lanzar','rzucać'),
('Los Verbos de Acción','Czasowniki akcji','atrapar','łapać'),
('Los Verbos de Acción','Czasowniki akcji','golpear','uderzać'),
('Los Verbos de Acción','Czasowniki akcji','empujar','pchać'),
('Los Verbos de Acción','Czasowniki akcji','tirar','ciągnąć / rzucać'),
('Los Verbos de Acción','Czasowniki akcji','levantar','podnosić'),
('Los Verbos de Acción','Czasowniki akcji','llevar','nieść / nosić / zabierać'),
('Los Verbos de Acción','Czasowniki akcji','traer','przynosić'),
('Los Verbos de Acción','Czasowniki akcji','abrir','otwierać'),
('Los Verbos de Acción','Czasowniki akcji','cerrar','zamykać'),
('Los Verbos de Acción','Czasowniki akcji','romper','psuć / łamać'),
('Los Verbos de Acción','Czasowniki akcji','arreglar','naprawiać'),
('Los Verbos de Acción','Czasowniki akcji','cortar','ciąć / kroić'),
('Los Verbos de Acción','Czasowniki akcji','pegar','przyklejać / uderzać'),
('Los Verbos de Acción','Czasowniki akcji','buscar','szukać'),
('Los Verbos de Acción','Czasowniki akcji','encontrar','znajdować'),
('Los Verbos de Acción','Czasowniki akcji','esconder','chować / ukrywać'),
('Los Verbos de Acción','Czasowniki akcji','dar','dawać'),
('Los Verbos de Acción','Czasowniki akcji','recibir','otrzymywać'),
('Los Verbos de Acción','Czasowniki akcji','coger / tomar','brać / chwytać'),
('Los Verbos de Acción','Czasowniki akcji','poner','kłaść / umieszczać'),
('Los Verbos de Acción','Czasowniki akcji','quitar','zdejmować / zabierać'),
('Los Verbos de Acción','Czasowniki akcji','subir','wchodzić (pod górę) / wsiadać'),
('Los Verbos de Acción','Czasowniki akcji','bajar','schodzić (w dół) / wysiadać'),
('Los Verbos de Acción','Czasowniki akcji','entrar','wchodzić'),
('Los Verbos de Acción','Czasowniki akcji','salir','wychodzić'),
('Los Verbos de Acción','Czasowniki akcji','escapar','uciekać'),
('Los Verbos de Acción','Czasowniki akcji','perseguir','gonić / ścigać'),
('Los Verbos de Acción','Czasowniki akcji','luchar','walczyć'),
('Los Verbos de Acción','Czasowniki akcji','ganar','wygrywać'),
('Los Verbos de Acción','Czasowniki akcji','perder','przegrywać / gubić'),
('Los Verbos de Acción','Czasowniki akcji','construir','budować'),
('Los Verbos de Acción','Czasowniki akcji','destruir','niszczyć'),
('Los Verbos de Acción','Czasowniki akcji','limpiar','czyścić / sprzątać'),
('Los Verbos de Acción','Czasowniki akcji','ensuciar','brudzić'),
('Los Verbos de Acción','Czasowniki akcji','lavar','myć / prać'),
('Los Verbos de Acción','Czasowniki akcji','secar','suszyć / wycierać'),
('Los Verbos de Acción','Czasowniki akcji','cocinar','gotować'),
('Los Verbos de Acción','Czasowniki akcji','comer','jeść'),
('Los Verbos de Acción','Czasowniki akcji','beber','pić'),
('Los Verbos de Acción','Czasowniki akcji','dormir','spać'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','simpático','sympatyczny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','antipático','niesympatyczny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','amable','uprzejmy / miły'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','grosero','niegrzeczny / grubiański'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','educado','wychowany'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','maleducado','niewychowany'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','inteligente','inteligentny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','tonto','głupi'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','listo','bystry / gotowy'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','trabajador','pracowity'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','perezoso / vago','leniwy'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','valiente','odważny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','cobarde','tchórzliwy'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','tímido','nieśmiały'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','extrovertido','ekstrawertyczny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','introvertido','introwertyczny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','generoso','hojny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','egoísta','egoistyczny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','honesto','uczciwy'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','mentiroso','kłamliwy / kłamca'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','sincero','szczery'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','hipócrita','hipokryta'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','alegre','radosny / wesoły'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','triste','smutny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','divertido','zabawny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','aburrido','nudny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','paciente','cierpliwy'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','impaciente','niecierpliwy'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','tranquilo','spokojny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','nervioso','nerwowy'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','optimista','optymistyczny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','pesimista','pesymistyczny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','orgulloso','dumny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','humilde','pokorny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','ambicioso','ambitny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','modesto','skromny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','creativo','kreatywny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','curioso','ciekawy (świata)'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','responsable','odpowiedzialny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','irresponsable','nieodpowiedzialny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','puntual','punktualny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','impuntual','niepunktualny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','tolerante','tolerancyjny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','intolerante','nietolerancyjny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','leal','lojalny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','desleal','nielojalny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','fiel','wierny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','infiel','niewierny'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','cariñoso','czuły'),
('Los Adjetivos de Personalidad','Przymiotniki osobowości','frío','chłodny (w obyciu)'),
('En el Restaurante','W restauracji','el restaurante','restauracja'),
('En el Restaurante','W restauracji','el menú','menu'),
('En el Restaurante','W restauracji','la carta','karta dań'),
('En el Restaurante','W restauracji','el camarero','kelner'),
('En el Restaurante','W restauracji','la camarera','kelnerka'),
('En el Restaurante','W restauracji','el cliente','klient'),
('En el Restaurante','W restauracji','la mesa','stół'),
('En el Restaurante','W restauracji','la silla','krzesło'),
('En el Restaurante','W restauracji','la reserva','rezerwacja'),
('En el Restaurante','W restauracji','reservar','rezerwować'),
('En el Restaurante','W restauracji','pedir','zamawiać / prosić'),
('En el Restaurante','W restauracji','la cuenta','rachunek'),
('En el Restaurante','W restauracji','la propina','napiwek'),
('En el Restaurante','W restauracji','el plato','talerz / danie'),
('En el Restaurante','W restauracji','el vaso','szklanka'),
('En el Restaurante','W restauracji','la copa','kieliszek'),
('En el Restaurante','W restauracji','la taza','filiżanka'),
('En el Restaurante','W restauracji','los cubiertos','sztućce'),
('En el Restaurante','W restauracji','el tenedor','widelec'),
('En el Restaurante','W restauracji','el cuchillo','nóż'),
('En el Restaurante','W restauracji','la cuchara','łyżka'),
('En el Restaurante','W restauracji','la cucharilla','łyżeczka'),
('En el Restaurante','W restauracji','la servilleta','serwetka'),
('En el Restaurante','W restauracji','el mantel','obrus'),
('En el Restaurante','W restauracji','la sal','sól'),
('En el Restaurante','W restauracji','la pimienta','pieprz'),
('En el Restaurante','W restauracji','el aceite','oliwa / olej'),
('En el Restaurante','W restauracji','el vinagre','ocet'),
('En el Restaurante','W restauracji','el pan','chleb'),
('En el Restaurante','W restauracji','el agua','woda'),
('En el Restaurante','W restauracji','la bebida','napój'),
('En el Restaurante','W restauracji','el entrante','przystawka'),
('En el Restaurante','W restauracji','el primer plato','pierwsze danie'),
('En el Restaurante','W restauracji','el plato principal','danie główne'),
('En el Restaurante','W restauracji','el postre','deser'),
('En el Restaurante','W restauracji','la especialidad de la casa','specjalność zakładu'),
('En el Restaurante','W restauracji','la recomendación','rekomendacja'),
('En el Restaurante','W restauracji','el chef','szef kuchni'),
('En el Restaurante','W restauracji','cocinar','gotować'),
('En el Restaurante','W restauracji','sabroso','smaczny'),
('En el Restaurante','W restauracji','picante','pikantny'),
('En el Restaurante','W restauracji','salado','słony'),
('En el Restaurante','W restauracji','dulce','słodki'),
('En el Restaurante','W restauracji','amargo','gorzki'),
('En el Restaurante','W restauracji','ácido','kwaśny'),
('En el Restaurante','W restauracji','la botella','butelka'),
('En el Restaurante','W restauracji','pagar','płacić'),
('En el Restaurante','W restauracji','en efectivo','gotówką'),
('En el Restaurante','W restauracji','con tarjeta','kartą'),
('En el Restaurante','W restauracji','el servicio','obsługa'),
('En el Hotel','W hotelu','el hotel','hotel'),
('En el Hotel','W hotelu','la recepción','recepcja'),
('En el Hotel','W hotelu','el recepcionista','recepcjonista'),
('En el Hotel','W hotelu','el huésped','gość (hotelowy)'),
('En el Hotel','W hotelu','la llave','klucz'),
('En el Hotel','W hotelu','la tarjeta','karta (do pokoju)'),
('En el Hotel','W hotelu','la habitación','pokój'),
('En el Hotel','W hotelu','la habitación individual','pokój jednoosobowy'),
('En el Hotel','W hotelu','la habitación doble','pokój dwuosobowy'),
('En el Hotel','W hotelu','la cama','łóżko'),
('En el Hotel','W hotelu','la almohada','poduszka'),
('En el Hotel','W hotelu','la manta','koc'),
('En el Hotel','W hotelu','el baño','łazienka'),
('En el Hotel','W hotelu','la ducha','prysznic'),
('En el Hotel','W hotelu','la bañera','wanna'),
('En el Hotel','W hotelu','el jabón','mydło'),
('En el Hotel','W hotelu','el champú','szampon'),
('En el Hotel','W hotelu','la toalla','ręcznik'),
('En el Hotel','W hotelu','el papel higiénico','papier toaletowy'),
('En el Hotel','W hotelu','el aire acondicionado','klimatyzacja'),
('En el Hotel','W hotelu','la calefacción','ogrzewanie'),
('En el Hotel','W hotelu','el balcón','balkon'),
('En el Hotel','W hotelu','las vistas','widok'),
('En el Hotel','W hotelu','el ascensor','winda'),
('En el Hotel','W hotelu','las escaleras','schody'),
('En el Hotel','W hotelu','el equipaje','bagaż'),
('En el Hotel','W hotelu','la maleta','walizka'),
('En el Hotel','W hotelu','el pasillo','korytarz'),
('En el Hotel','W hotelu','el desayuno','śniadanie'),
('En el Hotel','W hotelu','la pensión completa','pełne wyżywienie'),
('En el Hotel','W hotelu','la media pensión','niepełne wyżywienie'),
('En el Hotel','W hotelu','el servicio de habitaciones','obsługa pokoju'),
('En el Hotel','W hotelu','la limpieza','sprzątanie'),
('En el Hotel','W hotelu','cancelar','anulować'),
('En el Hotel','W hotelu','registrarse','zameldować się'),
('En el Hotel','W hotelu','la salida','wymeldowanie / wyjazd'),
('En el Hotel','W hotelu','la estancia','pobyt'),
('En el Hotel','W hotelu','la factura','faktura / rachunek'),
('En el Hotel','W hotelu','el gerente','kierownik'),
('En el Hotel','W hotelu','el botones','boy hotelowy'),
('En el Hotel','W hotelu','el vestíbulo','lobby / hol'),
('En el Hotel','W hotelu','la piscina','basen'),
('En el Hotel','W hotelu','el gimnasio','siłownia'),
('En el Hotel','W hotelu','el wifi','wi-fi'),
('En el Hotel','W hotelu','la contraseña','hasło'),
('En el Hotel','W hotelu','despertar','budzić'),
('En el Hotel','W hotelu','quejarse','skarżyć się'),
('En el Hotel','W hotelu','libre','wolny'),
('En el Hotel','W hotelu','ocupado','zajęty'),
('En el Hotel','W hotelu','la percha','wieszak');
