insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Las Estaciones','Pory roku','la estación','pora roku'),
('Las Estaciones','Pory roku','la primavera','wiosna'),
('Las Estaciones','Pory roku','el verano','lato'),
('Las Estaciones','Pory roku','el otoño','jesień'),
('Las Estaciones','Pory roku','el invierno','zima'),
('Las Estaciones','Pory roku','primaveral','wiosenny'),
('Las Estaciones','Pory roku','veraniego','letni'),
('Las Estaciones','Pory roku','otoñal','jesienny'),
('Las Estaciones','Pory roku','invernal','zimowy'),
('Las Estaciones','Pory roku','la temporada alta','wysoki sezon'),
('Las Estaciones','Pory roku','la temporada baja','niski sezon'),
('Las Estaciones','Pory roku','el clima','klimat'),
('Las Estaciones','Pory roku','el tiempo','pogoda / czas'),
('Las Estaciones','Pory roku','el cambio de estación','zmiana pory roku'),
('Las Estaciones','Pory roku','las vacaciones de verano','wakacje letnie'),
('Las Estaciones','Pory roku','las vacaciones de invierno','ferie zimowe'),
('Las Estaciones','Pory roku','la temperatura','temperatura'),
('Las Estaciones','Pory roku','el calor','upał'),
('Las Estaciones','Pory roku','el frío','zimno'),
('Las Estaciones','Pory roku','la nieve','śnieg'),
('Las Estaciones','Pory roku','la lluvia','deszcz'),
('Las Estaciones','Pory roku','el viento','wiatr'),
('Las Estaciones','Pory roku','el sol','słońce'),
('Las Estaciones','Pory roku','florecer','kwitnąć'),
('Las Estaciones','Pory roku','la flor','kwiat'),
('Las Estaciones','Pory roku','la hoja','liść'),
('Las Estaciones','Pory roku','caer las hojas','opadać (o liściach)'),
('Las Estaciones','Pory roku','nevar','padać śnieg'),
('Las Estaciones','Pory roku','llover','padać deszcz'),
('Las Estaciones','Pory roku','helar','zamarzać / mrozić'),
('Las Estaciones','Pory roku','el deshielo','odwilż'),
('Las Estaciones','Pory roku','la ola de calor','fala upałów'),
('Las Estaciones','Pory roku','la ola de frío','fala mrozów'),
('Las Estaciones','Pory roku','el solsticio','przesilenie'),
('Las Estaciones','Pory roku','el equinoccio','równonoc'),
('Las Estaciones','Pory roku','al aire libre','na świeżym powietrzu'),
('Las Estaciones','Pory roku','tomar el sol','opalać się'),
('Las Estaciones','Pory roku','esquiar','jeździć na nartach'),
('Las Estaciones','Pory roku','la cosecha','żniwa / zbiory'),
('Las Estaciones','Pory roku','la vendimia','winobranie'),
('Las Estaciones','Pory roku','el abrigo','płaszcz'),
('Las Estaciones','Pory roku','el traje de baño','strój kąpielowy'),
('Las Estaciones','Pory roku','las gafas de sol','okulary przeciwsłoneczne'),
('Las Estaciones','Pory roku','la bufanda','szalik'),
('Las Estaciones','Pory roku','el paraguas','parasol'),
('Las Estaciones','Pory roku','broncearse','opalać się (pokryć brązem)'),
('Las Estaciones','Pory roku','tiritar','trząść się z zimna'),
('Las Estaciones','Pory roku','sudar','pocić się'),
('Las Estaciones','Pory roku','refrescar','ochładzać się / odświeżać'),
('Las Estaciones','Pory roku','el clima tropical','klimat tropikalny'),
('Adverbios de Tiempo','Przysłówki czasu','ahora','teraz'),
('Adverbios de Tiempo','Przysłówki czasu','antes','wcześniej / przedtem'),
('Adverbios de Tiempo','Przysłówki czasu','después','potem / później'),
('Adverbios de Tiempo','Przysłówki czasu','luego','następnie / później'),
('Adverbios de Tiempo','Przysłówki czasu','hoy','dzisiaj'),
('Adverbios de Tiempo','Przysłówki czasu','mañana','jutro'),
('Adverbios de Tiempo','Przysłówki czasu','ayer','wczoraj'),
('Adverbios de Tiempo','Przysłówki czasu','pronto','wkrótce / niedługo'),
('Adverbios de Tiempo','Przysłówki czasu','tarde','późno'),
('Adverbios de Tiempo','Przysłówki czasu','temprano','wcześnie'),
('Adverbios de Tiempo','Przysłówki czasu','siempre','zawsze'),
('Adverbios de Tiempo','Przysłówki czasu','nunca','nigdy'),
('Adverbios de Tiempo','Przysłówki czasu','jamás','nigdy w życiu'),
('Adverbios de Tiempo','Przysłówki czasu','a veces','czasami'),
('Adverbios de Tiempo','Przysłówki czasu','ya','już'),
('Adverbios de Tiempo','Przysłówki czasu','todavía','jeszcze (ciągle)'),
('Adverbios de Tiempo','Przysłówki czasu','aún','jeszcze / mimo to'),
('Adverbios de Tiempo','Przysłówki czasu','enseguida','natychmiast / zaraz'),
('Adverbios de Tiempo','Przysłówki czasu','inmediatamente','natychmiast'),
('Adverbios de Tiempo','Przysłówki czasu','mientras','podczas gdy / dopóki'),
('Adverbios de Tiempo','Przysłówki czasu','mientras tanto','w międzyczasie'),
('Adverbios de Tiempo','Przysłówki czasu','de repente','nagle'),
('Adverbios de Tiempo','Przysłówki czasu','de pronto','nagle (nieoczekiwanie)'),
('Adverbios de Tiempo','Przysłówki czasu','frecuentemente','często'),
('Adverbios de Tiempo','Przysłówki czasu','a menudo','często (gęsto)'),
('Adverbios de Tiempo','Przysłówki czasu','raramente','rzadko'),
('Adverbios de Tiempo','Przysłówki czasu','rara vez','rzadka (bardzo rzadko)'),
('Adverbios de Tiempo','Przysłówki czasu','de vez en cuando','od czasu do czasu'),
('Adverbios de Tiempo','Przysłówki czasu','recientemente','ostatnio (niedawno)'),
('Adverbios de Tiempo','Przysłówki czasu','últimamente','ostatnio (w ostatnim czasie)'),
('Adverbios de Tiempo','Przysłówki czasu','actualmente','obecnie'),
('Adverbios de Tiempo','Przysłówki czasu','constantemente','stale / ciągle'),
('Adverbios de Tiempo','Przysłówki czasu','en este momento','w tym momencie'),
('Adverbios de Tiempo','Przysłówki czasu','al instante','w tej chwili'),
('Adverbios de Tiempo','Przysłówki czasu','a tiempo','na czas'),
('Adverbios de Tiempo','Przysłówki czasu','con tiempo','z wyprzedzeniem'),
('Adverbios de Tiempo','Przysłówki czasu','tarde o temprano','prędzej czy później'),
('Adverbios de Tiempo','Przysłówki czasu','antes de ayer','przedwczoraj'),
('Adverbios de Tiempo','Przysłówki czasu','de día','w dzień'),
('Adverbios de Tiempo','Przysłówki czasu','de noche','w nocy'),
('Adverbios de Tiempo','Przysłówki czasu','al principio','na początku'),
('Adverbios de Tiempo','Przysłówki czasu','al final','na końcu'),
('Adverbios de Tiempo','Przysłówki czasu','finalmente','w końcu / ostatecznie'),
('Adverbios de Tiempo','Przysłówki czasu','previamente','poprzednio / wcześniej'),
('Adverbios de Tiempo','Przysłówki czasu','cotidianamente','codziennie'),
('Adverbios de Tiempo','Przysłówki czasu','apenas','ledwie / dopiero co'),
('Adverbios de Tiempo','Przysłówki czasu','recién','dopiero co (Ameryka Łac.)'),
('Adverbios de Tiempo','Przysłówki czasu','jamás de los jamases','nigdy przenigdy'),
('Adverbios de Tiempo','Przysłówki czasu','en un rato','za chwilę'),
('Adverbios de Tiempo','Przysłówki czasu','hace poco','niedawno'),
('Adverbios de Lugar','Przysłówki miejsca','aquí','tutaj'),
('Adverbios de Lugar','Przysłówki miejsca','ahí','tam (blisko)'),
('Adverbios de Lugar','Przysłówki miejsca','allí','tam (daleko)'),
('Adverbios de Lugar','Przysłówki miejsca','allá','tam (bardzo daleko/ogólnie)'),
('Adverbios de Lugar','Przysłówki miejsca','acá','tutaj (Ameryka Łac. / w tym kierunku)'),
('Adverbios de Lugar','Przysłówki miejsca','cerca','blisko'),
('Adverbios de Lugar','Przysłówki miejsca','lejos','daleko'),
('Adverbios de Lugar','Przysłówki miejsca','arriba','w górze / na górze'),
('Adverbios de Lugar','Przysłówki miejsca','abajo','w dole / na dole'),
('Adverbios de Lugar','Przysłówki miejsca','delante','z przodu / przed'),
('Adverbios de Lugar','Przysłówki miejsca','detrás','z tyłu / za'),
('Adverbios de Lugar','Przysłówki miejsca','encima','na (powierzchni) / nad'),
('Adverbios de Lugar','Przysłówki miejsca','debajo','pod / pod spodem'),
('Adverbios de Lugar','Przysłówki miejsca','dentro','w środku / wewnątrz'),
('Adverbios de Lugar','Przysłówki miejsca','fuera','na zewnątrz'),
('Adverbios de Lugar','Przysłówki miejsca','adentro','do środka / wewnątrz'),
('Adverbios de Lugar','Przysłówki miejsca','afuera','na zewnątrz / dwór'),
('Adverbios de Lugar','Przysłówki miejsca','alrededor','dookoła / wokół'),
('Adverbios de Lugar','Przysłówki miejsca','junto','razem / obok'),
('Adverbios de Lugar','Przysłówki miejsca','al lado','obok'),
('Adverbios de Lugar','Przysłówki miejsca','enfrente','naprzeciwko'),
('Adverbios de Lugar','Przysłówki miejsca','atrás','w tył / z tyłu'),
('Adverbios de Lugar','Przysłówki miejsca','adelante','naprzód / z przodu'),
('Adverbios de Lugar','Przysłówki miejsca','donde','gdzie'),
('Adverbios de Lugar','Przysłówki miejsca','adonde','dokąd'),
('Adverbios de Lugar','Przysłówki miejsca','por donde','tędy / którędy'),
('Adverbios de Lugar','Przysłówki miejsca','hacia acá','w tę stronę'),
('Adverbios de Lugar','Przysłówki miejsca','hacia allá','w tamtą stronę'),
('Adverbios de Lugar','Przysłówki miejsca','en cualquier lugar / en cualquier sitio','gdziekolwiek'),
('Adverbios de Lugar','Przysłówki miejsca','en ningún lugar / en ningún sitio','nigdzie'),
('Adverbios de Lugar','Przysłówki miejsca','en todas partes','wszędzie'),
('Adverbios de Lugar','Przysłówki miejsca','en otra parte','gdzie indziej'),
('Adverbios de Lugar','Przysłówki miejsca','en alguna parte','gdzieś'),
('Adverbios de Lugar','Przysłówki miejsca','más allá','dalej / poza'),
('Adverbios de Lugar','Przysłówki miejsca','a la derecha','na prawo / po prawej'),
('Adverbios de Lugar','Przysłówki miejsca','a la izquierda','na lewo / po lewej'),
('Adverbios de Lugar','Przysłówki miejsca','recto / derecho','prosto'),
('Adverbios de Lugar','Przysłówki miejsca','en medio','pośrodku'),
('Adverbios de Lugar','Przysłówki miejsca','por aquí','tędy (blisko)'),
('Adverbios de Lugar','Przysłówki miejsca','por allí','tamtędy (daleko)'),
('Adverbios de Lugar','Przysłówki miejsca','en el fondo','w głębi / na dnie'),
('Adverbios de Lugar','Przysłówki miejsca','a lo lejos','w dali'),
('Adverbios de Lugar','Przysłówki miejsca','en lo alto','na wysokości / na szczycie'),
('Adverbios de Lugar','Przysłówki miejsca','boca arriba','na plecach (twarzą do góry)'),
('Adverbios de Lugar','Przysłówki miejsca','boca abajo','na brzuchu (twarzą w dół)'),
('Adverbios de Lugar','Przysłówki miejsca','por doquier','wszędzie (lit.)'),
('Adverbios de Lugar','Przysłówki miejsca','intramuros','w obrębie murów'),
('Adverbios de Lugar','Przysłówki miejsca','extramuros','poza murami'),
('Adverbios de Lugar','Przysłówki miejsca','en casa','w domu'),
('Adverbios de Lugar','Przysłówki miejsca','fuera de casa','poza domem'),
('Adverbios de Modo','Przysłówki sposobu','así','tak / w ten sposób'),
('Adverbios de Modo','Przysłówki sposobu','bien','dobrze'),
('Adverbios de Modo','Przysłówki sposobu','mal','źle'),
('Adverbios de Modo','Przysłówki sposobu','mejor','lepiej'),
('Adverbios de Modo','Przysłówki sposobu','peor','gorzej'),
('Adverbios de Modo','Przysłówki sposobu','despacio','wolno / powoli'),
('Adverbios de Modo','Przysłówki sposobu','rápido','szybko'),
('Adverbios de Modo','Przysłówki sposobu','lentamente','powoli'),
('Adverbios de Modo','Przysłówki sposobu','rápidamente','szybko'),
('Adverbios de Modo','Przysłówki sposobu','fácilmente','łatwo'),
('Adverbios de Modo','Przysłówki sposobu','difícilmente','z trudem / trudno'),
('Adverbios de Modo','Przysłówki sposobu','felizmente','szczęśliwie'),
('Adverbios de Modo','Przysłówki sposobu','tristemente','smutnie'),
('Adverbios de Modo','Przysłówki sposobu','claramente','jasno / wyraźnie'),
('Adverbios de Modo','Przysłówki sposobu','oscuro','ciemno'),
('Adverbios de Modo','Przysłówki sposobu','suavemente','delikatnie / miękko'),
('Adverbios de Modo','Przysłówki sposobu','fuertemente','mocno'),
('Adverbios de Modo','Przysłówki sposobu','duro','ciężko / twardo'),
('Adverbios de Modo','Przysłówki sposobu','aprisa','śpiesznie / prędko'),
('Adverbios de Modo','Przysłówki sposobu','aposta / adrede','celowo / specjalnie'),
('Adverbios de Modo','Przysłówki sposobu','sin querer','niechcący'),
('Adverbios de Modo','Przysłówki sposobu','a propósito','celowo / przy okazji'),
('Adverbios de Modo','Przysłówki sposobu','en voz alta','na głos'),
('Adverbios de Modo','Przysłówki sposobu','en voz baja','szeptem / po cichu'),
('Adverbios de Modo','Przysłówki sposobu','de memoria','na pamięć'),
('Adverbios de Modo','Przysłówki sposobu','a ciegas','na oślep'),
('Adverbios de Modo','Przysłówki sposobu','a escondidas','w ukryciu / potajemnie'),
('Adverbios de Modo','Przysłówki sposobu','de repente / de golpe','nagle / jednym ruchem'),
('Adverbios de Modo','Przysłówki sposobu','casi','prawie'),
('Adverbios de Modo','Przysłówki sposobu','apenas','ledwie'),
('Adverbios de Modo','Przysłówki sposobu','completamente','całkowicie'),
('Adverbios de Modo','Przysłówki sposobu','parcialmente','częściowo'),
('Adverbios de Modo','Przysłówki sposobu','totalmente','zupełnie / totalnie'),
('Adverbios de Modo','Przysłówki sposobu','absolutamente','absolutnie'),
('Adverbios de Modo','Przysłówki sposobu','exactamente','dokładnie'),
('Adverbios de Modo','Przysłówki sposobu','justamente','właśnie / dokładnie'),
('Adverbios de Modo','Przysłówki sposobu','estupendamente','wspaniale'),
('Adverbios de Modo','Przysłówki sposobu','terriblemente','okropnie'),
('Adverbios de Modo','Przysłówki sposobu','naturalmente','naturalnie'),
('Adverbios de Modo','Przysłówki sposobu','seguramente','pewnie / na pewno'),
('Adverbios de Modo','Przysłówki sposobu','probablemente','prawdopodobnie'),
('Adverbios de Modo','Przysłówki sposobu','posiblemente','możliwe'),
('Adverbios de Modo','Przysłówki sposobu','igual','tak samo / równo'),
('Adverbios de Modo','Przysłówki sposobu','diferente / distinto','inaczej'),
('Adverbios de Modo','Przysłówki sposobu','gratis','za darmo'),
('Adverbios de Modo','Przysłówki sposobu','solo / solamente','tylko'),
('Adverbios de Modo','Przysłówki sposobu','únicamente','wyłącznie'),
('Adverbios de Modo','Przysłówki sposobu','exclusivamente','wyłącznie'),
('Adverbios de Modo','Przysłówki sposobu','a medias','w połowie / niedokładnie'),
('Adverbios de Modo','Przysłówki sposobu','de maravilla','cudownie / świetnie');
