insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('El Espacio','Kosmos','el espacio','kosmos / przestrzeń'),
('El Espacio','Kosmos','el universo','wszechświat'),
('El Espacio','Kosmos','la galaxia','galaktyka'),
('El Espacio','Kosmos','el sistema solar','układ słoneczny'),
('El Espacio','Kosmos','el planeta','planeta'),
('El Espacio','Kosmos','la estrella','gwiazda'),
('El Espacio','Kosmos','el sol','słońce'),
('El Espacio','Kosmos','la luna','księżyc'),
('El Espacio','Kosmos','la tierra','ziemia'),
('El Espacio','Kosmos','el asteroide','asteroida'),
('El Espacio','Kosmos','el cometa','kometa'),
('El Espacio','Kosmos','el meteorito','meteoryt'),
('El Espacio','Kosmos','la órbita','orbita'),
('El Espacio','Kosmos','orbitar','krążyć (po orbicie)'),
('El Espacio','Kosmos','la gravedad','grawitacja'),
('El Espacio','Kosmos','el agujero negro','czarna dziura'),
('El Espacio','Kosmos','el eclipse','zaćmienie'),
('El Espacio','Kosmos','el telescopio','teleskop'),
('El Espacio','Kosmos','el observatorio','obserwatorium'),
('El Espacio','Kosmos','el astronauta','astronauta'),
('El Espacio','Kosmos','el cohete','rakieta'),
('El Espacio','Kosmos','la nave espacial','statek kosmiczny'),
('El Espacio','Kosmos','el transbordador','wahadłowiec'),
('El Espacio','Kosmos','el satélite','satelita'),
('El Espacio','Kosmos','la estación espacial','stacja kosmiczna'),
('El Espacio','Kosmos','el lanzamiento','start / wystrzelenie'),
('El Espacio','Kosmos','lanzar','wystrzeliwać (rakietę)'),
('El Espacio','Kosmos','aterrizar','lądować (na ziemi/planecie)'),
('El Espacio','Kosmos','alunizar','lądować na księżycu'),
('El Espacio','Kosmos','la misión','misja'),
('El Espacio','Kosmos','explorar','odkrywać / badać'),
('El Espacio','Kosmos','la exploración','eksploracja'),
('El Espacio','Kosmos','extraterrestre (adj.)','pozaziemski'),
('El Espacio','Kosmos','el extraterrestre','kosmita'),
('El Espacio','Kosmos','el alienígena','obcy'),
('El Espacio','Kosmos','el ovni','UFO'),
('El Espacio','Kosmos','la Vía Láctea','Droga Mleczna'),
('El Espacio','Kosmos','el rayo','promień'),
('El Espacio','Kosmos','luminoso','świetlny'),
('El Espacio','Kosmos','el año luz','rok świetlny'),
('El Espacio','Kosmos','el cielo','niebo'),
('El Espacio','Kosmos','la constelación','konstelacja'),
('El Espacio','Kosmos','el cosmos','kosmos'),
('El Espacio','Kosmos','cósmico','kosmiczny'),
('El Espacio','Kosmos','el vacío','próżnia'),
('El Espacio','Kosmos','flotar','unosić się / pływać'),
('El Espacio','Kosmos','la velocidad de la luz','prędkość światła'),
('El Espacio','Kosmos','el cráter','krater'),
('El Espacio','Kosmos','la superficie','powierzchnia'),
('El Espacio','Kosmos','descubrir','odkryć (planetę)'),
('Materiales','Materiały','el material','materiał'),
('Materiales','Materiały','la madera','drewno'),
('Materiales','Materiały','el plástico','plastik'),
('Materiales','Materiały','el metal','metal'),
('Materiales','Materiały','el cristal / el vidrio','szkło'),
('Materiales','Materiały','el acero','stal'),
('Materiales','Materiały','el hierro','żelazo'),
('Materiales','Materiały','el aluminio','aluminium'),
('Materiales','Materiały','el cobre','miedź'),
('Materiales','Materiały','el oro','złoto'),
('Materiales','Materiały','la plata','srebro'),
('Materiales','Materiały','el bronce','brąz'),
('Materiales','Materiały','la piedra','kamień'),
('Materiales','Materiały','el mármol','marmur'),
('Materiales','Materiały','el granito','granit'),
('Materiales','Materiały','el ladrillo','cegła'),
('Materiales','Materiały','el cemento','cement'),
('Materiales','Materiały','el hormigón','beton'),
('Materiales','Materiały','la arcilla','glina'),
('Materiales','Materiały','la arena','piasek'),
('Materiales','Materiały','el papel','papier'),
('Materiales','Materiały','el cartón','karton'),
('Materiales','Materiały','la tela','tkanina / materiał'),
('Materiales','Materiały','el algodón','bawełna'),
('Materiales','Materiały','la lana','wełna'),
('Materiales','Materiały','la seda','jedwab'),
('Materiales','Materiały','el lino','lniany materiał / len'),
('Materiales','Materiały','el poliéster','poliester'),
('Materiales','Materiały','el nailon','nylon'),
('Materiales','Materiały','el cuero / la piel','skóra (materiał)'),
('Materiales','Materiały','el ante','zamsz'),
('Materiales','Materiały','la goma','guma'),
('Materiales','Materiały','el caucho','kauczuk'),
('Materiales','Materiały','el corcho','korek'),
('Materiales','Materiały','la cerámica','ceramika'),
('Materiales','Materiały','la porcelana','porcelana'),
('Materiales','Materiały','el diamante','diament'),
('Materiales','Materiały','el carbón','węgiel'),
('Materiales','Materiały','el petróleo','ropa naftowa'),
('Materiales','Materiały','el gas','gaz'),
('Materiales','Materiały','sólido','stały (stan skupienia)'),
('Materiales','Materiały','líquido','ciekły'),
('Materiales','Materiały','gaseoso','gazowy'),
('Materiales','Materiały','blando','miękki'),
('Materiales','Materiały','duro','twardy'),
('Materiales','Materiały','resistente','wytrzymały'),
('Materiales','Materiały','frágil','kruchy / delikatny'),
('Materiales','Materiały','pesado','ciężki'),
('Materiales','Materiały','ligero','lekki'),
('Materiales','Materiały','elástico','elastyczny'),
('Formas Geométricas','Kształty geometryczne','la forma','kształt'),
('Formas Geométricas','Kształty geometryczne','el círculo','koło'),
('Formas Geométricas','Kształty geometryczne','el cuadrado','kwadrat'),
('Formas Geométricas','Kształty geometryczne','el triángulo','trójkąt'),
('Formas Geométricas','Kształty geometryczne','el rectángulo','prostokąt'),
('Formas Geométricas','Kształty geometryczne','el óvalo','owal'),
('Formas Geométricas','Kształty geometryczne','el rombo','romb'),
('Formas Geométricas','Kształty geometryczne','el pentágono','pięciokąt'),
('Formas Geométricas','Kształty geometryczne','el hexágono','sześciokąt'),
('Formas Geométricas','Kształty geometryczne','el octógono','ośmiokąt'),
('Formas Geométricas','Kształty geometryczne','la estrella','gwiazda (kształt)'),
('Formas Geométricas','Kształty geometryczne','la cruz','krzyż (kształt)'),
('Formas Geométricas','Kształty geometryczne','la esfera','kula'),
('Formas Geométricas','Kształty geometryczne','el cubo','sześcian'),
('Formas Geométricas','Kształty geometryczne','el cilindro','cylinder / walec'),
('Formas Geométricas','Kształty geometryczne','el cono','stożek'),
('Formas Geométricas','Kształty geometryczne','la pirámide','piramida'),
('Formas Geométricas','Kształty geometryczne','el prisma','graniastosłup'),
('Formas Geométricas','Kształty geometryczne','la línea','linia'),
('Formas Geométricas','Kształty geometryczne','recto','prosty (o linii)'),
('Formas Geométricas','Kształty geometryczne','curvo','krzywy'),
('Formas Geométricas','Kształty geometryczne','el punto','punkt'),
('Formas Geométricas','Kształty geometryczne','el ángulo','kąt'),
('Formas Geométricas','Kształty geometryczne','redondo','okrągły'),
('Formas Geométricas','Kształty geometryczne','cuadrado (adj.)','kwadratowy'),
('Formas Geométricas','Kształty geometryczne','triangular','trójkątny'),
('Formas Geométricas','Kształty geometryczne','rectangular','prostokątny'),
('Formas Geométricas','Kształty geometryczne','ovalado','owalny'),
('Formas Geométricas','Kształty geometryczne','plano','płaski'),
('Formas Geométricas','Kształty geometryczne','tridimensional','trójwymiarowy'),
('Formas Geométricas','Kształty geometryczne','la dimensión','wymiar'),
('Formas Geométricas','Kształty geometryczne','el centro','środek'),
('Formas Geométricas','Kształty geometryczne','el lado','bok'),
('Formas Geométricas','Kształty geometryczne','el borde','krawędź / brzeg'),
('Formas Geométricas','Kształty geometryczne','la superficie','powierzchnia'),
('Formas Geométricas','Kształty geometryczne','el volumen','objętość'),
('Formas Geométricas','Kształty geometryczne','la anchura','szerokość'),
('Formas Geométricas','Kształty geometryczne','ancho','szeroki'),
('Formas Geométricas','Kształty geometryczne','la longitud','długość'),
('Formas Geométricas','Kształty geometryczne','largo','długi'),
('Formas Geométricas','Kształty geometryczne','la altura','wysokość'),
('Formas Geométricas','Kształty geometryczne','alto','wysoki'),
('Formas Geométricas','Kształty geometryczne','profundo','głęboki'),
('Formas Geométricas','Kształty geometryczne','la profundidad','głębokość'),
('Formas Geométricas','Kształty geometryczne','simétrico','symetryczny'),
('Formas Geométricas','Kształty geometryczne','asimétrico','asymetryczny'),
('Formas Geométricas','Kształty geometryczne','paralelo','równoległy'),
('Formas Geométricas','Kształty geometryczne','perpendicular','prostopadły'),
('Formas Geométricas','Kształty geometryczne','el diámetro','średnica'),
('Formas Geométricas','Kształty geometryczne','el radio','promień'),
('El Ocio','Czas wolny','el ocio','czas wolny'),
('El Ocio','Czas wolny','el tiempo libre','czas wolny'),
('El Ocio','Czas wolny','el hobby / la afición','hobby / pasja'),
('El Ocio','Czas wolny','descansar','odpoczywać'),
('El Ocio','Czas wolny','el descanso','odpoczynek'),
('El Ocio','Czas wolny','relajarse','relaksować się'),
('El Ocio','Czas wolny','divertirse','bawić się / spędzać dobrze tiempo'),
('El Ocio','Czas wolny','el entretenimiento','rozrywka'),
('El Ocio','Czas wolny','el paseo','spacer'),
('El Ocio','Czas wolny','pasear','spacerować'),
('El Ocio','Czas wolny','el parque','park'),
('El Ocio','Czas wolny','el cine','kino'),
('El Ocio','Czas wolny','el teatro','teatr'),
('El Ocio','Czas wolny','el museo','muzeum'),
('El Ocio','Czas wolny','el concierto','koncert'),
('El Ocio','Czas wolny','la exposición','wystawa'),
('El Ocio','Czas wolny','el festival','festiwal'),
('El Ocio','Czas wolny','la discoteca','dyskoteka'),
('El Ocio','Czas wolny','bailar','tańczyć'),
('El Ocio','Czas wolny','el baile','taniec'),
('El Ocio','Czas wolny','cantar','śpiewać'),
('El Ocio','Czas wolny','el karaoke','karaoke'),
('El Ocio','Czas wolny','escuchar música','słuchać muzyki'),
('El Ocio','Czas wolny','leer','czytać'),
('El Ocio','Czas wolny','la lectura','czytanie / lektura'),
('El Ocio','Czas wolny','ver la televisión','oglądać telewizję'),
('El Ocio','Czas wolny','ver una película','oglądać film'),
('El Ocio','Czas wolny','ver una serie','oglądać serial'),
('El Ocio','Czas wolny','jugar','grać / bawić się'),
('El Ocio','Czas wolny','el juego','gra'),
('El Ocio','Czas wolny','navegar por internet','surfować po internecie'),
('El Ocio','Czas wolny','chatear','czatować'),
('El Ocio','Czas wolny','ir de compras','iść na zakupy'),
('El Ocio','Czas wolny','el deporte','sport'),
('El Ocio','Czas wolny','hacer deporte','uprawiać sport'),
('El Ocio','Czas wolny','ir al gimnasio','iść na siłownię'),
('El Ocio','Czas wolny','nadar','pływać'),
('El Ocio','Czas wolny','montar en bicicleta','jeździć na rowerze'),
('El Ocio','Czas wolny','el viaje','podróż'),
('El Ocio','Czas wolny','viajar','podróżować'),
('El Ocio','Czas wolny','las vacaciones','wakacje'),
('El Ocio','Czas wolny','la fotografía','fotografia (hobby)'),
('El Ocio','Czas wolny','sacar fotos','robić zdjęcia'),
('El Ocio','Czas wolny','pintar','malować'),
('El Ocio','Czas wolny','cocinar','gotować (dla przyjemności)'),
('El Ocio','Czas wolny','la jardinería','ogrodnictwo'),
('El Ocio','Czas wolny','el club','klub'),
('El Ocio','Czas wolny','la fiesta','impreza / przyjęcie'),
('El Ocio','Czas wolny','salir','wychodzić (na miasto)'),
('El Ocio','Czas wolny','quedar con amigos','spotykać się z przyjaciółmi');
