insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('En el Barco','Na statku','el barco','statek'),
('En el Barco','Na statku','el bote','łódź'),
('En el Barco','Na statku','el velero','żaglówka'),
('En el Barco','Na statku','el crucero','statek wycieczkowy'),
('En el Barco','Na statku','el yate','jacht'),
('En el Barco','Na statku','el ferry','prom'),
('En el Barco','Na statku','la lancha','motorówka'),
('En el Barco','Na statku','la cubierta','pokład'),
('En el Barco','Na statku','el camarote','kajuta / kabina'),
('En el Barco','Na statku','el capitán','kapitan'),
('En el Barco','Na statku','el marinero','marynarz'),
('En el Barco','Na statku','la tripulación','załoga'),
('En el Barco','Na statku','el ancla','kotwica'),
('En el Barco','Na statku','el puerto','port'),
('En el Barco','Na statku','el muelle','molo / pirs'),
('En el Barco','Na statku','zarpar','wypływać (z portu)'),
('En el Barco','Na statku','atracar','cumować'),
('En el Barco','Na statku','navegar','żeglować / pływać'),
('En el Barco','Na statku','naufragar','zatonąć / rozbić się'),
('En el Barco','Na statku','el naufragio','katastrofa morska'),
('En el Barco','Na statku','el chaleco salvavidas','kamizelka ratunkowa'),
('En el Barco','Na statku','el bote salvavidas','szalupa ratunkowa'),
('En el Barco','Na statku','la proa','dziób statku'),
('En el Barco','Na statku','la popa','rufa'),
('En el Barco','Na statku','babor','bakburta (lewa)'),
('En el Barco','Na statku','estribor','sterburta (prawa)'),
('En el Barco','Na statku','el mástil','maszt'),
('En el Barco','Na statku','la vela','żagiel'),
('En el Barco','Na statku','el timón','ster'),
('En el Barco','Na statku','el faro','latarnia morska'),
('En el Barco','Na statku','la ola','fala'),
('En el Barco','Na statku','el mar','morze'),
('En el Barco','Na statku','el océano','ocean'),
('En el Barco','Na statku','marearse','mieć chorobę morską'),
('En el Barco','Na statku','el mareo','choroba morska'),
('En el Barco','Na statku','el pasaje','bilet (na rejs)'),
('En el Barco','Na statku','el pasajero','pasażer'),
('En el Barco','Na statku','el salvavidas','koło ratunkowe / ratownik'),
('En el Barco','Na statku','la brújula','kompas'),
('En el Barco','Na statku','el radar','radar'),
('En el Barco','Na statku','la escotilla','właz'),
('En el Barco','Na statku','la bodega','ładownia'),
('En el Barco','Na statku','hundirse','tonąć'),
('En el Barco','Na statku','flotar','unosić się na wodzie'),
('En el Barco','Na statku','el nudo','węzeł'),
('En el Barco','Na statku','el pirata','pirat'),
('En el Barco','Na statku','el remo','wiosło'),
('En el Barco','Na statku','remar','wiosłować'),
('En el Barco','Na statku','la cuerda','lina'),
('En el Barco','Na statku','la marea','pływ (przypływ/odpływ)'),
('Transporte Público','Transport publiczny','el transporte público','transport publiczny'),
('Transporte Público','Transport publiczny','el autobús','autobus'),
('Transporte Público','Transport publiczny','el autocar','autokar'),
('Transporte Público','Transport publiczny','el tranvía','tramwaj'),
('Transporte Público','Transport publiczny','el metro','metro'),
('Transporte Público','Transport publiczny','el tren','pociąg'),
('Transporte Público','Transport publiczny','el taxi','taksówka'),
('Transporte Público','Transport publiczny','la parada','przystanek'),
('Transporte Público','Transport publiczny','la estación','stacja'),
('Transporte Público','Transport publiczny','la terminal','terminal'),
('Transporte Público','Transport publiczny','el billete / el boleto','bilet'),
('Transporte Público','Transport publiczny','el bono de transporte','bilet okresowy'),
('Transporte Público','Transport publiczny','la tarjeta de transporte','karta miejska'),
('Transporte Público','Transport publiczny','validar','kasować (bilet)'),
('Transporte Público','Transport publiczny','la máquina expendedora','automat biletowy'),
('Transporte Público','Transport publiczny','el revisor','kontroler biletów / rewizor'),
('Transporte Público','Transport publiczny','el conductor','kierowca'),
('Transporte Público','Transport publiczny','el pasajero','pasażer'),
('Transporte Público','Transport publiczny','subir','wsiadać'),
('Transporte Público','Transport publiczny','bajar','wysiadać'),
('Transporte Público','Transport publiczny','hacer transbordo','przesiadać się'),
('Transporte Público','Transport publiczny','la línea','linia'),
('Transporte Público','Transport publiczny','la ruta','trasa'),
('Transporte Público','Transport publiczny','el horario','rozkład jazdy'),
('Transporte Público','Transport publiczny','el retraso','opóźnienie'),
('Transporte Público','Transport publiczny','puntual','punktualny'),
('Transporte Público','Transport publiczny','la marquesina','wiata przystankowa'),
('Transporte Público','Transport publiczny','el asiento','siedzenie'),
('Transporte Público','Transport publiczny','ceder el asiento','ustąpić miejsca'),
('Transporte Público','Transport publiczny','de pie','na stojąco'),
('Transporte Público','Transport publiczny','el timbre','dzwonek'),
('Transporte Público','Transport publiczny','solicitar parada','żądać zatrzymania (przystanek na żądanie)'),
('Transporte Público','Transport publiczny','la hora punta','godzina szczytu'),
('Transporte Público','Transport publiczny','lleno','pełny'),
('Transporte Público','Transport publiczny','vacío','pusty'),
('Transporte Público','Transport publiczny','la tarifa','taryfa / opłata'),
('Transporte Público','Transport publiczny','el descuento','zniżka'),
('Transporte Público','Transport publiczny','la multa','mandat'),
('Transporte Público','Transport publiczny','el andén','peron'),
('Transporte Público','Transport publiczny','la vía','tor'),
('Transporte Público','Transport publiczny','la dirección','kierunek'),
('Transporte Público','Transport publiczny','próximo','następny'),
('Transporte Público','Transport publiczny','la parada de taxis','postój taksówek'),
('Transporte Público','Transport publiczny','el taxímetro','taksometr'),
('Transporte Público','Transport publiczny','la parada a petición','przystanek na żądanie'),
('Transporte Público','Transport publiczny','moverse','poruszać się'),
('Transporte Público','Transport publiczny','viajar','podróżować'),
('Transporte Público','Transport publiczny','el abono mensual','bilet miesięczny'),
('Transporte Público','Transport publiczny','la conexión','połączenie'),
('Transporte Público','Transport publiczny','el trayecto','przejazd / odcinek trasy'),
('Medicina','Medycyna','la medicina','medycyna / lek'),
('Medicina','Medycyna','el médico / la médica','lekarz'),
('Medicina','Medycyna','el doctor / la doctora','doktor'),
('Medicina','Medycyna','el enfermero / la enfermera','pielęgniarz/pielęgniarka'),
('Medicina','Medycyna','el paciente','pacjent'),
('Medicina','Medycyna','la salud','zdrowie'),
('Medicina','Medycyna','la enfermedad','choroba'),
('Medicina','Medycyna','el diagnóstico','diagnoza'),
('Medicina','Medycyna','diagnosticar','diagnozować'),
('Medicina','Medycyna','el tratamiento','leczenie / kuracja'),
('Medicina','Medycyna','tratar','leczyć'),
('Medicina','Medycyna','curar','uzdrawiać / wyleczyć'),
('Medicina','Medycyna','la cura','lekarstwo / wyleczenie'),
('Medicina','Medycyna','prevenir','zapobiegać'),
('Medicina','Medycyna','la prevención','profilaktyka'),
('Medicina','Medycyna','el síntoma','objaw'),
('Medicina','Medycyna','la consulta','wizyta lekarska'),
('Medicina','Medycyna','el consultorio','przychodnia / gabinet'),
('Medicina','Medycyna','examinar','badać'),
('Medicina','Medycyna','el examen médico','badanie lekarskie'),
('Medicina','Medycyna','la presión arterial','ciśnienie krwi'),
('Medicina','Medycyna','el pulso','puls'),
('Medicina','Medycyna','tomar el pulso','mierzyć puls'),
('Medicina','Medycyna','el termómetro','termometr'),
('Medicina','Medycyna','la temperatura','temperatura'),
('Medicina','Medycyna','la fiebre','gorączka'),
('Medicina','Medycyna','la inyección','zastrzyk'),
('Medicina','Medycyna','la vacuna','szczepionka'),
('Medicina','Medycyna','vacunar','szczepić'),
('Medicina','Medycyna','la operación','operacja'),
('Medicina','Medycyna','operar','operować'),
('Medicina','Medycyna','el cirujano','chirurg'),
('Medicina','Medycyna','la receta','recepta'),
('Medicina','Medycyna','recetar','przepisywać lek'),
('Medicina','Medycyna','la pastilla','tabletka'),
('Medicina','Medycyna','el jarabe','syrop'),
('Medicina','Medycyna','la sangre','krew'),
('Medicina','Medycyna','el análisis de sangre','badanie krwi'),
('Medicina','Medycyna','la radiografía','rentgen (zdjęcie)'),
('Medicina','Medycyna','el dolor','ból'),
('Medicina','Medycyna','doler','boleć'),
('Medicina','Medycyna','el especialista','specjalista'),
('Medicina','Medycyna','el pediatra','pediatra'),
('Medicina','Medycyna','el cardiólogo','kardiolog'),
('Medicina','Medycyna','el dentista','dentysta'),
('Medicina','Medycyna','el psicólogo','psycholog'),
('Medicina','Medycyna','el psiquiatra','psychiatra'),
('Medicina','Medycyna','la terapia','terapia'),
('Medicina','Medycyna','recuperarse','wracać do zdrowia'),
('Medicina','Medycyna','la recuperación','rekonwalescencja'),
('En la Farmacia','W aptece','la farmacia','apteka'),
('En la Farmacia','W aptece','el farmacéutico','farmaceuta'),
('En la Farmacia','W aptece','el medicamento','lekarstwo'),
('En la Farmacia','W aptece','la medicina','lek'),
('En la Farmacia','W aptece','la pastilla / la píldora','tabletka / pigułka'),
('En la Farmacia','W aptece','la cápsula','kapsułka'),
('En la Farmacia','W aptece','el jarabe','syrop'),
('En la Farmacia','W aptece','la pomada / la crema','maść / krem'),
('En la Farmacia','W aptece','el gel','żel'),
('En la Farmacia','W aptece','las gotas','krople'),
('En la Farmacia','W aptece','el supositorio','czopek'),
('En la Farmacia','W aptece','el antibiótico','antybiotyk'),
('En la Farmacia','W aptece','el analgésico','środek przeciwbólowy'),
('En la Farmacia','W aptece','el antiinflamatorio','lek przeciwzapalny'),
('En la Farmacia','W aptece','la aspirina','aspiryna'),
('En la Farmacia','W aptece','el paracetamol','paracetamol'),
('En la Farmacia','W aptece','el ibuprofeno','ibuprofen'),
('En la Farmacia','W aptece','el jarabe para la tos','syrop na kaszel'),
('En la Farmacia','W aptece','las vitaminas','witaminy'),
('En la Farmacia','W aptece','la receta médica','recepta lekarska'),
('En la Farmacia','W aptece','el prospecto','ulotka (dołączona do leku)'),
('En la Farmacia','W aptece','la dosis','dawka'),
('En la Farmacia','W aptece','los efectos secundarios','skutki uboczne'),
('En la Farmacia','W aptece','la fecha de caducidad','data ważności'),
('En la Farmacia','W aptece','caducado','przeterminowany'),
('En la Farmacia','W aptece','la tirita / la curita','plaster'),
('En la Farmacia','W aptece','el vendaje / la venda','bandaż'),
('En la Farmacia','W aptece','el algodón','wata'),
('En la Farmacia','W aptece','el alcohol','spirytus salicylowy'),
('En la Farmacia','W aptece','el agua oxigenada','woda utleniona'),
('En la Farmacia','W aptece','el desinfectante','środek dezynfekujący'),
('En la Farmacia','W aptece','la jeringa','strzykawka'),
('En la Farmacia','W aptece','la aguja','igła'),
('En la Farmacia','W aptece','el termómetro','termometr'),
('En la Farmacia','W aptece','el preservativo','prezerwatywa'),
('En la Farmacia','W aptece','la prueba de embarazo','test ciążowy'),
('En la Farmacia','W aptece','el colirio','krople do oczu'),
('En la Farmacia','W aptece','el botiquín','apteczka'),
('En la Farmacia','W aptece','aliviar','przynosić ulgę / łagodzić'),
('En la Farmacia','W aptece','chupar','ssać (np. tabletkę)'),
('En la Farmacia','W aptece','tragar','połykać'),
('En la Farmacia','W aptece','aplicar','nakładać / aplikować'),
('En la Farmacia','W aptece','la alergia','alergia'),
('En la Farmacia','W aptece','el antihistamínico','lek przeciwhistaminowy'),
('En la Farmacia','W aptece','el somnífero','lek nasenny'),
('En la Farmacia','W aptece','la receta electrónica','e-recepta'),
('En la Farmacia','W aptece','de venta libre','bez recepty'),
('En la Farmacia','W aptece','la gasa','gaza'),
('En la Farmacia','W aptece','el esparadrapo','przylepiec / taśma medyczna'),
('En la Farmacia','W aptece','el ungüento','maść (tłusta)');
