insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Los Números','Liczby','cero','zero'),
('Los Números','Liczby','uno','jeden'),
('Los Números','Liczby','dos','dwa'),
('Los Números','Liczby','tres','trzy'),
('Los Números','Liczby','cuatro','cztery'),
('Los Números','Liczby','cinco','pięć'),
('Los Números','Liczby','seis','sześć'),
('Los Números','Liczby','siete','siedem'),
('Los Números','Liczby','ocho','osiem'),
('Los Números','Liczby','nueve','dziewięć'),
('Los Números','Liczby','diez','dziesięć'),
('Los Números','Liczby','once','jedenaście'),
('Los Números','Liczby','doce','dwanaście'),
('Los Números','Liczby','trece','trzynaście'),
('Los Números','Liczby','catorce','czternaście'),
('Los Números','Liczby','quince','piętnaście'),
('Los Números','Liczby','dieciséis','szesnaście'),
('Los Números','Liczby','diecisiete','siedemnaście'),
('Los Números','Liczby','dieciocho','osiemnaście'),
('Los Números','Liczby','diecinueve','dziewiętnaście'),
('Los Números','Liczby','veinte','dwadzieścia'),
('Los Números','Liczby','veintiuno','dwadzieścia jeden'),
('Los Números','Liczby','treinta','trzydzieści'),
('Los Números','Liczby','cuarenta','czterdzieści'),
('Los Números','Liczby','cincuenta','pięćdziesiąt'),
('Los Números','Liczby','sesenta','sześćdziesiąt'),
('Los Números','Liczby','setenta','siedemdziesiąt'),
('Los Números','Liczby','ochenta','osiemdziesiąt'),
('Los Números','Liczby','noventa','dziewięćdziesiąt'),
('Los Números','Liczby','cien','sto'),
('Los Números','Liczby','ciento uno','sto jeden'),
('Los Números','Liczby','doscientos','dwieście'),
('Los Números','Liczby','trescientos','trzysta'),
('Los Números','Liczby','quinientos','pięćset'),
('Los Números','Liczby','mil','tysiąc'),
('Los Números','Liczby','un millón','milion'),
('Los Números','Liczby','un billón','bilion'),
('Los Números','Liczby','la mitad','połowa'),
('Los Números','Liczby','un tercio','jedna trzecia'),
('Los Números','Liczby','un cuarto','jedna czwarta'),
('Los Números','Liczby','primero','pierwszy'),
('Los Números','Liczby','segundo','drugi'),
('Los Números','Liczby','tercero','trzeci'),
('Los Números','Liczby','cuarto','czwarty'),
('Los Números','Liczby','quinto','piąty'),
('Los Números','Liczby','sexto','szósty'),
('Los Números','Liczby','séptimo','siódmy'),
('Los Números','Liczby','octavo','ósmy'),
('Los Números','Liczby','noveno','dziewiąty'),
('Los Números','Liczby','décimo','dziesiąty'),
('El Tiempo','Czas','el tiempo','czas / pogoda'),
('El Tiempo','Czas','la hora','godzina'),
('El Tiempo','Czas','el minuto','minuta'),
('El Tiempo','Czas','el segundo','sekunda'),
('El Tiempo','Czas','el día','dzień'),
('El Tiempo','Czas','la semana','tydzień'),
('El Tiempo','Czas','el fin de semana','weekend'),
('El Tiempo','Czas','el mes','miesiąc'),
('El Tiempo','Czas','el año','rok'),
('El Tiempo','Czas','la década','dekada'),
('El Tiempo','Czas','el siglo','wiek / stulecie'),
('El Tiempo','Czas','el milenio','tysiąclecie'),
('El Tiempo','Czas','hoy','dzisiaj'),
('El Tiempo','Czas','mañana','jutro / rano'),
('El Tiempo','Czas','ayer','wczoraj'),
('El Tiempo','Czas','anteayer','przedwczoraj'),
('El Tiempo','Czas','pasado mañana','pojutrze'),
('El Tiempo','Czas','la madrugada','świt / wczesny ranek'),
('El Tiempo','Czas','la mañana','poranek'),
('El Tiempo','Czas','el mediodía','południe'),
('El Tiempo','Czas','la tarde','popołudnie'),
('El Tiempo','Czas','la noche','noc'),
('El Tiempo','Czas','la medianoche','północ'),
('El Tiempo','Czas','el amanecer','wschód słońca'),
('El Tiempo','Czas','el atardecer','zachód słońca'),
('El Tiempo','Czas','la fecha','data'),
('El Tiempo','Czas','el calendario','kalendarz'),
('El Tiempo','Czas','el reloj','zegar / zegarek'),
('El Tiempo','Czas','el reloj de pulsera','zegarek na rękę'),
('El Tiempo','Czas','el reloj de pared','zegar ścienny'),
('El Tiempo','Czas','el despertador','budzik'),
('El Tiempo','Czas','pronto','wkrótce / wcześnie'),
('El Tiempo','Czas','tarde','późno'),
('El Tiempo','Czas','temprano','wcześnie'),
('El Tiempo','Czas','ahora','teraz'),
('El Tiempo','Czas','luego','później'),
('El Tiempo','Czas','antes','wcześniej / przedtem'),
('El Tiempo','Czas','después','potem'),
('El Tiempo','Czas','siempre','zawsze'),
('El Tiempo','Czas','nunca','nigdy'),
('El Tiempo','Czas','a veces','czasami'),
('El Tiempo','Czas','a menudo','często'),
('El Tiempo','Czas','de vez en cuando','od czasu do czasu'),
('El Tiempo','Czas','diariamente','codziennie'),
('El Tiempo','Czas','semanalmente','cotygodniowo'),
('El Tiempo','Czas','mensualmente','miesięcznie'),
('El Tiempo','Czas','anualmente','rocznie'),
('El Tiempo','Czas','puntual','punktualny'),
('El Tiempo','Czas','retrasado','opóźniony'),
('El Tiempo','Czas','la duración','czas trwania'),
('El Clima','Pogoda','el sol','słońce'),
('El Clima','Pogoda','la lluvia','deszcz'),
('El Clima','Pogoda','la nieve','śnieg'),
('El Clima','Pogoda','el viento','wiatr'),
('El Clima','Pogoda','la nube','chmura'),
('El Clima','Pogoda','la tormenta','burza'),
('El Clima','Pogoda','el relámpago','błyskawica'),
('El Clima','Pogoda','el trueno','grzmot'),
('El Clima','Pogoda','el granizo','grad'),
('El Clima','Pogoda','la niebla','mgła'),
('El Clima','Pogoda','el hielo','lód'),
('El Clima','Pogoda','el calor','upał'),
('El Clima','Pogoda','el frío','zimno / chłód'),
('El Clima','Pogoda','la temperatura','temperatura'),
('El Clima','Pogoda','el grado','stopień'),
('El Clima','Pogoda','el pronóstico','prognoza pogody'),
('El Clima','Pogoda','el huracán','huragan'),
('El Clima','Pogoda','el tornado','tornado'),
('El Clima','Pogoda','el arcoíris','tęcza'),
('El Clima','Pogoda','el clima','klimat'),
('El Clima','Pogoda','soleado','słoneczny'),
('El Clima','Pogoda','nublado','pochmurny'),
('El Clima','Pogoda','lluvioso','deszczowy'),
('El Clima','Pogoda','ventoso','wietrzny'),
('El Clima','Pogoda','despejado','bezchmurny'),
('El Clima','Pogoda','húmedo','wilgotny'),
('El Clima','Pogoda','seco','suchy'),
('El Clima','Pogoda','la humedad','wilgotność'),
('El Clima','Pogoda','la sequía','susza'),
('El Clima','Pogoda','la inundación','powódź'),
('El Clima','Pogoda','llover','padać (o deszczu)'),
('El Clima','Pogoda','nevar','padać (o śniegu)'),
('El Clima','Pogoda','helar','zamarzać'),
('El Clima','Pogoda','derretir','topnieć'),
('El Clima','Pogoda','la brisa','bryza'),
('El Clima','Pogoda','el chaparrón','ulewa / kapuśniaczek'),
('El Clima','Pogoda','el charco','kałuża'),
('El Clima','Pogoda','el termómetro','termometr'),
('El Clima','Pogoda','el invierno','zima'),
('El Clima','Pogoda','la primavera','wiosna'),
('El Clima','Pogoda','el verano','lato'),
('El Clima','Pogoda','el otoño','jesień'),
('El Clima','Pogoda','el chubasco','przlotny deszcz'),
('El Clima','Pogoda','la ráfaga','poryw wiatru'),
('El Clima','Pogoda','la escarcha','szron'),
('El Clima','Pogoda','el bochorno','parno / duchota'),
('El Clima','Pogoda','templado','umiarkowany / łagodny'),
('El Clima','Pogoda','el monzón','monsun'),
('El Clima','Pogoda','la gota','kropla'),
('El Clima','Pogoda','el paraguas','parasol'),
('La Naturaleza','Natura','la naturaleza','natura / przyroda'),
('La Naturaleza','Natura','el árbol','drzewo'),
('La Naturaleza','Natura','el bosque','las'),
('La Naturaleza','Natura','la selva','dżungla / puszcza'),
('La Naturaleza','Natura','la montaña','góra'),
('La Naturaleza','Natura','la colina','wzgórze'),
('La Naturaleza','Natura','el valle','dolina'),
('La Naturaleza','Natura','el río','rzeka'),
('La Naturaleza','Natura','el lago','jezioro'),
('La Naturaleza','Natura','el mar','morze'),
('La Naturaleza','Natura','el océano','ocean'),
('La Naturaleza','Natura','la playa','plaża'),
('La Naturaleza','Natura','la arena','piasek'),
('La Naturaleza','Natura','la isla','wyspa'),
('La Naturaleza','Natura','la costa','wybrzeże'),
('La Naturaleza','Natura','el desierto','pustynia'),
('La Naturaleza','Natura','la tierra','ziemia'),
('La Naturaleza','Natura','el suelo','gleba / grunt'),
('La Naturaleza','Natura','la piedra','kamień'),
('La Naturaleza','Natura','la roca','skała'),
('La Naturaleza','Natura','el mineral','minerał'),
('La Naturaleza','Natura','la hierba','trawa'),
('La Naturaleza','Natura','el césped','trawnik'),
('La Naturaleza','Natura','la planta','roślina'),
('La Naturaleza','Natura','la flor','kwiat'),
('La Naturaleza','Natura','la hoja','liść'),
('La Naturaleza','Natura','la rama','gałąź'),
('La Naturaleza','Natura','la raíz','korzeń'),
('La Naturaleza','Natura','el tronco','pień'),
('La Naturaleza','Natura','el arbusto','krzew'),
('La Naturaleza','Natura','la semilla','nasiono'),
('La Naturaleza','Natura','el fuego','ogień'),
('La Naturaleza','Natura','el aire','powietrze'),
('La Naturaleza','Natura','el agua','woda'),
('La Naturaleza','Natura','el paisaje','krajobraz'),
('La Naturaleza','Natura','el volcán','wulkan'),
('La Naturaleza','Natura','la cueva','jaskinia'),
('La Naturaleza','Natura','la cascada','wodospad'),
('La Naturaleza','Natura','el campo','pole / wieś'),
('La Naturaleza','Natura','el prado','łąka'),
('La Naturaleza','Natura','la fauna','fauna'),
('La Naturaleza','Natura','la flora','flora'),
('La Naturaleza','Natura','la ecología','ekologia'),
('La Naturaleza','Natura','el medio ambiente','środowisko naturalne'),
('La Naturaleza','Natura','la contaminación','zanieczyszczenie'),
('La Naturaleza','Natura','proteger','chronić'),
('La Naturaleza','Natura','el parque nacional','park narodowy'),
('La Naturaleza','Natura','la reserva','rezerwat'),
('La Naturaleza','Natura','el camino','ścieżka / droga'),
('La Naturaleza','Natura','el cielo','niebo');
