insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('El Periódico','Gazeta','el periódico','gazeta'),
('El Periódico','Gazeta','la revista','magazyn / czasopismo'),
('El Periódico','Gazeta','la prensa','prasa'),
('El Periódico','Gazeta','la noticia','wiadomość'),
('El Periódico','Gazeta','el periodista','dziennikarz'),
('El Periódico','Gazeta','la periodista','dziennikarka'),
('El Periódico','Gazeta','el artículo','artykuł'),
('El Periódico','Gazeta','el titular','nagłówek'),
('El Periódico','Gazeta','la portada','okładka / pierwsza strona'),
('El Periódico','Gazeta','la columna','kolumna'),
('El Periódico','Gazeta','el editorial','artykuł wstępny (edytorial)'),
('El Periódico','Gazeta','la entrevista','wywiad'),
('El Periódico','Gazeta','el reportaje','reportaż'),
('El Periódico','Gazeta','el reportero','reporter'),
('El Periódico','Gazeta','la sección','sekcja / dział'),
('El Periódico','Gazeta','las noticias locales','wiadomości lokalne'),
('El Periódico','Gazeta','las noticias internacionales','wiadomości międzynarodowe'),
('El Periódico','Gazeta','la sección de deportes','dział sportowy'),
('El Periódico','Gazeta','la sección de economía','dział gospodarczy'),
('El Periódico','Gazeta','la cultura','kultura'),
('El Periódico','Gazeta','el anuncio','ogłoszenie / reklama'),
('El Periódico','Gazeta','los clasificados','ogłoszenia drobne'),
('El Periódico','Gazeta','la tira cómica','komiks / pasek komiksowy'),
('El Periódico','Gazeta','el crucigrama','krzyżówka'),
('El Periódico','Gazeta','el horóscopo','horoskop'),
('El Periódico','Gazeta','el quiosco','kiosk'),
('El Periódico','Gazeta','el suscriptor','prenumerator'),
('El Periódico','Gazeta','la suscripción','prenumerata / subskrypcja'),
('El Periódico','Gazeta','publicar','publikować'),
('El Periódico','Gazeta','editar','edytować / wydawać'),
('El Periódico','Gazeta','el editor','redaktor / wydawca'),
('El Periódico','Gazeta','el redactor','redaktor (piszący)'),
('El Periódico','Gazeta','la redacción','redakcja'),
('El Periódico','Gazeta','la fuente','źródło (informacji)'),
('El Periódico','Gazeta','la objetividad','obiektywizm'),
('El Periódico','Gazeta','la censura','cenzura'),
('El Periódico','Gazeta','el tabloide','tabloid'),
('El Periódico','Gazeta','la tirada','nakład'),
('El Periódico','Gazeta','imprimir','drukować'),
('El Periódico','Gazeta','la imprenta','drukarnia'),
('El Periódico','Gazeta','el suplemento','dodatek (do gazety)'),
('El Periódico','Gazeta','la crítica','recenzja / krytyka'),
('El Periódico','Gazeta','la exclusiva','materiał na wyłączność (exclusive)'),
('El Periódico','Gazeta','el chisme / el cotilleo','plotka'),
('El Periódico','Gazeta','la prensa amarilla','prasa brukowa'),
('El Periódico','Gazeta','el corresponsal','korespondent'),
('El Periódico','Gazeta','el fotógrafo','fotograf'),
('El Periódico','Gazeta','leer','czytać'),
('El Periódico','Gazeta','hojear','kartkować'),
('El Periódico','Gazeta','enterarse','dowiadywać się'),
('Televisión y Radio','Telewizja i Radio','la televisión / la tele','telewizja'),
('Televisión y Radio','Telewizja i Radio','el televisor','telewizor'),
('Televisión y Radio','Telewizja i Radio','la radio','radio'),
('Televisión y Radio','Telewizja i Radio','el programa','program'),
('Televisión y Radio','Telewizja i Radio','el canal','kanał'),
('Televisión y Radio','Telewizja i Radio','la emisora','stacja (radiowa)'),
('Televisión y Radio','Telewizja i Radio','la cadena','sieć (telewizyjna/radiowa)'),
('Televisión y Radio','Telewizja i Radio','el mando a distancia','pilot (do telewizora)'),
('Televisión y Radio','Telewizja i Radio','la pantalla','ekran'),
('Televisión y Radio','Telewizja i Radio','el volumen','głośność'),
('Televisión y Radio','Telewizja i Radio','encender','włączać'),
('Televisión y Radio','Telewizja i Radio','apagar','wyłączać'),
('Televisión y Radio','Telewizja i Radio','cambiar de canal','zmieniać kanał'),
('Televisión y Radio','Telewizja i Radio','el telediario / las noticias','dziennik / wiadomości'),
('Televisión y Radio','Telewizja i Radio','la serie','serial'),
('Televisión y Radio','Telewizja i Radio','la telenovela','telenowela'),
('Televisión y Radio','Telewizja i Radio','el documental','film dokumentalny'),
('Televisión y Radio','Telewizja i Radio','el concurso','teleturniej'),
('Televisión y Radio','Telewizja i Radio','el programa de entrevistas','talk-show'),
('Televisión y Radio','Telewizja i Radio','los dibujos animados','kreskówki'),
('Televisión y Radio','Telewizja i Radio','la película','film'),
('Televisión y Radio','Telewizja i Radio','el anuncio','reklama'),
('Televisión y Radio','Telewizja i Radio','la pausa publicitaria','przerwa na reklamę'),
('Televisión y Radio','Telewizja i Radio','el presentador','prezenter'),
('Televisión y Radio','Telewizja i Radio','el locutor','spiker / prezenter radiowy'),
('Televisión y Radio','Telewizja i Radio','la audiencia','widownia / słuchacze'),
('Televisión y Radio','Telewizja i Radio','el espectador','widz'),
('Televisión y Radio','Telewizja i Radio','el oyente','słuchacz'),
('Televisión y Radio','Telewizja i Radio','el micrófono','mikrofon'),
('Televisión y Radio','Telewizja i Radio','la antena','antena'),
('Televisión y Radio','Telewizja i Radio','transmitir / emitir','nadawać / emitować'),
('Televisión y Radio','Telewizja i Radio','la transmisión / la emisión','emisja / transmisja'),
('Televisión y Radio','Telewizja i Radio','en directo / en vivo','na żywo'),
('Televisión y Radio','Telewizja i Radio','grabado','nagrany'),
('Televisión y Radio','Telewizja i Radio','el episodio','odcinek'),
('Televisión y Radio','Telewizja i Radio','la temporada','sezon (serialu)'),
('Televisión y Radio','Telewizja i Radio','sintonizar','dostroić / włączyć stację'),
('Televisión y Radio','Telewizja i Radio','el dial','tarcza (w radiu) / częstotliwość'),
('Televisión y Radio','Telewizja i Radio','el podcast','podcast'),
('Televisión y Radio','Telewizja i Radio','el volumen alto','wysoka głośność'),
('Televisión y Radio','Telewizja i Radio','el volumen bajo','niska głośność'),
('Televisión y Radio','Telewizja i Radio','subir el volumen','zgłośnić'),
('Televisión y Radio','Telewizja i Radio','bajar el volumen','ściszyć'),
('Televisión y Radio','Telewizja i Radio','el satélite','satelita'),
('Televisión y Radio','Telewizja i Radio','la televisión por cable','telewizja kablowa'),
('Televisión y Radio','Telewizja i Radio','la programación','ramówka / program'),
('Televisión y Radio','Telewizja i Radio','el guion','scenariusz'),
('Televisión y Radio','Telewizja i Radio','el plató','studio telewizyjne'),
('Televisión y Radio','Telewizja i Radio','los subtítulos','napisy'),
('Televisión y Radio','Telewizja i Radio','el doblaje','dubbing'),
('Cine y Teatro','Kino i Teatr','el cine','kino'),
('Cine y Teatro','Kino i Teatr','el teatro','teatr'),
('Cine y Teatro','Kino i Teatr','la película','film'),
('Cine y Teatro','Kino i Teatr','la obra de teatro','sztuka teatralna'),
('Cine y Teatro','Kino i Teatr','el actor','aktor'),
('Cine y Teatro','Kino i Teatr','la actriz','aktorka'),
('Cine y Teatro','Kino i Teatr','el director','reżyser'),
('Cine y Teatro','Kino i Teatr','dirigir','reżyserować'),
('Cine y Teatro','Kino i Teatr','el guion','scenariusz'),
('Cine y Teatro','Kino i Teatr','el guionista','scenarzysta'),
('Cine y Teatro','Kino i Teatr','el escenario','scena'),
('Cine y Teatro','Kino i Teatr','el telón','kurtyna'),
('Cine y Teatro','Kino i Teatr','la pantalla','ekran'),
('Cine y Teatro','Kino i Teatr','la butaca','fotel (w kinie/teatrze)'),
('Cine y Teatro','Kino i Teatr','la fila','rząd'),
('Cine y Teatro','Kino i Teatr','el pasillo','korytarz / przejście'),
('Cine y Teatro','Kino i Teatr','la entrada','bilet'),
('Cine y Teatro','Kino i Teatr','la taquilla','kasa biletowa'),
('Cine y Teatro','Kino i Teatr','el acomodador','bileter'),
('Cine y Teatro','Kino i Teatr','el estreno','premiera'),
('Cine y Teatro','Kino i Teatr','la cartelera','repertuar'),
('Cine y Teatro','Kino i Teatr','el espectador','widz'),
('Cine y Teatro','Kino i Teatr','el público','publiczność'),
('Cine y Teatro','Kino i Teatr','aplaudir','klaskać'),
('Cine y Teatro','Kino i Teatr','el aplauso','oklaski'),
('Cine y Teatro','Kino i Teatr','actuar','grać (rolę)'),
('Cine y Teatro','Kino i Teatr','la actuación','występ / gra aktorska'),
('Cine y Teatro','Kino i Teatr','el personaje','postać'),
('Cine y Teatro','Kino i Teatr','el protagonista','główny bohater'),
('Cine y Teatro','Kino i Teatr','el papel','rola'),
('Cine y Teatro','Kino i Teatr','el ensayo','próba'),
('Cine y Teatro','Kino i Teatr','ensayar','odbywać próbę'),
('Cine y Teatro','Kino i Teatr','el camerino','garderoba'),
('Cine y Teatro','Kino i Teatr','el maquillaje','makijaż / charakteryzacja'),
('Cine y Teatro','Kino i Teatr','el vestuario','kostiumy'),
('Cine y Teatro','Kino i Teatr','el decorado','dekoracja / scenografia'),
('Cine y Teatro','Kino i Teatr','la iluminación','oświetlenie'),
('Cine y Teatro','Kino i Teatr','los efectos especiales','efekty specjalne'),
('Cine y Teatro','Kino i Teatr','la banda sonora','ścieżka dźwiękowa'),
('Cine y Teatro','Kino i Teatr','el tráiler','zwiastun'),
('Cine y Teatro','Kino i Teatr','el cortometraje','film krótkometrażowy'),
('Cine y Teatro','Kino i Teatr','el largometraje','film pełnometrażowy'),
('Cine y Teatro','Kino i Teatr','la comedia','komedia'),
('Cine y Teatro','Kino i Teatr','el drama','dramat'),
('Cine y Teatro','Kino i Teatr','el musical','musical'),
('Cine y Teatro','Kino i Teatr','el intermedio','przerwa / antrakt'),
('Cine y Teatro','Kino i Teatr','las palomitas','popcorn'),
('Cine y Teatro','Kino i Teatr','el premio','nagroda'),
('Cine y Teatro','Kino i Teatr','nominar','nominować'),
('Cine y Teatro','Kino i Teatr','rodar','kręcić (film)'),
('Profesiones Médicas','Zawody medyczne','el médico / la médica','lekarz / lekarka'),
('Profesiones Médicas','Zawody medyczne','el enfermero / la enfermera','pielęgniarz / pielęgniarka'),
('Profesiones Médicas','Zawody medyczne','el cirujano','chirurg'),
('Profesiones Médicas','Zawody medyczne','el anestesista','anestezjolog'),
('Profesiones Médicas','Zawody medyczne','el pediatra','pediatra'),
('Profesiones Médicas','Zawody medyczne','el cardiólogo','kardiolog'),
('Profesiones Médicas','Zawody medyczne','el dermatólogo','dermatolog'),
('Profesiones Médicas','Zawody medyczne','el ginecólogo','ginekolog'),
('Profesiones Médicas','Zawody medyczne','el obstetra','położnik'),
('Profesiones Médicas','Zawody medyczne','la matrona','położna'),
('Profesiones Médicas','Zawody medyczne','el neurólogo','neurolog'),
('Profesiones Médicas','Zawody medyczne','el psiquiatra','psychiatra'),
('Profesiones Médicas','Zawody medyczne','el psicólogo','psycholog'),
('Profesiones Médicas','Zawody medyczne','el oftalmólogo','okulista'),
('Profesiones Médicas','Zawody medyczne','el dentista / el odontólogo','dentysta / stomatolog'),
('Profesiones Médicas','Zawody medyczne','el ortodoncista','ortodonta'),
('Profesiones Médicas','Zawody medyczne','el traumatólogo','traumatolog / ortopeda'),
('Profesiones Médicas','Zawody medyczne','el fisioterapeuta','fizjoterapeuta'),
('Profesiones Médicas','Zawody medyczne','el farmacéutico','farmaceuta'),
('Profesiones Médicas','Zawody medyczne','el veterinario','weterynarz'),
('Profesiones Médicas','Zawody medyczne','el oncólogo','onkolog'),
('Profesiones Médicas','Zawody medyczne','el urólogo','urolog'),
('Profesiones Médicas','Zawody medyczne','el endocrino','endokrynolog'),
('Profesiones Médicas','Zawody medyczne','el alergólogo','alergolog'),
('Profesiones Médicas','Zawody medyczne','el neumólogo','pulmonolog'),
('Profesiones Médicas','Zawody medyczne','el gastroenterólogo','gastrolog'),
('Profesiones Médicas','Zawody medyczne','el radiólogo','radiolog'),
('Profesiones Médicas','Zawody medyczne','el patólogo','patolog'),
('Profesiones Médicas','Zawody medyczne','el paramédico','ratownik medyczny'),
('Profesiones Médicas','Zawody medyczne','el asistente médico','asystent medyczny'),
('Profesiones Médicas','Zawody medyczne','el celador','sanitariusz (w szpitalu)'),
('Profesiones Médicas','Zawody medyczne','el nutricionista','dietetyk'),
('Profesiones Médicas','Zawody medyczne','el terapeuta ocupacional','terapeuta zajęciowy'),
('Profesiones Médicas','Zawody medyczne','el logopeda','logopeda'),
('Profesiones Médicas','Zawody medyczne','el podólogo','podolog'),
('Profesiones Médicas','Zawody medyczne','el quiropráctico','kręgarz / chiropraktyk'),
('Profesiones Médicas','Zawody medyczne','el cirujano plástico','chirurg plastyczny'),
('Profesiones Médicas','Zawody medyczne','el médico de cabecera','lekarz rodzinny'),
('Profesiones Médicas','Zawody medyczne','el médico de urgencias','lekarz pogotowia / ratunkowy'),
('Profesiones Médicas','Zawody medyczne','el hematólogo','hematolog'),
('Profesiones Médicas','Zawody medyczne','el reumatólogo','reumatolog'),
('Profesiones Médicas','Zawody medyczne','el nefrólogo','nefrolog'),
('Profesiones Médicas','Zawody medyczne','el otorrinolaringólogo','laryngolog'),
('Profesiones Médicas','Zawody medyczne','el epidemiólogo','epidemiolog'),
('Profesiones Médicas','Zawody medyczne','el inmunólogo','immunolog'),
('Profesiones Médicas','Zawody medyczne','el forense','lekarz medycyny sądowej'),
('Profesiones Médicas','Zawody medyczne','el técnico de laboratorio','technik laboratoryjny'),
('Profesiones Médicas','Zawody medyczne','el óptico','optyk'),
('Profesiones Médicas','Zawody medyczne','el osteópata','osteopata'),
('Profesiones Médicas','Zawody medyczne','el especialista','specjalista');
