insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Medio Ambiente','Środowisko naturalne','el medio ambiente','środowisko naturalne'),
('Medio Ambiente','Środowisko naturalne','la naturaleza','natura'),
('Medio Ambiente','Środowisko naturalne','la ecología','ekologia'),
('Medio Ambiente','Środowisko naturalne','el ecosistema','ekosystem'),
('Medio Ambiente','Środowisko naturalne','la biodiversidad','bioróżnorodność'),
('Medio Ambiente','Środowisko naturalne','la fauna','fauna'),
('Medio Ambiente','Środowisko naturalne','la flora','flora'),
('Medio Ambiente','Środowisko naturalne','el hábitat','siedlisko'),
('Medio Ambiente','Środowisko naturalne','la conservación','ochrona / konserwacja'),
('Medio Ambiente','Środowisko naturalne','proteger','chronić'),
('Medio Ambiente','Środowisko naturalne','la contaminación','zanieczyszczenie'),
('Medio Ambiente','Środowisko naturalne','contaminar','zanieczyszczać'),
('Medio Ambiente','Środowisko naturalne','la polución','smog / zanieczyszczenie (powietrza)'),
('Medio Ambiente','Środowisko naturalne','el calentamiento global','globalne ocieplenie'),
('Medio Ambiente','Środowisko naturalne','el cambio climático','zmiana klimatu'),
('Medio Ambiente','Środowisko naturalne','el efecto invernadero','efekt cieplarniany'),
('Medio Ambiente','Środowisko naturalne','la emisión de gases','emisja gazów'),
('Medio Ambiente','Środowisko naturalne','el dióxido de carbono','dwutlenek węgla'),
('Medio Ambiente','Środowisko naturalne','la huella de carbono','ślad węglowy'),
('Medio Ambiente','Środowisko naturalne','la capa de ozono','warstwa ozonowa'),
('Medio Ambiente','Środowisko naturalne','la deforestación','wylesianie'),
('Medio Ambiente','Środowisko naturalne','la tala de árboles','wycinka drzew'),
('Medio Ambiente','Środowisko naturalne','los recursos naturales','zasoby naturalne'),
('Medio Ambiente','Środowisko naturalne','la energía renovable','energia odnawialna'),
('Medio Ambiente','Środowisko naturalne','la energía solar','energia słoneczna'),
('Medio Ambiente','Środowisko naturalne','la energía eólica','energia wiatrowa'),
('Medio Ambiente','Środowisko naturalne','la energía nuclear','energia jądrowa'),
('Medio Ambiente','Środowisko naturalne','sostenible','zrównoważony'),
('Medio Ambiente','Środowisko naturalne','la sostenibilidad','zrównoważony rozwój'),
('Medio Ambiente','Środowisko naturalne','el ecologista','ekolog'),
('Medio Ambiente','Środowisko naturalne','verde','zielony / ekologiczny'),
('Medio Ambiente','Środowisko naturalne','la basura','śmieci'),
('Medio Ambiente','Środowisko naturalne','el residuo / el desecho','odpad / resztka'),
('Medio Ambiente','Środowisko naturalne','el vertedero','wysypisko śmieci'),
('Medio Ambiente','Środowisko naturalne','tóxico','toksyczny'),
('Medio Ambiente','Środowisko naturalne','el pesticida','pestycyd'),
('Medio Ambiente','Środowisko naturalne','en peligro de extinción','zagrożony wyginięciem'),
('Medio Ambiente','Środowisko naturalne','la extinción','wyginięcie'),
('Medio Ambiente','Środowisko naturalne','la sobreexplotación','nadmierna eksploatacja'),
('Medio Ambiente','Środowisko naturalne','el agua potable','woda pitna'),
('Medio Ambiente','Środowisko naturalne','purificar','oczyszczać'),
('Medio Ambiente','Środowisko naturalne','el aire puro','czyste powietrze'),
('Medio Ambiente','Środowisko naturalne','la reserva natural','rezerwat przyrody'),
('Medio Ambiente','Środowisko naturalne','el parque nacional','park narodowy'),
('Medio Ambiente','Środowisko naturalne','la biosfera','biosfera'),
('Medio Ambiente','Środowisko naturalne','la degradación','degradacja'),
('Medio Ambiente','Środowisko naturalne','el impacto ambiental','wpływ na środowisko'),
('Medio Ambiente','Środowisko naturalne','la concienciación','budowanie świadomości'),
('Medio Ambiente','Środowisko naturalne','concienciar','uświadamiać'),
('Medio Ambiente','Środowisko naturalne','preservar','zachowywać / chronić'),
('Reciclaje','Recykling','el reciclaje','recykling'),
('Reciclaje','Recykling','reciclar','przetwarzać / poddawać recyklingowi'),
('Reciclaje','Recykling','reutilizar','używać ponownie'),
('Reciclaje','Recykling','reducir','redukować / zmniejszać'),
('Reciclaje','Recykling','el contenedor','kontener / pojemnik'),
('Reciclaje','Recykling','la basura','śmieci'),
('Reciclaje','Recykling','la papelera','kosz na śmieci'),
('Reciclaje','Recykling','el cubo de basura','wiaderko na śmieci'),
('Reciclaje','Recykling','la separación de residuos','segregacja odpadów'),
('Reciclaje','Recykling','separar','segregować / oddzielać'),
('Reciclaje','Recykling','clasificar','klasyfikować / sortować'),
('Reciclaje','Recykling','el residuo','odpad'),
('Reciclaje','Recykling','el desecho','odpadek'),
('Reciclaje','Recykling','orgánico','organiczny'),
('Reciclaje','Recykling','inorgánico','nieorganiczny'),
('Reciclaje','Recykling','el plástico','plastik'),
('Reciclaje','Recykling','el vidrio','szkło (np. butelki)'),
('Reciclaje','Recykling','el cartón','karton'),
('Reciclaje','Recykling','el papel','papier'),
('Reciclaje','Recykling','el envase','opakowanie / pojemnik'),
('Reciclaje','Recykling','el envoltorio','opakowanie / papierek'),
('Reciclaje','Recykling','la lata','puszka'),
('Reciclaje','Recykling','la botella','butelka'),
('Reciclaje','Recykling','el metal','metal'),
('Reciclaje','Recykling','el aluminio','aluminium'),
('Reciclaje','Recykling','la pila','bateria (np. paluszek)'),
('Reciclaje','Recykling','la batería','bateria / akumulator'),
('Reciclaje','Recykling','la chatarra','złom'),
('Reciclaje','Recykling','el escombro','gruz / śmieci budowlane'),
('Reciclaje','Recykling','el punto limpio / el ecopunto','punkt zbiórki odpadów (PSZOK)'),
('Reciclaje','Recykling','la planta de reciclaje','zakład recyklingu'),
('Reciclaje','Recykling','la bolsa de plástico','torba foliowa / reklamówka'),
('Reciclaje','Recykling','la bolsa de tela','torba materiałowa'),
('Reciclaje','Recykling','biodegradable','biodegradowalny'),
('Reciclaje','Recykling','el compost','kompost'),
('Reciclaje','Recykling','el abono','nawóz'),
('Reciclaje','Recykling','ecológico','ekologiczny'),
('Reciclaje','Recykling','el desperdicio','marnotrawstwo / odpad'),
('Reciclaje','Recykling','desperdiciar','marnować'),
('Reciclaje','Recykling','tirar (a la basura)','wyrzucać (do śmieci)'),
('Reciclaje','Recykling','recoger','zbierać'),
('Reciclaje','Recykling','el material reciclado','materiał z recyklingu'),
('Reciclaje','Recykling','el embalaje','opakowanie (transportowe)'),
('Reciclaje','Recykling','contaminante','zanieczyszczający (substancja)'),
('Reciclaje','Recykling','verter','wylewać / wyrzucać na wysypisko'),
('Reciclaje','Recykling','el vertedero','wysypisko śmieci'),
('Reciclaje','Recykling','el residuo tóxico','odpad toksyczny'),
('Reciclaje','Recykling','la economía circular','gospodarka obiegu zamkniętego'),
('Reciclaje','Recykling','cero residuos (zero waste)','zero odpadów'),
('Reciclaje','Recykling','recuperar','odzyskiwać'),
('El Universo','Wszechświat','el universo','wszechświat'),
('El Universo','Wszechświat','el cosmos','kosmos'),
('El Universo','Wszechświat','el espacio exterior','przestrzeń kosmiczna'),
('El Universo','Wszechświat','la galaxia','galaktyka'),
('El Universo','Wszechświat','la Vía Láctea','Droga Mleczna'),
('El Universo','Wszechświat','el sistema solar','układ słoneczny'),
('El Universo','Wszechświat','la estrella','gwiazda'),
('El Universo','Wszechświat','el planeta','planeta'),
('El Universo','Wszechświat','la órbita','orbita'),
('El Universo','Wszechświat','orbitar','krążyć po orbicie'),
('El Universo','Wszechświat','la luna','księżyc'),
('El Universo','Wszechświat','el satélite natural','naturalny satelita'),
('El Universo','Wszechświat','el sol','słońce'),
('El Universo','Wszechświat','el asteroide','asteroida'),
('El Universo','Wszechświat','el cometa','kometa'),
('El Universo','Wszechświat','el meteorito','meteoryt'),
('El Universo','Wszechświat','el meteoro / la estrella fugaz','meteor / spadająca gwiazda'),
('El Universo','Wszechświat','la gravedad','grawitacja'),
('El Universo','Wszechświat','el agujero negro','czarna dziura'),
('El Universo','Wszechświat','la nebulosa','mgławica'),
('El Universo','Wszechświat','la constelación','konstelacja'),
('El Universo','Wszechświat','el año luz','rok świetlny'),
('El Universo','Wszechświat','la velocidad de la luz','prędkość światła'),
('El Universo','Wszechświat','el telescopio','teleskop'),
('El Universo','Wszechświat','el observatorio','obserwatorium'),
('El Universo','Wszechświat','la nave espacial','statek kosmiczny'),
('El Universo','Wszechświat','el cohete','rakieta'),
('El Universo','Wszechświat','el transbordador espacial','prom kosmiczny'),
('El Universo','Wszechświat','la estación espacial','stacja kosmiczna'),
('El Universo','Wszechświat','la sonda','sonda (kosmiczna)'),
('El Universo','Wszechświat','el astronauta','astronauta'),
('El Universo','Wszechświat','el cosmonauta','kosmonauta'),
('El Universo','Wszechświat','el traje espacial','skafander kosmiczny'),
('El Universo','Wszechświat','la gravedad cero','stan nieważkości'),
('El Universo','Wszechświat','la exploración espacial','eksploracja kosmosu'),
('El Universo','Wszechświat','el lanzamiento','start (rakiety)'),
('El Universo','Wszechświat','aterrizar','lądować'),
('El Universo','Wszechświat','alunizar','lądować na księżycu'),
('El Universo','Wszechświat','la órbita terrestre','orbita okołoziemska'),
('El Universo','Wszechświat','el extraterrestre','kosmita'),
('El Universo','Wszechświat','el ovni','UFO'),
('El Universo','Wszechświat','el alienígena','obcy / kosmita'),
('El Universo','Wszechświat','el cielo','niebo'),
('El Universo','Wszechświat','el vacío','próżnia'),
('El Universo','Wszechświat','el Big Bang','Wielki Wybuch'),
('El Universo','Wszechświat','la materia oscura','ciemna materia'),
('El Universo','Wszechświat','la supernova','supernowa'),
('El Universo','Wszechświat','el eclipse solar','zaćmienie słońca'),
('El Universo','Wszechświat','el eclipse lunar','zaćmienie księżyca'),
('El Universo','Wszechświat','el polvo cósmico','pył kosmiczny'),
('Planetas','Planety','el planeta','planeta'),
('Planetas','Planety','Mercurio','Merkury'),
('Planetas','Planety','Venus','Wenus'),
('Planetas','Planety','la Tierra','Ziemia'),
('Planetas','Planety','Marte','Mars'),
('Planetas','Planety','Júpiter','Jowisz'),
('Planetas','Planety','Saturno','Saturn'),
('Planetas','Planety','Urano','Uran'),
('Planetas','Planety','Neptuno','Neptun'),
('Planetas','Planety','Plutón','Pluton'),
('Planetas','Planety','el planeta enano','planeta karłowata'),
('Planetas','Planety','el exoplaneta','egzoplaneta'),
('Planetas','Planety','la órbita','orbita'),
('Planetas','Planety','el satélite natural','naturalny satelita'),
('Planetas','Planety','la luna','księżyc'),
('Planetas','Planety','el sistema solar','układ słoneczny'),
('Planetas','Planety','el sol','słońce'),
('Planetas','Planety','la estrella','gwiazda'),
('Planetas','Planety','el anillo','pierścień (np. Saturna)'),
('Planetas','Planety','el gas','gaz'),
('Planetas','Planety','la roca','skała'),
('Planetas','Planety','el cráter','krater'),
('Planetas','Planety','la superficie','powierzchnia'),
('Planetas','Planety','la atmósfera','atmosfera'),
('Planetas','Planety','la gravedad','grawitacja'),
('Planetas','Planety','la rotación','rotacja / obrót'),
('Planetas','Planety','la traslación','ruch obiegowy'),
('Planetas','Planety','el ecuador','równik'),
('Planetas','Planety','el hemisferio','półkula'),
('Planetas','Planety','el polo','biegun'),
('Planetas','Planety','el telescopio','teleskop'),
('Planetas','Planety','la sonda espacial','sonda kosmiczna'),
('Planetas','Planety','el rover','łazik'),
('Planetas','Planety','el satélite','satelita'),
('Planetas','Planety','la exploración','eksploracja'),
('Planetas','Planety','descubrir','odkrywać'),
('Planetas','Planety','rocoso','skalisty'),
('Planetas','Planety','gaseoso','gazowy'),
('Planetas','Planety','el gigante gaseoso','gazowy olbrzym'),
('Planetas','Planety','el núcleo','jądro'),
('Planetas','Planety','la corteza','skorupa'),
('Planetas','Planety','el manto','płaszcz'),
('Planetas','Planety','el campo magnético','pole magnetyczne'),
('Planetas','Planety','el día solar','dzień słoneczny'),
('Planetas','Planety','el año luz','rok świetlny'),
('Planetas','Planety','la temperatura','temperatura'),
('Planetas','Planety','el hielo','lód'),
('Planetas','Planety','la vida extraterrestre','życie pozaziemskie'),
('Planetas','Planety','el espacio','kosmos / przestrzeń'),
('Planetas','Planety','el vacío','próżnia');
