insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Deportes Individuales','Sporty indywidualne','el deporte individual','sport indywidualny'),
('Deportes Individuales','Sporty indywidualne','el atletismo','lekkoatletyka'),
('Deportes Individuales','Sporty indywidualne','la carrera / el running','bieganie'),
('Deportes Individuales','Sporty indywidualne','el esprint','sprint'),
('Deportes Individuales','Sporty indywidualne','el maratón','maraton'),
('Deportes Individuales','Sporty indywidualne','el salto de longitud','skok w dal'),
('Deportes Individuales','Sporty indywidualne','el salto de altura','skok wzwyż'),
('Deportes Individuales','Sporty indywidualne','el salto con pértiga','skok o tyczce'),
('Deportes Individuales','Sporty indywidualne','el lanzamiento de jabalina','rzut oszczepem'),
('Deportes Individuales','Sporty indywidualne','la natación','pływanie'),
('Deportes Individuales','Sporty indywidualne','el ciclismo','kolarstwo'),
('Deportes Individuales','Sporty indywidualne','el tenis','tenis'),
('Deportes Individuales','Sporty indywidualne','el tenis de mesa / el ping-pong','tenis stołowy'),
('Deportes Individuales','Sporty indywidualne','el bádminton','badminton'),
('Deportes Individuales','Sporty indywidualne','el squash','squash'),
('Deportes Individuales','Sporty indywidualne','el golf','golf'),
('Deportes Individuales','Sporty indywidualne','el boxeo','boks'),
('Deportes Individuales','Sporty indywidualne','la lucha libre','zapasy'),
('Deportes Individuales','Sporty indywidualne','el judo','judo'),
('Deportes Individuales','Sporty indywidualne','el karate','karate'),
('Deportes Individuales','Sporty indywidualne','el taekwondo','taekwondo'),
('Deportes Individuales','Sporty indywidualne','la esgrima','szermierka'),
('Deportes Individuales','Sporty indywidualne','la gimnasia','gimnastyka'),
('Deportes Individuales','Sporty indywidualne','el patinaje artístico','łyżwiarstwo figurowe'),
('Deportes Individuales','Sporty indywidualne','el esquí','narciarstwo'),
('Deportes Individuales','Sporty indywidualne','el snowboard','snowboard'),
('Deportes Individuales','Sporty indywidualne','la halterofilia','podnoszenie ciężarów'),
('Deportes Individuales','Sporty indywidualne','el tiro','strzelectwo'),
('Deportes Individuales','Sporty indywidualne','el tiro con arco','łucznictwo'),
('Deportes Individuales','Sporty indywidualne','la equitación / la hípica','jeździectwo'),
('Deportes Individuales','Sporty indywidualne','el triatlón','triathlon'),
('Deportes Individuales','Sporty indywidualne','el pentatlón','pięciobój'),
('Deportes Individuales','Sporty indywidualne','la escalada','wspinaczka'),
('Deportes Individuales','Sporty indywidualne','el billar','billiard'),
('Deportes Individuales','Sporty indywidualne','los dardos','rzutki (darts)'),
('Deportes Individuales','Sporty indywidualne','el ajedrez','szachy'),
('Deportes Individuales','Sporty indywidualne','la carrera','wyścig'),
('Deportes Individuales','Sporty indywidualne','el récord','rekord'),
('Deportes Individuales','Sporty indywidualne','la medalla','medal'),
('Deportes Individuales','Sporty indywidualne','el oro','złoto'),
('Deportes Individuales','Sporty indywidualne','la plata','srebro'),
('Deportes Individuales','Sporty indywidualne','el bronce','brąz'),
('Deportes Individuales','Sporty indywidualne','el campeón','mistrz'),
('Deportes Individuales','Sporty indywidualne','el podio','podium'),
('Deportes Individuales','Sporty indywidualne','el oponente / el contrincante','przeciwnik'),
('Deportes Individuales','Sporty indywidualne','el rival','rywal'),
('Deportes Individuales','Sporty indywidualne','el entrenamiento','trening'),
('Deportes Individuales','Sporty indywidualne','la condición física','kondycja'),
('Deportes Individuales','Sporty indywidualne','la técnica','technika'),
('Deportes Individuales','Sporty indywidualne','el equipamiento','sprzęt (sportowy)'),
('Deportes Acuáticos','Sporty wodne','el deporte acuático','sport wodny'),
('Deportes Acuáticos','Sporty wodne','la natación','pływanie'),
('Deportes Acuáticos','Sporty wodne','los saltos (de trampolín)','skoki do wody'),
('Deportes Acuáticos','Sporty wodne','el waterpolo','piłka wodna'),
('Deportes Acuáticos','Sporty wodne','la natación sincronizada','pływanie synchroniczne'),
('Deportes Acuáticos','Sporty wodne','el remo','wioślarstwo'),
('Deportes Acuáticos','Sporty wodne','el piragüismo / el kayak','kajakarstwo'),
('Deportes Acuáticos','Sporty wodne','la vela','żeglarstwo'),
('Deportes Acuáticos','Sporty wodne','el windsurf','windsurfing'),
('Deportes Acuáticos','Sporty wodne','el kitesurf','kitesurfing'),
('Deportes Acuáticos','Sporty wodne','el surf','surfing'),
('Deportes Acuáticos','Sporty wodne','el buceo / el submarinismo','nurkowanie'),
('Deportes Acuáticos','Sporty wodne','la apnea','freediving (na wstrzymanym oddechu)'),
('Deportes Acuáticos','Sporty wodne','el esnórquel','snorkeling (z rurką)'),
('Deportes Acuáticos','Sporty wodne','el esquí acuático','narty wodne'),
('Deportes Acuáticos','Sporty wodne','el wakeboard','wakeboard'),
('Deportes Acuáticos','Sporty wodne','el rafting','rafting'),
('Deportes Acuáticos','Sporty wodne','la piscina','basen'),
('Deportes Acuáticos','Sporty wodne','el mar','morze'),
('Deportes Acuáticos','Sporty wodne','el lago','jezioro'),
('Deportes Acuáticos','Sporty wodne','el agua','woda'),
('Deportes Acuáticos','Sporty wodne','la tabla de surf','deska surfingowa'),
('Deportes Acuáticos','Sporty wodne','la vela (objeto)','żagiel'),
('Deportes Acuáticos','Sporty wodne','el remo (objeto)','wiosło'),
('Deportes Acuáticos','Sporty wodne','la canoa / el kayak','kajak / kanoe'),
('Deportes Acuáticos','Sporty wodne','la barca','łódź'),
('Deportes Acuáticos','Sporty wodne','el bañador','strój kąpielowy'),
('Deportes Acuáticos','Sporty wodne','el traje de neopreno','pianka (do pływania)'),
('Deportes Acuáticos','Sporty wodne','las gafas de natación','okulary pływackie'),
('Deportes Acuáticos','Sporty wodne','el gorro de baño','czepek'),
('Deportes Acuáticos','Sporty wodne','las aletas','płetwy'),
('Deportes Acuáticos','Sporty wodne','el tubo de buceo','rurka do nurkowania'),
('Deportes Acuáticos','Sporty wodne','el chaleco salvavidas','kamizelka ratunkowa'),
('Deportes Acuáticos','Sporty wodne','el socorrista','ratownik wodny'),
('Deportes Acuáticos','Sporty wodne','la ola','fala'),
('Deportes Acuáticos','Sporty wodne','el viento','wiatr'),
('Deportes Acuáticos','Sporty wodne','la corriente','prąd (wodny)'),
('Deportes Acuáticos','Sporty wodne','la profundidad','głębokość'),
('Deportes Acuáticos','Sporty wodne','el estilo libre / el crol','kraul / styl dowolny'),
('Deportes Acuáticos','Sporty wodne','la braza','styl klasyczny (żabka)'),
('Deportes Acuáticos','Sporty wodne','el estilo espalda','styl grzbietowy'),
('Deportes Acuáticos','Sporty wodne','el estilo mariposa','styl motylkowy (delfin)'),
('Deportes Acuáticos','Sporty wodne','el trampolín','trampolina'),
('Deportes Acuáticos','Sporty wodne','la inmersión','zanurzenie'),
('Deportes Acuáticos','Sporty wodne','la regata','regaty / wyścig'),
('Deportes Acuáticos','Sporty wodne','el puerto deportivo','marina / przystań'),
('Deportes Acuáticos','Sporty wodne','el amarre','miejsce cumowania'),
('Deportes Acuáticos','Sporty wodne','la balsa','tratwa'),
('Deportes Acuáticos','Sporty wodne','la moto de agua','skuter wodny'),
('Deportes Acuáticos','Sporty wodne','bucear','nurkować'),
('Deportes de Invierno','Sporty zimowe','el deporte de invierno','sport zimowy'),
('Deportes de Invierno','Sporty zimowe','el esquí','narciarstwo / narta'),
('Deportes de Invierno','Sporty zimowe','el snowboard','snowboard'),
('Deportes de Invierno','Sporty zimowe','el patinaje sobre hielo','łyżwiarstwo figurowe / na lodzie'),
('Deportes de Invierno','Sporty zimowe','el hockey sobre hielo','hokej na lodzie'),
('Deportes de Invierno','Sporty zimowe','el patinaje de velocidad','łyżwiarstwo szybkie'),
('Deportes de Invierno','Sporty zimowe','el salto de esquí','skoki narciarskie'),
('Deportes de Invierno','Sporty zimowe','el biatlón','biathlon'),
('Deportes de Invierno','Sporty zimowe','el bobsleigh','bobsleje'),
('Deportes de Invierno','Sporty zimowe','el trineo','sanki / saneczkarstwo'),
('Deportes de Invierno','Sporty zimowe','el curling','curling'),
('Deportes de Invierno','Sporty zimowe','el alpinismo','alpinizm'),
('Deportes de Invierno','Sporty zimowe','la nieve','śnieg'),
('Deportes de Invierno','Sporty zimowe','el hielo','lód'),
('Deportes de Invierno','Sporty zimowe','la montaña','góra'),
('Deportes de Invierno','Sporty zimowe','la pista de esquí','stok narciarski'),
('Deportes de Invierno','Sporty zimowe','el telesilla / el remonte','wyciąg krzesełkowy / orczyk'),
('Deportes de Invierno','Sporty zimowe','el teleférico','kolejka linowa'),
('Deportes de Invierno','Sporty zimowe','la avalancha / el alud','lawina'),
('Deportes de Invierno','Sporty zimowe','el copo de nieve','płatek śniegu'),
('Deportes de Invierno','Sporty zimowe','el invierno','zima'),
('Deportes de Invierno','Sporty zimowe','el frío','zimno'),
('Deportes de Invierno','Sporty zimowe','bajo cero','poniżej zera'),
('Deportes de Invierno','Sporty zimowe','congelado','zamarznięty'),
('Deportes de Invierno','Sporty zimowe','resbaladizo','śliski'),
('Deportes de Invierno','Sporty zimowe','patinar','jeździć na łyżwach'),
('Deportes de Invierno','Sporty zimowe','esquiar','jeździć na nartach'),
('Deportes de Invierno','Sporty zimowe','deslizarse','ślizgać się / zjeżdżać'),
('Deportes de Invierno','Sporty zimowe','frenar','hamować'),
('Deportes de Invierno','Sporty zimowe','caerse','przewrócić się'),
('Deportes de Invierno','Sporty zimowe','los esquís','narty'),
('Deportes de Invierno','Sporty zimowe','los bastones (de esquí)','kije narciarskie'),
('Deportes de Invierno','Sporty zimowe','las fijaciones','wiązania'),
('Deportes de Invierno','Sporty zimowe','las botas de esquí','buty narciarskie'),
('Deportes de Invierno','Sporty zimowe','la tabla de snowboard','deska snowboardowa'),
('Deportes de Invierno','Sporty zimowe','los patines','łyżwy'),
('Deportes de Invierno','Sporty zimowe','el disco (de hockey)','krążek hokejowy'),
('Deportes de Invierno','Sporty zimowe','el casco','kask'),
('Deportes de Invierno','Sporty zimowe','las gafas de ventisca','gogle narciarskie'),
('Deportes de Invierno','Sporty zimowe','los guantes','rękawice'),
('Deportes de Invierno','Sporty zimowe','el abrigo','płaszcz / kurtka'),
('Deportes de Invierno','Sporty zimowe','el gorro','czapka'),
('Deportes de Invierno','Sporty zimowe','la bufanda','szalik'),
('Deportes de Invierno','Sporty zimowe','el forfait','karnet narciarski'),
('Deportes de Invierno','Sporty zimowe','el instructor','instruktor'),
('Deportes de Invierno','Sporty zimowe','la clase de esquí','lekcja narciarstwa'),
('Deportes de Invierno','Sporty zimowe','el campeonato','mistrzostwa'),
('Deportes de Invierno','Sporty zimowe','el fuera de pista','jazda poza trasą (freeride)'),
('Deportes de Invierno','Sporty zimowe','la estación de esquí','ośrodek narciarski'),
('Deportes de Invierno','Sporty zimowe','el trineo de perros','psi zaprzęg'),
('Equipamiento Deportivo','Sprzęt sportowy','el equipamiento deportivo','sprzęt sportowy'),
('Equipamiento Deportivo','Sprzęt sportowy','la pelota','piłka (zwykle mała)'),
('Equipamiento Deportivo','Sprzęt sportowy','el balón','piłka (duża)'),
('Equipamiento Deportivo','Sprzęt sportowy','la raqueta','rakieta (np. tenisowa)'),
('Equipamiento Deportivo','Sprzęt sportowy','el bate','kij baseballowy'),
('Equipamiento Deportivo','Sprzęt sportowy','el palo','kij (golfowy, hokejowy)'),
('Equipamiento Deportivo','Sprzęt sportowy','la red','siatka'),
('Equipamiento Deportivo','Sprzęt sportowy','la portería','bramka'),
('Equipamiento Deportivo','Sprzęt sportowy','la canasta','kosz'),
('Equipamiento Deportivo','Sprzęt sportowy','los guantes','rękawice'),
('Equipamiento Deportivo','Sprzęt sportowy','el casco','kask'),
('Equipamiento Deportivo','Sprzęt sportowy','las rodilleras','nakolanniki'),
('Equipamiento Deportivo','Sprzęt sportowy','las coderas','nałokietniki'),
('Equipamiento Deportivo','Sprzęt sportowy','las espinilleras','ochraniacze na piszczele'),
('Equipamiento Deportivo','Sprzęt sportowy','las gafas de natación','okulary pływackie'),
('Equipamiento Deportivo','Sprzęt sportowy','el gorro de baño','czepek pływacki'),
('Equipamiento Deportivo','Sprzęt sportowy','el bañador','strój kąpielowy'),
('Equipamiento Deportivo','Sprzęt sportowy','el chándal','dres'),
('Equipamiento Deportivo','Sprzęt sportowy','las zapatillas de deporte','buty sportowe'),
('Equipamiento Deportivo','Sprzęt sportowy','los tacos','korki (buty)'),
('Equipamiento Deportivo','Sprzęt sportowy','los patines','łyżwy / rolki'),
('Equipamiento Deportivo','Sprzęt sportowy','la bicicleta','rower'),
('Equipamiento Deportivo','Sprzęt sportowy','el sillín','siodełko'),
('Equipamiento Deportivo','Sprzęt sportowy','el pedal','pedał'),
('Equipamiento Deportivo','Sprzęt sportowy','el manillar','kierownica (rowerowa)'),
('Equipamiento Deportivo','Sprzęt sportowy','la tabla','deska'),
('Equipamiento Deportivo','Sprzęt sportowy','los esquís','narty'),
('Equipamiento Deportivo','Sprzęt sportowy','el silbato','gwizdek'),
('Equipamiento Deportivo','Sprzęt sportowy','el cronómetro','stoper'),
('Equipamiento Deportivo','Sprzęt sportowy','la cinta de correr','bieżnia (urządzenie)'),
('Equipamiento Deportivo','Sprzęt sportowy','la pesa','ciężarek'),
('Equipamiento Deportivo','Sprzęt sportowy','la mancuerna','hantel'),
('Equipamiento Deportivo','Sprzęt sportowy','la barra','sztanga / drążek'),
('Equipamiento Deportivo','Sprzęt sportowy','el disco (de pesas)','talerz (obciążenie)'),
('Equipamiento Deportivo','Sprzęt sportowy','la esterilla / la colchoneta','mata (np. do jogi) / materac'),
('Equipamiento Deportivo','Sprzęt sportowy','el saco de boxeo','worek treningowy'),
('Equipamiento Deportivo','Sprzęt sportowy','el kimono','kimono'),
('Equipamiento Deportivo','Sprzęt sportowy','el cinturón','pas (np. w sztukach walki)'),
('Equipamiento Deportivo','Sprzęt sportowy','los dardos','rzutki (lotki)'),
('Equipamiento Deportivo','Sprzęt sportowy','la diana','tarcza (do rzutek)'),
('Equipamiento Deportivo','Sprzęt sportowy','el tablero','plansza (np. do szachów)'),
('Equipamiento Deportivo','Sprzęt sportowy','las piezas','pionki / bierki'),
('Equipamiento Deportivo','Sprzęt sportowy','el aro','obręcz (np. hula hop)'),
('Equipamiento Deportivo','Sprzęt sportowy','la comba','skakanka'),
('Equipamiento Deportivo','Sprzęt sportowy','el trampolín','trampolina'),
('Equipamiento Deportivo','Sprzęt sportowy','la jabalina','oszczep'),
('Equipamiento Deportivo','Sprzęt sportowy','el disco (atletismo)','dysk (do rzutu)'),
('Equipamiento Deportivo','Sprzęt sportowy','el trofeo','trofeum / puchar'),
('Equipamiento Deportivo','Sprzęt sportowy','la medalla','medal'),
('Equipamiento Deportivo','Sprzęt sportowy','el uniforme','stój sportowy (uniform)');
