insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Economía Global','Gospodarka globalna','la economía','gospodarka / ekonomia'),
('Economía Global','Gospodarka globalna','el crecimiento','wzrost'),
('Economía Global','Gospodarka globalna','la recesión','recesja'),
('Economía Global','Gospodarka globalna','la crisis','kryzys'),
('Economía Global','Gospodarka globalna','la inflación','inflacja'),
('Economía Global','Gospodarka globalna','la deflación','deflacja'),
('Economía Global','Gospodarka globalna','el Producto Interior Bruto (PIB)','Produkt Krajowy Brutto (PKB)'),
('Economía Global','Gospodarka globalna','el mercado','rynek'),
('Economía Global','Gospodarka globalna','la demanda','popyt'),
('Economía Global','Gospodarka globalna','la oferta','podaż'),
('Economía Global','Gospodarka globalna','el monopolio','monopol'),
('Economía Global','Gospodarka globalna','la competencia','konkurencja'),
('Economía Global','Gospodarka globalna','la globalización','globalizacja'),
('Economía Global','Gospodarka globalna','el desarrollo','rozwój'),
('Economía Global','Gospodarka globalna','subdesarrollado','słabo rozwinięty'),
('Economía Global','Gospodarka globalna','el país en vías de desarrollo','kraj rozwijający się'),
('Economía Global','Gospodarka globalna','el primer mundo','pierwszy świat (kraje rozwinięte)'),
('Economía Global','Gospodarka globalna','el tercer mundo','trzeci świat'),
('Economía Global','Gospodarka globalna','la riqueza','bogactwo'),
('Economía Global','Gospodarka globalna','la pobreza','ubóstwo / bieda'),
('Economía Global','Gospodarka globalna','la desigualdad','nierówność'),
('Economía Global','Gospodarka globalna','la macroeconomía','makroekonomia'),
('Economía Global','Gospodarka globalna','la microeconomía','mikroekonomia'),
('Economía Global','Gospodarka globalna','la política económica','polityka gospodarcza'),
('Economía Global','Gospodarka globalna','la deuda externa','dług zagraniczny'),
('Economía Global','Gospodarka globalna','la tasa de desempleo','stopa bezrobocia'),
('Economía Global','Gospodarka globalna','el poder adquisitivo','siła nabywcza'),
('Economía Global','Gospodarka globalna','el sector primario','sektor pierwszy (rolnictwo)'),
('Economía Global','Gospodarka globalna','el sector secundario','sektor drugi (przemysł)'),
('Economía Global','Gospodarka globalna','el sector terciario','sektor trzeci (usługi)'),
('Economía Global','Gospodarka globalna','la bolsa','giełda'),
('Economía Global','Gospodarka globalna','el mercado de valores','rynek papierów wartościowych'),
('Economía Global','Gospodarka globalna','el índice bursátil','indeks giełdowy'),
('Economía Global','Gospodarka globalna','la cotización','notowanie (na giełdzie)'),
('Economía Global','Gospodarka globalna','el capitalismo','kapitalizm'),
('Economía Global','Gospodarka globalna','el comunismo','komunizm'),
('Economía Global','Gospodarka globalna','el libre mercado','wolny rynek'),
('Economía Global','Gospodarka globalna','la privatización','prywatyzacja'),
('Economía Global','Gospodarka globalna','la nacionalización','nacjonalizacja'),
('Economía Global','Gospodarka globalna','el déficit','deficyt'),
('Economía Global','Gospodarka globalna','el superávit','nadwyżka'),
('Economía Global','Gospodarka globalna','la divisa','waluta zagraniczna'),
('Economía Global','Gospodarka globalna','el mercado de divisas','rynek walutowy'),
('Economía Global','Gospodarka globalna','el Fondo Monetario Internacional (FMI)','Międzynarodowy Fundusz Walutowy (MFW)'),
('Economía Global','Gospodarka globalna','el Banco Mundial','Bank Światowy'),
('Economía Global','Gospodarka globalna','la ayuda humanitaria','pomoc humanitarna'),
('Economía Global','Gospodarka globalna','el comercio justo','sprawiedliwy handel (fair trade)'),
('Economía Global','Gospodarka globalna','la materia prima','surowiec'),
('Economía Global','Gospodarka globalna','la producción','produkcja'),
('Economía Global','Gospodarka globalna','el consumo','konsumpcja'),
('Comercio Internacional','Handel międzynarodowy','el comercio','handel'),
('Comercio Internacional','Handel międzynarodowy','internacional','międzynarodowy'),
('Comercio Internacional','Handel międzynarodowy','la exportación','eksport'),
('Comercio Internacional','Handel międzynarodowy','exportar','eksportować'),
('Comercio Internacional','Handel międzynarodowy','la importación','import'),
('Comercio Internacional','Handel międzynarodowy','importar','importować'),
('Comercio Internacional','Handel międzynarodowy','la aduana','urząd celny / cło'),
('Comercio Internacional','Handel międzynarodowy','el arancel','cło / taryfa celna'),
('Comercio Internacional','Handel międzynarodowy','el acuerdo comercial','umowa handlowa'),
('Comercio Internacional','Handel międzynarodowy','el tratado','traktat'),
('Comercio Internacional','Handel międzynarodowy','el mercado extranjero','rynek zagraniczny'),
('Comercio Internacional','Handel międzynarodowy','la barrera comercial','bariera handlowa'),
('Comercio Internacional','Handel międzynarodowy','el libre comercio','wolny handel'),
('Comercio Internacional','Handel międzynarodowy','la cuota','kontyngent / przydział'),
('Comercio Internacional','Handel międzynarodowy','la frontera','granica'),
('Comercio Internacional','Handel międzynarodowy','el puerto','port'),
('Comercio Internacional','Handel międzynarodowy','el contenedor','kontener'),
('Comercio Internacional','Handel międzynarodowy','la logística','logistyka'),
('Comercio Internacional','Handel międzynarodowy','el transporte','transport'),
('Comercio Internacional','Handel międzynarodowy','el flete','fracht (opłata za transport)'),
('Comercio Internacional','Handel międzynarodowy','el envío','wysyłka / przesyłka'),
('Comercio Internacional','Handel międzynarodowy','la naviera','firma żeglugowa / armator'),
('Comercio Internacional','Handel międzynarodowy','el proveedor','dostawca'),
('Comercio Internacional','Handel międzynarodowy','el cliente','klient'),
('Comercio Internacional','Handel międzynarodowy','el mercado interior','rynek wewnętrzny'),
('Comercio Internacional','Handel międzynarodowy','el socio comercial','partner handlowy'),
('Comercio Internacional','Handel międzynarodowy','la balanza comercial','bilans handlowy'),
('Comercio Internacional','Handel międzynarodowy','el déficit comercial','deficyt handlowy'),
('Comercio Internacional','Handel międzynarodowy','el superávit comercial','nadwyżka handlowa'),
('Comercio Internacional','Handel międzynarodowy','la Organización Mundial del Comercio (OMC)','Światowa Organizacja Handlu (WTO)'),
('Comercio Internacional','Handel międzynarodowy','el certificado de origen','świadectwo pochodzenia'),
('Comercio Internacional','Handel międzynarodowy','el despacho de aduanas','odprawa celna'),
('Comercio Internacional','Handel międzynarodowy','el importador','importer'),
('Comercio Internacional','Handel międzynarodowy','el exportador','eksporter'),
('Comercio Internacional','Handel międzynarodowy','el mercado global','rynek globalny'),
('Comercio Internacional','Handel międzynarodowy','la competitividad','konkurencyjność'),
('Comercio Internacional','Handel międzynarodowy','competitivo','konkurencyjny'),
('Comercio Internacional','Handel międzynarodowy','el tratado de libre comercio (TLC)','porozumienie o wolnym handlu'),
('Comercio Internacional','Handel międzynarodowy','el embargo','embargo'),
('Comercio Internacional','Handel międzynarodowy','la sanción comercial','sankcja handlowa'),
('Comercio Internacional','Handel międzynarodowy','la mercancía','towar / ładunek'),
('Comercio Internacional','Handel międzynarodowy','el producto','produkt'),
('Comercio Internacional','Handel międzynarodowy','manufacturar','produkować (przemysłowo)'),
('Comercio Internacional','Handel międzynarodowy','los bienes','dobra / towary'),
('Comercio Internacional','Handel międzynarodowy','los bienes de consumo','dobra konsumpcyjne'),
('Comercio Internacional','Handel międzynarodowy','la cadena de suministro','łańcuch dostaw'),
('Comercio Internacional','Handel międzynarodowy','el distribuidor','dystrybutor'),
('Comercio Internacional','Handel międzynarodowy','la distribución','dystrybucja'),
('Comercio Internacional','Handel międzynarodowy','el mercado emergente','rynek wschodzący'),
('Comercio Internacional','Handel międzynarodowy','la divisa','waluta obca'),
('Marketing y Publicidad','Marketing i reklama','el marketing / la mercadotecnia','marketing'),
('Marketing y Publicidad','Marketing i reklama','la publicidad','reklama (branża)'),
('Marketing y Publicidad','Marketing i reklama','el anuncio','reklama (pojedyncza) / ogłoszenie'),
('Marketing y Publicidad','Marketing i reklama','anunciar','reklamować / ogłaszać'),
('Marketing y Publicidad','Marketing i reklama','la campaña publicitaria','kampania reklamowa'),
('Marketing y Publicidad','Marketing i reklama','el público objetivo','grupa docelowa (target)'),
('Marketing y Publicidad','Marketing i reklama','el cliente potencial','potencjalny klient'),
('Marketing y Publicidad','Marketing i reklama','la estrategia','strategia'),
('Marketing y Publicidad','Marketing i reklama','la marca','marka'),
('Marketing y Publicidad','Marketing i reklama','el logotipo','logotyp / logo'),
('Marketing y Publicidad','Marketing i reklama','el eslogan','slogan / hasło reklamowe'),
('Marketing y Publicidad','Marketing i reklama','el consumidor','konsument'),
('Marketing y Publicidad','Marketing i reklama','consumir','konsumować'),
('Marketing y Publicidad','Marketing i reklama','el mercado','rynek'),
('Marketing y Publicidad','Marketing i reklama','la cuota de mercado','udział w rynku'),
('Marketing y Publicidad','Marketing i reklama','el estudio de mercado','badanie rynku'),
('Marketing y Publicidad','Marketing i reklama','el producto','produkt'),
('Marketing y Publicidad','Marketing i reklama','el precio','cena'),
('Marketing y Publicidad','Marketing i reklama','la promoción','promocja'),
('Marketing y Publicidad','Marketing i reklama','la distribución','dystrybucja'),
('Marketing y Publicidad','Marketing i reklama','el folleto','ulotka / broszura'),
('Marketing y Publicidad','Marketing i reklama','el cartel / el póster','plakat'),
('Marketing y Publicidad','Marketing i reklama','el patrocinador','sponsor'),
('Marketing y Publicidad','Marketing i reklama','patrocinar','sponsorować'),
('Marketing y Publicidad','Marketing i reklama','el evento','wydarzenie (event)'),
('Marketing y Publicidad','Marketing i reklama','las redes sociales','media społecznościowe'),
('Marketing y Publicidad','Marketing i reklama','el marketing digital','marketing cyfrowy'),
('Marketing y Publicidad','Marketing i reklama','el correo basura (spam)','spam'),
('Marketing y Publicidad','Marketing i reklama','el boletín (newsletter)','biuletyn (newsletter)'),
('Marketing y Publicidad','Marketing i reklama','la encuesta','ankieta / sondaż'),
('Marketing y Publicidad','Marketing i reklama','la satisfacción del cliente','satysfakcja klienta'),
('Marketing y Publicidad','Marketing i reklama','la fidelización','budowanie lojalności'),
('Marketing y Publicidad','Marketing i reklama','fidelizar','budować lojalność (klienta)'),
('Marketing y Publicidad','Marketing i reklama','la oferta','oferta'),
('Marketing y Publicidad','Marketing i reklama','el descuento','zniżka / rabat'),
('Marketing y Publicidad','Marketing i reklama','el posicionamiento','pozycjonowanie'),
('Marketing y Publicidad','Marketing i reklama','la agencia de publicidad','agencja reklamowa'),
('Marketing y Publicidad','Marketing i reklama','el presupuesto','budżet'),
('Marketing y Publicidad','Marketing i reklama','la creatividad','kreatywność'),
('Marketing y Publicidad','Marketing i reklama','viral','wirusowy (viral)'),
('Marketing y Publicidad','Marketing i reklama','el anuncio de televisión','reklama telewizyjna / spot'),
('Marketing y Publicidad','Marketing i reklama','el banner','baner internetowy'),
('Marketing y Publicidad','Marketing i reklama','las relaciones públicas','public relations (PR)'),
('Marketing y Publicidad','Marketing i reklama','la imagen de marca','wizerunek marki'),
('Marketing y Publicidad','Marketing i reklama','el boca a boca','marketing szeptany (poczta pantoflowa)'),
('Marketing y Publicidad','Marketing i reklama','persuadir','przekonywać'),
('Marketing y Publicidad','Marketing i reklama','la competencia','konkurencja'),
('Marketing y Publicidad','Marketing i reklama','el catálogo','katalog'),
('Marketing y Publicidad','Marketing i reklama','el lanzamiento','wprowadzenie (na rynek)'),
('Marketing y Publicidad','Marketing i reklama','la promoción de ventas','promocja sprzedaży'),
('Atención al Cliente','Obsługa klienta','la atención al cliente','obsługa klienta'),
('Atención al Cliente','Obsługa klienta','el cliente','klient'),
('Atención al Cliente','Obsługa klienta','el consumidor','konsument'),
('Atención al Cliente','Obsługa klienta','el servicio','usługa / serwis'),
('Atención al Cliente','Obsługa klienta','el dependiente / la dependienta','sprzedawca / sprzedawczyni'),
('Atención al Cliente','Obsługa klienta','el cajero','kasjer'),
('Atención al Cliente','Obsługa klienta','el operador','operator'),
('Atención al Cliente','Obsługa klienta','el representante','przedstawiciel'),
('Atención al Cliente','Obsługa klienta','la reclamación','reklamacja'),
('Atención al Cliente','Obsługa klienta','reclamar','reklamować'),
('Atención al Cliente','Obsługa klienta','la queja','skarga'),
('Atención al Cliente','Obsługa klienta','quejarse','skarżyć się'),
('Atención al Cliente','Obsługa klienta','la devolución','zwrot (towaru)'),
('Atención al Cliente','Obsługa klienta','devolver','zwracać (towar)'),
('Atención al Cliente','Obsługa klienta','el reembolso','zwrot pieniędzy'),
('Atención al Cliente','Obsługa klienta','el cambio','wymiana'),
('Atención al Cliente','Obsługa klienta','la garantía','gwarancja'),
('Atención al Cliente','Obsługa klienta','el defecto','wada / defekt'),
('Atención al Cliente','Obsługa klienta','defectuoso','wadliwy'),
('Atención al Cliente','Obsługa klienta','roto','zepsuty / uszkodzony'),
('Atención al Cliente','Obsługa klienta','la avería','awaria'),
('Atención al Cliente','Obsługa klienta','reparar','naprawiać'),
('Atención al Cliente','Obsługa klienta','el servicio técnico','serwis techniczny'),
('Atención al Cliente','Obsługa klienta','la solución','rozwiązanie'),
('Atención al Cliente','Obsługa klienta','resolver','rozwiązywać'),
('Atención al Cliente','Obsługa klienta','la ayuda','pomoc'),
('Atención al Cliente','Obsługa klienta','ayudar','pomagać'),
('Atención al Cliente','Obsługa klienta','la información','informacja'),
('Atención al Cliente','Obsługa klienta','el mostrador de información','punkt informacyjny'),
('Atención al Cliente','Obsługa klienta','la línea de atención','infolinia'),
('Atención al Cliente','Obsługa klienta','llamar','dzwonić'),
('Atención al Cliente','Obsługa klienta','la llamada','połączenie telefoniczne'),
('Atención al Cliente','Obsługa klienta','la espera','oczekiwanie'),
('Atención al Cliente','Obsługa klienta','esperar','czekać'),
('Atención al Cliente','Obsługa klienta','la amabilidad','uprzejmość'),
('Atención al Cliente','Obsługa klienta','amable','uprzejmy'),
('Atención al Cliente','Obsługa klienta','la satisfacción','satysfakcja'),
('Atención al Cliente','Obsługa klienta','satisfecho','zadowolony'),
('Atención al Cliente','Obsługa klienta','insatisfecho','niezadowolony'),
('Atención al Cliente','Obsługa klienta','la encuesta de satisfacción','ankietas satysfakcji'),
('Atención al Cliente','Obsługa klienta','el formulario','formularz'),
('Atención al Cliente','Obsługa klienta','los datos','dane'),
('Atención al Cliente','Obsługa klienta','el ticket de compra','paragon'),
('Atención al Cliente','Obsługa klienta','el comprobante','dowód zakupu / pokwitowanie'),
('Atención al Cliente','Obsługa klienta','la factura','faktura'),
('Atención al Cliente','Obsługa klienta','el buzón de sugerencias','skrzynka na sugestie'),
('Atención al Cliente','Obsługa klienta','el trato','traktowanie / obsługa'),
('Atención al Cliente','Obsługa klienta','profesional','profesjonalny'),
('Atención al Cliente','Obsługa klienta','eficiente','wydajny / sprawny'),
('Atención al Cliente','Obsługa klienta','la paciencia','cierpliwość');
