insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('En el Hospital','W szpitalu','el hospital','szpital'),
('En el Hospital','W szpitalu','la clínica','klinika'),
('En el Hospital','W szpitalu','el ambulatorio','przychodnia'),
('En el Hospital','W szpitalu','urgencias','ostry dyżur / SOR'),
('En el Hospital','W szpitalu','la emergencia','nagły wypadek'),
('En el Hospital','W szpitalu','la ambulancia','karetka'),
('En el Hospital','W szpitalu','el paramédico','ratownik medyczny'),
('En el Hospital','W szpitalu','la camilla','nosze'),
('En el Hospital','W szpitalu','la silla de ruedas','wózek inwalidzki'),
('En el Hospital','W szpitalu','la muleta','kula ortopedyczna'),
('En el Hospital','W szpitalu','el bastón','laska'),
('En el Hospital','W szpitalu','la sala de espera','poczekalnia'),
('En el Hospital','W szpitalu','la habitación','sala chorych'),
('En el Hospital','W szpitalu','la cama de hospital','łóżko szpitalne'),
('En el Hospital','W szpitalu','el quirófano','sala operacyjna'),
('En el Hospital','W szpitalu','la operación','operacja'),
('En el Hospital','W szpitalu','la cirugía','chirurgia'),
('En el Hospital','W szpitalu','el cirujano','chirurg'),
('En el Hospital','W szpitalu','el anestesista','anestezjolog'),
('En el Hospital','W szpitalu','la anestesia','znieczulenie / narkoza'),
('En el Hospital','W szpitalu','el oxígeno','tlen'),
('En el Hospital','W szpitalu','la mascarilla','maska tlenowa / maseczka'),
('En el Hospital','W szpitalu','el suero','kroplówka / surowica'),
('En el Hospital','W szpitalu','la vía','wkłucie / wenflon'),
('En el Hospital','W szpitalu','la donación de sangre','oddawanie krwi'),
('En el Hospital','W szpitalu','el donante','dawca'),
('En el Hospital','W szpitalu','la transfusión','transfuzja'),
('En el Hospital','W szpitalu','el escáner','skaner / tomograf'),
('En el Hospital','W szpitalu','la ecografía','USG'),
('En el Hospital','W szpitalu','la resonancia magnética','rezonans magnetyczny'),
('En el Hospital','W szpitalu','el parto','poród'),
('En el Hospital','W szpitalu','dar a luz','rodzić'),
('En el Hospital','W szpitalu','la planta','oddział szpitalny'),
('En el Hospital','W szpitalu','la UCI','OIOM (Oddział Intensywnej Terapii)'),
('En el Hospital','W szpitalu','el alta','wypis (ze szpitala)'),
('En el Hospital','W szpitalu','dar el alta','wypisać ze szpitala'),
('En el Hospital','W szpitalu','ingresar','przyjąć do szpitala'),
('En el Hospital','W szpitalu','el ingreso','przyjęcie do szpitala'),
('En el Hospital','W szpitalu','visitar','odwiedzać'),
('En el Hospital','W szpitalu','el horario de visitas','godziny odwiedzin'),
('En el Hospital','W szpitalu','grave','ciężki (stan)'),
('En el Hospital','W szpitalu','estable','stabilny (stan)'),
('En el Hospital','W szpitalu','crítico','krytyczny (stan)'),
('En el Hospital','W szpitalu','el yeso / la escayola','gips'),
('En el Hospital','W szpitalu','la herida','rana'),
('En el Hospital','W szpitalu','la cicatriz','blizna'),
('En el Hospital','W szpitalu','los puntos','szwy'),
('En el Hospital','W szpitalu','desmayarse','zemdleć'),
('En el Hospital','W szpitalu','sangrar','krwawić'),
('En el Hospital','W szpitalu','el coma','śpiączka'),
('Síntomas','Symptomy','el síntoma','objaw / symptom'),
('Síntomas','Symptomy','el dolor','ból'),
('Síntomas','Symptomy','la fiebre','gorączka'),
('Síntomas','Symptomy','la tos','kaszel'),
('Síntomas','Symptomy','el resfriado','katar / przeziębienie'),
('Síntomas','Symptomy','el estornudo','kichnięcie'),
('Síntomas','Symptomy','la fatiga / el cansancio','zmęczenie'),
('Síntomas','Symptomy','la debilidad','osłabienie'),
('Síntomas','Symptomy','el mareo','zawroty głowy / nudności'),
('Síntomas','Symptomy','la náusea','mdłości'),
('Síntomas','Symptomy','el vómito','wymioty'),
('Síntomas','Symptomy','la diarrea','biegunka'),
('Síntomas','Symptomy','el estreñimiento','zaparcie'),
('Síntomas','Symptomy','la erupción / el sarpullido','wysypka'),
('Síntomas','Symptomy','el picor / la comezón','swędzenie'),
('Síntomas','Symptomy','la hinchazón','obrzęk / opuchlizna'),
('Síntomas','Symptomy','los escalofríos','dreszcze'),
('Síntomas','Symptomy','el sudor','pot / pocenie się'),
('Síntomas','Symptomy','la falta de aire','duszność'),
('Síntomas','Symptomy','la dificultad para respirar','trudności w oddychaniu'),
('Síntomas','Symptomy','la hemorragia / el sangrado','krwawienie'),
('Síntomas','Symptomy','el moretón / el hematoma','siniak / krwiak'),
('Síntomas','Symptomy','el calambre','skurcz'),
('Síntomas','Symptomy','el entumecimiento','drętwienie'),
('Síntomas','Symptomy','el hormigueo','mrowienie'),
('Síntomas','Symptomy','el insomnio','bezsenność'),
('Síntomas','Symptomy','la pérdida de apetito','utrata apetytu'),
('Síntomas','Symptomy','la pérdida de peso','utrata wagi'),
('Síntomas','Symptomy','el aumento de peso','przyrost wagi'),
('Síntomas','Symptomy','la palidez','bladość'),
('Síntomas','Symptomy','el enrojecimiento','zaczerwienienie'),
('Síntomas','Symptomy','el dolor de cabeza','ból głowy'),
('Síntomas','Symptomy','el dolor de estómago','ból brzucha'),
('Síntomas','Symptomy','el dolor de garganta','ból gardła'),
('Síntomas','Symptomy','la acidez','zgaga'),
('Síntomas','Symptomy','la indigestión','niestrawność'),
('Síntomas','Symptomy','las flatulencias / los gases','wzdęcia / gazy'),
('Síntomas','Symptomy','el pinchazo','kłucie'),
('Síntomas','Symptomy','el ardor','pieczenie'),
('Síntomas','Symptomy','el lagrimeo','łzawienie'),
('Síntomas','Symptomy','la rinitis alérgica','katar sienny'),
('Síntomas','Symptomy','la ronquera','chrypka'),
('Síntomas','Symptomy','la pérdida de olfato','utrata węchu'),
('Síntomas','Symptomy','la pérdida de gusto','utrata smaku'),
('Síntomas','Symptomy','el desmayo','omdlenie'),
('Síntomas','Symptomy','las palpitaciones','palpitacje'),
('Síntomas','Symptomy','la asfixia','duszność / duszenie się'),
('Síntomas','Symptomy','la debilidad muscular','osłabienie mięśni'),
('Síntomas','Symptomy','la rigidez','sztywność'),
('Síntomas','Symptomy','el temblor','drżenie'),
('Tratamientos Médicos','Leczenie','el tratamiento','leczenie / kuracja'),
('Tratamientos Médicos','Leczenie','el medicamento / la medicina','lekarstwo'),
('Tratamientos Médicos','Leczenie','la pastilla','tabletka / pigułka'),
('Tratamientos Médicos','Leczenie','el jarabe','syrop'),
('Tratamientos Médicos','Leczenie','la pomada / la crema','maść / krem'),
('Tratamientos Médicos','Leczenie','la inyección','zastrzyk'),
('Tratamientos Médicos','Leczenie','el suero','kroplówka'),
('Tratamientos Médicos','Leczenie','la vacuna','szczepionka'),
('Tratamientos Médicos','Leczenie','el antibiótico','antybiotyk'),
('Tratamientos Médicos','Leczenie','el analgésico','środek przeciwbólowy'),
('Tratamientos Médicos','Leczenie','la operación','operacja'),
('Tratamientos Médicos','Leczenie','la cirugía','chirurgia'),
('Tratamientos Médicos','Leczenie','la rehabilitación','rehabilitacja'),
('Tratamientos Médicos','Leczenie','la fisioterapia','fizjoterapia'),
('Tratamientos Médicos','Leczenie','el masaje','masaż'),
('Tratamientos Médicos','Leczenie','la terapia','terapia'),
('Tratamientos Médicos','Leczenie','la quimioterapia','chemioterapia'),
('Tratamientos Médicos','Leczenie','la radioterapia','radioterapia'),
('Tratamientos Médicos','Leczenie','el trasplante','przeszczep'),
('Tratamientos Médicos','Leczenie','la diálisis','dializa'),
('Tratamientos Médicos','Leczenie','la inhalación','inhalacja'),
('Tratamientos Médicos','Leczenie','el vendaje','opatrunek / bandażowanie'),
('Tratamientos Médicos','Leczenie','la venda','bandaż'),
('Tratamientos Médicos','Leczenie','el yeso / la escayola','gips'),
('Tratamientos Médicos','Leczenie','las muletas','kule ortopedyczne'),
('Tratamientos Médicos','Leczenie','la silla de ruedas','wózek inwalidzki'),
('Tratamientos Médicos','Leczenie','los puntos de sutura','szwy'),
('Tratamientos Médicos','Leczenie','los primeros auxilios','pierwsza pomoc'),
('Tratamientos Médicos','Leczenie','la reanimación / la RCP','resuscytacja'),
('Tratamientos Médicos','Leczenie','la respiración artificial','sztuczne oddychanie'),
('Tratamientos Médicos','Leczenie','el análisis de sangre','badanie krwi'),
('Tratamientos Médicos','Leczenie','la radiografía','rentgen'),
('Tratamientos Médicos','Leczenie','la resonancia magnética','rezonans magnetyczny'),
('Tratamientos Médicos','Leczenie','la ecografía','USG'),
('Tratamientos Médicos','Leczenie','la receta','recepta'),
('Tratamientos Médicos','Leczenie','la dosis','dawka'),
('Tratamientos Médicos','Leczenie','el reposo en cama','leżenie w łóżku (odpoczynek)'),
('Tratamientos Médicos','Leczenie','la dieta','dieta'),
('Tratamientos Médicos','Leczenie','las vitaminas','witaminy'),
('Tratamientos Médicos','Leczenie','el suplemento','suplement'),
('Tratamientos Médicos','Leczenie','la acupuntura','akupunktura'),
('Tratamientos Médicos','Leczenie','la homeopatía','homeopatia'),
('Tratamientos Médicos','Leczenie','la anestesia','znieczulenie'),
('Tratamientos Médicos','Leczenie','el desfibrilador','defibrylator'),
('Tratamientos Médicos','Leczenie','el respirador','respirator'),
('Tratamientos Médicos','Leczenie','la cuarentena','kwarantanna'),
('Tratamientos Médicos','Leczenie','el aislamiento','izolacja'),
('Tratamientos Médicos','Leczenie','la desintoxicación','detoks'),
('Tratamientos Médicos','Leczenie','el trasplante de médula','przeszczep szpiku'),
('Tratamientos Médicos','Leczenie','la terapia láser','laseroterapia'),
('Deportes de Equipo','Sporty zespołowe','el deporte de equipo','sport zespołowy'),
('Deportes de Equipo','Sporty zespołowe','el equipo','drużyna'),
('Deportes de Equipo','Sporty zespołowe','el jugador / la jugadora','zawodnik / gracz'),
('Deportes de Equipo','Sporty zespołowe','el entrenador','trener'),
('Deportes de Equipo','Sporty zespołowe','el capitán','kapitan'),
('Deportes de Equipo','Sporty zespołowe','el árbitro','sędzia'),
('Deportes de Equipo','Sporty zespołowe','el fútbol','piłka nożna'),
('Deportes de Equipo','Sporty zespołowe','el baloncesto','koszykówka'),
('Deportes de Equipo','Sporty zespołowe','el voleibol','siatkówka'),
('Deportes de Equipo','Sporty zespołowe','el balonmano','piłka ręczna'),
('Deportes de Equipo','Sporty zespołowe','el rugby','rugby'),
('Deportes de Equipo','Sporty zespołowe','el fútbol americano','futbol amerykański'),
('Deportes de Equipo','Sporty zespołowe','el béisbol','baseball'),
('Deportes de Equipo','Sporty zespołowe','el hockey sobre hielo','hokej na lodzie'),
('Deportes de Equipo','Sporty zespołowe','el hockey sobre hierba','hokej na trawie'),
('Deportes de Equipo','Sporty zespołowe','el waterpolo','piłka wodna'),
('Deportes de Equipo','Sporty zespołowe','el críquet','krykiet'),
('Deportes de Equipo','Sporty zespołowe','el lacrosse','lacrosse'),
('Deportes de Equipo','Sporty zespołowe','el polo','polo'),
('Deportes de Equipo','Sporty zespołowe','el curling','curling'),
('Deportes de Equipo','Sporty zespołowe','el partido','mecz'),
('Deportes de Equipo','Sporty zespołowe','el torneo','turniej'),
('Deportes de Equipo','Sporty zespołowe','el campeonato','mistrzostwa'),
('Deportes de Equipo','Sporty zespołowe','la liga','liga'),
('Deportes de Equipo','Sporty zespołowe','la copa','puchar'),
('Deportes de Equipo','Sporty zespołowe','el estadio','stadion'),
('Deportes de Equipo','Sporty zespołowe','el campo / la cancha','boisko'),
('Deportes de Equipo','Sporty zespołowe','la portería','bramka'),
('Deportes de Equipo','Sporty zespołowe','la canasta','kosz'),
('Deportes de Equipo','Sporty zespołowe','la red','siatka'),
('Deportes de Equipo','Sporty zespołowe','el balón / la pelota','piłka'),
('Deportes de Equipo','Sporty zespołowe','el disco','krążek (hokejowy)'),
('Deportes de Equipo','Sporty zespołowe','el casco','kask'),
('Deportes de Equipo','Sporty zespołowe','las protecciones','ochraniacze'),
('Deportes de Equipo','Sporty zespołowe','marcar un gol','strzelić gola'),
('Deportes de Equipo','Sporty zespołowe','anotar un punto','zdobyć punkt'),
('Deportes de Equipo','Sporty zespołowe','lanzar','rzucać'),
('Deportes de Equipo','Sporty zespołowe','atrapar / coger','łapać'),
('Deportes de Equipo','Sporty zespołowe','pasar','podawać'),
('Deportes de Equipo','Sporty zespołowe','la falta','faul'),
('Deportes de Equipo','Sporty zespołowe','el penalti','rzut karny'),
('Deportes de Equipo','Sporty zespołowe','el fuera de juego','spalony'),
('Deportes de Equipo','Sporty zespołowe','el empate','remis'),
('Deportes de Equipo','Sporty zespołowe','la prórroga','dogrywka'),
('Deportes de Equipo','Sporty zespołowe','ganar','wygrać'),
('Deportes de Equipo','Sporty zespołowe','perder','przegrać'),
('Deportes de Equipo','Sporty zespołowe','el aficionado / el hincha','kibic'),
('Deportes de Equipo','Sporty zespołowe','la táctica','taktyka'),
('Deportes de Equipo','Sporty zespołowe','la defensa','obrona'),
('Deportes de Equipo','Sporty zespołowe','el ataque','atak');
