insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('La Economía','Gospodarka','la economía','gospodarka / ekonomia'),
('La Economía','Gospodarka','el dinero','pieniądze'),
('La Economía','Gospodarka','el banco','bank'),
('La Economía','Gospodarka','la cuenta bancaria','konto bankowe'),
('La Economía','Gospodarka','la tarjeta de crédito','karta kredytowa'),
('La Economía','Gospodarka','el efectivo / el metálico','gotówka'),
('La Economía','Gospodarka','la moneda','moneta / waluta'),
('La Economía','Gospodarka','el billete','banknot'),
('La Economía','Gospodarka','el cajero automático','bankomat'),
('La Economía','Gospodarka','el ingreso','przychód / dochód'),
('La Economía','Gospodarka','el gasto','wydatek'),
('La Economía','Gospodarka','el presupuesto','budżet'),
('La Economía','Gospodarka','el sueldo','pensja'),
('La Economía','Gospodarka','el salario','wynagrodzenie'),
('La Economía','Gospodarka','el precio','cena'),
('La Economía','Gospodarka','el coste / el costo','koszt'),
('La Economía','Gospodarka','barato','tani'),
('La Economía','Gospodarka','caro','drogi'),
('La Economía','Gospodarka','la inflación','inflacja'),
('La Economía','Gospodarka','la crisis económica','kryzys gospodarczy'),
('La Economía','Gospodarka','el crecimiento','wzrost'),
('La Economía','Gospodarka','el mercado','rynek'),
('La Economía','Gospodarka','la empresa','firma / przedsiębiorstwo'),
('La Economía','Gospodarka','el negocio','biznes / interes'),
('La Economía','Gospodarka','el empresario','przedsiębiorca'),
('La Economía','Gospodarka','el trabajador','pracownik'),
('La Economía','Gospodarka','el empleo','zatrudnienie'),
('La Economía','Gospodarka','el desempleo / el paro','bezrobocie'),
('La Economía','Gospodarka','la tasa de paro','stopa bezrobocia'),
('La Economía','Gospodarka','el contrato','kontrakt / umowa'),
('La Economía','Gospodarka','la inversión','inwestycja'),
('La Economía','Gospodarka','invertir','inwestować'),
('La Economía','Gospodarka','la bolsa (de valores)','giełda (papierów wartościowych)'),
('La Economía','Gospodarka','la acción','akcja (giełdowa)'),
('La Economía','Gospodarka','el dividendo','dywidenda'),
('La Economía','Gospodarka','el impuesto','podatek'),
('La Economía','Gospodarka','el IVA','podatek VAT'),
('La Economía','Gospodarka','la factura','faktura'),
('La Economía','Gospodarka','el recibo','paragon / pokwitowanie'),
('La Economía','Gospodarka','el cheque','czek'),
('La Economía','Gospodarka','el préstamo','pożyczka'),
('La Economía','Gospodarka','la deuda','dług'),
('La Economía','Gospodarka','el interés','odsetki / oprocentowanie'),
('La Economía','Gospodarka','la hipoteca','kredyt hipoteczny'),
('La Economía','Gospodarka','el ahorro','oszczędności'),
('La Economía','Gospodarka','ahorrar','oszczędzać'),
('La Economía','Gospodarka','comprar','kupować'),
('La Economía','Gospodarka','vender','sprzedawać'),
('La Economía','Gospodarka','el comercio','handel'),
('La Economía','Gospodarka','la exportación','eksport'),
('La Geografía','Geografia','la geografía','geografia'),
('La Geografía','Geografia','el mapa','mapa'),
('La Geografía','Geografia','el globo terráqueo','globus'),
('La Geografía','Geografia','el continente','kontynent'),
('La Geografía','Geografia','el país','kraj / państwo'),
('La Geografía','Geografia','la frontera','granica'),
('La Geografía','Geografia','el océano','ocean'),
('La Geografía','Geografia','el mar','morze'),
('La Geografía','Geografia','el golfo','zatoka (duża)'),
('La Geografía','Geografia','la bahía','zatoka (mniejsza)'),
('La Geografía','Geografia','el lago','jezioro'),
('La Geografía','Geografia','el río','rzeka'),
('La Geografía','Geografia','el arroyo','strumień'),
('La Geografía','Geografia','la montaña','góra'),
('La Geografía','Geografia','la cordillera','łańcuch górski'),
('La Geografía','Geografia','el volcán','wulkan'),
('La Geografía','Geografia','el valle','dolina'),
('La Geografía','Geografia','la llanura','równina'),
('La Geografía','Geografia','el desierto','pustynia'),
('La Geografía','Geografia','la selva','dżungla'),
('La Geografía','Geografia','el bosque','las'),
('La Geografía','Geografia','el ecuador','równik'),
('La Geografía','Geografia','el polo norte','biegun północny'),
('La Geografía','Geografia','el polo sur','biegun południowy'),
('La Geografía','Geografia','la latitud','szerokość geograficzna'),
('La Geografía','Geografia','la longitud','długość geograficzna'),
('La Geografía','Geografia','el clima','klimat'),
('La Geografía','Geografia','la península','półwysep'),
('La Geografía','Geografia','la isla','wyspa'),
('La Geografía','Geografia','el archipiélago','archipelag'),
('La Geografía','Geografia','el cabo','przylądek'),
('La Geografía','Geografia','el estrecho','cieśnina'),
('La Geografía','Geografia','la costa','wybrzeże'),
('La Geografía','Geografia','la playa','plaża'),
('La Geografía','Geografia','el acantilado','klif'),
('La Geografía','Geografia','la cueva','jaskinia'),
('La Geografía','Geografia','el hemisferio','półkula'),
('La Geografía','Geografia','la altitud','wysokość (n.p.m.)'),
('La Geografía','Geografia','el relieve','ukształtowanie powierzchni'),
('La Geografía','Geografia','el paisaje','krajobraz'),
('La Geografía','Geografia','el territorio','terytorium'),
('La Geografía','Geografia','la capital','stolica'),
('La Geografía','Geografia','la provincia','prowincja'),
('La Geografía','Geografia','el municipio','gmina / miasto'),
('La Geografía','Geografia','la región','region'),
('La Geografía','Geografia','el habitante','mieszkaniec'),
('La Geografía','Geografia','la población','populacja / ludność'),
('La Geografía','Geografia','el glaciar','lodowiec'),
('La Geografía','Geografia','el pantano','bagno'),
('La Geografía','Geografia','la duna','wydma'),
('La Historia','Historia','la historia','historia'),
('La Historia','Historia','el pasado','przeszłość'),
('La Historia','Historia','el presente','teraźniejszość'),
('La Historia','Historia','el futuro','przyszłość'),
('La Historia','Historia','el siglo','wiek / stulecie'),
('La Historia','Historia','la década','dekada'),
('La Historia','Historia','la época','epoka'),
('La Historia','Historia','la era','era'),
('La Historia','Historia','la prehistoria','prehistoria'),
('La Historia','Historia','la antigüedad','starożytność'),
('La Historia','Historia','la Edad Media','średniowiecze'),
('La Historia','Historia','el Renacimiento','renesans'),
('La Historia','Historia','el imperio','imperium'),
('La Historia','Historia','el rey','król'),
('La Historia','Historia','la reina','królowa'),
('La Historia','Historia','el emperador','cesarz'),
('La Historia','Historia','el faraón','faraon'),
('La Historia','Historia','el caballero','rycerz'),
('La Historia','Historia','el castillo','zamek'),
('La Historia','Historia','la corona','korona'),
('La Historia','Historia','la guerra','wojna'),
('La Historia','Historia','la paz','pokój (stan bez wojny)'),
('La Historia','Historia','la batalla','bitwa'),
('La Historia','Historia','el ejército','wojsko / armia'),
('La Historia','Historia','la revolución','rewolucja'),
('La Historia','Historia','la independencia','niepodległość'),
('La Historia','Historia','el descubrimiento','odkrycie'),
('La Historia','Historia','el explorador','odkrywca'),
('La Historia','Historia','la colonia','kolonia'),
('La Historia','Historia','el tratado','traktat'),
('La Historia','Historia','la alianza','sojusz'),
('La Historia','Historia','la victoria','zwycięstwo'),
('La Historia','Historia','la derrota','porażka'),
('La Historia','Historia','el héroe','bohater'),
('La Historia','Historia','el líder','przywódca'),
('La Historia','Historia','la civilización','cywilizacja'),
('La Historia','Historia','el monumento','pomnik / zabytek'),
('La Historia','Historia','la ruina','ruina'),
('La Historia','Historia','el museo','muzeum'),
('La Historia','Historia','el arqueólogo','archeolog'),
('La Historia','Historia','la excavación','wykopalisko'),
('La Historia','Historia','el artefacto','artefakt'),
('La Historia','Historia','el documento','dokument'),
('La Historia','Historia','el archivo','archiwum'),
('La Historia','Historia','el mito','mit'),
('La Historia','Historia','la leyenda','legenda'),
('La Historia','Historia','la tradición','tradycja'),
('La Historia','Historia','el antepasado','przodek'),
('La Historia','Historia','el progreso','postęp'),
('La Historia','Historia','la cronología','chronologia'),
('Las Emociones','Emocje','la emoción','emocja'),
('Las Emociones','Emocje','el sentimiento','uczucie'),
('Las Emociones','Emocje','la alegría','radość'),
('Las Emociones','Emocje','la tristeza','smutek'),
('Las Emociones','Emocje','el enfado / la ira','złość / gniew'),
('Las Emociones','Emocje','el miedo','strach'),
('Las Emociones','Emocje','la sorpresa','niespodzianka / zdziwienie'),
('Las Emociones','Emocje','el asco','wstręt'),
('Las Emociones','Emocje','el amor','miłość'),
('Las Emociones','Emocje','el odio','nienawiść'),
('Las Emociones','Emocje','la felicidad','szczęście'),
('Las Emociones','Emocje','la depresión','depresja'),
('Las Emociones','Emocje','la ansiedad','niepokój / lęk'),
('Las Emociones','Emocje','el estrés','stres'),
('Las Emociones','Emocje','la tranquilidad','spokój'),
('Las Emociones','Emocje','la esperanza','nadzieja'),
('Las Emociones','Emocje','la desesperación','rozpacz'),
('Las Emociones','Emocje','la culpa','wina'),
('Las Emociones','Emocje','la vergüenza','wstyd'),
('Las Emociones','Emocje','el orgullo','duma'),
('Las Emociones','Emocje','la envidia','zazdrość (o to, co ma ktoś)'),
('Las Emociones','Emocje','los celos','zazdrość (w miłości)'),
('Las Emociones','Emocje','la compasión','współczucie'),
('Las Emociones','Emocje','la empatía','empatia'),
('Las Emociones','Emocje','la simpatía','sympatia'),
('Las Emociones','Emocje','el aburrimiento','nuda'),
('Las Emociones','Emocje','la diversión','zabawa'),
('Las Emociones','Emocje','el entusiasmo','entuzjazm'),
('Las Emociones','Emocje','la frustración','frustracja'),
('Las Emociones','Emocje','la confusión','dezorientacja'),
('Las Emociones','Emocje','la decepción','rozczarowanie'),
('Las Emociones','Emocje','el alivio','ulga'),
('Las Emociones','Emocje','la gratitud','wdzięczność'),
('Las Emociones','Emocje','la nostalgia','nostalgia / tęsknota'),
('Las Emociones','Emocje','la soledad','samotność'),
('Las Emociones','Emocje','el cariño','czułość'),
('Las Emociones','Emocje','la pasión','pasja / namiętność'),
('Las Emociones','Emocje','la ternura','tkliwość'),
('Las Emociones','Emocje','la admiración','podziw'),
('Las Emociones','Emocje','el pánico','panika'),
('Las Emociones','Emocje','el terror','przerażenie'),
('Las Emociones','Emocje','la euforia','euforia'),
('Las Emociones','Emocje','el nerviosismo','nerwowość'),
('Las Emociones','Emocje','la confianza','zaufanie / pewność siebie'),
('Las Emociones','Emocje','la duda','wątpliwość'),
('Las Emociones','Emocje','el optimismo','optymizm'),
('Las Emociones','Emocje','el pesimismo','pesymizm'),
('Las Emociones','Emocje','llorar','płakać'),
('Las Emociones','Emocje','reír','śmiać się'),
('Las Emociones','Emocje','sonreír','uśmiechać się');
