insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Los Muebles','Meble','el mueble','mebel'),
('Los Muebles','Meble','amueblar','umeblować'),
('Los Muebles','Meble','la silla','krzesło'),
('Los Muebles','Meble','la mesa','stół'),
('Los Muebles','Meble','el sofá','kanapa'),
('Los Muebles','Meble','el sillón','fotel'),
('Los Muebles','Meble','la cama','łóżko'),
('Los Muebles','Meble','el armario','szafa'),
('Los Muebles','Meble','la estantería','regał'),
('Los Muebles','Meble','el estante','półka'),
('Los Muebles','Meble','la cómoda','komoda'),
('Los Muebles','Meble','el cajón','szuflada'),
('Los Muebles','Meble','la mesita de noche','stolik nocny'),
('Los Muebles','Meble','el escritorio','biurko'),
('Los Muebles','Meble','el taburete','stołek / taboret'),
('Los Muebles','Meble','la butaca','fotel / miejsce na widowni'),
('Los Muebles','Meble','el perchero','wieszak (stojący)'),
('Los Muebles','Meble','la percha','wieszak (do szafy)'),
('Los Muebles','Meble','el zapatero','szafka na buty'),
('Los Muebles','Meble','el aparador','kredens'),
('Los Muebles','Meble','la vitrina','witryna (mebel)'),
('Los Muebles','Meble','el tocador','toaletka'),
('Los Muebles','Meble','el espejo','lustro'),
('Los Muebles','Meble','la lámpara','lampa'),
('Los Muebles','Meble','la cuna','łóżeczko dziecięce'),
('Los Muebles','Meble','la litera','łóżko piętrowe'),
('Los Muebles','Meble','el colchón','materac'),
('Los Muebles','Meble','el cojín','poduszka (dekoracyjna)'),
('Los Muebles','Meble','la alfombra','dywan'),
('Los Muebles','Meble','la cortina','zasłona'),
('Los Muebles','Meble','el cuadro','obraz'),
('Los Muebles','Meble','el póster','plakat'),
('Los Muebles','Meble','la mecedora','fotel bujany'),
('Los Muebles','Meble','la hamaca','hamak'),
('Los Muebles','Meble','el cabecero','wezgłowie'),
('Los Muebles','Meble','el banco','ławka'),
('Los Muebles','Meble','la tapicería','tapicerka'),
('Los Muebles','Meble','de madera','z drewna'),
('Los Muebles','Meble','de plástico','z plastiku'),
('Los Muebles','Meble','de metal','z metalu'),
('Los Muebles','Meble','de cristal','ze szkła'),
('Los Muebles','Meble','antiguo','zabytkowy / stary'),
('Los Muebles','Meble','moderno','nowoczesny'),
('Los Muebles','Meble','montar','składać (meble)'),
('Los Muebles','Meble','desmontar','rozkładać (meble)'),
('Los Muebles','Meble','el diseño','design'),
('Los Muebles','Meble','espacioso','przestronny'),
('Los Muebles','Meble','cómodo','wygodny'),
('Los Muebles','Meble','incómodo','niewygodny'),
('Los Muebles','Meble','la decoración','dekoracja'),
('Los Electrodomésticos','Sprzęt AGD','el electrodoméstico','sprzęt AGD'),
('Los Electrodomésticos','Sprzęt AGD','la nevera / el frigorífico','lodówka'),
('Los Electrodomésticos','Sprzęt AGD','el congelador','zamrażarka'),
('Los Electrodomésticos','Sprzęt AGD','el horno','piekarnik'),
('Los Electrodomésticos','Sprzęt AGD','el microondas','mikrofalówka'),
('Los Electrodomésticos','Sprzęt AGD','la cocina (eléctrica/de gas)','kuchenka (elektryczna/gazowa)'),
('Los Electrodomésticos','Sprzęt AGD','la campana extractora','okap kuchenny'),
('Los Electrodomésticos','Sprzęt AGD','el lavavajillas / el lavaplatos','zmywarka'),
('Los Electrodomésticos','Sprzęt AGD','la lavadora','pralka'),
('Los Electrodomésticos','Sprzęt AGD','la secadora','suszarka do ubrań'),
('Los Electrodomésticos','Sprzęt AGD','la plancha','żelazko'),
('Los Electrodomésticos','Sprzęt AGD','la aspiradora','odkurzacz'),
('Los Electrodomésticos','Sprzęt AGD','el televisor / la tele','telewizor'),
('Los Electrodomésticos','Sprzęt AGD','la radio','radio'),
('Los Electrodomésticos','Sprzęt AGD','el ventilador','wentylator'),
('Los Electrodomésticos','Sprzęt AGD','el aire acondicionado','klimatyzacja'),
('Los Electrodomésticos','Sprzęt AGD','la estufa / el calentador','piecyk / grzejnik'),
('Los Electrodomésticos','Sprzęt AGD','el radiador','kaloryfer'),
('Los Electrodomésticos','Sprzęt AGD','el secador de pelo','suszarka do włosów'),
('Los Electrodomésticos','Sprzęt AGD','la tostadora','toster'),
('Los Electrodomésticos','Sprzęt AGD','la batidora','mikser / blender'),
('Los Electrodomésticos','Sprzęt AGD','la cafetera','ekspres do kawy'),
('Los Electrodomésticos','Sprzęt AGD','el hervidor (de agua)','czajnik (elektryczny)'),
('Los Electrodomésticos','Sprzęt AGD','el exprimidor','wyciskarka'),
('Los Electrodomésticos','Sprzęt AGD','la licuadora','sokowirówka'),
('Los Electrodomésticos','Sprzęt AGD','la freidora','frytkownica'),
('Los Electrodomésticos','Sprzęt AGD','la báscula / el peso','waga'),
('Los Electrodomésticos','Sprzęt AGD','la maquinilla de afeitar','maszynka do golenia (elektryczna)'),
('Los Electrodomésticos','Sprzęt AGD','la máquina de coser','maszyna do szycia'),
('Los Electrodomésticos','Sprzęt AGD','el robot de cocina','robot kuchenny'),
('Los Electrodomésticos','Sprzęt AGD','el enchufe','wtyczka / gniazdko'),
('Los Electrodomésticos','Sprzęt AGD','el cable','kabel'),
('Los Electrodomésticos','Sprzęt AGD','el botón','przycisk'),
('Los Electrodomésticos','Sprzęt AGD','el interruptor','włącznik'),
('Los Electrodomésticos','Sprzęt AGD','la pantalla','ekran'),
('Los Electrodomésticos','Sprzęt AGD','el mando a distancia','pilot (np. do TV)'),
('Los Electrodomésticos','Sprzęt AGD','la batería','bateria'),
('Los Electrodomésticos','Sprzęt AGD','enchufar','podłączać do prądu'),
('Los Electrodomésticos','Sprzęt AGD','desenchufar','odłączać od prądu'),
('Los Electrodomésticos','Sprzęt AGD','encender','włączać'),
('Los Electrodomésticos','Sprzęt AGD','apagar','wyłączać'),
('Los Electrodomésticos','Sprzęt AGD','funcionar','działać'),
('Los Electrodomésticos','Sprzęt AGD','estar estropeado','być zepsutym'),
('Los Electrodomésticos','Sprzęt AGD','estar roto','być rozbitym / zepsutym'),
('Los Electrodomésticos','Sprzęt AGD','reparar / arreglar','naprawiać'),
('Los Electrodomésticos','Sprzęt AGD','el técnico','technik / fachowiec'),
('Los Electrodomésticos','Sprzęt AGD','el repuesto','część zamienna'),
('Los Electrodomésticos','Sprzęt AGD','consumir','zużywać (energię)'),
('Los Electrodomésticos','Sprzęt AGD','el consumo','zużycie'),
('Los Electrodomésticos','Sprzęt AGD','inteligente','inteligentny (smart)'),
('Herramientas','Narzędzia','la herramienta','narzędzie'),
('Herramientas','Narzędzia','la caja de herramientas','skrzynka z narzędziami'),
('Herramientas','Narzędzia','el martillo','młotek'),
('Herramientas','Narzędzia','el clavo','gwóźdź'),
('Herramientas','Narzędzia','el tornillo','śruba / wkręt'),
('Herramientas','Narzędzia','el destornillador','śrubokręt'),
('Herramientas','Narzędzia','la tuerca','nakrętka'),
('Herramientas','Narzędzia','la llave inglesa','klucz francuski / nastawny'),
('Herramientas','Narzędzia','la llave Allen','klucz imbusowy'),
('Herramientas','Narzędzia','los alicates / el alicate','kombinerki / obcęgi'),
('Herramientas','Narzędzia','la sierra','piła (narzędzie)'),
('Herramientas','Narzędzia','el serrucho','piła ręczna'),
('Herramientas','Narzędzia','el taladro','wiertarka'),
('Herramientas','Narzędzia','la broca','wiertło'),
('Herramientas','Narzędzia','la cinta métrica','miara zwijana'),
('Herramientas','Narzędzia','la regla','linijka'),
('Herramientas','Narzędzia','el nivel','poziomica'),
('Herramientas','Narzędzia','el cúter','nóż do tapet / introligatorski'),
('Herramientas','Narzędzia','las tijeras','nożyczki'),
('Herramientas','Narzędzia','el pegamento','klej'),
('Herramientas','Narzędzia','la cinta adhesiva','taśma klejąca'),
('Herramientas','Narzędzia','la cinta aislante','taśma izolacyjna'),
('Herramientas','Narzędzia','la cuerda','lina / sznurek'),
('Herramientas','Narzędzia','el alambre','drut'),
('Herramientas','Narzędzia','la pala','łopata / szufla'),
('Herramientas','Narzędzia','el pico','kilof'),
('Herramientas','Narzędzia','el hacha','siekiera'),
('Herramientas','Narzędzia','la azada','motyka'),
('Herramientas','Narzędzia','el rastrillo','grabie'),
('Herramientas','Narzędzia','la carretilla','taczka'),
('Herramientas','Narzędzia','el pincel','pędzel'),
('Herramientas','Narzędzia','la brocha','pędzel malarski (szeroki)'),
('Herramientas','Narzędzia','el rodillo','wałek malarski'),
('Herramientas','Narzędzia','la pintura','farba'),
('Herramientas','Narzędzia','el papel de lija','papier ścierny'),
('Herramientas','Narzędzia','la espátula','szpachelka'),
('Herramientas','Narzędzia','la linterna','latarka'),
('Herramientas','Narzędzia','la lima','pilnik'),
('Herramientas','Narzędzia','el cincel','dłuto'),
('Herramientas','Narzędzia','el soldador','lutownica / spawarka'),
('Herramientas','Narzędzia','el casco','kask'),
('Herramientas','Narzędzia','los guantes de trabajo','rękawice robocze'),
('Herramientas','Narzędzia','clavar','wbijać (gwoździe)'),
('Herramientas','Narzędzia','atornillar','wkręcać (śrubę)'),
('Herramientas','Narzędzia','cortar','ciąć'),
('Herramientas','Narzędzia','pegar','kleić'),
('Herramientas','Narzędzia','medir','mierzyć'),
('Herramientas','Narzędzia','pintar','malować'),
('Herramientas','Narzędzia','lijar','szlifować'),
('Herramientas','Narzędzia','construir','budować'),
('El Coche','Samochód','el coche / el auto','samochód'),
('El Coche','Samochód','el volante','kierownica'),
('El Coche','Samochód','el motor','silnik'),
('El Coche','Samochód','la rueda','koło'),
('El Coche','Samochód','el neumático / la llanta','opona'),
('El Coche','Samochód','el freno','hamulec'),
('El Coche','Samochód','el acelerador','pedał gazu'),
('El Coche','Samochód','el embrague','sprzęgło'),
('El Coche','Samochód','la marcha','bieg (w samochodzie)'),
('El Coche','Samochód','el cinturón de seguridad','pas bezpieczeństwa'),
('El Coche','Samochód','el asiento','siedzenie / fotel'),
('El Coche','Samochód','el maletero','bagażnik'),
('El Coche','Samochód','el capó','maska samochodu'),
('El Coche','Samochód','el parabrisas','szyba przednia'),
('El Coche','Samochód','el limpiaparabrisas','wycieraczka (samochodowa)'),
('El Coche','Samochód','el espejo retrovisor','lusterko wsteczne'),
('El Coche','Samochód','el faro','reflektor'),
('El Coche','Samochód','la luz intermitente','kierunkowskaz'),
('El Coche','Samochód','la matrícula / la placa','tablica rejestracyjna'),
('El Coche','Samochód','la puerta','drzwi'),
('El Coche','Samochód','la ventanilla','szyba (w drzwiach)'),
('El Coche','Samochód','el claxon / la bocina','klakson'),
('El Coche','Samochód','el tubo de escape','rura wydechowa'),
('El Coche','Samochód','el depósito','bak'),
('El Coche','Samochód','la gasolina','benzyna'),
('El Coche','Samochód','el diésel / el gasoil','olej napędowy / diesel'),
('El Coche','Samochód','eléctrico','elektryczny (samochód)'),
('El Coche','Samochód','la gasolinera','stacja benzynowa'),
('El Coche','Samochód','el mecánico','mechanik'),
('El Coche','Samochód','el taller','warsztat'),
('El Coche','Samochód','la avería','awaria'),
('El Coche','Samochód','el accidente','wypadek'),
('El Coche','Samochód','conducir / manejar','prowadzić (samochód)'),
('El Coche','Samochód','frenar','hamować'),
('El Coche','Samochód','acelerar','przyspieszać'),
('El Coche','Samochód','aparcar / estacionar','parkować'),
('El Coche','Samochód','arrancar','odpalać / ruszać'),
('El Coche','Samochód','la velocidad','prędkość'),
('El Coche','Samochód','el límite de velocidad','ograniczenie prędkości'),
('El Coche','Samochód','la carretera','szosa / droga'),
('El Coche','Samochód','la autopista','autostrada'),
('El Coche','Samochód','el peaje','bramka autostradowa / myto'),
('El Coche','Samochód','el conductor','kierowca'),
('El Coche','Samochód','el pasajero','pasażer'),
('El Coche','Samochód','el carnet de conducir','prawo jazdy'),
('El Coche','Samochód','el seguro','ubezpieczenie'),
('El Coche','Samochód','la multa','mandat'),
('El Coche','Samochód','el tráfico','ruch drogowy'),
('El Coche','Samochód','el atasco / el embotellamiento','korek drogowy'),
('El Coche','Samochód','adelantar','wyprzedzać');
