insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Pintura y Escultura','Malarstwo i rzeźba','la pintura','malarstwo / farba'),
('Pintura y Escultura','Malarstwo i rzeźba','el cuadro','obraz'),
('Pintura y Escultura','Malarstwo i rzeźba','el pintor','malarz'),
('Pintura y Escultura','Malarstwo i rzeźba','la pintora','malarka'),
('Pintura y Escultura','Malarstwo i rzeźba','el pincel','pędzel'),
('Pintura y Escultura','Malarstwo i rzeźba','la paleta','paleta'),
('Pintura y Escultura','Malarstwo i rzeźba','el lienzo','płótno'),
('Pintura y Escultura','Malarstwo i rzeźba','el caballete','sztaluga'),
('Pintura y Escultura','Malarstwo i rzeźba','la acuarela','akwarela'),
('Pintura y Escultura','Malarstwo i rzeźba','el óleo','farba olejna / obraz olejny'),
('Pintura y Escultura','Malarstwo i rzeźba','el acrílico','akryl'),
('Pintura y Escultura','Malarstwo i rzeźba','el pastel','pastel'),
('Pintura y Escultura','Malarstwo i rzeźba','el carboncillo','węgiel (do rysowania)'),
('Pintura y Escultura','Malarstwo i rzeźba','el boceto','szkic / zarys'),
('Pintura y Escultura','Malarstwo i rzeźba','el esbozo','szkic'),
('Pintura y Escultura','Malarstwo i rzeźba','el dibujo','rysunek'),
('Pintura y Escultura','Malarstwo i rzeźba','el retrato','portret'),
('Pintura y Escultura','Malarstwo i rzeźba','el autorretrato','autoportret'),
('Pintura y Escultura','Malarstwo i rzeźba','el paisaje','pejzaż / krajobraz'),
('Pintura y Escultura','Malarstwo i rzeźba','el bodegón','martwa natura'),
('Pintura y Escultura','Malarstwo i rzeźba','la perspectiva','perspektywa'),
('Pintura y Escultura','Malarstwo i rzeźba','la textura','tekstura'),
('Pintura y Escultura','Malarstwo i rzeźba','la obra de arte','dzieło sztuki'),
('Pintura y Escultura','Malarstwo i rzeźba','la exposición','wystawa'),
('Pintura y Escultura','Malarstwo i rzeźba','la galería','galeria (sztuki)'),
('Pintura y Escultura','Malarstwo i rzeźba','el museo','muzeum'),
('Pintura y Escultura','Malarstwo i rzeźba','el marco','rama'),
('Pintura y Escultura','Malarstwo i rzeźba','la escultura','rzeźba'),
('Pintura y Escultura','Malarstwo i rzeźba','el escultor','rzeźbiarz'),
('Pintura y Escultura','Malarstwo i rzeźba','esculpir','rzeźbić'),
('Pintura y Escultura','Malarstwo i rzeźba','tallar','rzeźbić / ciosać (w drewnie/kamieniu)'),
('Pintura y Escultura','Malarstwo i rzeźba','el mármol','marmur'),
('Pintura y Escultura','Malarstwo i rzeźba','el bronce','brąz'),
('Pintura y Escultura','Malarstwo i rzeźba','la arcilla','glina'),
('Pintura y Escultura','Malarstwo i rzeźba','el yeso','gips'),
('Pintura y Escultura','Malarstwo i rzeźba','la piedra','kamień'),
('Pintura y Escultura','Malarstwo i rzeźba','el cincel','dłuto'),
('Pintura y Escultura','Malarstwo i rzeźba','el martillo','młotek'),
('Pintura y Escultura','Malarstwo i rzeźba','el relieve','płaskorzeźba'),
('Pintura y Escultura','Malarstwo i rzeźba','el busto','popiersie'),
('Pintura y Escultura','Malarstwo i rzeźba','la estatua','statua / posąg'),
('Pintura y Escultura','Malarstwo i rzeźba','el monumento','pomnik'),
('Pintura y Escultura','Malarstwo i rzeźba','la obra maestra','arcydzieło'),
('Pintura y Escultura','Malarstwo i rzeźba','la creatividad','kreatywność'),
('Pintura y Escultura','Malarstwo i rzeźba','abstracto','abstrakcyjny'),
('Pintura y Escultura','Malarstwo i rzeźba','figurativo','figuratywny'),
('Pintura y Escultura','Malarstwo i rzeźba','realista','realistyczny'),
('Pintura y Escultura','Malarstwo i rzeźba','surrealista','surrealistyczny'),
('Pintura y Escultura','Malarstwo i rzeźba','la pincelada','pociągnięcie pędzlem'),
('Pintura y Escultura','Malarstwo i rzeźba','las bellas artes','sztuki piękne'),
('Arquitectura','Architektura','la arquitectura','architektura'),
('Arquitectura','Architektura','el arquitecto','architekt'),
('Arquitectura','Architektura','el edificio','budynek'),
('Arquitectura','Architektura','la construcción','budowa / konstrukcja'),
('Arquitectura','Architektura','construir','budować'),
('Arquitectura','Architektura','el plano','plan / projekt'),
('Arquitectura','Architektura','el diseño','projekt / design'),
('Arquitectura','Architektura','el proyecto','projekt'),
('Arquitectura','Architektura','los cimientos','fundamenty'),
('Arquitectura','Architektura','la fachada','fasada / elewacja'),
('Arquitectura','Architektura','el muro','mur'),
('Arquitectura','Architektura','la pared','ściana'),
('Arquitectura','Architektura','el techo','sufit / dach'),
('Arquitectura','Architektura','el tejado','dach'),
('Arquitectura','Architektura','la columna','kolumna'),
('Arquitectura','Architektura','el pilar','filar'),
('Arquitectura','Architektura','el arco','łuk (architektoniczny)'),
('Arquitectura','Architektura','la bóveda','sklepienie'),
('Arquitectura','Architektura','la cúpula','kopuła'),
('Arquitectura','Architektura','la escalera','schody'),
('Arquitectura','Architektura','el balcón','balkon'),
('Arquitectura','Architektura','la terraza','taras'),
('Arquitectura','Architektura','la ventana','okno'),
('Arquitectura','Architektura','la puerta','drzwi'),
('Arquitectura','Architektura','el rascacielos','drapacz chmur'),
('Arquitectura','Architektura','la torre','wieża'),
('Arquitectura','Architektura','el castillo','zamek'),
('Arquitectura','Architektura','el palacio','pałac'),
('Arquitectura','Architektura','la iglesia','kościół'),
('Arquitectura','Architektura','la catedral','katedra'),
('Arquitectura','Architektura','el templo','świątynia'),
('Arquitectura','Architektura','la mezquita','meczet'),
('Arquitectura','Architektura','el puente','most'),
('Arquitectura','Architektura','el monumento','zabytek / pomnik'),
('Arquitectura','Architektura','el ladrillo','cegła'),
('Arquitectura','Architektura','el cemento','cement'),
('Arquitectura','Architektura','el hormigón','beton'),
('Arquitectura','Architektura','el acero','stal'),
('Arquitectura','Architektura','el vidrio','szkło'),
('Arquitectura','Architektura','la madera','drewno'),
('Arquitectura','Architektura','el estilo gótico','styl gotycki'),
('Arquitectura','Architektura','el estilo románico','styl romański'),
('Arquitectura','Architektura','el estilo barroco','styl barokowy'),
('Arquitectura','Architektura','el estilo renacentista','styl renesansowy'),
('Arquitectura','Architektura','el estilo modernista','styl modernistyczny'),
('Arquitectura','Architektura','el espacio','przestrzeń'),
('Arquitectura','Architektura','la luz','światło'),
('Arquitectura','Architektura','el urbanismo','urbanistyka'),
('Arquitectura','Architektura','el plano de planta','rzut poziomy'),
('Arquitectura','Architektura','la estructura','struktura / szkielet'),
('Fotografía','Fotografia','la fotografía','fotografia'),
('Fotografía','Fotografia','la foto','zdjęcie'),
('Fotografía','Fotografia','el fotógrafo','fotograf'),
('Fotografía','Fotografia','la cámara (fotográfica)','aparat (fotograficzny)'),
('Fotografía','Fotografia','el objetivo / la lente','obiektyw / soczewka'),
('Fotografía','Fotografia','el flash','flesz / lampa błyskowa'),
('Fotografía','Fotografia','el trípode','statyw'),
('Fotografía','Fotografia','el enfoque','ostrość / punkt ostrości'),
('Fotografía','Fotografia','enfocar','ustawiać ostrość'),
('Fotografía','Fotografia','el encuadre','kadr'),
('Fotografía','Fotografia','la luz','światło'),
('Fotografía','Fotografia','la iluminación','oświetlenie'),
('Fotografía','Fotografia','el contraste','kontrast'),
('Fotografía','Fotografia','la exposición','ekspozycja'),
('Fotografía','Fotografia','el diafragma','przesłona'),
('Fotografía','Fotografia','la velocidad de obturación','czas naświetlania'),
('Fotografía','Fotografia','el sensor','matryca (w aparacie)'),
('Fotografía','Fotografia','el carrete','klisza / film'),
('Fotografía','Fotografia','revelar','wywoływać (zdjęcia)'),
('Fotografía','Fotografia','el cuarto oscuro','ciemnia'),
('Fotografía','Fotografia','el álbum','album'),
('Fotografía','Fotografia','el retrato','portret'),
('Fotografía','Fotografia','el paisaje','pejzaż'),
('Fotografía','Fotografia','la fotografía en blanco y negro','fotografia czarno-biała'),
('Fotografía','Fotografia','la fotografía en color','fotografia kolorowa'),
('Fotografía','Fotografia','el primer plano','pierwszy plan / zbliżenie'),
('Fotografía','Fotografia','el fondo','tło'),
('Fotografía','Fotografia','el píxel','piksel'),
('Fotografía','Fotografia','la resolución','rozdzielczość'),
('Fotografía','Fotografia','el archivo','plik (np. ze zdjęciem)'),
('Fotografía','Fotografia','editar','edytować'),
('Fotografía','Fotografia','retocar','retuszować'),
('Fotografía','Fotografia','el filtro','filtr'),
('Fotografía','Fotografia','el modelo / la modelo','model / modelka'),
('Fotografía','Fotografia','posar','pozować'),
('Fotografía','Fotografia','el estudio fotográfico','studio fotograficzne'),
('Fotografía','Fotografia','la instantánea','zdjęcie natychmiastowe / polaroid'),
('Fotografía','Fotografia','el fotoperiodismo','fotoreportaż'),
('Fotografía','Fotografia','hacer una foto / sacar una foto','robić zdjęcie'),
('Fotografía','Fotografia','borrar','kasować'),
('Fotografía','Fotografia','guardar','zapisywać'),
('Fotografía','Fotografia','capturar','uchwycić'),
('Fotografía','Fotografia','la nitidez','ostrość (zdjęcia)'),
('Fotografía','Fotografia','desenfocado','rozmazany / nieostry'),
('Fotografía','Fotografia','nítido','ostry / wyraźny'),
('Fotografía','Fotografia','el gran angular','obiektyw szerokokątny'),
('Fotografía','Fotografia','el teleobjetivo','teleobiektyw'),
('Fotografía','Fotografia','la tarjeta de memoria','karta pamięci'),
('Fotografía','Fotografia','el autorretrato / el selfi','autoportret / selfie'),
('Fotografía','Fotografia','el visor','wizjer'),
('Géneros Literarios','Gatunki literackie','la literatura','literatura'),
('Géneros Literarios','Gatunki literackie','el género literario','gatunek literacki'),
('Géneros Literarios','Gatunki literackie','la novela','powieść'),
('Géneros Literarios','Gatunki literackie','la novela histórica','powieść historyczna'),
('Géneros Literarios','Gatunki literackie','la novela policíaca','powieść kryminalna'),
('Géneros Literarios','Gatunki literackie','la novela romántica','romans'),
('Géneros Literarios','Gatunki literackie','la ciencia ficción','science fiction'),
('Géneros Literarios','Gatunki literackie','la fantasía','fantasy'),
('Géneros Literarios','Gatunki literackie','el cuento','opowiadanie / bajka'),
('Géneros Literarios','Gatunki literackie','el relato','opowiadanie / relacja'),
('Géneros Literarios','Gatunki literackie','la leyenda','legenda'),
('Géneros Literarios','Gatunki literackie','el mito','mit'),
('Géneros Literarios','Gatunki literackie','la fábula','bajka (ze zwierzętami i morałem)'),
('Géneros Literarios','Gatunki literackie','el poema','wiersz'),
('Géneros Literarios','Gatunki literackie','la poesía','poezja'),
('Géneros Literarios','Gatunki literackie','el poeta','poeta'),
('Géneros Literarios','Gatunki literackie','el drama','dramat'),
('Géneros Literarios','Gatunki literackie','la comedia','komedia'),
('Géneros Literarios','Gatunki literackie','la tragedia','tragedia'),
('Géneros Literarios','Gatunki literackie','el ensayo','esej'),
('Géneros Literarios','Gatunki literackie','la biografía','biografia'),
('Géneros Literarios','Gatunki literackie','la autobiografía','autobiografia'),
('Géneros Literarios','Gatunki literackie','el diario','dziennik / pamiętnik'),
('Géneros Literarios','Gatunki literackie','las memorias','wspomnienia'),
('Géneros Literarios','Gatunki literackie','la crónica','kronika'),
('Géneros Literarios','Gatunki literackie','el artículo','artykuł'),
('Géneros Literarios','Gatunki literackie','la prosa','proza'),
('Géneros Literarios','Gatunki literackie','el verso','wers / wiersz'),
('Géneros Literarios','Gatunki literackie','la estrofa','zwrotka'),
('Géneros Literarios','Gatunki literackie','la rima','rym'),
('Géneros Literarios','Gatunki literackie','la métrica','metryka / rytm'),
('Géneros Literarios','Gatunki literackie','el narrador','narrator'),
('Géneros Literarios','Gatunki literackie','el protagonista','główny bohater'),
('Géneros Literarios','Gatunki literackie','el antagonista','antagonista / wróg'),
('Géneros Literarios','Gatunki literackie','el personaje','postać'),
('Géneros Literarios','Gatunki literackie','la trama','fabuła / intryga'),
('Géneros Literarios','Gatunki literackie','el argumento','streszczenie / treść'),
('Géneros Literarios','Gatunki literackie','el clímax','punkt kulminacyjny'),
('Géneros Literarios','Gatunki literackie','el desenlace','zakończenie / rozwiązanie'),
('Géneros Literarios','Gatunki literackie','el diálogo','dialog'),
('Géneros Literarios','Gatunki literackie','el monólogo','monolog'),
('Géneros Literarios','Gatunki literackie','la metáfora','metafora'),
('Géneros Literarios','Gatunki literackie','la obra literaria','dzieło literackie'),
('Géneros Literarios','Gatunki literackie','el autor','autor'),
('Géneros Literarios','Gatunki literackie','el escritor','pisarz'),
('Géneros Literarios','Gatunki literackie','la editorial','wydawnictwo'),
('Géneros Literarios','Gatunki literackie','publicar','publikować'),
('Géneros Literarios','Gatunki literackie','el best seller','bestseller'),
('Géneros Literarios','Gatunki literackie','el capítulo','rozdział'),
('Géneros Literarios','Gatunki literackie','el índice','spis treści');
