insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Los Transportes','Transport','el transporte','transport'),
('Los Transportes','Transport','el vehículo','pojazd'),
('Los Transportes','Transport','el coche / el carro','samochód'),
('Los Transportes','Transport','el autobús','autobus'),
('Los Transportes','Transport','el tren','pociąg'),
('Los Transportes','Transport','el tranvía','tramwaj'),
('Los Transportes','Transport','el metro','metro'),
('Los Transportes','Transport','el avión','samolot'),
('Los Transportes','Transport','el helicóptero','helikopter'),
('Los Transportes','Transport','el barco','statek'),
('Los Transportes','Transport','el ferry','prom'),
('Los Transportes','Transport','la bicicleta','rower'),
('Los Transportes','Transport','la moto / la motocicleta','motocykl'),
('Los Transportes','Transport','el camión','ciężarówka'),
('Los Transportes','Transport','la furgoneta','furgonetka / van'),
('Los Transportes','Transport','el taxi','taksówka'),
('Los Transportes','Transport','el billete / el boleto','bilet'),
('Los Transportes','Transport','el pasaje','przejazd / bilet lotniczy'),
('Los Transportes','Transport','la estación','stacja / dworzec'),
('Los Transportes','Transport','la parada','przystanek'),
('Los Transportes','Transport','el aeropuerto','lotnisko'),
('Los Transportes','Transport','el puerto','port'),
('Los Transportes','Transport','el andén','peron'),
('Los Transportes','Transport','la vía','tor'),
('Los Transportes','Transport','volar','latać'),
('Los Transportes','Transport','conducir / manejar','prowadzić (pojazd)'),
('Los Transportes','Transport','montar','jeździć (np. na rowerze, konno)'),
('Los Transportes','Transport','navegar','żeglować / pływać'),
('Los Transportes','Transport','viajar','podróżować'),
('Los Transportes','Transport','el pasajero','pasażer'),
('Los Transportes','Transport','el conductor','kierowca'),
('Los Transportes','Transport','el piloto','pilot'),
('Los Transportes','Transport','el billete de ida','bilet w jedną stronę'),
('Los Transportes','Transport','el billete de ida y vuelta','bilet w obie strony'),
('Los Transportes','Transport','la taquilla','kasa biletowa'),
('Los Transportes','Transport','el equipaje','bagaż'),
('Los Transportes','Transport','la maleta','walizka'),
('Los Transportes','Transport','el tráfico','ruch drogowy'),
('Los Transportes','Transport','el atasco','korek drogowy'),
('Los Transportes','Transport','el semáforo','sygnalizacja świetlna'),
('Los Transportes','Transport','la autopista','autostrada'),
('Los Transportes','Transport','la carretera','szosa / droga'),
('Los Transportes','Transport','la calle','ulica'),
('Los Transportes','Transport','la velocidad','prędkość'),
('Los Transportes','Transport','frenar','hamować'),
('Los Transportes','Transport','acelerar','przyspieszać'),
('Los Transportes','Transport','aparcar','parkować'),
('Los Transportes','Transport','el garaje','garaż'),
('Los Transportes','Transport','la gasolina','benzyna'),
('Los Transportes','Transport','la multa','mandat'),
('La Tecnología','Technologia','la tecnología','technologia'),
('La Tecnología','Technologia','el ordenador / la computadora','komputer'),
('La Tecnología','Technologia','el portátil','laptop'),
('La Tecnología','Technologia','el teléfono móvil / el celular','telefon komórkowy'),
('La Tecnología','Technologia','la tableta','tablet'),
('La Tecnología','Technologia','la pantalla','ekran'),
('La Tecnología','Technologia','el teclado','klawiatura'),
('La Tecnología','Technologia','el ratón','myszka (komputerowa)'),
('La Tecnología','Technologia','el cable','kabel'),
('La Tecnología','Technologia','el cargador','ładowarka'),
('La Tecnología','Technologia','la batería','bateria'),
('La Tecnología','Technologia','el enchufe','wtyczka / gniazdko'),
('La Tecnología','Technologia','la red','sieć'),
('La Tecnología','Technologia','el wifi','wi-fi'),
('La Tecnología','Technologia','el internet','internet'),
('La Tecnología','Technologia','la página web','strona internetowa'),
('La Tecnología','Technologia','el correo electrónico','poczta elektroniczna (e-mail)'),
('La Tecnología','Technologia','la contraseña','hasło'),
('La Tecnología','Technologia','el usuario','użytkownik'),
('La Tecnología','Technologia','la aplicación / la app','aplikacja'),
('La Tecnología','Technologia','el software','oprogramowanie'),
('La Tecnología','Technologia','el hardware','sprzęt komputerowy'),
('La Tecnología','Technologia','el archivo','plik'),
('La Tecnología','Technologia','la carpeta','folder / teczka'),
('La Tecnología','Technologia','el enlace / el link','link / odnośnik'),
('La Tecnología','Technologia','el virus (informático)','wirus (komputerowy)'),
('La Tecnología','Technologia','el antivirus','antywirus'),
('La Tecnología','Technologia','descargar','pobierać (plik)'),
('La Tecnología','Technologia','subir','przesyłać / wgrywać'),
('La Tecnología','Technologia','guardar','zapisywać (plik)'),
('La Tecnología','Technologia','borrar','usuwać / kasować'),
('La Tecnología','Technologia','imprimir','drukować'),
('La Tecnología','Technologia','la impresora','drukarka'),
('La Tecnología','Technologia','el escáner','skaner'),
('La Tecnología','Technologia','los auriculares','słuchawki'),
('La Tecnología','Technologia','el altavoz','głośnik'),
('La Tecnología','Technologia','el micrófono','mikrofon'),
('La Tecnología','Technologia','la cámara','kamera / aparat'),
('La Tecnología','Technologia','el botón','przycisk'),
('La Tecnología','Technologia','encender','włączać'),
('La Tecnología','Technologia','apagar','wyłączać'),
('La Tecnología','Technologia','reiniciar','uruchamiać ponownie'),
('La Tecnología','Technologia','hacer clic','klikać'),
('La Tecnología','Technologia','navegar (por internet)','surfować (w internecie)'),
('La Tecnología','Technologia','el servidor','serwer'),
('La Tecnología','Technologia','el mensaje de texto','wiadomość tekstowa (SMS)'),
('La Tecnología','Technologia','el chat','czat'),
('La Tecnología','Technologia','la base de datos','baza danych'),
('La Tecnología','Technologia','programar','programować'),
('La Tecnología','Technologia','el código','kod'),
('Los Deportes','Sport','el deporte','sport'),
('Los Deportes','Sport','el equipo','drużyna'),
('Los Deportes','Sport','el jugador / la jugadora','gracz / zawodnik'),
('Los Deportes','Sport','el entrenador','trener'),
('Los Deportes','Sport','el árbitro','sędzia (sportowy)'),
('Los Deportes','Sport','el partido','mecz'),
('Los Deportes','Sport','el estadio','stadion'),
('Los Deportes','Sport','la cancha','boisko / kort'),
('Los Deportes','Sport','la pista','bieżnia / tor'),
('Los Deportes','Sport','el balón / la pelota','piłka'),
('Los Deportes','Sport','el fútbol','piłka nożna'),
('Los Deportes','Sport','el baloncesto','koszykówka'),
('Los Deportes','Sport','el voleibol','siatkówka'),
('Los Deportes','Sport','el tenis','tenis'),
('Los Deportes','Sport','el béisbol','baseball'),
('Los Deportes','Sport','el golf','golf'),
('Los Deportes','Sport','el rugby','rugby'),
('Los Deportes','Sport','el atletismo','lekkoatletyka'),
('Los Deportes','Sport','la natación','pływanie'),
('Los Deportes','Sport','el ciclismo','kolarstwo'),
('Los Deportes','Sport','el boxeo','boks'),
('Los Deportes','Sport','las artes marciales','sztuki walki'),
('Los Deportes','Sport','el esquí','narciarstwo'),
('Los Deportes','Sport','el patinaje','łyżwiarstwo / jazda na rolkach'),
('Los Deportes','Sport','la gimnasia','gimnastyka'),
('Los Deportes','Sport','el campeonato','mistrzostwa'),
('Los Deportes','Sport','la medalla','medal'),
('Los Deportes','Sport','el trofeo','trofeum'),
('Los Deportes','Sport','la copa','puchar'),
('Los Deportes','Sport','ganar','wygrywać'),
('Los Deportes','Sport','perder','przegrywać'),
('Los Deportes','Sport','empatar','remisować'),
('Los Deportes','Sport','el empate','remis'),
('Los Deportes','Sport','marcar (un gol)','strzelić (gola)'),
('Los Deportes','Sport','el gol','gol'),
('Los Deportes','Sport','el punto','punkt'),
('Los Deportes','Sport','la carrera','wyścig'),
('Los Deportes','Sport','correr','biegać'),
('Los Deportes','Sport','saltar','skakać'),
('Los Deportes','Sport','lanzar','rzucać'),
('Los Deportes','Sport','atrapar','łapać'),
('Los Deportes','Sport','entrenar','trenować'),
('Los Deportes','Sport','el entrenamiento','trening'),
('Los Deportes','Sport','el aficionado / el hincha','kibic'),
('Los Deportes','Sport','el uniforme','mundur / strój sportowy'),
('Los Deportes','Sport','la raqueta','rakieta (np. tenisowa)'),
('Los Deportes','Sport','el bate','kij (np. baseballowy)'),
('Los Deportes','Sport','la red','siatka (sportowa)'),
('Los Deportes','Sport','el casco','kask'),
('Los Deportes','Sport','la regla','zasada / reguła'),
('El Arte','Sztuka','el arte','sztuka'),
('El Arte','Sztuka','el artista','artysta'),
('El Arte','Sztuka','la obra de arte','dzieło sztuki'),
('El Arte','Sztuka','la pintura','malarstwo / obraz'),
('El Arte','Sztuka','el cuadro','obraz'),
('El Arte','Sztuka','el pintor / la pintora','malarz / malarka'),
('El Arte','Sztuka','el pincel','pędzel'),
('El Arte','Sztuka','la paleta','paleta'),
('El Arte','Sztuka','el lienzo','płótno'),
('El Arte','Sztuka','la escultura','rzeźba (dziedzina lub obiekt)'),
('El Arte','Sztuka','el escultor','rzeźbiarz'),
('El Arte','Sztuka','el mármol','marmur'),
('El Arte','Sztuka','la arcilla','glina'),
('El Arte','Sztuka','el dibujo','rysunek'),
('El Arte','Sztuka','el dibujante','rysownik'),
('El Arte','Sztuka','el lápiz','ołówek'),
('El Arte','Sztuka','el retrato','portret'),
('El Arte','Sztuka','el paisaje','pejzaż'),
('El Arte','Sztuka','el bodegón','martwa natura'),
('El Arte','Sztuka','la exposición','wystawa'),
('El Arte','Sztuka','la galería','galeria'),
('El Arte','Sztuka','el museo','muzeum'),
('El Arte','Sztuka','el marco','rama'),
('El Arte','Sztuka','la creatividad','kreatywność'),
('El Arte','Sztuka','la inspiración','inspiracja'),
('El Arte','Sztuka','el estilo','styl'),
('El Arte','Sztuka','clásico','klasyczny'),
('El Arte','Sztuka','moderno','nowoczesny'),
('El Arte','Sztuka','abstracto','abstrakcyjny'),
('El Arte','Sztuka','realista','realistyczny'),
('El Arte','Sztuka','el surrealismo','surrealizm'),
('El Arte','Sztuka','la acuarela','akwarela'),
('El Arte','Sztuka','el óleo','farba olejna'),
('El Arte','Sztuka','el boceto','szkic'),
('El Arte','Sztuka','diseñar','projektować'),
('El Arte','Sztuka','el diseño','projekt / design'),
('El Arte','Sztuka','el arquitecto','architekt'),
('El Arte','Sztuka','la arquitectura','architektura'),
('El Arte','Sztuka','el edificio','budynek'),
('El Arte','Sztuka','el monumento','zabytek / pomnik'),
('El Arte','Sztuka','la fotografía','fotografia'),
('El Arte','Sztuka','el fotógrafo','fotograf'),
('El Arte','Sztuka','la cámara fotográfica','aparat fotograficzny'),
('El Arte','Sztuka','capturar','uchwycić / sfotografować'),
('El Arte','Sztuka','el grabado','grawer / rycina'),
('El Arte','Sztuka','la cerámica','ceramika'),
('El Arte','Sztuka','el mosaico','mozaika'),
('El Arte','Sztuka','la simetría','symetria'),
('El Arte','Sztuka','la perspectiva','perspektywa'),
('El Arte','Sztuka','admirar','podziwiać');
