insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Vehículos','Pojazdy','el vehículo','pojazd'),
('Vehículos','Pojazdy','el coche','samochód'),
('Vehículos','Pojazdy','el automóvil','samochód (formalnie)'),
('Vehículos','Pojazdy','el autobús','autobus'),
('Vehículos','Pojazdy','el autocar','autokar'),
('Vehículos','Pojazdy','el camión','ciężarówka'),
('Vehículos','Pojazdy','la furgoneta','furgonetka / van'),
('Vehículos','Pojazdy','la camioneta','pick-up'),
('Vehículos','Pojazdy','el tren','pociąg'),
('Vehículos','Pojazdy','el tranvía','tramwaj'),
('Vehículos','Pojazdy','el metro','metro'),
('Vehículos','Pojazdy','el avión','samolot'),
('Vehículos','Pojazdy','el helicóptero','helikopter'),
('Vehículos','Pojazdy','el barco','statek'),
('Vehículos','Pojazdy','el buque','okręt / duży statek'),
('Vehículos','Pojazdy','el ferry','prom'),
('Vehículos','Pojazdy','la lancha','motorówka'),
('Vehículos','Pojazdy','el yate','jacht'),
('Vehículos','Pojazdy','el submarino','łódź podwodna'),
('Vehículos','Pojazdy','la bicicleta','rower'),
('Vehículos','Pojazdy','la motocicleta / la moto','motocykl'),
('Vehículos','Pojazdy','el ciclomotor','motorower'),
('Vehículos','Pojazdy','el patinete','hulajnoga'),
('Vehículos','Pojazdy','el patinete eléctrico','hulajnoga elektryczna'),
('Vehículos','Pojazdy','el monopatín','deskorolka'),
('Vehículos','Pojazdy','el tractor','traktor'),
('Vehículos','Pojazdy','la excavadora','koparka'),
('Vehículos','Pojazdy','la ambulancia','ambulans / karetka'),
('Vehículos','Pojazdy','el coche de policía','radiowóz'),
('Vehículos','Pojazdy','el camión de bomberos','wóz strażacki'),
('Vehículos','Pojazdy','el taxi','taksówka'),
('Vehículos','Pojazdy','el carro','wóz / bryczka'),
('Vehículos','Pojazdy','el trineo','sanie / sanki'),
('Vehículos','Pojazdy','el globo aerostático','balon na ogrzane powietrze'),
('Vehículos','Pojazdy','el teleférico','kolejka linowa'),
('Vehículos','Pojazdy','el funicular','kolejka linowo-terenowa'),
('Vehículos','Pojazdy','el cohete','rakieta'),
('Vehículos','Pojazdy','la nave espacial','statek kosmiczny'),
('Vehículos','Pojazdy','el triciclo','rower trójkołowy'),
('Vehículos','Pojazdy','el remolque','przyczepa'),
('Vehículos','Pojazdy','la caravana','przyczepa kempingowa'),
('Vehículos','Pojazdy','la autocaravana','kamper'),
('Vehículos','Pojazdy','el vehículo todoterreno','samochód terenowy (4x4)'),
('Vehículos','Pojazdy','el quad','quad'),
('Vehículos','Pojazdy','el transporte público','transport publiczny'),
('Vehículos','Pojazdy','el transporte privado','transport prywatny'),
('Vehículos','Pojazdy','el velero','żaglówka'),
('Vehículos','Pojazdy','el bote','łódka'),
('Vehículos','Pojazdy','el coche deportivo','samochód sportowy'),
('Vehículos','Pojazdy','el crucero','statek wycieczkowy'),
('Partes de un Coche','Części samochodu','el motor','silnik'),
('Partes de un Coche','Części samochodu','el volante','kierownica'),
('Partes de un Coche','Części samochodu','la rueda','koło'),
('Partes de un Coche','Części samochodu','el neumático','opona'),
('Partes de un Coche','Części samochodu','el freno','hamulec'),
('Partes de un Coche','Części samochodu','el acelerador','pedał gazu'),
('Partes de un Coche','Części samochodu','el embrague','sprzęgło'),
('Partes de un Coche','Części samochodu','la marcha','bieg'),
('Partes de un Coche','Części samochodu','la caja de cambios','skrzynia biegów'),
('Partes de un Coche','Części samochodu','el parachoques','zderzak'),
('Partes de un Coche','Części samochodu','el capó','maska'),
('Partes de un Coche','Części samochodu','el maletero','bagażnik'),
('Partes de un Coche','Części samochodu','el parabrisas','szyba przednia'),
('Partes de un Coche','Części samochodu','el limpiaparabrisas','wycieraczka'),
('Partes de un Coche','Części samochodu','la ventanilla','szyba (w oknie)'),
('Partes de un Coche','Części samochodu','el espejo retrovisor','lusterko wsteczne'),
('Partes de un Coche','Części samochodu','el espejo lateral','lusterko boczne'),
('Partes de un Coche','Części samochodu','el faro','reflektor'),
('Partes de un Coche','Części samochodu','la luz intermitente','kierunkowskaz'),
('Partes de un Coche','Części samochodu','la matrícula','tablica rejestracyjna'),
('Partes de un Coche','Części samochodu','el tubo de escape','rura wydechowa'),
('Partes de un Coche','Części samochodu','la bocina / el claxon','klakson'),
('Partes de un Coche','Części samochodu','el asiento','siedzenie'),
('Partes de un Coche','Części samochodu','el cinturón de seguridad','pas bezpieczeństwa'),
('Partes de un Coche','Części samochodu','el airbag','poduszka powietrzna'),
('Partes de un Coche','Części samochodu','el salpicadero','deska rozdzielcza'),
('Partes de un Coche','Części samochodu','el velocímetro','prędkościomierz'),
('Partes de un Coche','Części samochodu','el depósito de gasolina','bak paliwa'),
('Partes de un Coche','Części samochodu','la batería','akumulator'),
('Partes de un Coche','Części samochodu','la bujía','świeca zapłonowa'),
('Partes de un Coche','Części samochodu','el radiador','chłodnica'),
('Partes de un Coche','Części samochodu','la suspensión','zawieszenie'),
('Partes de un Coche','Części samochodu','el amortiguador','amortyzator'),
('Partes de un Coche','Części samochodu','el eje','oś'),
('Partes de un Coche','Części samochodu','la puerta','drzwi'),
('Partes de un Coche','Części samochodu','la manilla','klamka'),
('Partes de un Coche','Części samochodu','la cerradura','zamek (w drzwiach)'),
('Partes de un Coche','Części samochodu','la llave','kluczyk'),
('Partes de un Coche','Części samochodu','el pedal','pedał'),
('Partes de un Coche','Części samochodu','la palanca de cambios','dźwignia zmiany biegów'),
('Partes de un Coche','Części samochodu','el freno de mano','hamulec ręczny'),
('Partes de un Coche','Części samochodu','el asiento trasero','tylne siedzenie'),
('Partes de un Coche','Części samochodu','el techo','dach'),
('Partes de un Coche','Części samochodu','la antena','antena'),
('Partes de un Coche','Części samochodu','el tapacubos','kołpak'),
('Partes de un Coche','Części samochodu','el chasis','podwozie / rama'),
('Partes de un Coche','Części samochodu','la guantera','schowek (przed pasażerem)'),
('Partes de un Coche','Części samochodu','el reposacabezas','zagłówek'),
('Partes de un Coche','Części samochodu','el cuentakilómetros','licznik przebiegu'),
('Partes de un Coche','Części samochodu','el maletero de techo','bagażnik dachowy'),
('Tráfico','Ruch drogowy','el tráfico','ruch drogowy'),
('Tráfico','Ruch drogowy','la circulación','ruch / obieg'),
('Tráfico','Ruch drogowy','el atasco','korek drogowy'),
('Tráfico','Ruch drogowy','la calle','ulica'),
('Tráfico','Ruch drogowy','la carretera','droga / szosa'),
('Tráfico','Ruch drogowy','la autopista','autostrada'),
('Tráfico','Ruch drogowy','la autovía','droga ekspresowa'),
('Tráfico','Ruch drogowy','el carril','pas ruchu'),
('Tráfico','Ruch drogowy','el carril bici','ścieżka rowerowa'),
('Tráfico','Ruch drogowy','la acera','chodnik'),
('Tráfico','Ruch drogowy','el cruce','skrzyżowanie'),
('Tráfico','Ruch drogowy','la rotonda','rondo'),
('Tráfico','Ruch drogowy','el semáforo','sygnalizacja świetlna'),
('Tráfico','Ruch drogowy','el paso de cebra','przejście dla pieszych'),
('Tráfico','Ruch drogowy','la señal de tráfico','znak drogowy'),
('Tráfico','Ruch drogowy','el límite de velocidad','ograniczenie prędkości'),
('Tráfico','Ruch drogowy','la velocidad','prędkość'),
('Tráfico','Ruch drogowy','el peatón','pieszy'),
('Tráfico','Ruch drogowy','el conductor','kierowca'),
('Tráfico','Ruch drogowy','el ciclista','rowerzysta'),
('Tráfico','Ruch drogowy','el pasajero','pasażer'),
('Tráfico','Ruch drogowy','el accidente','wypadek'),
('Tráfico','Ruch drogowy','el choque','zderzenie'),
('Tráfico','Ruch drogowy','atropellar','potrącić'),
('Tráfico','Ruch drogowy','la multa','mandat'),
('Tráfico','Ruch drogowy','el peaje','myto / bramki na autostradzie'),
('Tráfico','Ruch drogowy','el aparcamiento','parking'),
('Tráfico','Ruch drogowy','aparcar','parkować'),
('Tráfico','Ruch drogowy','la grúa','laweta'),
('Tráfico','Ruch drogowy','el policía de tráfico','policjant drogówki'),
('Tráfico','Ruch drogowy','la infracción','wykroczenie'),
('Tráfico','Ruch drogowy','el carnet de conducir','prawo jazdy'),
('Tráfico','Ruch drogowy','el sentido','kierunek ruchu'),
('Tráfico','Ruch drogowy','la dirección','kierunek / adres'),
('Tráfico','Ruch drogowy','la ruta','trasa'),
('Tráfico','Ruch drogowy','el desvío','objazd'),
('Tráfico','Ruch drogowy','la curva','zakręt'),
('Tráfico','Ruch drogowy','adelantar','wyprzedzać'),
('Tráfico','Ruch drogowy','frenar','hamować'),
('Tráfico','Ruch drogowy','acelerar','przyspieszać'),
('Tráfico','Ruch drogowy','ceder el paso','ustąpić pierwszeństwa'),
('Tráfico','Ruch drogowy','la prioridad','pierwszeństwo'),
('Tráfico','Ruch drogowy','la señal de stop','znak stop'),
('Tráfico','Ruch drogowy','el peligro','niebezpieczeństwo'),
('Tráfico','Ruch drogowy','el badén','próg zwalniający'),
('Tráfico','Ruch drogowy','la zona peatonal','strefa dla pieszych'),
('Tráfico','Ruch drogowy','el puente','most'),
('Tráfico','Ruch drogowy','el túnel','tunel'),
('Tráfico','Ruch drogowy','el viandante','przechodzień'),
('Tráfico','Ruch drogowy','la calzada','jezdnia'),
('En el Tren','W pociągu','el tren','pociąg'),
('En el Tren','W pociągu','la estación de tren','stacja kolejowa'),
('En el Tren','W pociągu','el andén','peron'),
('En el Tren','W pociągu','la vía','tor'),
('En el Tren','W pociągu','el billete','bilet'),
('En el Tren','W pociągu','el billete de ida','bilet w jedną stronę'),
('En el Tren','W pociągu','el billete de ida y vuelta','bilet w obie strony'),
('En el Tren','W pociągu','la taquilla','kasa biletowa'),
('En el Tren','W pociągu','la máquina expendedora','automat biletowy'),
('En el Tren','W pociągu','el horario','rozkład jazdy'),
('En el Tren','W pociągu','la pantalla','tablica odjazdów / ekran'),
('En el Tren','W pociągu','el destino','miejsce docelowe'),
('En el Tren','W pociągu','la salida','odjazd'),
('En el Tren','W pociągu','la llegada','przyjazd'),
('En el Tren','W pociągu','el retraso','opóźnienie'),
('En el Tren','W pociągu','el pasajero','pasażer'),
('En el Tren','W pociągu','el revisor','konduktor / rewizor'),
('En el Tren','W pociągu','el maquinista','maszynista'),
('En el Tren','W pociągu','el vagón','wagon'),
('En el Tren','W pociągu','el coche cama','wagon sypialny'),
('En el Tren','W pociągu','el coche comedor','wagon restauracyjny'),
('En el Tren','W pociągu','el asiento','siedzenie'),
('En el Tren','W pociągu','la ventanilla','okno (w pociągu)'),
('En el Tren','W pociągu','el pasillo','korytarz'),
('En el Tren','W pociągu','el portaequipajes','półka na bagaż'),
('En el Tren','W pociągu','la maleta','walizka'),
('En el Tren','W pociągu','el transbordo','przesiadka'),
('En el Tren','W pociągu','hacer transbordo','przesiadać się'),
('En el Tren','W pociągu','directo','bezpośredni (pociąg)'),
('En el Tren','W pociągu','el tren de alta velocidad','pociąg dużych prędkości'),
('En el Tren','W pociągu','el tren de cercanías','pociąg podmiejski'),
('En el Tren','W pociągu','el metro','metro'),
('En el Tren','W pociągu','el tranvía','tramwaj'),
('En el Tren','W pociągu','el silbato','gwizdek'),
('En el Tren','W pociągu','subir','wsiadać'),
('En el Tren','W pociągu','bajar','wysiadać'),
('En el Tren','W pociągu','reservar','rezerwować'),
('En el Tren','W pociągu','la reserva','rezerwacja'),
('En el Tren','W pociągu','el número de asiento','numer siedzenia'),
('En el Tren','W pociągu','el coche de pasajeros','wagon pasażerski'),
('En el Tren','W pociągu','la primera clase','pierwsza klasa'),
('En el Tren','W pociągu','la segunda clase','druga klasa'),
('En el Tren','W pociągu','el descuento','zniżka'),
('En el Tren','W pociągu','validar','kasować / zatwierdzać (bilet)'),
('En el Tren','W pociągu','la consigna','przechowalnia bagażu'),
('En el Tren','W pociągu','viajar','podróżować'),
('En el Tren','W pociągu','el viaje','podróż'),
('En el Tren','W pociągu','puntual','punktualny'),
('En el Tren','W pociągu','el equipaje','bagaż'),
('En el Tren','W pociągu','la estación de término','stacja końcowa');
