insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('El Dormitorio','Sypialnia','el dormitorio','sypialnia'),
('El Dormitorio','Sypialnia','la cama','łóżko'),
('El Dormitorio','Sypialnia','el colchón','materac'),
('El Dormitorio','Sypialnia','la almohada','poduszka (do spania)'),
('El Dormitorio','Sypialnia','la sábana','prześcieradło'),
('El Dormitorio','Sypialnia','la manta','koc'),
('El Dormitorio','Sypialnia','el edredón','kołdra'),
('El Dormitorio','Sypialnia','la funda','poszewka'),
('El Dormitorio','Sypialnia','el cabecero','wezgłowie'),
('El Dormitorio','Sypialnia','la mesita de noche','stolik nocny'),
('El Dormitorio','Sypialnia','la lámpara','lampa'),
('El Dormitorio','Sypialnia','el despertador','budzik'),
('El Dormitorio','Sypialnia','el armario','szafa'),
('El Dormitorio','Sypialnia','la percha','wieszak (do szafy)'),
('El Dormitorio','Sypialnia','la cómoda','komoda'),
('El Dormitorio','Sypialnia','el cajón','szuflada'),
('El Dormitorio','Sypialnia','el espejo','lustro'),
('El Dormitorio','Sypialnia','la alfombra','dywan'),
('El Dormitorio','Sypialnia','la cortina','zasłona'),
('El Dormitorio','Sypialnia','la persiana','roleta / żaluzja'),
('El Dormitorio','Sypialnia','la ventana','okno'),
('El Dormitorio','Sypialnia','la puerta','drzwi'),
('El Dormitorio','Sypialnia','el interruptor','włącznik'),
('El Dormitorio','Sypialnia','el enchufe','gniazdko'),
('El Dormitorio','Sypialnia','el techo','sufit'),
('El Dormitorio','Sypialnia','el suelo','podłoga'),
('El Dormitorio','Sypialnia','la pared','ściana'),
('El Dormitorio','Sypialnia','el pijama','piżama'),
('El Dormitorio','Sypialnia','el camisón','koszula nocna'),
('El Dormitorio','Sypialnia','las zapatillas de casa','kapcie'),
('El Dormitorio','Sypialnia','dormir','spać'),
('El Dormitorio','Sypialnia','despertar','budzić (się)'),
('El Dormitorio','Sypialnia','roncar','chrapać'),
('El Dormitorio','Sypialnia','soñar','śnić / marzyć'),
('El Dormitorio','Sypialnia','el sueño','sen'),
('El Dormitorio','Sypialnia','la pesadilla','koszmar'),
('El Dormitorio','Sypialnia','descansar','odpoczywać'),
('El Dormitorio','Sypialnia','hacer la cama','ścielić łóżko'),
('El Dormitorio','Sypialnia','deshacer la cama','rozkładać łóżko'),
('El Dormitorio','Sypialnia','la cuna','łóżeczko dziecięce'),
('El Dormitorio','Sypialnia','la litera','łóżko piętrowe'),
('El Dormitorio','Sypialnia','el cojín','poduszka (dekoracyjna)'),
('El Dormitorio','Sypialnia','la colcha','narzuta'),
('El Dormitorio','Sypialnia','el tocador','toaletka'),
('El Dormitorio','Sypialnia','el joyero','szkatułka na biżuterię'),
('El Dormitorio','Sypialnia','la ropa de cama','pościel'),
('El Dormitorio','Sypialnia','apagar la luz','gasić światło'),
('El Dormitorio','Sypialnia','encender la luz','zapalać światło'),
('El Dormitorio','Sypialnia','el insomnio','bezsenność'),
('El Dormitorio','Sypialnia','madrugar','wstawać wcześnie'),
('El Salón','Salon','el salón','salon'),
('El Salón','Salon','la sala de estar','pokój dzienny'),
('El Salón','Salon','el sofá','kanapa'),
('El Salón','Salon','el sillón','fotel'),
('El Salón','Salon','la butaca','fotel (wypoczynkowy/teatralny)'),
('El Salón','Salon','la mesa de centro','stolik kawowy'),
('El Salón','Salon','el mueble','mebel'),
('El Salón','Salon','la estantería','regał'),
('El Salón','Salon','la televisión / la tele','telewizor / telewizja'),
('El Salón','Salon','el mando a distancia','pilot'),
('El Salón','Salon','la alfombra','dywan'),
('El Salón','Salon','la cortina','zasłona'),
('El Salón','Salon','el cuadro','obraz'),
('El Salón','Salon','el póster','plakat'),
('El Salón','Salon','el jarrón','wazon'),
('El Salón','Salon','la planta','roślina'),
('El Salón','Salon','el cojín','poduszka (ozdobna)'),
('El Salón','Salon','la chimenea','kominek'),
('El Salón','Salon','la leña','drewno na opał'),
('El Salón','Salon','el fuego','ogień'),
('El Salón','Salon','la lámpara de pie','lampa stojąca'),
('El Salón','Salon','la lámpara de techo','lampa sufitowa'),
('El Salón','Salon','sentarse','siadać'),
('El Salón','Salon','descansar','odpoczywać'),
('El Salón','Salon','ver la tele','oglądać telewizję'),
('El Salón','Salon','charlar','rozmawiać / gadać'),
('El Salón','Salon','el reposabrazos','podłokietnik'),
('El Salón','Salon','el respaldo','oparcie'),
('El Salón','Salon','el puf / el puff','pufa'),
('El Salón','Salon','la vitrina','witryna (mebel)'),
('El Salón','Salon','el reloj de pared','zegar ścienny'),
('El Salón','Salon','la decoración','dekoracja'),
('El Salón','Salon','decorar','dekorować'),
('El Salón','Salon','el cenicero','popielniczka'),
('El Salón','Salon','el radiador','kaloryfer'),
('El Salón','Salon','el aire acondicionado','klimatyzacja'),
('El Salón','Salon','el ventilador','wentylator'),
('El Salón','Salon','la revista','magazyn / czasopismo'),
('El Salón','Salon','el periódico','gazeta'),
('El Salón','Salon','la mesa de comedor','stół w jadalni'),
('El Salón','Salon','la silla','krzesło'),
('El Salón','Salon','la manta','koc (na kanapę)'),
('El Salón','Salon','la pantalla','ekran'),
('El Salón','Salon','el equipo de música','wieża stereo'),
('El Salón','Salon','el altavoz','głośnik'),
('El Salón','Salon','acogedor','przytulny'),
('El Salón','Salon','amplio','przestronny'),
('El Salón','Salon','el sofá cama','sofa rozkładana'),
('El Salón','Salon','recibir visitas','przyjmować gości'),
('El Salón','Salon','el rincón','kąt / róg (pokoju)'),
('Limpieza del Hogar','Sprzątanie domu','la limpieza','sprzątanie'),
('Limpieza del Hogar','Sprzątanie domu','limpiar','czyścić / sprzątać'),
('Limpieza del Hogar','Sprzątanie domu','ensuciar','brudzić'),
('Limpieza del Hogar','Sprzątanie domu','barrer','zamiatać'),
('Limpieza del Hogar','Sprzątanie domu','la escoba','miotła'),
('Limpieza del Hogar','Sprzątanie domu','el recogedor','szufelka'),
('Limpieza del Hogar','Sprzątanie domu','fregar','myć (podłogę/naczynia)'),
('Limpieza del Hogar','Sprzątanie domu','la fregona','mop'),
('Limpieza del Hogar','Sprzątanie domu','el cubo','wiadro'),
('Limpieza del Hogar','Sprzątanie domu','el agua','woda'),
('Limpieza del Hogar','Sprzątanie domu','el jabón','mydło'),
('Limpieza del Hogar','Sprzątanie domu','el detergente','detergent'),
('Limpieza del Hogar','Sprzątanie domu','la lejía','wybielacz'),
('Limpieza del Hogar','Sprzątanie domu','el desinfectante','środek dezynfekujący'),
('Limpieza del Hogar','Sprzątanie domu','el estropajo','druciak / szorstka gąbka'),
('Limpieza del Hogar','Sprzątanie domu','la bayeta / el trapo','ścierka'),
('Limpieza del Hogar','Sprzątanie domu','la esponja','gąbka'),
('Limpieza del Hogar','Sprzątanie domu','aspirar','odkurzać'),
('Limpieza del Hogar','Sprzątanie domu','la aspiradora','odkurzacz'),
('Limpieza del Hogar','Sprzątanie domu','el polvo','kurz'),
('Limpieza del Hogar','Sprzątanie domu','quitar el polvo','ścierać kurz'),
('Limpieza del Hogar','Sprzątanie domu','el plumero','miotelka do kurzu'),
('Limpieza del Hogar','Sprzątanie domu','planchar','prasować'),
('Limpieza del Hogar','Sprzątanie domu','la plancha','żelazko'),
('Limpieza del Hogar','Sprzątanie domu','la tabla de planchar','deska do prasowania'),
('Limpieza del Hogar','Sprzątanie domu','lavar','myć / prać'),
('Limpieza del Hogar','Sprzątanie domu','la lavadora','pralka'),
('Limpieza del Hogar','Sprzątanie domu','tender la ropa','rozwieszać pranie'),
('Limpieza del Hogar','Sprzątanie domu','la pinza','klammerka (do prania)'),
('Limpieza del Hogar','Sprzątanie domu','el tendedero','suszarka na pranie (stojak)'),
('Limpieza del Hogar','Sprzątanie domu','secar','suszyć'),
('Limpieza del Hogar','Sprzątanie domu','la secadora','suszarka (do ubrań)'),
('Limpieza del Hogar','Sprzątanie domu','el lavavajillas','zmywarka'),
('Limpieza del Hogar','Sprzątanie domu','la basura','śmieci'),
('Limpieza del Hogar','Sprzątanie domu','el cubo de basura','kosz na śmieci'),
('Limpieza del Hogar','Sprzątanie domu','reciclar','recyklingować'),
('Limpieza del Hogar','Sprzątanie domu','la bolsa de basura','worek na śmieci'),
('Limpieza del Hogar','Sprzątanie domu','ordenar','porządkować'),
('Limpieza del Hogar','Sprzątanie domu','recoger','zbierać / sprzątać'),
('Limpieza del Hogar','Sprzątanie domu','el desorden','bałagan'),
('Limpieza del Hogar','Sprzątanie domu','el orden','porządek'),
('Limpieza del Hogar','Sprzątanie domu','sucio','brudny'),
('Limpieza del Hogar','Sprzątanie domu','limpio','czysty'),
('Limpieza del Hogar','Sprzątanie domu','manchar','plamić'),
('Limpieza del Hogar','Sprzątanie domu','la mancha','plama'),
('Limpieza del Hogar','Sprzątanie domu','el quitamanchas','odplamiacz'),
('Limpieza del Hogar','Sprzątanie domu','ventilar','wietrzyć'),
('Limpieza del Hogar','Sprzątanie domu','el cristal','szyba / szkło'),
('Limpieza del Hogar','Sprzątanie domu','el limpiacristales','płyn do szyb'),
('Limpieza del Hogar','Sprzątanie domu','el cepillo','szczotka'),
('Mascotas','Zwierzęta domowe','la mascota','zwierzę domowe'),
('Mascotas','Zwierzęta domowe','el perro','pies'),
('Mascotas','Zwierzęta domowe','el gato','kot'),
('Mascotas','Zwierzęta domowe','el cachorro','szczeniak / młode'),
('Mascotas','Zwierzęta domowe','el gatito','kociak'),
('Mascotas','Zwierzęta domowe','ladrar','szczekać'),
('Mascotas','Zwierzęta domowe','maullar','miauczeć'),
('Mascotas','Zwierzęta domowe','morder','gryźć'),
('Mascotas','Zwierzęta domowe','arañar','drapać'),
('Mascotas','Zwierzęta domowe','el collar','obroża'),
('Mascotas','Zwierzęta domowe','la correa','smycz'),
('Mascotas','Zwierzęta domowe','el bozal','kaganiec'),
('Mascotas','Zwierzęta domowe','el hueso','kość'),
('Mascotas','Zwierzęta domowe','el pienso','sucha karma'),
('Mascotas','Zwierzęta domowe','el comedero','miska na jedzenie'),
('Mascotas','Zwierzęta domowe','el bebedero','miska na wodę'),
('Mascotas','Zwierzęta domowe','la cama','legowisko'),
('Mascotas','Zwierzęta domowe','la jaula','klatka'),
('Mascotas','Zwierzęta domowe','el pájaro','ptak'),
('Mascotas','Zwierzęta domowe','el loro','papuga'),
('Mascotas','Zwierzęta domowe','el canario','kanarek'),
('Mascotas','Zwierzęta domowe','el pez','rybka'),
('Mascotas','Zwierzęta domowe','el acuario / la pecera','akwarium'),
('Mascotas','Zwierzęta domowe','el hámster','chomik'),
('Mascotas','Zwierzęta domowe','la cobaya','świnka morska'),
('Mascotas','Zwierzęta domowe','el conejo','królik'),
('Mascotas','Zwierzęta domowe','el ratón','mysz'),
('Mascotas','Zwierzęta domowe','la tortuga','żółw'),
('Mascotas','Zwierzęta domowe','el lagarto','jaszczurka'),
('Mascotas','Zwierzęta domowe','la serpiente','wąż'),
('Mascotas','Zwierzęta domowe','el veterinario','weterynarz'),
('Mascotas','Zwierzęta domowe','la vacuna','szczepionka'),
('Mascotas','Zwierzęta domowe','vacunar','szczepić'),
('Mascotas','Zwierzęta domowe','acariciar','głaskać'),
('Mascotas','Zwierzęta domowe','el pelo','sierść / włosy'),
('Mascotas','Zwierzęta domowe','soltar pelo','gubić sierść / linieć'),
('Mascotas','Zwierzęta domowe','cepillar','szczotkować'),
('Mascotas','Zwierzęta domowe','pasear (al perro)','wyprowadzać (psa)'),
('Mascotas','Zwierzęta domowe','el juguete','zabawka'),
('Mascotas','Zwierzęta domowe','la arena (para gatos)','żwirek (dla kotów)'),
('Mascotas','Zwierzęta domowe','el arenero','kuweta'),
('Mascotas','Zwierzęta domowe','la pulga','pchła'),
('Mascotas','Zwierzęta domowe','la garrapata','kleszcz'),
('Mascotas','Zwierzęta domowe','el microchip','czip'),
('Mascotas','Zwierzęta domowe','la raza','rasa'),
('Mascotas','Zwierzęta domowe','de pura raza','rasowy'),
('Mascotas','Zwierzęta domowe','el mestizo','kundel / mieszaniec'),
('Mascotas','Zwierzęta domowe','adoptar','adoptować'),
('Mascotas','Zwierzęta domowe','la adopción','adopcja'),
('Mascotas','Zwierzęta domowe','domesticar','oswoić');
