insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Ropa de Verano','Ubrania letnie','el verano','lato'),
('Ropa de Verano','Ubrania letnie','el calor','upał / gorąco'),
('Ropa de Verano','Ubrania letnie','la camiseta','koszulka / t-shirt'),
('Ropa de Verano','Ubrania letnie','el tirante','ramiączko'),
('Ropa de Verano','Ubrania letnie','la camiseta de tirantes','koszulka na ramiączkach / top'),
('Ropa de Verano','Ubrania letnie','el top','krótki top'),
('Ropa de Verano','Ubrania letnie','el pantalón corto','krótkie spodenki'),
('Ropa de Verano','Ubrania letnie','las bermudas','bermudy'),
('Ropa de Verano','Ubrania letnie','el vestido','sukienka'),
('Ropa de Verano','Ubrania letnie','el vestido de verano','letnia sukienka'),
('Ropa de Verano','Ubrania letnie','la falda','spódnica'),
('Ropa de Verano','Ubrania letnie','el bañador','strój kąpielowy jednoczęściowy / kąpielówki'),
('Ropa de Verano','Ubrania letnie','el bikini','bikini'),
('Ropa de Verano','Ubrania letnie','las sandalias','sandały'),
('Ropa de Verano','Ubrania letnie','las chanclas','klapki / japonki'),
('Ropa de Verano','Ubrania letnie','las alpargatas','espadryle'),
('Ropa de Verano','Ubrania letnie','el sombrero','kapelusz'),
('Ropa de Verano','Ubrania letnie','la gorra','czapka z daszkiem'),
('Ropa de Verano','Ubrania letnie','las gafas de sol','okulary przeciwsłoneczne'),
('Ropa de Verano','Ubrania letnie','de lino','lniany'),
('Ropa de Verano','Ubrania letnie','el lino','len'),
('Ropa de Verano','Ubrania letnie','el algodón','bawełna'),
('Ropa de Verano','Ubrania letnie','la manga corta','krótki rękaw'),
('Ropa de Verano','Ubrania letnie','sin mangas','bez rękawów'),
('Ropa de Verano','Ubrania letnie','fresco','chłodny / przewiewny'),
('Ropa de Verano','Ubrania letnie','ligero','lekki'),
('Ropa de Verano','Ubrania letnie','sudar','pocić się'),
('Ropa de Verano','Ubrania letnie','la piscina','basen'),
('Ropa de Verano','Ubrania letnie','la playa','plaża'),
('Ropa de Verano','Ubrania letnie','el pareo','pareo / chusta plażowa'),
('Ropa de Verano','Ubrania letnie','el caftán','kaftan / tunika'),
('Ropa de Verano','Ubrania letnie','la blusa','bluzka'),
('Ropa de Verano','Ubrania letnie','la camisa de manga corta','koszula z krótkim rękawem'),
('Ropa de Verano','Ubrania letnie','los zapatos abiertos','odkryte buty'),
('Ropa de Verano','Ubrania letnie','el capazo','torba plażowa / koszyk'),
('Ropa de Verano','Ubrania letnie','la toalla','ręcznik (plażowy)'),
('Ropa de Verano','Ubrania letnie','el protector solar','krem z filtrem'),
('Ropa de Verano','Ubrania letnie','broncearse','opalać się'),
('Ropa de Verano','Ubrania letnie','nadar','pływać'),
('Ropa de Verano','Ubrania letnie','el traje de baño','strój kąpielowy'),
('Ropa de Verano','Ubrania letnie','la ropa ligera','lekka odzież'),
('Ropa de Verano','Ubrania letnie','descalzo','boso'),
('Ropa de Verano','Ubrania letnie','holgado','luźny (o ubraniu)'),
('Ropa de Verano','Ubrania letnie','ajustado','obcisły / dopasowany'),
('Ropa de Verano','Ubrania letnie','floreado','w kwiaty (wzór)'),
('Ropa de Verano','Ubrania letnie','el estampado','nadruk / wzór'),
('Ropa de Verano','Ubrania letnie','transpirable','oddychający (materiał)'),
('Ropa de Verano','Ubrania letnie','el abanico','wachlarz'),
('Ropa de Verano','Ubrania letnie','refrescar','chłodzić'),
('Ropa de Verano','Ubrania letnie','descubierto','odkryty'),
('Calzado','Obuwie','el calzado','obuwie'),
('Calzado','Obuwie','el zapato','but'),
('Calzado','Obuwie','los zapatos','buty'),
('Calzado','Obuwie','las zapatillas','trampki / tenisówki'),
('Calzado','Obuwie','las zapatillas de deporte','buty sportowe'),
('Calzado','Obuwie','los tenis','adidasy / buty sportowe'),
('Calzado','Obuwie','las botas','kozaki / buty wysokie'),
('Calzado','Obuwie','los botines','botki'),
('Calzado','Obuwie','las sandalias','sandały'),
('Calzado','Obuwie','las chanclas','klapki / japonki'),
('Calzado','Obuwie','los tacones','obcasy'),
('Calzado','Obuwie','los zapatos de tacón','buty na obcasie'),
('Calzado','Obuwie','los zapatos planos','płaskie buty'),
('Calzado','Obuwie','las bailarinas','baleriny'),
('Calzado','Obuwie','los mocasines','mokasyny'),
('Calzado','Obuwie','los zapatos de cordones','buty sznurowane'),
('Calzado','Obuwie','los zapatos de piel','buty skórzane'),
('Calzado','Obuwie','las alpargatas','espadryle'),
('Calzado','Obuwie','las pantuflas','kapcie'),
('Calzado','Obuwie','las botas de agua','kalosze'),
('Calzado','Obuwie','las botas de nieve','śniegowce'),
('Calzado','Obuwie','el cordón','sznurówka'),
('Calzado','Obuwie','atar','wiązać'),
('Calzado','Obuwie','desatar','rozwiązywać'),
('Calzado','Obuwie','la suela','podeszwa'),
('Calzado','Obuwie','el tacón','obcas'),
('Calzado','Obuwie','la punta','czubek (buta)'),
('Calzado','Obuwie','el empeine','podbicie'),
('Calzado','Obuwie','la plantilla','wkładka (do butów)'),
('Calzado','Obuwie','el betún','pasta do butów'),
('Calzado','Obuwie','limpiar los zapatos','czyścić buty / pastować'),
('Calzado','Obuwie','el zapatero','szewc'),
('Calzado','Obuwie','la zapatería','sklep obuwniczy'),
('Calzado','Obuwie','probarse','przymierzać'),
('Calzado','Obuwie','la talla','rozmiar (odzieży / butów ogólnie)'),
('Calzado','Obuwie','el número','rozmiar (buta)'),
('Calzado','Obuwie','calzar','nosić buty w rozmiarze...'),
('Calzado','Obuwie','apretar','uwierać / cisnąć'),
('Calzado','Obuwie','holgado','luźny'),
('Calzado','Obuwie','cómodo','wygodny'),
('Calzado','Obuwie','incómodo','niewygodny'),
('Calzado','Obuwie','de cuero','ze skóry'),
('Calzado','Obuwie','de ante','z zamszu'),
('Calzado','Obuwie','de tela','z materiału'),
('Calzado','Obuwie','caminar','chodzić'),
('Calzado','Obuwie','el roce','otarcie'),
('Calzado','Obuwie','la ampolla','pęcherz / bąbel (na skórze)'),
('Calzado','Obuwie','el calcetín','skarpetka'),
('Calzado','Obuwie','calzarse','wkładać buty'),
('Calzado','Obuwie','descalzarse','zdejmować buty'),
('Accesorios','Akcesoria','el accesorio','akcesorium / dodatek'),
('Accesorios','Akcesoria','el complemento','dodatek (do ubioru)'),
('Accesorios','Akcesoria','el cinturón','pasek'),
('Accesorios','Akcesoria','la corbata','krawat'),
('Accesorios','Akcesoria','la pajarita','mucha (do garnituru)'),
('Accesorios','Akcesoria','el pañuelo','chustka / apaszka'),
('Accesorios','Akcesoria','la bufanda','szalik'),
('Accesorios','Akcesoria','el guante','rękawiczka'),
('Accesorios','Akcesoria','el gorro','czapka'),
('Accesorios','Akcesoria','el sombrero','kapelusz'),
('Accesorios','Akcesoria','la gorra','czapka z daszkiem'),
('Accesorios','Akcesoria','el bolso','torebka'),
('Accesorios','Akcesoria','la cartera','portfel / teczka'),
('Accesorios','Akcesoria','el monedero','portmonetka'),
('Accesorios','Akcesoria','la mochila','plecak'),
('Accesorios','Akcesoria','el maletín','aktówka / walizeczka'),
('Accesorios','Akcesoria','la maleta','walizka'),
('Accesorios','Akcesoria','el paraguas','parasol'),
('Accesorios','Akcesoria','las gafas','okulary (korekcyjne)'),
('Accesorios','Akcesoria','las gafas de sol','okulary przeciwsłoneczne'),
('Accesorios','Akcesoria','el reloj','zegarek (na rękę)'),
('Accesorios','Akcesoria','el abanico','wachlarz'),
('Accesorios','Akcesoria','la joya','klejnot / biżuteria'),
('Accesorios','Akcesoria','el anillo','pierścionek'),
('Accesorios','Akcesoria','el collar','naszyjnik'),
('Accesorios','Akcesoria','la pulsera','bransoletka'),
('Accesorios','Akcesoria','el pendiente','kolczyk'),
('Accesorios','Akcesoria','el broche','broszka'),
('Accesorios','Akcesoria','el pasador','spinka (do włosów)'),
('Accesorios','Akcesoria','la diadema','opaska na włosy'),
('Accesorios','Akcesoria','la goma de pelo','gumka do włosów'),
('Accesorios','Akcesoria','de cuero','ze skóry'),
('Accesorios','Akcesoria','de seda','z jedwabiu'),
('Accesorios','Akcesoria','de oro','ze złota'),
('Accesorios','Akcesoria','de plata','ze srebra'),
('Accesorios','Akcesoria','de plástico','z plastiku'),
('Accesorios','Akcesoria','llevar','nosić'),
('Accesorios','Akcesoria','ponerse','zakładać (na siebie)'),
('Accesorios','Akcesoria','quitarse','zdejmować'),
('Accesorios','Akcesoria','combinar','pasować (o ubraniach) / łączyć'),
('Accesorios','Akcesoria','de moda','modny'),
('Accesorios','Akcesoria','pasado de moda','niemodny'),
('Accesorios','Akcesoria','elegante','elegancki'),
('Accesorios','Akcesoria','casual','nieformalny / casualowy'),
('Accesorios','Akcesoria','el adorno','ozdoba'),
('Accesorios','Akcesoria','el detalle','detal / szczegół'),
('Accesorios','Akcesoria','la hebilla','klamra (od paska)'),
('Accesorios','Akcesoria','el colgante','wisiorek'),
('Accesorios','Akcesoria','adornar','ozdabiać'),
('Accesorios','Akcesoria','regalar','dawać w prezencie'),
('Joyería','Biżuteria','la joyería','biżuteria / jubiler (sklep)'),
('Joyería','Biżuteria','el joyero','szkatułka na biżuterię / jubiler (zawód)'),
('Joyería','Biżuteria','la joya','klejnot / biżuteria'),
('Joyería','Biżuteria','el anillo','pierścionek'),
('Joyería','Biżuteria','la alianza','obrączka'),
('Joyería','Biżuteria','el collar','naszyjnik'),
('Joyería','Biżuteria','la pulsera','bransoletka'),
('Joyería','Biżuteria','el pendiente','kolczyk'),
('Joyería','Biżuteria','el aro','kolczyk w kształcie koła'),
('Joyería','Biżuteria','el broche','broszka'),
('Joyería','Biżuteria','el colgante','wisiorek'),
('Joyería','Biżuteria','la cadena','łańcuszek'),
('Joyería','Biżuteria','el diamante','diament'),
('Joyería','Biżuteria','la perla','perła'),
('Joyería','Biżuteria','el rubí','rubin'),
('Joyería','Biżuteria','la esmeralda','szmaragd'),
('Joyería','Biżuteria','el zafiro','szafir'),
('Joyería','Biżuteria','el cristal','kryształ'),
('Joyería','Biżuteria','el oro','złoto'),
('Joyería','Biżuteria','la plata','srebro'),
('Joyería','Biżuteria','el platino','platyna'),
('Joyería','Biżuteria','el cobre','miedź'),
('Joyería','Biżuteria','el acero inoxidable','stal nierdzewna'),
('Joyería','Biżuteria','la piedra preciosa','kamień szlachetny'),
('Joyería','Biżuteria','el reloj de pulsera','zegarek na rękę'),
('Joyería','Biżuteria','la corona','korona'),
('Joyería','Biżuteria','la tiara','tiara'),
('Joyería','Biżuteria','el camafeo','kamea'),
('Joyería','Biżuteria','el cierre','zapięcie'),
('Joyería','Biżuteria','el esmalte','emalia'),
('Joyería','Biżuteria','tallar','szlifować'),
('Joyería','Biżuteria','brillar','błyszczeć'),
('Joyería','Biżuteria','el brillo','blask'),
('Joyería','Biżuteria','valioso','wartościowy'),
('Joyería','Biżuteria','caro','drogi'),
('Joyería','Biżuteria','barato','tani'),
('Joyería','Biżuteria','antiguo','antyczny / zabytkowy'),
('Joyería','Biżuteria','moderno','nowoczesny'),
('Joyería','Biżuteria','heredar','odziedziczyć'),
('Joyería','Biżuteria','la herencia','spadek / pamiątka'),
('Joyería','Biżuteria','regalar','dawać w prezencie'),
('Joyería','Biżuteria','el quilate','karat'),
('Joyería','Biżuteria','auténtico','autentyczny / prawdziwy'),
('Joyería','Biżuteria','falso','sztuczny / fałszywy'),
('Joyería','Biżuteria','la bisutería','sztuczna biżuteria'),
('Joyería','Biżuteria','el diseñador','projektant'),
('Joyería','Biżuteria','el engaste','oprawa (kamienia)'),
('Joyería','Biżuteria','la gema','klejnot / gema'),
('Joyería','Biżuteria','el amuleto','amulet'),
('Joyería','Biżuteria','el talismán','talizman');
