insert into public.seed_catalog_v40_staging (categoria_es, categoria_pl, palabra_es, palabra_pl) values
('Biología','Biologia','la biología','biologia'),
('Biología','Biologia','la vida','życie'),
('Biología','Biologia','el organismo','organizm'),
('Biología','Biologia','la célula','komórka'),
('Biología','Biologia','el ADN','DNA'),
('Biología','Biologia','el ARN','RNA'),
('Biología','Biologia','el gen','gen'),
('Biología','Biologia','la genética','genetyka'),
('Biología','Biologia','la evolución','ewolucja'),
('Biología','Biologia','la especie','gatunek'),
('Biología','Biologia','el ecosistema','ekosystem'),
('Biología','Biologia','la biodiversidad','bioróżnorodność'),
('Biología','Biologia','el hábitat','siedlisko'),
('Biología','Biologia','la adaptación','adaptacja / przystosowanie'),
('Biología','Biologia','la selección natural','dobór naturalny'),
('Biología','Biologia','la anatomía','anatomia'),
('Biología','Biologia','la fisiología','fizjologia'),
('Biología','Biologia','el tejido','tkanka'),
('Biología','Biologia','el órgano','narząd / organ'),
('Biología','Biologia','el sistema','układ (np. krążenia, nerwowy)'),
('Biología','Biologia','la reproducción','rozmnażanie'),
('Biología','Biologia','el crecimiento','wzrost'),
('Biología','Biologia','la nutrición','odżywianie'),
('Biología','Biologia','el metabolismo','metabolizm'),
('Biología','Biologia','la fotosíntesis','fotosynteza'),
('Biología','Biologia','la bacteria','bakteria'),
('Biología','Biologia','el virus','wirus'),
('Biología','Biologia','el hongo','grzyb'),
('Biología','Biologia','la planta','roślina'),
('Biología','Biologia','el animal','zwierzę'),
('Biología','Biologia','la botánica','botanika'),
('Biología','Biologia','la zoología','zoologia'),
('Biología','Biologia','la microbiología','mikrobiologia'),
('Biología','Biologia','la ecología','ekologia'),
('Biología','Biologia','la zoología','zoologia'),
('Biología','Biologia','el fósil','skamieniałość'),
('Biología','Biologia','la extinción','wyginięcie'),
('Biología','Biologia','la clonación','klonowanie'),
('Biología','Biologia','la mutación','mutacja'),
('Biología','Biologia','el microscopio','mikroskop'),
('Biología','Biologia','la muestra','próbka'),
('Biología','Biologia','el espécimen','okaz'),
('Biología','Biologia','la membrana','błona komórkowa'),
('Biología','Biologia','el núcleo','jądro komórkowe'),
('Biología','Biologia','el citoplasma','cytoplazma'),
('Biología','Biologia','la enzima','enzym'),
('Biología','Biologia','la proteína','białko'),
('Biología','Biologia','el aminoácido','aminokwas'),
('Biología','Biologia','la simbiosis','symbioza'),
('Biología','Biologia','el parásito','pasożyt'),
('Matemáticas','Matematyka','las matemáticas','matematyka'),
('Matemáticas','Matematyka','el número','liczba / numer'),
('Matemáticas','Matematyka','la cifra','cyfra'),
('Matemáticas','Matematyka','la suma','suma / dodawanie'),
('Matemáticas','Matematyka','la resta','odejmowanie'),
('Matemáticas','Matematyka','la multiplicación','mnożenie'),
('Matemáticas','Matematyka','la división','dzielenie'),
('Matemáticas','Matematyka','sumar','dodawać'),
('Matemáticas','Matematyka','restar','odejmować'),
('Matemáticas','Matematyka','multiplicar','mnożyć'),
('Matemáticas','Matematyka','dividir','dzielić'),
('Matemáticas','Matematyka','el resultado','wynik'),
('Matemáticas','Matematyka','el total','całkowity / suma'),
('Matemáticas','Matematyka','la fracción','ułamek'),
('Matemáticas','Matematyka','el decimal','liczba dziesiętna'),
('Matemáticas','Matematyka','el porcentaje','procent'),
('Matemáticas','Matematyka','la ecuación','równanie'),
('Matemáticas','Matematyka','la fórmula','wzór'),
('Matemáticas','Matematyka','la variable','zmienna'),
('Matemáticas','Matematyka','la constante','stała'),
('Matemáticas','Matematyka','la geometría','geometria'),
('Matemáticas','Matematyka','el álgebra','algebra'),
('Matemáticas','Matematyka','el cálculo','rachunek / obliczenie'),
('Matemáticas','Matematyka','la trigonometria','trygonometria'),
('Matemáticas','Matematyka','la estadística','statystyka'),
('Matemáticas','Matematyka','la probabilidad','prawdopodobieństwo'),
('Matemáticas','Matematyka','el ángulo','kąt'),
('Matemáticas','Matematyka','el triángulo','trójkąt'),
('Matemáticas','Matematyka','el cuadrado','kwadrat'),
('Matemáticas','Matematyka','el círculo','koło'),
('Matemáticas','Matematyka','el rectángulo','prostokąt'),
('Matemáticas','Matematyka','el radio','promień'),
('Matemáticas','Matematyka','el diámetro','średnica'),
('Matemáticas','Matematyka','el perímetro','obwód'),
('Matemáticas','Matematyka','el área','pole powierzchni'),
('Matemáticas','Matematyka','el volumen','objętość'),
('Matemáticas','Matematyka','la raíz cuadrada','pierwiastek kwadratowy'),
('Matemáticas','Matematyka','la potencia','potęga'),
('Matemáticas','Matematyka','el exponente','wykładnik potęgi'),
('Matemáticas','Matematyka','la matriz','macierz'),
('Matemáticas','Matematyka','el vector','wektor'),
('Matemáticas','Matematyka','la función','funkcja'),
('Matemáticas','Matematyka','la derivada','pochodna'),
('Matemáticas','Matematyka','la integral','całka'),
('Matemáticas','Matematyka','el teorema','twierdzenie'),
('Matemáticas','Matematyka','la demostración','dowód'),
('Matemáticas','Matematyka','el infinito','nieskończoność'),
('Matemáticas','Matematyka','la lógica','logika'),
('Matemáticas','Matematyka','el gráfico','wykres'),
('Matemáticas','Matematyka','la tabla','tabela'),
('Historia Antigua','Historia starożytna','la historia antigua','historia starożytna'),
('Historia Antigua','Historia starożytna','la prehistoria','prehistoria'),
('Historia Antigua','Historia starożytna','la antigüedad','starożytność'),
('Historia Antigua','Historia starożytna','la civilización','cywilizacja'),
('Historia Antigua','Historia starożytna','el imperio','imperium'),
('Historia Antigua','Historia starożytna','el reino','królestwo'),
('Historia Antigua','Historia starożytna','la dinastía','dynastia'),
('Historia Antigua','Historia starożytna','el faraón','faraon'),
('Historia Antigua','Historia starożytna','el emperador','cesarz'),
('Historia Antigua','Historia starożytna','el rey','król'),
('Historia Antigua','Historia starożytna','la reina','królowa'),
('Historia Antigua','Historia starożytna','el esclavo','niewolnik'),
('Historia Antigua','Historia starożytna','la esclavitud','niewolnictwo'),
('Historia Antigua','Historia starożytna','el gladiador','gladiator'),
('Historia Antigua','Historia starożytna','el templo','świątynia'),
('Historia Antigua','Historia starożytna','la pirámide','piramida'),
('Historia Antigua','Historia starożytna','el monumento','pomnik / zabytek'),
('Historia Antigua','Historia starożytna','las ruinas','ruiny'),
('Historia Antigua','Historia starożytna','la mitología','mitologia'),
('Historia Antigua','Historia starożytna','el dios','bóg'),
('Historia Antigua','Historia starożytna','la diosa','bogini'),
('Historia Antigua','Historia starożytna','el mito','mit'),
('Historia Antigua','Historia starożytna','la leyenda','legenda'),
('Historia Antigua','Historia starożytna','la escritura','pismo'),
('Historia Antigua','Historia starożytna','el jeroglífico','hieroglif'),
('Historia Antigua','Historia starożytna','el papiro','papirus'),
('Historia Antigua','Historia starożytna','el pergamino','pergamin'),
('Historia Antigua','Historia starożytna','la arqueología','archeologia'),
('Historia Antigua','Historia starożytna','el arqueólogo','archeolog'),
('Historia Antigua','Historia starożytna','el fósil','skamieniałość'),
('Historia Antigua','Historia starożytna','la excavación','wykopaliska'),
('Historia Antigua','Historia starożytna','el tesoro','skarb'),
('Historia Antigua','Historia starożytna','la conquista','podbój'),
('Historia Antigua','Historia starożytna','conquistar','podbijać'),
('Historia Antigua','Historia starożytna','la batalla','bitwa'),
('Historia Antigua','Historia starożytna','la guerra','wojna'),
('Historia Antigua','Historia starożytna','el ejército','armia'),
('Historia Antigua','Historia starożytna','el soldado','żołnierza'),
('Historia Antigua','Historia starożytna','la espada','miecz'),
('Historia Antigua','Historia starożytna','el escudo','tarcza'),
('Historia Antigua','Historia starożytna','Grecia','Grecja'),
('Historia Antigua','Historia starożytna','Roma','Rzym'),
('Historia Antigua','Historia starożytna','Egipto','Egipt'),
('Historia Antigua','Historia starożytna','Mesopotamia','Mezopotamizacja / Mezopotamia'),
('Historia Antigua','Historia starożytna','Persia','Persja'),
('Historia Antigua','Historia starożytna','Esparta','Sparta'),
('Historia Antigua','Historia starożytna','Atenas','Ateny'),
('Historia Antigua','Historia starożytna','el coliseo','koloseum'),
('Historia Antigua','Historia starożytna','el senat','senat'),
('Historia Antigua','Historia starożytna','la república','republika'),
('Historia Moderna','Historia nowożytna','la historia moderna','historia nowożytna'),
('Historia Moderna','Historia nowożytna','la Edad Moderna','epoka nowożytna'),
('Historia Moderna','Historia nowożytna','el Renacimiento','renesans'),
('Historia Moderna','Historia nowożytna','el Humanismo','humanizm'),
('Historia Moderna','Historia nowożytna','el descubrimiento','odkrycie'),
('Historia Moderna','Historia nowożytna','el explorador','odkrywca / badacz'),
('Historia Moderna','Historia nowożytna','la colonización','kolonizacja'),
('Historia Moderna','Historia nowożytna','la colonia','kolonia'),
('Historia Moderna','Historia nowożytna','la conquista','podbój'),
('Historia Moderna','Historia nowożytna','el continente','kontynent'),
('Historia Moderna','Historia nowożytna','el Nuevo Mundo','Nowy Świat'),
('Historia Moderna','Historia nowożytna','la Reforma','reforma (religiosa)'),
('Historia Moderna','Historia nowożytna','el protestantismo','protestantyzm'),
('Historia Moderna','Historia nowożytna','la Contrarreforma','kontrreformacja'),
('Historia Moderna','Historia nowożytna','la monarquía absoluta','monarchia absolutna'),
('Historia Moderna','Historia nowożytna','el absolutismo','absolutyzm'),
('Historia Moderna','Historia nowożytna','la Revolución','rewolucja'),
('Historia Moderna','Historia nowożytna','la Revolución Industrial','rewolucja przemysłowa'),
('Historia Moderna','Historia nowożytna','la burguesía','burżuazja'),
('Historia Moderna','Historia nowożytna','el proletariado','proletariat'),
('Historia Moderna','Historia nowożytna','el capitalismo','kapitalizm'),
('Historia Moderna','Historia nowożytna','el mercantilismo','merkantylizm'),
('Historia Moderna','Historia nowożytna','la máquina de vapor','maszyna parowa'),
('Historia Moderna','Historia nowożytna','la imprenta','drukarnia'),
('Historia Moderna','Historia nowożytna','el telescopio','teleskop'),
('Historia Moderna','Historia nowożytna','la ilustración','oświecenie'),
('Historia Moderna','Historia nowożytna','la enciclopedia','encyklopedia'),
('Historia Moderna','Historia nowożytna','la independencia','niepodległość'),
('Historia Moderna','Historia nowożytna','la república','republika'),
('Historia Moderna','Historia nowożytna','la democracia','demokracja'),
('Historia Moderna','Historia nowożytna','el ciudadano','obywatel'),
('Historia Moderna','Historia nowożytna','los derechos humanos','prawa człowieka'),
('Historia Moderna','Historia nowożytna','la guillotina','gilotyna'),
('Historia Moderna','Historia nowożytna','el rey','król'),
('Historia Moderna','Historia nowożytna','la reina','królowa'),
('Historia Moderna','Historia nowożytna','la corte','dwór królewski'),
('Historia Moderna','Historia nowożytna','el palacio','pałac'),
('Historia Moderna','Historia nowożytna','la armada','flota wojenna'),
('Historia Moderna','Historia nowożytna','el tratado','traktat / umowa'),
('Historia Moderna','Historia nowożytna','la paz','pokój'),
('Historia Moderna','Historia nowożytna','la crisis','kryzys'),
('Historia Moderna','Historia nowożytna','la hambruna','głód'),
('Historia Moderna','Historia nowożytna','la peste','dżuma / zaraza'),
('Historia Moderna','Historia nowożytna','el siglo','wiek / stulecie'),
('Historia Moderna','Historia nowożytna','la época','epoka'),
('Historia Moderna','Historia nowożytna','el evento','wydarzenie'),
('Historia Moderna','Historia nowożytna','el cambio','zmiana'),
('Historia Moderna','Historia nowożytna','el progreso','postęp'),
('Historia Moderna','Historia nowożytna','la sociedad','społeczeństwo'),
('Historia Moderna','Historia nowożytna','la cultura','kultura');
